### ISSUE TITLE
Line and Wall length is slightly incorrect for Metric system

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#100]
see table in https://marklenser.com/rpg/themes/powers

Line and Wall lengths should be 4.5 meters per mana point spent. This is off by 0.5 or 1 meter in the table, in some places.

For example, a wall cast with 10 mana should be 45 meters long, not 46.

**Comment by mlenser** [comment]
Conversion starts to round to the nearest whole number after 10 and to the nearest 5 after 20... booo
