### ISSUE TITLE
In the list of 5e spell conversions chain lightning leads to a page not found

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1003]
**Describe the bug**
The conversion for chain lightning is listed as lightning but goes to page not found.

**Link**
Er more specifically the bad link is located here
https://www.kryxrpg.com/conversion/spells
And here is the bad link itself
https://www.kryxrpg.com/spells/lightning

**Comment by mlenser** [comment]
Lightning became Chain Lightning and Arc Lightning a while ago. Fixed.
