### ISSUE TITLE
Grammatical error in front page around ability scores 

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1004]
**Describe the bug**
Under agility scores it says:
Classes give ability increases and do so in a more **inclusive**, resulting in more rounded characters and allows for more diverse character options.

One needs an additional word after inclusive, for instance in an inclusive way or inclusive manner. One could alternatively say does so more inclusively.

**Link**
https://www.kryxrpg.com/

**Comment by Daniel-Soham** [comment]
Whoops made an error. Fixed it.

**Comment by mlenser** [comment]
Reworded

> Classes give ability increases to allow for more diverse character options.
