### ISSUE TITLE
Lucky feat not found from skills (various magic skills)

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1005]
**Describe the bug**
Under skills, in all the magic skills when it says you can attempt to identify a spell after which you can try various countering or boosting methods one of them is "lucky" which does not seem to exist.

**Link**
https://www.kryxrpg.com/rules/skills
https://www.kryxrpg.com/feats/lucky

**Comment by mlenser** [comment]
Fixed. Thanks!
