### ISSUE TITLE
Missing information on foraging 

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1006]
**Describe the bug**
In the description of the Wilderness skill it says:
Forage for food and water. As you travel at a normal or slow pace, you can gather food and water. The Difficulty is determined by the abundance of food and water in the region. See the “Foraging” section of Adventuring for more details.

Meanwhile the foraging section of adventuring merely says:
Foraging
Characters can gather food and water using the Wilderness skill

**Link**
https://www.kryxrpg.com/rules/skills#wilderness
https://www.kryxrpg.com/rules/adventuring#foraging

**Comment by mlenser** [comment]
I removed the reference to the adventuring section from Wilderness. So Adventuring refers to Wilderness.

The rules are fairly open-ended.
