### ISSUE TITLE
High mana spell information should also be in the spellcasting section.

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1008]
**Describe the bug**
I was trying to check on the general spellcasting rules for the rules about high mana cost spells like 4 and 5 cost ones and I couldn't find them. It's not bad to have them in the classes so a player can for the most part stay on their class info page, but they should also be with the general spellcasting rules. Probably right under augmenting. I haven't yet checked but if the rules are the same for stamina maneuvers and concoctions it would also make sense to put the information for their high cost limitations there too.

High mana spells
Spells using 4 or 5 mana are particularly taxing to cast. Once you cast a spell using 4 mana, you can’t cast another spell using 4 mana until you finish a short or long rest and once you cast a spell using 5 mana, you can’t cast another spell using 5 mana until you finish a long rest.

Also unclear is whether augmenting a spell to 4 or 5 mana counts as casting one of those high mana cost spells and thus restricts you.

**Link**
https://www.kryxrpg.com/rules/concoctions-maneuvers-and-spells#mana

**Comment by mlenser** [comment]
These rules only apply to PCs. They do not apply to creatures so they are only listed on the character pages.

> Also unclear is whether augmenting a spell to 4 or 5 mana counts as casting one of those high mana cost spells and thus restricts you.

Do these spells `use` 4 or 5 mana? 😉

> Spells **using** 4 or 5 mana

**Comment by mlenser** [comment]
> I haven't yet checked but if the rules are the same for stamina maneuvers and concoctions

The rule only applies to concoctions and spells, not maneuvers.

**Comment by Daniel-Soham** [comment]
Does a spell that requires an additional one mana per round take things to
4 mana or 5 mana? What if combined with an instantaneous 3 mana cost spells
(one on maintenance of the other spell, three on the new spell)? It seems
the thing that causes this mana burnout is not casting a high mana cost
spell but spending 4 or 5 mana via any method on your turn? Also one would
assume reactions are NOT part of that rule, even if cast on your own turn?

I just think the explanation of these rules could be a bit more unambiguous.

**Comment by mlenser** [comment]
> Does a spell that requires an additional one mana per round take things to 4 mana or 5 mana?

4 mana to cast and 1 mana each round does not mean it uses 5 mana. It means it uses 4 mana and then 1 mana. 2 separate events.

> What if combined with an instantaneous 3 mana cost spells (one on maintenance of the other spell, three on the new spell)?

2 separate events.

> It seems the thing that causes this mana burnout is not casting a high mana cost spell but spending 4 or 5 mana via any method on your turn

Nope, it is spending 4 or 5 mana on a single spell.

**Comment by mlenser** [comment]
Closing as I believe the current wording is clear. I'm open to specific suggestions if you think otherwise.

**Comment by Daniel-Soham** [comment]
On a related but not precisely the same situation note, how does it work
with duration? Do you spend the mana as the duration rolls over?
Contingency is a good example of an unclear situation. It is a three mana
spell but you cast a two mana spell as part of casting the three cost
spell. It sounds from your earlier clarification that it does not count as
casting a 5 cost spell. However it also costs 1 mana/day. I presume one
day's worth comes with casting the spell.
It's not an augment so it presumably doesn't increase the mana cost of the
spell to cast it with a longer duration but when does the mana get spent?
The duration portion of the rules on mana don't make it clear.

Duration
A concoction, maneuver, or spell’s duration is the length of time the
concoction, maneuver, or spell persists. A duration can be expressed in
rounds, minutes, hours, or even years. If a concoction, maneuver, or spell
specifies that its duration lasts an amount per resource used (1
minute/mana for example), the duration is automatically increased the
amount listed based on the amount of resources (catalysts, mana, stamina
dice) used. Some spells specify that their effects last until the spell is
dispelled or destroyed.

Perhaps a sentence in the duration section could say when this mana gets
spent.

**Comment by mlenser** [comment]
> On a related but not precisely the same situation note, how does it work with duration? Do you spend the mana as the duration rolls over?

I think you've misunderstood duration. The duration is dictated by the mana cost. 1 hour/mana or 1 day/mana means the spell ends at that point. It'd need to be re-cast.

> Contingency is a good example of an unclear situation. It is a three mana spell but you cast a two mana spell as part of casting the three cost spell. It sounds from your earlier clarification that it does not count as
casting a 5 cost spell.

These are 2 different instances of mana cost, ya.

**Comment by Daniel-Soham** [comment]
So does contingency always last three days as there is no way to spend more
or less than three mana on casting it?

**Comment by mlenser** [comment]
Contingency was dropped to 2 mana and changed to 1 hour/mana. So 2 hours.

All spells can spend more mana for increased duration, even if an augment isn't listed. I think I have that written somewhere..

**Comment by Daniel-Soham** [comment]
_All spells can spend more mana for increased duration, even if an augment isn't listed. I think I have that written somewhere.._
If you can't find it or think of where it would be it seems like a new player would definitely have trouble finding it.

Yikes contingency is dropped down to 2 hours? I am not sure the spell is still useful at that point. 5e's version is 10 days and Pathfinder 2 is until your next long rest. If it's only going to last a few hours instead of a few days I would definitely drop the casting time down so you can, for example, cast a contingent buff or two before trying something dumb like jumping a ravine or kicking down a door.

**Comment by Daniel-Soham** [comment]
It seems contingency could just be a one mana spell that lets you make a cantrip contingent and for each mana higher it lets you cast one less than the total mana cost spell, so a 5 cost contingency let's you cast 4 mana worth of spell if the trigger happens etc. I think the 1 day/mana duration works well as well.

**Comment by mlenser** [comment]
> If you can't find it or think of where it would be it seems like a new player would definitely have trouble finding it.

Explicitly added it to the rules: 

> A concoction can be created using more catalysts then the concoction needs, even if no augmentation is listed.
> A spell can be cast using more mana than the spell needs, even if no augmentation is listed.
> A maneuver can be used with more stamina dice than the maneuver needs, even if no enhancement is listed.

**Comment by mlenser** [comment]
> I think the 1 day/mana duration works well as well.

I'd like to avoid casting spells for the next day.

**Comment by mlenser** [comment]
Contingency changed to reduce its mana cost to 1 mana, reduce its duration to 3 hours/mana, change the contingent spell to a cantrip, add an augment to increase the mana of the contingent spell, and remove the material component.

**Comment by Daniel-Soham** [comment]
That's pretty great. I still think to be useful and to be able to reach a day with it maybe 6 or 8 hours per mana makes more sense?

**Comment by mlenser** [comment]
The standards are 1, 3, or 6. Mana recovers on a short rest so 3 hours, or 6 hours at 2 mana with a 1st level contingent spell seems totally on point.
