### ISSUE TITLE
Grammatical typo in divination psychic focus and a clarity issue

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1009]
**Describe the bug**
Under psychic focus in the Psionicist class it says the following:
Divination. You understand the literal meaning of any spoken language that you hear and you understand any written language that you **sees**, but you must be touching the surface on which the words are written.

Sees should be see.

On a separate note, perhaps this should be a separate bug/feature request, but it is not very clear that when you select a psychic focus whether you are selecting just one option in the case where there are many in a theme, or you get multiple things by selecting a theme, for instance it is not clear if a monk selecting the acid theme psychic focus gets resistance to acid and the ability to shoot acid in place of monk martial arts, or just one of the other.

Also for themes where it says (monk) I assume it means monk are the only ones who can select that option, but it is unclear and one could potentially read it as monks can only select that option.

**Link**
https://www.kryxrpg.com/character/classes/psionicist

**Comment by mlenser** [comment]
I changed `sees` to `see` and changed the wording around selecting a focus:

> As an action, you can choose one of the themes you know and gain **_one of_** its psychic focus benefits

**Comment by Daniel-Soham** [comment]
Great. Thanks for clarifying that.
