### ISSUE TITLE
Incendiary Cloud minor fixes

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#101]
> As an action, a swirling cloud of smoke shot through with white-hot embers appears in a sphere centered on a point within 120 feet. The cloud spreads around corners and is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.

> A creature that enters the spell’s area for the first time on a turn or starts its turn there must make a Fortitude saving throw. On a failed save, a creature takes 2d6 fire damage. On a successful save, a creature takes half as much damage.

> The cloud moves 10 feet directly away from you in a direction that you choose at the start of each of your turns, rolling along the surface of the ground.

Issues:

- "rolling along the surface of the ground" implies you must cast it on the ground (which is not mentioned in the targeting sentence) or that it sinks down. I bet it's due to copying this sentence from Cloudkill, but note that Cloudkill also says "The vapors, being heavier than air, sink to the lowest level of the land, even pouring down openings." to explain what happens exactly. I suggest either removing the ground part, or adding the "heavier than air" part, or even going wild and saying that it's lighter than air (because it's hot) so it floats up! :o

- "directly away from you" conflicts with "in a direction that you choose" ([issue in original RAW](https://www.sageadvice.eu/2016/07/30/does-incendiary-cloud-move-directly-away-from-you/)). Can be changed to just "moves 10 feet away from you in a direction that you choose", or if you want to buff it a bit, "moves 10 feet in a direction that you choose".

**Comment by Marcloure** [comment]
About moving up because it's hot, volcanic pyroclastic flow goes down even though it can reach 1000 ºC (it's made of hot ashes and airborne molten rock). Also, it would be quite a difficult spell to use if it goes up xD

About moving directly away from, I think you can choose where to. It can go straight away from you, maybe a bit North, maybe a bit to the South, but always increasing your distance to it without making curves.

**Comment by mlenser** [comment]
The ground wording comes from Cloudkill. I tried to synchronize the wording in similar cases (Acid Fog, Cloudkill, Incendiary Cloud, Rolling Thunder, Sandstorm)

**Comment by mlenser** [comment]
Maybe the "along the ground" wording should be removed from all cases?

**Comment by itamarcu** [comment]
I think it's neat that Cloudkill moves along the ground - "The vapors, being heavier than air, sink to the lowest level of the land, even pouring down openings.". This is not just a fluff description as it has actual mechanical implications (e.g. you can't keep it above you as a deterrent against creatures, but you can slide it through a sewer grate or thick underbrush where you aren't able to cast down below otherwise.

**Comment by mlenser** [comment]
I think it is equally as neat to be able to create a cloud of poison/acid/fire/etc in the sky to inhibit flying creatures if I so desire.

If it applies to Cloudkill then it also applied to Acid Fog and then why not the rest? They're all clouds.
