### ISSUE TITLE
Repeated line in mending 

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1011]
**Describe the bug**
As you spend 1 minute to cast this spell, you repair a single break or tear in an object you touch, such as a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no longer than 30 centimeters in any dimension, you mend it, leaving no trace of the former damage.

This spell can physically repair a magic item or construct, but the spell can’t restore magic to such an object **such as a broken key, a torn cloak, or a leaking wineskin**.

It seems the bolded section is an unnecessary repeat from the previous section.

**Link**
https://www.kryxrpg.com/spells/mending

**Comment by mlenser** [comment]
Thank you!
