### ISSUE TITLE
Colon seems inappropriate in fey step feat

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1012]
**Describe the bug**
The requirements for fey step say 
Prerequisites: Elf: High Elf or Gnome
Putting a colon right after another colon seems wrong.
Should this be just High Elf or Elf (High Elf)? Or can other Elf variants do this as well? In which case it could just say Elf, Gnome

**Link**
https://www.kryxrpg.com/character/feats/fey-step

**Comment by mlenser** [comment]
Only high elves.

Thanks!
