### ISSUE TITLE
Greater meta magic imbue clarity

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1013]
**Describe the bug**
Imbue Spell
When you cast a spell that takes one or two actions to cast and which is not a sphere emanating from you, you can expend metamagic equal to the total mana cost to cast the spell (1 metamagic if the spell is a cantrip) to store its energy within your weapon or a piece of ammunition instead of applying its effects immediately. You can then make a weapon attack with the imbued weapon before the end of your turn (no action required).

**The next time the weapon hits or when you fire the piece of ammunition** before the end of your next turn, the spell is released as if you cast it from the point at which the weapon hits or the piece of ammunition lands, with any areas of effect originating from that position. If the spell is a cone or line, the cone or line extends in the direction directly away from you. If an imbued ammunition misses by 4 or less, it lands within 1 meter of the target. Roll a d8 to determine which space it lands in.

This could be used to imbue a crossbow bolt with a [lightning bolt](https://www.kryxrpg.com/spells/lightning-bolt) that streaks through your enemies or to throw a dagger imbued with [knock/lock](https://www.kryxrpg.com/spells/knock-lock) at a door.

Can you imbue someone else's weapon?
If you can not it should say the next time you hit with the weapon. If you can then some other items should be corrected to not say "you". Such as when the ammunition is fired.

Also does the weapon still deal its normal attack damage? If so it should probably say in addition to the weapons normal attack or effect or something of that nature.

**Link**
https://www.kryxrpg.com/character/feats/major-metamagic

**Comment by mlenser** [comment]
> Can you imbue someone else's weapon?

Sure, but the action economy makes it quite ineffective. I've changed the wording from "your weapon" to "a weapon" anyways.

> Also does the weapon still deal its normal attack damage? If so it should probably say in addition to the weapons normal attack or effect or something of that nature.

The effect does not specify that the weapon/ammunition does not deal its normal damage, so yes.
