### ISSUE TITLE
Heighten spell major meta magic broken link 

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1014]
**Describe the bug**
Heighten Spell
When you cast a spell that forces a creature to make a saving throw to resist its effects, you can expend 3 metamagic to give one target of the spell **disadvantage** on its first saving throw made against the spell. You can not use this metamagic option in combination with other metamagic options.
Disadvantage there is a link that goes to https://www.kryxrpg.com/rules/%5Badvantage%5D(/rules/advantage-disadvantage)-disadvantage
One presumes it should go to https://www.kryxrpg.com/rules/advantage-disadvantage

**Link**
https://www.kryxrpg.com/character/feats/major-metamagic

**Comment by mlenser** [comment]
Thanks - it was a regex issue.
