### ISSUE TITLE
Error in witch class familiar feature

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1017]
**Describe the bug**
You gain the service of a familiar that watches over you. You have a familiar as outlined in the find familiar spell, though your familiar has additional health equal to your level + your Wisdom, has an Intelligence, Wisdom, and Charisma of at least 0, and has the ability to speak one language that you speak. Your familiar always appears in the same form. If your familiar drops to 0 health, it reappears next to you after you finish a long rest or **if you expend 1 mana as a ritual or your Witchcraft to bring it forth.**

The ritual should say how long it is and I'm not sure what is meant there by using the witchcraft to bring it forth.

**Link**
https://www.kryxrpg.com/character/classes/witchcrafter#familiar

**Comment by mlenser** [comment]
I've added a link to the `ritual` word to the ritual rules. However the Witchcrafter casts rituals in 5 minutes instead of 10 via the ritualist feature so they'll have to remember/reference that for this case and others.

**Comment by Daniel-Soham** [comment]
Well I mean if witches can perform rituals for 5 minutes plus the casting time of a spell instead of 10 minutes plus the length of the spell one still needs to make clear the spell being referenced and how long it takes. For instance it should say one mana to cast find familiar or cast it as a ritual or if this is a special non spell ritual it should state the length of time to perform the ritual. Regardless of all this the bolded text does not make grammatical sense to me.

**Comment by mlenser** [comment]
It should be more clear now:

> If your familiar drops to 0 health, it reappears next to you after you finish a long rest unless you expend 1 mana as a [ritual](http://kryxrpg.com/rules/concoctions-maneuvers-and-spells#rituals) or expend your Witchcraft to bring it forth before then.

**Comment by Daniel-Soham** [comment]
So is the idea you spend one mana in a 5 minute ritual to bring it back or
one usage of the witchcraft feature to bring it back as an action or does
that also take a 5 minute ritual?

The point I find unclear is the length of time of the ritual. If you're
ritually casting find familiar that would take seemingly 20 minutes
normally or 15 minutes normally for a witch. If you are using one mana to
cast find familiar that would normally take 10 minutes.

If this is a special non spell ritual it should probably have the length of
time of the ritual listed.

**Comment by mlenser** [comment]
> So is the idea you spend one mana in a 5 minute ritual to bring it back or one usage of the witchcraft feature to bring it back as an action.

Correct.

> The point I find unclear is the length of time of the ritual. If you're ritually casting find familiar that would take seemingly 20 minutes normally or 15 minutes normally for a witch.

Correct.

> If you are using one mana to cast find familiar that would normally take 10 minutes.

Correct. But that's not what a Witchcrafter would be doing here. They'd be spending 1 mana as a ritual (which is normally 10 minutes, but is 5 minutes for them). So 1 mana and 5 mins and they have their familiar back.

> If this is a special non spell ritual it should probably have the length of time of the ritual listed.

One goal of the system is to not over-specify. This case references the normal ritual rules via link so those rules should be followed. This feature shouldn't mention Ritualist or the rules for rituals specifically as that is verbose.

**Comment by Daniel-Soham** [comment]
Not over specifying and avoiding repeating information everywhere are
admirable goals. My concern is the ritual information listed specifies it
as a method to cast spells. Furthermore rituals are methods to avoid
spending mana. As such it is confusing both to have a mana cost and perform
a ritual, and to have a ritual without casting a spell without the length
of the ritual specified. The ritualist feature also specifies when casting
a spell. If I were writing the familiar feature I would have it say the
witch can spend one mana during a five minute ritual to bring back their
familiar, or use one usage of their witchcraft feature to bring it back as
an action or something of that nature if that is the intended behavior as
otherwise there is no information in the ritualist feature of the witch nor
the ritual spellcasting rules to let you know the length of any given
non-spell based ritual.

**Comment by mlenser** [comment]
> If I were writing the familiar feature I would have it say the witch can spend one mana during a five minute ritual to bring back their familiar.

The Naturalist and Suffused have the same feature to bring something back by spending 1 mana as a ritual so it's not unique to the Witchcrafter. It's not about the time - the word ritual is literal here as the character is actively performing a ritual.

I'll remove the ability to bring it back as a ritual.

**Comment by mlenser** [comment]
Naturalist, Suffused, and Witchcrafter can only bring a familiar or wild companion back as an action by expending a use of another core feature. They cannot bring it back with a ritual.
