### ISSUE TITLE
Companions hard to navigate

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1019]
**Describe the bug**
Any spell or ability that creates a companion links to the general companion page rather than specific companion making it hard to find. It also seems that there is no way to actually link specific companions?

In addition, using Chrome on Android results in a very long drop down list that you can not scroll through and gets cut off by the bottom of the screen thus only showing the top portion of the list. As such for a user like myself it is literally impossible to reach more than half of the companions.

**Link**
https://www.kryxrpg.com/character/companion

**Comment by mlenser** [comment]
The goal has been to [replace companions with normal creatures](https://github.com/mlenser/kryx-rpg-issues/issues/930), but I never quite made it work. It'd take some work to calculate it all.

Sorry about the dropdown - it likely happened when I switched up how I build my UI components.

**Comment by Daniel-Soham** [comment]
Sure this one seems like more work than the usual typos I've been finding here and there.

**Comment by mlenser** [comment]
I changed the component to be searchable. I'll fix the scroll on it later - no time now, sorry!

**Comment by mlenser** [comment]
companion can now be scrolled

**Comment by Daniel-Soham** [comment]
The scrolling isn't working for me on Android Chrome, though I haven't tested it on a desktop yet, but that search function is helpful.

**Comment by mlenser** [comment]
Android chrome with scroll:

![Screenshot_20240218-075815](https://github.com/mlenser/kryx-rpg-issues/assets/235857/5cb79365-7257-4c66-8b25-77dc56abbfca)

**Comment by Marcloure** [comment]
I can confirm it's working correctly for me.
