### ISSUE TITLE
Flawed distance logic in black hole spell

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1021]
**Describe the bug**
If my understanding of spells is correct, a 5 mana cost spell has a 5 meter radius.
Black hole has an additional radius of 30 meters that it affects but that area doesn't cause damage.
The issue here is once inside the black hole creatures are "pulled towards the center" a longer distances than exists if the spell has a 5 meter radius. If the black hole actually warped space and made that 5 meter radius area deeper ... that would be awesome but that's not what it says the spell does.
Another logical flaw in my mind is the ability to make a brawn or nimbleness check to get out might make sense in the outside the black hole area situation but it doesn't make too much sense in the being levitated and crushed by it situation. Like are you going to swim through the air against gravity to escape? One would need a fly speed faster than 6 meters. If that's just how all spells in this system are where you can make a check at the end of your turn to repeat a save that's fine. I feel the same way about the spell levitate which I see follows the same rules basically.

Text of the spell with issues bolded follows.

As two actions, a dark sphere of destructive gravitational force forms, centered on a point you can see within sight range. For the duration, the black hole and any space within 30 meters of it are difficult terrain.

When the black hole appears and at the start of each of your turns thereafter:

Unsecured objects within 30 meters of the black hole are pulled toward its center.
Nonmagical objects fully inside the black hole are destroyed if they aren't being worn or carried.
Each creature within 30 meters of the black hole must succeed on a Reflex saving throw or be pulled 6 meters toward the center of the black hole.
Each creature inside the black hole must succeed on a Reflex saving throw.
On a failure, it takes 6d8 concussion damage, is **pulled 6 meters toward the center of the black hole,** and is restrained for the duration.

On a critical failure, it takes twice as much damage and is **pulled 12 meters toward the center of the black hole**.

On a success, it takes half as much damage.

On a critical success, it takes no damage.

A creature that enters the black hole for the first time on a turn must also make the Reflex saving throw.

If the black hole is in the air, creatures remain aloft while being pulled toward the black hole.

**A creature restrained by the black hole, or one that can touch the creature, can use an action to make a Brawn or Nimbleness check (its choice) against your spell save Difficulty. If it succeeds, it is no longer restrained.**

A creature reduced to 0 health by this spell is annihilated, along with any nonmagical items it is wearing or carrying.

**Link**
https://www.kryxrpg.com/spells/black-hole

**Comment by Marcloure** [comment]
> The issue here is once inside the black hole creatures are "pulled towards the center" a longer distances than exists if the spell has a 5 meter radius.

Then the creature is pulled only 5 meters. It's the same with other AOE pulls, you don't overshoot it.

> Like are you going to swim through the air against gravity to escape? One would need a fly speed faster than 6 meters.

The Brawn or Nimbleness check only frees you from the restrained condition (i.e.: the crushing gravity). To get out of the black hole, you still need to move 5 meters in difficult terrain, and then not get pulled again on your next turn. If the black hole is holding you aloft, passing the check only removes the restrained condition, but you still can't move away from it and will inevitably die if you can't fly, teleport, or get pushed away.

**Comment by Daniel-Soham** [comment]
Sure it's just a little weird that it's specified that they can be pulled 12 meters but only in a situation where they can maximally be pulled 5 meters. If that critical failure causing a 12 meter pull applied in the larger 30 meter radius it would be more useful. It's just some unnecessary text as any failure while in the damaging area just automatically pulls you to the center.

**Comment by Marcloure** [comment]
Yeah, you are right about that. The black hole itself should pull only 5 meters

**Comment by mlenser** [comment]
Why should it only pull 5 meters? The black hole is 5 meters and the area of effect extends to 30 meters beyond that. So if a character is 30 meters away they can be pulled 6 or 12 meters no problem.

If they're inside the black hole they're still pulled further to the center and then take damage.

> Like are you going to swim through the air against gravity to escape?

If you can fly/swim, why couldn't they use their normal mobility to move away? There are all kinds of examples of a flying/swimming character being pulled towards something and resisting by flying/swimming.

> One would need a fly speed faster than 6 meters.

If they have a speed less than 6 then they'll be pulled in 6 and then they'll be able to move their speed. They'd be pulled in eventually or they can dash or they can disrupt the spell. Lots of options.

**Comment by Daniel-Soham** [comment]
No I'm saying the wording of the spell indicates they can only be pulled 12 meters if they're already in the 5 meter radius and then critically fail the save at which point they cant actually be pulled 12 meters because they're only 5 meters from the center of the effect at that point.

All that stuff about flying and swimming is assuming the creature does not have a fly speed. I acknowledge what you said about the character just not being restrained but are still in the black hole potentially with no way to get out depending on their various move speeds. I suppose conceptually they're being crushed by the gravity in a sort of fetal ball position and they flex or wiggle their way out of that but they're still trapped in the black hole unless they can climb or fly or walk their way out depending on the terrain and location of the black hole. That's reasonable enough (as reasonable as a black hole in a fantasy setting can be I mean).

**Comment by Marcloure** [comment]
> Why should it only pull 5 meters? The black hole is 5 meters and the area of effect extends to 30 meters beyond that. So if a character is 30 meters away they can be pulled 6 or 12 meters no problem.

The spell pulls creatures at 2 dfifferent moments. There is:
> Each creature within 30 meters of the black hole must succeed on a Reflex saving throw or be pulled 6 meters toward the center of the black hole.

And:

> Each creature inside the black hole must succeed on a Reflex saving throw.
> On a failure, it takes 6d8 concussion damage, is pulled 6 meters toward the center of the black hole, and is restrained for the duration.
> On a critical failure, it takes twice as much damage and is pulled 12 meters

The save _inside_ the black hole can't pull creatures more than 5 meters, since the black hole itself has only 5 meters.

**Comment by mlenser** [comment]
Black Hole wording changed so the creature is pulled to the center.
