### ISSUE TITLE
Feather Fall has two names and different rules in the same spell?

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1022]
**Describe the bug**
Take a look. There is Feather Fall and Feather Fell, the same thing but 20% of the strength, both in the same spell link?

**Link**
https://www.kryxrpg.com/spells/feather-fall

**Comment by Marcloure** [comment]
Feather Fell is a reaction, feather fall is an action.

**Comment by Daniel-Soham** [comment]
Ah. That's a bit cheeky, haha. Should they share a single link though?

**Comment by Marcloure** [comment]
Yes. There are a couple of "variant spells", for instance: https://www.kryxrpg.com/spells/hydraulic-push
This means that when you learn this spell, you learn both variations of them (I don't think there is an explicity rule for this).

**Comment by mlenser** [comment]
I added the following to the spell rules:
> Some spells have variations which allow them to be cast in different ways. *[Feather Fall](https://www.kryxrpg.com/spells/feather-fall)* for example can be cast as an action or as a reaction.
