### ISSUE TITLE
Abscond seems to have an extra bit of text.

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#1023]
**Describe the bug**
If you were hit by an attack, attacks made against you are made with disadvantage until the start of your next turn, including the triggering attack. You can do so after the roll but before any effects of the roll occur.

If the roll already has disadvantage, you cannot apply another instance of disadvantage **and you must use this before the roll to cancel out any disadvantage.**

The bolded section does not appear to belong there as this spell is only about giving your enemies disadvantage and doesn't appear to cancel disadvantage in any situations 

**Link**
https://www.kryxrpg.com/spells/abscond

**Comment by mlenser** [comment]
Abscond does give the triggering attack disadvantage:
> If you were hit by an attack, attacks made against you are made with disadvantage until the start of your next turn, including the triggering attack.

Averting Gust and Memory of One Thousand Steps have similar wording

**Comment by Daniel-Soham** [comment]
It's the bolded test that is the problem. 

**and you must use this before the roll to cancel out any disadvantage.**

You can't use the spell to cancel disadvantage. It causes disadvantage in your enemies. It can't cancel disadvantage.

**Comment by Daniel-Soham** [comment]
Perhaps it should say to cancel out any advantage.

**Comment by Marcloure** [comment]
Yeah, I _think_ the idea is that if the attack has advantage, you need to use before the roll to cancel it, not after the roll is made

**Comment by Daniel-Soham** [comment]
Even that can't be relevant though because you use this reaction after you are hit so you can't actually use it before the roll. I think the bolded text just isn't relevant to this specific spell.

**Comment by mlenser** [comment]
You use the reaction which forces a reroll. The wording is wonky, but that's the effect.

**Comment by Daniel-Soham** [comment]
The intended effect seems clear enough but the bolded text is incorrect.

**Comment by mlenser** [comment]
https://github.com/mlenser/kryx-rpg-issues/issues/1023
