### ISSUE TITLE
Imperial centaurs have four feet; Metric centaurs have 4 extr30?

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#103]
https://marklenser.com/rpg/character/races/centaur

bug in metric:

> When you make such a climb, each foot of movement costs you 4 extra feet, instead of the normal 1 extr30 centimeters.

while in imperial:

> When you make such a climb, each foot of movement costs you 4 extra feet, instead of the normal 1 extra foot.

I'm guessing your clever regex algorithm for converting feet to meters is not clever enough when people start adding words in the middle!

but, of course, 

this should be, of course:

> When you make such a climb, each meter of movement costs you 4 extra meters, instead of the normal 1 extra meter.

**Comment by mlenser** [comment]
Fixed so it now correctly says
`When you make such a climb, each foot of movement costs you 1.2 extra meters, instead of the normal 30 extra centimeters.`

Thanks!
