### ISSUE TITLE
Contact Info (or: some questions!)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#104]
Hi! This is obviously not a direct issue with the Kryx RPG (or is it Kryx's RPG?), but, basically, me and my play group found this RPG and are quite interested, but we have many questions and some of them don't really fit the github issue tracker.

Could you add some contact info (email, discord, etc)?

Alternatively, is there some place for discussions of this RPG? I found [this long GiantITP forum thread](https://forums.giantitp.com/showthread.php?541724-Structural-Class-Changes-(Mana-Talents-Clear-gish-structure)) but it seems outdated and the last post was made half a year ago.

Some general topics that I'd like to discuss include...
- how many people are using this system (that you're aware of)?
- is there good support for it in any VTT? (particularly interested in Foundry and Roll20)
- isn't there a bit of a licensing issue, with the website using copyrighted images and race/class/creature names?
- is there a page like https://marklenser.com/rpg/character/feats but for spells or maneuvers? I know there's probably a lot of them but it would be very helpful to have a list of all spell descriptions (and not just spell names) for the ability to easily ctrl+f certain phrases.

Thank you!

**Comment by mlenser** [comment]
Hey,

I've received feedback on this project for years now through Bitbucket/Github. Bitbucket (https://bitbucket.org/mlenser/tabletop-homebrew/issues) has 785 issues dating back until 2017. Github is now at 104, which is great! Github is my primary place to receive feedback as it is searchable and others can see the items raised for years to come. If there is a strong interest in having more live discussion then discord could be an option.

Firstly I'd like to say that this is a hobby project that I've worked on for 3+ years now. It is not a commercial project.

> how many people are using this system (that you're aware of)?

It's difficult to answer that question. From my time building Roll20 sheets I know that using those who interact and give feedback is a small portion of the whole user base. I have around 5 users who give regular feedback, with Marcloure giving the most by far. So maybe max 50 groups I'd guess. I could get a more accurate number by adding google analytics, but then I have to have a cookie consent..

> is there good support for it in any VTT? (particularly interested in Foundry and Roll20)

Not particularly. I used to build the Shaped sheet on Roll20, but do not have the time to build it into the future. One of my patrons was talking about building the system in Foundry, but don't get your hopes up for that. He may be in your same group?

> isn't there a bit of a licensing issue, with the website using copyrighted images and race/class/creature names?

Images can be removed/replaced if they are an issue. They aren't very pervasive. Monsters are different enough from RAW, but if the names ever become an issue then they can be renamed.

> is there a page like https://marklenser.com/rpg/character/feats but for spells or maneuvers? I know there's probably a lot of them but it would be very helpful to have a list of all spell descriptions (and not just spell names) for the ability to easily ctrl+f certain phrases.

Only a list:
- https://marklenser.com/rpg/themes/concoctions/all
- https://marklenser.com/rpg/themes/spells/all
- https://marklenser.com/rpg/themes/maneuvers/all

Its the same for monsters: https://marklenser.com/rpg/monsters/all

Showing ~800 React components is incredibly laggy and the site lags for a good 15s or more. If there is a strong desire for this, I could potentially build it, but it won't be performant.

**Comment by Marcloure** [comment]
> is there good support for it in any VTT? (particularly interested in Foundry and Roll20)
I have been using Kryx's RPG on Roll20 for some time now, and I can say it is possible with Shaped Sheet, but it will require some work.

Below follows a post I wrote some time ago about how to adapt the Shaped Sheet to these rules. Keep in mind that it is already outdated, for instance, it doesn't cover skill capability (which I solve adding modifiers), but I think you can find it to be helpful still.

https://bitbucket.org/mlenser/tabletop-homebrew/issues/667/roll20-and-shaped-character-sheet

**Comment by itamarcu** [comment]
Thanks for your answers! ^_^

My group will try a combination of google sheets and Roll20, and see how it goes.

Currently the biggest issue (for me at least) is being able to quickly check what a spell/maneuver does (also true for features and feats, but those are easier).

For now the solution seems to be just keeping several browser tabs open (one for your class, one for feats, and one per theme you got). Would be nice to have an easy way of... somehow incorporating spells and such into the google sheeets character sheets easily. I'll try to do stuff with that and try the shaped sheet too.

Thanks for working on this!

**Comment by Marcloure** [comment]
You can attach the spell link to the sheet, but it would be nice if you could incorporate its description somehow, like on a popover window. I am not an expert in spreadsheets, so I don't know how one would do that (or if it's possible at all)
