### ISSUE TITLE
Odd result of rules concerning spell mana restrictions when knowing them, and Spell Thief

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#106]
Normal casting classes (e.g. Wizard):

> Learn a new spell from a theme you know. The spell must cost equal to, or less than, your mana limit and you must know a number of spells from the spell’s theme equal to half the spell’s mana cost (rounded down).

(note: Arcane Secrets let you ignore the "theme you know" restriction)

The rule about casting spells:

> To use a spell, a character must know a number of spells from the spell’s theme equal to half the spell’s mana cost (rounded down)

Result:

* When learning new spells in a new theme through your standard level-up, you must first start by learning a 1-mana spell. Then you can learn another spell, up to 3-mana (because 3/2=1.5, rounded down to 1). Then, you can learn another spell, up to 5-mana. In total, this spell progression is [1, 3, 5, ...].

* To use a 3-mana spell, you must know at least 1 spell of its theme (which you do, because you know that spell itself). Therefore, you don't actually need to have that 1-mana spell to cast the 3-mana spell; you only need it at the moment of level-up. 

* If you level up again as Wizard, you can choose to replace your 1-mana spell with another spell from a different theme, and you will still be able to cast that 3-mana spell. So functionally, your progression can be [3, 5, 7...] as you remove the 1-mana spell.

* If you're a Spell Thief, you can "steal the knowledge of the spell if it is at least 1 mana and equal to or less than your mana limit. For the next 8 hours, you know the spell and can cast it using your mana". Note that this does not have a limit like the Wizard's. Therefore, you can steal a 3-mana spell from a theme you don't know, and you'll be able to cast it.

THE PROBLEM:

This is weird and unintuitive.

THE SOLUTION:

I don't know. The obvious thing is to change the basic spell rule to:

> To use a spell, a character must know **an additional** number of spells from the spell’s theme equal to half the spell’s mana cost (rounded down)

However, this basically nerfs the Spell Thief, preventing them from being able to use any stolen off-theme spell unless it's a 1-mana spell. So I suggest also changing Spell Thief to:

> ...steal the knowledge of the spell if it is at least 1 mana and equal to or less than your mana limit. For the next 8 hours, you know the spell and can cast it using your mana. You can ignore the requirement to know additional spells of that theme, for this purpose.

**Comment by mlenser** [comment]
I can look at this after https://github.com/mlenser/kryx-rpg-issues/issues/87 as that will change some wording here.

**Comment by mlenser** [comment]
> When learning new spells in a new theme through your standard level-up, you must first start by learning a 1-mana spell.

Cantrips count as well

> If you level up again as Wizard, you can choose to replace your 1-mana spell with another spell from a different theme, and you will still be able to cast that 3-mana spell. So functionally, your progression can be [3, 5, 7...] as you remove the 1-mana spell.

This is intended. The requirement is just that you know X amount of spells to ensure you're familiar with the theme. If you retrain them (1/level and should be rare) then that's ok.

___________________

Some fixes:

- "Learn a new spell from a theme you know. The spell must cost equal to, or less than, your mana limit. **If the spell costs 2 or more mana you must know a number of spells from the spell’s theme equal to spell’s mana cost minus 1.**" (wording reflects the new 5 mana system)
- "For the next 8 hours, you know the spell and can cast it using your mana, **ignoring the normal restrictions on knowing a certain number of spells from its theme**."

**Comment by mlenser** [comment]
This will release as part of 19.27.0 soon.

**Comment by Marcloure** [comment]
> equal to spell’s mana cost minus 1.

Equal to **the** spell's mana cost minus 1.

Just noting the typo before it goes live.

**Comment by mlenser** [comment]
thanks
