### ISSUE TITLE
Inconsistencies in weapon names

### ISSUE THREAD

**Issue by xindium** [mlenser/kryx-rpg-issues#107]
I'm not sure if this happens with anything but hatchets, but in multiple places the rules refer to handaxes, even though none exist in the weapons list (and I imagine these are hatchets.) I noticed it at least on the weapons page, under Thrown -description, and in starting equipment under various classes.

**Comment by Marcloure** [comment]
Hatchets are named handaxes in PHB, it's a leftover from there.

**Comment by mlenser** [comment]
I'll rename them, thank you!
