### ISSUE TITLE
Vampire isn't Blood and Lycanthrope isn't Beast

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#108]
Currently, all of the Vampiric abilities are in [Shadow](https://marklenser.com/rpg/themes/shadow) and all of the Lycanthropy abilities are in [Blood](https://marklenser.com/rpg/themes/blood). Thematically, it feels like Vampires should be in Blood, because they're blood drinkers and bloodless and kinda evil, while Lycanthropes should be in Beast, because while they have their blood curse they also literally transform into beasts and have beastly features.

This is also a bit odd because Blood is only in Occult, while Shadow is also in Martial - which means that martial classes have an easy time becoming vampires but only very few classes get to become werewolves easily.

I suggest making Vampiric (and similar feats) both Blood and Shadow, and making Lycan Form (and similar feats) both Blood and Beast.

**Comment by mlenser** [comment]
Ya, Vampire was previously blood, but there is a lot of Shadow there. Both work as you say so I'll add it to both.

Lycan feels more like Beast than blood. The only connection to blood is the disease in their blood.

**Comment by itamarcu** [comment]
cool, so Vampire will be Blood & Shadow and Lycan will just be moved to Beast?

**Comment by mlenser** [comment]
I think that's best. Maybe lycan in pestilence, but that doesn't make too much sense.

**Comment by mlenser** [comment]
- Lycan feats moved to the Beast theme
- Vampiric feats added to the Blood theme
