### ISSUE TITLE
Spellbook - typo, and suggestion

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#109]
https://marklenser.com/rpg/character/classes/mage/wizard

**Spellbook**
> You have a spellbook. Each time you gain a Wizard level you can write the spells you learn from that level into your spellbook without expending any sp, though you still must spend time writing them. Choose one theme, the gold and time you must spend to copy spells from this theme into your spellbook is halved.

This should say "silver", not "gold".

Also - I noticed that the spellbook is a 1st level feature but this is a 2nd level feature:

**Arcane Inspiration**
> You can call a spell to mind that suits your needs. On your turn with your spellbook in hand, you can cast a spell in your spellbook as if you know it. Once you use this feature, you must finish a short or long rest before you can use it again.

> Also, on a short rest you can choose a number of spells you know up to half your proficiency bonus (rounded down) and replace each of them with another spell in your spellbook from a theme you know, which must cost equal to, or less than, your mana limit. On a long rest you can choose and replace a number of spells equal to your proficiency bonus.

This second paragraph, should be right next to the spellbook description, in my opinion. I know this technically changes the progression and lets wizards "prepare" spells starting from 1st level, but... it seems weird to me that the core feature of the spellbook is given only one level later, and until then, the only reason to inscribe spells is as rituals.

Is there an issue with moving this second half of Arcane Inspiration back to the Spellbook feature? I think it would make things much more straightforward and people won't have to be confused about the purpose of the spellbook or if you still need to "prepare" spells.

**Comment by mlenser** [comment]
> Is there an issue with moving this second half of Arcane Inspiration back to the Spellbook feature?

Class defining features come at 2nd level.

> people won't have to be confused about the purpose of the spellbook or if you still need to "prepare" spells.

Preparing isn't mentioned anywhere in the rules. Moving this wouldn't clarify that.

> it seems weird to me that the core feature of the spellbook is given only one level later, and until then, the only reason to inscribe spells is as rituals.

Mages learn their spells by writing them down and studying them. The purpose of the spellbook is flavor.
