### ISSUE TITLE
Explorer's Guide to Wildemount spells

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#11]
Original: https://bitbucket.org/mlenser/tabletop-homebrew/issues/784/explorers-guide-to-wildemount-spells

______

I have got the CR book here, and it has some new gravity spells in it. I am not sure if you can add them to the project, but I’ll post the spells I have found to be the most interesting.

## Immovable Object (2nd level)

1 action. Touch, 1 hour

You touch an object that weighs no more than 10 pounds and cause it to become magically fixed in place. You and the creatures you designate when you cast this spell can move the object normally. You can also set a password that, when spoken within 5 feet of the object, suppresses this spell for 1 minute.

If the object is fixed in the air, it can hold up to 4,000 pounds of weight. More weight causes the object to fall. Otherwise, a creature can use an action to make a Strength check against your spell save DC. On a success, the creature can move the object up to 10 feet.

### At Higher Levels. 

If you cast this spell using a spell slot of 4th or 5th level, the DC to move the object increases by 5, it can carry up to 8,000 pounds of weight, and the duration increases to 24 hours. If you cast this spell using a spell slot of 6th level or higher, the DC to move the object increases by 10, it can carry up to 20,000 pounds of weight, and the effect is permanent until dispelled.

## Gravity Sinkhole (4th level)

1 action. 120 feet, instantaneous

A 20-foot-radius sphere of crushing force forms at a point you can see within range and tugs at the creatures there. Each creature in the sphere must make a Constitution saving throw. On a failed save, the creature takes 5d10 force damage and is pulled in a straight line toward the center of the sphere, ending in an unoccupied space as close to the center as possible (even if that space is in the air). On a successful save, the creature takes half as much damage and isn't pulled.

### At Higher Levels. 

When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d10 for each slot level above 4th.

## Dark Star (8th level)

1 action. 150 feet, concentration up to 1 minute

This spell creates a sphere centered on a point you choose within range. The sphere can have a radius of up to 40 feet. The area within this sphere is filled with magical darkness and crushing gravitational force.

For the duration, the spell's area is difficult terrain. A creature with darkvision can't see through the magical darkness, and nonmagical light can't illuminate it. No sound can be created within or pass through the area. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.

Any creature that enters the spell's area for the first time on a turn or starts its turn there must make a Constitution saving throw. The creature takes 8d10 force damage on a failed save, or half as much damage on a successful one. A creature reduced to 0 hit points by this damage is disintegrated. A disintegrated creature and everything it is wearing and carrying, except magic items, are reduced to a pile of fine gray dust.

## Ravenous Void (9th level)

1 action. 1000 feet, concentration up to 1 minute

You create a 20-foot-radius sphere of destructive gravitational force centered on a point you can see within range. For the spell's duration, the sphere and any space within 100 feet of it are difficult terrain, and nonmagical objects fully inside the sphere are destroyed if they aren't being worn or carried.

When the sphere appears and at the start of each of your turns until the spell ends, unsecured objects within 100 feet of the sphere are pulled toward the sphere's center, ending in an unoccupied space as close to the center as possible.

A creature that starts its turn within 100 feet of the sphere must succeed on a Strength saving throw or be pulled straight toward the sphere's center, ending in an unoccupied space as close to the center as possible. A creature that enters the sphere for the first time on a turn or starts its turn there takes 5d10 force damage and is restrained until it is no longer in the sphere. If the sphere is in the air, the restrained creature hovers inside the sphere. A creature can use its action to make a Strength check against your spell save DC, ending this restrained condition on itself or another creature in the sphere that it can reach. A creature reduced to 0 hit points by this spell is annihilated, along with any nonmagical items it is wearing or carrying.

They also have a Time Ravage spell at 10th level. It deals damage and makes the target age enough to have only 30 days left until death. The effect can only be removed by a Wish spell or Greater Restoration cast at 9th level.

**Comment by mlenser** [comment]
I'll see if I can find the book - I'd like to add more spells if they are good.

**Comment by DalenWBrauner** [comment]
Immovable Object sounds fun! Maybe instead of 4k lbs, it's dependent on your Spell Save DC? (If the Strength Check scales with DC, then the weight probably should, too.) I could imagine an augment that doubles the strength of the effect. Permanency might want to follow the "cast this every day for a year" thing just for consistency.

Telekinesis already has Gravitational Well, which is roughly Ravenous Void/Gravity Sinkhole but at 2 mana. I wouldn't mind seeing an augment that increases the power enough to warrant being restrained.

Dark Star is a bit strange. Much like the 'moveable orb' spells a few other themes get, except it seems to impose both Magical Darkness and Magical Silence. Definitely would need to be compared closely to other spells that suppress sight/sound so as to not make the others obsolete.

**Comment by Marcloure** [comment]
> Telekinesis already has Gravitational Well, which is roughly Ravenous Void/Gravity Sinkhole but at 2 mana.

Gravitational Well makes the target a body of strong gravity; attacking it is easier and moving away from it is harder. Gravity Sinkhole and Ravenous Void pull creatures and objects towards the center of a sphere. Note that Gravity Sinkhole is instantaneous (like Dark Seer's Vacuum from DotA), while Ravenous Void lasts and is much bigger and stronger.

**Comment by Marcloure** [comment]
I think this can be closed, since we have #440

**Comment by mlenser** [comment]
There are some other spells that I want to add, I think.

**Comment by mlenser** [comment]
- **Themes**
  - **Mind**
    - Reality Break added to the Mind theme [#11](https://github.com/mlenser/kryx-rpg-issues/issues/11)
  - **Telekinesis**
    - Immovable Object added to the Telekinesis theme [#11](https://github.com/mlenser/kryx-rpg-issues/issues/11)
