### ISSUE TITLE
"Ability Modifiers" toggle is inverted

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#110]
The toggle in the top right corner of the page should be inverted in its function, or renamed "Ability Scores".

![ability modifiers bug](https://user-images.githubusercontent.com/6516621/80807961-2264b700-8bc7-11ea-8e9e-444e095ac251.png)

**Comment by mlenser** [comment]
There are two options:

1. Abilities (default)
2. Ability scores & modifiers (with the toggle)

option 1 has no need for the word score or modifier - it is not used by the system at all.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/80809119-4e7d3980-8bc1-11ea-9726-160e4f5020f1.png)

updated it
