### ISSUE TITLE
How are saving throws rounded?

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#112]
https://marklenser.com/rpg/rules

> Use the average of your Strength and Dexterity for your Reflex saving throw.

Is this average rounded up or down?

The google sheet seems to round this up, but it's not explicitly stated here.

(Will saves are similar)

**Comment by Marcloure** [comment]
I have always rounded it as the general rule states: rounded down.

**Comment by mlenser** [comment]
> I have always rounded it as the general rule states: rounded down.

Unless stated otherwise, this is correct.

The spreadsheet takes the average. The formatting rounds it after. I should make it round down.

**Comment by mlenser** [comment]
It was just Reflex which wasn't rounded properly - its fixed now.
