### ISSUE TITLE
Editing cantrips causes annoying pop-up

### ISSUE THREAD

**Issue by eunomicZenith** [mlenser/kryx-rpg-issues#114]
![image](https://user-images.githubusercontent.com/31997989/80815224-82f6f280-8bcd-11ea-801a-4cc5804a6bb5.png)

This pop-up shows up when editing cantrips on the Google Sheets character sheet. No other part of the character sheet (that I've found so far) does this. It's just a mild nuisance. Can it be removed?

**Comment by mlenser** [comment]
I've fixed it on my sheet. You can fix it on yours by going to **Tools** -> **Protect Sheet** -> **Cancel Button** -> remove all protected cells except:
- I17:I22 (this one should end in 22)
- I25:I42
- H14:H15
