### ISSUE TITLE
Blood Sacrifice seems overpowered?

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#115]
https://marklenser.com/rpg/themes/spells/blood-sacrifice

As a level 3 Sorcerer you could combine Blood Sacrifice, Twinned Spell, and Inflict Wounds, using your action and bonus action and spending 0 or 1 mana (signature spell), 2 metamana, 1 hit die, and a tiny bit of hp and max-hp (equal to your hit die roll) - to deal 12d6 (avg 42) damage to two targets. you could even add Power Surge to this for another 6 damage per target, and there's probably feats that make this more ridiculous (4th level Metamagic to do this twice between short rests?).

The description of Twinned Spell isn't clear about whether or not you need to spend 2 meta/mana or 4 meta/mana here (does it count mana that augmented the spell even though you didn't spend that mana yourself?), but even then, 12d6 with the Blood Sacrifice seems like a lot of damage for a very low cost.

Players in my group thought that this is unbalanced!

Opinion?

**Comment by mlenser** [comment]
Blood Sacrifice cantrip changed so that it is simply HD for 1 mana augment:

> As a bonus action when you cast a spell, you can expend 1 Hit Die to augment the spell by 1 mana. Your hit points and hit point maximum is reduced by an amount equal to the Hit Die result. This reduction lasts until you finish a long rest.

**Comment by mlenser** [comment]
Thanks again for the feedback!

**Comment by itamarcu** [comment]
isn't it a bit too similar to Consumptive Power?
https://marklenser.com/rpg/themes/feats/consumptive-power

CP lets you spend functionally 3 hp per 1 mana, while this cantrip lets you spend functionally [1 hit die]hp per 1 mana. In addition, you spend a bonus action, and a hit die, of course.

I think Blood Sacrifice is now too useless, compared to just taking CP at 4th level.

maybe keep the ability to increase the limit?

**Comment by mlenser** [comment]
The ability to increase the limit is too strong.

A cantrip is a much smaller cost than a feat.

**Comment by Marcloure** [comment]
I also agree that a cantrip value is much smaller than a 4th level feat. Many of the core feats are at 4th level.
