### ISSUE TITLE
Ability Modifiers point-buy with a leftover point

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#116]
https://marklenser.com/rpg/character/how-to

> You have 23 points to spend on your abilities. The cost of each value is shown on the Ability Point Cost table. For example, an ability of 2 costs 7 points. Using this method, 2 is the highest ability you can end up with, before applying racial increases. You can’t have an ability lower than −1. This method of determining abilities enables you to create a set of three high numbers and three low ones (2, 2, 2, 0, −1, −1), a set of numbers that are above average and nearly equal (1, 1, 1, 1, 1, 0), or any set of numbers between those extremes.

Players will frequently want to have two high abilities (e.g. spellcasting and martial/armor). This point-buy system pretty much pushes them to start with [2, 2, 1, 1, -1, -1] or [2, 2, 0, 0, 0, 0] in that case. This is what many people might want, but it feels bad, because you end up with an unspent leftover point that you can't do anything with.

This happens with RAW 5e too, but there ability scores still slightly matter - for multiclassing, proficiencies, ASI-feats, etc.

Could you perhaps add some reward to people with an unspent point like this? for example... giving them a skill/tool proficiency?

**Comment by mlenser** [comment]
I wonder if it'd be better to just list the possible choices as there aren't that many choices with the point buy and point buy just complicates things.

Thoughts?

**Comment by itamarcu** [comment]
yeah, I guess that works!

**Comment by mlenser** [comment]
I would not give PCs rewards for having points left over - that's part of the system.

I think point buy is ok for now, though listing the options could be done if people really want that.
