### ISSUE TITLE
Whirling Blade is strictly better than Slice Through

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#118]
https://marklenser.com/rpg/themes/maneuvers/slice-through
https://marklenser.com/rpg/themes/maneuvers/whirling-blade

Slice through and Whirling Blade are similar, and both from Vanguard, but:

- Slice Through requires you to hit a creature first
- Slice Through only hits creatures next to the target

Slice Through needs to be improved!

**Comment by mlenser** [comment]
See https://docs.google.com/spreadsheets/u/0/d/1_ig6KbPdhBrkIp3JqgHIRR8XbBTu-O1zNKuLJXgu378/htmlview# to compare numerical values on spells maneuvers, though these numbers change slightly on the 5 mana system. Slice through is ever so slightly too weak while whirling blade is too strong. But maneuvers don't have many options to adjust balance due to strictly using a d8 dice.

**Comment by itamarcu** [comment]
Yes, but that doesn't change the fact that Slive Through is worse in every way - it's not a sidegrade, it's just the same but worse, and in the same theme - so no one should ever pick this.

Either one of them should be removed, or they need to be changed somehow. For example, maybe Slice Through can let you move around the creatures you're attacking, or also hit creatures next to the target if they're only 1.5 meters (5 feet) away from your reach?

**Comment by mlenser** [comment]
I'm just linking the calculation so you can get a better understanding of how it is calculated.
As I said, things will have to change here in the 5 Mana system. See the maneuvers there (https://docs.google.com/spreadsheets/u/0/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/htmlview#) and you'll see Alice through is actually too strong. Slice through needs no buffs. But Whirling Blade likely needs to be bumped to 2 or changed in other ways.

**Comment by mlenser** [comment]
As part of 20.0.0 when I release it:

> Hammer Spin no longer does half damage on a save to balance it out with other 1 stamina die options
> Whirling Blade no longer does half damage on a save to balance it out with other 1 stamina die options
