### ISSUE TITLE
Google Sheets sheet should have spaces for Mana/Stamina/Catalyst maximums

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#119]
https://docs.google.com/spreadsheets/d/1_m-cphXFxOK7xzMRtfa9r9OLDLdq1R7stv0-tLK8qJ8/edit#gid=1750226729

Unless I missed where this should be - it seems like the sheet doesn't have that!

**Comment by mlenser** [comment]
I would probably do it like:

![Screenshot_20200501-230810](https://user-images.githubusercontent.com/235857/80841992-d3d40e80-8c00-11ea-82a3-1116c4a3ea22.png)


Though I could make an extra field..

**Comment by itamarcu** [comment]
problem is, it seems to think it's a date...

> 5/15/2020

**Comment by mlenser** [comment]
You can use a ' to avoid that
`'5/15` as the formula

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/80855028-b2454800-8c3d-11ea-814b-21eefdd588ff.png)
solved it in a better way
