### ISSUE TITLE
Call Beast spell attack vs. Wild Shape

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#121]
Call Beast states that:

> When [the beast] attacks, make a melee spell attack in place of its attack, but retain the damage and other effects.

But for the Wild Shape spell, you keep the beast's attack bonus. Is this intended?

**Comment by mlenser** [comment]
Thematically I don't think either option should be based on a spell attack. I'll make sure that is not the case and that it is balanced after #87

**Comment by Marcloure** [comment]
Argreed

**Comment by mlenser** [comment]
As part of 20.0.0 when I release it:

> Spells that use the companion system no longer use a spell attack in place of the creature’s normal melee attack

**Comment by mlenser** [comment]
This will go out at as part of 19.27.0
