### ISSUE TITLE
Comparison of Dual Wielding, Two-Handed, Dueling

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#122]
Consider a low level character, and for simplicity, a Battlemaster.

**Two-Handed:**
* weapon = Greatsword (1d12) = 6.5 damage on average
* fighting style = Great Weapon Fighting = "advantage" on weapon damage ≈ 8.5 damage on average
* ability modifier, let's say it's +3 (though it's also likely to be +4). so 11.5 damage.
* 4th level feat - Cleave, which lets you deal a bit of damage (3-4) to enemies next to your target sometimes, and make an extra attack when you drop an enemy. both of these are a uncommon situations that require you to be next to two adjacent creatures, and even then you deal damage only if you make a good hit, so for now I'm not counting them.
* alternatively, you can take Savage Attacker, and roll each damage die three times (!), which mathematically ends up close to a +1 benefit)
* opportunity attacks deal 11.5
* by 5th level, you get Extra Attack, so you deal double this much, 23 damage on a turn.
* many of the maneuvers cost 2 stamina dice and let you make an attack (e.g. Swift Strike). when you do, you deal your attack damage - 11.5 damage.

**Dual Wielding**
* weapon = longsword (1d8) = 4.5 damage on average
* fighting style = Two Weapon Fighting (allows you to have two longswords)
* 4th level feat, Dual Wielder, gives +1 AC (ignore it for now) and add modifier to 2nd attack damage
* result: you make two attacks per turn, of 7.5 damage each. that's 15 damage. even without the feat, that's already more than the two-handed weapon damage.
* by 5th level, you get Extra Attack, but only one of your weapons attacks again, so you deal 22.5 damage per turn. 
* opportunity attacks deal 7.5
* again, many maneuvers cost 2 stamina and let you make an attack. however, about all of these maneuvers have an extra statement, seemingly for balancing purposes: "If the attack is made with a weapon wielded in one hand, add one of the stamina dice to the attack’s damage roll." this means that when you do that, you deal an extra 1d8 damage - actually 1d8 with advantage usually, so approximately 5.8, which we'll say is 5.5 damage. along with your attack that's 13 damage, more than the great weapon!

**Dueling (1 one-handed weapon)**
* weapon = longsword (1d8) = 4.5 damage on average. with your strength/dexterity, 7.5.
* fighting style = dueling = 8.5 damage on average and another +1 to hit, which I guess is kind of like a +10% damage increase, if you have a 50% chance of hitting, so let's call that 9 damage. also +1 to AC
* 4th level feat, Savage Attacker, which is statistically something like +1 damage. so 10 damage.
* once you get Extra Attack, that's 20 damage.
* however, again, your maneuvers that let you make attacks deal both the attack damage and an extra stamina die. since your single attack damage is the highest it could be for a one-handed weapon, this is highest damage: about 14.5 damage.

I noticed that "GWM" (Great Weapon Master") is mentioned in a few places (e.g. https://github.com/mlenser/kryx-rpg-issues/issues/87). is this a feat that was removed, or something? I can't find it!

either way, it seems to me like the end result is....
- two-weapon fighting definitely deals more damage up until level 5 (and not including); even deals more damage at 2nd level, without the feat that improves it even more. furthermore, it's reliable - you get one more attack, so you miss important shots less, and you're more consistent. furthermore, it's helped more by your ability stat increases, and you can reasonably have a +4 by level 3.
- dueling definitely deals more damage with the special maneuvers, because of the odd "one handed" restriction on the extra damage which more than covers up for their slightly lower damage
- great weapon fighting seems bad until level 5, and then it's reasonable, and only really shines with opportunity attacks, which I don't think are very common.

did I miss anything? are those the "expected" optimal builds for each kind of weapon?

**Comment by Marcloure** [comment]
You can check the classes and their many options balance on:

https://docs.google.com/spreadsheets/d/1sGvcz9vbq9yk4kRBEY6ZYGWhGO6-t7CWudznQcWPk74/edit?usp=sharing

Now, that doesn't mean it is easy to understand, but you can compare the DPR of each class build there.

> I noticed that "GWM" (Great Weapon Master") is mentioned in a few places (e.g. #87). is this a feat that was removed, or something? I can't find it!

GWM is the Great Weapon Master feat from 5e. Here the feat is named Cleave (in Vanguard) and it's quite different, but it's still a +3/4 damage per attack.

**Comment by itamarcu** [comment]
thanks!

> Cleave

isn't Cleave much weaker though? its first part only helps when you're fighting two adjacent enemies (uncommon) and the second part only works if you score a critical hit (5% chance, gives another attack, so about +1 damage on average maybe?) or if you kill a creature next to another creature (which, again, is situational and is the same situation).

meanwhile, two-weapon fighting gives you +4 to your damage pretty much on every turn, no situational aspect.

**Comment by Marcloure** [comment]
The spreadsheet gives 33% chance of occurrence for Cleave (I think considering both the AOE damage and the extra attack). Also, for the warrior specifically, two-handed weapons benefit better from action surge and other maneuvers that grant additional attacks or advantage on one attack.

Now, keep in mind that the spreadsheet is not necessarily surely correct. Maybe you can find some miscalculation there as I have in the past.

**Comment by mlenser** [comment]
The first bullet of Cleave is not its strength. A bit of extra damage equal to strength is pretty negligible in most cases.
The power comes from:
> Once on your turn, when score a critical hit with a heavy melee weapon you wield in two hands or reduce a creature to 0 hit points with one, you can immediately make one melee weapon attack without using your action.

I've calculated the chance of that occurring and that is the backbone of thw Greataxe/Greatsword/Maul DPR.

____________________

As Marcloure has pointed out the overall DPR is on that spreadsheet. Please let me know if you think anything is inaccurate.

## Quick TWF vs GWM:

## Level 1
- Battlemaster TWF: 7.8 DPR
- Battlemaster GWF: 7.7 DPR

## Level 2
- Battlemaster TWF: 11.3 DPR
- Battlemaster GWF: 11.2 DPR

## Level 3
- Battlemaster TWF: 13.8 DPR
- Battlemaster GWF: 13.7 DPR

## Level 4
- Battlemaster TWF: 17.4 DPR
- Battlemaster GWF: 17.3 DPR

I'm never going to be able to achieve 100% perfect DPR - my goal is to aim for a stable base. But this case is actually perfect as is as far as my numbers show.

____________________

I can do a quick comparison of the maneuvers in a bit

**Comment by mlenser** [comment]
> dueling definitely deals more damage with the special maneuvers, because of the odd "one handed" restriction on the extra damage which more than covers up for their slightly lower damage

- 2 handed weapons deal ~8.49 + ability (4) for ~12.49 damage, not including the benefit of cleave or other benefits.
- 1 handed weapons deal ~1d8 (4.5) + ability (4), so if we add another 1d8 then we're at ~13.

So one handed weapons would deal about 0.5 more damage on these type of maneuvers. Otherwise these manuevers would be garbage for anything but 2 handed weapons.

**Comment by mlenser** [comment]
Adding the +1 to attack and damage makes 1handed problematic.

**Comment by mlenser** [comment]
As part of 20.0.0 when I release it:

> Maneuvers that allow a character to make a weapon attack such as Backlash, Brace, Commander’s Strike, Frenzy, Rampage, Retaliate, Riposte, Slashing Blades, Swift Strike, and Vengeance have all had their clause for 1 handed weapons reduced to half the result of a stamina die

**Comment by itamarcu** [comment]
Ooh, that seems neat. And thanks for the detailed explanation of everything!
