### ISSUE TITLE
Community Communication?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#128]
I noticed several times in #87 you stated:
> I've been posting here for a week to get more feedback.

That is 100% reasonable. But it also seems apparent that, for one reason or another, some of us hadn't noticed these changes until very recently. (To speak of myself, I only just discovered I had only been watching the repo for releases, rather than the whole repo. While that should resolve the issue for _me_...)

I can't help but wonder if there are more solutions. A spattering of thoughts:

- A Kryx Discord might be too much to manage, and I think there's a lot of value to be had in holding these discussions within each issue on the issue tracker. But I'm very partial to Discord otherwise- as of now, if I wanted to ask you a small question or such, I'm not sure what the best avenue is for that. Discord servers also foster an idea of 'Community' that would encourage discussion between just us playtesters as well. 

- You _could_ start a twitter account for tweeting more major changes you'd like to discuss, and that would work for everyone with a twitter, as well as address the one-off questions concern. I don't have a twitter, so I'm less partial to this one :P

- Maybe the simplest solution would be a descriptive ReadMe? It could include, more or less:
"For those unfamiliar with GitHub, here's how to get email notifications. Please create a new issue if you have new ideas or suggestions. Please create individual issues when discussing individual ideas..." etc. That would at least mitigate you having to repeat yourself, but I'm unsure if it does much for the broader issue.

Ideally, one could set up GitHub to give you an email notification every time there is a **new** issue, without automatically being set to watch the issue. But I haven't figured out if there's a way to do that.

As of right now, for those uninterested in receiving email notifications, the best one can do is refresh the issue page. But I'm also curious if anyone else perceives this as a problem- obviously the community noticing an issue a week late is not ideal.

**Comment by mlenser** [comment]
I think you raise a valid point that a community (Discord) can bring a lot of value for everyone to communicate.

While I think issues are a better place for concrete things to fix, a discussion place would be great.

I'll start a discord in a bit.

**Comment by mlenser** [comment]
Please join https://discord.gg/DZBx33 and we can form it to best suit everyone's needs.
