### ISSUE TITLE
Update single target spell's damage

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#129]
On the site, single target burst spells still list the damage from the 10 mana system. They need to be updated to match the numbers on the sheet.

Apparently (according to one of my players), they were updated but rolled back to the previous values

**Comment by mlenser** [comment]
Ugh, I lost some work when trying to merge branches... oy this won't be fun to fix.

**Comment by mlenser** [comment]
Looks like it was just burst spells and Acidic Spray. Hopefully nothing more.. Should be fixed when the build goes out in a minute
