### ISSUE TITLE
Conviction augment not worth the mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#130]
> You can expend 2 additional mana to be convicted if you miss on an attack, fail an ability check, or fail a saving throw.

I don't think the benefit of rolling 1d4 after you know you miss is worth 3 mana in the current system.

**Comment by mlenser** [comment]
It is intended to allow a reroll after the fact.
> You can expend 2 additional mana to reroll if you miss on an attack, fail an ability check, or fail a saving throw.

So:
- 1 mana: add 1d4 before the results are sure
- 2 mana: reroll before the results are sure
- 3 mana: reroll after the results are sure

Is that clear/better?

**Comment by mlenser** [comment]
Ahh, conviction is meant to be 1 mana.. hmm. Looks like I lost more spells. Let me restore them.
