### ISSUE TITLE
Smite the Faithless vs. Divine Power

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#134]
Smite the Faithless deals 2d6 + Spellcasting ability. That is 2 damage above what a spellstrike like Guiding Strike deals, but it also grants advantage on the next attack. So, it's not really worth to use it instead of Divine Power.

**Comment by Marcloure** [comment]
The same also happens with Lay on Hands compared spells such as Regenerate or Heal.

**Comment by mlenser** [comment]
So I should remove Divine Power then?

**Comment by Marcloure** [comment]
I believe that is for the best. Divine Power was too broad and I think it limits other options

**Comment by mlenser** [comment]
Acolyte
- Divine Power Channel Divinity removed as it is too broad and limits other options
- Lay on Hands and Smite the Faithless are given small heal/damage buffs
- Acolyte given a myriad of other Channel Divinity options: Bane, Bless, Convicted, Divine Detection, Divine Protection, Divine Shield, Divine Steed, and Divine Weapon


Occultist:
- Channel Power Witchcraft removed as it is too broad and limits other options
