### ISSUE TITLE
Feature Request: Add a page with everything on it (performance may be abysmal)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#136]
It could be at https://www.kryxrpg.com/everything for example.

I would want it to be just one huge page with:

* all the spells
* all the concoctions
* all the maneuvers
* all the feats

Purpose: being able to use the browser's "find in page" function (Ctrl+F / Cmd+F) to quickly find spells while running a session, or to quickly search for all instances of a certain word or phrase, as part of development.

Note - this will be a page with probably close to 1000 cards, so it will likely have performance issues. This is fine for now (especially if you include a warning in the link to this page wherever you put it).

**Comment by mlenser** [comment]
1,227 cards on a page.. oh boy.

https://5mana.kryxrpg.com/themes/everything
