### ISSUE TITLE
Add Sand Elementals to the Eidolon feat

### ISSUE THREAD

**Issue by eunomicZenith** [mlenser/kryx-rpg-issues#137]
What it says on the tin. For some reason they aren't there?

**Comment by itamarcu** [comment]
Fire, Acid, and Air elementals are also not there.

The elementals that do appear are: Ice, Water, Earth, Lightning.

**Comment by mlenser** [comment]
Fire, Acis, and Air have no matching subclass.

I've added Sand for Mummy.

**Comment by eunomicZenith** [comment]
Even if the Occultist has no subclass for fire/acid/air, it'd be nice to still have those options written in, since occultists do get to pick a theme outside their power source and people are going to want the options available.

**Comment by mlenser** [comment]
Eidolon is specifically built to support specific subclasses, not be a general option for all themes. Otherwise it'd list options by theme, not subclass and not be tied to the Occultist.

**Comment by eunomicZenith** [comment]
Okay. Just to check, would it be mechanically okay for a DM to allow an occultist to get an air elemental through this feat? Are the elementals balanced against each other?

**Comment by mlenser** [comment]
- The eidolon is intended to give a companion that represents your Patron. 
- No other feat offers an open-ended "any companion you desire".

So for those reasons I would not offer any other companions.

**Comment by eunomicZenith** [comment]
That's not what I asked. I asked if, assuming a Dungeon Master was willing to relax the rules on that, it'd be mechanically okay to allow other elementals on the basis of them being balanced to be just as strong as the other elementals.

**Comment by Marcloure** [comment]
All elemental companions have roughly the same power, yes.
