### ISSUE TITLE
Feat Suggestion: Premonition

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#138]
**Premonition** (2nd level feat, Divination)
> You see glimpses and fragments of the very near future, giving you preternatural knowledge of imminent dangers. You have a bonus to your initiative rolls equal to your Intelligence.

It could alternatively be named "Precognition".

**Comment by itamarcu** [comment]
(mirrors [Perceptive](https://www.kryxrpg.com/themes/feats/perceptive) (WIS) and [Rakish Audacity](https://www.kryxrpg.com/themes/feats/rakish-audacity) (CHA)).

**Comment by mlenser** [comment]
Premonition is more like the Spirit theme. I'd be in favor of a +Int to initiative, but I think the flavor is different. Not battle tactics, but something like that.

**Comment by itamarcu** [comment]
I wanted to call it Precognition and have it be Divination+Fate, but the word was taken by a maneuver :P

I think it needs to be some subset of Fate and Divination, and potentially Mind or Spirit, depending how theme-restrictive you want "seeing glimpses of the future" to be. To me, psychic future-reading powers are INT-related, while divine premonition is somewhere between INT and WIS, You could just have two feats if you think that's better.

**Comment by mlenser** [comment]
If you're seeing the future then it should be advantage, not Int.

**Comment by mlenser** [comment]
Glimpses into the Future added as a 2nd level feat

**Comment by itamarcu** [comment]
Wait, no, but now you made it identical to the Alert feat.

> You have advantage on initiative checks and you can’t be surprised.

and the Alert feat is strictly "better", in the sense that it's also 2nd level but open to all themes and not just this theme (Fate).

I think it should be +INT to initiative. If you think the flavor of glimpsing the future doesn't fit, perhaps it should be phrased differently - calculating people's next moves, or using your psionic powers (which are INT) to get these future-glimpses, or using telepathy to read people's intentions and react before them.

**Comment by Marcloure** [comment]
There are other ways to flavor a +INT to initiative feat. Maybe something like Keen Mind or Tactical Awareness,

**Comment by mlenser** [comment]
> There are other ways to flavor a +INT to initiative feat. Maybe something like Keen Mind or Tactical Awareness,

Exactly, Tactical Awareness or something similar could give +Int to initiative.

Seeing the future is definitely a yes or no thing, not a matter of how intelligent a character is.
