### ISSUE TITLE
Feat Suggestion: Savvy Skeptic

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#139]
**Savvy Skeptic** (2nd level Feat; Divination, Deceit)
> You have an advantage on Will saves to discern illusions for what they are. You can also make an attempt to examine an object for this purpose as a bonus action, instead of as an action.

**Comment by DalenWBrauner** [comment]
Oooh, I like this. The 'bonus action' bit feels a tad strong for a 2nd
level feat, though.
Also, I thought when you examined an illusion on your turn with an action,
it was a check, not a save? I'm not sure where to look to confirm that. I'm
a little confused if this feat would grant advantage in those cases as well
(or if it should).

**Comment by Marcloure** [comment]
I is a, Investigation check in RAW, here it's a Will saving throw.

**Comment by mlenser** [comment]
> The 'bonus action' bit feels a tad strong for a 2nd level feat, though.

I'm inclined to agree. While illusions are niche, a 2nd level feat to pretty much obliterate them is too much.

I'd say the first part is enough for a 2nd level feat.

**Comment by DalenWBrauner** [comment]
The 2nd part could also make for a good higher-level feat on its own. Maybe
with this one as a prerequisite, maybe 6th level?

**Comment by itamarcu** [comment]
yeah, that could work; or just two different 2nd-level feats, each with half of this one.

The intention was that this feat represents someone who's experienced illusory trickery a lot (perhaps an investigator, perhaps someone who fought against mages, perhaps someone who used to get hallucionations) - and is routinely confirming that things are real, touching them and looking at them more than the regular person.

**Comment by mlenser** [comment]
> The intention was that this feat represents someone who's experienced illusory trickery a lot

You can do that with the first part of the feat. The first + second almost completely nulifies illusions.

**Comment by mlenser** [comment]
Savvy Skeptic added as a 2nd level feat
