### ISSUE TITLE
Align elemental feats

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#140]
[Fiery](https://www.kryxrpg.com/themes/feats/fiery) gives you:

* Ignan language
* Advantage on charisma with fire elementals
* Ability to ignite flammable objects with a touch

This is awesome. I think the other elemental feats should be at the same power level. This means...

[Borealis](https://www.kryxrpg.com/themes/feats/borealis)'s "unhindered by difficult ice/water" should also be granted to [Coastal](https://www.kryxrpg.com/themes/feats/coastal). Alternatively, give Coastal something like swimming speed.

[Acidic](https://www.kryxrpg.com/themes/feats/acidic) and [Terran](https://www.kryxrpg.com/themes/feats/terran) should be merged into a single feat that gives both benefits (perhaps limited only to acid elementals and not earth elementals), and remove the spellcasting requirement. I think it'd then be comparable to Fiery. I also think the ability to create acid should take less than 10 minutes, when the fiery person can ignite things with merely an action. Fire is already much more useful than acid!

[Airy](https://www.kryxrpg.com/themes/feats/airy) should have an additional advantage. My suggestion: grant the ability to hold your breath for 15 minutes. Alternatively, just copy Storm.

**Comment by mlenser** [comment]
- Coastal: advantage on ability checks to swim and can hold breath for twice as long.

**Comment by mlenser** [comment]
Coastal now gives advantage to swim and the ability to hold your breath twice as long

**Comment by itamarcu** [comment]
Neat!

Now we need to align Terran and Airy. How do you think about my suggestions?

* Merge Terran and Acidic, removing the "earth" from "earth elemental" and the spellcasting requirement, calling the combined feat "Acidic".
* Add the following to Airy: "Your maximum High Jump and Long Jump distances increase by 1.5 meters (or 5 feet) each."

**Comment by mlenser** [comment]
- **Acid**
    - Terran and Acidic combined. It requires the ability to cast at least one spell from the acid theme as the acid has to come from somewhere
- **Air**
    - Airy now lets you jump twice as far and treat falls as being 10 feet shorter
- **Fire**
    - Fiery now requires the ability to cast at least one spell from the fire theme as the fire has to come from somewhere
