### ISSUE TITLE
Feat Suggestion: Hoverwalk

### ISSUE THREAD

**Issue by eunomicZenith** [mlenser/kryx-rpg-issues#141]
**Hoverwalk** (Air theme, Telekinesis theme, no idea for the level)
_Prerequisite: The ability to cast at least one spell._
> Some magical force allows you to move while hovering 3 centimeters off the ground, at the same speed as your walking speed. You must not be incapacitated to benefit from this feat. This has the following implications:
> - You don't leave footprints.
> - You ignore difficult terrains and ground-based hazards like slippery ice, muddy terrain, quicksand, the Grease spell, caltrops, and more.
> - You move more silently, without your feet making noises as they hit against the floor. A creature that tries to perceive you based on sound alone has disadvantage on its Perception checks.
> - You don't take damage from falling 20 feet or less.

**Comment by mlenser** [comment]
This is a spell similar to Levitate, but self only (as its much stronger). It's half way between levitate and fly, but can cost 1 mana if its only self.

Casting it at will would be a 6th level feat like other at will spell feats.

**Comment by eunomicZenith** [comment]
I suggest a duration of 1 hour/mana, being able to affect up to two creatures baseline, and being augmentable to affect 2 more for every extra mana.

**Comment by DalenWBrauner** [comment]
I agree that the feat and baseline versions of the spell should apply it only to yourself. Augments for more creatures are a good idea. The duration, even with concentration seems a bit long, but I'd be fine with it.

I could also see it having an augment that gives you advantage on things like climbing checks.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/81778489-44c5d100-94f3-11ea-9203-b594195dad4f.png)

Hovering 1 inch isn't enough to lessen fall damage, imo.

**Comment by eunomicZenith** [comment]
I'd like an augment to target more creatures.

**Comment by mlenser** [comment]
You can target two additional willing creatures for each additional mana expended. The creatures must be within 30 feet of each other when you target them and must remain within 30 feet of you or they stop hovering.

**Comment by eunomicZenith** [comment]
Sounds good.
