### ISSUE TITLE
Feat Suggestion: Crafty

### ISSUE THREAD

**Issue by eunomicZenith** [mlenser/kryx-rpg-issues#142]
**Crafty** (2nd level, Creation)
> You become capable with the Engineering skill. If you are already capable, you become proficient. If you are already proficient, you gain expertise with it.
> Choose two tools, or the same tool twice. You become capable with those tools. If you are already capable, you become proficient. If you are already proficient, you gain expertise with them.

**Comment by mlenser** [comment]
Per https://github.com/mlenser/kryx-rpg-issues/issues/147 I'd like to see tools not really be part of the game, so the tools part should be replaced I think,

**Comment by mlenser** [comment]
Closing this. We could use an engineering skill, but tools don't exist as proficienies as part of #147. So a new idea could be created, but this one doesn't work.
