### ISSUE TITLE
Feat Suggestion: Sanguine Surge

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#143]
**Sanguine Surge** (2nd level feat, Blood)
> You can force your body to overexert itself for a short duration. As a bonus action, you may become Hasted 4 until the start of your next turn. When the condition ends, you gain a level of Exhaustion.

**Comment by Marcloure** [comment]
Adrenaline Rush is a better name, I think

**Comment by itamarcu** [comment]
Sure, we can go with that! I was just making a small reference to another D&D-related thing I like :P

**Comment by mlenser** [comment]
Similar to the discussion on https://github.com/mlenser/kryx-rpg-issues/issues/152 this feels like an active thing that should be a spell or maneuver,

Though if this were a cantrip then it's basically a lesser version of action surge in some ways (1 attack) and better in others (speed). 1-2 uses per day or 2-3 on a more difficult day would make this incredibly powerful.

This feels like an active power that it needs a cost (mana/stamina) associated with it so it'd fit better a spell and/or maneuver imo.

**Comment by DalenWBrauner** [comment]
> Though if this were a cantrip then it's basically a lesser version of action surge in some ways (1 attack) and better in others (speed). 1-2 uses per day or 2-3 on a more difficult day would make this incredibly powerful.

Perhaps it just needs a stronger drawback? Maybe even one that scales each time you use it without a long rest.

Though it might be odd to call a _cantrip_, as I don't believe it should require any magical abilities. Would it be better as a maneuver, then?

**Comment by itamarcu** [comment]
this makes you take a level of exhaustion - that's a really steep cost! after the first time you use this you're almost half as slow and more vulnerable to attacks and reflex saves; after the second time you use this your attacks all get disadvantage and you're definitely at half speed. Ability checks, too, though that's less relevant in combat.

Those drawbacks all get restored only after long-resting and only by one exhaustion level at a time.

I also don't think it should be limited to spellcasters or limited to martials; hence, a feat makes the most sense (or, barring that, a spell and a maneuver that do the same thing). I view this as similar to [Consumptive Power](https://www.kryxrpg.com/themes/feats/consumptive-power) but useful for both casters and non-casters.

**Comment by mlenser** [comment]
> this makes you take a level of exhaustion - that's a really steep cost

It's really not that steep. You can easily do it in the "last fight of the day" with almost no consequences. Casters can do it more as the consequences of attacking at disadvantage are almost nothing for them and moving slower isn't the end of the world.

This is basically a lesser version of action surge in some ways (1 attack) and a greater version in others (speed). 1-2 uses per day or 2-3 on a more difficult day makes this far too much for a 2nd level feat.

**Comment by mlenser** [comment]
This needs heavy refinement so I'm going to close the issue. It can be reopened if it is refined.
