### ISSUE TITLE
Indestructible Life should belong to the Life theme (not just Death)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#144]
https://www.kryxrpg.com/themes/feats/indestructible-life

Seems reasonable to me that a feat that lets you live longer would be related to life.

Also - maybe the feat can be improved a little bit, to grant some minor mechanical advantage?

**Comment by DalenWBrauner** [comment]
I agree with this being added to Life, not so sure I agree with the
mechanical benefit (unless it was very, very minor); It's common/fair to
have a 2nd-level feat comprised of almost entirely of flavor.

I'd also argue that "Immunity to spells that age you" is actually a
mechanical benefit, though I don't see any in the Time theme. I could have
sworn there were effects that could cause this, albeit I'm not sure if
players could ever cast them...

**Comment by mlenser** [comment]
I think this feat is the antithesis of the Life theme. Maybe the flavor isn't clear enough, but this is very much in the same vein as a lich extending their life. It's intended to be unnatural.

**Comment by DalenWBrauner** [comment]
Ahh, I see. In that case a bit of flavor and maybe even renaming the feat
would suffice.

I'd definitely propose a Life feat that can extend your natural lifespan,
though. Perhaps no immunity to aging, but maybe something that slows it and
prevents death by 'natural causes' (think druid elders that have lived for
more than hundreds of years).

**Comment by eunomicZenith** [comment]
The feat is currently very flavor-neutral. You might have intended for it to be unnatural and lich-like, but it doesn't show, atm. Still, I do think that yes, the Life and perhaps the Time themes might want life extension feats. For Life, maybe it could be named 'Life Springs Eternal' and for Time it could be named 'Timeless' or some variation thereof?

**Comment by mlenser** [comment]
For time I can surely see the flavor of continuously rolling back the clock. For Life I don't see the flavor.

**Comment by eunomicZenith** [comment]
5e Druids have a lv 20 feat that makes them age much more slowly. There's also a few examples of "old ascetic that has lived wayyyy longer than they should have".

**Comment by mlenser** [comment]
> Starting at 18th level, the **primal magic** that you wield causes you to age more slowly. For every 10 years that pass, your body ages only 1 year.

very different than the life theme :)

**Comment by eunomicZenith** [comment]
I see you focus on the wording of 'primal magic' not being about life as quibbling at best, and could easily retort that the 'primal magic' involved in that feature is clearly about lifeforce, and how primal magic generally involves a connection with nature, etc. I personally do believe Life should get its own life extension feat. As you're the guy who owns the website and made the system, I can't do much more than tell you what I wish you did, and you are in a position to simply ignore me, dismiss whatever arguments I may try to make, or disagree with them.

**Comment by mlenser** [comment]
Primal magic is about nature. Not like Divine magic which is what Life is about. This split is evident in the power sources https://www.kryxrpg.com/themes

> I personally do believe Life should get its own life extension feat. 

If there is flavor for it, then sure. The druid flavor above is nature (primal magic), not Life/divine magic. Those are explicitly different in my system.

**Comment by itamarcu** [comment]
Then it should be flavorful for one of the primal power source themes (which are mostly elements, and Beast and Plants and Chaos) to allow this.

Perhaps this feat should be in the Plants theme? After all, the oldest tree in the world is over 4700 years old.

**Comment by mlenser** [comment]
I had an idea for the Life theme: Fountain of Youth. Though based on https://en.wikipedia.org/wiki/Fountain_of_Youth that's a bit more Water theme.. hmm..

**Comment by DalenWBrauner** [comment]
I think that's like saying Holy Water should be in the Water theme :stuck_out_tongue: 

Life Theme: "Gift of Life": Healing energy flows all throughout your body, gradually undoing scars and strain. This slows down your aging process, and reduces any attempts to age you by unholy or necrotic means. You can still die of natural causes, however.

Plants Theme: "Eternal Growth": Your connection with the energy flowing through nature increases your lifespan, preventing you from dying from old age or 'natural causes'. You still age at the same rate, however.

**Comment by mlenser** [comment]
I think the above is the best option.

However I think a 2nd level feat for this purpose is probably not correct. When this appears in 5e it appears at level 14-18 in various classes and subclasses. I think these need to be high level feats. They aren't mechanical, but people spend their whole lives looking for immortality. It shouldn't be freely available at 2nd level.

**Comment by mlenser** [comment]
- **Death**
    - Indestructible Life now has better flavor and moved from 2nd level to 14th level
- **Life**
    - Gift of Life feat added
- **Plants**
    - Eternal Growth feat added
