### ISSUE TITLE
Explicitly state that you can't have more than your total resources

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#145]
I know this is clear by design, but people will surely ask if you can make a short rest to regain half your total mana and go beyond the your maximum.

"You can't have more mana than the value on the table" should suffice.

**Comment by mlenser** [comment]
One design goal is to have concise wording. `regain`, inherently means to gain again. If you've never had it, you can't regain.

The Heal spell for example says:
> As an action, a creature of your choice that you can see within 60 feet regains 3d8 hit points. This spell has no effect on undead or constructs.

No where does it specify that the user cannot gain more hit points than their maximum as that is inherent in the wording, or inherent in the rules. At a glance I don't see rules specifying hit points can't go over your maximum. Though if that exists somewhere then I can add the same to https://5mana.kryxrpg.com/themes/rules

**Comment by Marcloure** [comment]
Yeah, you are right. Regain already means that you can only gain what you have lost.

**Comment by itamarcu** [comment]
5e uses the "regain" word but still has this explicit rule about hit points:

> When a creature receives healing of any kind, hit points regained are added to its current hit points. A creature's hit points can't exceed its hit point maximum, so any hit points regained in excess of this number are lost. For example, a druid grants a ranger 8 hit points of healing. If the ranger has 14 current hit points and has a hit point maximum of 20, the ranger regains 6 hit points from the druid, not 8.

I think you could add this as a short snippet for mana/stamina/etc.
