### ISSUE TITLE
Tools and Proficiencies

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#147]
Spawning off a discussion on Discord, where Kryx mentioned:

> https://www.kryxrpg.com/equipment/tools of the things that aren't in skills:
> - Artisan's tools seem entirely backstory or NPC based. 99% pointless on a PC.
> - Gaming sets are super niche
> - Musical Instruments are just a prerequisite for performance

and

> There is no proficiency in thieves tools, just the Stealth skill. No proficiency in the compass, just the Nature skill. Musical Instruments seem very verbose for a purpose that is covered by the Performance skill 

and

> You could have proficiency in performance and the flavor is that you're really good at the Lute for example. No need to have the musical instruments proficiency

It seems like different kinds of tools need to be treated differently.

Some types of "tools" like lockpicks are a countable, consumable and mostly-prerequisite resource.
When it comes to mana and catalysts, characters are assumed to always have whatever items and materials they need to use them. This can work in other places, too- if your character is an established thief, your DM can probably handwave that they would have lockpicks. Depending on your world, players and DM, some archers may not need to keep track of exactly how many mundane arrows they own. It could then be interesting for the DM to these away, but there's no one-size-fits-all for the mechanical consequence for that. An archer can't fire without arrows. Alchemy with bootlegged ingredients might go haywire. Lockpicking with improvised lockpicks is mostly just harder.

On the other hand, some items such as a sailor's spyglass might grant mechanical benefits that a character wouldn't have by default. A compass is a useful tool with a unique mechanical purpose that is not strictly necessary for navigation. These items don't require much or any special training to use, but some tools (e.g. lockpicks, musical instruments) certainly do. These are more like optional items that confer bonuses.

And on the topic of gaming or gambling sets, I'm with Kryx: there's value in dividing the tools that are just for flavor and the tools that are for mechanics.

Perhaps a good division would be:
- Consumable, commonplace, needed for a task? Assume a character who can perform that task would have them by default. A character who doesn't normally have the skills for that task might need to acquire them.
- Nonconsumable, not needed but provides benefit? Maybe just gives advantage, or a small bonus to the role, or boosts your proficiency, etc.
- Provides flavor to the character, but would rarely come up in play outside of downtime? Keep it in the flavor department, let players and DMs do what they think makes sense. e.g. which musical instruments you can play should likely fall under flavor, even though playing them falls under performance.

Also one comment by @itamarcu I found useful, about choosing between tool proficiencies:
> I think the issue is that sometimes you're basically forced to choose between a fluff choice and a crunch choice
> "do I want to be really good in Dragon Chess, or really good in smithing?"

The discord transitioned into convos about Downtime from there, which while related, I think can be kept seperate. Conversation about WHEN a tool proficiency might be used is probably fine, though.

**Comment by Marcloure** [comment]
I'm fine without tools. In all my years playing 5e, I very rarely used them both as a player or as a DM. Imo, if a character has a specially helpful tool, they gain advantage on the related skill (I think Xanathar recommends something like that?)

**Comment by mlenser** [comment]
I would pretyt much never follow XGtE to give advantage for tool usage.

I believe most tools are a requirement for the activity, but should never give advantage. Being able to play the piano for example is a requirement to be able to use performance with a piano. Same with singing.
I believe that to be the case for everything currently listed under https://www.kryxrpg.com/equipment/tools

Some other tools in 5e:
- Disguise Kit: prerequisite
- Forgery Kit: prerequisite
- Herbalism Kit: prerequisite
- Navigator's Kit: prerequisite (you could maybe get by with the stars if you had training
- Poisoner's Kit: prerequisite
- Thieves tools: prerequisite

Without such prerequisites I would give disadvantage or much worse. For example if you're trying to navigate a boat without a Navigator's Kit and without extensive training to use the stars then I'd definitely give disadvantage.

**Comment by DalenWBrauner** [comment]
> Without such prerequisites I would give disadvantage or much worse. For example if you're trying to navigate a boat without a Navigator's Kit and without extensive training to use the stars then I'd definitely give disadvantage.

I agree, but I wonder if that's actually worth writing out explicitly. I think a DM understands that a player cannot navigate the seas or sail the ship if they've never been on one before. You can't pick up a musical instrument and _just play it._ In other words, I think those prerequisites are pretty implicit and understood.

In which case, I liked one of the suggestions in the Discord- instead of enumerating all possible toolkits, why not a general rule of thumb that characters, without training in these areas, cannot perform these tasks? Lockpicking, disguises and navigation can then be provided as examples, and DMs will understand that other scenarios (perhaps repairing weapons/armor or painting a landscape) may follow.

The tricky part then is how you'd allow players to gain these tool proficiencies- maybe, simply, each background provides one (or some equivalent)? That's more or less how they're assigned already.

**Comment by mlenser** [comment]
I think you remove them entirely and let it all be up to flavor.

Players dont have proficiency in running or jumping or the scalpel to perform medicine.

**Comment by mlenser** [comment]
Tools section merged into the gear section. These items are required to use some skills, but the skillfulness of a character is really up to the GM and unrelated to the proficiency system.
