### ISSUE TITLE
Archival Knowledge feat is too strong

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#148]
https://www.kryxrpg.com/themes/feats/archival-knowledge

Functionally, this grants Capable in 15/18 skills (because all skills are mental except for Acrobatics, Athletics, and Stealth), plus improves your proficiency further with one of them.

Suggestion for how to fix it:

* Raise the feat's minimum level
* Replace encompassing passive capability with something such as "once per day, you can have expertise in one of these skills for a single check"
* Remove the first part of the feat (and maybe still raise its level?)
* Replace it with giving you skill increase in just 1-3 skills

**Comment by mlenser** [comment]
Archival Knowledge level changed from 4th level to 2nd level and reworked with the ability to become capable with a skill for an hour.
