### ISSUE TITLE
Bestial Senses feat is redundant

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#149]
The effect of Bestial Senses is already available to all classes via the general feat "Competency".

However I'd say that there is still design space for such a feat, but it either requires an additional effect to make it stand out from the generic feat, even if it is little more than a ribbon, or a rework.

One potential change could be a choice of improving one sense:
- Sight: Improve night vision by one stage (normal vision to low light, low-light to dark vision 60ft, dark vision 60ft to dark vision 90ft) 
- Hearing: Gain Tremorsense out to a range of 5ft
- Smell: Gain blindsense out to a range of 5ft

I'm not certain about the balance of super-short range blind/tremorsense, but the idea is that at an extremely short range, such a character could pinpoint the scent or the minute noises an unseen character might make. To me it seems cool (much more flavourful and fun than proficiency) , but not actually useful very often, so probably not busted.

**Comment by mlenser** [comment]
See the latest changelog:
- Competency changed to only allow you to improve a skill from your class skill list

**Comment by mlenser** [comment]
Darkvision/Tremorsense/Blindsight are all much stronger than a 2nd level feat can offer. Bestial Sense should have a ribbon/niche aspect like the other 2nd level skill feats, but especially the Sight option seems far too strong. The super short range could be ok.

**Comment by itamarcu** [comment]
How about copying this feature from many 5e beasts?

> **Keen Hearing and Smell.** The creature has advantage on Wisdom (Perception) checks that rely on hearing or smell.

**Comment by mlenser** [comment]
I think that sounds good, but not sure it'd be good in practice. If we allow them to choose one of the following:
- Hearing: Advantage on Wisdom (Perception) checks that rely on hearing.
- Sight: Advantage on Wisdom (Perception) checks that rely on sight.
- Smell: Advantage on Wisdom (Perception) checks that rely on smell.

It's perma-advantage to Perception once Sight is chosen. That's much too strong for a 2nd level feat. That's a 6th level+ feat.

**Comment by eunomicZenith** [comment]
I mean, the easy thing to do is to just not include "sight" among the senses you can get advantage to. Hearing and smell are far less commonly used senses. Perhaps just give advantage in both of those.

**Comment by itamarcu** [comment]
Even just an advantage on a single one of them (player's choice) is good, IMO. If a player knows that they have an advantage on hearing, they will try to listen through doors, walk silently and scout ahead, If a player knows that they have an advantage on smelling, they will try to track enemies, sniff for fresh corpses, etc.

**Comment by Lamorak11** [comment]
I feel like changing Bestial Senses to be the same wording as "Keen Hearing and Smell" is probably worth a 2nd level feat in and of itself. Maybe a choice of hearing or smell with the skill would work, but I'm not a massive fan of skill feats like those (they're just a bit boring). 

So, I'd vote to make it mirror keen hearing and smell.

**Comment by mlenser** [comment]
> So, I'd vote to make it mirror keen hearing and smell.

So no skill, just advantage on perception to hear and smell? Is that truly better (less boring) than Perception + 1 other sense?

**Comment by itamarcu** [comment]
Actually I think it would be better to have it exactly that.

**Bestial Senses** (2nd level feat, Beast)
> You have advantage on Wisdom (Perception) checks that rely on hearing or smell.

If it's both proficiency and advantage it might be too much (as this feat would be providing effectively a +1/3 + advantage when it's applicable). Besides, this way people can combo this feat a bit better with other feats or class features that improve your Perception proficiency (which many players want to do) and you won't have to make a permanent choice and mark it down on the feat (simpler!).

**Comment by Lamorak11** [comment]
> Is that truly better (less boring) than Perception + 1 other sense?

Hmm. Probably not actually. I'm happy with either.

**Comment by mlenser** [comment]
Bestial Senses reworked to give advantage on Perception checks that rely on hearing or smell
