### ISSUE TITLE
Arcane Spears allows melee cantrips to be cast at range

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#150]
It's not that it would be powerful, but the feat allows Primal Savagery and Stonefist to be cast at 60 ft., which I don't think is the intention.

**Comment by DalenWBrauner** [comment]
My suggestion, adapted from the 'Distant Spell' metamagic:

When you cast a cantrip that has a range of 5 feet or greater, increase its range by 60 feet. When you cast a cantrip that has a range of touch, the range of the cantrip becomes 30 feet.

**Comment by DalenWBrauner** [comment]
Obvious alternatives for touch cantrips:
- No range increase
- 5ft range increase
- 15ft range increase

**Comment by mlenser** [comment]
When you cast a cantrip that has a range of 30 feet or more, its range is increased by 60 feet.

**Comment by mlenser** [comment]
Arcane Spears only extends the range of cantrips that already have a range
