### ISSUE TITLE
Move Purify Food and Drink to Holy

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#151]
It currently sits in Light, which I believe is a mistake

**Comment by mlenser** [comment]
Sunlight is a great purifier.
![image](https://user-images.githubusercontent.com/235857/81036725-6c3bee80-8ea0-11ea-9f6d-4c51afed327b.png)

In the modern age it feels like Light could be seen as purifying. In fantasy I wonder if Life is a better choice than both Holy and Light.

**Comment by Marcloure** [comment]
Yeah, Life is also a good option. I think Light per se is a bit weird, purifying light feels more like a holy thing than a property of the light

**Comment by mlenser** [comment]
I think it's quite important to differentiate Holy from its other aspects of Life and Light. We should do our best to limit the crossover.

**Comment by mlenser** [comment]
Light and Water both could have purifying properties. I currently have Purify in the Water theme though looking it over now I'd say water can only really resolve some of the minor things so maybe not the best idea.

**Comment by itamarcu** [comment]
Fire also has some purifying qualities (cauterizing flesh, cooking food, pasteurisation)!

**Comment by eunomicZenith** [comment]
Now we absolutely need a Fire cantrip named "Pasteurize". :)

**Comment by DalenWBrauner** [comment]
I strongly agree that this is not a Light spell. All other spells in the
Theme make direct reference to the visual properties of Light, which is
what makes it distinct from the godly, righteous and people-serving powers
of Holy (e.g. sanctuary, create food and water), or the ailment-cleansing,
healing properties of Life (blessed touch, antiplague, purity potion,
Heal's augment Cure, Restoration...)

**Comment by mlenser** [comment]
Life is where all the anti poison/disease spells are so that makes the most sense. Holy does not have such spells.
