### ISSUE TITLE
Create a "sand in the eyes" maneuver

### ISSUE THREAD

**Issue by eunomicZenith** [mlenser/kryx-rpg-issues#154]
Tossing sand into someone's eyes to blind them is a classic dirty trick. It'd be nice to have a maneuver to represent this. It could be a reflavored Blind. (Obviously in the Sand theme.)

**Comment by itamarcu** [comment]
Note: we already have the [Blind](https://kryxrpg.com/themes/maneuvers/blind) maneuver, but it's restricted to the Shadow theme. We also have the [Sandblast / Sandblasting Blade](https://5mana.kryxrpg.com/themes/spells/sandblast) spells, but those require mana. Sand is plentiful and should not be limited to fancy spellcasters!

**Comment by mlenser** [comment]
I think Blind's two uses should be split. "you can blind the target by striking a sensitive area or throwing something in its eyes":

- Sensitive area stays in Shadow
- "Throw sand/dirt/whatever in eyes" added to earth/sand/somewhere else?

**Comment by itamarcu** [comment]
Throwing something in its eyes is definitely Sand, and I don't really think any other theme should have it (maybe deceit, maaaybe pestilence)

**Comment by Paulorpribeiro** [comment]
Do you really need to have the sand theme to throw sand in someone's eyes? It's a classic maneuver and just a dirty trick, not related to sand specifically. If you throw snow, would it be the ice theme? Earth? How about leaves? I'd say it should go to deceive or stay in the shadow theme.

**Comment by eunomicZenith** [comment]
Maneuvers are meant to be non-magical, which means that any cutoff about which theme gets what is going to end up being pretty arbitrary and frivolous, otherwise we end up with every 'physical prowess' maneuver in Skirmish/Vanguard/Beast and everything that can be categorized as a dirty trick exclusively in Deceit. Other themes want maneuvers too!

**Comment by mlenser** [comment]
> we end up with every 'physical prowess' maneuver in Skirmish/Vanguard/Beast and everything that can be categorized as a dirty trick exclusively in Deceit/Shadow. Other themes want maneuvers too!

That's what we currently have. I think the solution is to split these themes:
- Skirmish -> Air
- Vanguard -> Earth/Fire
- Protection -> Earth/Water
- Marksmanship -> ?

**Comment by Marcloure** [comment]
That some wuxia fantasy there! xD

**Comment by Paulorpribeiro** [comment]
I'm not 100% on board, but following that logic, perhaps
Markmanship -> Beast?
Deceit -> shadow/death

**Comment by itamarcu** [comment]
Protection should be Ice, IMO :P

But why are we splitting the martial themes? I think they're great right where they are, and it's just some maneuvers that should be tweaked or added that are the issue.

For this particular maneuver, I think putting it in Deceit+Shadow makes sense. They're both Martial themes, plus have decent spells, so half-casters shouldn't have an issue picking them.

If we want maneuvers for "throwing <theme> at someone", I think this should be limited to the bonus action mana spells, which exist already (e.g. Sandblasting Blade).

If we still *really* want it, we can just duplicate this; have both this "Blind" maneuver (single target ongoing blind and damage added to attack) and a second "Throw Stuff" maneuver for the themes of Sand, Blood, Plants, Earth, Ice (or whatever).

**Comment by mlenser** [comment]
> I'm not 100% on board, but following that logic, perhaps
Markmanship -> Beast?
Deceit -> shadow/death

Huh? Deceit is deceit. It's a complete theme. Marksmanship is nothing like Beast.

**Comment by mlenser** [comment]
> But why are we splitting the martial themes? I think they're great right where they are, and it's just some maneuvers that should be tweaked or added that are the issue.

We have specific themes and catch-all themes. The catch-all themes are problematic and have been for a long time. I've removed some others along the way.

> If we want maneuvers for "throwing <theme> at someone", I think this should be limited to the bonus action mana spells, which exist already (e.g. Sandblasting Blade).

Throwing sand in someone's eyes (blind without the damage) as a bonus action is surely a good maneuver for sand/deceit.

**Comment by Paulorpribeiro** [comment]
That s why I'm not 100% on board with it, elemental themes are also complete, and if they don't have maneuvers are because they are too magical/supernatural. For me if you want to your weapon to shake the earth or send shockwaves when you swing it, you are looking to be a half caster and use the strike spells.

**Comment by mlenser** [comment]
Maneuvers wont cross that line. They will remain mundane.

But elemental themes are not "complete" except for Earth. None have more than 1 or 2 maneuvers, but there is plenty of flavor to work off. Skirmish for example is very much in the same vein as Air.

**Comment by Marcloure** [comment]
I believe this retheming would also affects the... well theme of the maneuvers. If we call lunge a Fire maneuver, that has a very different feeling than a generic Vanguard maneuver. I as joking when I said about wuxia fantasy, but it's also true. If each maneuver is related to an element, that is another kind of fantasy.

Now, I'm a fan of wuxia and Avatar, but this change does have it's impact on how the characters are portraited. It's much closer to Legends of the Five Rings, for instance.

**Comment by mlenser** [comment]
Many Vanguard maneuvers moved to Earth and the world didn't break ;)

Nimble and similar maneuvers in Skimish could surely move to Air without issue. Let's start there.

**Comment by Marcloure** [comment]
Hm, more or less. The hobgoblin warrior at my table has been learning from dwarves recently. Whenever he uses an Earth maneuver, it feels much more like something he learned from them than the Vanguard maneuvers that feels much more like it came from his hobgoblin warband.

**Comment by mlenser** [comment]
I've created https://github.com/mlenser/kryx-rpg-issues/issues/156 to discuss this further. Please take any further comments there

**Comment by mlenser** [comment]
Sand in the Eyes maneuver added
