### ISSUE TITLE
Divide the Martial Power Source

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#157]
I've been brainstorming this for a while, but posting now in response to #156.

Right now, we have a strange situation for Gishes and Maneuvers. When it comes to Themes like Earth and Shadow, the only way for Warriors to have access to their maneuvers is if those Themes are in the Martial Power Source. But then this means that all Gishes, which also have that Power Source, inherently have those themes as well. This leads to either Gishes having access to magic from Themes outside their caster's Power Source, or we have to put oddly specific rules in place to prevent that from happening.

Or, we could split the Martial power source in half.
Every purely martial theme (e.g. marksmanship, skirmish, vanguard) can remain in the more "standard" martial Power Source, which for now I'll call "Warfare." Then all of our magic-leaning Themes that also have maneuvers can move to a new martial Power Source, which for now I'll call "Martial Arts."

All you have to do from there is give Gishes access to Warfare, and Warriors the unique ability to access both. (As a bonus, that means Warriors have something cool and unique now.) And if we like the flavor for Martial Arts, then conceivably that could be a Power Source for the Monk, etc.

But we wouldn't have to flavor our divide quite like that- I'm open to other suggestions. But I think this gives us a better design space for Maneuver-focused Themes, as well as Maneuvers within spell-focused Themes, without either leaving out Warriors of giving Gishes access to literally everything.

**Comment by DalenWBrauner** [comment]
Obviously we can debate what should go where, but here's the concept visually:

Warfare Power Source:
- Courage
- Deceit
- Marksmanship
- Protection
- Skirmish
- Vanguard
- (Fear?)

"Martial Arts"(?) Power Source:
- Beast
- Charm
- Earth
- Shadow
- (Air? Fire? Water? Sand? etc)

Each Class's Power Sources:
- **Warriors:** Warfare and Martial Arts
- **Half-Casters:** Warfare, their casting Power Source
- **Monks:** Martial Arts (but that's just for flavor)

**Comment by Lamorak11** [comment]
Don't Courage and Deceit (and Fear) have spells in them that you wouldn't want gish characters to automatically have access to? Surely in your system they would need to be part of "martial arts"?

**Comment by DalenWBrauner** [comment]
I think that makes sense- it just depends on how problematic it is for all Gishes to have access to those spells.

**Comment by Paulorpribeiro** [comment]
I really like that divide, one power source of purely "feats of strength and skill" for those who doesn't want a magic/supernatural character and one power source of those maneuvers (that many people love around here and on many tables) that walk the line between magic and martial. l like the warfare martial arts names too. But I think warriors shouldnt have access to both. They should have an ability (similar to the mage) to pick themes from the martial arts power source.

**Comment by mlenser** [comment]
> those maneuvers that walk the line between magic and martial.

There are no such maneuvers because maneuvers are inherently nonmagical.

The martial power source is just a dumping ground for all themes with maneuvers. It's not the best design, but I haven't thought of a better option currently.

> This leads to either Gishes having access to magic from Themes outside their caster's Power Source, or we have to put oddly specific rules in place to prevent that from happening.
What you've suggested doesn't remove these specific rules as many of the themes in "Warfare" have spells and would need the same wording.

**Comment by DalenWBrauner** [comment]
>What you've suggested doesn't remove these specific rules as many of the themes in "Warfare" have spells and would need the same wording.

Not if the "Warfare" Power Source has just the martial-exclusive Themes:
- Protection
- Skirmish
- Vanguard
- Marksmanship
- ~~Courage~~
- ~~Deceit~~
- ~~(Fear?)~~

**An aside about the listed feats:**
And even then, if we examine Courage specifically, we can see that a lot of its spells and maneuvers are very very similar- its maneuvers are powered by sheer force of battle charisma, and its spells are largely the same effects powered by mana. In other words, it's probably fine for Gishes to have access to these spells if we wanted to give them access to these maneuvers. This is different from, say, Deceit, where the maneuvers are more akin to skullduggery and the spells are more akin to conjuring illusions. And I listed Fear because, while it has little in the way of maneuvers, as I was dividing them I realized many of its spells (e.g. Frighten) could have maneuver counterparts- but that's a separate issue. So perhaps Courage and Fear should be included, Deceit left out.
**/aside**

>The martial power source is just a dumping ground for all themes with maneuvers. It's not the best design, but I haven't thought of a better option currently.

Which is why it could really use some flavor! I think that's easier to do if we divide it: the "Warfare" Power Source is all about themes and maneuvers that you would learn from armies and guards. Vanguard and Protection are invaluable to soldiers. Marksmanship for siege defense. Skirmish for assassins. Taking this approach I think even gives us a better framework for how we might create better Martial themes- perhaps one could exist around mounted combat, or themes about one-on-one dueling versus with an army at your back.

Sadly "Martial Arts" isn't a perfect counterpart. While Earth, Shadow, and any Primal themes would match, themes like Beast and Deceit are much more of a stretch flavor-wise.
But despite that conflict, I'm still convinced this suggestion, even when incomplete:
- Gives more flavor to Martial themes and classes
- Addresses the Gish problem cleanly
- Consequently, encourages more maneuvers to exist outside of themes in the current Martial Power Source

While #156 proposes taking Maneuvers out of martial themes and diving them across other themes, this suggestion is the opposite approach. I feel #156 proposes simply to do the last bullet, without addressing (and actually exacerbating) the existing Warrior/Gish theme availability problem.

**Comment by Marcloure** [comment]
> The martial power source is just a dumping ground for all themes with maneuvers

Isn't that also true for Alchemy? 

This happens for both power sources because, while magic can come from different sources and have different aspects, alchemy and martial prowess are not granted by different things.

Of course, we can divide Martial in something like Dalen is saying, but I'm still not convinced that is the better way to go.

**Comment by DalenWBrauner** [comment]
> while magic can come from different sources and have different aspects, alchemy and martial prowess are not granted by different things.

Hrmm, good point. I'd argue that's achieved with the "Warfare" vs "Martial Arts" split: maneuvers you'd learn in a militarized region vs maneuvers you'd learn in a dojo. But the more I look at it, the more that feels like an "East vs West" divide I'm not sure belongs in the game.

I still have that _on to something_ feeling here, but maybe that's just me. If nobody has any additional suggestions, I can live with closing this.

**Comment by DalenWBrauner** [comment]
>Isn't that also true for Alchemy?

Man, now you've got me thinking of power sources for Chemistry (learned through scientific study) and something like Natural Remedies, (learned through passed-down traditions). But perhaps more aimless brainstorming is suited for the Discord.

**Comment by mlenser** [comment]
> I still have that on to something feeling here, but maybe that's just me

I agree that the Alchemy and Martial Power Sources are not good. I just haven't come up with a better option.

Realistically we could allow them to learn from any theme, which is basically what I did with the Alchemy and Martial Power Sources.

**Comment by DalenWBrauner** [comment]
I thought of that as well, and if we head in that other issue's direction,
I don't think you'll have much choice.

Except that property only makes sense for Warriors and Alchemists, unless
you continue to also use the weird maneuvers-are-seperate exception rule
for Gishes.

**Comment by DalenWBrauner** [comment]
Martial Power Sources no longer exist :)
