### ISSUE TITLE
Restrict "Corrode Armor" maneuver to creatures with acid attacks

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#158]
https://www.kryxrpg.com/themes/maneuvers/corrode-armor

It's the only Acid maneuver, and it's clearly something magical.

If the intention is to have it be used by [Acid elementals](https://www.kryxrpg.com/monsters/huge-acid-elemental)... well, they already have both the [Corrode](https://www.kryxrpg.com/themes/spells/corrode) cantrip and the [Corrosive Weapon](https://www.kryxrpg.com/themes/spells/corrosive-weapon) spell, so I don't think they really need this maneuver to exist (and if they do, better add a spell for it, IMO, as this does not fit the idea of players' maneuvers).

**Comment by mlenser** [comment]
I've reworded the title. It could be used by an acid elemental, a acid elemental companion, or a PC who turns into an acid elemental.

**Comment by itamarcu** [comment]
Is there any other example of a maneuver that is restricted?

**Comment by Marcloure** [comment]
Better add it as an action with recharge or simply an effect of the elemental attack then, no?

**Comment by DalenWBrauner** [comment]
This isn't strictly magical- concoctions can conjure acid, too.

**Comment by mlenser** [comment]
> Better add it as an action with recharge or simply an effect of the elemental attack then, no?

It is also used by Oozes.

Corroding armor is not magical, especially not for Oozes. It should be a maneuvers, thematically.

**Comment by mlenser** [comment]
> Is there any other example of a maneuver that is restricted?

Nope, but surely others could exist if there is a need.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/81139904-c489f380-8f67-11ea-8af5-3cdd3fc51e81.png)

**Comment by Marcloure** [comment]
Isn't the standard form "as a reaction which you take when you make a weapon attack that deals acid damage"? Otherwise, a creature with acid attack can use this maneuver when it makes an non-acid weapon attack (which may be ok?)

**Comment by mlenser** [comment]
That's better
![image](https://user-images.githubusercontent.com/235857/81140503-d79dc300-8f69-11ea-87e5-16a4730869da.png)
