### ISSUE TITLE
Update giant insect concoction/spell?

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#164]
Giant Insect and Giant Insect Potion still use monsters instead of the companion form, and the insect make its attack using the caster spellcasting ability.

Maybe the concoction and spell should insect companions forms?

**Comment by Marcloure** [comment]
Though then I'm not sure what is the use of Giant Insect spell instead of Call Beast. The potion should still exist, I believe.

**Comment by mlenser** [comment]
> Giant Insect and Giant Insect Potion still use monsters instead of the companion form

The insects aren't all on the componaion list, that's why. See #86
