### ISSUE TITLE
with 5 mana, "Studied Antimagic" is gained at 3rd level but useless until 5th level

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#166]
See: https://www.kryxrpg.com/character/classes/mage/wizard#studied-antimagic

Previously it made sense, because [Counterspell](https://www.kryxrpg.com/themes/spells/counterspell) and [Dispel Magic](https://www.kryxrpg.com/themes/spells/dispel-magic) both were castable at 3rd level. Now it no longer makes sense.

Suggested solutions:
* Lower Counterspell and Dispel Magic to be 1-mana spells.
* Move this feature to a higher level (5th+)

**Comment by Marcloure** [comment]
Both Counterspell and Dispel Magic are available at 5th level in RAW, I think they are fine like that. Moving the feature up is my favored solution.
