### ISSUE TITLE
Adapt soaring vines

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#167]
https://www.reddit.com/r/UnearthedArcana/comments/geil9g/soaring_vines_a_naturethemed_fly_alternative_for/?sort=top

**Comment by itamarcu** [comment]
I concur, this looks like an awesome spell.

**Comment by mlenser** [comment]
Vine Lasher adds two augments: one to catch you while falling and another to gain a pseudo-flying sheet
