### ISSUE TITLE
Add Grapnel to Plants Theme

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#168]
https://www.kryxrpg.com/themes/spells/grapnel
In response to #167, if vines can help grab onto you and surfaces to help you climb around a space, then they should also be able to allow you to grab a single surface for less mana.

**Comment by mlenser** [comment]
Grapnel would have a very different flavor in Plants (using vines, not a grapnel).

**Comment by itamarcu** [comment]
So make it a new but almost identical spell?

**Grapnel**
(1 mana, Plants)
*concentration, 1 minute/mana*

> As a bonus action, vines extend from your outstretched arm. Until the spell ends, you can cause the vines to lash at a target on each of your turns as an action. Make a ranged spell attack against a creature, object, or structure you can see within 35 meters.
> 
> **Creature**. On a hit, the target must succeed on a Reflex saving throw or be pulled up to 9 meters toward you. A Large or larger creature has advantage on this saving throw. If the creature is willing, it can allow itself to be pulled. If a creature is grappled by your vine you can use your action to pull it up to 9 meters toward you.
> 
> **Unattended Object**. On a hit, an unattended object is pulled up to 9 meters towards you; if this moves it into your square, you may grasp the item, although you must have a free hand to do so. 
>
> **Structure**. If you target an immovable object (such as an object bolted to the floor, a building wall, floor, or ceiling), you can move up to 18 meters towards the target. If you end your movement at a climbable location (such as a wall or ledge), you can attempt an Athletics check to grab hold (or pull yourself over the edge, in the case of a ledge). If you fail that check you begin falling. You can move yourself up to 18 meters as an action on your turn.
> 
> A miss causes the grapnel to retract instantly without attaching to anything.
> 
> If you pull yourself towards a structure while grappled, any creature that is grappling you must succeed on a Reflex saving throw or be forced to release the grapple or be moved with you (your choice). On a success the creature can prevent you from moving.
> 
> You can cause the vines to release at any time (no action required by you). They retract instantly.

**Comment by mlenser** [comment]
This is a grapnel
![image](https://user-images.githubusercontent.com/235857/81296294-f7b8a980-9071-11ea-9df9-6aafb80abe00.png)

Totally different to create one of those instead of `As a bonus action, vines extend from your outstretched arm.` as you wrote above. Quite similar in mechanics, but different in flavor

**Comment by DalenWBrauner** [comment]
_Oh,_ I didn't realize that word was a real noun. Back when this was in the ectoplasm theme, I just imagined goo, basically. That's partly why the vines fit so well.

That said, I think we could call Itmarcu's suggestion 'Vine Grapnel' and be done.

**Comment by itamarcu** [comment]
how about calling it "Ivy Whip"?

**Comment by DalenWBrauner** [comment]
It's more about grappling than whipping- whip exists as a weapon but it doesn't grant you anything like this. Grappling Ivy or Grappling Vine (ala Grappling Hook) might be better.

**Comment by DalenWBrauner** [comment]
This is me just reposting what @itamarcu wrote, cleaning up one or two things (and foolishly eschewing the metric system). I don't think it needs any other changes, and I don't feel strongly about the name.

> **Ivy Whip** or **Grappling Vine**
(1 mana, Plants)
concentration, 1 minute/mana

>As a bonus action, vines extend from your outstretched arm. Until the spell ends, you can cause the vines to lash out at a target on each of your turns as an action.
Make a ranged spell attack against a creature, object, or structure you can see within 120 feet.
>**Creature.** On a hit, the target must succeed on a Reflex saving throw or be pulled up to 30 feet toward you. A Large or larger creature has advantage on this saving throw. If the creature is willing, it can allow itself to be pulled. If a creature is grappled by your _ivy whip_ / _grappling vine_ you can use your action to pull it up to 30 feet toward you.
> **Unattended Object.** On a hit, an unattended object is pulled up to 30 feet towards you; if this moves it into your square, you may grasp the item, although you must have a free hand to do so.
> **Surface.** If you target an immovable object (such as an object bolted to the floor, a building wall, floor, or ceiling), you can move up to 60 feet towards the target. If you end your movement at a climbable location (such as a wall or ledge), you can attempt an Athletics check to grab hold (or pull yourself over the edge in the case of a ledge). If you fail that check you begin falling. You can move yourself up to 60 feet as an action on your turn.
> A miss causes the _ivy whip_ / _grappling vine_ to retract instantly without attaching to anything.
> If you pull yourself towards a surface while being grappled, any creature that is grappling you must succeed on a Reflex saving throw or be forced to release the grapple. On a success, the creature can prevent you from moving.
> You can cause the vines to release at any time (no action required by you). They retract instantly.
