### ISSUE TITLE
Add Divination to Arcane

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#169]
I'm not sure why Divination isn't in Arcane. Discovery and finding things is much into the Mage domain, many are the stories of wizards in search of a person or place, that can see distant lands or know things lost in time. Also, much of theme is related to research and knowledge, both things related to the Arcane.

Also, this card from Gwent is totally a Wizard thing (the image is too large, so I'm not showing a preview):

[xarthisius___gwent_card_by_akreon-dayg1pe](https://user-images.githubusercontent.com/29084710/81229953-0c8c3300-8fc7-11ea-8726-966463be6de9.jpg)

**Comment by eunomicZenith** [comment]
I agree Divination should be in Arcane.

**Comment by DalenWBrauner** [comment]
Agreed! I didn't even notice it was missing.

**Comment by mlenser** [comment]
Divination added to Arcane
