### ISSUE TITLE
Levitate spell balance

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#172]
Moving here for @itamarcu

> I have some complaints about the Levitate spell.
>
> * Why does Levitate force you to target yourself with it (i.e. has a range of self instead of touch, basically)? Levitating an archer is indeed useful, but to levitate one archer you'd have to spend 2 mana, because one of them would go to you, and you aren't necessarily another archer. Similarly, if you want to target an enemy with this, you gotta spend 2 mana and also affect yourself with the spell, an odd side-effect that I don't think makes sense. Why not just let you target any willing target you're touching when cast at 1 mana, and when augmented, allow both adding targets and better targeting (including monsters, and with increased range)?
> * When you cast the spell on yourself, you get to immediately rise vertically up to 9 meters. However, the spell doesn't mention levitating other targets this way; this means you'll have to wait until your next turn to actually get them off of the ground. That's pretty weird, and weak, too.
> * As an action, you can alter the altitude of a target within 18 meters by 9 meters. why can't you alter your own altitude, then, when this spell is cast at its baseline form? Furthermore, why not allow you to alter the altitude of all targets simultaneously with the same action?

**Comment by DalenWBrauner** [comment]
I do like this perspective: that Levitate is better suited to cast on other
things besides yourself. It _can_ be useful on yourself, but way more fun
on other things.

I also think Levitate is a weird name, if only because levitation implies
some sort of finer control over it. This spell literally requires you to
push off other things to move like in Zero G, so maybe "Undo Gravity" or
"Repel Gravity" would be a more accurate name.

**Comment by mlenser** [comment]
Levitate is the right word:
> Levitation is the process by which an object is held aloft, without mechanical support, in a stable position.

Pushing off things is just a way of moving while you're levitating.
________________

Addressing some of the comments:

> Why does Levitate force you to target yourself

The same reason Invisibility and several other spells do: It takes less effort to use a spell on yourself than others. All throughout my system there are spells that are a lower mana cost to use on yourself and a higher mana cost to use on others.

> if you want to target an enemy with this, you gotta spend 2 mana

Levitate is a very harsh condiditon for a melee creature. It practically disables them. Something of that strength isn't an option for 1 mana.

> better targeting (including monsters, and with increased range)?

It should definitely have a range to target another creature. I will fix that.

>  the spell doesn't mention levitating other targets

I think other willing targets should be able to control the levitation, the same that they can control flying.

> why can't you alter your own altitude

formatting problem. I'll fix

**Comment by DalenWBrauner** [comment]
Levitate might be physically accurate, but so would calling a Wall of Fire
a Plasma Baracade.
'Levitation' invokes fine control over your hovering ability. 'Undo
Gravity' invokes Zero-G, which is more in line with the spell effect. But
I'd love to hear more opinions from others, in case I'm being too pedantic.

**Comment by Marcloure** [comment]
I'm good with Levitate. Also, Undo Gravity is another theme completely.

**Comment by itamarcu** [comment]
I also agree that the spell is fine, though it's perhaps a bit weird that Fly is an augment of it, because someone looking for the fly spell might not find that intuitive.

**Comment by itamarcu** [comment]
> > the spell doesn't mention levitating other targets

> I think other willing targets should be able to control the levitation, the same that they can control flying.

That's not what I meant; I meant that if you cast it successfully on a monster, the monster actually doesn't get levitated at all. You have to use your action on the *next* turn to move the monster up in the air, the way it's phrased. As for letting willing targets control their movement...the spell is phrased like this:

> As an action, you rise vertically, up to 9 meters, and remains suspended there for the duration.

> You can move only by pushing or pulling against a fixed object or surface within reach (such as a wall or a ceiling), which allows you to move as if you were climbing. You can move up or down as part of your move.

From that, I gathered that you can only move by pulling/pushing against objects. If the intention is to allow you to vertically move with your speed but only horizontally move by pushing on things, or something like that, it should be explicit.

**Comment by mlenser** [comment]
Cleaned up:
![image](https://user-images.githubusercontent.com/235857/81319666-45dca580-9090-11ea-889f-6a2697c07552.png)

**Comment by DalenWBrauner** [comment]
That looks good. I would prefer willing creatures to use their own bonus
actions to adjust their height, though. (Unless there was wording that
allowed you to adjust all willing creatures together.)

Minor text fix:
"and remains suspended" -> "and remain suspended"

**Comment by itamarcu** [comment]
I think it looks good! Having willing targets unable to change their own height means that you can't levitate them high while you remain on the ground below them. If that's intended, I guess keep it your own bonus action.

**Comment by Paulorpribeiro** [comment]
3rd bullet seems the same as the 2nd one, but you can use a bonus action to target a creature you just that, correct? If that is the case, you could merge both together son the text is cleaner. Something like:
"You can expend 1 additional mana to target a creature within 18 meters or to cast the spell as a bonus action when you hit a creature with a weapon attack."

You can expend 1 additional mana

**Comment by mlenser** [comment]
2nd and 3rd bullet combined:
![image](https://user-images.githubusercontent.com/235857/81371171-6724ac80-90f7-11ea-915a-133392ae79bf.png)

I decided to always have the caster in control of the elevation. It's different from Fly where the user gets the power. With Levitate, the caster is the one causing and controlling the effect. The user wouldn't know how to control it like they could flying. I think that's the best thematic option.

**Comment by itamarcu** [comment]
Perhaps slightly alter it to

> You can change the altitude of **all targets** within 60 feet by up to 30 feet in either direction as a bonus action on your turn

So that the mage may raise multiple party members at the same speed simultaneously?
