### ISSUE TITLE
Power Sources should only be relevant for spells

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#176]
Remove the concept of Power Sources for anything other than spells.

Add a note to the bottom of each theme to indicate if it has concoctions, maneuvers, or spells.

**Comment by itamarcu** [comment]
What are the mechanical implications of this? Martials and Alchemists will just pick themes from anywhere, without being limited to picking within the martial power source?

**Comment by Marcloure** [comment]
Isn't this the same as adding all themes with maneuvers to the Martial power source?

**Comment by DalenWBrauner** [comment]
What are the rules for Halfcasters after this change? Will/should they simply be limited to the maneuvers in the Power Sources they already have? Or will they gain access to all themes, but only for their feats and maneuvers? Or just maneuvers?

**Comment by mlenser** [comment]
> Isn't this the same as adding all themes with maneuvers to the Martial power source?

That's already the case. The main point here is more about thematics. Power Sources don't make sense for Concoctions or Maneuvers.

> What are the rules for Halfcasters after this change?

Magus:
![image](https://user-images.githubusercontent.com/235857/81469791-505d8300-91e7-11ea-87ba-d265412c6a6b.png)

Half-half Paladin:
![image](https://user-images.githubusercontent.com/235857/81469802-60756280-91e7-11ea-8ca8-c626cd4024d3.png)

All Spells Paladin:
![image](https://user-images.githubusercontent.com/235857/81469805-679c7080-91e7-11ea-853f-b9bb6e415424.png)

All Maneuvers Paladin: 
![image](https://user-images.githubusercontent.com/235857/81469814-708d4200-91e7-11ea-843b-b808c2ea4a9c.png)

**Comment by mlenser** [comment]
Power Sources are only used for spells now

**Comment by Marcloure** [comment]
How do you learn the Vanguard theme being a Paladin now? The text says you can learn themes from your powersource, but it says nothing about other the martial themes

**Comment by DalenWBrauner** [comment]
Perhaps calling them "Class Themes" (or some other title), just so you can say

>Learn a new theme from your power source or list of class themes.

or for warriors

> earn a new theme from your list of class themes.

**Comment by mlenser** [comment]
> Perhaps calling them "Class Themes" 

They are purposefuly not connected to classes. The Sorcerer isn't becoming a Mage by picking Arcane - it's learning Arcane. The same is true for the Spellthief.
