### ISSUE TITLE
Magical Ward buff in 5 mana system

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#179]
> Whenever you expend mana to cast a spell, the ward regains a number of hit points equal to the mana you expended.

Should it recharge by twice the mana expended now? I mean, gaining 5 hp at 17th level isn't much.

**Comment by mlenser** [comment]
This spell gives ~20+5+60 = 85 hp at 20th level. That's 4x your level. Sure, it comes after you lose some hp so the real number is more like 55. Still almost 3x as good as Tough.

This is completely fine, if not overpowered.

**Comment by Marcloure** [comment]
So it was too much before? Well, ok then

**Comment by mlenser** [comment]
It's probably a bit too much now. But, meh.
