### ISSUE TITLE
"Expert" themes more useful to spellcasters after 5-mana change?

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#180]
Compare [Marksmanship Expert](https://www.kryxrpg.com/themes/feats/marksmanship-expert) and [Fire Expert](https://www.kryxrpg.com/themes/feats/fire-expert). Each of them lets you use one spell or maneuver enhanced to half your limit rounded up, once per short rest.

However, the value of one maneuver is not the same as the value of one spell/concoction.

If you pick Marksmanship Expert, you can use [Impaling Shot](https://www.kryxrpg.com/themes/maneuvers/impaling-shot) as a bonus action when attacking, to deal 1d8 damage to creatures in a line (save for none).

If you pick Fire Expert, for example, you can use [Burning Blade](https://www.kryxrpg.com/themes/spells/burning-hands) in the same way to deal 3d6 damage to creatures in a line (save for half).

Clearly, the mana option is stronger, here.

(I can find more examples, e.g. Scorching Strike and some maneuver that increases your damage. generally, though, 1 point of mana/catalyst is just more valuable than 1 point of maneuver).

Suggestions to fix this: 
* Let the player pick and enhance the maneuver up to their dice limit, instead of half their dice limit
* Let the player use this twice between short rests, instead of once between short rests; or pick two maneuvers instead of one, using each of them once?

**Comment by mlenser** [comment]
Expert feats removed as they are simply uninteresting filler feats that gave more resources (for a specific purpose) for the cost of a feat. I think we should aim for more interesting feats.
