### ISSUE TITLE
Magic Initaite Feat should require you to pick a power source and a source of your spellcasting

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#181]
All spellcasting in my system comes from a source. It's the reason a Bard doesn't exist for example. Initiate feats could either be a deal like a deal with a patron or deity, or they could be study like a mage does - minor magic. I think either would be thematic and align with the system

- Study like a Mage: Arcane & Int for casting
- Minor worship of a deity: Divine & Wis/Cha for casting
- Minor deal with a patron: Occult & Cha for casting
- Bonded with nature spirits: Primal & Wis for casting
- Self-meditation/empowerment: Psionics & Int for casting

**Comment by itamarcu** [comment]
Would you also allow nonstandard combinations of these? For example, a person who studied the occult, and didn't make any deal. Alternative example would be someone who has a nature spirit patron.

**Comment by DalenWBrauner** [comment]
@itamarcu I think the system's default answer would be _not without good reason._ From there, it's likely up to your DM to decide whether your noncommittal cultist or ancient druid pact would have enough of a connection to cast those spells.

@mlenser You didn't say so explicitly, but are you suggesting that characters have to be at least proficient (not just capable) in the relevant skill to access these Magic Initiate feats for that Power Source?
- Arcana Proficiency being a prerequisite for Arcane Spells
- Religion Proficiency being a prerequisite for Divine Spells
- Occult Proficiency being a prerequisite for Occult Spells
- Nature Proficiency being a prerequisite for Primal Spells
- Psionics Proficiency being a prerequisite for Psionic Spells

And then for Themes like Charm, which are in multiple sources, you would only need the proficiency for one of them, correct?

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/81476082-25d3f000-9210-11ea-8686-c233ecbc3358.png)

![image](https://user-images.githubusercontent.com/235857/81476066-10f75c80-9210-11ea-92a6-4040937ed654.png)
