### ISSUE TITLE
Whatever happened to the knockout maneuver?

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#183]
I really liked that maneuver, did it got removed? Why?

**Comment by mlenser** [comment]
It seems to have gotten removed at some point. I have no record of purposefulyl removing it, but I vaguely remember doing so.

**Comment by DalenWBrauner** [comment]
Is there a record of what it used to do? I'm curious whether something similar exists in its place, or if it can be altered and revived.

**Comment by Paulorpribeiro** [comment]
I remembered it would put the target unconscious and had a hit point limit similar to the sleep and disable spell. I think it was modeled after them

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/81577913-64051700-93aa-11ea-882b-11f7e956f404.png)

**Comment by Paulorpribeiro** [comment]
I liked the new maneuver, but the old one was more of a sutilstrike, more like an attack with a sap, this one is more of a brute knockout. I will propose in another issue a more subtle knockout
