### ISSUE TITLE
Concealing Amorpha should be similar to Blur

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#184]
https://www.kryxrpg.com/themes/spells/concealing-amorpha

https://www.kryxrpg.com/themes/spells/blur

Concealing Amorpha should have this sentence added, to be identical in functionality:

> An attacker is immune to this effect if it doesn’t rely on sight, as with blindsight, or can see through illusions, as with truesight.

**Comment by mlenser** [comment]
Concealing Amorpha is no an illusion. The sight part would apply, but not the illusions part.

**Comment by mlenser** [comment]
Added `An attacker is immune to this effect if it doesn’t rely on sight, as with blindsight.`
