### ISSUE TITLE
Add Climber feat to more themes

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#188]
https://www.kryxrpg.com/themes/feats/climber

Currently it's just in Alteration.

I think this should be added to Beast (as a lot of beasts can climb, and beast-like fighting can totally involve climbing), and Plants (as people like climbing on plants, and even plants like climbing on plants).

**Comment by mlenser** [comment]
- Climb added as a maneuver. Climber feat removed as there is now a maneuver and spell
- Climb maneuver and spell added to the Beast and Plants themes
