### ISSUE TITLE
Buff Meteor Swarm

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#189]
Meteor Swarm is the native 5 mana spell that deals the least damage. Also, since you can only cast one 5 mana spell per day, I think it's fine if they are ok being stronger.

I mean, casting this spell to deal 7d6 / 12d6 damage isn't great, even if you can cast it from veeeery far away.

**Comment by mlenser** [comment]
The issue with those two spells is the AoE size. It's the type ofspell you use against an army.

**Comment by mlenser** [comment]
The best that could be achieved is 9d6/16d6 for ~130-140 damage like other 5 mana spells

**Comment by Marcloure** [comment]
> Two orbs plummet to the ground. Each creature within 10 feet of the point where the meteor explodes
Or 
> Eight orbs plummet to the ground. Each creature within 5 feet

None of these options sound like a huge area

**Comment by mlenser** [comment]
Eight 5 foot aoes allows you to target real well. A 5 foot aoe has a target value of ~1.7. I've multiplied that by 4, assuming only 4 AoEs are really effective. Can't go higher than 9d6 with that amount of targets.

Two orbs target about half as many creatures.

What numbers are you looking for?

**Comment by Marcloure** [comment]
No, no, no, I'm talking about "It's the type of spell you use against an army". I think the spell is fine if buffed to the other 5 mana spells level.

**Comment by itamarcu** [comment]
It *was* the type of spell you'd use against the army, but the AoE size reduction hit this spell harshly.

I think increasing this to 9d6 would be nice, though I'd rather have this spell be more about covering a huge area and less about dealing damage, so if anything is buffed, I'd rather have it be the area of effect. When all other spells can be cast with the same amount of mana to be just as effective, this spell needs to have something unique to make people want to use it, and "huge and modular AoE" looks like the thing here.

**Comment by mlenser** [comment]
Meteor Swarm area and damage buffed after recalculation of aoe effectiveness

![image](https://user-images.githubusercontent.com/235857/81490830-0d52ec80-9287-11ea-8a7d-1a8377fd0024.png)
