### ISSUE TITLE
(Steady?) Aim maneuver

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#190]
After a couple of hours in discord, we came up with the following idea of maneuver:

 Aim – 1 Stamina
As an action, you can take aim with a ranged weapon and line up a perfect shot. You must choose a target and, until the start of your next turn, you cannot use your movement or take any reactions. Your next atrack against the target is a devastating shot. You have advantage on the attack row, ignore cover inferior to total cover and add the total stamina cost as stamima die to the damage row. If the smaller die also hit, you add and extra stamina die to the damage. 
Enhance: you can spend more stamina to add and additional d20 to the attack still (stacking advantage).

**Comment by Paulorpribeiro** [comment]
I'm not very good on writing maneuvers, but I tried to put all t h e discussion to paper. I like the stacking a lot of advantage part, and converted some of it to extra damage, so to not grant an auto crit. Static dmg also doesn't look like a great idea to me, but it was on the table. Fell free  to hack the make iu her and rewrite it

**Comment by DalenWBrauner** [comment]
Quoting Kryx's earlier comments on the maneuver:
> Advantage improves your aim. Adding double advantage or triple advantage are effectively autohit.
Attack can either incrementally increase (like precision) or use advantage. Scaling advantage is no good.

>There are two options to increase aim:
>- Incremental
>- Advantage
>
>All other options are effectively autohit. I get that you want autohit, but that's not on the table.

I don't think there's much room for negotiation here. Either the maneuver grants Advantage once, or it adds to the attack bonus in line with the bonuses granted by Precision.

When I asked Kryx about this directly:
> Your budget is advantage. That's the highest possible (besides +5 at 5 stam which is effectively the same). That's a 87% chance to hit. There is no higher possibility than that.

This maneuver is not going to make it into the game without respecting that design choice.

**Comment by Paulorpribeiro** [comment]
I'm not trying to disrespect any design choices here. This is the idea that was suggested, I just fleshed out. Fell free to hack it and take it out.
Although the intent is that this maneuver depicts a move that a veteran archer (or anything ranges, really) locks it's target and fires with a really high chance of hitting. It It just a matter of we making rules to make that happen.
I think simple advantage makes the .a river weak (considering it costs one action and makes you stay immobile and forgo your reaction).

**Comment by eunomicZenith** [comment]
I understand the desire to avoid labor and granularity, but IMO we can't do without them in this context.

**Comment by itamarcu** [comment]
Just for history's sake, I'm gonna post here the first revision of this idea, straight from Discord ("Revision 1"):
> **Perfect Aim** (5 stamina, marksmanship)
> As an action, you can take aim with a ranged weapon and line up a perfect shot. Until the end of your next turn, you cannot use your movement or take any other actions and reactions. If you are still capable of taking your action at the end of your next turn, you release a devastating shot that scores an automatic critical hit against the target. The target takes additional piercing damage equal to half your expended stamina dice.

Now, I'll try to type a new suggestion, that keeps to the restrictions mentioned above...

(I'm gonna call this Revision 7)

> **Aim** (1 stamina, marksmanship)
> As an action or as an attack, you can take aim with a ranged weapon and line up a perfect shot against a target you can see. While aiming, if you move, use your reaction, make an attack against a different target, or become incapacitated, this maneuver fails. Otherwise, your next ranged weapon attack against the target is devastatingly accurate. You have advantage on the attack, ignore all cover other than total cover, can attack up to double your weapon's range or long range, and add the stamina die to the damage.
> *Enhance*
> You can spend more stamina dice to increase the damage of the attack. If you had disadvantage, additional dice also add advantage to cancel it, until you have advantage on your attack. Otherwise, additional dice increase your attack roll by +1.

Notes:

* The "you must choose a target" limitation is harsh, but I'll keep it for now, as it's both reasonable and gives us more "fuel" to buff the rest of the ability (since this maneuver can be countered by the creature just running behind cover).
* Changed it to "as an action or as an attack", so if you have Extra Attack you can either aim-and-shoot (making one attack with advantage and a few small benefits; should be about as good as making two separate attacks) or shoot and then start aiming. It still allows it as an action because aiming while you're e.g. invisible shouldn't take you out of the invisibility.
* Removed the "next turn" restriction, so you can keep aiming for several turns in case you want to delay your attack for some reason.
* Additional enhancement dice will now stack advantage only for the purposes of canceling disadvantage, which shouldn't break anything.
* Further enhancement will add +1 to the attack roll, similar to how the Precision maneuver works. Note that these dice also increase the damage, but I thought this is fair, since the Precision maneuver grants the attack roll bonus to all of your attacks during a turn, and not just one.

Please give feedback or offer your own revisions on this!

**Comment by Paulorpribeiro** [comment]
First, I would substitute the "...or as an attack" part in the beggining of the maneuver  for " or substituting an attack, if you take the attack action and has the extra attack feature

**Comment by Paulorpribeiro** [comment]
Now this is a quote from the rules, playing section: 

"If multiple situations affect a roll and each one grants advantage or imposes disadvantage on it, each advantage/disadvantage pair cancels out. After resolving, if you have multiple advantages or multiple disadvantages you roll one additional dice for each advantage or disadvantage. For example, two advantage and no disadvantage on an attack would roll 3d20 and keep the highest 1".

So the rules allow for multiple dice to be rolled if multiple advantages apply. It also does not specify a limit. So having one stack of advantage in the attack per stamina is not bending the rules in any way, it is wihing the rules. If 6d20 is an absurd and practically auto hit, then we should put a limit in the stacking advantage, not only on the maneuver. The maneuver could be written so the enhance gives one extra stamina die to damage and one extra stack of advantage each 2 stamina spend, making a maximum of 3 advantages for 5 stamina, or 4d20 on the attack (one more than the example given in the text I mentioned) if no other source of disadvantage apply.

**Comment by itamarcu** [comment]
This was one of the earlier iterations, yeah, where additional dice just added additional advantage. Personally I believe that the new advantage rules are fun, but if you put a maximum amount of advantages on a single roll, I'd say this maneuver should just allow you to gain advantages up to that many (and probably just drop the +1 part, for simplicity).

**Comment by Paulorpribeiro** [comment]
This discussion is getting kinda of old news, did we just give up on the maneuver?

I agree with itamarcu's last statement, the maneuver should stack advantage until the maximum of stacked advantages and deal stamina dice as extra damage, to keep it simple.

The real question here is: do we need a cap on how much advantage a single attack can get? The example given is double advantage for 3d20 attack roll, should we allow more than that?

**Comment by mlenser** [comment]
> This discussion is getting kinda of old news, did we just give up on the maneuver?

I've given feedback on crucial aspects that were quoted above



> Quoting Kryx's earlier comments on the maneuver:
> 
> > Advantage improves your aim. Adding double advantage or triple advantage are effectively autohit.
> > Attack can either incrementally increase (like precision) or use advantage. Scaling advantage is no good.
> 
> > There are two options to increase aim:
> > 
> > * Incremental
> > * Advantage
> > 
> > All other options are effectively autohit. I get that you want autohit, but that's not on the table.
> 
> I don't think there's much room for negotiation here. Either the maneuver grants Advantage once, or it adds to the attack bonus in line with the bonuses granted by Precision.
> 
> When I asked Kryx about this directly:
> 
> > Your budget is advantage. That's the highest possible (besides +5 at 5 stam which is effectively the same). That's a 87% chance to hit. There is no higher possibility than that.
> 
> This maneuver is not going to make it into the game without respecting that design choice.

**Comment by Paulorpribeiro** [comment]
Well, I am Golagar, for some reason my nickname in the new account for github was default to the first part of my email. 
And my original idea was to give one instance of advantage per stamina spent. Up to the maximum allowed by the rules. There is no explicit maximum number of advantages one can accumulate, so we are kinda stuck in this detail.

If the max increment possible for a maneuver like this is one advantage, then I think giving up one action or one attack is not worth it and we're back to the design board. If we change it to a bonus action than there is no design space, the maneuver ready exists and it's called precision.

**Comment by mlenser** [comment]
Features were never intended to give multiple advantages. Multiple advantages are intended to allow a user to have a circumstance advanatage stack with another circumstance advantage or to stack with a feature that gives advantage.

Attacking with advantage already gives ~87% chance to hit. The game shouldn't give higher options for several reasons:
- Bounded accuracy
- It would be a very niche option that is only useful versus a creature with really high hit. In other cases it is a trap option
- Such an option can significantly increase the value of another feature that is typically dependent on hitting

**Comment by Paulorpribeiro** [comment]
Well in that case I'd have to change the whole maneuver. If it is to give advantage and stamina to the damage it has to be a bonus action, not a full attack or action, and in that case it steps into the precision maneuver design space. I'll try to write it again when I have time

**Comment by itamarcu** [comment]
Wait, why not continue with the thing we had last written? 

Revision 8.
> **Aim** (1 stamina, marksmanship)
> As an action, or substituting an attack if you take the attack action and has the extra attack feature, you can take aim with a ranged weapon and line up a perfect shot against a target you can see. While aiming, if you move, use your reaction, make an attack against a different target, or become incapacitated, this maneuver fails. Otherwise, your next ranged weapon attack against the target is devastatingly accurate. You have advantage on the attack, ignore all cover other than total cover, can attack up to double your weapon's range or long range, and add the stamina die to the damage.
> *Enhance*
> You can spend more stamina dice to increase the damage of the attack. If you had disadvantage, additional dice also add advantage to cancel it, until you have advantage on your attack. Otherwise, additional dice increase your attack roll by +1.

This keeps to bounded accuracy (the maximum you could get here is advantage and an additional +4). 

I am also okay with just dropping the "additional dice increase your attack roll by +1" part (though I'd rather keep it).

Sidenote - this combos pretty nicely with the potential change to Spell Strikes, as you could cast a spell strike buff on your ranged weapon before making the attack, and you'd be less worried about wasting the special attack (and have a higher chance to crit with it).

**Comment by mlenser** [comment]
> Attack can either incrementally increase (like precision) ***or*** use advantage. Scaling advantage is no good.

**Comment by Lamorak11** [comment]
The only version of this I can see working:

**Aim** (1 stamina, marksmanship)
As an action, or substituting an attack if you take the attack action and have the extra attack feature, you can take aim with a ranged weapon and line up a perfect shot against a target you can see. While aiming, if you move, use your reaction, make an attack against a different target, or become incapacitated, this maneuver fails. Otherwise, your next ranged weapon attack against the target is devastatingly accurate. You have advantage on the attack, ignore all cover other than total cover, can attack up to double your weapon's range or long range, and add the stamina die to the damage.
Enhance
You can spend more stamina dice to increase the damage of the attack. If you had disadvantage, additional dice also add advantage to cancel it, until you have advantage on your attack.

**Comment by itamarcu** [comment]
So basically, the last revision I made but without the extra +1? Yeah, like I said, I'm okay with that.

**Comment by mlenser** [comment]
> While aiming, if you move, use your reaction, make an attack against a different target, or become incapacitated, this maneuver fails.

This wording can be skipped. It doesn't align with skipped an attack as part of an Attack action. It's a an attempt to create a full round action which doesn't exist in 5e.

> You have advantage on the attack, ignore all cover other than total cover, can attack up to double your weapon's range or long range, and add the stamina die to the damage.

Cover shouldn't be ignored - that would be something magical to allow you to shoot around the cover for example.

> If you had disadvantage, additional dice also add advantage to cancel it, until you have advantage on your attack.

There isn't room for this in the cost budget nor should this cancel disadvantage, imo. That's not something within a maneuver's mundane domain.

___________________

The core of this is Advantage + double range + stamina dice. With those factors its slightly strong at 1 stamina die, but a few other maneuvers are like this:
![image](https://user-images.githubusercontent.com/235857/81832441-cd1d9380-953e-11ea-9b9b-9b219ef10117.png)

That'd be a workable option.

**Comment by mlenser** [comment]
Aim added as a 1 stamina die maneuver

**Comment by itamarcu** [comment]
> Cover shouldn't be ignored - that would be something magical to allow you to shoot around the cover for example.

This doesn't let you shoot around the corner - it just lets you aim well enough that you ignore "lower" forms of cover (half cover and three-quarters), by biding your time until the target looks around the corner or by shooting at the exposed part of the creature. It could be reduced to "ignore half-cover", if that's too much.

> > While aiming, if you move, use your reaction, make an attack against a different target, or become incapacitated, this maneuver fails.

> This wording can be skipped. It doesn't align with skipped an attack as part of an Attack action. It's an attempt to create a full round action which doesn't exist in 5e.

The goal here is to prevent you from aiming at the goblin with your dagger (about to throw it), using your reaction to stab the kobold that's running away from you, and then throwing the dagger at the goblin as if nothing happened. Similarly, the movement restriction is to allow the creature to hide behind (total) cover, so that you can't just walk on your next turn to see it again and then shoot at it with an "aimed" attack.

----

All in all, though, it seems like we reached a good enough compromise, and my complaints above are minor. Thanks for adding this!

**Comment by Paulorpribeiro** [comment]
Maybe I'm late ast suggesting it, but maybe just restricting the character to half speed until the attack is made? He can still use all his speed, he is not restricted  physically, but he would loose the maneuver. It's flavourfull (imo) and maybe will help bring the value down just that extra notch

**Comment by mlenser** [comment]
After aiming, your speed is reduced by half until you make the attack and you cannot use another maneuver when you make the attack.
