### ISSUE TITLE
Skills page doesn't mention Untrained/Capable/Expertise

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#195]
I... actually can't find the Untrained/Capable/Proficient/Expertise rules anywhere. I'm _pretty sure_ it's somewhere on the site, but the closest I could find:

>Choose a skill you know or from from your skill list to improve your proficiency with.
>- If you are untrained, you become capable
>- If you are already capable, you become proficient
>- If you are already proficient, you gain expertise with that skill.

Now _I_ know that Untrained = +no prof bonus, Capable = +(0.5 * prof bonus), Proficient = +full prof bonus, Expertise = +(1.5 * prof bonus), but...

**Comment by Marcloure** [comment]
It is here:
https://www.kryxrpg.com/rules

**Comment by mlenser** [comment]
Let me know if you think this can be structured better. I tried to match the PHB grouping.

**Comment by DalenWBrauner** [comment]
I'd like to reopen this issue. I can provide a "fixed" version of the text a bit later, but for now, there are a few paragraphs that are outdated and seem almost contradictory to how the system is currently supposed to function.

The second and third paragraphs at the top of the [Skills](https://www.kryxrpg.com/rules/skills) page read:
> Sometimes, the GM might ask for an ability check using a specific skill—for example, “Make a Perception check.” At other times, a player might ask the GM if proficiency in a particular skill applies to a check. In either case, proficiency in a skill means an individual can add his or her proficiency bonus to ability checks that involve that skill. Without proficiency in the skill, the individual makes a normal ability check.
> For example, if a character attempts to climb up a dangerous cliff, the GM might ask for an Athletics check. If the character is proficient in Athletics, the character’s proficiency bonus is added to the Strength check. If the character lacks that proficiency, they just make a Strength check.

Sure, you _could_ argue that this is accurate, but it's a bit confusing that it never mentions the possibilities of being capable or having expertise. I can provide improved text a bit later.

I'm having the same problem with the text on Saving Throws, which might be arguably worse. Perhaps, again, it's just written somewhere else on the site that I haven't found, but the only truly explanatory/accurate information I _can_ find is on the page for each Class. There it indicates that Saving Throws can also have capability/proficiency/expertise, but the bottom of the [Rules/Playing page](https://www.kryxrpg.com/rules) reads:

>Each class gives proficiency in one saving throw. The mage, for example, is proficient in Will saves. As with skill proficiencies, proficiency in a saving throw lets a character add his or her proficiency bonus to saving throws made using that save. Some monsters have saving throw proficiencies as well.

(Ironically, the text about Capability/Expertise is on this same page.)
I feel like the biggest reason I'm not confounded by this is because I'm _not_ a new player and have been here long enough to know how it's supposed to work.

**Comment by DalenWBrauner** [comment]
My gut says: 
- Clarify the Skills section to mention that a character can (be? have?) Untrained, Capable, Proficient, Expertise in each Skill
- Clarify in the Saving Throws section that these 4 also apply, and apply exactly the same way
