### ISSUE TITLE
Sugestion for control flames

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#196]
I think this really fits the cantrip, because even though it's an utility cantrip, with some a preparation, it should damage.

My suggestion is to add this bullet to the possibilities of the spell

*You can target a creature with the burning condition and instantly increase the fire to cause [appropriate cantrip level damage] to the target. 
The damage, I'd say, has to be the same or a little less than Produce Flame damage, since Control Flames also has other uses.

It makes sense if you can whiff the flames and reduce the bur njing by 1, you could flare it to cause a little bit of extra damage. Change damage for balance, but at least a 1d4 damage just for consistency would be nice

**Comment by itamarcu** [comment]
I'm in favor of:
* You can target a creature with the Burning condition to increase or decrease the level of Burning by 1. This increases to 2 by 5th level, 3 by 9th level, 4 by 13th level, and 5 by 17th level.

**Comment by mlenser** [comment]
> You can target a creature with the Burning condition to increase or decrease the level of Burning by 1. This increases to 2 by 5th level, 3 by 9th level, 4 by 13th level, and 5 by 17th level.

I've already written that this won't happen in discord and others also wrote why it shouldn't happen.

**Comment by Paulorpribeiro** [comment]
I also think itamarcu's idea makes it too strong, but mine I think it is on par with cantrip lower level.

Like I said, I prefer the damage to be low like 1d4 but to have that option, just for consistency. If the burning condition is the prerequisite for this (utility) cantrip to be used for damage, it wont be the go-to choice for damage cantrip.
Produce flame should be always stronger and the control flame.should not increase the burning, just cause damage in the casters turn.

**Comment by mlenser** [comment]
Ya, I think your suggestion is pretty good. I'll try it out when I have a bit more energy

**Comment by mlenser** [comment]
So I'm not sure there is room for another fire cantrip. We have:
- Cauterize Wound. Fort save for 1d6 (half) and no healing
- Product Flame: Ranged attack for 1d8
- Product Flame: Melee attack for 1d8

- Control Flames: Only usable on a burning creature. Fort would just be a lesser version of Cauterize Wound. Do you intend to have the damage automatically apply? 1d4 is too little for that and 1d6 is too much..

hmm

**Comment by DalenWBrauner** [comment]
I'd vote just leave it as an auto 1d4. Considering the cantrip has other utility uses, this would really be more for the sake of flavor anyway.

**Comment by mlenser** [comment]
Control Flames adds the ability to burn a burning creature
