### ISSUE TITLE
Crit Fishing: Hungry Lightning Strike

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#197]
Props to @wherfz for catching this one.

In #94 Kryx mentioned:
> The [spell portion of the] strike can't be an auto-hit in order to avoid crit fishing, so Fort save.

> Auto damage is for the force theme, not here.

Hungry Lightning Strike reads:
> As a bonus action when you hit a creature with a weapon attack, tendrils of lightning lash out from your weapon. Add 2d8 lightning damage to the attack’s damage roll, and the target can’t take reactions until the end of its next turn.

**Comment by Marcloure** [comment]
Damn, I was just writing this exact same post xD

**Comment by wherfz** [comment]
I personally love these kind of 'smite' spells. They are very satisfying. I've discussed their balance with players and think they should be limited but still used. (E.g., melee only, class feature, cast before an attack.) These abilities were less of an issue before augments became more prevalent. It always really fit as something a melee Magus or Paladin would perform. A big risky but satisfying spell attack.

I think it warrants some discussion. I'm interested in what others think about spells like this!

**Comment by itamarcu** [comment]
I'm pretty certain that this is a mistake - all the other similar spells are worded with a save inbetween, to avoid this being more useful on crits.

Hungry Lightning itself is:

> The target must make a Reflex saving throw. On a failed save, a creature takes 4d8 lightning damage and it can’t take reactions until the end of its next turn. On a successful save, it takes half as much damage.

so I bet Hungry Lightning Strike is meant to be:

> As a bonus action when you hit a creature with a weapon attack, tendrils of lightning lash out from your weapon. The target must make a Reflex saving throw. On a failed save, the creature takes 3d8 lightning damage and can't take reactions until the end of its next turn. On a successful save, it takes half as much damage.

(possibly not 3d8 damage but whatever fits the spreadsheet)

see [Lightning Bolt / Lightning Blade](https://www.kryxrpg.com/themes/spells/lightning-bolt) for example.

**Comment by Marcloure** [comment]
I disagree with limiting to melee only. Ranged Paladins and Magus are awesome.

Now, the problem if we cast the spell before the attack is that the damage would be really high. That means an eventual crit would kill almost anything.

**Comment by mlenser** [comment]
It is definitely inteded to work for ranged or melee

I've added a save in the middle.

https://github.com/mlenser/kryx-rpg-issues/issues/199 opened to discuss spell strikes.
