### ISSUE TITLE
Create Shaman

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#2]
Original: https://bitbucket.org/mlenser/tabletop-homebrew/issues/192/create-shaman-as-an-option
_____

Mark Lenser REPO OWNER created an issue 2018-11-14
Consider adding a Shaman class or perhaps as an archetype to Barbarian (moving rage to Bloodrager and Warrior)

Comments (11)
Mark Lenser REPORTER
marked as proposal
2018-11-19
Sebastian Gruber
Going to bring back this old post as a query. Now that Bloodrager no longer exists, is this once again on the table, perhaps with Shaman, Bloodrager, and perhaps something like a Woodsman/Huntsman (ranger-esque, but without Wild Shape).

2019-01-29
Mark Lenser REPORTER
Shaman has never gone off the table. It's definitely something that I want to do. Though it's not a straightforward concept and my hands have been fill with other ideas. I've tried to make the shaman a few times, but they fell flat due to lack of inspiration.

2019-01-29
Kimmyth Pesz-Basham
I think understanding your intent when you say Shaman is the key to inspiration. What is a Shaman to you? Due to so many types of shamans from multiple sources it's hard to pin down what your looking for. There is the W.O.W Shaman every elements themed. Then there is something like Shaman King were it uses spirits as it focus. What do you mean by Shaman?

2019-02-03
Mark Lenser REPORTER
The identity of a Shaman is part of the task here. But this is an embryo of an idea that will not likely be done for months.

2019-02-03
Kimmyth Pesz-Basham
Well that being said I think W.o.Ws version of a Shaman has a lot we can work with and translate into a mechanical form for this system. The Enhancement was my favorite. They worked there way up to mail armour,could two weapon fight, used the elements for quick magic and bluffs. Flame/ earth shock and lightning/water shield. But the big thing they had going for them was the totems. They could be attacked and destroyed but there were all kinds so healed or gave you mana or did dmg or made others attack it as a distraction. And my favorite they could summon 2 wolf spirits that would fight with you and any dmg they did also healed you. It was not much but it could make the difference between 1 more hit to kill you. That being said I think there are a few classes that fill this type of role just not the flavor per say. Anyway totems and sprit wolf's are cool.

2019-02-03
Scott Simmons
I'd group the Shaman in with Divine spellcasters,somewhere between a druid and a cleric with a Wilder more cultural approach. The Shaman is usually still a devotee of something; be it the tribe, nature, spirits or fate.

Perhaps the Acolyte class needs renaming to something less formal in organizational connotation and more oriented to actions and behavior. This should allow adding the Shaman alongside the ranks of clerics et Al.

"Disciple" has a nice ring to it.

2019-02-08
Mark Lenser REPORTER
The shaman is definitely not divine. It is a class that confers with primal spirits.

It is very closely tied to Primal.

2019-02-09
Parker Abbott
I think the best way you could handle a Shaman type character would be to make a Spiritualist class that focuses on consorting with the spirits of nature and the dead, with options like Shaman and Witch as Archetypes or subclasses. I think giving them Occult and Primal would do nicely as well as giving the shaman a more “Speaker of the Dead” vibe and Witch possibly getting curses as a class resource.

2019-06-08
Mark Lenser REPORTER
The Witch is already completely covered in the Incanter class. You can play a witch with a pact/bloodline like Sabrina, a Witch that has sold its soul to an entity, or just a normal village witch.

There are many options to fulfill the concept:

Grimoire
Familiar
Supernatural sense
Ritual Preparation
Hex is covered as part of Blood Hunter. Normal curses are covered as part of spells from the Fate theme (Bestow Curse)

Is there anything missing from the Incanter that is needed for a Witch let me know.

2019-06-08
Mark Lenser REPORTER
https://old.reddit.com/r/UnearthedArcana/comments/f0v1gz/the_shaman_become_a_conduit_for_the_raw_power_of/
https://old.reddit.com/r/UnearthedArcana/comments/fboud1/witch_class_v20_bind_spirits_with_the_newly
https://old.reddit.com/r/UnearthedArcana/comments/fasuqg/the_shaman_v15_a_new_5e_homebrew_class_with_4
‌

2020-02-12

**Comment by mlenser** [comment]
https://old.reddit.com/r/UnearthedArcana/comments/g1y7sc/the_shaman_class_become_a_conduit_for_the_raw/?sort=top

**Comment by mlenser** [comment]
https://www.reddit.com/r/UnearthedArcana/comments/hc0alu/the_shaman_v_21_a_wisdombased_halfcaster_full_pdf/

**Comment by mlenser** [comment]
https://www.reddit.com/r/UnearthedArcana/comments/hkj4q1/the_shaman_updated_to_ver_22_a_wisdombased/

**Comment by mlenser** [comment]
https://old.reddit.com/r/UnearthedArcana/comments/i174h6/the_shaman_class_updated_to_ver_24_full_pdf/

**Comment by mlenser** [comment]
Witch can be created as an archetype to Suffused which has half alchemy half spells or full spells, just need some features.
Shaman can also be a Suffused archetype with half maneuvers half alchemy or half maneuvers half spells or other mixes.
I think this is a good option.

**Comment by Marcloure** [comment]
I'm not sure what definition of Shaman you are following, but I never saw them as "infused by powers". I have always thought of them having deep connection with the spirits, and in that sense, wouldn't they be Naturalists?

**Comment by mlenser** [comment]
Shaman added as an archetype to Naturalist
