### ISSUE TITLE
Inconsistent Spell Strikes

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#201]
Some spell strikes still add damage directly to the attack or require a second attack. Some examples:

• Light Brand
• Guiding Strike
• Acidic Strike (requires a secondary attack)
• Chaos Strike (auto hit, damage not added to the attack)

These are the ones I could caught on the spreadsheet, might be a few more.

**Comment by mlenser** [comment]
I'll look at this after #199

**Comment by mlenser** [comment]
Closing this as it'll be fixed as part of #199
