### ISSUE TITLE
Sound Spell- Piercing Screech

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#202]
A spell that originates from the caster in a sphere or cone. Wisdom save or be frightened (or stunned?)

**Comment by eunomicZenith** [comment]
I think there should be two different spells, one that stuns and one that frightens.

**Comment by Lamorak11** [comment]
Or perhaps an augment? Frighten can be replaced by stun?

**Comment by mlenser** [comment]
This sounds like a prime example of a spell that uses sound, but is not based on sound. The fear spell already covers the frightened condition. Mind blast already covers the stunned. We could make thematic duplicates if there is a strong flavor, but these seem like options that belong in other themes being applied to Sound.

**Comment by eunomicZenith** [comment]
If it helps any, I think these - especially the stunning one - should also cause thunder damage.

I'm personally confident we'd want stun and frighten to be on two different spells, not augments of the same spell.

**Comment by Lamorak11** [comment]
**Piercing Screech** (1 mana, Sound) 
As an action you let loose a magically-enhanced scream that rattles the minds of creatures around you. Each creature other than you in a sphere centred on you that is twice as big as normal must succeed on a Will saving throw or become frightened of you until the end of your next turn. A construct or an undead is immune to this effect.

While frightened by this spell, a creature is rooted to the spot with fear and cannot move or take the dash action.

If a creature’s saving throw is successful or the effect ends for it, the creature is immune to your Piercing Screech for the next 24 hours.

Augment
You can expend 1 additional mana to Stun creatures affected by this spell instead of Frightening them.

**Comment by Lamorak11** [comment]
Different to Fear as it doesn't have a duration, and roots them instead of sending them running.

**Comment by Marcloure** [comment]
I can see a sound spell that is so loud and high that makes people put their hands over their ears. But I guess that effect would be stunned/staggered, not frightened.

**Comment by mlenser** [comment]
> magically-enhanced scream that rattles the minds of creatures around you

This is not a Sound spell. It uses sound, but its core component is rattling the mind of creatures around you.

**Comment by Lamorak11** [comment]
I'm not sure I agree. An extremely loud, high pitched noise like that in real life is more than capable of putting someone out of action. Here we have a magical noise that is effecting a person physically. "Mind" is probably the wrong word. Brain is more apt. 

I agree frightened is probably wrong. And as its more physical in nature it should be a Fortitude save. 

Perhaps a rewording:

**Piercing Screech** (1 mana(?), sound) 
As an action you let loose a magically-enhanced scream that is loud and shrill enough to stop foes in their tracks. Each creature other than you in a sphere centred on you that is twice as big as normal must succeed on a Fortitude saving throw or become staggered until the end of your next turn. A construct or an undead is immune to this effect.

If a creature’s saving throw is successful or the effect ends for it, the creature is immune to your Piercing Screech for the next 24 hours.

Augment
You can expend 1 additional mana to Stun creatures affected by this spell instead of Staggering them.

Notes:
Not sure if it should last until the start or end of your next turn.

**Comment by DalenWBrauner** [comment]
We're getting closer, I like this spell a lot!

Opinions:
- 1 mana for sure
- "you let loose a magically-**amplified** scream" <- to erase any ambiguity that you are still producing the sound, and that magic is only serving to strengthen that
- Because the duration is going to be so short, it should probably last until the end of your next turn, so you can make use of their lack of reactions.
- This isn't a charm effect. Rather than constructs or undead being immune, it should be Deafened creatures.
- I know the 24 hours comes from the Fear spell, but given the flavor of this spell, I would suspect it should be shorter (somewhere between 1 and 8 hours, maybe?)

**Comment by itamarcu** [comment]
I think the immunity for 24 hours part can just be dropped - it doesn't feel important to me, and very few spells have such a restriction.

**Comment by Lamorak11** [comment]
Dalen I agree with all those points, thanks!

**Comment by mlenser** [comment]
Monster examples:
> The vrock emits a horrific screech. Each creature within 20 feet of it that can hear it and that isn’t a demon must succeed on a DC 14 Fortitude saving throw or be stunned until the end of the vrock’s next turn.

> The deep scion emits a terrible scream audible within 300 feet. Creatures within 30 feet of the deep scion must succeed on a DC 13 Will saving throw or be stunned until the end of the deep scion’s next turn. In water, the psychic screech also telepathically transmits the deep scion’s memories of the last 24 hours to its master, regardless of distance, so long as it and its master are in the same body of water.

**Comment by mlenser** [comment]
I'm wary of the stun option due to how powerful it is. It isn't damage, but stunning a lot of people is very very powerful.

I think we should probably skip that augment.

**Comment by Lamorak11** [comment]
Yeah, that's fair, I wasn't married to the stun idea. My next question is: should it deal any thunder damage?

Updated:

**Piercing Screech** (1 mana, sound)
As an action you let loose a magically amplified scream that is loud and shrill enough to stop foes in their tracks. Each creature other than you in a sphere centred on you that is twice as big as normal must succeed on a Fortitude saving throw or become staggered until the end of your next turn. A Deafened creature is immune to this effect.

**Comment by mlenser** [comment]
If it's a big aoe it shouldn't deal damage. I think a big AoE is more fitting for the flavor.

**Comment by mlenser** [comment]
Piercing Screech added as a spell
