### ISSUE TITLE
Sound Spell - Luring Song

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#203]
More or less as the Harpy ability (https://www.kryxrpg.com/monsters/harpy).

**Comment by DalenWBrauner** [comment]
This matches the power of other 2 Mana Charm spells I think, and it should belong in both themes. The range of course should just be a sphere (and it probably shouldn't affect allies).

**Comment by Lamorak11** [comment]
I agree.

**Comment by mlenser** [comment]
I think this is actually perfectly fit for a Performance option.

**Comment by mlenser** [comment]
Luring Song added as a Performance
