### ISSUE TITLE
Sound Feat - Echolocation

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#204]
High level feat. Grants Blindsense out to 30(?) feet?

**Comment by DalenWBrauner** [comment]
I think a Harmonic Spell that grants this temporarily might make more sense. I can see this being an effect created by magic, moreso than I can see it being something innate without modifying your physical form.

**Comment by Lamorak11** [comment]
That's a good point, a spell might work better for this.

**Comment by mlenser** [comment]
Echolocation added to the Beast and Sound theme as a spell
