### ISSUE TITLE
Give Minstrel an Instrument AC bonus

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#205]
Possibly just for the bard.

Something like:
"You are adept at using your instrument to avoid harm; using music, mocking sound-effects and harsh chords to distract and misdirect your foes when they target you." You gain +2  AC while holding an instrument (in two hands?)"

**Comment by Lamorak11** [comment]
If possible with an instrument held in one hand, should not be stack-able with a shield.

**Comment by mlenser** [comment]
I think a pseudo-shield is the wrong approach.

It should be something that is thematic for minstrels and ideally is unique. Aoe buffs that improve speed, attack, dodging. Maybe all. Maybe that's a core feature for the Minstrel.

**Comment by Lamorak11** [comment]
Maybe those effects - speed, attack, dodging - can all be different "stances" and the bard can be in one at a time, change stance as a bonus action, and they provide an AOE buff.

**Comment by Marcloure** [comment]
I also don't think giving a shield-like feature is the solution. Better to try to capitalize on what the instrument uniquely offers to us than to make it fit something it is not.

**Comment by Lamorak11** [comment]
Agreed, I'll close this issue as I think the other things we have discussed fit much better.

**Comment by mlenser** [comment]
@Lamorak11 please follow up with the new idea when you've refined it a bit!
