### ISSUE TITLE
Sound Feat - Earplugged(?)

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#206]
I don't have a good name for it.

> **4th Level**
> Due to longterm exposure of loud sounds, you have resistance to Thunder damage and <some other small trait)>.

Fire Theme grants resistance to Fire Damage and ambient heat. Storm Theme grants resistance to Thunder and Lightning damage.

This feats needs a second thing, but I'm not yet sure what.

**Comment by mlenser** [comment]
I would also give this disadvantage on Perception checks to hear.

**Comment by DalenWBrauner** [comment]
Good label, thank you. I'll likely change the thematics so that the disadvantage is not required- just want something in line with the other Themes.

**Comment by itamarcu** [comment]
Advantage on saving throws against spells or effects that deafen you? maybe something similar about Stagger, Confuse or Stun?

**Comment by mlenser** [comment]
Closing until this is refined more
