### ISSUE TITLE
Spell Suggestion - Orbiting Object

### ISSUE THREAD

**Issue by eunomicZenith** [mlenser/kryx-rpg-issues#207]
**Orbiting Object** (Telekinesis cantrip) (duration: 1 hour)
> You create a telekinetic force that causes an object to hover around you, following you wherever you go, always staying in your space. The object must weigh 2.25kg or less, and be no larger than 1.5m in any dimension.
This spell gives you a degree of telekinetic control over the object, such as what is required to flip the pages of a book or pluck the strings of a harp. You can also slowly move the object around you.
The force moves the object with too little force to be used to swing a weapon or pull a bowstring taut, and with too little speed to deliver an attack without being trivial to dodge. The movement is also hard to finely control, causing any skill checks made to accurately manipulate the object (such as playing an instrument, or using thieves' tools) to be made with disadvantage, unless you're using a hand to interact with the object yourself.
When the spell ends, the force slowly wanes, causing the object to fall softly. It does not take damage for falling 3 meters or less.
You can only have one instance of this spell active at any given time.

> **Augment**
The number of instances of this spell you can have active at any given time increases to two at 5th level, three at 9th level, four at 13th level, and five at 17th level. Two or more instances of this spell can be 'summed together' to carry an object of greater weight, such as using two instances to carry  a single object weighing 5kg.

**Comment by wherfz** [comment]
This is a good flavorful cantrip. It's a little wordy, but overall its better to be specific with a cantrip like this. The wording appears good as is. 

If you wanted to condense it I would change the beginning of the second paragraph to:
"The force moves the object with too little force and speed to deliver an attack without being trivial to dodge."

**Comment by mlenser** [comment]
> The movement is also hard to finely control, causing any skill checks made to accurately manipulate the object (such as playing an instrument, or using thieves' tools) to be made with disadvantage, unless you're using a hand to interact with the object yourself.

This part can be skipped as the object is always within 5 feet of you so it's not a big concern and Minor Telekinesis can pick locks out to 30 feet.

**Comment by mlenser** [comment]
Refined wording: ![image](https://user-images.githubusercontent.com/235857/81772867-3d002f80-94e7-11ea-9d35-114deddb4472.png)

I think 1 object at atime makes sense when compared to Minor Telekinesis.

**Comment by eunomicZenith** [comment]
> While the spell is active, you have some telekinetic control over the object to flip the pages of a book, pluck the strings of a harp, or slowly move the object around you.

This seems incorrect syntax-wise. Maybe "control over the object, enough to...".

> The control is not fine enough to make an attack with the object.

I understand the desire for brevity, but I'm really unsatisfied with this. It doesn't really provide a satisfactory explanation for why you can play an instrument with this but you can't swing a club or have it put a torch to your opponent's face (neither of which need precision). The wording I gave might have been too long, but this feels like it handwaves things away.

> I think 1 object at atime makes sense when compared to Minor Telekinesis.

I don't know what else to say other than "I wish you had decided otherwise". Floating multiple small objects is a big chunk of the fun!

**Comment by mlenser** [comment]
> Floating multiple small objects is a big chunk of the fun!

It sure is, but Minor Telekinesis can't do it and that cantrip is using your whole focus. This cantrip isn't even using that.

**Comment by eunomicZenith** [comment]
Mind answering to the other parts of my message?

**Comment by mlenser** [comment]
Was working on that. Improved wording:

> While the spell is active, you have some telekinetic control over the object, enough to flip the pages of a book, pluck the strings of a harp, or slowly move the object around you. The control does not allow enough force to be applied to make an attack with the object.

**Comment by eunomicZenith** [comment]
I guess that's good enough.
