### ISSUE TITLE
Forced Reflex

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#209]
**Forced Reflex** (cantrip, blood/mind/fear/charm)
> As an action, you compel a creature that you can see within 18 meters to do a simple physical action, affecting its nervous system. The target must succeed on a Reflex saving throw or follow the command immediately.
> Some typical compulsions. You might compel a different action than one described here. If you do so, the DM determines how the target behaves. 
> - The target falls prone.
> - The target drops an object it is holding with one hand.
> - The target lets go of a creature it is grappling.
> - The target makes a simple interaction with an object in its space, such as picking up a knife, pulling a lever, or kicking a box.
> - The target momentarily averts its eyes or drops its guard. Attacks against the target have advantage until the start of its turn.
> - The target feels a painful muscle spasm, and cannot take reactions until the start of its turn.

The flavor is meant to be physical puppeteering (affecting their nervous system, like an unwanted reflex) and not mind control. But it could be changed.

Also, some notes to help judge this:
* Minor Illusion deals 1d3 (scales) damage to the target, takes away its reactions, and grants advantage on melee attacks against it. Time Flux deals 1d6 and takes away reactions.
* Shove is an attack anyone can make that pushes the target prone.
* Disarm mentions that interaction with an object in a hostile space requires both your action and a successful ability check.
* I made this a Reflex saving throw because it's very fitting, but it could just as well be a Will saving throw.

**Comment by mlenser** [comment]
> The target falls prone.
> Attacks against the target have advantage until the start of its turn.

This gives all allies advantage on all attacks until the creature stand up on their turn. This is far beyond what a cantrip should be able to do.

> The target drops an object it is holding with one hand.

This is effectively half damage, potentially permanently. This is far beyond what a cantrip should be able to do.

________________

The power level of this is far beyond that of any other cantrip.


> Minor Illusion deals 1d3 (scales) damage to the target, takes away its reactions, and grants advantage on melee attacks against it.
Minor Illusion should not be that strong. I'll fix it.

**Comment by itamarcu** [comment]
> Minor Illusion should not be that strong

Heh, oops. 

> This gives all allies advantage on all attacks until the creature stand up on their turn. This is far beyond what a cantrip should be able to do.

But... but Shove is an ability that anyone can do and can push an enemy prone (for an enemy within your reach). It even costs an attack, and not a whole action, so a martial could use it twice in one turn (and with proficiency/expertise in athletics, likely succeed). I think having to spend an entire action is a fair price to pay for what is basically a long-distance Shove.

> This is effectively half damage, potentially permanently

Can you explain why you consider this effectively half damage permanently? As far as I know, the object that a creature drops in its own space can just be picked up again right at the start of the creature's turn, so no damage is lost.

Only if two players combine abilities to both disarm an opponent and push the opponent away from its weapon (requiring two failed saves, and two actions) it is a permanent effect, And even then the opponent could have backup weapons equipped, pick up a weapon from a nearby body, or just be one of the majority of monsters who don't use weapons, or hold their weapon with two hands.

**Comment by Paulorpribeiro** [comment]
What you are sug gfesting is basic the command spell (which is 1 mana, 1st level in RAW), but as a cantrip, and plus some more uses.
I will say I (as a DM) wiuld allow everything you wrote there as pissible with t hge command spell, if you could command it in one word. But it is way too powerful as a cantrip

**Comment by itamarcu** [comment]
Nah, this is specifically inspired by that spell and meant to *not* be the command spell. It doesn't spend the target's action, it can't do any complex things (only grab a thing, let go of a thing, or fall down), it lasts for less time (until the target's turn, and not for what is functionally a full round from one turn of the target to the next), and it has a different flavor (nervous system instead of compulsion).

**Comment by Paulorpribeiro** [comment]
It was my oversight comparing it to command, it wastes the targets turn, which is way worse

But disarm is was 2 mana spell on the 10 mana version , 1 mana in this version,  and I can't see how a limited disarm could be made other than "disadvantage on the next attack".
One other thing I think this cantrip shouldn't do is to bend down and pick up an object. This is too complex for a caster to make.the trarget do if they are minimally resisting the caster (which I assume they always are, since this is not mind control, but "limb control")

Finally, I wouldn't put the same ca trip in 4 themes, I think the "mind themes" are weird choices, since this is not a mind influence, while I think it is suited for telekinesis and maybe blood

**Comment by itamarcu** [comment]
Yeah, it was hard to really figure out which theme this fits, so I basically just gave suggestions. I think Blood makes the most sense, and it could be themed and rewritten as basically limited bloodbending.

> One other thing I think this cantrip shouldn't do is to bend down and pick up an object.

Yeah, that's fair, a bit too complex.
