### ISSUE TITLE
Climber feat should be in Beast and Plants

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#210]
https://www.kryxrpg.com/themes/feats/climber

Currently it's just in Alteration.

I think this should be added to Beast (as a lot of beasts can climb, and beast-like fighting can totally involve climbing), and Plants (as people like climbing on plants, and even plants like climbing on plants).

**Comment by mlenser** [comment]
That feat doesn't exist. It was removed 4 days ago when the Climb Maneuver was added. Climbing is already part of Bestial Transformation so that covers it for Beast.

The Climb spell and maneuver are already part of Plants.
