### ISSUE TITLE
Striking Requital

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#211]
**Striking Requital** (3 stamina maneuver, skirmish)
> As a reaction, which you take when an enemy makes a melee attack against you, you can impose disadvantage on the attack, potentially causing it to miss you. If the attack misses you in this way, you can turn the force of the attack against your attacker, forcing it to make a Fortitude saving throw. On a failed save, the attacker becomes stunned until the end of its next turn.
> *Enhance:* 
> You can expend one additional stamina die to increase the duration of each effect to one minute. The target can repeat the saving throw at the end of each of its turns.

**Comment by mlenser** [comment]
This seems like Patient Defense, but a reaction and stunned instead of damage.

I don't think this can exist in a world next to Nimble Dodge which is 5 stamina for +5 AC which is the equivalent of disadvantage.

*Note: As a general rule I don't apply conditions without at least 1 dice of damage which I think should hold here.*

**Comment by itamarcu** [comment]
Nimble Dodge is 5 stamina for +5 AC to all attacks until your turn - not just a single attack,

Patient Defense, similarly, is disadvantage against all attacks (as it's a Dodge)

As for applying a condition - I guess you could make this deal 1 stamina die of damage, plus the stunning condition. You could replace the Enhance with simple additional damage, too.

The goal of this maneuver is "make effort to deflect a single melee attack" (tried to make it different than Deflect Missiles). I guess you could simply replace the condition with more damage. I think it could alternatively be neat if this allowed you to push the enemy away from you or make the enemy prone (I'm imagining a monk who pulls an enemy's sword arm and forces the enemy to step to their other side, or a warrior who bashes an enemy with a shield in the same motion that blocks an attack, pushing away the enemy).

**Comment by mlenser** [comment]
Stunning strike, which is 1d8 + stun as a bonus is 4 stamina dice: 
![image](https://user-images.githubusercontent.com/235857/82011737-3653f280-9676-11ea-8083-68515193a93c.png)

Making it a reaction makes this far too strong for any tier:
![image](https://user-images.githubusercontent.com/235857/82011768-453aa500-9676-11ea-948b-2aa96f021aef.png)

I believe what you're after is too strong for maneuvers so closing this. Can reopen if the goal is changed.
