### ISSUE TITLE
Improve Manipulate Sound

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#213]
https://www.kryxrpg.com/themes/spells/manipulate-sound
> **Manipulate Sound**
> *1 minute*
> As an action, you can manipulate sound within 9 meters. You create one of the following magical effects.
> - Your voice booms up to three times as loud as normal.
> - You create an instantaneous sound, such as a rumble of thunder, the cry of a raven, or ominous whispers.
> If you cast this spell multiple times, you can have up to three of its effects active at a time, and you can dismiss such an effect as an action.

It should have more options, and not just be a worse Thaumaturgy.

Suggestions:

> - You can make a creature's voice or an object's sound up to four times louder or quieter.
> - You can alter the pitch of a sound, making it high-pitched or low-pitched
> - You can add noise to a voice, making it difficult to understand, or reduce noise, making the sound clearer
> - You replicate a voice you've heard. If you attempt to mislead a creature this way, make a Deception check contested by the creature's Insight check.
> - You replicate your own voice, whispering a few words into the ear of a creature.

**Comment by DalenWBrauner** [comment]
Replicating a voice you've heard might be a bit much- I think that's a cool effect, but maybe should be somewhere other than a cantrip.

I might add:
- You can play brief, minor musical effects, such as light percussion or a simple bass line.

**Comment by itamarcu** [comment]
Yeah, that's a good addition!

> Replicating a voice you've heard might be a bit much

It's basically a weakened version of what [Control Sound](https://www.kryxrpg.com/themes/spells/control-sound) lets you do. Control Sound has:

> You can substitute any sound you have heard for the target sound. If you attempt to exactly duplicate the voice of a specific individual, or an inherently terrifying sound (such as a dragon’s roar), you must succeed on a Deception ability check with advantage opposed by the intended listener’s Insight check to avoid arousing suspicion.

And [Minor Illusion](https://www.kryxrpg.com/themes/spells/minor-illusion) has:

> If you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else’s voice, a lion’s roar, a beating of drums, or any other sound you choose. The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends.

I think that, in terms of power level, Manipulate Sound should be stronger than Minor Illusion, and Control Sound should be stronger than both.

Therefore, I made Manipulate Sound able to replicate a sound you've heard, but you don't get advantage on that check.

If I could alter the other two spells easily, I'd change them to - 

- (nerf) Minor Illusion can only replicate non-voice sounds that you've heard
- (buff) Control Sound can make any sound you can imagine, and can replicate someone else's voice saying something that person did not say before

**Comment by mlenser** [comment]
> You can add noise to a voice, making it difficult to understand

I think this is problematic in social situations.

Regarding replicating:
> You create an instantaneous sound whose volume can range from a whisper to a scream. It can be your voice, someone else’s voice

This wording,which is nearly the same as Minor Illusion should cover the case. Neither mentions replicating, but surely the cantrip would allow for it as you can create a Lion's roar.

**Comment by mlenser** [comment]
Added additional options to Manipulate Sound
