### ISSUE TITLE
(Minstrel) Melodious Spell Performance

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#215]
A suggestion for a deceit-based performance:

**Melodious Spell**
_Prerequisites: Deceit theme_
You cunningly weave your spellcasting into your performance. If the next action you take is to cast a spell, attempt a Performance check against all observers’ passive perceptions. If your Performance check is successful against an observer’s passive perception, that observer doesn’t notice that you are casting a spell, even though normally spells have sensory manifestations that would make spellcasting obvious to those around you, and verbal, somatic, and material components are extremely overt. You hide all of these as part of an ordinary performance.

**Comment by DalenWBrauner** [comment]
I like this, but I wonder if it should be against their Insight instead.

It also seems like making a Deception check might be more appropriate. While it's certainly _important_ to be able to keep up the performance, you're primarily trying to see if you can slip the spell past your audience, not if you can continue to play well while doing so. (Yes, playing poorly might tip the audience off, but avoiding playing in a suspicious way sounds more like Deception territory to me.)

**Comment by Lamorak11** [comment]
This performances is lifted almost entirely from Pathfinder 2e, and converted to this homebrew.

It requires deciet as a theme to "unlock", but I think that performance is still the correct skill for it - it is deceptive, but it's your skillful musical abilities, not your deceptive capabilities, that determine the success - it's a Performance, after all. 

As for Perception vs Insight, again it could be argued to be either, but the main reason I think perception is the correct choice is that passive perception is a thing. It's a DC the bard's performance check can roll against. As passive insight doesn't exist you'd have to do a roll-off for all the observers against the bard's performance check and that would bog the ability down.

**Comment by mlenser** [comment]
Somatic/Verbal aren't officially part of the game until #186. That seems essential for this.

**Comment by mlenser** [comment]
Closing this for now since #186 is not a top priority. If it is in the future then we can bring this back.
