### ISSUE TITLE
(Minstrel) Battlesong Feature

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#216]
A tentative draft for the feature discussed on discord. 

**Battlesong**
Minstrels rarely stop performing while they and their allies fight, and as they do they weave their magic into this performance, enchanting their allies and adapting their music on the fly to better suit their needs. 

Your battlesong is a magical aura that affects all allies within 30(60?) feet that can hear you. Starting your battlesong is a bonus action and lasts until you are incapacitated, choose to stop it, or are otherwise prevented from performing (your instrument is lost, you enter a silence effect, etc). Your battlesong has four modes, and you can change mode as a bonus action on your turn.

- High Tempo: your allies gain +5 to their movement speed and may use their bonus action to dash. 

- Staccato Rhythm: your allies gain a +1 bonus to their AC and reflex saving throws. 

- Thunderous Cadence: your allies gain a +2 bonus to their damage rolls. 

- Uplifting Lilt: your allies gain a +1 bonus to their Will saving throws and gain 1d4 temporary HP at the start of their turn.

**Comment by Lamorak11** [comment]
As a note: I originally had High Tempo just grant the movement speed but that felt underwhelming. Bonus action dash may be a bit too much, on the other hand.

**Comment by itamarcu** [comment]
How about just making High Tempo +10 ft to movement speed?

Also, Uplifting Lilt needs "at the start of each of their turns", I think. In addition, note that it doesn't scale very well, as 1d4 hp per round is a lot on early levels but pretty bad at higher ones. Perhaps make it a number of hit points equal to half your level? or your proficiency modifier?

**Comment by DalenWBrauner** [comment]
I would suggest having the Battlesong be 60ft:
1. If we make it 30ft, then this benefit becomes a little more difficult to keep track of which characters do and do not have it in a combat scenario. With 60ft, it's more likely your party members meet the criteria (and more notable when they do not), so it should be noticeably easier to run.
2. While 30ft can encourage more tactical, stay-close-to-the-bard play, I'm not sure that's the right direction. 60ft allows a Bard to assist their teammates whether they prefer their character in the frontline, in the backline (but not too far), or the center of the party.
3. If we make it 60ft, it feels more inline with the flavor of "being able to hear it is what grants you the buff". Any further than 60ft and the sounds are less clear, i.e. less effective.  You shouldn't need to be in 30ft of your bard's blasted bagpipes to fully hear the battlesong.

Also,
> note that it doesn't scale very well, as 1d4 hp per round is a lot on early levels but pretty bad at higher ones.

I like this observation, but free temp hp every round for all allies can add up very fast. I would guess your suggestion of a flat amount equal to your proficiency modifier is about right.

**Comment by Lamorak11** [comment]
I like the temp HP = to proficiency idea.
And yes, thematically the radius should be 60ft
I'm struggling to determine how good 5ft or 10ft speed is in the system. Would like someone more savvy with these things to weight in.

**Comment by mlenser** [comment]
It'd probably be nice to have Hasted 1 be one of the options and then build other options around that lower level.

**Comment by Lamorak11** [comment]
Isn't Hasted 1 powerful for an always on feature?

I imagine its usage would need to be limited a fair amount if that was the power-level of the options.

**Comment by mlenser** [comment]
You're probably right, hasted one is probably too much for a permanent buff.
________________________
Dashing is too much for this. +10 speed is quite strong.

_______________

> If we make it 30ft

All the problems you talk about with 30 feet and a Paladin's aura is protection is 10 feet by RAW and increases to 30 feet at level 18. I expanded this to 30 feet.

I think auras should probably be the same radius for both classes. 30 feet is quite far.

**Comment by Lamorak11** [comment]
Spit-balling here: What about a "5ft step" as a bonus action? (A 5 foot move that doesn't provoke an AoO)

Or are we better off sticking with minor passive benefits like the 5/10 foot move bonus?

**Comment by mlenser** [comment]
The 5 foot step was removed from D&D and I don't think we should bring it back.

I think you're undervaluing +10 speed. It's a 4th level feat to get that benefit. It can be quite useful.

**Comment by mlenser** [comment]
Battlesong added as a core feature
