### ISSUE TITLE
(Minstrel) Minstrel Lore Feature

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#217]
Converted from Pathfinder 2e

**Minstrel Lore**
Your studies make you informed on nearly every subject. You are capable with Minstrel Lore, a unique Intelligence skill that can only be used in the place of Alchemy, Arcana, Engineering, Nature, Occult, Psionics, Religion and Society checks made to recall lore or identify monsters. 
     You become proficient with Minstrel Lore at 9th level, and gain expertise at 17th level

**Comment by mlenser** [comment]
Where is this in PF2e? This feels like too much.

**Comment by Lamorak11** [comment]
**Bardic Lore**, PF2e:
Your studies make you informed on every subject. You are trained in Bardic Lore, a special Lore skill that can be used only to Recall Knowledge, but on any topic. If you have legendary proficiency in Occultism, you gain expert proficiency in Bardic Lore, but you can’t increase your proficiency rank in Bardic Lore by any other means.


This is what "Recall Knowledge" can achieve in PF2e:

**Arcana**: Arcane theories, magical traditions, creatures of arcane significance, and arcane planes.
**Crafting**: Alchemical reactions and creatures, item value, engineering, unusual materials, and constructs.
**Lore**: The subject of the Lore skill’s subcategory.
**Medicine**: Diseases, poisons, wounds, and forensics.
**Nature**: The environment, flora, geography, weather, creatures of natural origin, and natural planes.
**Occultism**: Ancient mysteries, obscure philosophy, creatures of occult significance, and esoteric planes.
**Religion**: Divine agents, divine planes, theology, obscure myths, and creatures of religious significance.
**Society**: Local history, key personalities, legal institutions, societal structure, and humanoid culture.

**Comment by mlenser** [comment]
Ya, that seems way like a far superior version of Jack of all Trades and way more powerful. Its one skill for many and can also get up to expertise! Sure, it's limited to knowledge, but if you have the knowledge you should then be able to do something with it too (I know that is not always true, but should be for the game's purpose, imo)

I don't think this can work.
