### ISSUE TITLE
(Minstrel) Elusive Spellsong Feature

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#218]
**Elusive Spellsong**
Your musical magic is difficult for other spellcasters to decode or anticipate.
Skill checks made to dispel or counterspell your spells and magical abilities are made with disadvantage. 

Could be a minor feature given to minstrels at level 5, to mirror the mage's studied antimagic.

**Comment by mlenser** [comment]
- Elusive Spellsong feature added at level 2
