### ISSUE TITLE
Remove bonus action from Fast Loader

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#219]
> Thanks to extensive practice with loading weapons, you can use a bonus action to reload a weapon with which you are proficient that has the loading property.

I don't see reason why this needs a bonus action. This makes crossbow hunters pretty bad, since they can't use maneuvers and spell strikes when they use their extra attack.

**Comment by mlenser** [comment]
It's not thematic thematic that a crossbow can shoot as often as a bow.

And removing the bonus action makes crossbows as quick as bows to shoot. Which then makes crossbows the best option and no one should use bows.

**Comment by itamarcu** [comment]
That does sound very fair, but where is that "repeating crossbow" coming from? there is no such weapon in the weapons or magic items lists.

**Comment by Marcloure** [comment]
> And removing the bonus action makes crossbows as quick as bows to shoot. Which then makes crossbows the best option and no one should use bows.

Except that it costs a feat.

My problem is that with the current situation, there is no reason why someone would pick a crossbow unless they are an Alchemist. Bow allows for more attacks and lose nothing after 5th level.

**Comment by mlenser** [comment]
> Except that it costs a feat.

A feat shouldn't remove all thematics. Crossbows are slower than bows. Allowing a repeating version allows the thematics to persist.

Besides, bows don't have a comparable damage boost feat available. So the opportunity cost isn't there. But even if they did the above is still true.

Bows and Crossbows are different and we should play into that, not make them the same.

**Comment by mlenser** [comment]
Side note: in PF2e's action economy a crossbow is 1 action (similar to a bonus action). I could see making that a default rule.

**Comment by Marcloure** [comment]
> Bows and Crossbows are different and we should play into that, not make them the same.

That is fair and good, but currently I don't think it is satisfied. It's simply a matter of "do I have extra attack"?

> Side note: in PF2e's action economy a crossbow is 1 action to reload (similar to a bonus action). I could see making that a default rule.

While I understand why, that would completely remove any crossbow Rogue or Warrior from the game.

**Comment by itamarcu** [comment]
How about this?

> ***Loading***. Because of the time required to load this weapon, you can fire only a limited number of shots from it, **until you spend a bonus action reloading the weapon**. The number of attacks you can make before having to reload the weapon equals its loading number.

> ***Heavy Crossbow*** - 50 sp, 1d10 piercing, Ammunition, heavy, loading **1**, two-handed

(same change for other crossbows, and probably reduce their price, too)

And then add:

> ***Repeating Heavy Crossbow*** - 300 sp, 1d10 piercing, Ammunition, heavy, loading **4**, two-handed


And replace the feat "Fast Loader" with:

> Thanks to extensive practice with loading weapons, you can spend half your movement to reload a weapon with which you are proficient that has the loading property, instead of spending a bonus action.

**Comment by mlenser** [comment]
> currently I don't think it is satisfied. It's simply a matter of "do I have extra attack"?

Then lets find a way to make bows and crossbows different.


> that would completely remove any crossbow Rogue or Warrior from the game.

Not with repeating.

Plus the wording for Loading is problematic. It shouldn't allow attack + snap shot in a turn. It shouldn't allow for Rain of Arrows or Volley. With repeating and a full clip? sure. Otherwise, no.

**Comment by itamarcu** [comment]
> It shouldn't allow for Rain of Arrows or Volley

I disagree - Just like how an archer can pull back several arrows at once and shoot them all simultaneously (sacrificing accuracy and stamina to do a shotgun-like attack), so should the crossbow wielder be allowed to jam multiple bolts into the crossbow and shoot them together haphazardly.

**Comment by mlenser** [comment]
Rain of Arrows and Volley are not shooting multiple arrows at a time. It's shooting them very quickly, one after another. Which the crossbow can't do.

**Comment by itamarcu** [comment]
(This was closed because @mlenser changed the wording of Loading to:
> This weapon takes time to reload. Once you fire a piece of ammunition from it, you must use an action or bonus action to reload it before you can fire another piece of ammunition from it. Repeating versions of crossbows, which have 5 shots per cartridge, can be purchased at your GM’s discretion for 100 sp more than than a cost of a normal crossbow.
)
