### ISSUE TITLE
Shock damage

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#220]
Shock deals the same damage whether used at melee or ranged

**Comment by mlenser** [comment]
So does Icicle, so does Shadow Blade.

I'm not sure it should be different, actually. A melee cantrip is actually a benefit to avoid disadvantage if a creature attacks you in melee.
I have a feeling that cantrips are different in this regard.

**Comment by Marcloure** [comment]
If you judge that the damage should be the same, I'm fine with that as well. I just though this was some mistake.

**Comment by Paulorpribeiro** [comment]
Produce flame as well. I think it got changed when you reduced the range of several cantrips (which I think was a good call).
But I think ranged damage should be smaller. When you are at a range (and the new range of 60 ft is quite far, most creatures can't cover that and attack in the same turn) you usually don't need to worry about retaliation. Of course if youhave a creture in meele with you meele cantrips are better. But ranged attacks usually deal less damage (in most weapons tables that compare weapons, the meele weapon damage die is bigger) when compared in a vacuum.

This is not a video game of course but a character with ranged attacks can quite easily "kite" meele enemies until they kill them.

**Comment by mlenser** [comment]
Weapons have a 1 size difference (1 damage). Cantrips scale so 1 damage becomes 5 which is too much.

**Comment by itamarcu** [comment]
The benefit of having a melee option for cantrips is not just getting no disadvantage with them, but also [War Caster](https://www.kryxrpg.com/themes/feats/war-caster) allowing you to make cantrip opportunity attacks. Furthermore, you get advantage against prone targets, and you get crits against paralyzed targets.

I don't think ranged cantrip damage should be nerfed. Casters are expected to fight at range. These cantrips get the option of attacking at melee range as a bonus usability feature, that is sometimes more useful than ranged combat.

You should also consider the fact that many attack cantrips are save-based, and then ranged and melee combat are the same.

**Comment by mlenser** [comment]
I agree with @itamarcu. Melee is not necessarily as bad for cantrips. I've made a note of it on the spreadsheet and will close this issue.
