### ISSUE TITLE
Assassinate is overpowered

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#221]
- You have advantage on initiative rolls.
- You have advantage on attack rolls against any creature that hasn’t taken a turn in the combat yet.
- Any hit you score against a creature that is surprised is a critical hit.

**Comment by Paulorpribeiro** [comment]
Yeah, if I remember correctly this is very similar to a 3rd level feature of the assassin subclass. So I'd say 4th at most?

**Comment by mlenser** [comment]
"Evaulate its strength" means put it into the DPR calculator and see how strong it really is. Especially with spells/maneuvers as possibilities.

**Comment by mlenser** [comment]
Ok, assassinate is problematic. Other feats:
- GWM adds ~4-6 DPR for a typical character & ~7 for a Warrior
- Polearm adds ~4-5 DPR for a typical character & ~6 for a Warrior
- TWF adds ~4-5 DPR for a typical character & ~10 for a Warrior

Assassinate adds 12 DPR to a Rapier Rogue and likely even more for a Warrior, especially with action surge - though that's like 20 mins of calculation that I'm going to avoid as 12 DPR on a rogue is ~2-2.5 as strong as other feats.
![image](https://user-images.githubusercontent.com/235857/81975321-2234d480-9627-11ea-85d9-89ace2f28201.png)

Not only the DPR side of things, encounters can be significantly ruined by alpha striking the main boss for 100 damage in the first of every encounter.

## Conclusion
Something has to change

**Comment by Paulorpribeiro** [comment]
I don't know how you came to DPR calculation for the assassinate, if it can only be used once per encounter, unless in some weird combination. It's a huge attack once, but after that the feat is not "useful" for the next couple of rounds until t the fight is over.

That said, my gut feeling is that, even though assassinate is very thematic for a rogue, alfa striking is not fun for the others in the table. 
I would suggest not giving a guaranteed crit and just double weapon dice if the target is surprised, keep everything else on the feat. Have to check if the damage is in line with this change but it will most certainly bring it down

**Comment by Paulorpribeiro** [comment]
I'd go even further and say triple the damage of a dagger. To incrntivyze the poor dagger that was the perfect assassination tool but is never used because of its 1d4 damage

**Comment by itamarcu** [comment]
As for the damage calculation - from looking over that picture (which I admit I don't understand fully), it looks like you're doubling the damage of maneuvers and opportunity attacks, both of which shouldn't be affected, as maneuvers are post-attack and opportunity attacks are not against a surprised target.

Plus, like mentioned above, Assassinate can only be used once per fight, not every round. If the three other feats add ~4 DPR, and battles last an average of 3 rounds, it seems fair that Assassinate would add ~12 damage to the first round and 0 to the other rounds. It is also, of course, much less consistent than feats like Two-Weapon Fighting (that always help you).

Despite all of the above, though the feat does feel a bit wrong to me. I don't like how it gives advantage to initiative and attack rolls in every fight (regardless of if you are surprising someone or not). I also think it shouldn't affect more than one attack, because it's silly that a fighter can action surge and use it four times, and crit each time. People tend to stop being oblivious after the first stab.

Plus, I like Paulo's dagger buff!

I suggest:

> You are at your deadliest when you get the drop on your enemies. You gain the following benefits:
> 
> - Every combat, the first hit that you score against a creature that is surprised is a critical hit. 
> - When you score a critical hit with a dagger, you deal additional damage equal to your attack's ability modifier.

**Comment by mlenser** [comment]
> I don't know how you came to DPR calculation for the assassinate, if it can only be used once per encounter, unless in some weird combination

**As always, the calculation is available on the spreadsheet.** If people want to be involved in these discussions its up to them to learn the system and know the numbers.

It is indeed used once per encounter, which is ~19% of the day. As always, this will vary with some days having more encounters and some less, but in the "average" it should be around here.

**Note:** I did a slight miscalculation here, and had the usage ~23%. with this new number the DPR increase is 10, not 12. But I also forgot to take into account the advantage on another round so that'd boost it higher, but is time consumimg to calculate.

> It's a huge attack once, but after that the feat is not "useful" for the next couple of rounds until t the fight is over.

A huge attack once is what is called Alpha striking. It is pretty regularly the best strategy possible in D&D - there are threads about alpha striking and competitions for it dating back to at least 3e because of its powerfulness. If you can alpha strike a big creature on turn 1 an encounter changes massively. A deadly encounter can become easy or medium in difficulty.

______________________________

> alfa striking is not fun for the others in the table.

100% agreed. Even if this feat was more balanced, I think it's poorly designed for fun.

> I would suggest not giving a guaranteed crit and just double weapon dice if the target is surprised

This changes nothing. It's effectively the same.

_______________________________

> I'd go even further and say triple the damage of a dagger. To incentivise the use of the poor dagger that was the perfect assassination tool but is never used because of its measly 1d4 damage

That doesn't alleviate anything. Using a dagger vs a rapier on assassinate is a 1 DPR difference. If you then tripple the damage of a dagger then you're definitely higher than the original Rapier after you take other factors into account like maneuvers.

______________________________

> doubling the damage of maneuvers [...] which shouldn't be affected, as maneuvers are post-attack and opportunity attacks are not against a surprised target.

Maneuvers are 100% affected by crits:

> When you score a critical hit, you get to roll extra dice for the attack’s damage against the target. Roll all of the attack’s damage dice twice and add them together.

Maneuvers are extra dice and there is no save on Ambush for example.

**Comment by mlenser** [comment]
Assassinate feat renamed Ambusher and drops the 3rd bullet about auto critting

If there is still a need for some kind of Assassinate aspect I agree with what @Lamorak11 said on discord:
> I'd rather we make a maneuver that carries the flavour of an assassination, as the assassinate feat as it currently stands isnt really used as the flavour suggests anyway

**Comment by Paulorpribeiro** [comment]
I agree with you on the fix and I 100% agree that we should make an assassinate maneuver (auto crit will be the obvious choice of mechanic to simulate an assassination, but I get ahead of myself...). 
In the future I will check the spreadsheet if I were to dig into the numbers and give suggestions better than gut feeling, which, while not as refined as number crunch, are also useful for the discussion.

**Comment by mlenser** [comment]
> gut feeling

Off topic, but based on the years I've discussed D&D online I find discussions based on gut feeling to be entirely unproductive discussions. Additionally, they are time consuming to discuss and can poison the well-water.

**_Discussions on balance should always be data driven_**. If the data is wrong then it can be adjusted and the conclusion can be changed. Without data it's all just opinion and that has a negative value associated with it, in my experience.
