### ISSUE TITLE
Feat to increase AOE of concoctions

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#222]
Alchemists lack cool feats for themselves, since they can't get most feats related to spells and don't care about most martial feats. A suggestion would be a Feat that increases the AOE of a concoction by 5 ft. once per long rest. What do you think?

**Comment by mlenser** [comment]
Many concoctions have the following wording:
> You can expend 1 additional catalyst to increase the size of the impact to each creature within 10 feet.

I think concoctions should scale automatically like a spell does. Have them be a sphere.

In terms of feats for an Alchemist: I think PF2e might provide some inspiration.

**Comment by mlenser** [comment]
All AoE Concoctions have been converted to spheres
