### ISSUE TITLE
Holy Spell: Angelic Wings

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#223]
**Angelic Wings** (2 mana, holy) 
As an action, wings of divine light spread out from your back, granting you a flying speed of 60 feet for the duration. Your wings cast bright light in a 15-foot radius and dim light for an additional 15 feet. When this spell's duration would end, if you're still flying, you float gently to the ground at 60 feet per round.

**Comment by itamarcu** [comment]
There better also be **Demonic Wings** in the unholy theme that give you evil bat-wings and reduce light in a 15/30 radius sphere around them!

**Comment by Lamorak11** [comment]
Absolutely! Devilish/Demonic Wings could absolutely work, although I don't think they are particularly known for reducing light :P

**Comment by mlenser** [comment]
The best movies always shround the monster with a bit of darkness and only show bits and pieces.

**Comment by mlenser** [comment]
Angels Wings are feathers though, not light. Unless we're talking Diablo. But I'm going to go with the option that appears on the MM under angels and on google under angels wings which is white feathers. So no light.

**Comment by mlenser** [comment]
- **Blood**
  - Leathery Wings added as a copy of Fly
  - Vampiric Wings feat changed to cast Leathery Wings at will
- **Holy**
  - Angelic Wings added as a copy of Fly
  - Celestial Wings feat added to cast Angelic Wings at will
- **Unholy**
  - Demonic Wings feat added to cast Leathery Wings at will
  - Leathery Wings added as a copy of Fly
