### ISSUE TITLE
Alchemist Feats from PF 2e

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#224]
I checked the Alchemist's Feat list from PF 2, and compiled the ones I found worth here. Before I write the feats properly, I would like to know which ones you think make the cut.

**Directional Bomb** changes a sphere AOE to a cone:
https://2e.aonprd.com/Feats.aspx?ID=104

**Debilitating Bomb** add small conditions to bombs
https://2e.aonprd.com/Feats.aspx?ID=103
Also has a greater vertion:
https://2e.aonprd.com/Feats.aspx?ID=110
And a "True" version:
https://2e.aonprd.com/Feats.aspx?ID=118

**Smoke Bomb** add a fog effect to any bomb
https://2e.aonprd.com/Feats.aspx?ID=98

A draft suggestion of my own
**Sticky Fire/Napalm** (can be limited per day)
When a concoction you created cause the burning condition to a target, the DC to reduce the burning level of that target increases to 12. Additionally, water and sand doesn't extinguish the fire on the target. The effects of your sticky fire ends when the burning level on the target is reduced to 0.

**Comment by mlenser** [comment]
> Directional Bomb changes a sphere AOE to a cone:
https://2e.aonprd.com/Feats.aspx?ID=104

Spheres are stronger than cones by a bit so this would be ok.

> Debilitating Bomb add small conditions to bombs
Sounds good as a feat which lets you add catalysts for effects. I'd have to calculate some effects to make it work.

> Smoke Bomb add a fog effect to any bomb
https://2e.aonprd.com/Feats.aspx?ID=98

We already have https://www.kryxrpg.com/themes/concoctions/smoke-bomb. It should remain separate like Fog Cloud and similar spells are, imo.

> Sticky Fire/Napalm (can be limited per day)
When a concoction you created cause the burning condition to a target, the DC to reduce the burning level of that target increases to 12. Additionally, water and sand doesn't extinguish the fire on the target. The effects of your sticky fire ends when the burning level on the target is reduced to 0.

I think this should be a catalyst augment to Alchemical Fire for example. Grease would work in the same manner.

**Comment by mlenser** [comment]
- Directional bomb added to concoction themes
- Sticky Napalm added as an augment to Alchemical Fire

Re Debilitating Bomb: Can you please open a new issue and try to explain the flavor of the desire and try to translate the desire to the conditions in my system? I'm a bit unsure what the desire is. Staggering? Does that make sense? What else would make sense?
