### ISSUE TITLE
Charming Presence duration

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#225]
Charming Presence has no listed duration on the spreadsheet, but I believe its duration could be increased to 5 min/mana to allow more use out of combat.

**Comment by mlenser** [comment]
## Maneuver
![image](https://user-images.githubusercontent.com/235857/81976322-a6d42280-9628-11ea-9aac-64a0638d5b1f.png)
![image](https://user-images.githubusercontent.com/235857/81976363-b9e6f280-9628-11ea-855b-01b22e69ea03.png)

## Spell
![image](https://user-images.githubusercontent.com/235857/81976394-c23f2d80-9628-11ea-828c-8da239920139.png)
![image](https://user-images.githubusercontent.com/235857/81976409-c79c7800-9628-11ea-96e2-731dfbe750df.png)

What am I missing?

**Comment by mlenser** [comment]
Closing, can reopen if there is an issue.
