### ISSUE TITLE
Assassinate

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#226]
Continuing #221 - I decided to try and make a maneuver for assassins.

We decided that auto-critting a surprised target at the beginning of the fight for free is too powerful. Therefore, I suggest the following maneuver:

> **Assassinate** (1 stamina, shadow+skirmish)
> As a bonus action when you attack a surprised creature with a weapon attack you can capitalize on its unawareness. Any weapon attack you make that hits the creature is a critical hit, until the end of your turn. If you are making the attacks with a dagger, you deal additional damage equal to your attack's ability modifier, each time.

**Comment by Marcloure** [comment]
I believe assassination should be a tier 2 thing.

About the maneuver power itself, it doesn't allow other maneuvers/spell strikes to go with it, so that is better. But another problem with auto-crit is that it's too variable from class to class. I think maybe just adding 2 damage dice per stamina die spent may be more balanced, but I'm not sure this is a good approach either.

I like the idea of a maneuver to use on surprise rounds though, maybe just not like that.

**Comment by itamarcu** [comment]
How about...

> **Assassinate** (1 stamina, shadow+skirmish)
> As a bonus action when you attack a surprised creature you can capitalize on its unawareness. If you hit, add twice as many stamina dice as you expended to the attack's damage, and the creature gains the *wounded 1* condition.
> *Enhance*
> You can expend additional stamina dice to increase the damage and the level of the wounded condition.

(If you think this should start as tier 2, just have it cost 2 stamina and deal the wounded 2 condition)

I added the wounded condition because I think it's quite flavorful and doesn't actually affect the effectiveness of the attack in most situations.

Note that adding damage dice per stamina die expended means these still have a chance of all doubling if the player gets a natural crit. So, technically, looking at the edge case, if a level 5 rogue gets the drop on a victim and manages to roll a critical hit (~10% chance, or ~14% if the rogue has the ambusher feat) with a rapier and +3 dexterity, the damage will be 2d8+3+4d6+8d8 which is 9+3+14+36 = 62 on average. Without the crit it would be 32.5.

If you don't want this to be affected by a potential critical hit, we could replace it with something similar:

> **Assassinate** (1 stamina, shadow+skirmish)
> As a bonus action when you attack a surprised creature you can capitalize on its unawareness. If you hit, add the maximum result of each stamina die you expend to the attack's damage, and the creature gains the *wounded 1* condition.
> *Enhance*
> You can expend additional stamina dice to increase the damage and the level of the wounded condition.

and then the damage without a crit would be 1d8+3+2d6+2\*8 = 30.5, and on a crit, 2d8+3+4d6+2\*8 = 42.

**Comment by Paulorpribeiro** [comment]
I like the proposal where you add the max of your stamina dice, instead of rolling the dice, that way you produce a powerful attack, but not an insta kill on a crit.
But I think the wounded 1 doesn't add a thing to the maneuver. The Wounded condition, if you read carefully, mans thst younare more likely to die after you are reduced to 0. This hardly ever applies to monsters (maybe important NPCs would roll death saving throws) and the conditiom will end up having 0 effect.

Just scratch the condition and leave the rest as is and I think it is very good

**Comment by itamarcu** [comment]
No, that's exactly the point - it's already balanced without it. The condition is just adding some flavor - you're trying to kill someone, so you're making wounds that are particularly deadly.

**Comment by Lamorak11** [comment]
> No, that's exactly the point - it's already balanced without it. The condition is just adding some flavor - you're trying to kill someone, so you're making wounds that are particularly deadly.

Plus, I'll point out that PCs aren't the only assassins out there. I'f I tell a player that he has just taken a load of damage from the sudden appearance of an assassin, and that he has gained the wounded condition, they are going to start to sweat - and that's great storytelling built into a manuever.

**Comment by mlenser** [comment]
## Wounded
`Wounded` isn't meant to be used by anything but dying. A bit like Exhaustion isn't meant for anything except the DM dishing it out as a severe consequence.

Grievous Wound gives a good example of a similar flavor: `and its hit point maximum is reduced for 1 hour by an amount equal to the damage taken by this maneuver`

## Crit
As the other points out, crit is problematic. Combine this maneuver with a high damage feature such as action surge or even sneak attack and the value becomes multiplicative.

## Flavor
The current flavor doesn't seem connected to assassinate. It feels more like a called shot. A maneuver that lets you always hit in the eye. Though I'm unsure how Assassinate should even be flavored, tbh.

**Comment by itamarcu** [comment]
Then I'll attempt a new revision:

> **Assassinate** (1 stamina, shadow+skirmish)
> As a bonus action when you attack a surprised creature you can capitalize on its unawareness. If you hit, add the maximum result of each stamina die you expend to the attack's damage, and the creature cannot regain hit points until the start of your next turn.
> *Enhance*
> You can expend additional stamina dice to increase the damage.

Replaced "wounded 1" condition with "cannot regain hit points for 1 round".

Alternative possibility is "If this damage reduces the creature to 0 hit points or less, it dies immediately", but I feel like that would be very mean to do to players.

You could also just leave it the way it is, just simply dealing 8 damage per die to a surprised target. I added the extra condition to give it the assassination flavor.

**Comment by mlenser** [comment]
That's about 25% stronger than a normal maneuver:

![image](https://user-images.githubusercontent.com/235857/82157048-70441500-987f-11ea-903a-171c8ba143f2.png)

### Mindset
Concoctions/maneuvers/spells shouldn't be balanced based on being rare/niche so the surprise condition does not impact the balance at all and shouldn't.

**Comment by Paulorpribeiro** [comment]
I like the fact that the extra damage is a static number instead of a a roll, so it's more reliable at the same time it doesn't go crazy high on a crit. 
If 8 is too high, we could use the following: Instead of rolling stamina dice, you deal an extra 6 points of damage. Augment: for each extra stamina spent, you deal an additional 6 points of damage.

Also, I would drop the skirmish and keep this maneuver in Shadow only and also keep the "no healing on next turn" condition.

**Comment by itamarcu** [comment]
Sure, I like that. Would also make the damage clearer, even though a bit less tied to the one die everyone uses.

Then I'll attempt a new revision:

> **Assassinate** (1 stamina, shadow+skirmish)
> As a bonus action when you attack a surprised or incapacitated creature you can capitalize on its unawareness. If you hit, you deal 6 additional damage, and the creature cannot regain hit points until the start of your next turn.
> *Enhance*
> You can expend additional stamina dice to increase the damage by 6 for each die.

I added "or incapacitated" to allow using this even during combat.

I dislike the fact that this deals 6 damage and a normal maneuver for the same cost could potentially deal more damage if you roll well. I also dislike the fact that, if you're hoping for a critical hit, this maneuver is actually significantly weaker than using something like Ambush (because our expected damage is 6 per stamina and not 9 per stamina).

I don't have a suggestion for something much better, though.

**Comment by Paulorpribeiro** [comment]
I chose 6 so we could reduce the damage by ~25%. It will be of course worse than a crit to balance the fact that it will be better on average (the average of most maneuvers is 4.5 per stamina). It could also be **potentially worse** (other maneuvers could cause more damage) to balance the fact that it is **often better** (higher average damage). I think it is a very solid maneuver

**Comment by mlenser** [comment]
I think we should find a better solution than a flat damage. Some options:

- Roll the stamina die twice, taking the higher result
- Stamina die, reroll 1s and 2s

I considered rerolling weapon dice, but maneuvers are used after, so probably not a good idea.

**Comment by mlenser** [comment]
We discussed on DIscord and this needs to prevent crit fishing. All other maneuvers currently do.

**Comment by itamarcu** [comment]
After further discussions in Discord, here is a new suggestion:

> **Assassinate**, 1 stamina, shadow/skirmish
> As a bonus action, you can capitalize on the unawareness of a creature that is surprised or incapacitated. Until the end of your turn, whenever you hit the creature with a finesse weapon attack, you can use 1d10 instead of your weapon's damage dice.
> *Enhance*
> You add the stamina die to the damage roll of the first attack you hit, for each additional stamina die expended.

**Explanation**
- Increasing the weapon's damage dice fits the theme of making an attack as strong as you can, because of the target being so unaware that no matter what weapon you're using you're able to hit the most vulnerable areas
- By increasing the damage dice to a set number, this maneuver is the most effective when using daggers. This was a sub-goal of this maneuver's design. Assassins use daggers because they are the most maneuverable weapon when you're in close quarters, so you can strike the vital spots of a person easily, and multiple times in quick succession.
- This maneuver is limited to finesse weapon attacks. The intention is to make it work for daggers, shortswords, their similarly-named reskins, and some unarmed attacks (as unarmed assassination is thematic and common) - but not weapons like a sling or an axe. This also improves whips, which is unintentional, but it's okay because they aren't light weapons so they're less useful. Still, an alternative restriction would be "piercing damage weapons or unarmed attacks" (also helps crossbows!). Or, you could also remove this restriction completely, if you think everyone should be able to do it.
- Additional enhancements add damage to the first attack out of simplicity. In a perfect world, I'd like them to increase the weapon's damage die to 1d14, 1d18, 1d22, 1d26 :P
- This maneuver is used before you attack (like Ambush, Lunge, etc) which means it's a bit riskier but also it has the chance of being used before a crit. Indeed, it's written in a way that improves your critical hit damage, functionally doubling the damage of the maneuver (just like the other similar maneuvers). This is intentional, because surprise-critting an enemy is exactly what you try to do when you assassinate them.
- This maneuver's effect can be easily tweaked with. Instead of setting the damage die to 1d10, you could nerf it to 1d8, buff it to 1d12, or make even more minute changes, such as making it 2d4 damage.

When calculating the effect of this maneuver, I will assume the almost best case: a 5th level rogue with extra attack that dual-wields daggers is using it during the first turn against a surprised enemy. 

The damage gain from increasing 1d4 to 1d10 is +3 per attack, on average, or +6 on critical hits. Assuming the rogue makes three normal attacks with the standard 64% chance to hit, the expected damage of this is 64%×9 = 5.76, which is very close to the stamina die goal. When considering 5% crit chance, you could say this adds another 5%×9 which is 0.45 damage, reasonable.

For each of these attacks that the rogue has advantage on (usually only the first one, because hiding), the chance to hit increases to 87% and critical chance increases to 9%, so I'll do some sketchy math and say that this increases damage by another (23%+4%)×3 = 0.81 - that's fine, and is similar to how much having advantage increases the damage of the Lunge maneuver, for example.

It should be noted - I made these calculations assuming a dagger (1d4 damage), but unless you're planning to assassinate people specifically when they're within dagger throw range (10 or 15 feet away from you), you actually have no reason not to use shortswords, instead, as those are the standard dual-wielding weapon and they're better in every way except for the short-range throws. In that case, the damage is +2 per attack, which is 66% of my calculations above, and is only about +4.5 damage in total if you're making three attacks one of which has advantage.

There are two situations in which this maneuver is potentially overpowered:
1. When used by a fighter who uses action surge 
2. When used before melee-attacking a paralyzed target (e.g. one under a Hold Person).

Some other maneuvers are already strong in these situations (for 1, see Precision and enhanced Feint/Distract; for 2, see Ambush). For example, the Ambush maneuver (ignoring its stealth benefit) will deal 2d8 (9) per die, against a paralyzed target (multiplied by 87% chance to hit, so 7.83). Therefore, I think it's alright for this maneuver to increase triple-shortsword-attack base damage from 6d6 to 6d10, for a total of +10.44 to expected damage. It'll be the highest you can do, but it is restricted to a very specific situation (melee attack against incapacitated target), and in that situation a 5th level rogue will already deal an expected attack+sneak-attack value of (3d6+2d6)×2+4 = 39 damage, without a maneuver.

**Comment by mlenser** [comment]
The value would vary based on the weapon used. Some it would be three times as strong than on other weapons.

We shouldn't be manipulating weapon dice.

**Comment by itamarcu** [comment]
> The value would vary based on the weapon used. Some it would be three times as strong than on other weapons.

That's exactly the point! This maneuver is meant for you to use with small weapons (daggers, shortswords, fists?) and balanced around that. Assassinating someone with knives is much more thematic and reasonable than assassinating someone with a greataxe.

This is meant to be a maneuver like Brace, Tear Tendon, and Fan of Blades - limited to assassination weapons. If you prefer, it could say that directly - it's just a lot. I wrote "finesse weapons", it could be change to "piercing damage weapons", but actually now that I'm considering it again a great restriction would be "light weapons". This would make it clear that this is best used with dual wielding. It would also enable hammers, hatchets, and clubs - which are crude but somewhat popular assassination weapons (I hope I don't need to post references as to why).

**Comment by itamarcu** [comment]
I could rewrite it to specifically refer to just a few weapons, and use the 2d4 idea, for a more elegant:

> **Assassinate**, *1 stamina maneuver, shadow+skirmish*
> As a bonus action, you can capitalize on the unawareness of a creature that is surprised or incapacitated. Until the end of your turn, whenever you hit the creature with a club, dagger, katar, sai, sickle, shuriken, or dart, you can use 2d4 instead of 1d4 for your weapon's damage die.
> *Enhance*
> You can increase the weapon's damage dice by another 1d4 for each additional stamina die expended.

**Comment by mlenser** [comment]
Why can't I assassinate someone with a Greatsword? Sneak Attack works with a Greatsword.

It feels like you're tying to "fix" weapons via this maneuver. I think this should focus on the flavor, not on "fixing" certain weapons.

As discussed on discord:
> Maneuver should not manipulate weapon dice except through rerolls

**Comment by itamarcu** [comment]
I'm not focused on fixing - this is an ability that's meant to be used once or less every combat, not a feat. 

You could replace "use 2d4 instead of 1d4" with "add 1d4 to the damage", like I mentioned, and then it wouldn't manipulate the weapon dice (I won't discuss the actual limitation, though I disagree with it).

I already explained the flavor of this - hitting someone in a vulnerable area is much easier with a small and fast weapon. This is just like the Brace maneuver ("pike, spear, trident, rapier, or similar weapon"), Tear Tendon maneuver ("a natural weapon that deals piercing or slashing damage"), or Fan of Blades maneuver ("dagger"). It's thematic to weapons that would be used by assassins.

**Comment by mlenser** [comment]
> hitting someone in a vulnerable area is much easier with a small and fast weapon.

Sneak attack is this, but also allows a greatsword.

Maneuvers could be restricted to light weapons, like Slice Tendon and Bloodletting Blade are, but those are flavored to do so. This is just "you murder an incapacitated creature"

**Comment by itamarcu** [comment]
Would this make more sense if we remove the weapon restriction completely, then?

> **Assassinate**, *1 stamina maneuver, shadow+skirmish*
> As a bonus action, you can capitalize on the unawareness of a creature that is surprised or incapacitated. Until the end of your turn, whenever you hit the creature with a weapon attack, you deal an additional 1d4 damage.
> *Enhance*
> You can increase the damage by another 1d4 for each additional stamina die expended.

**Comment by mlenser** [comment]
Assassinate should be one attack. It's not a stance. This is just a self-buff of Battle Leader  that lasts 1 turn and lacks the Assassinate flavor.

Also on stances: Giving a bonus to all attacks should be very rare (outside of small buffs like dodging, taking aim). I only have it on Blood in the Water right now.

Rerolling 1s and 2s or rerolling dice gives what the maneuver originally desired. It would just be a matter of stopping crit-fishing somehow.

**Comment by Marcloure** [comment]
Assassination is often all or nothing. If we make the character use the maneuver before they know if it's a hit isn't good?

**Comment by itamarcu** [comment]
Alright, then I'll drop this idea and try a different direction.

> Rerolling 1s and 2s or rerolling dice gives what the maneuver originally desired. It would just be a matter of stopping crit-fishing somehow.

This is further problematic - it's too similar to what Savage Attacker gives you (just restricted to a very particular occasion), and it's *worse* for smaller weapons (which are the actual assassination weapons).

**Comment by Marcloure** [comment]
I know taking 8 instead of rolling was suggested but was too powerful, but what about taking 8 but declaring the maneuver before the attack? Was it considered?

**Comment by itamarcu** [comment]
How about...

> **Assassinate** *(1 stamina maneuver, shadow+skirmish)*
> As a bonus action when you make an attack against a surprised or incapacitated creature you can capitalize on its unawareness. If you hit, roll the stamina die twice, and add the higher of the two results to the attack's damage.
> *Enhance*
> You can expend additional stamina dice to increase the damage. For each die, roll it twice and add the higher result to the attack's damage.

**Comment by mlenser** [comment]
Skirmish is not about killing. This is a Shadow maneuver.

Advantage on the d8 is 5.81 instead of 4.5 and is a big weak: 
![image](https://user-images.githubusercontent.com/235857/82547957-d4562a00-9b5a-11ea-8d87-0aea8dca672a.png)

**Comment by mlenser** [comment]
Per our discord convo:
A maneuver that is only used to give a big boost on a surprise round is problematic to start with. Surprise rounds are already super deadly. A creature could end up doing two rounds before the other side does one. I don't think those should be enhanced any further than normal maneuvers/spells.

Additionally, conditions already cover their vulnerabilities. Most are far worse than the tame incapacitated. Those conditions already cover that niche.

**Comment by itamarcu** [comment]
So we're closing this?

**Comment by mlenser** [comment]
This maneuver shouldn't be restricted to surprise and definitely not incapacitated, but there could be something here.

Rerolling the stamina dice is a nice benefit, though not sure it fully matches the flavor. It's realiable.

**Comment by itamarcu** [comment]
Could it be restricted to when you have advantage (like ambush)?

**Comment by itamarcu** [comment]
Revision 11:

> **Assassinate** *(1 stamina maneuver, shadow)*
> As a bonus action when you make an attack against a creature, if you have advantage on the attack or if the creature is below half its maximum hit points, you can capitalize on its unawareness. If you hit, roll the stamina die twice, and add the higher of the two results to the attack's damage.
> *Enhance*
> You can expend additional stamina dice to increase the damage. For each die, roll it twice and add the higher result to the attack's damage.

As for calculation - this seems to be balanced, from what I can tell, under the assumption that you will almost use this on an attack with advantage (I multiplied the expected value by 0.9 because of the advantage restriction and because you might sometimes use this on a bloodied enemy instead. might be wrong in how I calculated this).

![image](https://user-images.githubusercontent.com/6516621/82730695-63557480-9d0a-11ea-917d-b62273de9a18.png)

**Comment by mlenser** [comment]
It doesn't give you advantage so its actually

![image](https://user-images.githubusercontent.com/235857/82746393-6e9eb380-9d8f-11ea-8175-f2d06646ea2a.png)

I think rerolling the stamina dice is intersting, but probably doesn't fit for Assassinate.

We've struggled with this maneuver's identity and mechanics for a bit. I think it'd be best to start fresh with it or other maneuvers.
