### ISSUE TITLE
Elemental Aura spell

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#227]
Unknowingly of each other, two players from my two tables suggested the same thing: a spell that deals elemental damage around you. I think they were specially interested in one for Storm, Fire, and Ice (that also slows) as an addition for gishes.

Problem: it would overlap a bit with the Bloodrager's aura. Do you think it has value? I can write it if you think so.

**Comment by mlenser** [comment]
So like https://www.kryxrpg.com/themes/spells/holy-nimbus, but elemental? If there is flavor, sure. The Bloodrager will be fine.

**Comment by Marcloure** [comment]
Yes, something like that, but with the flavor effects from the elements.

**Comment by Paulorpribeiro** [comment]
Once I suggested it and it was said that it is too similar to the "rebuke like" spells (fiery rebuke vs a spell similar to RAW fire shield at the time) is it still the case?

**Comment by mlenser** [comment]
That's the case for a spell like Fire Shield, but a persistent sphere that emanates from the caster would be different.

**Comment by mlenser** [comment]
Closing this. A new issue can be opened to implement the idea.
