### ISSUE TITLE
(Minstrel) Performance - Precognitive Overture 

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#229]
**Precognitive Overture**
_Prerequisites: Divination theme_
As a reaction when you roll initiative and are not surprised, you play an overture that instils allies with a flash of precognitive warning. All other allies within 30 feet can use their reaction to move up to half their speed.

**Comment by mlenser** [comment]
I'm not seeing the flavor for music that lets you see the future. Never seen that in any story.

This needs a different word than Precognitive, imo.

**Comment by itamarcu** [comment]
I think you can reflavor it to:

> Rousing Overture
> Prerequisites: Sound theme
> As a reaction when you roll initiative and are not surprised, you play an overture that rouses allies, stirring them into action. All other allies within 30 feet can use their reaction to move up to half their speed.
