### ISSUE TITLE
Fortunes of Fate typo

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#230]
Partway through The Devil and onward, some of the list items aren't rendering properly:
![image](https://user-images.githubusercontent.com/3477032/82106719-b7e86680-96f0-11ea-9a37-c62eb4697637.png)

**Comment by Marcloure** [comment]
"Partway through The Devil" is my favorite band

**Comment by mlenser** [comment]
fixed
