### ISSUE TITLE
Solicit Mindcrystal should refer to Meld Mindcrystal

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#231]
https://www.kryxrpg.com/themes/spells/solicit-mindcrystal

It should say something like "your mindcrystal from  the _mend mindcrystal_ spell [...]", otherwise it has no reference and can be quite confusing (I for instance didn't know such spell existed, so I was kinda lost in its description).

**Comment by mlenser** [comment]
Solicit Mindcrystal links to Meld Mindcrystal now

**Comment by Marcloure** [comment]
This push doesn't seem to have applied. Solicit Mindcrystal is the same as before

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/82129363-64dee400-97c2-11ea-82a7-f457129a05a0.png)
its a link

**Comment by Marcloure** [comment]
Oh, I see
