### ISSUE TITLE
Schism should be more clear

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#232]
https://www.kryxrpg.com/themes/spells/schism

The spell isn't clear that the second mind can cast spells up to 1 mana, I could understand that clearly only by reading its augment. I suggest changing:

> It can cast spells, expending 1 mana per spell. The mana is removed from your mana.

to something like:

"It can cast spells up to 1 mana limit. The mana is removed from your mana."

**Comment by Marcloure** [comment]
Or use similar text to Personality Parasite:

> The parasitic personality casts spells as if it were the target, but can only expend 1 mana when it casts spells.

**Comment by mlenser** [comment]
`It can cast spells and has a mana limit of 1. The mana is removed from your mana`
