### ISSUE TITLE
Psychic Crush is just better than Brain Lock

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#233]
Both spells stun a target, but Psychic Crush also deals damage and has 120 feet of range. Not sure how the spreadsheet can consider both balanced, but it lists Psychic Crush as a 60 feet range spell (which is different from the spell on the site).

**Comment by Marcloure** [comment]
I think one of them should be removed, there is no need for 2 almost identical spells, even if they were somehow balanced against each other.

**Comment by mlenser** [comment]
Brain Lock removed as Psychic Crush fills the same niche better
