### ISSUE TITLE
Spirit Spell - Phantom Impressions

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#235]
**Phantom Impressions** (2 mana, Spirit) 
_concentration, 1 hour/mana_
As you spend 1 minute to cast this spell, you conjure ghostly historical impressions of a given location within 60 feet or object you touch.

Location. Rooms, streets, tunnels, and other discrete locations accumulate impressions left by powerful emotions experienced in a given area. These impressions offer you a ghostly recreation of the location’s past.

The types of events most likely to leave impressions are those that elicited strong emotions: battles and betrayals, marriages and murders, births and great pain, or any other event where one emotion dominates. Everyday occurrences leave no residue for a caster to detect.

The conjured phantoms of the event are mist-like and ghostly, and cannot be interacted with. You do not gain special knowledge of those involved in the vision, though you might be able to read large banners or other writing if they are in your language.

Beginning with the most recent significant event at a location and working backward in time, you can conjure one distinct event for every 10 minutes you maintain concentration, if any such events exist to be created.

Object. You create mist-like and ghostly echoes which let you learn about the past owners of an object. You learn the owner’s race, gender, age, and how the owner gained and lost the object. Beginning with the most recent owner of an object and working backward in time, you can conjure one distinct owner for every 10 minutes you maintain concentration, if any such owner exists to be created.

Track. You can track creatures with an Intelligence score of 3 or greater by following the ghostly trails of spritual energy they leave behind. You have advantage on Nature checks made to track such creatures.

The impressions can extend 100 years into the past.

Augment
You can augment this spell with the following options, expending mana for each option.
The impressions can be 500 years further in the past for each additional mana expended.

**Comment by mlenser** [comment]
Spiritual Impressions added to the Spirit theme

adjusted it a bit from abovce, but 95% the same.
