### ISSUE TITLE
Spells with augments to target more creatures should limit damage augments

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#236]
Psychic Crush for example

**Comment by Marcloure** [comment]
Maybe we are better off removing these augments, since AOE spells exist to fulfill this purpose. For example, Mind Blast is an AoE spell that does the same of Psychic Crush but in area: damage and stun, so there is an overlap of purpose here.

**Comment by mlenser** [comment]
There are 68 of them. Aid has several for example:

![image](https://user-images.githubusercontent.com/235857/82122805-03088500-9796-11ea-9e44-f6d17d972210.png)

I think its best if we can find a way to keep most around. Half damage on augments should be ok for most cases, I think. I'll check.

**Comment by itamarcu** [comment]
A bit off-topic, but - Aid should probably target two additional creatures for each additional mana (or even 3 additional). At least, mathematically, it seems so.

Also, "the target's" should be "the targets'".

I'm guessing these are changes leftover from the 10 mana system.

**Comment by mlenser** [comment]
Spells with augments to target more creatures have their damage augments halved if they target more creatures
