### ISSUE TITLE
Hyperlinks on mobile are hard to see

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#237]
It seems hyperlinks are not colored on mobile. Or at least, not enough to spot them. They can't turn bright red on mouse hover, so they should be naturally brighter I think.

Well, I hope the issue is not my phone's screen, or my eye.

![Screenshot_20200516-172750](https://user-images.githubusercontent.com/29084710/82129675-d99e2800-979a-11ea-9eeb-8ebf0b9ea7ba.png)

![Screenshot_20200516-172916](https://user-images.githubusercontent.com/29084710/82129676-dacf5500-979a-11ea-8713-216a9bc06008.png)

**Comment by Marcloure** [comment]
Ok, after much staring I can see they are indeed redish, but they don't contrast enough with the rest of the text

**Comment by mlenser** [comment]
And here we can see why color is not a strong enough differentiator.

**Comment by mlenser** [comment]
More accessible:
![image](https://user-images.githubusercontent.com/235857/82139251-d6507e00-9826-11ea-93bf-1a57520089c0.png)

**Comment by itamarcu** [comment]
I'm also in favor of turning the links slightly brighter when you're not hovering above them.

**Comment by mlenser** [comment]
Underline is accessible. Color is vary reasons:
- Poor contrast monitors/night mode
- Color Blindness
- Too subtle

**Comment by Marcloure** [comment]
I don't like the current spell's titles underline, the page feels too heavy to the eye. I'm not sure what you can do there, can you make the line thinner for them?

**Comment by mlenser** [comment]
Unfortunately, underline cannot be changed in a way that is supported by browsers, especially chrome.

**Comment by mlenser** [comment]
One thing I can play around with is the color:

![image](https://user-images.githubusercontent.com/235857/82148033-2c86e680-9852-11ea-86e7-fd849ada068b.png)
![image](https://user-images.githubusercontent.com/235857/82148052-4de7d280-9852-11ea-8dc7-f43c03983465.png)



```
text-decoration-color: #cb3a248f;
```

**Comment by Marcloure** [comment]
Yeah, that is better

**Comment by mlenser** [comment]
Ok, I've removed the underlines from headings and adjusted the underline color so it should be better now:

![image](https://user-images.githubusercontent.com/235857/82149056-5d691a80-9856-11ea-9a3b-b46738046941.png)
