### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#238]
Because there is always that person who hates white pixels on their screen.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/82142324-c42d0a80-983b-11ea-9d2d-0cabb1f51711.png)
getting close..

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/82146707-740a7400-984c-11ea-9c9f-547583370b34.png)
![image](https://user-images.githubusercontent.com/235857/82146716-7e2c7280-984c-11ea-842f-362f6f27185a.png)
![image](https://user-images.githubusercontent.com/235857/82146724-8b496180-984c-11ea-8d4f-d92dbcf3b5a6.png)

**Comment by mlenser** [comment]
It should default to whatever the phone prefers, but I haven't tested that.
