### ISSUE TITLE
Augment for spirit drain

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#239]
That was what i thought when I read the spirit DRAIN spelltitle, but maybe it is more suited as an augment.

Augment: You can spend an additional mana so that you retain some the energy drained from the target. You can augment the next spell you cast until the end of your next turn by one mana without spending that resource. Your mana limit also increases by one for this cast of the spell.

**Comment by mlenser** [comment]
Spirit Drain is already a stronger version of mana burn. I'm not sure..

**Comment by mlenser** [comment]
> You can expend 1 additional mana to retain some the energy drained from the target. You can augment the next spell you cast before the end of your next turn by 1 mana without expending mana.

No mana limit increase.

**Comment by mlenser** [comment]
Spirit Drain can now be augmented to reuse some of the drained energy

**Comment by itamarcu** [comment]
Wait, you added...

> You can expend 1 additional mana to retain some the energy drained from the target. You can augment the next spell you cast before the end of your next turn by 1 mana without expending mana.

So now you gain the power to.....spend one mana immediately....to regain this mana on your next turn?

...What exactly is the benefit of this? 🤔

**Comment by itamarcu** [comment]
I think to make it worthwhile you could do...

> You can augment the next spell you cast before the end of your next turn by 2 mana without expending mana.

or:

> You can augment the next two spells you cast during the next minute by 1 mana without spending mana.

or:

> You regain an amount of mana equal to the amount lost by the creature, plus one.

**Comment by mlenser** [comment]
> You can augment the next spell you cast before the end of your next turn by 2 mana without expending mana.
> You regain an amount of mana equal to the amount lost by the creature, plus one.

These don't work as you only drain 1 mana.

> You can augment the next two spells you cast during the next minute by 1 mana without spending mana.

This is too complex.

_________________

I'll revert this. There is no point to this augment.

**Comment by Paulorpribeiro** [comment]
I'd rather we make this augment the right power level instead of dropping it. I can see atimagic having a mana burn spell, but spirit? This spell should be more than mana (or resource) burn. Well it could be more. I had the idea yesterday when I saw the world of warcraft movie, where guldan drain a poor slave and plays with the fell (which is sort of a corrupted mana, for tbose unfamiliar) it drained in his hand.

**Comment by Paulorpribeiro** [comment]
I'm also ok with creating a whole new spell, but I think the augment idea can work

**Comment by mlenser** [comment]
Sure, feel free to refine it. Some thematic/system requirements:
- no mana limit increase
- if a spell is very similar to another spell, they should be 1 spell
- you can't gain more mana than the mana you drained

**Comment by Paulorpribeiro** [comment]
My train of thought is, if you spend 2 mana and gain 1 mana back (actually, not even that, because the mana has to be used in your next turn, in the original) it's a null augment. You spend 1 mana to augment a spell to have that mana back, **for a brief moment** and **if you hit**.
That s is why I thought about increasing the mana limit while the spell is "active"

**Comment by Paulorpribeiro** [comment]
My train of thought is, if you spend 2 mana and gain 1 mana back (actually, not even that, because the mana has to be used in your next turn, in the original) it's a null augment. You spend 1 mana to augment a spell to have that mana back, **for a brief moment** and **if you hit**.
That s is why I thought about increasing the mana limit while the spell is "active"

**Comment by mlenser** [comment]
> no mana limit increase

This is important for balance.

**Comment by Paulorpribeiro** [comment]
Version 2

Spirit Drain
"Augment: you can spend 1 additional mana to retain some of the power you drain. The next spell you cast until the end of your next turn, instead of rolling the damage, all dice are maxed against all targets affected."

**Comment by mlenser** [comment]
That flavor doesn't really match the name.

https://wowwiki.fandom.com/wiki/Drain_Mana ahs similar power to what I think you're after. In that case its a simple mana transfer with no damage.

**Comment by Paulorpribeiro** [comment]
That's what I'm avoiding actually. What I want is for the drain spirit to buff the spelcaster's next spell. 
1st try is to buff it by augmenting it for free, but since expanding the limit is not possible (I agree with that) and simply augmenting it within the mana limit is null.
2nd try was to buff it by maximizing the damage, but I also agree it is not the best idea. 

It was never about giving the caster mana back, its about boosting the caster after he drains. I'm open to more ideas if someone else wanna pitch in.
