### ISSUE TITLE
Sacred/Profane Shield augment suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#240]
One of players suggested two augments for Sacred/Profane Shield:

• You can expend 1 additional mana to target an ally you touch / 30 feet.
• You can expend 2 additional mana to cast the spell as a reaction when you take damage. The spell's effect includes the triggering damage.

**Comment by mlenser** [comment]
I'll give both the same wording as Shield of Faith:

> You can target one additional creature for each additional mana expended, though the spell then must be cast as an action. The creatures must be within 30 feet of each other when you target them.

The reaction can cost 1 mana, Uncanny Dodge is a maneuver and costs 2 stamina total.

**Comment by Marcloure** [comment]
> The reaction can cost 1 mana, Uncanny Dodge is a maneuver and costs 2 stamina total.

Sacred/Profane Shield lasts for a whole round and deals area damage, while Uncanny Dodge is against the triggering attack and don't deal damage.

**Comment by Marcloure** [comment]
Hm, sorry, I misread. It would be 2 mana total for a reaction Sacred/Profane Shield against 2 stamina for Uncanny Dodge. If 1 mana makes the longer duration and AOE damage ok, then it's fine.

**Comment by mlenser** [comment]
I don't understand.

![image](https://user-images.githubusercontent.com/235857/82147166-327ac880-984e-11ea-8f5e-d6442790507f.png)

Is there something wrong, or did you misunderstand earlier?
