### ISSUE TITLE
Add thematic beasts to Call Steed

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#241]
I would remove the pegasus, since it's a celestial, and maybe the griffon and peryton (monstrosities), and add a few other beasts usually used as mounts to the spell:

• Giant Eagle
• Giant Lizard
• Giant Spider

They would all be part of the augmented set of beasts

**Comment by Marcloure** [comment]
Maybe Giant Spider could also be added to Find Steed, because of drows?

**Comment by mlenser** [comment]
Do you mean Call Steed?

**Comment by mlenser** [comment]
Call Steed options have been changed to more bestial options

**Comment by Marcloure** [comment]
Yeah, I meant Call Steed. Sorry
