### ISSUE TITLE
Hallow augment has no use

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#242]
First augment:

> You can expend 1 additional mana to affect all celestials, elementals, fey, fiends, and undead.

But the spell says: 

> Choose one **or more** of the following types of creatures: celestials, elementals, fey, fiends, or undead. 

I believe the bold part should be removed for the augment to make sense.

**Comment by mlenser** [comment]
Hallow wording fixed to only choose 1 creture type at 2 mana
