### ISSUE TITLE
Knife Adept (or some other dagger-related feat name)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#243]
Feat suggestion! (name is temporary until we can think of a better name)

> **Knife Adept**, 4th level feat (Shadow, Skirmish)
> When you roll a 1 on a damage die for an attack made with a dagger, katar, sai, or shuriken, you can reroll the die and must use the new roll, even if the new roll is a 1.

The point is to have a feat similar to Savage attacker, Cleave, Polearm Master, Two-Weapon Fighting, etc - that rewards people for using daggers. It especially rewards rogues, because it also lets them increase their sneak attack damage. It also combos well with maneuvers such as Fan of Blades that let you make many attacks in one turn.

An alternative suggestion, which could also be neat in my opinion, is:

> **Knife Adept**, 4th level feat (Shadow, Skirmish)
> When you roll damage for an attack made with a dagger, katar, sai, or shuriken, you can take a result of 4 for your weapon's damage die, instead of rolling.

The goal is to have dual wielding daggers be a balanced options, as powerful as using a rapier or dual-wielding shortswords. I don't think the ability to throw daggers is strong enough to warrant -1 to all of your damage rolls, as the range is pitiful and if you're that close to an enemy you're likely to have disadvantage for being next to an enemy. Still, I'm alright with limiting this feat to only work on melee dagger attacks.

I would be open to other suggestions - a feat that only increases dagger damage is a bit boring. I'd like a feat that lets you attack more times, because I like the idea of daggers being the fastest but weakest weapon, but it's really hard to add even one more attack per turn without making this too powerful or breaking consistency of other rules.

Other thematic dagger buffs could be improving critical hits or critical hit chance.

Allowing critical hits on a 19, while holding a dagger, feels good to me, as it increases expected damage by a good amount, but I'll need to calculate to be sure

**Comment by Paulorpribeiro** [comment]
I'm not sure about expected damage, but the crit chance goes way up. 19-20 crit is 10% chance, ~19% with advantage and ~27% with double advantage. It is way high, and it will be very dangerous with sneak attack or any maneuvers.

**Comment by mlenser** [comment]
> I'm not sure about expected damage, but the crit chance goes way up. 19-20 crit is 10% chance, ~19% with advantage and ~27% with double advantage. It is way high, and it will be very dangerous with sneak attack or any maneuvers.

Indeed, there is a reason that such an option is almost unseen in 5e, only appearing on one subclass.

What build needs a dagger feat to compete? The rogue is totally within the expected limits with daggers as they currently are.

**Comment by Paulorpribeiro** [comment]
Well, dual dagger is obviously not as good as dual rapier. I understand not every weapon will be as good. If I understand correctly, double rapier with two weapon fighting style and feat is the build used for DPR comparison for "meele rogue". Im ok with that, and not all combinations of weapons is supposed to be "DPR equivalent", but dual dagger rogue is a classic
 Can we have some love for the daggers?

**Comment by mlenser** [comment]
Rapiers are not light. I assume you mean Shortswords. In that case daggers have very marginally less DPR as they have ranged.

Daggers have love. They are a great option. The DPR difference is very minor.

**Comment by Paulorpribeiro** [comment]
Yes, short sword, sorry. Well, I still think it could get some love, perhaps the assassinate maneuver could see a boost if used with daggers.

**Comment by mlenser** [comment]
What about it needs love? Is dagger a subpar option? If you boost a dagger then shortswords are not a competetive option.

Daggers are great and fun and balanced as far as I can see. One weapon can't be buffed in isolation - every comparable option would also need changes.

**Comment by Paulorpribeiro** [comment]
What I said, the assassinate maneuver could favor daggers. That way they have lower DPR in general, but have higher DPR if used with that maneuver. Perhaps we should finish the basis of the maneuver 1st. And put this on hold

**Comment by mlenser** [comment]
If you give an option a better maneuver then you're giving that option more DPR as DPR is based on maneuvers.

There is no love to give for daggers specifically without upsetting the balance with other options.

**Comment by itamarcu** [comment]
I do believe melee daggers need some love.

In comparison to shortswords, they deal 1 damage less per hit, which means 3 damage less (after 5th level) per turn - plus 1 less on opportunity attacks. Yes, you could throw them if you'd like, but their range is quite short (unless you like disadvantage) and you could just as well throw daggers if you're dual-wielding swords and your opponent is suddenly unavailable at melee.

Rogues, and especially assassins and criminals, tend to use one or two daggers as their weapon of choice. Throwing daggers, while cool and useful, is not what makes dagger fighters unique, IMO. It should be the fact that they attack very often, attack at very close range, aim for the most vulnerable areas in their opponents' bodies, and prioritize offense over defense (or over staying away from the enemy's reach).

They should get feats and maneuvers that work for that purpose - while still keeping to the damage guidelines for other weapons.

**Comment by mlenser** [comment]
The DPR of a rogue is already balanced between all the options:

![image](https://user-images.githubusercontent.com/235857/82327871-5883a280-99df-11ea-9db5-6e8b25f1ba6e.png)

> There is no love to give for daggers specifically without upsetting the balance with other options.

I'[m going to close this as we're just going in circles now.

**Comment by itamarcu** [comment]
You didn't respond to any of my points :/

I'm specifically discussing melee daggers, which is none of the options here.

In addition, "Rogue Thrown Dagger" is based on this pair of (non-formula) numbers:

![image](https://user-images.githubusercontent.com/6516621/82328608-cbdde200-99e8-11ea-835b-dec73313173f.png)

And I don't think that the chances of sneak-attacking with a 15 ft thrown weapon attack are three times as high as the chances of sneak-attacking with a melee weapon attack.

(also, sidenote: there's a comment there that says "Sneak attack also includes the rules that are normally under Swashbuckler in RAW 5e", but it seems wrong - the swashbuckler's ability (sneak attack when basically dueling an enemy) is not mentioned in the Sneak Attack feature description)

**Comment by Marcloure** [comment]
> (also, sidenote: there's a comment there that says "Sneak attack also includes the rules that are normally under Swashbuckler in RAW 5e", but it seems wrong - the swashbuckler's ability (sneak attack when basically dueling an enemy) is not mentioned in the Sneak Attack feature description)

This used to be in the standard rogue, but was removed as we now have a lot of maneuvers that can grant advantage to the rogue.

**Comment by mlenser** [comment]
All balance changes must be data driven. So far what has been discussed is opinions. I've shown numbers how the current balance is pretty ok overall.

Steps to change balance:
1. Identify a balance problem. Find an issue somewhere in the spreadsheet or duplicate the spreadsheet and create a sample case that I haven't covered.
2. (Optional) suggest a solution and map out how that changes the identified issue.

Without data its just opinions and such feedback around the balance area has negative value to building a good system.

Please feel free to open a new issue around balance where data is the key factor.
