### ISSUE TITLE
Balance Spear & Trident

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#246]
In 5e RAW, both Spears and Tridents are d6 weapons with versatile and thrown. Tridents, however are martial, and more expensive.

In Kryx RPG, Tridents have been buffed, so they now deal 1d8 (1d10 with two hands).

I think that spears shouldn't be weaker than tridents - if you look around the web for arguments about this you'll see some good explanations (along with people disappointed about tridents being slightly worse).

__My suggestion:__

Add "war spear" weapon (or "long spear"), that is identical to current trident, being like a spear that deals more damage and requires martial proficiency.

__My second and not directly related suggestion:__

Reduce thrown range of trident and the new war spear from 30/60 to 15/30. This gives at least one reason to choose to use normal spears instead of tridents or these new spears, and stops tridents from being the ultimate thrown weapon (which was quite weird).

**Comment by mlenser** [comment]
Pathfinder 2e Trident does 1d8, so I'll keep that.

I'm not sure a longspear really has much room in 5e. It uses two hands in:
- 3.5: https://forgottenrealms.fandom.com/wiki/Longspear
- PF: https://www.d20pfsrd.com/equipment/weapons/weapon-descriptions/longspear/
- PF2e: https://2e.aonprd.com/Weapons.aspx?ID=6

So really it'd just be a worse trident and a worse spear.

**Comment by itamarcu** [comment]
You could call it "war spear", or you could just call it "spear" and rename the old one "short spear".

**Comment by mlenser** [comment]
I got through page 3 on Google and couldn't find a consistent way to handle Longspear. It seems either a Spear or a Pike with little room inbetween. Some tried to create what is effectively the lance: Martial 1d8 two handed. But we have that so no need.

I timeboxed a solution here and couldn't find a way for this to work, thematically. So closing this.
