### ISSUE TITLE
Add haste to Courage

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#247]
It's a suggestion from one my players. He suggested naming it as Induce Frenzy, Fast March, Call to Battle, or something along those lines.

Also, he suggested to add a special augment to make it an aura around self, but that would probably be a  5 mana spell.

**Comment by mlenser** [comment]
During the Minstrel adding Haste as a Performance was suggested and I think it didn't fit. For the Minstrel's case we added a battle song that increases movement which I think is a much better fit.

For Time I see haste as manipualting the whole time spectrum around the person.
For Storm you're literally electrocuting someone to give them adrenaline
For Alteration it could be flavored as a strong burst of adrenaline
For Courage I'm not sure the same flavor is there.

I'm not sure en extended duration buff for increasing speed makes too much sense for Courage. Yes, Courage is bolstering you, but I believe haste is beyond that flavor.

What do you think?

**Comment by Marcloure** [comment]
If at all, it would be as a spell only. But I agree that we can't just add every buff spell to Courage and flavor it as "Just Do It".

**Comment by mlenser** [comment]
I don't think there is enough flavor here, but can reopen if there is something here - let me know.
