### ISSUE TITLE
Elemental Auras implementation

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#248]
**Fire Avatar** (or a better name, maybe simply Fiery Aura)
*concentration, 1 minute/mana*

As an action, you are surrounded by flames in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you.

Whenever an enemy enters the area for the first time on a turn or starts its turn there, it must make a Reflex saving throw.

On a failed save, the creature takes 2d8 fire damage and it has disadvantage on saving throws against spells you cast that deal fire damage.

On a successful save, the creature takes half as much damage.

In addition, for the duration, you have advantage on saving throws against Fire spells.

**Augment**
You can increase the damage by 1d8 for each additional mana expended.

#### Notes
It would be nice to have it causing the burning condition, but I thought burning in a lasting spell might be too much, though incendiary cloud does that.

**Comment by Marcloure** [comment]
**Storm Avatar** (or a better name, maybe Storm Lord?)
*concentration, 1 minute/mana*

As an action, the air around you is electrified in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you.

Whenever an enemy enters the area for the first time on a turn or starts its turn there, it must make a Reflex saving throw.

On a failed save, the creature takes 2d6 lightning damage, loses its reaction until the start of its next turn, and it has disadvantage on saving throws against spells you cast that deal lightning damage.

On a successful save, the creature takes half as much damage.

In addition, for the duration, you have advantage on saving throws against Storm spells.

**Augment**
You can increase the damage by 1d8 for each additional mana expended.

**Comment by Marcloure** [comment]
**Ice Avatar** (or a better name, maybe simply Frost Aura)
*concentration, 1 minute/mana*

As an action, freezing cold surrounds you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you.

Whenever an enemy enters the area for the first time on a turn or starts its turn there, it must make a Fortitude saving throw.

On a failed save, the creature takes 2d4 cold damage, is slowed 1 until the start of its next turn, and it has disadvantage on saving throws against spells you cast that deal cold damage.

On a successful save, the creature takes half as much damage.

In addition, for the duration, you have advantage on saving throws against Ice spells.

**Augment**
You can increase the damage by 2d4 for each additional mana expended.

**Comment by Marcloure** [comment]
I linked the advantage on saving throws to themes, but maybe could be "against spells that deal [element] damage"

**Comment by mlenser** [comment]
> disadvantage on saving throws against spells you cast that deal X

I think this is problematic. I see it in Holy Nimbus, but I don't think it should exist their either.

It's effectively changing saves from a 55% chance failure rate to a 80% failure rate. Half damage on this lessens this a bit, but still..
This is around a 25% damage boost to other spells cast. In general I think a damage boost to other spells is not the best design. I have not accounted for this at all on Holy Nimbus and it would be substantially powerful.

I'd rather see Fire aura cause fire and cause burning in nearby creatures. It should also be Fort, imo.

Storm Aura and Ice aura are both flavorful, though I think the disadvantage part should be dropped.

**Comment by itamarcu** [comment]
I'd rather have the auras be more interesting than simple reskins of each other. My suggestion:

- Fire aura sets things on fire
- Storm area zaps one thing near you every round
- Air aura pushing things away and makes ranged attacks miss (or disadv)
- Ice aura slows everything near you
- Earth aura makes difficult terrain around you, and perhaps grants you half cover from attacks (if it's like a crater that follows you)
- Water aura keeps you heavily obscured and douses fire

etc!

**Comment by Marcloure** [comment]
Just FYI, I'll rework these auras based on feedback. Possibly I'll open a new issue for each, since now I have ideas for 5 or 6 themes

**Comment by Marcloure** [comment]
Closing as I moved auras to individual issues
