### ISSUE TITLE
Question about the burning condition

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#249]
Maybe it was an old iteration of the condition, but I always thought that the burning condition always decreased by one at the end of the creature's turn. If I read it correctly, now it only lowers the burning condition if the target uses the action to extinguish the flames, is that it?

If that is true, I think burning is too powerful. Take immolate for example, you inflict burning 4 to someone. If the target doesn't spend and action he will take 4d6 (the same initial damage of the spell) every turn, until he or an ally spares his action or target burns to death. It is a very debilitating condition (similar to incapacitated for a round, except it can take reactions). I think the burning condition should lower by one every round, or end with a successful save.

**Comment by itamarcu** [comment]
I suggest changing it as follows:
> At the start of each of its turns (or the turn it was ignited for an object), a burning creature or object takes 1d6 fire damage for each burning level**, and then its burning level decreases by 1**.

And changing every spell/concoction/maneuver we have that causes Burning X to cause Burning X+1 instead.

**Comment by mlenser** [comment]
Immolation is supposed to be 3d6 and burning 3, it was wrong on the site.

**Comment by mlenser** [comment]
> I always thought that the burning condition always decreased by one at the end of the creature's turn

That was an earlier design.


Lets compare two spells:

### Immolation
(updated values it was off on the spreadsheet)
2d6(7) or half (3.5) = .514*7 (3.598) + .486*3.5 (1.701) = 5.299
burning is 3d6, but you only burn if you fail the fort so .514*10.5 = 5.397

Total: **10.696** damage from immolation if the creature uses its action

### Corrosive Consumption
(updated values it was off on the spreadsheet)
4d6(14) or half (7) = .514*14 (7.196) + .486*7 (3.402) = 10.598

Total: **10.598** damage from Corrosive Consumption

### Further
Further rounds we have 10.5 automatically vs 10.598 on average.

Each round that fort is used to save the chance of it ending goes up. I calculate that value on the spreadsheet:
![image](https://user-images.githubusercontent.com/235857/82470055-22205300-9ac5-11ea-802c-1c7818dc5a87.png)
Which results in 154%.

Burning I've estimated similarly:
![image](https://user-images.githubusercontent.com/235857/82470303-74617400-9ac5-11ea-9394-ab49c72f07c1.png)
for 196%
The action cost is calculated in (the $K$9). It's reduced by a bit because an ally can help. The end result is reduced a bit as a failed save by 4 or less still reduces the burning level. 1/3 in this case is 66% so 0.7 is a decent estimate.

### Conclusion
I think its probably ok at the current values. I'd need to do more calculation to determine how reducing it by 1 each level would impact it overall.

**Comment by Paulorpribeiro** [comment]
One other thing you didn't consider (and I think it is tricky to calculate the exact value) is that burning can stack. If you start with immolation (burning 3 currently, with no augment), and use a burning 1 spell each round thereafter. The creature is permanently burning unless he uses his action to put out the flames every round.

**Comment by itamarcu** [comment]
I don't think the stacking is important for the spreadsheet - if enemies tend to put themselves out fast (or at all) then stacking is *bad* for the caster, and good for the victims. If the enemies tend to let burning linger, stacking more and more burn on the enemy is still worse than just putting all the burn up front. You'd generally prefer to burn a different creature, instead - this makes it twice as difficult to cancel your effects and means that if one of them helps the other, the one who helped will keep burning themselves.

**Comment by mlenser** [comment]
> burning can stack.

Each burning application is its own value. If Immolation and Scorching Bolts are applied they are evaluated as their own spells.

Them stacking and being ended by one ability check is actually way worse for burning's value. See the comment about for a more detailed description for why.

> If you start with immolation (burning 3 currently, with no augment), and use a burning 1 spell each round thereafter. The creature is permanently burning unless he uses his action to put out the flames every round.

1 action stops the ongoing damage and then it's just whatever is applied the next round. 3.5 damage per turn is pretty minimal. I mean.. Single target spells deal an average of 21 damage. Burning is noit a concern in this regard.

**Comment by Paulorpribeiro** [comment]
It actually looks way better now after the values were adjusted (for immolation). I will playtest it more.

**Comment by mlenser** [comment]
This goes to show how tiny deviations from the goal can lead to a big difference in how good the spell is.

I'll close this for now. Feel free to open a new issue if your playtesting shows it to be too powerful.

**Comment by mlenser** [comment]
Note: the level automatically decreased when the DC was spell DC. The DC is now 10, but against dex do it doesn't scale.

**Comment by Paulorpribeiro** [comment]
I didn't have the chance to playtest, but I was looking at the calculation on the spreadsheet:
- the burning damage calculation looks solid
- the action loss in my opinion is missing. The loss of an action an reaction by an enemy is the cell N143 which is 7.91. The loss of an action is a condition, not a multiplier you add to the burning factor. I know the target looses an action but can still use the reaction, but this condition is not on the spreadsheet (yet), but can be calculated. Of course the target can still choose not to use the action to remove the burning effect, or another creature can use the action, but either way, it is not computed in the value in the spreadsheet.
As I see it, the spreadsheet doesn't account for the action used by the target, just the chance of success.

By my calculations it would be like this: 196% * [hit_chance] + 7.91 (or whatever is the number, I think "can't use action or reaction" the closest)

**Comment by mlenser** [comment]
> the action loss in my opinion is missing.

It's accounted for, I wrote about it above:

![image](https://user-images.githubusercontent.com/235857/82724212-d3490800-9cd4-11ea-8f00-140e6c1e3aab.png)

______________________

The creature can definitely take actions. "can't take actions or reactions" is when a creature is prevented from doing so. Giving up your action to prevent minor persistent damage is totally different.

**Comment by Paulorpribeiro** [comment]
Well, it's not minor if its burning 3+. Even for beefier creature, it will take 10.5 hp without any effort on the part of the caster. If you think about the worst case, a caster could cast a 5 mana inaction that applies burning 15! (OMG, every augment increases it by 3? This can't be right...) If he is fighting a target that does not have fire resistance it is taking 50+ hp per turn unless.he wants to loose his action.

The K9 cell is not the action lost by the target, is the action cost by the caster. Otherwise, why loosing a reaction or a bonus action more severe than loosing an action? The stun for example is a co edition, not a percentage. I can't see why this action potentially lost is not a condition like slow, can't heal or others.

**Comment by Marcloure** [comment]
> If he is fighting a target that does not have fire resistance it is taking 50+ hp per turn unless.he wants to loose his action.

Well, the DC is 25 at this point. Not much to be done unless you have more than 20 Dex.

**Comment by Paulorpribeiro** [comment]
The DC is actually 10+ half burning level, but still. Burning 15 is an exaggeration, it is probably an error, but I can't make the calculations (away from laptop until monday)

**Comment by Marcloure** [comment]
Oh, you're right, it's half the burning level

**Comment by itamarcu** [comment]
When you're burning so much, you're just going to extinguish yourself (or have a friend extinguish you) immediately.

Spending 5 mana to deal 50 damage to a creature and make it lose its action during its next turn isn't overpowered!

**Comment by Paulorpribeiro** [comment]
Extinguish yourself if you can. You might not be able to. If you burn then restrain a creature, it has an o going effect it can't stop. Same if you combo burn+stun or burn+paralyze. In RAW almost all condition/effects allow a save to end at the end of the turn (no cost) to bring down the "save or die/suck" spells, which were a major complain in 3e. I think we should keep that in mind. If you make a combo where you are taking damage each round and can't stop it, it is not so fun.

**Comment by Paulorpribeiro** [comment]
That said, even at 2 mana, immolation causing burn 6 is a little excessive imo (I don't have the numbers right now) and it praticaly

**Comment by mlenser** [comment]
Please open a new issue where you provide an alternative option for burning. It was purposefully made into an action because people said that was more thematic. If you have a better idea, please flesh out the idea and provide some numbers.

**Comment by itamarcu** [comment]
@Paulorpribeiro 
> If you burn then restrain a creature, it has an ongoing effect it can't stop. Same if you combo burn+stun or burn+paralyze. 

Same if you use the popular combo where you create Incendiary Cloud plus Wall of Force, to deal heavy AoE damage to creatures that can't escape it.

I think combos that require two spells (potentially two concentration spells) are allowed to be a bit strong, especially when they only affect a single creature or when they're countered with relatively common spells (teleportation, water to extinguish burning, disintegrate to destroy wall of force, etc).

**Comment by mlenser** [comment]
Some quick comparisons, assuming fire isn't put out:

## 1 mana
- Acid Arrow does ~11.5 damage on the first turn, and ~5.7 on the second turn.
- Blight does ~14.7 damage on the first turn
- Immolation does ~10.6 damage on the first turn, and ~5.3 damage on later turns.

## 2 mana
- Acid Arrow does ~25.8 damage on the first turn, and ~12.9 on the second turn.
- Blight does ~34.3 damage on the first turn
- Immolation does ~26.5 damage on the first turn, and ~10.7 damage on later turns. It takes about 1.5 turns for it to be equivalent to Blight.

Fire is strong, I don't disagree. But reducing by 1 each doesn't really solve the problem.
The DC should probably be a flat 10 though. DC 10+half burning quickly gets out of hand when the roll is always d20+dex(max 5, typically ~1-3 at low tiers).

**Comment by itamarcu** [comment]
I think it might be better if failure on the ability check to put yourself out would still do something - for example, reduce your burning condition by half (rounded up). This way characters won't feel frustrated about losing their action for no gain at all.

**Comment by mlenser** [comment]
It does
>  On a failure by 4 or less, the burning level is reduced by 1.

That doesn't really solve the issue though.

**Comment by Marcloure** [comment]
> Acid Arrow does ~11.5 damage on the first turn, and ~5.7 on the second turn.
> Immolation does ~10.6 damage on the first turn, and ~5.3 damage on later turns.

I expected a greater difference, considering that the fire is only put out if the target lose its action (win-win), and even then it's a chance of doing so

**Comment by mlenser** [comment]
> I expected a greater difference

I did as well. And that's why there is a problem with burning.

**Comment by itamarcu** [comment]
What were the reasons not to have Burning level decrease by 1 every turn? (in addition to a check ending it faster)

**Comment by Paulorpribeiro** [comment]
I will look into this further on Monday, can't this weekend but it I is certainly a good discussion to have. The idea of burning is great, but we need to work on the execution. Now, burning an impossible decision for enemies (you either take a bunch of damage, no save or loose your action, and might get rid of the condition). Have a good weekend

**Comment by mlenser** [comment]
Reduced the overall amount of burning condition:
- Fireball burning reduced from 2 to 1 and its initial damage has been increased
- Immolation burning reduced from 3 to 2, its initial damage has been increased, and its augments only augment burning by 1
- Incendiary Cloud burning reduced from 2 to 1 and its augments no longer increase burning
- Minute Meteors damage buffed as small AoEs were recalculated, its burning reduced from 2 to 1, and its initial damage has been increased
- Molten Upheaval burning reduced from 2 to 1, and its initial damage has been increased
- Wall of Fire burning reduced from 2 to 1

**Comment by mlenser** [comment]
- Burning changed to occur at the end of the creature’s turn so it matches acid. Otherwise the damage might as well occur right away
- Burning changed to remove the DC changing based on the burning level

I'm unsure about reducing the level by 1 automatically at the end of each turn. Let's go with that for now and see how it works.

**Comment by mlenser** [comment]
I think the reducing of burning reduces any risk of burning being too powerful. Plus the change to DC makes the DC always manageable. DC 10 vs d20 + dex (~1-3) = **~60-65%** chance to end, and failure by 4 or less (**~80-85%**) means remove 1 burning level.

Closing this as the risk is reduced. If someone does some math I'd be willing to explore it further.
