### ISSUE TITLE
Catnap and Astral Sequestration

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#250]
[Catnap ](https://www.kryxrpg.com/themes/spells/catnap) has no use in this system as a short rest takes 15 min here. Also, [Astral Sequestration](https://www.kryxrpg.com/themes/spells/astral-sequestration) is simply a better spell at the same mana cost, being both safer and faster than Catnap.

**Comment by mlenser** [comment]
Catnap adjusted so the short rest happens after 1 minute
