### ISSUE TITLE
Temporal Sequestration

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#251]
This is a spell suggestion. Alternative names: Time Out, Temporal Pocket, Accelerated Rest, or whatever you come up with in the comments.

> **Temporal Sequestration** (3 mana, Time)
> *V, S, M (emerald dust worth 100 sp, consumed)*
> As you spend 1 action tracing a 10-foot radius circle on the ground, you create a temporally accelerated zone. The zone is a 10-foot sphere with no inherent lighting. Inside it, time flows at a faster rate - every minute that passes inside the zone takes only a second outside it. The zone has enough breathable air for a single human to last five hours inside. Nothing can physically pass into the perimeter, including light or sound, making it completely dark inside. Light can still pass out of it, so creatures outside the zone can see a blur of motion within. The spell stops when any creature inside the zone pushes against the barrier, when a spell is cast from within that would affect anything outside, when the perimeter is dispelled or disintegrated, or when five hours have passed inside the zone.
>
> *Augment*
> - You can expend 1 additional mana to increase the radius of the sphere to 20 feet. The supply of available air increases to sixty hours, and the spell's maximum duration increases to sixty hours inside the zone (or one hour outside it). 
> - You can expend 1 additional mana to accelerate time further inside, making every hour that passes inside the zone take only a second outside it.

This spell is shamelessly stolen from a cool story I've read, and it is meant as a very strong utility spell. It can allow a party to take a short rest in the middle of a fight, though it is restricted (they have to all stand very close together, they must spend the rest in a very small space, they have to conserve oxygen, and anyone outside the perimeter can take the opportunity to set a quick trap/ambush for them or run away). At the highest level (5 mana), this spell lets the party take an entire long rest in the span of two rounds, which I believe is epic enough to fit an archmage of time.

While this spell can easily "break" resource economy, a party that uses this spell in the middle of combat should expect monsters to surround them afterwards - or hide and lay an ambush for them. The barrier is asymmetric - it's easier to keep things from entering than keep them from exiting - which means that while the party is inside the zone, they cannot see or hear anything outside it - but everyone outside can see exactly what the party is doing.

If the ability to take a rest during combat for 5 mana is deemed too strong even for an archmage, I'm alright with adding a paragraph such as "This space is too tight and claustrophobic for anyone to rest within" or a concentration requirement for the time mage.

**Comment by itamarcu** [comment]
...only after posting this spell and rereading the Time spell list I realize that there already exists a spell, [Temporal Bubble](https://www.kryxrpg.com/themes/spells/temporal-bubble). I do think that spell is too weak (5 mana, 10 minutes casting time, for only 24 minutes, and only targeting yourself, and other creatures can easily stop it; though it doesn't specify any limitations about affecting things outside it).

Now I'm not sure what I'd want to do - probably replace Time Bubble with this spell (which might be called Time Bubble), because I do think it's infinitely more useful while still more or less balanced.

**Comment by Marcloure** [comment]
Just as a note, the longer the spell lasts, better it is for other uses beyond rest, like crafting, studying, etc.

**Comment by itamarcu** [comment]
Yes, that's true! However, this spell's normal duration is only 5 hours (~1 hour if you got friends), and it costs 100 sp each time, so you wouldn't want to waste it on most things. The best use for it is to basically prepare yourselves for a fight in the middle of it, giving your group much more prep time than whichever enemy is in front of you. It's also useful as an emergency spell, when something very bad is about to happen (total party kill, avalanche, volcano explosion, etc) and you need the extra time to think of a plan and prepare some useful spells/items to get out of it alive.

**Comment by mlenser** [comment]
>  24 minutes

You get 24 hours.

> and other creatures can easily stop it;

How? You're moving 24x faster than them. You'd get 24 rounds while they get 1.

**Comment by mlenser** [comment]
Temporal Bubble already covers this case.

**Comment by itamarcu** [comment]
My point was that Temporal Bubble is too weak and this would be a better replacement.

> You're moving 24x faster than them. You'd get 24 rounds while they get 1.

That's not precise and is exactly the issue - Temporal Bubble has a *casting time of 10 minutes*, so it's useless in combat. The time between the 10th minute and the 60th minute is almost always safe, if you could afford to do it in the first place.

I guess I could make a new github issue explaining why temporal bubble is weak, but I just wrote all of that suggestion before noticing temporal bubble (and decided to go through with it because it didn't seem good enough).

**Comment by mlenser** [comment]
> Temporal Bubble has a casting time of 10 minutes,

**Comment by mlenser** [comment]
> Temporal Bubble has a casting time of 10 minutes

Ya, this isn't a combat spell. It's a spell to use outside of combat to study, learn, etc.

Time Stop is for using inside of combat.

> I guess I could make a new github issue explaining why temporal bubble is weak

That would be more fitting, but I think you've misunderstood the spell. It's meant for out of combat.
