### ISSUE TITLE
Allow melee dagger attacks on Fan of Blades

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#252]
I think [Fan of Blades](https://www.kryxrpg.com/themes/maneuvers/fan-of-blades) should allow you to make any weapon attack with a dagger, and not only a thrown weapon attack. It would be weird if a melee dagger user had to step back from their enemy to do more damage.

**Comment by mlenser** [comment]
Mechanically, it could, but flavor-wise the maneuver is supposed to do emulate these options:

![image](https://user-images.githubusercontent.com/235857/82427072-e49dd480-9a88-11ea-8a94-73e3eef96033.png)
![image](https://user-images.githubusercontent.com/235857/82426942-bfa96180-9a88-11ea-995e-742adf1952b5.png)
![image](https://user-images.githubusercontent.com/235857/82427012-d5b72200-9a88-11ea-85df-b6f54f2676c0.png)

So based on the flavor I believe it should remain ranged.

**Comment by itamarcu** [comment]
We could clone the maneuver and make the clone melee-only, but I'd rather not force knife rogues to take both maneuvers when they're very similar.

Also - the images you've shown make it seem more like the thief is sacrificing accuracy (and damage) for hitting everyone in an area. This seems like the Fan of Knives maneuver is really meant to be more like the [Volley](https://www.kryxrpg.com/themes/maneuvers/volley) or [Rain of Arrows](https://www.kryxrpg.com/themes/maneuvers/rain-of-arrows) maneuvers. 

How about renaming this to "Blade Flurry" and allowing both ranged and melee attacks?

(yes, I'm stealing names from [WoW ability lists](https://wowwiki.fandom.com/wiki/Category:Rogue_abilities))

**Comment by mlenser** [comment]
Fan of Blades does use multiple weapons once its augmented. That's where the flavor of multiple is.

**Comment by mlenser** [comment]
So this maneuver should remain ranged only based on its flavor.

In general I try to avoid extra attacks without a very strong flavor to back it up. Frenzy for example. Slashing Blades is similar, but heavily restricted.

Extra Attack maneuvers are always a bit risky as they can stack features lik Hunter's Mark or Hex.

For light weapons we have both Bloodletting Blade and Slice Tendon as nice flavorful options. Potentially more options could be added, but there has to be a flavor motivation.
