### ISSUE TITLE
Fiery Aura implementation

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#254]
Based on #248 feedback

**Fire / Fiery Aura**
_concentration, 1 minute/mana_

As an action, you are surrounded by flames in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you.

Whenever an enemy enters the area for the first time on a turn or starts its turn there, it must make a Fortitude saving throw.

On a failed save, the creature takes 2d6 fire damage and is burning 1. _(Note: damage is estimated)_

On a successful save, the creature takes half as much damage.

In addition, ability checks made to extinguish the fire on a burning creature or object within the aura have disadvantage.

**Augment**
You can increase the damage by 1d6 for each additional mana expended.

**Comment by itamarcu** [comment]
> In addition, ability checks made to extinguish the fire on a burning creature or object within the aura have disadvantage.

I really like this! I would actually prefer it if this ability removed the fire damage and was just the burning condition (burning 2 or burning 3, with zero on a successful save?), but either way it is quite neat.

**Comment by mlenser** [comment]
Blazing Inferno added to the Fire theme

**Comment by mlenser** [comment]
Blazing Inferno changed to a 1 mana spell named Searing Burst with an augment to cause it to continuously occur
