### ISSUE TITLE
Storm Lord implementation

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#255]
Based on feedback from #248 

**Storm Lord / Aura**
_concentration, 1 minute/mana_

As an action, the air around you is electrified in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you.

When you cast this spell — and as a bonus action on each of your turns thereafter — a lightning bolt leaps from you to any number of creatures you choose within the sphere. A targeted creature must make a Reflex saving throw.

On a failed save, the creature takes 2d6 lightning damage and loses its reaction until the start of its next turn. _(Note: damage is estimated. Removing reaction at the start of your turn can be a powerful disengage tool)_

On a successful save, the creature takes half as much damage.

**Augment**
You can increase the damage by 1d6 for each additional mana expended.

**Comment by itamarcu** [comment]
I like this, but "any number of creatures" is too powerful. If you cast this with more mana, you could easily have a dozen creatures in a sphere around you, and bonus action Xd6 damage to all of them every turn is a lot of damage!

Maybe you could limit the number of creatures to your spellcasting ability modifier, or two times amount of mana expended, or "any number of creatures, as long as each of them is no more than 5 feet away from another creature targeted"?

**Comment by Marcloure** [comment]
I think "any number of creatures within the aura" and "when a creature enters or starts its turn in the aura" have roughly the same value, no? The main difference is that with the first you can move before using your bonus action, but it also allows for enemies to pass through the area without taking damage.

**Comment by itamarcu** [comment]
That's true, I should have considered that! The sphere's radius is actually normal (5 feet per mana) and the damage isn't huge, so it's fine when you compare it to the other aura.

Like you said, the actual damage could be tweaked to fit the guidelines, anyways.

**Comment by mlenser** [comment]
Lightning Nova added as 1 mana spell with an augment to cause it to continuously occur

Lightning nova harkens back to the ability named the same in Diablo 2
