### ISSUE TITLE
Frost Aura implementation

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#256]
Based on feedback from #248 

**Frost Aura**
_concentration, 1 minute/mana_

As an action, freezing cold surrounds you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you.

Whenever an enemy enters the area for the first time on a turn or starts its turn there, it must make a Fortitude saving throw.

On a failed save, the creature takes 2d4 cold damage, is slowed 1 until the start of its next turn.

On a successful save, the creature takes half as much damage.

**Augment**
You can increase the damage by 2d4 for each additional mana expended.

**Comment by itamarcu** [comment]
Suggested names:
- Frost Aura
- Aura Borealis
- Arctic Aura
- Ice Vortex
- Snowsquall

**Comment by mlenser** [comment]
Aura Borealis added to the Ice theme

**Comment by mlenser** [comment]
Aura Borealis changed to a 1 mana spell named Frost Nova with an augment to cause it to continuously occur
