### ISSUE TITLE
Tremoring Aura

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#258]
Expanding from #248

**Tremoring Aura **
_concentration, 1 minute/mana_

As an action, the ground quakes and erupts around you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you. The cracks on the ground turn the aura into difficult terrain.

Whenever a creature (enemy?) enters the area for the first time on a turn or starts its turn there, it must make a Reflex saving throw.

On a failed save, the creature takes 2d6 bludgeoning damage and is knocked prone. (Note: damage is estimated)

On a successful save, the creature takes half as much damage.

In addition, the ground rises at the edge of the aura, creating a wall that grants half cover against attacks that pass through it.

**Augment**
You can increase the damage by 2d4 for each additional mana expended.

**Comment by mlenser** [comment]
Tremors added to the Earth theme

**Comment by itamarcu** [comment]
You made a copy-paste mistake! [Tremors](https://www.kryxrpg.com/themes/spells/tremors) was mixed up with Blazing Inferno, and now reads:
> As an action, the ground quakes and erupts around you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you. The ground in the aura turns into difficult terrain.
> Whenever a creature enters the area for the first time on a turn or starts its turn there, it must make a Reflex saving throw.
> On a failed save, the creature takes 2d6 bludgeoning damage and is burning 1.
> On a successful save, the creature takes half as much damage and doesn’t start burning.
> In addition, ability checks made to extinguish the a burning creature or object within the aura have disadvantage.

But I'm pretty sure it should read:

> As an action, the ground quakes and erupts around you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you. The ground in the aura turns into difficult terrain.
> Whenever a creature enters the area for the first time on a turn or starts its turn there, it must make a Reflex saving throw.
> On a failed save, the creature takes 2d6 bludgeoning damage and is knocked prone.
> On a successful save, the creature takes half as much damage and isn't knocked prone.
> In addition, the ground rises at the edge of the aura, creating a wall that grants half cover against attacks that pass through it.

**Comment by Paulorpribeiro** [comment]
This spell is very similar to earth tremor (1 mana), except earth tremor is instant and tremors persists with concentration. Don't you think the concentratiom spell should be an augment to instant spell? So tremors an augment to earth tremor?

**Comment by itamarcu** [comment]
@Paulorpribeiro the idea is to have this as one of the spells in an "aura cycle", basically. Removing one of the spells and making it into an augment would be weird.

Perhaps one of these two spells could be altered a little bit to make these two more distinct.

**Comment by mlenser** [comment]
As of 50 mins ago:

Tremors integrated into Earth Tremor as an augment
