### ISSUE TITLE
Vendaval Aura 

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#259]
Expending from #248 

**Vendaval Aura ** (Is vendaval an English word?)
_concentration, 1 minute/mana_

As an action, rushing winds swirl around you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you. The wind force turns the aura into difficult terrain.

Whenever a creature (enemy?) enters the area for the first time on a turn or starts its turn there, it must make a Reflex saving throw.

On a failed save, the creature takes 2d6 bludgeoning damage and is pushed 10 feet away from you. (Note: damage is estimated. Pushing the creature when it just entered the aura can create some weird bounce effect)

On a successful save, the creature takes half as much damage.

In addition, creatures have disadvantage on attack rolls using arrows, bolts, and other ordinary projectiles that pass throw the aura. (Boulders hurled by giants or siege engines, and similar projectiles, are unaffected.)

**Augment**
You can increase the damage by 2d4 for each additional mana expended.

**Comment by itamarcu** [comment]
I like this. One suggestion: replace...
> The wind force turns the aura into difficult terrain.

with...
> Any Medium or smaller creature must spend 2 feet of movement for every 1 foot it moves when moving closer to you into or inside the aura.

(similar to the Gust of Wind)

**Comment by mlenser** [comment]
Cyclone added as 1 mana spell with an augment to cause it to continuously occur
