### ISSUE TITLE
A bunch of random cantrip balance suggestions

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#262]
I compared some spells and also copied the balance sheet to make sure my suggestions make sense mathematically. Except for those that come from my heart.

- Make [Dune Hammer](https://www.kryxrpg.com/themes/spells/dune-hammer) player's choice of bludgeoning or slashing (as sand is commonly slashing damage). If possible, increase the speed debuff to -10 feet at 13th level (might be too inelegant).

- Add the weight restrictions of [Lightning Lure](https://www.kryxrpg.com/themes/spells/lightning-lure) to [Hydraulic Push](https://www.kryxrpg.com/themes/spells/hydraulic-push) and [Gust](https://www.kryxrpg.com/themes/spells/gust) and [Thorn Whip](https://www.kryxrpg.com/themes/spells/thorn-whip) so that they all have the same restrictions (keep Gust's extra detail about objects).

- Change [Cloud Senses](https://www.kryxrpg.com/themes/spells/cloud-senses)'s saving throw from fortitude to will, as it is a psychic spell, and that's a slightly better save to target (this spell needs this).

- Reduce [Chill touch](https://www.kryxrpg.com/themes/spells/chill-touch)'s range from 60 feet to 30 feet. Improves the numbers, and for a spell with "touch" in its name, makes sense for you to cast it at closer targets :P

- Allow [Gust](https://www.kryxrpg.com/themes/spells/gust) to move creatures and objects in any horizontal direction, not only away from you. Or at least to pull objects! (this is just me asking for more utility from this spell)

- Make [Thunderclap](https://www.kryxrpg.com/themes/spells/thunderclap) deal 1d6 instead of 1d8 damage.

- Change [Toll the Dead](https://www.kryxrpg.com/themes/spells/toll-the-dead)'s damage. Currently it's 1d6 per tier, plus 1 per tier if the creature is missing any hit points. I think it would be better if the spell instead simply dealt 1d8 damage (and scaled with 1d8), with a sentence that says "If the creature is not missing any hit points, this spell has no effect". Alternatively: "... it has advantage on the saving throw.".

**Comment by mlenser** [comment]
> Make Dune Hammer player's choice of bludgeoning or slashing (as sand is commonly slashing damage). If possible, increase the speed debuff to -10 feet at 13th level (might be too inelegant).

A hammer is not slashing though. Think of Sandman
![image](https://user-images.githubusercontent.com/235857/82592088-a1cf2000-9ba0-11ea-8eba-0ae01b2c8177.png)

And as discussed on discord, Dune Hammer should not slow as much as icicle does.

____________________

> Change Cloud Senses's saving throw from fortitude to will, as it is a psychic spell, and that's a slightly better save to target (this spell needs this).

Senses are part of the bonus, thus Fortitude.

______________

> Change Toll the Dead's damage. Currently it's 1d6 per tier, plus 1 per tier if the creature is missing any hit points. I think it would be better if the spell instead simply dealt 1d8 damage

1d8 is more generic and more like other cantrips. The way its currently set up brings some uniqueness.
