### ISSUE TITLE
Add Weapon Thrower feat

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#263]
I would like to have a feat similar to [Dual Wielder](https://www.kryxrpg.com/themes/feats/dual-wielder) that works with thrown weapons specifically. This is because "holding a melee weapon in each hand" doesn't really happen with thrown weapons that you draw as part of the attack, much less with Darts and Shuriken which aren't melee weapons at all.

Therefore, a rogue that is throwing two (or three) daggers at an enemy every turn will be unable to actually hold two daggers after that turn, and then the rogue will not benefit from the +1 AC.

I would like this new feat to be added:

> **Quick Thrower** (4th level feat, skirmish, vanguard)
> You master fighting with thrown weapons, gaining the following benefit:
> - You gain a +1 bonus to AC while each of your hands is either holding a weapon that has the thrown property or is empty.
> - When you engage in two-weapon fighting with a weapon that has the thrown property, you can add your ability modifier to the damage of the second attack.

That first bullet about +1 to AC might seem a bit weird, because for two-weapon fighing it symbolizes you being able to parry attacks with the two weapons - but here you can think of it as... your hands are free or holding lightweight weapons, so it's easier for you to dodge attacks.

You could also make this feat the same as Dual Wielder, really, if you want to accommodate players who can do both. In that case, I'd want just the first bullet to be changed, so that if you're holding a thrown weapon or no weapon at all you still benefit from the bonus to AC.

**Comment by mlenser** [comment]
Dual Wielder already does what this feat desires. Dual Wielder works for thrown weapons.

> I'd want just the first bullet to be changed, so that if you're holding a thrown weapon or no weapon at all you still benefit from the bonus to AC.

The defense comes from using the weapons to block attacks. The weapons are essential to it.

**Comment by itamarcu** [comment]
No, this feat is suggested specifically because Dual Wielder doesn't do everything. As I said:

>  "holding a melee weapon in each hand" doesn't really happen with thrown weapons that you draw as part of the attack, much less with Darts and Shuriken which aren't melee weapons at all.

I'm talking about how Dual Wielder's requirement for increasing your AC is:

> while you are wielding a separate melee weapon in each hand

Which is problematic for two reasons:

1. Some thrown weapons are not melee weapons: Dart, Shuriken, Bola, Net.
2. You aren't holding the thrown weapon, You draw it and immediately throw it as part of your attack.

You could say that the first one is "solved" by just never throwing anything but daggers (because they're obviously better), and you could say that the second one is "solved" by creatively interpreting the "draw as part of your attack action" rule to mean "throw the weapon you're holding and then immediately draw another one, for you to use on your next turn". Still, I'd rather there was just rules text that enabled this.

I'd actually prefer it if this ruling was added specifically to the Dual Wielder feat, because rogues that dual-wield daggers shouldn't need to take *two* 4th-level feats to make their character build work. However, I agree that it would be better to make the weapon throwing feat something different in its mechanics, instead of trying to just fix dual wielder. Therefore, I offer a new option:

> **Weapon Thrower** (4th level feat, marksmanship)
> You master fighting with thrown weapons, gaining the following benefit:
> - When a creature enters the short range of a thrown weapon you are holding or able to draw, you can use your reaction to make an attack against that creature with that weapon.
> - When you engage in two-weapon fighting with a weapon that has the thrown property, you can add your ability modifier to the damage of the second attack.

**Comment by mlenser** [comment]
Dual Wielder is a feat for characters using two weapons and fighting with two weapons. It isn't intended for throwing weapons and the thematics of +1 AC don't make sense for throwing weapons. We shouldn't have it together to make it work. Thematics first, always.

**Comment by mlenser** [comment]
> When a creature enters the short range of a thrown weapon you are holding or able to draw, you can use your reaction to make an attack against that creature with that weapon.

This is too strong. It would significantly increase the DPR of a thrown character.

**Comment by itamarcu** [comment]
Alright, so I think we agree that the feat should look like this, right?

> **Weapon Thrower** (4th level feat, marksmanship)
> You master fighting with thrown weapons, gaining the following benefit:
> - ???????????????????
> - When you engage in two-weapon fighting with a weapon that has the thrown property, you can add your ability modifier to the damage of the second attack.

**Comment by mlenser** [comment]
Throwing doesn't necessitate two weapons thrown. A character can build a spear thrower with a shield.

**Comment by itamarcu** [comment]
That's true.

But now there's a problem - if a character is building a spear thrower they would like a feat like this but half of it won't apply to them. However, if a character is building a dart thrower, they would like a feat of this and *really want* the second half, because it increases the damage of their secondary dart attack.

We can't just say "dart throwers will take dual wielder" because as I stated above the feat will only give them half of its benefit, and the +1 AC will be wasted, which makes players feel bad about that choice.

**Comment by mlenser** [comment]
Throwing, like spears or picks, or several other weapons are not well supported by feats. Similar to https://github.com/mlenser/kryx-rpg-issues/issues/276 there could be a feat to support this, but it has to be thematic and unique. Offhand is interesting, but the problem there is it doesn't stack with dual wielder and characters might want both.

I don't have an answer, just a problem statement.
