### ISSUE TITLE
Add the Light property to Dart and Shuriken

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#265]
Currently, they're already strictly worse than daggers with how you can't use melee attacks with them. They should be made Light, so that you could actually use two-weapon fighting with them (and throw an additional one each turn) without having to take the fighting style that lets you use non-light weapons. It's really just a mistake by WotC that Darts aren't light weapons in D&D, and many people complain about it or houserule that they are (as they should be - they're the lightest weapon!).

**Comment by mlenser** [comment]
https://rpg.stackexchange.com/questions/86354/why-isnt-a-dart-considered-a-light-weapon

**Comment by mlenser** [comment]
Dart and Shuriken are now light weapons
