### ISSUE TITLE
Add a feat for improvised weapon proficiency

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#266]
My suggestion goes like this, but feel free to offer other things:

> **Brawler** (4th level feat, survival, vanguard)
> You are proficient with improvised weapons. When you use an improvised weapon, you can choose to treat it as having one of the following sets of attributes. You may not change the improvised weapon's attributes until a minute after making your choice. The attributes must be reasonable for your improvised weapon, under the GM's discretion. For example, you could use a long branch as a weapon with the reach property, a small rock as a light thrown weapon, or a chair as a shield.
> - 1d4, light, finesse, thrown (15/30)
> - 1d6, light, finesse
> - 1d8, finesse
> - 1d8, thrown (30/60)
> - 1d8, reach, two-handed
> - 1d12, two-handed
> - Shield (increases your Armor Class by 2. You can benefit from only one shield at a time)
> If you are a monk, improvised weapons are considered monk weapons for you.

**Comment by DalenWBrauner** [comment]
I have a fellow player in one of my games that would absolutely love something like this.

**Comment by mlenser** [comment]
> you can choose to treat it as having one of the following sets of attributes. You may not change the improvised weapon's attributes until a minute after making your choice

Huh? Serring an improvised weapon's attributes should be entirely up to the GM and should never be changed. A greatsword doesn't suddenly change, it's a greatsword.

Improvised items are determined by a GM:
https://www.kryxrpg.com/equipment/weapons

> In many cases, an improvised weapon is similar to an actual weapon and can be treated as such. For example, a table leg is akin to a club. At the DM’s option, a character proficient with a weapon can use a similar object as if it were that weapon and use their proficiency bonus.
>
> An object that bears no resemblance to a weapon deals 1d4 damage (the DM assigns a damage type appropriate to the object). If a character uses a ranged weapon to make a melee attack, or throws a melee weapon that does not have the thrown property, it also deals 1d4 damage. An improvised thrown weapon has a normal range of 4.5 meters and a long range of 9 meters.

That covers improvised weapons fully.

**Comment by mlenser** [comment]
Also, proficiency with improvised weapons that don't resemble actual weapons (as covered in the quote above) is provided by the Brawler fighting style:

> You are proficient with improvised weapons and you can roll a d4 in place of the normal damage of your unarmed strike.

**Comment by itamarcu** [comment]
The intention here was:

- Make a feat that grants proficiency in improvised weapons to classes that don't get fighting styles (Such as the Monk). 
- Make improvised weapons monk weapons, which is something for the "drunken master" style that some players want their characters to be.
- Make a feat that lets you rely purely on improvised weapons as your "weapon of choice" by giving you a benefit (versatility).

The idea of the benefit here is basically that you have much more leniency about what object can be considered what object when using improvised weapons. A normal character picking up a long branch might be told that this branch is unwieldy and just deals 1d4 damage, but a character with this feat would basically be allowed to say "I wield my long branch as if it's a lance" (reach) or "I wield my long branch as if it's a spear" (thrown), or "I wield my long branch as if it's a quarterstaff" (two-handed).

With normal improvised weapons, there is very little leniency, so the GM would usually give you the standard suboptimal stats of "1d4 damage, 20/60 range if you wanna throw it".

Here, the Brawler is so used to fighting with whatever they can get their hands on, that they can pretty much emulate martial weapons with these things, and because it's all improvisation, they can basically "shift their stance" and improvise a new use for the weapon they're holding (e.g. throw the chair they were using as a shield at someone). The limitation of once per minute is to prevent someone from constantly changing their "weapon type" to give themselves a shield when they're hit, reach when someone's 10 feet away from them, etc.

It could alternatively be a switch-limit of "only at long rests" or "only at the start of your turn". Really depends on how much versatility you want to give the player with a single object.

(also, now I notice that I named this feat "Brawler" too, oops. if you decide to give this feat a chance it would need to be renamed.)

**Comment by mlenser** [comment]
> Improvised weapons are determined by a GM

This is how improvised weapons work. A feat for a player to determine them won't be added.

**Comment by mlenser** [comment]
> Make a feat that grants proficiency in improvised weapons to classes that don't get fighting styles

The Fighting Styles are where improvised weapons come from. A better solution to the scenario you're talking about is giving the monk Fighting Styles and then moving part of their unarmed fighting into there. Then a Monk can choose to use unarmed or weapons (Kensei, Drunken Master). I've opened https://github.com/mlenser/kryx-rpg-issues/issues/268 to handle this.
