### ISSUE TITLE
Archival Magic

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#267]
> Archival Magic 2 Mana
> As an action, you learn one spell that costs 2 or less mana from any theme for the duration. You cannot augment it to more than 2 mana.
> 
> Augment
> The spell can cost or be augmented 1 additional mana for each additional mana expended.

This spell seems like its more fitting for Wizards to have as a class feature rather than something anyone could grab. It seems to step on the Wizard identity a bit. One of my Player Characters has been able to do some really creative things with this spell during downtime sessions, but they are an Occultist with plenty of other benefits! 

Any opinions on this? I like the spell aesthetically but it does allow other classes to perform the job of the Wizard Spellbook with only an investment in Divination.

**Comment by mlenser** [comment]
Note: Archival Magic replaced Master of Magic, a former 14th level feat:

> Your knowledge of magic allows you to duplicate almost any spell. As a bonus action, you can call to mind the ability to cast one spell of your choice from any theme. The spell must cost equal to, or less than, your mana limit or psi limit, and you follow the normal rules for casting it, including expending mana or psi. The ability to cast the spell vanishes from your mind when you cast it or when the current turn ends.
>
> Once you use this feature, you can’t use it again until you finish a long rest.

**Comment by itamarcu** [comment]
If you just reflavor it a tiny bit and remove the "divination" theme, this could very easily be explained as "your patron casts a spell for you, even if it's a spell you don't know", or the same with your god, or "your innate magic allows you to manifest a new temporary power, without knowing how to do it again".

While this fits wizards, I think allowing non-wizards to obtain this ability or at least something similar to it is not that wrong.

Maybe you could add a restriction that makes this spell better for wizards, such as requiring a theme you know or a number of spells known from there.

---

Also, uh, rules question: what's stopping a Wizard from using this spell and then scribing the new spell into their spellbook? :D

**Comment by DalenWBrauner** [comment]
> What's stopping a Wizard from using this spell and then scribing the new spell into their spellbook? :D

(Interactions like these are why I never use spellbook rules when I play wizards, but that's a seperate issue.)

**Comment by mlenser** [comment]
I reworded it

> As you spend 1 minute to cast this spell, you call to mind a fragment of a spell that costs 1 mana or less from any theme. Until the spell ends, you can cast the spell once and then this spell ends. You cannot augment the spell to more than 1 mana and the knowledge of the spell is insufficient to learn from permanently.

## Changes

### 1 mana
1 mana instead of 2 mana makes the spell oyu find always 1 below your limit

### The spell must be your next spell and is then gone
This limits how you can use the spell. This will restrict it to mostly out of combat choices and first-spell

### Can't learn from it

_____________

That said, I still think this spell is problematic and I think I should probably remove it.

**Comment by mlenser** [comment]
Archival Magic removed as it provides too much versatility, searching through all spells, and steps on the Mage’s toes
