### ISSUE TITLE
Give Fighting Styles to the Monk

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#268]
Move part of their unarmed fighting into the fighting style and have it be a tradeoff for the other options. Then a Monk can choose to use unarmed or weapons (Kensei, Drunken Master).

**Comment by itamarcu** [comment]
Would it be possible to make a feat that grants a fighting style, instead? This way other characters (e.g. Rogue) could get this.

**Comment by mlenser** [comment]
Making it a feat would simply be a necessary choice that increases a Rogue's DPR as there are no comparable choices that would be as effective.

**Comment by mlenser** [comment]
There is no room to trade out any low-level monk feature for fighting styles so I'll need to analyze this further.

A GM can let a monk forgot the unarmed attacks dealing 1d4 for Brawler for the Drunken master or other styles for the Kensei.

I'll try to make this a formal option.

**Comment by itamarcu** [comment]
How about the option of making this a [Psychic Focus](https://www.kryxrpg.com/character/classes/psionicist/monk#psychic-focus)? 

The fact that a monk can only keep a single psychic focus makes this a bit worse, though.

**Comment by mlenser** [comment]
I've tried this in many ways, but ultimately I don't think there is a solution. Monks need the unarmed damage on all their extra little attacks so removing that and giving them a benefit when they use their longsword isn't mechanically worth it.
