### ISSUE TITLE
Change the Bow Expert feat

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#269]
Bow Expert doesn't make sense. it mentions being "skilled with a bow" but it actually makes you skilled with arrows as a melee weapon. 

My suggestion is to rename this feat to "Melee Marksman", and instead of "you can use an arrow as an improvised melee weapon" make it "you can use a ranged or thrown weapon or a piece of ammunition as an improvised melee weapon".
This way, the feat also lets you whack people with your longbow or puncture them with your blowgun or stab them in the eye with a dart - it's flavorful, and it keeps the same mechanics.

The old and new feats, for comparison:

Old:

> Skilled with a bow, you can use an arrow as an improvised melee weapon that you are proficient with it, and you can use your Dexterity modifier instead of Strength for the attack and damage rolls with it. If you hit a creature with this attack you can then immediately use your reaction to move up to half your speed without provoking opportunity attacks from the target of your attack.

New:

> You can use a ranged or thrown weapon or a piece of ammunition as an improvised melee weapon that you are proficient with it, and you can use your Dexterity modifier instead of Strength for the attack and damage rolls with it. If you hit a creature with this attack you can then immediately use your reaction to move up to half your speed without provoking opportunity attacks from the target of your attack.

**Comment by mlenser** [comment]
> lets you whack people with your longbow

This is purposefully not an option, the same as it is not an option to hit someone with an instrument. The instrument/bow is a delicate creation that is not built for melee and would likely break in melee.
In this case a bow is very different from a quarterstaff for example. I'd allow a hit with it, but then it'd probably be broken and need fixing.

**Comment by mlenser** [comment]
Bow Expert removed as there are maneuvers like Vault which serve the need better
