### ISSUE TITLE
Chains of Light is weak

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#270]
Compare:

[Chains of Light](https://www.kryxrpg.com/themes/spells/chains-of-light)
[Constricting Bandage](https://www.kryxrpg.com/themes/spells/constricting-bandage)
[Ensnare](https://www.kryxrpg.com/themes/spells/ensnare)
[Iron Maiden](https://www.kryxrpg.com/themes/spells/iron-maiden)

They're basically all identical with different flavors, except Chains of Light deals no damage and its augment is different (more creatures).

I suggest adding some radiant damage to chains of light. I also suggest either changing the augment for this spell to match the others, or making all of these spells have both and augment for more damage and an augment for more targets.

**Comment by mlenser** [comment]
Utility spells are especially hard to calculate. The numbers on the sheet are meant to be guidelines, not hard numbers.

The whole section is red:
![image](https://user-images.githubusercontent.com/235857/82728151-04cecd00-9cef-11ea-9d01-7009d959f4fb.png)

**Comment by itamarcu** [comment]
I don't see why this is considered a utility spell and the other three spells aren't. Wouldn't adding damage to this spell solve this problem?

**Comment by mlenser** [comment]
It would change the flavor. You could also add damage to Hold Creature, but that's not the point.

**Comment by Marcloure** [comment]
I can accept the chains burning with radiant damage, i think that makes sense. About Hold Creature, it causes paralyze, while Chains of Light only restrains

**Comment by mlenser** [comment]
The spreadsheet isn't accurate for these utility spells. It shouldn't be used to make micro adjustments to these type of spells. They are only there for a general feeling. As I posted above, many would need to be adjusted if it was accurate.

**Comment by Marcloure** [comment]
I'm not considering the Spreadsheet, I'm comparing the effects. All of these are 2 mana:

- Chains of Light: restrains a target
- Entangle: restrains in AOE
- Hold Create: paralyzes a target
- Iron Maiden / Constricting Bandage: restrains and paralyzes

Clearly Chains of Light is far worse than the other options at 2 mana

**Comment by itamarcu** [comment]
Sounds like the preferred solution is to make the spell more unique. What if it restrained and blinded, for example?

**Comment by Marcloure** [comment]
That would give 2 advantages to attackers

**Comment by mlenser** [comment]
Winter's Grasp is nearly the same as Chains of Light. Brain Lock is only slightly better. Confusion is "bad".

[Chains of Light](https://www.d20pfsrd.com/magic/all-spells/c/chains-of-light/) are not meant to have damage.

Ultimately, I need to redo my calculations of conditions. Until I do so, I don't feel comfortable doing micro-adjustments on utility spells.

**Comment by mlenser** [comment]
https://github.com/mlenser/kryx-rpg-issues/issues/273

**Comment by itamarcu** [comment]
I noticed this issue again, and I have an idea for a solution (if you're okay with rebalancing utility spells a bit):  based on your link for the source of Chains of Light, we can add the "dimensional anchor" effect, just like the one in Hallow, Magic Circle, and augmented Wall of Force:

> While held by the golden chains, a creature cannot move or travel using teleportation or by extradimensional or interplanar means.
