### ISSUE TITLE
Circle of Death should be a Cylinder and not a Sphere

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#271]
...because it fits the flavor better, and has almost no mechanical impact.

https://www.kryxrpg.com/themes/spells/circle-of-death

**Comment by mlenser** [comment]
A sphere is a circle, just as much as a cylinder. A cylinder just extends upward more. How does that fit the spell better?

**Comment by itamarcu** [comment]
I'm imagining circle of death as an evil magic circle that is drawn on the floor and then extends its effects up above it. I tried to find some pictures and this is the closest I found:

![](https://www.worldanvil.com/uploads/images/7c6a2b1bce10fc66e725df1ad3146bcf.png)

![](https://ocdn.eu/zapytaj-transforms/1/VEVk9kuTURBXy84ODM5ZTM0Ni1mNzBlLTRhMGYtOTkwMy00MzcwYTkyYzQ2MWEuanBlZ5GTAs0EOACBAQI)

**Comment by mlenser** [comment]
It is a sphere, see https://www.dndbeyond.com/spells/circle-of-death

**Comment by Marcloure** [comment]
Circle of Death used to be "everyone there dies", but it was converted to damage in 5e. So, it's not really a visual spell, just a spell that kills things within the distance to its origin
