### ISSUE TITLE
Two-weapon fighting and Spell Strike

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#278]
> When you take the Attack action, you can forgo one weapon attack to use a maneuver or cast a spell that has a use time or casting time of 1 action.

Can you forgo an attack made with your off hand? Seems like so, but is that the intention? It won't make much of difference if the caster has the same values for both weapons, but it's important if the character doesn't have Dual-Wielder or if one of their weapons are magical.

**Comment by mlenser** [comment]
Mechanically, you should forgo the attack with the ability modifier. I can add wording for that so TWF doesn't avoid the negative.

**Comment by mlenser** [comment]
`When you take the Attack action, you can forgo one weapon attack that uses your ability modifier to...`

**Comment by mlenser** [comment]
Spell strike feature requires you to forgot an attack that uses your ability modifier
