### ISSUE TITLE
Merge Regenerate and Regrowth

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#282]
I'd like it if Regenerate and Regrowth were merged into a single spell (Life & Plants, unsure about Alteration) that had a target of touch. The augment would be adding targets (one per mana) or adding distance (120 feet, probably, as it would cost a whole mana point).

Thematically, they're pretty much exactly the same thing - regrowth and regeneration are almost synonyms, and I don't see why plants theme should grant you additional range, or be unable to regrow major organs (plants do that all the time!).

**Comment by mlenser** [comment]
They are different spells. One targets other creatures, one targets only you. The spells are balanced for their distance.

In general I don't think touch should be required on spells above cantrips unless there is a strong reason. This is a good prompt to minimize the amount of those.
