### ISSUE TITLE
Links to Sample Subclasses behave strangely

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#286]
Classes like Rogue with starting Themes have links such as these:
https://www.kryxrpg.com/character/classes/rogue/deceit

Which displays the page, but without any of the Archetype information. This doesn't quite look like expected behavior.

**Comment by Marcloure** [comment]
It goes to https://www.kryxrpg.com/character/classes/rogue/ and tries to search for that archetype. If you write anything after rogue/ that is not an existing archetype, the same will happen.

**Comment by DalenWBrauner** [comment]
To be specific, these links work fine:
![Hyperlinks in the Subclasses Section](https://i.imgur.com/Riibtuz.png)

But these links (which link to the subclasses) behave strangely:
![Deceptive Ploys](https://i.imgur.com/HG71XlX.png)

**Comment by DalenWBrauner** [comment]
@Marcloure Right, the likely solution is to use `#Deceit` instead of `/Deceit`.

**Comment by Marcloure** [comment]
Oh, now I understand what you mean. The links in Deceptive Ploys aren't linking to the Themes, but to the Rogue page

**Comment by DalenWBrauner** [comment]
Right. And it makes sense they would link to the Subclasses below, but not that they would hide the archetype information.

**Comment by mlenser** [comment]
will be fixed next time I push.
