### ISSUE TITLE
Slick Pores Feat suggestion

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#288]
### Slick Pores
4th Level Feat (Water Theme)
_Prerequisites: The ability to cast at least one spell_

You can cast _[Slick Skin](https://www.kryxrpg.com/themes/spells/slick-skin)_ on yourself at will, without expending mana.

**Comment by mlenser** [comment]
Hydrated Skin added as a feat to cast Slick Skin at will
