### ISSUE TITLE
Shadowy creation permanent augment

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#289]
The shadowy creation spelk is a copy of t h e creation spell, and it is great an all, fits the theme. But the augment to make the item permanent doesn't fit the shadow theme in my opinion. It fits creation, but how can an item made of shadow from the shadow fell ever be made permanent? C an we take that augment away?
If the shadow spell will be that much weaker than the creation counterpart, and we want to compensate that somehow, we could come up with a different augment. But I don't think it is necessary, you already have a powerful utility spell in the a theme that is already very versatile. It has burst damage, debuffs and concealment/ protection, one of the most versatile themes (together with beast maybe).

**Comment by itamarcu** [comment]
I agree.

If we're looking for augment ideas...

- Spend 1 mana to cast this spell as an action instead of taking a minute to cast it. The duration of the item created is reduced to 1 minute.
- Spend 2 mana to make it last indefinitely...until it is exposed to sunlight or heat.
- Spend 1 mana to make the item burst into shadows when the duration is up, blinding creatures holding it or next to it, for one round.

**Comment by Paulorpribeiro** [comment]
O I'd vote for 1, maybe 2, or both!

**Comment by mlenser** [comment]
Creation is a shadow spell by RAW: https://www.dndbeyond.com/spells/creation

**Comment by mlenser** [comment]
Creation is a Shadow spell by RAW: https://www.dndbeyond.com/spells/creation. It's not a shadowy variant to Creation, but Creation was created out of this spell with the Shadow parts removed.

**Comment by Paulorpribeiro** [comment]
You always say we should be so attached to RAW, what do you think? Should a shadow creation have the possibility to be made permanent when we have a theme specifically for creation?

**Comment by Paulorpribeiro** [comment]
Not to be personal, everyone who is contributing should make this reflection when offering opinions... think with this system in mind

**Comment by mlenser** [comment]
I was just adding a correct to the first sentence which said that Shadowy Creation was a copy of Creation, not commenting on the suggested alteration.

**Comment by mlenser** [comment]
Creation spell removed as Fabricate, while different, fits the theme better

**Comment by mlenser** [comment]
Shadowy Creation augment to make the items permanent removed

**Comment by itamarcu** [comment]
Maybe keep the Creation spell in Creation? The theme seems like it's about both fabrication (making materials into complex things, e.g. Forge Armor or Fabricate) and creation "ex nihilo" (e.g. Iron Maiden, Mighty Fortress, Construct Defender).

Its description (which I'll admit is definitely influenced by the existence of this spell) is:

> Creation is the art of making new objects, whether from the materials of the world **or out of thin air**. The Creation theme focuses on a variety of creation, utility, protection, and control, with some piercing and slashing damage.
> Spells from the Creation theme allow you to repair objects, fabricate objects, create clouds and walls of blades, cover areas with slippery grease, instantaneously forge hooks and armors, restrain creatures in bindings of iron, build shelters, **create materials out of nothing**, restore the function of broken objects and constructs, and build a whole fortress in under a minute.

Plus, the combo of Creation plus Fabricate is neat (though it still remains in some form, if you have both shadow and creation in your party).

**Comment by itamarcu** [comment]
If the intention is to keep Creation about using existing matter and not creating new matter, I'd be fine with that too - that's a good limitation that keeps things interesting. In that case, though, I hope we could change the few spells that do create matter out of nothing. For example, the Construct Steel Defender spell could change to make the construct built out of surrounding materials (or material components you carry).

**Comment by mlenser** [comment]
Creation spell is removed. It comes from when the theme covered ectoplasm and other stuff. It doesn't fit anymore. See the note above.

I'll push sometime soon

**Comment by mlenser** [comment]
Steel defender should probably be removed until the artificer is done.

**Comment by mlenser** [comment]
> create materials out of nothing

The theme descriptions were written by Marcloure specifically for the spells that were in each theme at time time. They've become a bit outdated as things have moved around. But this example is just referencing the Creation spell.
