### ISSUE TITLE
Remove the Fangs of the Fire Snake feat

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#290]
[Fiery Blast](https://www.kryxrpg.com/themes/feats/fiery-blast) vs [Fangs of the Fire Snake](https://www.kryxrpg.com/themes/feats/fangs-of-the-fire-snake).

Fangs of the Fire Snake is a feat based on the 5e Four Elements monk:
> **Fangs of the Fire Snake**: When you use the Attack action on your turn, you can spend 1 ki point to cause tendrils of flame to stretch out from your fists and feet. Your reach with your unarmed strikes increases by 10 feet for that action, as well as the rest of the turn. A hit with such an attack deals fire damage instead of bludgeoning damage, and if you spend 1 ki point when the attack hits, it also deals an extra 1d10 fire damage.

Fiery Blast is based on [Searing Blast](https://www.kryxrpg.com/themes/feats/searing-blast), which I beleive is based on 5e Sun Soul monk:
> **Radiant Sun Bolt** - You can hurl searing bolts of magical radiance. You gain a new attack option that you can use with the Attack action. This special attack is a ranged spell attack with a range of 30 feet. You are proficient with it, and you add your Dexterity modifier to its attack and damage rolls. Its damage is radiant, and its damage die is a d4. This die changes as you gain monk levels, as shown in the Martial Arts column of the Monk table.

(There's a whole "cycle" of Blast feats for the monk in Kryx RPG - one for each element)

I think that Fangs of the Fire Snake should be removed. Functionally, for Monks, the Fiery Blast is better. If you take both feats, you get an attack with a range of 35 feet, which is weird. If you're not a Monk, you pretty much have no reason to take this, unless you're playing a very weird brawler fighter who refuses to play a monk but wants a very short range fire fist attack.

**Comment by mlenser** [comment]
Range 30/60 can be worse than reach 10 feet though. Reach allows for opportunity attacks and to avoid cover.

Maybe the reach just needs to be made permanent?

**Comment by DalenWBrauner** [comment]
I think so. As of now, since it lasts "for the rest of the turn" and not "until the end of your turn", it grants you extended reach to your Opportunity Attacks, but only if you happened to use this feature with the Attack action this turn.
That made more sense when it had a Ki cost (which shouldn't return), but now seems like a rather arbitrary limitation.

**Comment by itamarcu** [comment]
You're right, I haven't considered opportunity attacks - the Fangs say "When you use the Attack action on your turn" so they currently don't allow this, but if the feat was changed, it would be a reason to pick it.

I do think that a feat that increases opportunity attack range for monks is pretty neat, but in that case I think I'd rather just have this feat detached from the fire concept. If this remains, maybe it's better as...

> **Fangs of the Snake** (or another name)
> Your reach with your unarmed strikes increases by 5 feet.

**Comment by DalenWBrauner** [comment]
I also think it's rather strange that Fire Fangs _isn't_ Monk-exclusive when Fiery Blast is. I get that Fiery Blast is built explicitly to scale with Monks, but it's thematically closer to a cantrip than Fire Fangs. Whereas elemental unarmed strikes seem squarely in the Monk thematic to me.

**Comment by mlenser** [comment]
Fangs of the Fire Snake changed from 6th level to 4th level, requires monk, and reworked to be continuous reach with unarmed strikes.

**Comment by mlenser** [comment]
Opened https://github.com/mlenser/kryx-rpg-issues/issues/294 to look at moving stuff to psychic focus.
