### ISSUE TITLE
Increase duration of Ash Fall and Snow Storm

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#291]
> **[Ash Fall](https://www.kryxrpg.com/themes/spells/ash-fall)** (fire)
> *concentration, 1 minute/mana*
> As an action, ash falls in a cylinder twice as big as normal centered on a point you choose within 120 feet. The area is heavily obscured.

> **[Snow Storm](https://www.kryxrpg.com/themes/spells/snow-storm)** (ice)
> *concentration, 1 minute/mana*
> As an action, snow falls in a cylinder twice as big as normal centered on a point you choose within 120 feet. The area is heavily obscured, and exposed flames in the area are doused.
> *(+also has an augment)*

> **[Fog Cloud](https://www.kryxrpg.com/themes/spells/fog-cloud)** (water, air)
> *concentration, 1 hour/mana*
> As an action, you create a sphere twice as big as normal of fog centered on a point within 120 feet. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.

> **[Sand Cloud](https://www.kryxrpg.com/themes/spells/sand-cloud)** (sand)
> *concentration, 1 hour/mana*
> As an action, you create a sphere twice as big as normal of fog centered on a point within 120 feet. The sphere spreads around corners, and its area is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.
> *(+also has an augment)*

Ignoring the fact that some of these have useful augments and some of them don't - I feel like the first two spells are much weaker, because their duration is 1 minute and not 1 hour (per mana, but it doesn't matter much).

Yes, the second two spells' winds also stop early if a strong wind disperses them, but that's an uncommon situation, and even when that happens it's almost definitely gonna be after more than one minute.

So, I suggest adding the 1 hour duration to the first two spells. Probably also add the wind-dispersal part, at least for the ash fall.

**Comment by mlenser** [comment]
I wouldn't expect heavy winds to improve ash anymore than snow.
