### ISSUE TITLE
Summon Elemental Chaos Theme

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#292]
I have a fun suggestion for the chaos theme! During playtesting one of my players mentioned there were exactly 8 Elementals.  

> As an action, you call forth a random elemental based on the chart below which appears in an unoccupied space that you can see within 60 feet. The elemental is a fire elemental companion, using 1 resource. The creature has no mana or stamina dice, but you can infuse it with mana or stamina dice by expending mana, up to your mana limit. For each mana you expend, the elemental gains 1 mana or 2 stamina dice. The elemental is friendly to you and your companions, and it disappears when it drops to 0 hit points or when the spell ends. As a bonus action on each of your turns, you can mentally command any creature you summoned with this spell if the creature is within 300 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete. Augment You can augment this spell with the following options, expending mana for each option. You can use an additional resource for each additional mana expended. You can expend 2 additional mana to call forth another elemental.

1- Fire Elemental
2 - Acid Elemental
3 - Lightning Elemental
4- Water Elemental
5 - Ice Elemental
6 - Sand Elemental
7 - Earth Elemental
8 - Air Elemental

**Comment by wherfz** [comment]
If this spell was to be more complicated I'd have the elemental shift to a new type of elemental every time it was given a new order as a bonus action. I like this idea of a constantly shifting summon, but it might be a bit much!

**Comment by mlenser** [comment]
Summoning spells are meant to use companions. See https://www.kryxrpg.com/themes/spells/animate-flames

So this should follow the same structure and summon a random variant.

**Comment by DalenWBrauner** [comment]
Huh? All 8 of the elementals listed are on the Companions page. The intent
is to roll a d8 and summon one of those at random.

**Comment by mlenser** [comment]
Animate Chaos added as a 1 mana spell
