### ISSUE TITLE
Consider moving Monk feats into psychic focus

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#294]
I can add feats like [Fiery Blast](https://www.kryxrpg.com/themes/feats/fiery-blast) and [Fangs of the Fire Snake](https://www.kryxrpg.com/themes/feats/fangs-of-the-fire-snake) to Psychic Focus (with monk required).

We can then add a feat to make one effect permanent. That'd be the same effect, but better structure if we think allowing psychic focus to be permanent is good.

**Comment by itamarcu** [comment]
The feat would need to be phrased more or less like this:

> **Permanent Focus** (4th level feat?, mind? general? perhaps one per theme, appearing in all themes?)
> *Prerequisites: Psionicist*
> You have practiced one of your psychic abilities for long enough that you can use it instinctively.
> Pick one [Psychic Focus](https://www.kryxrpg.com/character/classes/psionicist/psion#psychic-focus) from a theme you have. You gain its effects permanently, as if this feat granted them to you.
> You may no longer activate any psychic focus if its effects are identical to the effects gained from this feat (for example, if both grant you a +1 to your AC).
> You may take this feat multiple times. Each time, pick a different psychic focus, and you may not pick one that has effects identical to the effects gained from this feat.

(The restriction is to prevent a character from stacking these and getting +1 AC from every feat, or taking two +10 speed increases. However, you might judge that this should still be allowed (or choose to remove the +1 AC psychic foci), in which case this feat no longer needs those restrictions)

**Comment by mlenser** [comment]
Psychic Focus now lets you focus on two psychic focuses at a time at 9th level and 3 at 17th level

**Comment by mlenser** [comment]
All the feats converted to psychic focuses for the Psionicist
