### ISSUE TITLE
Sound theme feat suggestion - Selective Hearing

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#295]
> **Selective Hearing** *(4th level feat, sound)*
> You have fine control over your ears, allowing you to instinctively deafen yourself to defend against harmful sounds. You have resistance to thunder damage, and you have advantage on saving throws against effects that require you to be able to hear, such as words laced with magic or startling roars.

This is based on feats such as [Stormborn](https://www.kryxrpg.com/themes/feats/stormborn). It gives you resistance to one damage type and not two, but it also grants you advantage against Suggestion, Compulsion, Vicious Mockery, Fearsome Beast, etc.

An alternative feat could be "as a reaction to hearing a harmful sound, you deafen yourself until the start of your next turn". This would be outright immunity to those effects, but would come at the cost of becoming temporarily deaf, which is pretty cool.

If this feat seems too supernatural, perhaps it should require spellcasting.

**Comment by mlenser** [comment]
I think the flavor is too strange for the instantaneous deafening.

Roosters can do it when they make loud noises, but that's an action, not a reaction. I can't see the flavor for this to be a reaction.

I'd prefer a different flavor for the resistance.

**Comment by DalenWBrauner** [comment]
I'm no audio engineer, so I don't have a good name for it, but:
> You magically dampen loud sounds and amplify soft ones before they reach your ears. You have resistance to Thunder damage, and have advantage on Perception checks to hear quiet sounds (such as faint whispering or distant marching).

This seems in line mechanically with the [Dungeon Delver](https://www.kryxrpg.com/themes/feats/dungeon-delver) feat. It _could_ require spellcasting.

**Comment by mlenser** [comment]
I can't see the flavor of that. It feels forced to get the desired mechanical benefits. I think we should start from flavor or scrap the idea.

**Comment by mlenser** [comment]
Closing this, can reopen
