### ISSUE TITLE
Sound theme feat suggestion - Echolocation

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#297]
> **Echolocation** *(6th level feat, sound)*
> You can sense your surroundings by sound. You have advantage on Perception checks that rely on hearing and have blindsight out to a range of 30 feet. You can’t use this blindsight while deafened.

This is based on feats such as [Whispers of the Grave](https://www.kryxrpg.com/themes/feats/whispers-of-the-grave) (which allows you to cast a 2-mana spell at will), except here the spell is Echolocation, and instead of casting the spell you just have its effects on you all the time (which makes more sense).

If this feat seems too supernatural, perhaps it should require spellcasting.

Note - I admit that blindsight is stronger than tremorsense, which is what the [Grounded](https://www.kryxrpg.com/themes/feats/grounded) feat gives. However, the Grounded feat is of slightly lower level, and it also grants resistance to being pushed, pulled, or knocked prone, which is very beneficial.

If this feat is still a bit too strong, another limitation could be added - making the echolocation only work while there's a source of sound nearby (including your own voice). This means you can't sneak through silent and dark areas with this ability, unless you're willing to make sound.

The minimum level could be higher, after fixing #298!

**Comment by mlenser** [comment]
I need to align feats that allow at-will to a system. Right now its not very clear what mana is at each level.

**Comment by mlenser** [comment]
Echolocation added as an 8th level Sound feat

I chose 8th level because blindsight allows you to attack as if you see them whereas tremorsense requires earth below you and only tells you where they are. The attack is still made with disadvantage.

**Comment by itamarcu** [comment]
> Additionally, you have disadvantage on saving throws against loud sounds.

is this intended? is this feat supposed to make you permanently more vulnerable to thunder damage?

(The actual Echolocation spell doesn't have this weakness)

**Comment by mlenser** [comment]
> is this intended?

I intended it, ya. An example: Daredevil can basically see through echolocation, but one of his biggest weakenesses is loud noises.

I can add it to the spell.
