### ISSUE TITLE
Align at will feats

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#298]
Some current levels:

## 4th level
- Barkskinned: 1 mana spell, 4 hours/mana duration
- Hydrated Skin: 1 mana spell, 4 hours/mana duration
- Persistent Armor: 1 mana spell, 4 hours/mana duration

## 6th level
- Ascendant Step: 1 mana spell, 5 mins/mana
- Master of Myriad Forms: 1 mana spell, 1 hr/mana
- Misty Visions: 1 mana spell, 5 mins/mana
- Sense Magic: 1 mana spell, 5 mins/mana
- Sense Toxins: 1 mana spell, 5 mins/mana
- Shroud: 1 mana spell, 1 min/mana
- Tongue of Wild Spaces: 2 mana spell, 5 mins/mana
- Whispers of the Grave: 2 mana spell, 5 mins/mana

## 8th level
- Consult the Spirits: 1 mana spell

## 10th level
- Visions of Distant Realms: 2 mana spell, 1 hr/mana

## 14th level
- Celestial Wings: 2 mana spell, 5 mins/mana
- Demonic Wings: 2 mana spell, 5 mins/mana
- Vampiric Wings: 2 mana spell, 5 mins/mana

**Comment by Marcloure** [comment]
I believe these Feats should be a level below the next tier. So a 1 Mana spell would be available at will at 4th level, 2 Mana spells at 8th level, a 3 Mana at 12th level, so on.

It's also important to consider if a character at that level should have such a power fictionally. For instance, I don't know if 8th level is high enough for a Priest to gain permanent angelic wings. Seems like a very prized blessing.

**Comment by Marcloure** [comment]
Also, it's important to consider the spell's duration and how probable it is that you would be using it more than once per day. Fly lasts some minutes and you could be using any combat, the Armor spells you would be using once per day anyway.

**Comment by mlenser** [comment]
I think it really varies by spell.
- Detect Magic/Detect Poison at will is pretty harmless.
- Speaking with Dead is rare enough that its quite harmless.
- Levitating or turning invisible are both very strong.

**Comment by mlenser** [comment]
# New List

## 4th level
- Barkskinned: AC spell, 1 mana spell, 4 hours/mana duration
- Hydrated Skin: AC spell, 1 mana spell, 4 hours/mana duration
- Persistent Armor: AC spell, 1 mana spell, 4 hours/mana duration

## 6th level
- Sense Magic: 1 mana spell, 5 mins/mana
- Sense Toxins: 1 mana spell, 5 mins/mana
- Tongue of Wild Spaces: 2 mana spell, 5 mins/mana
- Whispers of the Grave: 2 mana spell, 5 mins/mana
- Consult the Spirits: 1 mana spell

## 8th level
- Ascendant Step: Levitate, 1 mana spell, 5 mins/mana
- Master of Myriad Forms: Disguise, 1 mana spell, 1 hr/mana
- Misty Visions: Image, 1 mana spell, 5 mins/mana
- Shroud: Invisibility, 1 mana spell, 1 min/mana

## 10th level
- Visions of Distant Realms: 2 mana spell, 1 hr/mana

## 12th level
- Celestial Wings: 2 mana spell, 5 mins/mana
- Demonic Wings: 2 mana spell, 5 mins/mana
- Vampiric Wings: 2 mana spell, 5 mins/mana

**Comment by mlenser** [comment]
Feats that enable spells to be cast at will have been realigned to a system

**Comment by Marcloure** [comment]
Winged racial feat grants wing at 8th level. Should those be aligned or are they ok since they are racial?

**Comment by mlenser** [comment]
I'll move Winged to 10th.
