### ISSUE TITLE
Unstable Polymorph WMS

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#299]
Wild Magic Surge's fourth option:
> You cast unstable polymorph augmented to baleful unstable polymorph on yourself.

Unstable Polymorph was removed a while ago. This should be changed or Unstable Polymorph should be re-added/re-worked. 

A quick fix is, having the working changed to - You are under the effects of the spell baleful polymorph. The type of creature is random or of the DMs choice.

**Comment by mlenser** [comment]
It should just be polymorph

**Comment by mlenser** [comment]
Wild Magic Surge no longer refers to unstable polymorph, which was removed. It not uses the polymorph spell

**Comment by wherfz** [comment]
Number 03 on the Chaos table is worded like so... 
You cast polymorph augmented to baleful polymorph on yourself. If you fail the saving throw, you turn into a sheep for the spell’s duration.
--
To make 04 different I would word it like this to keep the same theme.

> You cast polymorph augmented to baleful polymorph on yourself. If you fail the saving throw, you turn into a random creature or creature chosen by the DM for the spell’s duration.

**Comment by mlenser** [comment]
baleful polymorph is gone too

**Comment by mlenser** [comment]
Haven't pushed yet. Will push today.
