### ISSUE TITLE
Allow reacting to a spell after identifying it

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#300]
From the [Skills](https://www.kryxrpg.com/rules/skills) page, example of usage of Arcana:

> ***Identify an Arcane Spell***. If you are proficient with Arcana you can attempt to identify a spell from the Arcane power source. As a reaction, which you take when you see a creature casting a spell, make an Arcana check with a DC of 10 + double the mana expended to cast the spell.

While the description of [Counterspell](https://www.kryxrpg.com/themes/spells/counterspell) starts as:

> As a reaction, which you take when you see a creature within 60 feet of you casting a spell, you attempt to interrupt the spell.

Similarly, [Bend Luck](https://www.kryxrpg.com/themes/maneuvers/bend-luck) and [Deflect Spell](https://www.kryxrpg.com/themes/spells/deflect-spell) allow you to react to a spell (attack roll or saving throw) to defend yourself.

Problem is - we do want identification to require a reaction, at least when the player isn't instantly recognizing a spell but the GM wants to give the player a chance - because otherwise, it leads to players constantly rolling to identify every spell anyone casts, which slows down the game.

So, my suggestion is to edit all of these Identify options as follows:

> ... to cast the spell. After making this attempt, you can still use an ability to react to the spell, such as casting [*counterspell*](https://www.kryxrpg.com/themes/spells/counterspell) or using the [*Lucky*](https://www.kryxrpg.com/themes/feats/lucky) feat.

**Comment by mlenser** [comment]
https://www.enworld.org/threads/xanathars-guide-how-does-identifying-a-spell-counterspell-work.602800/

**Comment by DalenWBrauner** [comment]
The predominant solution I see in that thread is "just make a house rule". Some players prefer:
- All spells declared out in the open
- Spells can be passively identified with your Passive Arcana
- Spells can be passively identified if you know the spell / have the power source / have seen this caster cast it before
- You can identify a spell and Counterspell in the same reaction
- Counterspelling has to be blind; if you want identification, get a spotter
- Counterspelling has to be blind; spotters can't shout with their reaction (for some reason)
- "This is why we don't use Counterspell"
- (My personal favorite) Identifying spells is easy, but some characters can use a Bonus Action + Deception Check to appear to be casting a different spell

But these are all rules that DMs can build in. We have a bit more power here; at minimum, we can lampshade this discussion and have some optional rules listed adjacent to the Arcana section. At most, we can build in some feats and features that allow for multiple playstyles.

For example, we could add:
- Passive checks to spellcasting classes vs other spells from their power source. E.G. Acolytes can make passive Religion checks, Occultsists passive Occult checks, etc.
- - (Perhaps excluding Suffused)
- Giving Wizards the ability to identify spells without a reaction (perhaps some number of times per day)
- A feat or spell to allow spending a Bonus Action feat to Disguise Spell, as suggested above
- Adding a feat that grants "When you spend your reaction to a spell being cast, you can also choose to try to identify that spell as part of that reaction" (not a big fan of it but it could work)

I'm not sure that any/all of these properly solve the problem that Bacon Bits addresses, but I'm not sure we'll find a good 'one size fits all' solution.

**Comment by mlenser** [comment]
> All spells declared out in the open

That defeats a major portion of the skill system. Psionics, Arcana, Occult all become much less usefuly.
Not only that, it is completely illogcal. We've spent a few weeks now talking about how everyone casts differently. The idea that you'd know a spell right away is ridiculous.
I would _really really **really**_ encourage people to not make such a houserule.

> Spells can be passively identified if you know the spell / have the power source

We've spent a few weeks now talking about how everyone casts differently. It should not be automatic without some kind of skill involved unless you've seen that specific caster cast that specific spell and saw the effects or identified it.

**Comment by mlenser** [comment]
I think the best course of action:
- Counterspell should use the skill associated with the spell
- Identifying a spell through a skill should be a DC of 10 + mana, not 10 + mana x2
- Skills should use pseudo reactions. Wording like `If you are proficient with Arcana, you can attempt to identify a spell from the Arcane power source as it is cast. When you see a creature casting a spell, make an Arcana check with a DC of 10 + the mana expended to cast the spell. The check doesn't expend the your reaction, but you can't make the check if anything, such as the incapacitated condition or the *shock* spell, is preventing it from taking reactions. You are limited to identifying one spell per turn.`

Unrelated
- Counterspell should probably always be a check. (remove the augment and wording about auto countering). Bacon suggests removing the augment. I think this would bind it to the power sources system much better.

**Comment by Marcloure** [comment]
Just to add in, the way I use to do it is:

• You always know the spell's mana cost
• You need to roll to determine the spell (no action required)

**Comment by mlenser** [comment]
- The rules for identifying a spell have been adjusted so they do not take a reaction
- Counterspell reworked a bit to always be an ability check

**Comment by itamarcu** [comment]
> The rules for identifying a spell have been adjusted so they do not take a reaction

That's good and I approve of it! wording is a bit weird (posted in #typos channel) and personally I'd allow passive identification in many cases, but this is a good and elegant enough rule.

---

> Counterspell should probably always be a check. (remove the augment and wording about auto countering). Bacon suggests removing the augment. I think this would bind it to the power sources system much better.

This is a huge nerf to counterspell, and seems unjust to me, as requiring you to identify the spell to make sure you're not wasting your time and limiting identification to spells from your power source and a successful check.. those are already roadblocks. This is one of the core D&D spells that a lot of things are built around, so I'd like us not to be too hasty with making drastic decisions.

- Why remove the guaranteed counterspell in case it's a 2 mana spell or lower? What purpose does this serve? Is there anyone in any forum thread who advocated for it?

- This is going to anger a lot of players who relied on Counterspell, even more than the addition of identifying spells will. I guess they still get a "benefit" from this change in that their own spells are going to be harder to counter, but generally, players are the ones who cast more counterspells.

- Why reduce it from 10+M×2 to 10+M? It's a bit simpler, but this makes countering an epic meteor swarm with a flimsy counterspell much easier, which seems like bad flavor to me.

- Dispel Magic is no longer symmetric to Counterspell. It still has auto-dispel for spells that cost 2 or less, but also its DC for other spells is higher for some reason, and is 10 + M + C (where C is creature's casting ability).

- Would you consider granting the counterspeller/dispeller a bonus or advantage on the roll, if they have identified the spell?

**Comment by mlenser** [comment]
> Why remove the guaranteed counterspell in case it's a 2 mana spell or lower?

Because I think all countering should be a check. Countering a spell is powerful. It is basically mana burn in that it reduces the enemy's mana, preventing a huge negative for the party, and effectively wasting the creature's turn. It should not be easy.

> This is going to anger a lot of players who relied on Counterspell

Firstly, I've never had a party rely on counterspell. And if its so essential for a party in your experience then that should tell you how ridiculously powerful it is.

Change always angers people. If I made design decisions based on those people then my system wouldn't exist. If the rules are not sufficient then we should dicuss here. If people are angered enough they can also make their own rules.

> Why reduce it from 10+M×2 to 10+M
The spell already has to be identified (which is easy) so this is a second check, reducing the overall success of knowing+countering a spell.
The chance to succeed also was drop drastically. Against 5 mana it was d20+5 vs 20. That's a 25% chance. But if we allow advantage after you identify the spell then this could go back to 10+ 2x mana

> Dispel Magic is no longer symmetric to Counterspell.

Thought about this last night too. I need to change it there.

> Would you consider granting the counterspeller/dispeller a bonus or advantage on the roll, if they have identified the spell?

Yes, I thought about this.

**Comment by DalenWBrauner** [comment]
The current wording for identifying spells is ambiguous in one case. While it explicitly states:
> Alternatively, as an action, you can identify an ongoing spell from its effects or a spell in a spellbook.

It also says:
> **_Identify an Arcane Spell._** [...] you can attempt to identify a spell from the Arcane power source.
> Make an Arcana check [...]. The check doesn’t expend your reaction, but [...]

Does this mean that my "free" per-round identification check **cannot** be used on ongoing spells? Is the intention that this "free" check only applies to spells **as they are being cast?**  If so, then we should improve the wording to explicitly say so, e.g.:
> You can make this check the moment you observe someone cast a spell. This check doesn’t expend your reaction, but [...]
> If you observe the ongoing effects of a spell, or a spell in a spellbook, you instead make this check as an Action.

**Comment by mlenser** [comment]
- **Rules**
  - **Skills**
    - The wording for identifying a spell has been cleaned up [#300](https://github.com/mlenser/kryx-rpg-issues/issues/300)
- **Themes**
  - **Antimagic**
    - Counterspell and Dispel Magic ability check calculation and DC calculation reworked [#300](https://github.com/mlenser/kryx-rpg-issues/issues/300)
    - Improved Abjuration feat removed as the ability to get advantage on these spells now is identifying the spell [#300](https://github.com/mlenser/kryx-rpg-issues/issues/300)

Math: https://anydice.com/program/1bea5

Summary: 50% chance to stop a spell cast by a caster of equal level when you cast counterspell at the same mana as the spell. 75% chance to stop the spell if you identify the spell first.

**Comment by DalenWBrauner** [comment]
So with the addition of Advantage:
* You can't get this advantage unless you can identify the spell.
* You can't identify the spell unless you're at least capable in that skill.
* Identifying the spell is _"free"_, (either not-a-reaction, or an extra action to Dispel an ongoing spell,) so for the average player with capability, there's a roughly 50% chance you'll pass the check and obtain that advantage, right?

So this should translate to:
* 50% chance to Defeat the Spell if you're not capable in that power source.
* Starting at roughly 60% if you're capable, but have a low bonus in that Skill
* Reaching up to 75% if you have a high bonus in that Skill

These are all back-of-my-napkin calculations, but I think that looks good! You can directly improve your odds of Counterspelling by improving your skill in the relevant power source. I like that a lot.

**Comment by mlenser** [comment]
> You can't identify the spell unless you're at least capable in that skill.

You have to be proficient

**Comment by mlenser** [comment]
> there's a roughly 50% chance you'll pass the check and obtain that advantage, right?

Much higher than 50%. Prof+ability vs mana cost. At tier 2 that's d20+3+(3-4) vs dc 12.

**Comment by DalenWBrauner** [comment]
Ahh, so I'd say those two facts balance each other out. You _have_ to invest enough to get Proficiency in the skill to get that advantage, but once you do, you're much more effective at counterspelling. Doesn't scale as linearly as I estimated, but that's totally fine. This looks good!
