### ISSUE TITLE
Survivalist theme needs clarity and direction

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#301]
I have several problems with the current contents:
- Survivalist. Is Survival the Nature aspect of surviving in the wild? If so that should be a bigger focus. If not this feat should be removed
- Perception/Insight should decide to live in Survivalist or Divination

**Comment by mlenser** [comment]
I cleared up the Perception problem by moving all Perception stuff from Divination. But more clarity is needed around Survivalist and Survival's definition.

**Comment by itamarcu** [comment]
#### Suggestion for the theme description

Survival is the basest of instincts, the force that keeps creatures going on even through the worst conditions, and keep living despite everything. The Survival theme focuses on outdoor survival, travel in the wilderness, enduring natural dangers, and similar rugged activities.

Spells from the Survival theme allow you to climb or swim with ease, trespass difficult terrain, survive in harsh conditions, travel through dangerous areas, spot traps, detect imminent danger, escape effects that restrain you, and keep yourself healthy.

**Comment by mlenser** [comment]
Survival theme removed
- Alert moved to general feats
- Ancestral Hearth moved to the Spirit theme
- Climb and Climbing Potion remain in the Alteration theme
- Danger Sense and Danger Sense Potion remain in the Fate theme
- Dungeon Delver moved to general feats
- Fluid Footwork remains in the Skirmish theme
- Freedom of Movement moved to the Alteration theme
- Mobile remains in the Skirmish theme
- Path of the Tenacious moved to the Alteration theme
- Purify Food and Drink remains in the Life theme
- Sprint remains in the Beast theme
- Steady Eye moved to the Marksmanship theme
- Striding and Springing remains in the Alteration theme
- Survivalist moved to the Plants theme
- Tough moved to general feats
