### ISSUE TITLE
Spiritual Weapon and Crawling Claw

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#302]
Both deal the same damage, but Crawling Claw can be cast at 120 ft., moves up to 60 feet per turn, and has other benefits. It has the downside of being destructible, but if a creature spends resources to deal twice as much damage as the the caster's hp, then that is not so bad.

**Comment by mlenser** [comment]
Crawling Claw, Kinetic Greasp, and Force Hand are all the same power level and versatility level.

Force Sword and Spiritual Weapon are o nthe same power level, but have less versatility.

The first 3 should not be weaker because the other 2 are more narrow in their flavor.

**Comment by Marcloure** [comment]
Sure, that is not the issue. We can start by making the Weapon spells move as much as those other spells.

My friend said he'll see if he can think of something that a weapon can do, but I don't think we should force things to make these spells closer.

**Comment by mlenser** [comment]
Note: Several of these spells were incorrectly 2 mana. All should be 1 mana and that'll be fixed.

I'll also adjust the hands/claws to be 60 feet as they can also move 60 feet when cast, so 60+60=120 which is the standard range. 120+60=180 which is not standard.

**Comment by Marcloure** [comment]
Aren't strong control spells at 2 mana?

**Comment by mlenser** [comment]
Yes, but grappled isn't a strong control spell.

**Comment by Marcloure** [comment]
You are right, it grapples, not restrains.

Speaking of which, Earthen Grasp restrains, deals damage, and is 1 mana.

**Comment by mlenser** [comment]
Ya, fixing that already.

**Comment by mlenser** [comment]
- Earthen Grasp changed from 1 mana to 2 mana as it imposes the restrained condition which is too strong for 1 mana
