### ISSUE TITLE
Change definition of Monk Weapons

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#303]
### [Current definition](https://www.kryxrpg.com/character/classes/psionicist/monk#martial-arts):
> Your practice of martial arts gives you mastery of combat styles that use unarmed strikes and monk weapons, which are shortswords, quarterstaffs, and any simple melee weapons that don’t have the two-handed or heavy property.

### Problems:
- This doesn't allow darts and shuriken (simple thrown weapons), which fit monks
- This doesn't allow blowguns (simple ranged weapon, deals 1 damage), which fit monks
- This doesn't allow improvised weapons, which certain styles of monk would like
- This doesn't allow kamas, kukris, or scimitars, which are identical to shortswords (kamas are thematically fitting; kukri and scimitar might not be)
- This doesn't allow natural weapons. I think allowing you to use hooves or claws as an attack doesn't break anything, so we might as well add an option to enable them.

#### Note
The recent Classes Variants UA of 5th edition offers this:
> You can use this feature to define your monk weapons, rather than using the definition in Martial Arts. You practice your martial arts with specially chosen weapons, which become monk weapons for you. You can choose a number of weapons to be your monk weapons equal to 5 + your Wisdom modifier (minimum of five weapons). The chosen weapons must meet the following criteria:
> - The weapon must be a simple or martial weapon.
> - You must be proficient with the weapon.
> - The weapon must lack these properties: heavy, special, or two-handed.

This seems pretty good to me. Do note that it allows using a hand crossbow or a whip (if you got proficiency), but you could already get those or even get a longbow or a warhammer if you take the [Weapon Master](https://www.kryxrpg.com/themes/feats/weapon-master) feat (which I do not think needs to change). However, having to pick which weapons count as monk weapons for you seems weird, and makes less sense when multiclassing isn't an option, and it's already at least 8, so I think it's more elegant to just make all viable weapons monk weapons.

### Suggested solution

1. Change the definition to:
> Your practice of martial arts gives you mastery of combat styles that use unarmed strikes and monk weapons, which are any weapons that meet the following criteria:
> - The weapon must be a simple or martial weapon.
> - You must be proficient with the weapon.
> - The weapon must lack these properties: heavy, special, or two-handed.

2. Add a psychic focus (theme: vanguard) that allows you to use improvised weapons as monk weapons, and grants you proficiency with them.

2. Add a psychic focus (theme: beast) that allows you to use natural weapons as monk weapons.

3. Change monk starting weapon proficiencies from "simple weapons and shortswords" to "simple weapons, shortswords, and kamas".

**Comment by mlenser** [comment]
> - This doesn't allow improvised weapons, which certain styles of monk would like
> - This doesn't allow natural weapons. I think allowing you to use hooves or claws as an attack doesn't break anything, so we might as well add an option to enable them.

2/5 of your main posts are not covered by the proposed solution.
____________

Monk weapons are only useful for Martial Arts.


The current definition is:
- Club
- Dagger
- Hammer
- Hatchet
- Katar
- Mace
- Pick
- Quarterstaff
- Sai
- Sickle
- Spear
- Shortswords

I don't think this should be expanded to martial weapons beyond flavor variants of shortsword like Kukri/Scimitar.
It should include several of the simple ranged weapons, yes.

**Comment by itamarcu** [comment]
We could simply add natural weapons by removing:
> - The weapon must be a simple or martial weapon.

For improvised weapons, the problem is that a monk just doesn't have proficiency with them by default. Unless we change that (which is an option!), there would have to be a "tax" of some sort, a choice they make that gives them improvised weapons. Psychic Focus seemed the easiest to implement and doesn't cost too much, and a 2nd level feat could potentially work too. As you said before, it's just too hard to add fighting styles to the monk otherwise.

> I don't think this should be expanded to martial weapons
> I'd rather see the current definition + light weapons + simple ranged.

I pretty much agree, but my suggestion and yours are actually equivalent! The monk only has proficiency in simple weapons (+shortsword), so my suggested requirement of having proficiency in the weapon should automatically prevent the monk from using any martial weapon. The only way (that I know of) for monks to gain proficiency in new weapons is through the Weapon Master feat, which specifically states they become monk weapons (and allows you to get nonstandard monk weapons through it).

Requiring proficiency is basically identical to saying "simple melee weapons, light weapons, and simple ranged weapons". And of course, either way we need to add "as long as it isn't two-handed or heavy or special".

**Comment by Paulorpribeiro** [comment]
For natural attacks only, I thinl the idea of having that tied to the psychic focus interesting.
"Psychic focus: Beast - while you have this psychic focus active, you can consider any natural weapon attacks you have and acquire through feats or features as monk weapons"

**Comment by mlenser** [comment]
- **Monk**
  - Monk weapons redefined to quarterstaffs, light weapons, and any simple weapons that don’t have the two-handed or heavy property [#303](https://github.com/mlenser/kryx-rpg-issues/issues/303)
  - Monk Martial Arts feature enables natural weapons to trigger unarmed strikes [#303](https://github.com/mlenser/kryx-rpg-issues/issues/303)
  - Monk Flurry of Blows is only unarmed [#303](https://github.com/mlenser/kryx-rpg-issues/issues/303)

____________

Improvised weapons, as always are handled via the GM. They should generall fall under the `simple weapons that don’t have the two-handed or heavy property` specification as long as they meet those requirements.
