### ISSUE TITLE
Bloodseeker (Suggestion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#305]
> ### Bloodseeker
>**8th level feat - *Blood, Beast***
>*Prerequisites: spellcasting or a natural weapon*
> You can sense blood in your vicinity. You know the location of any Small or larger creature with a heartbeat within 60 feet of you (you cannot sense creatures such as undead or constructs this way). You know if any such creature is missing more than half of its hit points.

**Comment by mlenser** [comment]
Should be based on scent

**Comment by itamarcu** [comment]
My intention was to leave it ambiguous on purpose - for Beast users it would be based on scent, and for Blood users it would be based on blood magic (magically sensing heartbeat within nearby creatures).

If you'd rather make this less magical, I think I'd restrict this to smelling creatures that are missing hit points (as you can't smell the blood inside their veins):

> ### Bloodhound
>**4th level feat - *Beast***
>*Prerequisites: the [Bestial Senses](https://www.kryxrpg.com/themes/feats/bestial-senses) feat*
> Your heightened sense of smell lets you sniff blood in your vicinity. You know the location of any living creature within 120 feet of you that has blood and is missing any hit points, if the smell could reach you. You also know if any such creature is missing more than half of its hit points.
> In addition, you have advantage on Nature checks to track trails of blood.

**Comment by mlenser** [comment]
Bloodhound added as a 6th level feat
