### ISSUE TITLE
Water Awareness (Suggestion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#306]
> ### Water Awareness (or "Dowser"?)
>**4th level feat - *Water***
>*Prerequisites: spellcasting*
> You can sense water in your vicinity. You know the location of objects containing water, at least the size of a bottle, within 30 feet of you. You also know the location of any large body of water - such a lake, a stream, or a sewer system - within 300 feet of you.

**Comment by mlenser** [comment]
How would you know of objects containing water if they are closed? And the larger usage of this is covered by the locate water spell.

I'd say this shouldn't be added

**Comment by itamarcu** [comment]
You're right - Locate Water is good enough, and it's even a ritual. I'll cancel this suggestion as I can't think of a good enough reason to let people sense water in bottles and barrels around them.
