### ISSUE TITLE
Heat Sense (Suggestion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#307]
> ### Heat Sense
>**4th level feat - *Fire***
>*Prerequisites: spellcasting*
> You can sense heat in your vicinity. You know the location of Small or larger creatures within 30 feet of you if they are at least as warm as a human body. You also know the location of any fire at least as large as a campfire if it is within 300 feet of you.

**Comment by mlenser** [comment]
This seems unrelated to fire. This is like predator.

Not sure there is really a theme to capture this besides some kind of aberration theme.

**Comment by itamarcu** [comment]
I was imagining literal magic powers that let you sense fire - not infrared vision but more like a sixth sense that lets you know when there's a big fire nearby or when there is a torch on the other side of the wall or when a warm-blooded creature is invisibly stalking you.

It's a bit exotic, and less drawn from media - but the basic idea is "you're so good with fire magic that you can sense fire and heat around you", just like my intention with other spells (water sense for example).

---

Predator-like "infrared vision" is a different version of this, and we can add it, but I would make it quite different:

> ### Thermal Vision
>**6th level feat - *Beast***
> You can see infrared light, letting you perceive hot and cold areas. While a creature or object is within 60 feet of you and in your field of vision, you can roughly sense its temperature. This allows you to see creatures that are invisible or in darkness, as long as they are warmer than their immediate surroundings (for example- a human is warm, but a vampire isn't).

**Comment by mlenser** [comment]
> You know the location of Small or larger creatures within 30 feet of you if they are at least as warm as a human body.

This is predator vision.

**Comment by mlenser** [comment]
I don't see the flavor basis for the original suggestion and I think the Predator-like vision is really more like an aberration (as they were aliens).

Also, I'm wary of heat vision. Infravision was removed for reasons. http://seankreynolds.com/rpgfiles/rants/infravision.html

**Comment by itamarcu** [comment]
Predator-like vision isn't just for aberrations - see [this article about animals that have it](https://sciencing.com/animals-can-see-infrared-light-6910261.html), for example.

> http://seankreynolds.com/rpgfiles/rants/infravision.html

That's a good article, thanks. I still think infravision / heat vision (the latter makes me think of shooting beams of heat from your eyes, because it's a badly named ability of superman) has place in the game - the questions that it raises can just be answered by the GM when it's relevant, and this is specifically a *weaker* version that only lets you see the location of a creature - a blur of heat - so you still have disadvantage if you can't see the target normally.

Generally, it's going to be very similar to tremorsense, with a slightly different limitation. Similar questions can be asked with Tremorsense - does Mirror Image work against it? does Earthquake disable it? do you need to be barefoot?

**Comment by mlenser** [comment]
This could potentially work for the right creature, but I don't think this should be available to everyone. So perhaps in the future if there is a creature with a basis for having heat sense we can revisit it for that creature.
