### ISSUE TITLE
Eyes of Light (suggestion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#308]
> ### Eyes of Light
>**4th level feat - *Light***
>*Prerequisites: spellcasting*
> Your eyes glow brightly, as your affinity to light grows stronger. You gain the following benefits:
> - You shed bright light in a 10-foot radius and dim light for an additional 10 feet, as long as you keep your eyes open.
> - You have resistance to radiant damage.
> - You cannot be blinded by bright light.
> - You always know the direction of the sun from you, as well as the direction to any particularly large sources of light within 300 feet of you, such as a wildfire or a *wall of light* spell.

**Comment by mlenser** [comment]
This feat has weird flavor that I can't really substantiate in any media.

- Light out of eyes should be a cone
- Light out of eyes is unrelated to being resistant to radiant
- Always knowing direction to light is unrelated to being resistant to radiant and has the same problems as the discussion about keen mind

I think this shouldn't be added without a large flavor and mechanical rework.

**Comment by mlenser** [comment]
Closing as it needs a large flavor and mechanical rework or else it should be abandoned.
