### ISSUE TITLE
Psychic Awareness

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#309]
> ### Psychic Awareness
>**14th level feat - *Mind***
> You have expanded your awareness of intelligent minds, and can feel them resonate in your. You can sense the location of creatures within 60 feet of you, as long as they have an Intelligence of -1 or more.

(Yeah.. this one is simple and straightforward. It's intended to be like [Sense Minds](https://www.kryxrpg.com/themes/spells/sense-minds), but better (can work through walls), and at a very high level.)

**Comment by itamarcu** [comment]
Alright, that's acceptable. If it's a permanent Sense Minds it could probably be reduced to 8th level.

I'd prefer this to be the effects of Sense Minds over "you can case Sense Minds at will without expending mana", because that spell is a concentration spell, and I think the psychic should constantly have this ability on, not just when not concentrating on something else. Plus, it would be annoying to need to remember to cast this spell again every five minutes outside combat, unless your GM just accepts your saying "I cast this spell every five minutes, let's just assume it's always on".

Still, either one of these would be a fine feat, so go with whichever option you feel works best.

**Comment by mlenser** [comment]
Sense Minds added as a 6th level feat
