### ISSUE TITLE
Become the Tide spell suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#310]
It's a water version of Wind Walk:

**Become the Tide** (Ride the Tide?)
_1 hour/mana_
As you spend 1 minute to cast this spell, a creature that you can see within 30 feet assumes a river form for the duration, appearing as a stream of water. While in this stream form, a creature can breathe underwater, has swim speed of 300 feet, and has resistance to damage from nonmagical attacks. The only actions a creature can take in this form are the Dash action or to revert to its normal form. Reverting takes 1 minute, during which time a creature is incapacitated and can’t move. Until the spell ends, a creature can revert to stream form, which also requires the 1-minute transformation.

If a creature is in stream form and swimming when the effect ends, the creature ascends 60 feet per round for 1 minute until it surfaces. If it can’t surface after 1 minute, the creature starts to drown if it can't breathe.

**Augment**
You can target two additional creatures for each additional mana expended. The creatures must be within 30 feet of each other when you target them.

**Comment by itamarcu** [comment]
I like it! small nitpicks:

1. Should specify a willing creature. 

2. I think it would be more thematic if you become the *tide*, the waves, something visible moving on the surface of the water - and not just a flow of water moving through the water. The latter situation can still be useful, though, so I suggest that:

> has swim speed of 300 feet

be changed to:

> has swim speed of 150 feet when underwater and 300 feet when at the surface of the water

**Comment by Marcloure** [comment]
> Should specify a willing creature.

This needs to be fixed in Wind Walk as well

> has swim speed of 150 feet when underwater and 300 feet when at the surface of the water

I don't see need or reason for this, but if you think it's more fitting...

**Comment by itamarcu** [comment]
Mechanically, I think it makes the spell a bit more interesting. If you go along the surface of the water, you can be spotted, but you'll move faster - this gives the players an interesting decision to make.

Flavorfully - it's "become the tide" or "wave walk". It's not "become the underwater current" :P

Plus, I find it hard to believe there is any situation in which moving at a speed of 150 feet underwater is not good enough.

**Comment by mlenser** [comment]
Water Glide added as a 2 mana spell
