### ISSUE TITLE
Counterspell Augment?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#311]
While the discussion in #300 lead to the removal of guaranteed spell-counters, I wonder if there is still room for spending More Mana in exchange for reducing the difficulty of the check. Something along the lines of:

> **Augment**
> You can expend additional mana to lower the DC of the check by 1 for each additional mana expended.

I believe +1 per mana does not imbalance the check or make it too easy- it simply means that mana can be spent to "match" higher-level spells. The difficulty of a 5-mana spell can be matched with a 5-mana counterspell.

I would think channeling 5 mana into a single counterspell against a 1 mana spell should be _allowed_, even if it's largely a waste, but if we preferred not to allow that, we could add:
> You cannot reduce the DC below 11 in this way.

Of course, there's a question that comes attached to that:
Should the counterspeller know the DC of the task (i.e. the manacost of their opponent's spell) before they cast counterspell? Or at least before deciding to augment? Or does learning the manacost require spell identification?

Please avoid extended discussion on the changes in #300.

**Comment by mlenser** [comment]
See #300. Counterspell and Dispel Magic scale with mana expenditure now.

**Comment by DalenWBrauner** [comment]
I'm not sure it's clear you can "upcast" Dispel Magic and Counterspell, even though the wording accounts for the mana you spent. Most spells, as I understand, cannot be "upcast" in this way without an explicit augment listed.

Perhaps something as simple as:
>You can expend additional mana when casting this spell, increasing the bonus to your arcana check.
