### ISSUE TITLE
Some companion forms are too strong

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#313]
Aren't some companions too strong? Phoenix has a lot of powerful resistances (including to weapon attacks), fly 90 ft., fire form, rebirth, etc. Any other elemental form has many of this as well, the resistances specially are very powerful for any level

**Comment by mlenser** [comment]
All companions are meant to be used for both options like hexenbeast or wild shaper, spells like call beast, and feats like animal companion.

Companions are meant to scale monsters up and down as needed. If some are too powerful at certain tiers or too powerful then they should be adjusted.

**Comment by Marcloure** [comment]
Considering #420 , what about cutting the hp of monsters with weapon resistances and many condition immunities by 30~40%? Though that wouldn't impact Fuse Form, since it uses the character hp...

**Comment by DalenWBrauner** [comment]
Just noting that #500 and #502 are related to this issue.

**Comment by mlenser** [comment]
?

**Comment by DalenWBrauner** [comment]
I was just going through older issues that were still open. If discussion pops up again for this one, I thought it'd help to connect those for reference.

**Comment by mlenser** [comment]
Closing this as this isn't a major issue. These forms are only available to the Suffused.
