### ISSUE TITLE
Psychic Focus glitch?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#314]
The Psychic Focus feature for the Psion appears to be incorrectly listed in the Table of Contents as having some additional benefit at 3rd Level. I think this is supposed to be 17th level.

![image](https://user-images.githubusercontent.com/3477032/83575245-18531280-a4fd-11ea-8a36-908a577f0819.png)

![image](https://user-images.githubusercontent.com/3477032/83575321-3f114900-a4fd-11ea-81df-addca3434cd9.png)

**Comment by mlenser** [comment]
fixed, will go out on the next release
