### ISSUE TITLE
Allow resting when needed

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#316]
The current [Adventuring](https://www.kryxrpg.com/rules/adventuring) rules specify:

> A short rest is a period of downtime, at least 15 minutes long, during which a character does nothing more strenuous than eating, drinking, reading, and tending to wounds.

and

> A character can’t benefit from a short or long rest more than once every four hours, can’t benefit from more than one long rest in a 24-hour period, and a character must have at least 1 hit point at the start of the rest to gain its benefits.

This is problematic because there are many valid situations during which a character might want to rest sooner than 4 hours after their previous rest. Example:

* Tordek wakes up at 8 AM, eats breakfast, and heads into the dungeon at 8:30. After exploring for an hour and getting into two fights, it's now 10:00, and he wants to take a short rest. He's forced to wait two more hours before being allowed to do so - it would have been better for him to head into the dungeon at 12:00 - waiting four hours after a long rest - to allow himself the opportunity to short-rest when he needs it without needing to spend excess time in a dangerous area.

The rule needs to be tweaked to allow this. My suggestion:

> A character can’t benefit from a short ~or long~ rest more than once every four hours, can’t benefit from more than one long rest in a 24-hour period, and a character must have at least 1 hit point at the start of the rest to gain its benefits.

However, the rules might be meant to discourage something like short-resting immediately after waking up, to regain a few extra hit dice (since you get 25% of them back). Therefore, maybe it's better to make it more flexible:

> A character can’t benefit from a short or long rest more than once every four hours, and can’t benefit from more than one long rest in a 24-hour period. The GM may allow resting soon after a period of exertion, ignoring this restriction.

**Comment by DalenWBrauner** [comment]
Perhaps:
> A character can’t benefit from more than one long rest in a 24-hour period, and can’t benefit from any rest more than once every four hours without a period of exertion or strenuous activity at the GM's discretion.

**Comment by mlenser** [comment]
## Short rest
> A character can’t benefit from more than two short rests before they take a long rest and a character must have at least 1 hit point at the start of the rest to gain its benefits. Once a character rests, it can’t rest again unless it waits four hours or exerts itself with strenuous activity, at the GM’s discretion.

## Long rest
> A character can’t benefit from more than one long rest in a 24-hour period and a character must have at least 1 hit point at the start of the rest to gain its benefits. Once a character rests, it can’t rest again unless it waits four hours or exerts itself with strenuous activity, at the GM’s discretion.
