### ISSUE TITLE
Power source wording (Wording)

### ISSUE THREAD

**Issue by DiBastet** [mlenser/kryx-rpg-issues#317]
**Issue:** The wording on the Power Source ability might imply you don't need to know a theme to learn a spell.

**Original:** "Power Source: You can learn spells from themes in [your] power source."

**Suggested wording:** "Power Source: You can learn spells from themes _**you know**_ in [your] power source."

**Comment by mlenser** [comment]
Also clean `Spells are divided into six power sources. Characters can learn spells from one power source.`

**Comment by mlenser** [comment]
Wording cleaned up, will go out on the next release
