### ISSUE TITLE
Booming Weapon Spell

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#319]
**Booming Weapon** _Sound Theme, maybe Storm_
_1 mana_ 
_concentration, 10 minutes/mana_
As a bonus action, a weapon you touch echoes with booming energy. For the duration, the weapon deals an extra 1d6 thunder damage when it hits.

Alternatively, you can touch a quiver containing arrows or bolts, granting the ammunition pulled from it the same effect. The spell’s magic ends on a piece of ammunition when it hits or misses.

Augment
You can increase the damage by 1d6 for each additional mana expended and an additional 1d6 for every other additional mana expended.

**Comment by mlenser** [comment]
Booming Weapon added as a 1 mana spell to Sound and Storm
