### ISSUE TITLE
Sonic Strike Feat

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#323]
Currently, the Storm theme has:
> **Thunderbolt Strike**
_6th_
When you hit a Huge or smaller creature with a weapon attack or deal lightning damage to a Huge or smaller creature, you can also push it up to 10 feet away from you.

The flavor of pushing someone or objects backwards is more commonly associated with sonicbooms than lightning strikes, and Thunder damage moreso than Lightning. I would suggest changing this to:

> **Sonic Strike**
_6th_
When you hit a Huge or smaller creature with a weapon attack or deal thunder damage to a Huge or smaller creature, you can also push it up to 10 feet away from you.

And place it in both the Storm and Sound themes.

**Comment by mlenser** [comment]
Thunderbolt Strike renamed Thunderous Strike and now uses thunder damage as the condition to push
