### ISSUE TITLE
Continued Thunderwave

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#324]
Similar to #315, I think we can add a Continuous augment to Thunderwave.

>**Rolling Thunder**
You can expend 1 additional mana so that the sound crashes around you continuously. The duration changes to 1 minute/mana, concentration and the sounds spread out from you in an aura shaped as a sphere. Until the spell ends, the aura moves with you, centered on you.
>
>Whenever a creature enters the area for the first time on a turn or starts its turn there, it must make the Fortitude saving throw. Additional augments to the damage increase the damage by 1d10 for each additional mana expended, instead of the normal increase.

Also, the current text of Thunderwave that reads
> is deafened for the duration

should probably be changed to
> is deafened for 1 minute

**Comment by mlenser** [comment]
Thunderwaves added as an augment to Thunderwave
