### ISSUE TITLE
Protection from Sound Spell

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#325]
Based on [Protection from the Storm](https://www.kryxrpg.com/themes/spells/protection-from-the-storm):

>**Protection from Sound**
_1 mana
1 hour/mana_
As an action, you have resistance to thunder damage for the duration.
>**Augment**
You can augment this spell with the following options, expending mana for each option.
You can target one additional willing creature you can touch or see within 60 feet for each additional mana expended. The creatures must be within 30 feet of each other when you target them.
>**Immunity.** You can expend 2 additional mana so the creature is immune to thunder damage.

>**Dampen Sound**
_1 mana_
As a reaction, which you take when you take thunder damage, you gain resistance to thunder damage until the start of your next turn.

>**Augment**
You can expend 1 additional mana to trigger the spell when a creature that you can see within 60 feet takes thunder damage. The creature gains the resistance instead.

**Protection from Sound** obviously belongs in the Sound theme, but could be in Storm as well.

**Protection from the Storm** should probably also be modified to protect only from Lightning damage.

**Comment by mlenser** [comment]
Sond theme is removed #327
