### ISSUE TITLE
Frost Trinket Cantrip

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#326]
**Frost Trinket**
_10 minutes_
As an action, you conjure an object of solid, magical ice in a shape of your choosing within 30 feet. The item created cannot exceed 1 cubic foot in volume, and does not melt unless its duration expires or it is exposed to extreme heat or a flame. Objects created in this manner may be used as tools, but they are too fragile to be extensively used.

They are also too fragile to be used as weapons except for arrows, bolts, bullets, and darts (casting this spell will create up to three of such at once).

**Comment by DalenWBrauner** [comment]
(Cleaned up the first sentence)

**Comment by Paulorpribeiro** [comment]
I think it would be nice to add that if you cast the spell again, the first immediately melts

**Comment by DalenWBrauner** [comment]
Interesting... the [Trinket](https://www.kryxrpg.com/spells/trinket) cantrip doesn't specify you can only have one at a time. But it used to, right? Or am I imagining things?

I'll add in the bit about melting when its duration expires though, thanks!

**Comment by Paulorpribeiro** [comment]
I don't know if it did, but it should! Since cantrips are free to cast, you may literally cast a hundred of small trinkets before the first one expires. If not one at a time, at least a text similar to prestidigitation's "can maintain 3 effects at a time" should be added to both this and trinket cantrip

**Comment by DalenWBrauner** [comment]
I'm pretty sure it used to- I'll go ahead an make a seperate issue for it.

**Comment by mlenser** [comment]
Frozen Trinket added as an Ice cantrip
