### ISSUE TITLE
Ice Sculpture Spell

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#328]
> **Ice Sculpture** (2 Mana)
> _4 hours_
> 
> As you spend 1 minute to cast this spell, you shape and conjure magical ice into the form of a solid object of your choosing. The object is created within 60ft, and must be no larger than a 5-foot cube, or a 10-foot cube if you have a nearby volume of ice or snow. It does not melt unless its duration expires or it is exposed to extreme heat or a flame.
>
> Augment
> You can increase the cube by 5 feet for each additional mana expended.

Inspired by [Trinket](https://www.kryxrpg.com/spells/trinket), [Shadowy Creation](https://www.kryxrpg.com/spells/shadowy-creation) and [Fabricate](https://www.kryxrpg.com/spells/fabricate). Lacks a lot of their functionality, aside from flexibility in shape, a more consistent duration than Shadow Creation, and an explicit environmental bonus just to give it something unique.

**Comment by itamarcu** [comment]
I like this! I'd change "snow" to "snow, ice, or water".

**Comment by DalenWBrauner** [comment]
It should definitely include ice! I'll edit that in.

I think access to water would be too significant of a buff, seeing how much more prevalent water is, and how much more variable its temperature can be. As a DM, I'd allow near-freezing water, but I wasn't sure if that was worth including (or how to phrase it).

**Comment by DalenWBrauner** [comment]
I set it to 4 hours instead of 1, as Shadowy Creation lets basic raw materials last for 12.

**Comment by mlenser** [comment]
Ice Sculpture spell added
