### ISSUE TITLE
Add alternative to Metamorphosis, which uses Power Surges

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#329]
(after a length discussion on Discord, here's the end result)

Current version of Metamorphosis:

> You take the visage of your origin form. As a bonus action, you undergo a transformation. For 1 hour, you gain the following benefits:
> 
> - You gain a flying speed of 60 feet.
> - You emanate an aura of menace in a 30-foot radius. The first time any enemy creature enters the aura or starts its turn there during a battle, the creature must succeed on a Will saving throw or become frightened of you for 1 minute or until it takes any damage. While frightened by this feature the creature has disadvantage on saving throws against spells you cast and attack rolls you make against the creature have advantage.
> 
> Once you use this feature, you must finish a long rest before you can use it again.

Suggested new version:

> You take the visage of your origin form. As a bonus action, you undergo a transformation. For 1 hour, you gain the following benefits:
> 
> - You gain a flying speed of 60 feet.
> - You emanate an aura of menace in a 30-foot radius. The first time any enemy creature enters the aura or starts its turn there during a battle, the creature must succeed on a Will saving throw or become frightened of you for 1 minute or until it takes any damage. While frightened by this feature the creature has disadvantage on saving throws against spells you cast and attack rolls you make against the creature have advantage.
> 
> Alternatively, you can let loose the magic that suffuses your body. As a bonus action, you become overflowing with magical energy for 1 minute. Choose a theme that you know. At the end of each of your turns, you can activate your Power Surge as if you just expended 2 mana to cast a spell belonging to that theme.
> 
> Once you use this feature, you must finish a long rest before you can use it again.

(note - if this is too weak, the "as if you expended 2 mana" part can be increased to a higher amount, or you can have it trigger both at the start and at the end of your turn)

**Comment by itamarcu** [comment]
Thinking about this some more, perhaps it's not the best idea. This is basically a 1-minute super buff, and the 20th level feature is very similar. It would be better if one of them was more passive and long-term. Plus, with the abundant power you can easily cast two spells every turn and react every round, for 3 surges per round

**Comment by mlenser** [comment]
Closing this since we think it's not the best option. I can see adjusting Metamorphosis, but another 1 minute "I win button" isn't the right direction.

Lets see where we get with https://github.com/mlenser/kryx-rpg-issues/issues/333 or feel free to create a new suggestion to replace metamorphosis.
