### ISSUE TITLE
Fix Power Surge to apply when you spend stamina (for Battleragers)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#330]
Power surges meant to trigger when you spend stamina to use a maneuver. The feature description mentions them but the actual effects depends on mana and not stamina.
> The magical energy flowing through your veins often seeps out. Whenever you expend energy to cast a spell or use a maneuver, the magic within erupts from you. When you gain this feature choose a default theme to use when you use a spell or maneuver from a theme not listed below. The magic seeps out in a way based on the theme of the spell cast or of your chosen default theme:
> 
> **Acid**. Acid spreads out from you. Up to 3 creatures of your choice that you can see within 30 feet of you take acid damage equal to twice the mana expended.
> 
> ...etc...

The effects of such surges need to depend on the stamina, somehow. It should be noted that the value of stamina is lower than the value of mana, so perhaps the calculation should address this.

**Comment by mlenser** [comment]
Wait for #343

**Comment by itamarcu** [comment]
Just to confirm - whatever feature ends up being created, it should work with both mana and stamina, and if it works with "value per mana" - the value per stamina should be about 1/3 of it, right? (now relevant, because of #346 )

**Comment by mlenser** [comment]
Correct

**Comment by mlenser** [comment]
Power Surge reworked so that you store and expend surges after you cast a spell or use a maneuver
