### ISSUE TITLE
Rework some themes' Power Surges

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#331]
The goal is to make the power surges more unique (currently there's 10 that just deal damage to creatures near you), and make sure they capture their theme. It's alright to combine damage and an effect.

**Comment by itamarcu** [comment]
My suggestions are in italics or with "(new)".

> **Acid**. Acid spreads out from you. Up to 3 creatures *or objects* of your choice that you can see within 30 feet of you take acid damage equal to twice the mana expended.

> (new) **Alteration**. Your mass shifts away from danger. If you are grappled or restrained, you can immediately make a saving throw to escape. If you succeed or if you were not grappled or restrained, you can then move up to 5 feet without provoking an opportunity attack.

> (new) **Antimagic**. You resist the effects of any foreign magic. You can make a saving throw against any one spell or magical effect that is affecting you.

> (new) (identical to Fear) **Beast**. You roar with primal fury. A creature of your choice that you can see within 30 feet of you must succeed on a Will saving throw or be frightened of you until the start of your next turn.

> (new) **Charm**. You beguile a creature with your presence. A creature of your choice that you can see within 30 feet of you must succeed on a Will saving throw or be charmed by you until the start of your next turn.

**Comment by mlenser** [comment]
Power Surge is meant to be uncontrollable power seeping out. Based on that I'd say several of these ideas do not meet that definition.

Some specifics:
- Alteration, Antimagic, Divination, and Fate are specific and controlled benefits. They are not uncontrollable power seeping out.
- Beast: I don't think we should copy fear here. There isn't a fear based spell in the Beast theme. I'd rather see something beast specific or nothing at all.
- Charm is good.
- Creation is strange. I can see this for plants, but don't think it fits for creation.
- Fire: The problem with burning is its just adding more stacks to fire spells that already cause burning. It becomes quite fiddly. I think we shouldn't do it, actually.
- Force: It should do damage equal to the mana and push.

**Comment by mlenser** [comment]
Added Charm to Power Surge and adjusted the targets to up to 2 for some options and increased the damage for options that target one creature with a saving throw.

I need to do some more work so I'll keep this open until I do. I think Shadow is far too complex for example.

**Comment by itamarcu** [comment]
Agreed with most of your replies, yeah.

Regarding the "specific and controlled benefits" - the power is already not fully uncontrollable (you can still select the exact target or targets, for example), so I don't think they're wrong. Perhaps they should be *less* controllable - for example, the Alteration one could just be "move away from the closest creature", and the antimagic could be something to dispel a random magical affect on yourself (potentially a good one).

Also, the teleportation benefit is obviously very controlled, which I thought was fine. Do you think it should be changed? teleport to a random direction, or towards/away from a random creature?

Force - the temporary hp are alright, they just don't really fit the force theme, IMO, unless you count the force shield. Plus, the temp hp don't stack, so it would be a waste to get a Force surge multiple times in a row. Still, I couldn't think of anything else and we already have auto-damage, so perhaps this is the best option.

---

Ice is currently damage and speed decrease to 3 creatures:

> **Ice**. The blood of nearby creatures slows as it chilled. Up to 3 creatures of your choice that you can see within 30 feet of you take cold damage equal to the mana expended and their speed is reduced by 10 feet until the start of your next turn.

We could replace it with the Slowed 1 condition, which also reduces AC and reflex saves. That would probably be too strong, so we could change to something like this:

> **Ice**. The blood of a nearby creature is chilled to a crawl. A creature of your choice that you can see within 30 feet of you must succeed on a Fortitude saving throw or take cold damage equal to the mana expended and become slowed 1 until the start of your next turn.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/84144083-f48d5080-aa57-11ea-9244-32bd2a6d1d70.png)
newer versions. I can post screenshots in the future

**Comment by mlenser** [comment]
> the Alteration one could just be "move away from the closest creature"

How do you move away via magic from alteration? I'm not seeing this one at all.

> The antimagic could be something to dispel a random magical affect on yourself (potentially a good one).

It's a 2 mana spell to dispel things. Power Surges are meant to be small.

____________

>Force - the temporary hp are alright, they just don't really fit the force theme

I would then suggest that you haven't read the theme's description.

> The Force theme focuses on reliable force damage, **_impenetrable barriers_**, and some utility over magic itself.

The latest version: 
![image](https://user-images.githubusercontent.com/235857/84144554-b6dcf780-aa58-11ea-96b3-ce42dbf4a2b1.png)

Ice is currently
![image](https://user-images.githubusercontent.com/235857/84144586-c65c4080-aa58-11ea-9360-bd96d310dd4c.png)

I don't think it should slow, for the same reasons that fire shouldn't burn: Power Surges are meant to be minor

**Comment by itamarcu** [comment]
Okay, fair! And with Force allowing you to protect another creature it neatly fixes the stacking problem, too.

---

Shadow - indeed too complicated, though I really love the idea of conjuring areas of darkness. 

Currently, it's:

> **Shadow**. The surrounding shadows envelop you. You can create a 5-foot cube of dim light or darkness which lasts for 1 minute. The area is considered magical and non-magical light can’t illuminate it. If you are in dim light or darkness you can wrap yourself in shadows, gaining one of the following benefits:
> - You can take the Hide action (no action required).
> - The next attack roll against you before the start of your next turn made by a creature that relies on sight is made with disadvantage.
> - While not grappled, incapacitated, or restrained, you can teleport up to 30 feet to an unoccupied space you can see that is also in dim light or darkness.

I suggest changing it to:

> **Shadow**. The surrounding shadows envelop you. You can create a cube of magical dim light or darkness in the space you occupy, which lasts for 1 minute. You may then take the Hide action as a bonus action.

**Comment by itamarcu** [comment]
> **Storm**. Stormy magic erupts from you. Up to 3 creatures of your choice that you can see within 30 feet of you take lightning or thunder damage (choose each time this ability activates) equal to twice the mana expended.

Can remove thunder from this, and add it to Sound (though this might depend on #322):

> **Storm**. You discharge electric energy. Up to 3 creatures of your choice that you can see within 30 feet of you take lightning damage equal to twice the mana expended.

> **Storm**. A thunderous boom erupts from you. Up to 3 creatures of your choice that you can see within 30 feet of you take thunder damage equal to twice the mana expended.

(maybe replace thunderous boom with high-pitched shriek or deafening cacophony or some other thing)

**Comment by mlenser** [comment]
I'm changing Shadow to be more offensive, like Light. We already have gloom as a cantrip for the shadow aspects

![image](https://user-images.githubusercontent.com/235857/84168312-8ce6fd80-aa77-11ea-89f9-63bd6150c9f6.png)

**Comment by mlenser** [comment]
Planes is not really about teleporting. Not like Teleport at least.

Sound vs Thunder can be handled as part of #327

**Comment by mlenser** [comment]
Light is twice the mana. But blinded is quite strong. I'll change Light, Sand, and Shadow to just damage = mana.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/84169599-12b77880-aa79-11ea-9683-c1c647ab79eb.png)

Current wording. I'm fairly happy with that. The list is somewhat generic, but the surge is meant to be simple so we don't want anything too advanced.

There could be other options, but they need to be simple.

**Comment by itamarcu** [comment]
I think you forgot to fix Teleportation - it's lacking the flavor text sentence. Also, IMO, there's no need to mention "incapacitated" because I don't think you can ever get a power surge while incapacitated.

**Comment by mlenser** [comment]
I purposefully removed the flavor text of teleportation to trim it down. `You teleport` seems redundant and its conditional so saying `you teleport` and then `If...` doesn't make much sense.

**Comment by itamarcu** [comment]
ahh, okay, that explains it
