### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#332]
[Inspire spell](https://www.kryxrpg.com/themes/spells/inspire)

> You can use this maneuver

Should be "spell".

[Suffused - Bloodrager - Bloodrage](https://www.kryxrpg.com/character/classes/suffused/bloodrager#bloodrage)

> The aura extends 15 from you in every direction

Should be "15 feet".

[Mending](https://www.kryxrpg.com/themes/spells/mending)

> you repairs

Should be "you repair".

**Comment by mlenser** [comment]
fixed locally, will release on the next release
