### ISSUE TITLE
Give Suffused more origin identity

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#333]
Suffused has always flirted with a bit of transformation. We should embed that (or similar ideas for concept that don't transform) into the core class. I'd like to remove metamagic as I've never thought that fits the Suffused so well.

Examples:
- Draconic would get options like the Draconic, Draconic Resilience, Draconic Fear, Draconic Wings feats. Maybe the feats, or maybe absorb some of those feats
- Celestial: same as Draconic
- Fiend: same as Draconic
- Vampire: same as Draconic
- Other, less transformation options, could have other features to be determined

This would basically take RAW Sorcerer subclass options and embed them into the class while leaving feats open for other options.

**Comment by DalenWBrauner** [comment]
It sounds like this could this be accomplished by having Sorcerers pick a "core" theme at Level 1, and giving them extra, free feats from that Theme.

As the Sorcerer is intended to "embody" a particular Theme, it certainly makes a lot of sense that they would draw more attributes from it than other classes, but I can't imagine any attributes that should be limited to Sorcerers exclusively.

**Comment by itamarcu** [comment]
As we work on this, let's make sure that all popular Suffused options fit this. If we want a transformation ability, we've got to make sure that it *makes sense* for transformation to fit each origin.

Looking over the 5th edition Sorcerer, we know:
> Sorcerers carry a magical birthright conferred upon them by an exotic bloodline, some otherworldly influence, or exposure to unknown cosmic forces

The texts suggest the following origin options (I spent time collecting them because it was fun):
- Bloodline can be traced back to a supernatural being (dragon, giant, celestial, fiend...), or sometimes, a person who was granted power by such a being
- Blessing/Curse
- Reincarnation of powerful being
- Created in a vat
- Product of generations of careful, selective breeding
- Exposed to a powerful artifact
- Born in a storm, or near a phoenix, or close to a portal
- Prophecy
- A spirit haunts your mind or possesses your body
- Exposed to extraplanar influence (far realm, "psychic wind")
- Survived a near-death experience
- Drank from a magical stream
- Ate your twin in the womb
- Had an imaginary friend

**Comment by Euthrosyne** [comment]
Can we then fold the transformation aspect into a feature that would encompass the Suffused channeling power/magic/essence from its origin? That way origins that definitively have something to transform into can do so, whereas origins that have more amorphous origins could still find a way to express themselves. One potential drawback is that it would require us to come up with a framework that can broadly cover all the ways a character can transform itself. 

Another option to represent transformation is to give explicitly the option for Suffused to manipulate character features at creation (These features may or may not have pragmatic applications). If a Suffused was created in a vat for example, do they necessarily have to have two legs or legs at all?  In this way, it reduces the amount of prescriptive guidelines that have to be created and allows more creativity to the player character. One potential concern is that this design space eats into the Alteration theme slightly.

**Comment by mlenser** [comment]
Some clarifications:

"Transformation" does not mean something like Wild Shape. It means taking traits, as my example in the OP outlined: "Draconic would get options like the Draconic, Draconic Resilience, Draconic Fear, Draconic Wings feats. Maybe the feats, or maybe absorb some of those feats". Still very humanoid, but with traits of the creature

> As the Sorcerer is intended to "embody" a particular Theme

A Sorcerer does not embody a theme. It embodies a concept like dragon, angel, vampire, fey, fiend, genie, sea creature, creature of shadow, etc.

> The texts suggest the following origin options (I spent time collecting them because it was fun):

Going to discuss some specifics:
- Blessing/Curse, Exposed to a powerful artifact, Prophecy, Drank from a magical stream: I'm not sure that is really Sorcerer. The other cases of "exposure" have a source. These would need one too. The magic isn't just generic.
- Survived a near-death experience, Ate your twin in the womb, Had an imaginary friend: not sure how this gives you magic

The rest are the same as the bloodline case, you still have the stuff inside you and parts of that stuff are expressed by you in how you look and the traits you have.

**Comment by DalenWBrauner** [comment]
> A Sorcerer does not embody a theme. It embodies a concept

Well, then we either need to:
1. Enumerate these concepts outside of Themes, and not have our selectable bonuses be Theme-dependent, or
2. Enumerate these concepts _within_ Themes, so we can still say "You take the Shadow Theme to gain Vampiric traits, you take the Water Theme to gain Sea creature traits, etc".

This is why I brought up feats- one way we could accomplish this is to label certain feats as Explicitly being for this feature. Feats like Vampiric, Lycan Form, Fiery, etc. We would just need to create more of them to have enough content for each of the bloodlines we can imagine.

**Comment by mlenser** [comment]
If this feature needs things, they don't need to be feats. We don't need to create a complex system of feats that areo nly used by Suffused. Then such features would only exist on Suffused. But some can surely be shared. Vampire, for example, could become a vampire through blood. A Kobold could become a bit draconic. So those feats should remain feats.

> Enumerate these concepts outside of Themes, and not have our selectable bonuses be Theme-dependent

The options will be based on the subclasses, as mentioned in the OP.

**Comment by itamarcu** [comment]
> Still very humanoid, but with traits of the creature
> A Sorcerer does not embody a theme. It embodies a concept like dragon, angel, vampire, fey, fiend, genie, sea creature, creature of shadow, etc.

A lot of sorcerers are based on creatures but *not all* sorcerers are based on creatures.

For example, the Astral sample origin (sample origin = subclass?):
> You have often dreamed of traveling the Astral Plane in search of knowledge and secrets. Perhaps you wandered into a portal that infused you with power, or perhaps you were born and raised by a family of wanderers whose faith was based in astronomy, you wander the world seeking lore that you can share with them.

Chaotic and Storm are similar. They can technically be related to some creature, an elemental, but many of the sorcerers with those origins have nothing to do with that.

Another example - the Clockwork Soul sorcerer (5e UA) is based on the plane of absolute order. It can "equalize chaotic moments", "enter a state of clockwork consciousness", and "summon spirits of order to restore balance" - none of these are transformations, though the second one can be said to be about affecting the sorcerer's mind with the magic of that plane. In the Kryx RPG such a sorcerer could utilize themes of Creation, Force, Antimagic, and perhaps Fate or Mind. Very few of these really make sense as things that would physically affect the sorcerer's body, and of course this is not related to any particular creature.

**Comment by mlenser** [comment]
> A lot of sorcerers are based on creatures but not all sorcerers are based on creatures.

I already covered this in the OP and several times in this discussion.

> We should embed that (or similar ideas for concept that don't transform) into the core class

____________________

> Chaotic and Storm are similar. They can technically be related to some creature, an elemental

The pure representation of those energies is the elemental so I think those cases should show signs of the elemental.

> Clockwork Soul sorcerer (5e UA) is based on the plane of absolute order

I would argue that this concept should live in an Acoltye or Artificer of some kind.

**Comment by mlenser** [comment]
So here's my thought:

## Suffused
- (-) Choice of Power Source. This was just lazy. Power Source is fully tied to your origin.
- (-) Magic Manipulator (2 metamagic + 2 metamagic options)
- (-) Signature Spells (10 signature spells which cost 1 mana less)

### Dragon origin
- (+) Power Source and themes based on Dragon Type. Black will give you the Occult power source and the shadow and acid themes. Gold will give you the Divine power source and the Holy theme and some other options like Charm or Light. Blue will give you the Primal power source and Storm/Sand/Deceit.
- (+) "You can speak, read, and write Draconic and whenever you make a Charisma check when interacting with dragons you have advantage on the check."
- (+) Resistance based on the dragon type. Black gets acid, blue gets lightning, etc
- (+) Draconic fear ability. We already have the fear theme for the power surge, perhaps spells like Frighten, Fear or maneuvers like Fearsome Beast and Fountain of Blood for Bloodrager.
- (+) Wings

### Celestial origin
- (+) Divine power source plus some themes from Holy, Life, and Light
- (+) "You can speak, read, and write Celestial and whenever you make a Charisma check when interacting with celestials you have advantage."
- (+) "You have resistance to radiant damage and you have advantage on saving throws against being frightened."
- (+) "You don’t need to share a language with a creature for it to understand your words, but the creature must be able to understand at least one language."
- (+) Wings

### Fiendish origin
- (+) Divine power source plus some themes from Holy, Fire, Charm, Fear, etc
- (+) "You can speak, read, and write Abyssal or Infernal and whenever you make a Charisma check when interacting with fiends, you have advantage."
- (+) "You gain darkvision out to a range of 18 meters and magical darkness doesn’t impede your darkvision. If you already have darkvision, its range increases by 18 meters."
- (+) "You have resistance against fire and poison damage."
- (+) Another feature
- (+) Wings

### Storm origin
- (+) Primal power source with the Storm theme
- (+) "You can speak, read, and write Auran and whenever you make a Charisma check when interacting with elementals based on air you have advantage. Additionally, you gain the ability to subtly control the weather around you."
- (+) "You are infused with elemental air. You gain resistance to lightning and thunder damage."
- (+) Another feature light no reactions on attacks or something
- (+) Flying Speed

## Summary
This basically builds the subclass back into the class. Metamagic would still be an option as a feat for the Sorcerer who wanted to specialize in that. The cost would be the same as you take metamagic as a feat instead of all these origin feats. So we're basically giving up Signature Spells for some more flavorful features and potentially an extra theme. I haven't quite worked out how many themes and everything.

**Comment by Marcloure** [comment]
My issue with that is having to make a list for each subclass, and also a good framework so users can make their own if needed. Surely someone will one day come with a origin we never thought before.

**Comment by Euthrosyne** [comment]
One thought that came to me is that this system does not have a way to compensate certain races for already having a lot of the traits associated with their race. What options exist for a player wanting to play a Dragonborn Draconic Origin Sorcerer who finds they lack a lot of functional diversity compared to other races/classes?

**Comment by itamarcu** [comment]
I really love the fact that Kryx RPG uses feats as a way to make character creation more modular, giving more power to the player, and I feel like this is a step back.

The Celestial origin is equivalent to just taking the feats Celestial (2nd), Radiant Being (4th), Divine Language (10th), Celestial Wings (12th), along with choosing a Divine power source, the Holy/Life/Light themes, and capability with Persuasion. These are all things that the player can already do, and I can easily imagine players who will want to tweak it a little - for example, a player might want to play a "fire angel"-based character who gets intimidation instead of persuasion and the Radiant Soul feat (resistance to fire and radiant) instead of Radiant Being (resistance to light and frightened). A player could want to play an angel of death, who has most of the angelic features but uses the Life and Death themes instead of anything to do with radiant, or an angel of judgement, who replaces persuasion with insight and doesn't have wings and heavily focuses on spells like Extort Truth.

If we enforce these as player choices, we are just artificially limiting sorcerers in a way that feels awful to me. Why not just put all of these great lists as *suggestions*, in the subclass flavor area?

Removing Metamagic - I'm in favor, because it's already a feat, so sorcerers that want it can take it.

Removing Signature Spells - no opinion. If it's replaced with something of equal power, sure. The subclass could use more mechanical identity, and if we remove these two features, only Power Surges do that - it would be nice to have another mechanical identity feature.

After rereading the conversation, I think I agree with @DalenWBrauner - feats already allow making all of these character design choices. The problem there is that the sorcerer doesn't have enough feats to spend on other character traits. I think the solution should be giving them extra feats, and these extra feats should just be limited - all in one theme. Potentially increasing to two themes at a higher level.

A similar idea would be limiting them to be only feats labeled something like "anomaly"/"origin" (referring to all these creature-based feats, and the plane-based ones) - but this might be harder to decide. Are Fire Adept and Fire Master feats that particularly fit the phoenix fire sorcerers? I don't know.

If we go with the idea of extra feats from one or two themes, the feature could read:
> **Anomalous Influence** `(4th, 8th, 12th, 16th, 20th)`
> Your soul is altered by the power within it, slowly transforming you in various ways.
>
> Choose a theme. You gain a feat of your choice from that theme.
>
> You gain additional feats from that theme at 8th, 12th, 16th, and 20th level. At 12th level, you can choose another theme, and feats gained by this feature can be from either of the two themes.
>
> When you gain a level, you can choose one of the feats gained by this feature and replace it with another feat that you could have gained when the replaced feat was chosen.

**Comment by DalenWBrauner** [comment]
> I really love the fact that Kryx RPG uses feats as a way to make character creation more modular, giving more power to the player, and I feel like this is a step back.

>These are all things that the player can already do, and I can easily imagine players who will want to tweak it a little-

> If we enforce these as player choices, we are just artificially limiting sorcerers in a way that feels awful to me. Why not just put all of these great lists as suggestions, in the subclass flavor area?

I couldn't have said it better myself.

**Comment by Euthrosyne** [comment]
Thinking about a new mechanical feature to replace Signature Spells, the notion of sorcery points rose to the surface, but acquired through casting spells/expending stamina. You could scale it to the amount of mana/stamina expended on a spell/maneuver. These points could be used to: 

- regain mana/stamina at a loss, efficiency wise
- increase the casting limit of a spell/maneuver
- cast a spell/use a maneuver in place of mana/stamina 
- augment the next use of a power surge in some form
- augment your appearance, i.e. as you cast spells associated with your theme, you acquire traits associated with that theme, i.e. as you cast fire spells, magical fire begins to writhe around your body 

There could also be an active drawback with accumulating too many sorcery points as your body becomes unable to contain the burgeoning magical energies, creating a dichotomy where the sorcerer wants to run hot and cast a flurry of spells, but not run too hot and potentially burn out.

Thematically, it represents the Sorcerer tapping deeper and deeper into its source and its source resonating with that usage of power and encouraging even more use of that power. As a Fire Sorcerer channels their magic more and more, it becomes easier to do so, but with greater and greater amounts of risk.

**Comment by Euthrosyne** [comment]
One way to maintain the customizability of the system while functionally baking in 5e subclass features would be to create a template and points system where sorcerers receive a certain amount of points to customize their character at level 1 to better represent their origin. To some extent, you have already codified this system of traits in the race balance worksheet, though I'm not sure how feasible implementing it would be.

**Comment by DalenWBrauner** [comment]
> There could also be an active drawback with accumulating too many sorcery points as your body becomes unable to contain the burgeoning magical energies, creating a dichotomy where the sorcerer wants to run hot and cast a flurry of spells, but not run too hot and potentially burn out.

This to me is reminiscent of the Consumptive Power feat, but in a good way. I like the idea of a suffused tapping into or bringing out their innate magical energies in a way that other classes simply can't keep up with, but at some kind of physical cost or toll to the user. Or perhaps like irresponsibly opening the faucet a bit wider on the magic that flows through you.

Some other potential drawbacks we could play with:
- Exhaustion
- Temporary decreases to Mana Limit
- Will or Fortitude saves to prevent indescriminate Power Surges
- Will or Fortitude saves to maintain control over your character

I don't think the boons should necessarily be remenscent of Metamagic in terms of spellcasting _finesse_, but I like the idea of more "raw magic" bonuses like 'free' augments, etc.

**Comment by Euthrosyne** [comment]
> This to me is reminiscent of the Consumptive Power feat, but in a good way. I like the idea of a suffused tapping into or bringing out their innate magical energies in a way that other classes simply can't keep up with, but at some kind of physical cost or toll to the user. Or perhaps like irresponsibly opening the faucet a bit wider on the magic that flows through you.

Thinking about this from a balance-perspective, I feel that the drawbacks would have to appear early on, but not be overly crippling until a character has truly gone overboard. This would compensate for the expanded capabilities of the class and create tension in how players handle their sorcerers. 

It could exist as a short-term feature a la a Limit Break where a sorcerer could activate it and for the next minute, spells/maneuvers open the spigot of the origin a little more, allowing the sorcerer enhanced capabilities, but at the risk of losing control as the spigot is opened more and more. Spells/maneuvers that cost more resources would open the spigot proportionally more. 

It could also exist as a passive that the character has to modulate over the course of a day before short rests, i.e. spells/maneuvers used create another resource that itself can be used for other features, but using this resource does not deplete it, but instead increases it

There could (and I feel should) also be an option for a release valve of sorts, but one that sharply limits the sorcerer for a short period of time to represent the Sorcerer stepping back from the edge and regaining control of themselves at the cost of needing to concentrate on calming their magic down, i.e. release/disperse all sorcery points, but cannot cast any spells except cantrips until the end of the next turn.

**Comment by mlenser** [comment]
> My issue with that is having to make a list for each subclass, and also a good framework so users can make their own if needed. Surely someone will one day come with a origin we never thought before.

Guidelines can be created. It's pretty straight forward from the above. GiphyGlyph's example:
![image](https://user-images.githubusercontent.com/235857/84230724-ec332500-aaec-11ea-8a83-deb520c2a441.png)

> this system does not have a way to compensate certain races for already having a lot of the traits associated with their race and so in a way underpowers them in comparison to more varied builds.

Nor does RAW, but I'm happy to resolve that for those rare cases (Dragonborn as Draconic, Aasimar as Celestial, etc). Those cases are all after the same thing: showing more of your inherent identity.

_________________

> giving more power to the player, and I feel like this is a step back.
> artificially limiting sorcerers

Classes need identity. The Suffused, especially, is a character suffused with magic from an origin. A Suffused with the Draconic origin, for example, gets its power from its Draconic bloodline. That bloodline is not just a spark of magic that the character can then ignore. It manifests in a myriad of ways. Currently that is entirely optional which doesn't fit the flavor of the class. The Suffused is not an open-ended class that is intended to just grab whatever magic the player wants. That is a class with no identity.

> players who will want to tweak it a little

Tweaking will not be removed. The Suffused will still have all of its feats. It will just have its origin actually manifested like the flavor intends.


_____________

> Thinking about a new mechanical feature to replace Signature Spells

I have no intention to replace Signature Spells. It was an attempt at an identity, but I don't think it fits.

What you describe below, though, sounds super interesting. However, mechanically it can be very unbalancing.
> Thematically, it represents the Sorcerer tapping deeper and deeper into its source and its source resonating with that usage of power and encouraging even more use of that power. As a Fire Sorcerer channels their magic more and more, it becomes easier to do so or has greater effects, but with greater and greater amounts of risk.

Can you please open a new issue for this and move all the conversation about it there?

**Comment by itamarcu** [comment]
> One way to maintain the customizability of the system while functionally baking in 5e subclass features would be to create a template and points system where sorcerers receive a certain amount of points to customize their character at level 1 to better represent their origin. To some extent, you have already codified this system of traits in the race balance worksheet, though I'm not sure how feasible implementing it would be.

There's several problems with this - 
- Many origin-based features should only come into play at later levels (e.g. wings). Making the sorcerer choose them at 1st level and gain them at 12th level is weird.
- It would require creating a whole new system just for this.
- What would prevent people from just point-buying the best options? (e.g. vampiric, devil's sight, draconic fear)

**Comment by Euthrosyne** [comment]
> * Many origin-based features should only come into play at later levels (e.g. wings). Making the sorcerer choose them at 1st level and gain them at 12th level is weird.

In that case, would you then spread out the selection a la 5e subclasses where they can choose from x, y, & z at level 1 and so forth? 

> * What would prevent people from just point-buying the best options? (e.g. vampiric, devil's sight, draconic fear)

It's not particularly elegant, but for those very powerful options, one could have a limit on how many of those options could be taken or limit the number of slots so that only one of those kinds of options could be taken.

**Comment by itamarcu** [comment]
> That bloodline is not just a spark of magic that the character can then ignore. It manifests in a myriad of ways. Currently that is entirely optional which doesn't fit the flavor of the class. The Suffused is not an open-ended class that is intended to just grab whatever magic the player wants. That is a class with no identity.
> Tweaking will not be removed. The Suffused will still have all of its feats. It will just have its origin actually manifested like the flavor intends.

I agree with you, and I feel like simply giving additional feats and restricting them in a certain way (e.g. to a specific theme) is a better solution than going with predefined choices. It still limits the Suffused and forces them to follow a path, it just lets them pick the steps of the path better, and makes developing this system much easier.

In addition, if there's a risk of a player claiming to belong to a draconic bloodline but taking a mish-mash of skills and feats that make no coherent sense, I'd rather allow some annoying players to build badly-flavored characters than prevent well-intentioned players from building their character in a way that makes sense to them. The rules already have multiple ways to discourage going against flavor (limiting choices by your themes, limiting themes by your power source, making all choices viable, perfectly balancing each playstyle, and having an actual GM who can judge the player's build). If players sacrificing flavor for power is a problem, I think it's better to wait and see if and how it happens, and make more localized fixes.

If we go with the "predefined choices" solution....
- Someone will need to write a dozen lines detailing these features, for each sample origin, of which there are currently almost 20.
- They will all need to fit into the Suffused class description.
- They would all need to be balanced against each other
- They would all need to use the same "guideline template", which could be hard to fit for certain origins
- Many players would want to pick one of them but slightly tweak it, by removing something and adding something else. They'd have to "create" a whole homebrew origin for this.
- How do we choose which origins get to be mechanically integrated into the core ones? When people suggest new origins, when do we add them?
- What about specific races or backgrounds that already give some of the features? Are we going to start adding statements such as "if you are a Dragonborn, you get..."? We could go with "unless you already have X Y Z" but sometimes races don't give *exactly* what the origin feature would give them.
- There will be a lot of duplication (a feat restated in this feature) or a lot of referrals to existing feats. If a feat is changed/rebalanced (e.g. moved to higher level, or get split into two) we will need to remember to update the appropriate copy or to look at the list again and see if this requires additional changes there.
- Many origins might not currently have an existing list of feats to convert into a choice (e.g. for the Spectral origin (Death/Spirit) there isn't a feat sequence that makes you into a ghost or into an undead, not in the same way as Draconic/Vampiric/Celestial do). We do want to come up with these eventually, but if we make these into predefined subclass options we'll have to come up with them *immediately*, or drop them from the subclass list.

It can still work out, but it doesn't seem like the best solution to me.

**Comment by Euthrosyne** [comment]
> Can you please open a new issue for this and move all the conversation about it there?

I'll be happy to do so.

> Classes need identity. The Suffused, especially, is a character suffused with magic from an origin. A Suffused with the Draconic origin, for example, gets its power from its Draconic bloodline. That bloodline is not just a spark of magic that the character can then ignore. It manifests in a myriad of ways. Currently that is entirely optional which doesn't fit the flavor of the class. The Suffused is not an open-ended class that is intended to just grab whatever magic the player wants. That is a class with no identity. 

It feels very much like this concept of the Suffused is rooted in Pathfinder, and as such, it might be easiest to look there as to how to adapt it to this system. There is a class whose identity is to be open ended and to grab whatever magic the character can acquire through learning, research, discussion, etc, and that would be the mage, arcane secrets being the epitome of such an approach. So being an open-ended class is not the same thing as being a class with no identity. That said, I agree that the identity of the Suffused is not one that is rooted being open-ended and that employing it as such, while very convenient for player characters to handle, is probably not as accurate as it should be. 

(As a side note, one very odd thing that is canon in 5e is that half-dragons are infertile, making it interesting how the bloodline manages to continue. I guess magic can make miracles happen, hence why more of the bloodline would tend to occur in a magical class, but...)
![image](https://user-images.githubusercontent.com/65435786/84233697-d14abb80-aac0-11ea-87ea-1054e654a59a.png)

**Comment by mlenser** [comment]
The conversation is getting off topic with other suggestions and the thread is just filling up. Further discussion is currently not a good use of my time.

**Comment by mlenser** [comment]
Reopening the discussion. I have limited time so I try to make issues very focused so they can be discussed and processed through. Apologies for marking items as off-topic. It doesn't mean that the post was bad, just that it perhaps deserves its own issue or deserves to be discussed somewhere else. @Euthrosyne please feel free to join our discord for discussions as well.

**Comment by mlenser** [comment]
>  I feel like simply giving additional feats and restricting them in a certain way (e.g. to a specific theme) is a better solution than going with predefined choices

The issue here is that concept like Draconic, Celestial, Fiend, Beholder, Fey, etc do not belong in a theme. A Beholder for example is in the mind theme, but that is quite a broad theme. Fey has some Plants, Charm, and maybe Deceit or Fear, but that's a lot. Additionally, I don't think it's wise ot make a `Dragon` or `Beholder` or `Fey` theme. Those are not themes, but identities that pull from different themes. Plus a `Dragon` theme wouldn't work very well as each type of dragon is very different. Sure, you could give the Suffused some themes related to the identity, but that does not attach them to their bloodline. This all boils down to my next point:

### Suffused are defined by their origin
Suffused get their magic from their origin. The magic they have is inside them and seeks to escape out. It does so in their appearance and their spells. Examples:
- a Suffused with Fiendish blood in them is going to appear somewhat like a Tiefling
- a Suffused with Celestial blood in them is going to appear somewhat like an Aasimar
- a Suffused with Draconic blood in them is going to appear somewhat like a Dragonborn

*Note: the power source can come from a source other than a bloodline, but the result is the same: their DNA is mutated by whatever the cause*

This doesn't mean your Human Dragon Suffused is now a Dragonborn, but over time it'll definitely start to resemble it more and more. That shouldn't be any more optional than it is for a Tiefling to have its traits. The extent of the appearance changes is up to the player, but the mechanics of the Tiefling and the Suffused should not change based on that (though a GM could make some exceptions).

____________

This is getting long so I'll jump to your concerns:
> Someone will need to write a dozen lines detailing these features, for each sample origin, of which there are currently almost 20.
> They would all need to be balanced against each other

This is already the case with the feats system here. If we're not doing it already then we're providing a dis-service to those origins (which I know is the case)

> Many players would want to pick one of them but slightly tweak it, by removing something and adding something else. They'd have to "create" a whole homebrew origin for this.

A Tiefling is a Tiefling as much as a Fiendish Suffused is a Fiendish Suffused. We should create the origin to cover all the cases of dragons/fiends (which I will). GM can always tweak, but the vast majority of cases should be covered.

> How do we choose which origins get to be mechanically integrated into the core ones? When people suggest new origins, when do we add them?

The same way we do now: people create suggestions. Currently origins need feat support so the process is not so different

> What about specific races or backgrounds that already give some of the features?

RAW doesn't cover this either. But it should be covered. I'll make sure its covered.

> There will be a lot of duplication

I definitely won't refer to feats from a class as that is difficult for a user to track and follow. Some feats I may remove. Others, that have value to other classes like Occultist, I'll probably restrict to Occultist. Vampire and Lycan and similar options will remain available for all.

> Many origins might not currently have an existing list of feats to convert into a choice

Which means they are not supported sufficiently and doing this process will force me to do so.

**Comment by mlenser** [comment]
I updated my post above with some more origins. You can already see that some are lacking, for sure.

One thing we can play around with: The appearance can be on a toggle. A suffused could not express any signs of being celestial until it chooses to do so (as a bonus action, probably). But it wouldn't get outward benefits like wings until it did so. That keeps the identity without forcing you to "look like a dragon" all the time.

**Comment by itamarcu** [comment]
Alright, I think this could work well. It will take a lot of work (now and to maintain it) but it could be a good change. If you can start the partial work on this, you could open some github issues for missing origins (with some template or default origin to build around), and the community could help lighten the load.

I think you'd want a special UI element for the origin - something like the Companion picker, perhaps. Alternatively, put them all in the bottom of the Sorcerer page, but with the class description pointing out that you should keep scrolling down and choosing.

I'm against removing feats though, because it would functionally prevent other classes from getting them. If somebody wants to play a genasi druid with [Fiery](https://www.kryxrpg.com/feats/fiery), a priest of the god of chaos with [Wild Surge](https://www.kryxrpg.com/feats/wild-surge), or a peaceful ranger who was blessed with [Divine Language](https://www.kryxrpg.com/feats/divine-language), I don't want these options to become unavailable just because they fit a Suffused character *more*.

**Comment by mlenser** [comment]
Suffused class reworked to give it more identity based around its origin
