### ISSUE TITLE
Infinite Trinkets?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#334]
https://www.kryxrpg.com/spells/trinket

I believe that once upon a time, the Trinket cantrip stated you could only ever have one at a time. Did this change? As @Paulorpribeiro mentioned in #326, right now there's nothing stopping anyone from conjuring an infinite amount of them (or rather, however many Actions exist in 10 minutes..).

**Comment by mlenser** [comment]
- **Themes**
  - **Creation**
    - Trinket duration changed to 1 minute
  - **Earth**
    - Ferrous Growth duration changed to 1 minute

**Comment by DalenWBrauner** [comment]
Well, this still allows you to create as many as you can create in a single minute. Is it intended to be able to conjure multiple trinkets at a time?

**Comment by mlenser** [comment]
The items last a minute. There is no limit on the amount you can create, but it would be a terrible tactic to spend your whole time keeping 10 active.
