### ISSUE TITLE
Adjust Psionicist image size

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#336]
Make the image slightly smaller so the Quirks section and the table can fit beneath it

![image](https://user-images.githubusercontent.com/29084710/84115108-dd247800-aa03-11ea-8085-d578fcfd49e3.png)

**Comment by mlenser** [comment]
The size is a standard size. We'd have to add content above to push it down.

**Comment by Marcloure** [comment]
I actually don't really like that image. It has a very low resolution, and the compression is easily visible

**Comment by mlenser** [comment]
Please, find a new image. All the others I have are higher quality.

**Comment by Marcloure** [comment]
Psion:
https://i.pinimg.com/originals/61/47/10/6147107628eef1e9a930064ab718cca2.jpg

Monk:
https://haroldshomebrewworld.files.wordpress.com/2013/08/39.jpg

Soulknife:
https://user-images.githubusercontent.com/29084710/84117350-c5e78980-aa07-11ea-91e8-be6431c07703.png

Soulknife:
https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/68806613-0e8f-46fb-9565-a944c9516719/d1ou4zy-de0eb40e-d759-4797-954b-5460b4686041.jpg/v1/fill/w_900,h_1165,q_75,strp/xeph_soulknife_by_thedarkestseason.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwic3ViIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl0sIm9iaiI6W1t7InBhdGgiOiIvZi82ODgwNjYxMy0wZThmLTQ2ZmItOTU2NS1hOTQ0Yzk1MTY3MTkvZDFvdTR6eS1kZTBlYjQwZS1kNzU5LTQ3OTctOTU0Yi01NDYwYjQ2ODYwNDEuanBnIiwid2lkdGgiOiI8PTkwMCIsImhlaWdodCI6Ijw9MTE2NSJ9XV19.cNapLC1iI6EEudo8Yz6boC6zruhvmi88UaYaulsDF0g

Soulknife:
https://therafim.wdfiles.com/local--files/soulknife/Soulknife.jpg

**Comment by Marcloure** [comment]
Psion:
https://srd.dndtools.org/srd/resource/images/classes/33173.jpg

**Comment by mlenser** [comment]
I only use one image per class so it has to fit the class in general.

I'm not a huge fan of most psionicist artwork. Most have halos around their head or eyes on their foreheads or weird vein stuff going on.

**Comment by Marcloure** [comment]
I like the pathfinder images, this woman with blue saris I sent above

**Comment by mlenser** [comment]
It's very pathfinder and recognizable as pathfinder. That's the main problem.

This one you posted earlier is probably the best, besides the random spellbook and rune floating next to her. Though, those could be cut out.
![Psion](https://www.gmbinder.com/images/3lPH13r.jpg)

**Comment by Marcloure** [comment]
That one is my favorite as well. She is the same character from the very first like I posted

**Comment by mlenser** [comment]
The problem is the quality of it is actually not great..

**Comment by Marcloure** [comment]
How large are the images on the site? I thought 1000px high would be enough

**Comment by mlenser** [comment]
It's not about the width. It's heavily compressed and pixelated.

**Comment by Marcloure** [comment]
Yeah, the compression is visible if I zoom in a bit

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/84143974-c3ad1b80-aa57-11ea-8a4b-a0083f184222.png)
