### ISSUE TITLE
A bunch of typos

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#337]
[Converting Spells](https://www.kryxrpg.com/themes/converting-spells):
> Powerful, theme defining spells Just summoning spells left and the hundreds that aren’t on my damage calculation sheet.

should have a line break (or just remove that extra comment)

---

[Rules of Concoctions, etc.](https://www.kryxrpg.com/themes/rules):
> Every spell has a mana cost from 0 to 10

should be 0 to 5, or 1 to 5 with special mention for cantrips

> So when Umara, a 5rd-level Mage (Wizard), uses fireball, a 2 mana spell, he spends 2 mana and has 3 mana remaining.

should be "she"

> Finishing a short or long rest restores any expended mana.

actually short rests don't restore all mana

> For instance Umara casts magic missiles using 2 mana, that magic missiles is cast as if it were a 2 mana spell

should probably just be rewritten - hard to understand what the point of it is. I suggest "For instance, if Umara casts magic missiles using 2 mana, the spell creates 12 magic missiles."

> For a maneuver like cleave

needs a newer example

> Most spells have ranges expressed in meters typically

should add a comma after "meters"

> Most sells require

should be "Most spells require"

> Minor component costs have been removed

I think this paragraph should be put after the next one, and not before it - and perhaps colored purple, to make it clear that this is a difference relative to 5th edition?

> the caster must provide this focus

should be "the caster must provide this material" or "the caster must provide this item"

> can’t be dispelled, because its effect exists only for an instant

should be "because their effect", IMO

> Being incapacitated or killed. A creature loses concentration on a spell if it is incapacitated or if it dies.

I'd like to say that this really surprised me, because I didn't realize that Hold Person automatically stops concentration.

Could we add this to the conditions descriptions? under "incapacitated", add "cannot concentrate on a spell"?

> Unstable concoctions

is this meant to be mechanically identical to concentration or not? like, do things that stop concentration stop this, too? If so, you should probably add a statement about that.

---

**Water Jet:**

> in a direction following the line

should be "cone or line"

**Eruptive Pustule:**

> On a failed save, a creature takes 2d8 poison damage.

this entire statement should be removed (copy-paste mistake)

> On a successful save, a creature takes half as much damage.

Should be "... half as much damage and no damage at the end of its next turn"

**Acid Fog:**

> On a successful save, a creature takes half as much damage.

Should be "... half as much damage and no damage at the end of its next turn"

**Comment by mlenser** [comment]
> actually short rests don't restore all mana

They do. A long rest restores all, a short rest restores some. Changed to `Finishing a short or long rest restores some mana. See your class for more details.`

> should probably just be rewritten - hard to understand what the point of it is. I suggest "For instance, if Umara casts magic missiles using 2 mana, the spell creates 12 magic missiles."

This is copied from RAW and slots are replaced with mana. Stating it is 2 mana is important for reasons. For example Counterspell.

![image](https://user-images.githubusercontent.com/235857/84171602-4abfbb00-aa7b-11ea-9a58-6d2dda52d740.png)


> colored purple, to make it clear that this is a difference relative to 5th edition?

I've stopped doing that. I removed spell components for now.


> I'd like to say that this really surprised me, because I didn't realize that Hold Person automatically stops concentration.

It's RAW

> Could we add this to the conditions descriptions? under "incapacitated", add "cannot concentrate on a spell"?

yes

> is this meant to be mechanically identical to concentration or not?

No. The only limit on unstable concoctions is as written (only 1 created at a time).

___________


Thanks for the rest. Really great to have someone proofread stuff.
