### ISSUE TITLE
Improve scaling of Line effects

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#338]
Currently, Lines are 15 feet long per mana, and their width is always 5 feet. Cones are also 15 feet long per mana, but they also have the expanding width (equal to the length at the end), so they cover much more ground.

Many spell effects ask you to choose a cone or a line, and because of this, a cone is almost always the optimal choice - the only time when it isn't is when you're trying to avoid hitting someone, and all of your enemies happen to be standing perfectly in line. This is rare, and in 5e, usually Lines have a wider or longer area of effect, to balance this. For example, Lightning Bolt is supposed to be roughly as good as Fireball, but when Fireball is a 20x20 sphere anywhere within 120 feet of you and Lightning Bolt is a 30x5 line that extends from you, I feel like the first one is clearly better at hitting more targets. In 5e, it was less of an issue, because it was a 100x5 line.

I suggest that one of the following two changes was implemented:
* Line length is twice the current numbers - 30 feet for 1 mana, and 150 feet for 5 mana.
* Line width also scales, by 5 feet per mana, so a 2 mana spell would be 30x10 and a 5 mana spell would be 75x25.

Note: Impaling Shot (maneuver) stops making sense if width is bigger. However, every other spell or maneuver I've looked at is still fine and this change would fit them.

**Comment by DalenWBrauner** [comment]
Personally, I think lines should be longer than cones, rather than a width increase. Thinking back to our discussion on hand shapes, it makes sense that a lot of "beam"-like abilities would either be "sprayed out" or more _focused_.

**Comment by mlenser** [comment]
A 30 foot line is stronger than a 15 foot cone, I believe. 15 foot cone you have to get pretty close and angle it right. A line of 30 feet has much more potential to hit multiple creature. Almost always 2 creature, often 3.

Mechanically we could do somewhere in the middle, but then we're creating weird lengths like 20. I think 20 would be the only option if we want to do this. 20,40,60,80,100.

**Comment by Lamorak11** [comment]
I like 20. Feels about right to me.

**Comment by itamarcu** [comment]
> A 30 foot line is stronger than a 15 foot cone

That's true - a 15 ft cone affects 5 squares, and a 30 ft line affects 6 squares.

But when you keep scaling, cones are clearly better - at 2 mana, the cone covers 18 squares, while a line covers 12. At 5 mana, the cone covers 41 squares, while the line would cover 18.

In addition, creatures are much more often either standing in a packed group or scattered in a roughly circular area. A cone fits these circumstances much more, while lines are only optimal if you're fighting in tight yet long corridors.

At 1 mana, lines might be slightly better at 30 feet, but at higher mana cones are still usually better, IMO, even when they reach half as far.

Ideally, we would have a database full of standard combat encounter positions, to have good numbers on how many creatures could be hit with AoE attacks on average. Sadly, I don't know of any, so I drew this instead:

![image](https://user-images.githubusercontent.com/6516621/84419395-37e6eb00-ac21-11ea-9f8f-582fb6e284a9.png)

**Comment by mlenser** [comment]
Numbers of squares isn't a total indicator. For example in tbe ottom arrangement you can hit several groups of 3 in a line, but only one group of 3 in a cone.

**Comment by mlenser** [comment]
Lines changed to 20 feet per tier

**Comment by itamarcu** [comment]
Also worth noting (this this might be too late): https://rpg.stackexchange.com/questions/128299/would-it-be-unbalanced-to-allow-a-dragonborn-access-to-both-breath-weapon-aoe-ty

In 5e, dragonborn have access to either a 30x5 ft line or a 15 ft cone, so it's at least implicitly considered balanced/equivalent.

**Comment by itamarcu** [comment]
With the recent changes to scaling (5-5-10-10-20 m), cones and lines now have exactly the same length, making lines almost always worse than cones.  Even the spreadsheet shows it, with its calculations (which already included a higher "Targets per square exponential" value for Lines, 0.40 vs 0.33).

The "30 ft line is better than 15 ft cone" argument no longer matters now that all cones and lines start at 25 ft / 5 meters.

With doubled distances (i.e. 10-10-20-20-40 or 10-10-20-20-50), lines will still be equal to or slightly worse than cones, according to the spreadsheet calculations.  So, I'm reopening this suggestion.

**Comment by mlenser** [comment]
> cones and lines now have exactly the same length

Cones and Lines have been the same size since November 27th, 2020. It is unrelated to the recent change.

I considered a few options to make lines a bit better on their own, but 40 or 50 meters is not a standard distance.

Lines are essentially more useful when you want to avoid allies.
