### ISSUE TITLE
Thunder Step's should protect the caster/ally

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#339]
https://www.kryxrpg.com/spells/thunder-step/

Thunder Step has the option to cause the thunderous boom in the space you teleport into, not just the space you teleport from:

> A thunderous boom sounds, and each creature in a sphere centered on the space you left or the space you teleport to must make a Fortitude saving throw, taking 1d10 thunder damage on a failed save, or half as much damage on a successful one. 

Due to the rule:

> A sphere’s point of origin is included in the sphere’s area of effect.

This means that when you thunder step to a location and decide to make the boom originate from the end-point, you deal yourself damage. If you use the augment and bring another creature, the creature takes damage, too.

I suggest changing it to:

> ... each creature *other than you* in a sphere ...

But the problem is, then it won't hurt you if you thunder-step an incredibly short distance (which might be okay).

Either way, the augment of adding a creature should probably specify:

> The creature does not take damage from the spell.

**Comment by mlenser** [comment]
Thunder Step does not damage you and the joint augment is removed.

The augment doesn't make much sense. You basically blast off and leave a shockwave or land so hard and create a shockwave. Either way the other creature would take the damage.
