### ISSUE TITLE
Some "cone or line" spells could be changed to only one of the two

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#340]
I think:

- **Mind Blast**
- **Scatter**
- **Burning Hands?**

should be a cone and not a line. They make less sense as a directed line that only affects creatures in a narrow beam. 

Burning Hands is iconic for being a cone, and mentions "a thin sheet of flames" (same with Fire Breath), but...I guess it's intended to allow a beam attack just like Agnazzar's Scorcher from 5e?

For the other type - 

**Force Spear** should not be a cone, as it's called "Spear" (just like how Cone of Cold is not a line). If we want to allow that, the name should change. Force Blast? 

**Water Jet** - as a jet, it should be a line, not a cone. It could alternatively be renamed "Gushing Water" or "Water Spray"?

**Comment by DalenWBrauner** [comment]
I'd say Burning Hands, Cone of Cold and Water Jet are all good examples of elemental attacks that are evocative of one shape in particular, but could be channeled into the other shape. I don't think we should be too restrictive in general, unless one of the two options cannot make sense for the spell.

**Comment by mlenser** [comment]
I agree with Dalen. Cone or Line is pretty much all about how you channel it.

**Comment by itamarcu** [comment]
Alright, then in that case - should Cone of Cold allow the user to shoot it in a line? :P

**Comment by mlenser** [comment]
Yes. A line of ice makes complete thematic sense. If anything I'd rename the spell, but it's too iconic.

**Comment by Marcloure** [comment]
D&D has that Somewizard's Scorcher which is basically a line burning hands. I agree that being able to fire spread or concentrated is better for basically all options

**Comment by mlenser** [comment]
Closing this as the goal is to allow cones and lines to be interchangable.
