### ISSUE TITLE
Slow and Slowing Poison might be too weak

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#341]
[Slow](https://www.kryxrpg.com/spells/haste-slow) and [Slowing Poison](https://www.kryxrpg.com/spells/slowing-poison) are both underpowered - they let a single target make a save and on failure they make the target Slowed 1, with a save every turn.

Compare them to [Spirit Drain](https://www.kryxrpg.com/spells/spirit-drain) and [Winter's Bite](https://www.kryxrpg.com/spells/winters-bite) which give you a lot more value for a shorter duration, and the indigo [Prismatic Spray](https://www.kryxrpg.com/spells/prismatic-spray).

I think Slow and Slowing Poison should inflict a much higher slowed condition (my gut instinct - Slowed 3, or Slowed 2 on fail and Slowed 1 on success). They could also implement the mechanic from Prismatic Spray where saving throws every turn reduce the target's slowed level by 1.

**Comment by mlenser** [comment]
Slow and slowing poison last for the duration. The others last for 1 turn. Huge difference.

**Comment by itamarcu** [comment]
Yeah, it's a difference - it makes it about 2-3 times more powerful than "slowed until the end of the creature's next turn" (x3 according to the powers balance sheet).

Still, compared to Prismatic Spray, they're clearly worse.

**Comment by itamarcu** [comment]
Agreed about Prismatic Spray (maybe make a new github issue about it?).

Slow is definitely weak, though. Haste is on an ally so you can count on it to keep working for the rest of the fight, but Slow lets the target make a save every turn (plus an initial one), and on a failure the spell stops immediately (or doesn't work in the first place).

The 5e Slow spell was viable because it let you target a lot of creatures at once and made the slowed condition more debilitating than Slowed 1 is here.

Here, when you cast Slow, there's a 60% chance of slowing for 1 turns, 36% of slowing for 2 turns, 22% for 3 turns, 13% for 4 turns... and you only affect a single creature and you don't get to do any damage or other effect.

Players would rather just cast spells like Cone of Cold, because it has guaranteed value (damage, even on miss) and hits multiple targets. Or the single-target spells mentioned above. Slowing for 1 turn is frequently enough, especially since slowed targets are prioritized so they will die faster.

The Slow spell doesn't have a row in the Powers Balance spreadsheet - I tried manually making one in a copy and it calculated the value as 3.6 (extremely low), though I might have done it wrong.

I think it should be buffed to inflict Slowed 3, and when the target saves the condition decreases by 1.

**Comment by mlenser** [comment]
Once again: the sheet is not meant to give super accurate values to pure conditions. See #273.

**Comment by mlenser** [comment]
Slows makes the enemy 20% more likely to be hit by your allies attacks and fail your allies Reflex saving throws. That's effectively a 20% damage boost to all allies smart enough to attack or use a Reflex save. That's definitely worth a 1 mana spell.

**Comment by mlenser** [comment]
I've opened https://github.com/mlenser/kryx-rpg-issues/issues/350 to address Prismatic Spray.
