### ISSUE TITLE
Psi conversion to stamina dice

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#346]
About this feature for Soulknifes and Monks:

> **Psi**
> During a short or long rest you can meditate to gain 2 stamina dice, which are d8s, for each psi spent. To use a maneuver, you must expend a number of stamina dice based on the maneuver’s cost.

My Soulknife player doesn't like it, another one of my players that is thinking in building a Monk next doesn't like it, and I'm also not a fan of it. The issue is that having to choose between mana and stamina during a rest is not great, it requires too much planning, too bothersome, so it's much easier to safely have only 1 resource pool.

> It's still a fairly better version than other classes get

While that is true, it seems to mostly encourage people to not care with allocating resources and just go with a single one

Kryx commented:
> The option to do it as a bonus action is ok, just need some flavor. Then the issue of planning is nearly gone.

**Comment by mlenser** [comment]
Additional problem:
1:2 ratio is problematic. A full stamina half-character gets 45 stamina. A full man half-character gets 15. 15*2 = 30, not 45. But if we use 1:3 ratio it's also a bit problematic:

### Level 1
- 1:3: 3 stamina
- Stam: 2 stamina

### Level 3
- 1:3: 6 stamina
- Stam: 7 stamina

### Level 5
- 1:3: 12 stamina
- Stam: 11 stamina

### Level 9
- 1:3: 21 stamina
- Stam: 20 stamina

### Level 13
- 1:3: 30 stamina
- Stam: 29 stamina

### Level 17
- 1:3: 39 stamina
- Stam: 38 stamina

### Level 20
- 1:3: 45 stamina
- Stam: 45 stamina

_____________

Ok, 1:3 is a much better ratio. Not excatly perfect, but very very close.

**Comment by Marcloure** [comment]
Haven't the mana to stamina value rate changed from 1:2 to 1:3 when the system changed from 10 mana to 5 mana?

**Comment by Euthrosyne** [comment]
Flavor-wise, you could represent it as a form of Chakra or the Mind over Body principle:
> Psionicists influence the world through the power of their will, and their bodies are no exception to that principle. As a bonus action, a psionicist can focus to convert psi to stamina at a 1:3 ratio.

**Comment by mlenser** [comment]
Soulknife and Monk can now convert psi to stamina dice as a bonus action.

**Comment by mlenser** [comment]
Animate spells and transformation spells like Animate Earth, Animate Fire, Call Beast, Create Homunculus, Wild Shape, and Tree Shape have has their mana to stamina ratios changed to 1:3
