### ISSUE TITLE
Regenerate balance issues

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#352]
- [Heal](https://www.kryxrpg.com/spells/heal) heals 3d8, 60 ft range
- [Regrowth](https://www.kryxrpg.com/spells/regrowth) heals 3d6+half next turn, 60 ft range
- [Regenerate](https://www.kryxrpg.com/spells/regenerate) heals 3d8+half next turn, but can only target yourself
- [Regeneration Potion](https://www.kryxrpg.com/concoctions/regeneration-potion) heals 3d8+half next turn and can be given to any creature

I believe something here is unbalanced. Regenerate is obviously stronger than Heal and Regrowth, except for the fact that you can only use it on yourself. However, Regeneration Potion has no such limits, and you could give it to any creature (though you could say it's limited by preparing it in advance and not during combat?).

Furthermore, Regenerate has the Major Regeneration augment, which is the only way to reattach missing limbs with a healing spell. The fact that it's limited to only yourself, however, makes it impossible to actually heal such injuries in your friends.

My suggestion is that Regenerate becomes identical to Regrowth (3d6 and with range), and both should get the Major Regeneration augment. Regeneration Potion would be lowered to 3d6, as well.

Alternative suggestion: give Regenerate a 1 mana augment to cast it on others, and change Regeneration Potion somehow to be balanced against it (e.g. make its Major Regeneration augment cost 1 more mana).

**Comment by mlenser** [comment]
Half next turn is valued at a much lower value, as you have to wait a turn for its. All of this is on the spreadsheet:
![image](https://user-images.githubusercontent.com/235857/84594769-cdb68c00-ae54-11ea-8b00-6d52be1e8bf2.png)
![image](https://user-images.githubusercontent.com/235857/84594772-d4450380-ae54-11ea-9a54-89bf998948e5.png)
![image](https://user-images.githubusercontent.com/235857/84594792-e8890080-ae54-11ea-82b5-f3ac5b2bc287.png)

> Regeneration Potion has no such limits, and you could give it to any creature

This is true for all potions and one of the perks of using potions.

> My suggestion is that Regenerate becomes identical to Regrowth (3d6 and with range),

You've brought this up before. Regenerate and Regrowth are different spells. Regrowth is a Plant based spell that should not have as much healing flavor as a Life spell. It is meant to give a taste of healing, but not the full meal.

> The fact that it's limited to only yourself, however, makes it impossible to actually heal such injuries in your friends.

This is an issue that should be addressed. I can add an augment.

**Comment by mlenser** [comment]
Regenerate removed from the Life theme. Its Major regeneration augment has been added to Heal
