### ISSUE TITLE
Spellsplinter

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#353]
#### Spellsplinter
*2 stamina, antimagic*
As a reaction, which you take when you see a creature within 5 feet of you casting a spell, you attempt to interrupt the creature and disrupt the casting. Make an attack roll against the creature. If you hit, the creature takes bludgeoning damage equal to your maneuver ability, and must make a Fortitude saving throw. 
On a failure, the creature’s spell fails and has no effect, though the creature does not expend any resources. The damage type is the same as the weapon used.

---

The concept here is a maneuver that a martial character would use to stop someone in their reach from casting a spell. This was an inherent mechanic in 3.5e, and there was even a "[Mage Slayer](http://dnd.arkalseif.info/feats/complete-arcane--55/mage-slayer--1818/index.html)" feat for making it better.

Some design rationales - 
- Mages can counter each others' spells, and have plenty of ways to counter martials' ability to fight effectively. It only makes sense for warriors to have special tactics and maneuvers to use against magic users.
- I chose to make it deal *a bit* of damage (equal to str/dex), for flavor reasons and to let the player feel like they didn't fully waste their resources (balancing the low chance of this maneuver hitting, since it's attack+save). Still, the intent of this maneuver is not to deal damage (for that you should use opportunity attacks or the [various](https://www.kryxrpg.com/maneuvers/backlash) [reaction-attack](https://www.kryxrpg.com/maneuvers/retaliate) [maneuvers](https://www.kryxrpg.com/maneuvers/riposte)).
- The damage is bludgeoning because it makes sense for a quick distracting blow with any weapon or with an unarmed strike. It's also because adding "The damage is of the same type as the weapon used" would've made phrasing awkward, especially since a weapon is not even required for this (martial artists with "magic-blocking" strikes are common in media).
- This is both an attack and an opposed save, for flavor and balance reasons. If it was just a save, it would imply that the disrupting attack auto-hit, which is weird. If it was just an attack, it would probably be too easy, and wouldn't factor in the spellcaster's ability to withstand the interruption. An alternative would be making it an ability check, like Counterspell.
- This doesn't cause the creature to waste the mana expended (or daily uses of a spell) to keep it low level. Stamina dice are less powerful than mana, so a maneuver that fully imitates Counterspell would be worth at least 5 stamina. I don't want this ability to be limited to 5th tier characters, so if there is need for this, it could be an enhancement (for 3 stamina).
- I chose not to keep it simple and not make it a check/attack/save against a DC based on the spell's mana expended, the spellcaster's ability, the damage of the attack, etc - because those are complicated, and because this maneuver doesn't take away the creature's resources (unlike counterspell), and because the flavor here is interrupting the caster physically and not draining away the spell's energy or blocking it.
- I wasn't sure if to add "flavor text" to the maneuver, such as "you attempt to disrupt the spell by timing your attack to hit the creature just as its magic flows out" or "you attempt to bash the creature's throat as it's chanting" or "you attempt to push away the creature's fingers as they're making arcane movements" or even "you attempt to break the creature's focus". If you think there's need for that, we can add something, though I'd like to keep it generic (to fit somatic-only spells, verbal-only spells, creatures with no necks, etc).
- Alternative names: Disrupt Spell, Interrupt, Spell Jam, Thwart Casting.

**Comment by mlenser** [comment]
> The concept here is a maneuver that a martial character would use to stop someone in their reach from casting a spell.

So, it should be a maneuver then?

We're looking at a very high cost though. 5 stamina due to extra attack and ending a spell.


> The concept here is a maneuver that a martial character would use to stop someone in their reach from casting a spell. This was an inherent mechanic in 3.5e, and there was even a "Mage Slayer" feat for making it better.

Mage Slayer in 5e does not stop the casting. 3.5 had completely different rules for casting while in melee so this shouldn't be a source of information for 5e. Mage Slayer in 5e:

> You have practiced techniques in melee combat against spellcasters, gaining the following benefits.
>
> - When a creature within 5 feet of you casts a spell, you can use your reaction to make a melee weapon attack against that creature.
> - When you damage a creature that is concentrating on a spell, that creature has disadvantage on the saving throw it makes to maintain its concentration.
> - You have advantage on saving throws against spells cast by creatures within 5 feet of you.

The second two are part of the Mage Slayer feat. The 1st could be added as an Antimagic Maneuver.

_____________________

### As a spell
The stated goal should be accomplished via a maneuver, but some discussion points:

Mana Drain must be used before the creature's turn and reduces an enemy's mana by 1. This not only reduces mana by 1-5, but is also used as a reaction. This is too strong, even with the attack+save factor.

**Comment by DalenWBrauner** [comment]
Just for clarification:
> - When a creature within 5 feet of you casts a spell, you can use your reaction to make a melee weapon attack against that creature.
> - When you damage a creature that is concentrating on a spell, that creature has disadvantage on the saving throw it makes to maintain its concentration.

These two bullets combined don't allow you to prevent a spell's effect from taking place, right? They would only allow you, at most, to end a concentration spell immediately after it begins?

**Comment by itamarcu** [comment]
> We're looking at a very high cost though

Yeah, like I wrote - my intention is to make it lower cost and available earlier (hence, 2 stamina; fixed that typo). To balance that, I made it...
- low chance of success (hit with an attack and have the creature fail a save)
- let the creature keep its mana (or other resource)
- deal very low damage (might as well be no damage, but I explained my reasoning)

Functionally, you're spending your reaction and your stamina dice to have a chance at canceling the creature's action, though the creature doesn't lose any resources itself. Counterspell is more expensive, which is why it makes the countered spell still cost resources; this one is cheaper, so you only get to prevent the spell now. It's bad if you're using it at the start of a prolonged fight, but it's good to prevent a spellcaster from doing something specific or to keep them neutralized while you're standing close to them.

I'm mentioning that this exists in 3.5 (and PF, and PF2) because this is an interesting game mechanic that is flavorful and has a history of existing. 5th edition removed it as part of simplifying the game, but I believe it's perfect for the maneuver system, and is a good chance to add an interesting maneuver.

**Comment by mlenser** [comment]
> These two bullets combined don't allow you to prevent a spell's effect from taking place, right? They would only allow you, at most, to end a concentration spell immediately after it begins?

Correct.

I added Spell Slayer as a maneuver which can be combined with Mage Slayer for this effect. Spell Slayer:

> As a reaction, which you take when a creature within your weapon’s reach casts a spell, you can make a melee weapon attack against the creature. If the attack is made with a weapon wielded in one hand, add half the result of one of the stamina dice to the attack’s damage roll.

**Comment by itamarcu** [comment]
The Spell Slayer maneuver is nice (though that name is a bit odd since it doesn't slay spells :P), and it fits the theme, but it's basically just another one in the set of "opportunity attack alternatives" - reaction maneuvers that react to something (hit, miss, movement, spell), let you make an attack, and add a bit of damage.

The concept here is very different - you're not trying to deal damage, you're trying to disrupt a spell that is being cast.

**Comment by mlenser** [comment]
> let the creature keep its mana (or other resource)

Ah, I missed that. But reactions occur after the trigger so in this case the mana is already spent. The mechanics of the system wouldn't allow you to shove the mana back in.

### Evaluation of action denial

I don't think this maneuver should exist at a low cost. Denying an action is huge. PCs have tons of stamina and if the martial uses all of its stamina to stop spells from a lich boss then the fight is over. This is not a trivial ability that should be available for a low stamina cost.

**Comment by mlenser** [comment]
> it's basically just another one in the set of "opportunity attack alternatives" - reaction maneuvers that react to something (hit, miss, movement, spell), let you make an attack, and add a bit of damage.

So basically exactly what the first bullet of mage slayer does? :)

Also: The damage isn't just a bit. Bonus action maneuver + reaction maneuver to attack again is a significantly higher damage result for the rounds where that occurs. It's very powerful.

**Comment by mlenser** [comment]
Actually, I don't think this should exist at all. Even at 5 mana a Warrior could use this maneuver 8-9 times. Magic casting bosses would become trivial.

I believe replicating the RAW option of Spell Slayer reaction to attack + Mage Slayer feat to be more likely to end concentration is the best the system should offer.

**Comment by itamarcu** [comment]
Yeah, the potential of using this every round is high. Counterspell can do the same, but at a very high cost and with some chance of failure. Here, the cost is lower, so the chance of failure is higher - assuming 64% hit chance and 51% fort fail chance, this has a 32% chance of countering. I felt that's a fair chance for a cost like this, but maybe it could be reduced further, perhaps depending on mana expended on spell?

(Also, keep in mind that this only works in melee - spellcasters who don't want the chance to be neutralized can (and should) avoid melee for this reason, among other reasons like being stabbed.)

**Comment by itamarcu** [comment]
Counterspell itself is 2 mana and on 5th level spells you get a 25% chance (+5% per additional mana spent, and assuming same spellcasting modifier). It's much better if you identify the spell, but I don't know the chances of that happening. A mage could cast Counterspell a lot of times against magic casting bosses to neutralize them in the same way (and from a distance, and taking away their resources). So, I think it's comparable enough to allow a maneuver to do the same, though it might require tweaking the chances or cost.

**Comment by mlenser** [comment]
I don't think you see how powerful this ability is. So let me create an equivalent, but against martials:

### Melee Smasher
*2 stamina*
As a reaction, which you take when you see a creature within 5 feet of you make a weapon attack, you attempt to interrupt the attack. Make an attack roll against the creature. If you hit, the creature takes bludgeoning damage equal to your maneuver ability, and must make a Fortitude saving throw. 
On a failure, the creature’s attack misses and the creature is incapacitated until the end of its turn. The damage type is the same as the weapon used.

This maneuver would completely nullifer martial enemies just the same as the proposed manuever would completely nullify spellcasting enemies. The effect is pretty much the same.

**Comment by itamarcu** [comment]
I appreciate the equivalent (and I'd compare it to [Misdirection](https://www.kryxrpg.com/maneuvers/misdirection), 2 mana to prevent an attack by redirecting it), but I heavily disagree with "completely nullify" - this is a 30% chance of success, and it only works in melee. I think if we increase the cost (even up to 5 stamina) and decrease the chance (e.g. making it an attack and then a check against DC 10+spellcasting+mana, no advantage for identifying), it can fit and be balanced, just like how Counterspell is.

**Comment by DalenWBrauner** [comment]
I'm not sure Misdirection is a fair comparison. In that case, the effect still has to occur, just perhaps not the ideal target. (Which would also have radically different implications when applied to spellcasting.) The effect isn't prevented.

I generally agree that a Substantially Weaker Counterspell is notable even at 5 stamina. But rather than advocate for its inclusion or exclusion, I just have some tangental design questions.

> The damage isn't just a bit. Bonus action maneuver + reaction maneuver to attack again is a significantly higher damage result for the rounds where that occurs.

This part can be mitigated by the maneuver simply not dealing damage, right? I believe it makes sense flavor-wise that a person could interact with/disrupt/be a general nuisance to a spellcaster without inflicting any lasting injury.

> But reactions occur after the trigger

Hrmm... Could "when you observe someone preparing to cast a spell" be a trigger, in the general case? The intention being, as long as you properly observe and recognize someone _about_ to cast a spell (so hidden creatures or particularly subtle casters would avoid this), you have _just enough_ time to react before the spell is fully-formed and the mana is spent.

**Comment by itamarcu** [comment]
> Misdirection 

Yeah, it's not a perfect comparison, it was just meant to show that an ability with a chance of negating an enemy's attack already exists. [Misdirection](https://www.kryxrpg.com/spells/misdirection) and [Instinctive Charm](https://www.kryxrpg.com/spells/instinctive-charm) can also do it for attacks, and like I said, Counterspell can do it for spells. All of these are situational to a certain degree and have a certain failure chance, so if these abilities can be balanced, I believe a maneuver can be balanced as well - the fact that a spell costs an entire action indeed makes it stronger, so that's why I'm adding drawbacks (situational, low chance, little to no damage, negative resource balance) and am ready to add further drawbacks.

> The damage isn't just a bit
> This part can be mitigated

Heh, I think we had a misunderstanding here - I was saying "a bit" when I referred to the extra damage granted by maneuvers such as [Retaliate](https://www.kryxrpg.com/maneuvers/retaliate) - I was referring to the extra ~3 damage (half stamina die), mlenser thought I was referring to the entire maneuver (which is an entire attack plus that ~3 damage), and you thought he referred to the damage in my suggested maneuver (3-5).

> trigger

Yeah, maybe the trigger could be rephrased to be something like "preparing to cast a spell". If we really can't find a way to phrase it in a way that fits the rules, I guess there's no choice but to make the mana lost on a countered spell, and increase the cost or decrease the chances or restrict it further (e.g. to spells that cost 2 mana or less).

There's plenty of potential balance directions to take this maneuver - I just started with what felt like a good balance between flavor and mechanics. I think this maneuver could have its cost increased to 3-4 mana and it could have its chances reduced further against higher-mana magic, or even be limited to small spells (e.g. spells that cost <2 mana, or bonus action and reaction spells).

**Comment by mlenser** [comment]
> Actually, I don't think this should exist at all.

I still believe this. Especially after [calculating out Counterspell](https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=1867996895). Counterspell is a huge investment in skills or a ~45% chance. A maneuver, due to the reaction, must drain the mana. The wording can't be manipulated to interrupt and not drain the mana as that isn't how reactions work in 5e.

So if this is as strong as counterspell then it's ~6 stamina which is not possible.

Spell Slayer maneuver + Mage Slayer feat can accomplish this for concentration spells. I'm not sure more can or should be offered.

**Comment by itamarcu** [comment]
I'd really want to put this into the game, since it feels very flavorful and interesting to play with/around, but if the system just can't allow for a maneuver this strong I guess this should be discarded.

I'm gonna make one last suggestion, hoping it's balanced enough to consider: put it at 4 stamina, make it just like Counterspell, remove identification bonus, limit it to a 5 ft range (unlike Counterspell's 60 feet), and restrict it to reaction and bonus action spells.

This would give you a 50% chance against a 1 mana spell, 40% against 2 mana, 30% against 3 mana, and so on. It's a chance low enough to feel fair compared to counterspell (at its worst). Restricting it to bonus action and reaction spells reduces the power of neutralizing an enemy's action, and still keeps the flavor of a skilled fighter preventing the enemy from teleporting away or casting counterspell.

#### Spellsplinter

*4 stamina, antimagic*

As a reaction, which you take when you see a creature within 5 feet of you casting a spell with a casting time of 1 bonus action or 1 reaction, you attempt to hit the creature at just the right moment and place to disrupt the spell. Make an ability check using your maneuver ability. The DC equals 8 + the creature’s spellcasting ability + twice the spell’s effective mana.

On a success, the creature’s spell fails and has no effect.

**Comment by mlenser** [comment]
There is no such thing as spell failure in 5e, which is what your idea effectively implements based on an attack instead of based on armor or other conditions as it was in earlier editions.

> I believe replicating the RAW option of Spell Slayer reaction to attack + Mage Slayer feat to be more likely to end concentration is the best the system should offer.

> Spell Slayer maneuver + Mage Slayer feat can accomplish this for concentration spells. I'm not sure more can or should be offered.
