### ISSUE TITLE
Terrifying Visage augment might be wrong

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#354]
[Terrifying Visage](https://www.kryxrpg.com/spells/terrifying-visage):
> (...) At the start of each of its turns, the creature must make a Will saving throw. (...) On a failed save, the creature takes 6d6 psychic damage and is frightened until the start of its next turn.

It has this augment:
> ***Visions of Horror***. You can expend 1 additional mana to cast the spell as a reaction, which you take when a creature makes an attack roll against you.

The augment is pretty weird (and bad), because other than the faster casting time, this spell actually has no immediate effect. It only applies at the start of the creature's next turns. This makes it (as far as I know) the only reaction spell to cause an effect that only applies one round later.

I think it should be:
> ***Visions of Horror***. You can expend 1 additional mana to cast the spell as a reaction, which you take when a creature makes an attack roll against you. The creature must immediately make the saving throw.

**Comment by DalenWBrauner** [comment]
This lead me to notice something else strange:
> and cause it to regard itself as a manifestation of its deepest fears.

This makes it sound like the target is becoming afraid of itself, rather than afraid of the caster. I'm not sure how the frightened condition is supposed to work when you're the source of your own fear.

**Comment by mlenser** [comment]
> This makes it sound like the target is becoming afraid of itself, rather than afraid of the caster.

It isn't meant to use the caster as the source of fear. https://www.d20pfsrd.com/magic/all-spells/h/horrifying-visage has a good exmaple of how it should probably be worded:

> You choose one kind of creature, object, or image within the area of the spell when it is cast that triggers the phobia.

**Comment by mlenser** [comment]
Terrifying Visage reworded to be clear who or what the target is afraid of

**Comment by itamarcu** [comment]
Being reminded of this issue made me realize that it was never fixed - the reaction augment should have this appended to it:
> The creature must immediately make the saving throw.

**Comment by mlenser** [comment]
#354
