### ISSUE TITLE
Increase Sending to 2 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#358]
It's a 3rd level spell in RAW, and sending a global or interplanar message should not be so easy that a novice mage can do.

**Comment by mlenser** [comment]
Sending was 2 mana in my 10 mana system, not 3.. During the conversion to 5 mana the interplanar message was moved to an augment. The base version is within 5 miles so this is already done.

**Comment by Marcloure** [comment]
Oh, sorry, I did not notice that the range was limited to 5 miles as a 1 mana spell
