### ISSUE TITLE
Bestial Transformation: Tough Hide should probably not stack with armor

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#360]
Natural Armor typically doesn't stack with armor.

**Comment by itamarcu** [comment]
Perhaps make it a set AC, such as 17, or 15 + DEX (max 2)?

**Comment by Marcloure** [comment]
Other AC spells (mage armor copies) give 13+Dex (max 4)

**Comment by mlenser** [comment]
Bestial Transformation and Bestial Transformation Potion Tough Hide option changed to a base AC formula instead of an AC bonus

**Comment by Marcloure** [comment]
Ok, now Tough Hide is just a much weaker version of Barkskin and other mage armor copies, since it lasts for much less and requires concentration.

**Comment by mlenser** [comment]
We have a problem with this. Fly is concentration, 5 mins/mana, a lot of the options are 1 hour/mana, and a few are 4 hours/mana.

Should it be split?

**Comment by Marcloure** [comment]
It has the benefit of giving a bunch of effects with 1 concentration, so it's fine if the duration is lower. But that only makes sense if you combine more than 1 effect.

**Comment by mlenser** [comment]
Well, only 1 of the effects has concentration that I could see. Flight.

**Comment by mlenser** [comment]
- Bestial Wings split from Bestial Transformation [#360](https://github.com/mlenser/kryx-rpg-issues/issues/360)
- Tough Hide part of Bestial Transformation changed so that it lasts longer [#360](https://github.com/mlenser/kryx-rpg-issues/issues/360)
