### ISSUE TITLE
Levitate should be added to Telekinesis

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#361]
[Levitate](https://www.kryxrpg.com/spells/levitate) should be added to Telekinesis. That theme can already cast Telekinesis and Reverse Gravity, so levitating or flying should be within its capabilities. There's a lot of psionic characters shown to hover above the ground or even fly, so this should be flavorful and thematic.

**Comment by mlenser** [comment]
Levitate added to Telekinesis
