### ISSUE TITLE
Mind Flayer Psion should have a higher Psionics skill bonus

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#362]
I think [Mind Flayer Psion](https://www.kryxrpg.com/monsters/mind-flayer-psion) should have a higher Psionics skill bonus. Currently, it has +6 to many skills, but only +4 to psionics.

**Comment by mlenser** [comment]
It has expertise. This is a bug.

**Comment by mlenser** [comment]
fix monster skills
