### ISSUE TITLE
Synaptic Static issues

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#363]
[Synaptic Static](https://www.kryxrpg.com/spells/synaptic-static)

1. It's phrased oddly - the description for muddles thoughts should be before the phrase about a success. Alternatively, it should say "While a creature has muddled thoughts, ...".
2. There should probably be another Will save against the muddled thoughts every turn. The 5e spell works like that, and I think this one should, too, otherwise it's incredibly strong.

**Comment by mlenser** [comment]
wording order fixed
