### ISSUE TITLE
Exploding Ice Sculpture augment

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#364]
One of my players suggested to add an option or augment to the Ice Sculpture spell to make it explode and deal cold and piercing damage in the area surrounding it. It should probably be as a trigger when someone gets close so you can use it as a warding/trap spell.

**Comment by Paulorpribeiro** [comment]
Nice idea, I second it. Perhaps slowed one as well, but I agree the main point of the "trap" should be deal damage

**Comment by DalenWBrauner** [comment]
As the person who put Ice Sculpture together, I didn't really intend for it to be much of an offensive option. I don't have any opinion _against_ using it in such a way- that's certainly cool- but an icy trap almost feels to me like a different spell.

But I could see a +1 mana "detonation" augment, and then a +2 mana "triggered detonation" augment. We would just need to decide:
1. what kind of save, radius, conditions, and how much damage
2. how to word the remote trigger (I know there are other spells like that, I'm just being lazy)

**Comment by mlenser** [comment]
This idea is a bit hard to implement. I've tried a few times and failed. I think Glyph of Warding pretty much covers the niche anyways.

Closing this for clarity. Not super opposed, but it's difficult to do and mostly covered already.
