### ISSUE TITLE
Add Yuan-Ti species

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#367]
The evil sneak people are cool, and if we implement feats for species, it becomes easier to handle their magic resistance.

**Comment by mlenser** [comment]
I don't think these can be made into a species with their magic resistance. It's 3x as powerful as the gnome ability.

**Comment by itamarcu** [comment]
The magic resistance is not an integral part of the species, it can be dropped.

More important features of the yuan-ti: they are snake people, they are emotionless (or at least less emotional than other species), they are immune to poison.

Lots of people online tried to make homebrew "fixed" versions of the Yuan-Ti - I think that's enough inspiration to make one without magic resistance (or with gnome-like magic resistance).

**Comment by Marcloure** [comment]
I also think removing magic resistance is fine. Many people like to play snake people

**Comment by mlenser** [comment]
> gnome-like magic resistance

Gnomes are only Will saves. Yuan-ti are all saves, which makes them too strong. There could be something here, but likely will be too difficult to make balanced.

> Lots of people online tried to make homebrew "fixed" versions of the Yuan-Ti - I think that's enough inspiration to make one

If you're interested, please help by suggesting how it should be built. I don't see too many features beyond poison stuff and darkvision.

**Comment by itamarcu** [comment]
Could Yuan-Ti get only Fortitude saves, then? It will fit with their scales and resistance to poison.

**Comment by mlenser** [comment]
Mechanically, sure. But that doesn't seem to capture the flavor of Yuan-ti. They already have poison stuff, so shouldn't double up on fort vs magic to fulfill the resistant to poisons niche.

**Comment by Marcloure** [comment]
It would be cool if Yuan-ti gained something related to them being emotionless. Maybe creatures have disadvantage on insight checks to determine a Yuan-ti's feeling or intent?

**Comment by itamarcu** [comment]
The Yuan-Ti Broodguard monster (from Volo's) has this:

> **Variant: Shed Skin (1/Day)**
> The yuan-ti can shed its skin as a bonus action to free itself from a grapple, shackles, or other restraints. If the yuan-ti spends 1 minute eating its shed skin, it regains hit points equal to half its hit point maximum.

I think the ability to shed your skin to get out of grappled/restrained is really cool. The part about eating it is amusing but can be dropped.

Also from that monster:
> **Mental Resistance**. The broodguard has advantage on saving throws against being charmed, and magic can't paralyze it.

**Comment by mlenser** [comment]
Glancing around at homebrew options I think the magic resistance is core to the Yuan-ti. And that makes it beyond a player species.

Closing this unless someone comes up with something.

**Comment by itamarcu** [comment]
I don't think magic resistance is core to Yuan-Ti. I think being a snake person is core, and I'm sure people would play yuan-ti characters without magic resistance.

I'm in favor of adding the race without that feature (or with resistance only to will or fortitude magic - many people houserule the yuan-ti the same way as gnomes), and if anyone will say there's any problem, we could revisit it.
