### ISSUE TITLE
Stacking AC bonuses (specifically from dual wielder and brawler feats)

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#372]
Brawler and dual wielding AC part of the feats stack, as written. There is a discussion of wether they should stack or not, and I think they shouldn't, but I'm just pointing that out as I'm not sure this is intended.

**Comment by mlenser** [comment]
Brawler updated to remove AC bonus

**Comment by mlenser** [comment]
- **Classes**
  - **Psionicist**
    - Martial arts damage adjusted with the new Punches in Bunches feat
- **Themes**
  - **Skirmish**
    - Punches in Bunches replaces the Brawler feat
  - **Vanguard**
    - Punches in Bunches replaces the Brawler feat
