### ISSUE TITLE
Brawler feat doesnt completely apply to monk

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#373]
The second bullet of the feat does not apply to a monk using weapons or natural attacks, only unarmed strikes

I would suggest either changing the feat text to include such options or change the martial arts text in the monk to something like:

- You can roll a d4 in place of the normal damage of your unarmed strikes This damage die increases by one step when you reach 5th level and once more when you reach 17th level in this class. This increased damage also apply to your natural weapon or monk weapon attacks if they are higher.

I like this option better, because the martial arts feature, as written with fixed dies at lvls 5 and 17, doesn't match the "increased die size" text of the feat.

**Comment by mlenser** [comment]
> as written with fixed dies at lvls 5 and 17, doesn't match the "increased die size" text of the feat.

Martial arts text gives you dice, which brawler improves. How does it not work?

**Comment by mlenser** [comment]
Changed wording:

> You can roll a d4 in place of the normal damage of your unarmed strike, natural weapon, or monk weapon if you are a psionicist with the monk archetype. If your unarmed strike, natural weapon, or monk weapon already uses a die for damage, that die increases by 1 step. From d4 to d6, d6 to d8, and d8 to d10.

**Comment by mlenser** [comment]
- **Classes**
  - **Psionicist**
    - Martial arts damage adjusted with the new Punches in Bunches feat
- **Themes**
  - **Skirmish**
    - Punches in Bunches replaces the Brawler feat
  - **Vanguard**
    - Punches in Bunches replaces the Brawler feat
