### ISSUE TITLE
Opinions about the Brawler feat

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#374]
I'm not sure I get the purpose of the [Brawler](https://www.kryxrpg.com/feats/brawler/) feat. It seems like it's just a bland "hey, monk, your attacks now deal more damage" feat, which is boring and would make all monks who don't take it feel weaker.

There's precedence for other feats that increase a class's DPR (Cleave, Dual-Wielder, Polearm Master) but this one seems like it just applies to 90% of monks, since they all tend to use unarmed strikes. I would much rather make this into multiple feats that enhance different styles or aspects of the monk.

On the other hand, as a feat that just lets *non-monk* characters be brawlers - I think it's fine and should even be a bit better (I think AC and 1d4/1d6 damage die would be good enough, perhaps also granting improvised weapons proficiency because it literally mentions that in the description).

So, my suggestion is to make it aimed mostly at non-monk characters, and improve it for them:

> Accustomed to rough-and-tumble fighting using whatever weapons happen to be at hand, you gain the following benefits:

> - You become proficient in improvised weapons. If you are a psionicist with the monk archetype, they are considered monk weapons for you.
> - While you are wearing no armor and not wielding a shield, your AC equals 13 + your Dexterity.
> - Your unarmed strikes can use a d6 for damage.

If there's a need for a feat that improves DPR of monks, I'd rather see a new one that is more interesting than a straight-up increase to the martial arts die.

**Comment by Marcloure** [comment]
*If* the monk needs a DPR boost, I would rather see they being able to use Flurry without a bonus action

**Comment by itamarcu** [comment]
@Marcloure that's already changed in the latest release.

> **Flurry of Blows** (3rd)
> When you use the Attack action with an unarmed strike, a natural weapon, or a monk weapon on your turn, you can make one additional unarmed strike.

**Comment by mlenser** [comment]
Monks either have to do less damage than other classes/archetype or they need to take a feat to do equivalent damage. I chose the second option.

This feat applies to anyone with the Brawler fighting style or a Monk.

> If there's a need for a feat that improves DPR of monks, I'd rather see a new one that is more interesting than a straight-up increase to the martial arts die.

Feel free to suggest an alternative.

**Comment by mlenser** [comment]
> You become proficient in improvised weapons. If you are a psionicist with the monk archetype, they are considered monk weapons for you.

I have said this to you many many times now: The brawler fighting style is where proficiency with improved weapons comes from. Please remember it.

> While you are wearing no armor and not wielding a shield, your AC equals 13 + your Dexterity.
This isn't meant to give an armor boost.

> Your unarmed strikes can use a d6 for damage.

That isn't compatible with the Brawler Fighting style or monk. It's not balanced.

**Comment by mlenser** [comment]
Closing this issue as this is not the direction that this feat is intended to go.

Please, do feel free to suggest an alternative for Monk's damage.

**Comment by mlenser** [comment]
- **Classes**
  - **Psionicist**
    - Martial arts damage adjusted with the new Punches in Bunches feat
- **Themes**
  - **Skirmish**
    - Punches in Bunches replaces the Brawler feat
  - **Vanguard**
    - Punches in Bunches replaces the Brawler feat

**Comment by itamarcu** [comment]
ignore everything I've said, this feat is perfect and it has a perfect name now. :D
