### ISSUE TITLE
Punches in bunches opinion and feedback

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#376]
This is not critical, but I'd like to state that I don't like the name. I think its too cartoony, I much prefer brawler for this feats name.

Now, I didnt check the new balance numbers for the monk, but I think this feat should allow a monk to use his ability mod to the extra attack granted by the feat, for one reason only:
Monk
1st level: martial arts feature - one additional attack with ability mod (2 total)
3rd level: flurry of blows feature - one additional attack with ability mod (3 total)
5th level: extra attack feature - one additional attack with ability mod (4 total) or a spell (Not sure, do they have spell strike?)

Punches in Bunches feat (4th level): 
one additional attack **without** ability mod (4 with mod +1 without)

I think it's extra bookkeeping to figure out which attack adds or not your ability mod for little difference (in 5 attacks, the diff between 4 and 5 times ability mod to damage is a small percentage). 
I would prefer if only monks get to add their ability mod to the extra attack granted by this feat.

**Comment by Paulorpribeiro** [comment]
Other than that, the change in flavor from the previous version of brawler feat is very welcome

**Comment by mlenser** [comment]
> I think its too cartoony, I much prefer brawler for this feats name.

Brawler has a very different feel and is taken by the fighting style. I'm open to other names if there are ones that capture the thematics of hitting a lot.

> Now, I didnt check the new balance numbers for the monk

Well, then any conclusion you make isn't so valuable. See https://docs.google.com/spreadsheets/d/1sGvcz9vbq9yk4kRBEY6ZYGWhGO6-t7CWudznQcWPk74/edit#gid=2110595549

> I think it's extra bookkeeping to figure out which attack adds or not your ability mod for little difference

It's not a little difference. Its a difference of 3.5 DPR vs 7.1 DPR. Feats like Dual Wielder, Great Weapon Master, Polearm Master, etc offer around 3.5 DPR at level 20, so does this feat.

**Comment by itamarcu** [comment]
I agree with the fact that adding the ability modifier would make it overpowered - but I'd like to also agree that adding your ability modifier to 4 of the 5 attacks is extra bookkeeping that could frustrate people or be easily forgotten.

It's kind of ridiculous that these five attacks come from five different sources (normal attack, extra attack, martial arts, flurry of blows, punches in bunches) and have slightly different rules (first two can be any attack, and then you get either light or unarmed, and then you get only unarmed, and then you get only unarmed without ability mod).... this really feels complicated.

I don't have an easy solution, though. Simply pointing it out.

**Comment by Paulorpribeiro** [comment]
> Well, then any conclusion you make isn't so valuable. See

That's not so nice to dismiss the opinion like that, but I'll take it, since it makes sense at least.

> It's not a little difference. Its a difference of 3.5 DPR vs 7.1 DPR

That's also not accurate. The value of the feat, as written is between 1.8 and 3.5 across the levels. The difference between with and without mod is also between 2.6 and 3.6. If you're balancing only for max level (which is a debatable decision, but let's go with it) the difference is indeed 3.6, and the value of the feat doubles with the change I proposed

That said, I reiterate what I stated: having 5 attacks, where 4 apply your mod and one doesn't is not practical.

**Comment by mlenser** [comment]
> That's not so nice to dismiss the opinion like that

I've asked time and time again that people use data to make suggestions. If you don't understand the DPR then the suggestion you make is not valuable. If anything, the suggestion becomes a waste of time because you haven't taken the time to understand the core math. It would be different if this was super complex math, but the Power balance sheet and the DPR sheet are available for all and suggestions in that area do expect that you look at them.

> That's also not accurate.

Again, please refer to the DPR sheet.

![image](https://user-images.githubusercontent.com/235857/85200642-7ce1e000-b2f9-11ea-9ed8-34d7e1d8793c.png)

You'll see that line 34 at 20th level is 7.1 DPR while line 38 is 3.5 DPR. Huge difference.

>  If you're balancing only for max level

I'm balancing for all levels. I just used 20 as a reference. It's a problem at all levels.

> having 5 attacks, where 4 apply your mod and one doesn't is not practical.

Why? TWF without Dual Wielder does it.

**Comment by Paulorpribeiro** [comment]
> Why? TWF without Dual Wielder does it.

Except you don't have 5 attacks, you have 3, but yes, it is a similar issue.

Monk is a hard one to balance, and this feat has to be balanced around the monk and not be complete crap to others. Not an easy task

**Comment by itamarcu** [comment]
With TWF, looking at classes other than the Monk, I'm pretty sure all classes have one attack, one extra attack, and then the offhand attack. That's more manageable (3 vs 5), uses rules that are shared between all characters and familiar to everyone, and becomes more consistent once the character takes Dual Wielder (which the majority of such characters will do).

**Comment by itamarcu** [comment]
Maybe we could make this feat add the ability modifier but with a restriction that balances the extra damage? For example, if to make this extra attack you must not move during your turn.

**Comment by mlenser** [comment]
> Maybe we could make this feat add the ability modifier but with a restriction that balances the extra damage? For example, if to make this extra attack you must not move during your turn.

Pretty much all options only have 1 feat that can boost DPR in a meaningful way. So giving unarmed two feats tha tboost DPR would make Monks more powerful than other options. GWM + Polearm is an exception

**Comment by itamarcu** [comment]
I think you misunderstood me - I agree it should be just one feat, I'm suggesting that we add a restriction to it instead of reducing the damage (to make it a bit easier to remember, and more interesting). Such as:

> **If you haven't spent your movement during your turn**, when you use the Attack action with an unarmed strike, a natural weapon, or a monk weapon (if you are a psionicist with the monk archetype) on your turn, you can make one additional unarmed strike. **When you do, your movement becomes 0 until the end of your turn**.

Or:

> When you use the Attack action with an unarmed strike, a natural weapon, or a monk weapon (if you are a psionicist with the monk archetype) on your turn, you can make one additional unarmed strike **against a creature other than the creature you attacked**.

Or:

> When you use the Attack action with an unarmed strike, a natural weapon, or a monk weapon (if you are a psionicist with the monk archetype) on your turn, **if you miss with two or more attacks**, you can make one additional unarmed strike.

**Comment by mlenser** [comment]
We had such a restriction: bonus action. But Marcloure specifically didn't want that.

I don't think the rest are balanced.

**Comment by Marcloure** [comment]
>  I'm open to other names if there are ones that capture the thematics of hitting a lot.

~MUDA MUDA MUDA~

I don't like the name also, so I'll see if I can come up with a few suggestions.

---

> Marcloure specifically didn't want [bonus action].

It's not that I don't want, but losing an attack to do a maneuver can easily just not be worth it. And if just attacking is better than using a maneuver, then I think it's no good.

**Comment by mlenser** [comment]
> It's not that I don't want, but losing an attack to do a maneuver can easily just not be worth it. And if just attacking is better than using a maneuver, then I think it's no good.

I fully agree with it should be removed, that's why I went through the effort of rebalancing it. 😃

**Comment by Marcloure** [comment]
Some names suggestion instead of Punches in Bunches:

- Follow Up Jab
- Quick Jab
- Sequencing Jab / Slam / Blow
- Sequencing Attacker

**Comment by mlenser** [comment]
All of those are much worse, imo.

**Comment by Paulorpribeiro** [comment]
I like follow up jab, but it sounds like you should use this as an off hand attack after an attack with any one-handed weapon, which is not the case (yet? It's not too powerfull, its like always having a dagger in your offhand).

**Comment by itamarcu** [comment]
Does anyone have ideas or opinions for the possibility of allowing you to add your ability modifier but restricting the attack?
My suggestions (from the earlier comment, plus some more ideas):
- Can only make this attack if you stay in place for the entire turn
- Can only make this attack against a different creature
- Can only make this attack if you missed twice already during this turn
- Can only make this attack if you have more than half your hit points 
- Can only make this attack against a grappled creature
- After making this attack you cannot make opportunity attacks until your next turn
- Change to "Once per turn, if you have advantage on an unarmed strike (...), you can forego the advantage to make an additional attack."

If you think one of these is good enough or have your own idea to suggest, I think it would help make this feat better to keep track of and more interesting to play with. The name change might be affected by this, too.

**Comment by mlenser** [comment]
> Can only make this attack if you stay in place for the entire turn

No, it's still the same value. Just set in old 3.5 ways of getting more attacks if you don't move. This shouldn't exist in 5e, at all.

> Can only make this attack against a different creature

Then its value is only effective in edge cases. It becomes like the bullet of cleave that I removed because it exists as a maneuver. Edge cases should be manuevers, not full-time feats.

> Can only make this attack if you missed twice already during this turn

This is the one that may work

> Can only make this attack if you have more than half your hit points

Why? This exists nowhere else in 5e. I think a simple "don't add ability mod to one attack" is far more simple than this. And its value is not very good as I hope you're not below half your hit points more than 25% of the time, much less 50%.

> Can only make this attack against a grappled creature

This would force monks to be grapplers. No.

> After making this attack you cannot make opportunity attacks until your next turn

Why? You're inventing new mechanics that don't exist in 5e with more complexity than what you're trying to "fix"

> Change to "Once per turn, if you have advantage on an unarmed strike (...), you can forego the advantage to make an additional attack."

The value on this is not so great for a monk and Rapid Strike already exists.

**Comment by Paulorpribeiro** [comment]
I'll just go ahead and suggest another one: 
When you spend stamina to use a maneuver, you can make an additional unarmed strike when you take the attack action

**Comment by itamarcu** [comment]
I kinda like that - it would be similar to the 5e class features UA rule:
> If you spend 1 ki point or more as a part of your action on your turn, you can then immediately make one unarmed strike as a bonus action.

It would need to be phrased a bit better, because some maneuvers apply to an attack you just made and some maneuvers apply to an attack you are about to make.

**Comment by mlenser** [comment]
The problem with it is that it'd discourage maneuver usage outside of combat. Maneuvers that give you advantage on jumping, etc. Those should be encouraged.

**Comment by Paulorpribeiro** [comment]
Well, the feat itself is combat oriented. There are both feats and maneuvers that are combat oriented and non-combat oriented. Combat oriented feats will naturally encourage combat oriented maneuvers. You wouldnt expect savage attacker to encourage non combat maneuvers either

**Comment by itamarcu** [comment]
That's true, but I think it's only a small effect. Yes, making your maneuvers deal a bit more damage functionally makes your stamina more efficient when used during combat, but the same is true for feats like Acid Adept that make your spells deal more damage and thus technically discourage you from casting utility spells.

I'd be more worried about how it might work maneuvers taken outside the attack action (bonus action attacks, reaction maneuvers) but I think we could do the math to see if the additional attack should be added there or not.

**Comment by Paulorpribeiro** [comment]
My idea (maybe need a bit of work on the phrasing) is that if you use a maneuver in your turn (whatever action it might use) you can make an additional unarmed attack as long as you take the attack action on that turn.

**Comment by mlenser** [comment]
Locking this as Punches in Bunches is done and a solid feat. If you think there are better options, feel free to refine it and open a new feat.
