### ISSUE TITLE
Air Genasi has three damage resistances

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#377]
...Is this intentional?

[Air Genasi](https://www.kryxrpg.com/character/species/genasi)

> **Elemental Resistance**. You have resistance to concussion, lightning, and poison damage.

I think this should be a single resistance, either to lightning or to concussion.

**Comment by mlenser** [comment]
Yes
![image](https://user-images.githubusercontent.com/235857/85203304-0e0e8200-b30d-11ea-9eb3-4e2b7084cfe1.png)

> lightning or to concussion.

You've brought this up several times now. Storm based options are resistant to Lightning and Concussion. Please don't raise it as an issue in the future.

_____________

Fire is meant to have fire and posion. I'll fix that.

**Comment by mlenser** [comment]
Fire Genasi are resistant to fire and poison damage as intended
