### ISSUE TITLE
Planes have Minute Meteors and Crown of Stars

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#379]
Both spells are basically the same, but one blinds while the other burns. I think Minute Meteors can remain in fire if we reflavor it, or just scrap it away.

Note: crown of stars isn't concentration, while minute meters is.

**Comment by itamarcu** [comment]
I think it would be neat if the spells belonged to both Light and Planes, or both Fire and Planes.

A fire sorcerer will obviously conjure little balls of fire to throw at enemies, but the planar wizard will open a little rift to the fire dimension and borrow a few balls of fire from there.

**Comment by mlenser** [comment]
> A fire sorcerer will obviously conjure little balls of fire to throw at enemies

A meteor is different than a little ball of fire.

**Comment by Paulorpribeiro** [comment]
Minute meteors is a classic fire spell, and much more themtic in fire than planes, IMO. Crown of stars maybe fits planes better than light, specially the new Void/Space dimension the theme is going lately (which is great, maybe not fit to every campaign, but great)

**Comment by mlenser** [comment]
> Minute meteors is a classic fire spell

Is it? I don't see it in AD&D or 3.5. But it can be hard to find these things.

Fire could have a spell like this if there is a reason for it. Meteros, though, should be cosmic.

**Comment by mlenser** [comment]
Minute Meteors added to Fire for now. I'm not sure that is the best long-term option with Cosmos.

**Comment by mlenser** [comment]
Also fixed the concentration and rebalanced them

**Comment by Paulorpribeiro** [comment]
This spell has only to do with meteors because of its name. It could be "summon fire seeds", have the same effect and be firm in the fire theme. We wouldn't want to put it into plants, because seeds? I think a copy of meteors to planes theme (or cosmos) is a nice addition. Fortunately we already have grown of stars for it.

**Comment by Paulorpribeiro** [comment]
Also, while not as classic as fireball or magic missile, Melf's Minute Meteors (or MMM) has been around for some time.

**Comment by mlenser** [comment]
> Melf's Minute Meteors (or MMM) has been around for some time.

In what other editions?

**Comment by Paulorpribeiro** [comment]
I dont have the old editions books on me anymore, but 3.5 for sure (maybe in the arcane classes supplement, Arcane Power IIRC) and 4th edition as well, as a wizard daily or encounter power. And of course 5e, forgot the name of the supplement now.

**Comment by mlenser** [comment]
Looks like it was 2e, 4e, and 5e.

https://forgottenrealms.fandom.com/wiki/Melf%27s_minute_meteors
https://dnd4.fandom.com/wiki/Melf%27s_minute_meteors

**Comment by itamarcu** [comment]
Interesting to note that it's sometimes balls of fire and sometimes something very cosmic.
In 2e:
> several small globes of fire

And here are some images:
![](https://vignette.wikia.nocookie.net/forgottenrealms/images/0/0a/Minutemeteors.png)
![](https://vignette.wikia.nocookie.net/forgottenrealms/images/f/fc/Minute_meteors_DC_Comics.jpg/revision/latest?cb=20180514061904)

**Comment by Marcloure** [comment]
https://www.youtube.com/watch?v=tenOqLK2sEw

MMM is in the game since very early, together with Melf's Acid Arrow. MMM is in the 4:00 min mark
