### ISSUE TITLE
Fix weapon creation cantrips

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#380]
When these cantrips are used on a gish character, it basically gives them a 4d8 wepaon which  they can use with their spellcasting ability. Insanely OP.
Crimson Blade, Death Blade, Dune Hammer, Hammer, Icicle, etc

Primal Savagery is also really problematic as it can be combined with Monk or Wild Shape.

**Comment by itamarcu** [comment]
My opinion - these cantrips should be balanced for usage by half-caster characters (as an alternative to using normal weapons), and should be weaker for full casters. Full casters are good at casting, and they have plenty of normal cantrips; it's gish characters who should be combining their magic with their skill at wielding weapons.

Note, by the way, that we want to prevent the combo of the half-caster taking the Two-Weapon Fighting fighting style and then casting two of these cantrips (one on each hand).

**Comment by mlenser** [comment]
- **Themes**
  - **Alteration**
    - Hammer reworked to a melee spell attack [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Beast**
    - Primal Savagery reworked to a spell attack as an action so you can’t make a weapon attack multiple times [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Blood**
    - Crimson Blade reworked to create a weapon [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Cold**
    - Icicle reworked to a spell attack as an action so you can’t make a weapon attack multiple times [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Death**
    - Death Blade reworked to create a weapon [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
    - Scythe reworked to modify a quarterstaff [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Fire**
    - Produce Flame reworked to a spell attack as an action so you can’t make a weapon attack multiple times [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Plants**
    - Shillelagh reworked to modify a quarterstaff [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Sand**
    - Dune Hammer reworked to a melee spell attack [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
  - **Shadow**
    - Shadow Blade reworked to create a weapon [#380](https://github.com/mlenser/kryx-rpg-issues/issues/380)
