### ISSUE TITLE
Raw power feature (suffused) doesnt grant you a theme

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#381]
All classes start with 2 themes, one from their main feature at level 1 (Martial Power, Holy Power, Arcane Power, etc) and one from your subclass (arcane tradition, martial specialization, divine domain, etc).
The suffused only starts with one, defined by their origin (subclass). Is the Raw Power feature missing a starting theme or am I missing something?

**Comment by mlenser** [comment]
Suffused now have an open ended theme like all other classes
