### ISSUE TITLE
Minor Retort once per turn

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#382]
Minor Retort requires a save each time an enemy attacks you or it's pushed 10 feet. That can be a lot of rolls and can really slow down play, since the DM will have to roll attack and then make a save each time it hits.

Also, it's quite powerful for a 2nd feat when triggered more than once per turn, since it can completely interrupt a creature's action if it can't move back to you.

**Comment by mlenser** [comment]
Minor Retort feat removes as we have spells like Kinetic Retort

**Comment by itamarcu** [comment]
Minor Retort required your reaction, @Marcloure, so if you missed that it might have explained why it felt like too much.

> Whenever a creature damages you with a melee attack, you can **use your reaction** to push it away. The creature must succeed on a Reflex saving throw or be pushed 10 feet away from you.

**Comment by Marcloure** [comment]
Oh, I indeed missed that part
