### ISSUE TITLE
Incomprehensible Magic (feat suggestion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#383]
(based on a [PF2E feat](https://2e.aonprd.com/Feats.aspx?ID=761))
> **Incomprehensible Magic** (2nd level feat, *deceit*)
> You can draw upon strange variations in your spellcasting, making your spells seem bizarre and unfamiliar. The DC to identify spells you cast increases by 5. Spells such as *detect magic* can detect the existence of your spells, but cannot tell which spells you used.

(the flavor for this feat can either be "your spells are bizarre because they're from the occult" or it can be "you learned to cast your spells in a tricky way that makes them unfamiliar". I chose to allow both flavors, and this should make it fit in Deceit)

**Comment by mlenser** [comment]
5 has a very different value in PF2e than it does in 5e, due to bounded accuracy. This would have to be ~3 in 5e.

I'm not sure it's worth it at that point.

**Comment by itamarcu** [comment]
It's only a 2nd level feat, so I think it's fine if it's not particularly useful - plus, it has the secondary benefit that might come in handy.

Could also replace the +3 to DC with disadvantage on the roll.

**Comment by mlenser** [comment]
Disadvantage on the roll is areound +5

+5 in PF2e is not the same value as +5 in 5e. +5 is too much. If 3 isn't worth it, then the feat isn't worth creating.

**Comment by itamarcu** [comment]
I don't see why we're trying to "translate" the pathfinder bonus to an equivalent 5e bonus - these are different systems, and PF2e has [different](https://2e.aonprd.com/Rules.aspx?ID=298) [rules](https://2e.aonprd.com/Feats.aspx?ID=633) [about](https://2e.aonprd.com/Rules.aspx?ID=371) [identifying and countering](https://2e.aonprd.com/Feats.aspx?ID=653) spells.

In *this* system, the chance to identify a spell (with the most mana you're likely to encounter at a time), according to the [sheet](https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=1867996895), is about 65%, when you have proficiency (ignoring expertise for now).

If this feat granted +5 to DC, the chance would drop to 40%.

Considering just the benefit you get against your spells being countered, this reduces their chance of being countered from about 61% to about 55%.

I think that's completely fine, and good value for a 2nd level feat (considering the other non-combat benefits). A very situational bonus that is flavorful and might help you a little bit once every few sessions. This is in line with stuff like the ability to speak Celestial, or the ability to glow at will.

**Comment by mlenser** [comment]
PF2e scales much higher than 5e. Their bonuses scale into the 30s and 40s quite easily. 5e does not, due to bounded accuracy.

Therefore, a +5 bonus in PF2e is much less impactful than a +5 bonus in 5e.

> I think that's completely fine

And I'm telling you that its not. The bonuses, while they would be the same number, are different values in different systems. Numbers can't be ported directly like you're trying to do.

**Comment by itamarcu** [comment]
Again, I don't think we need to care at all about Pathfinder. We need to look at this feat's value within this system, and judge what number would make it good enough.

Do you think +5 is too strong of a DC increase, considering the expected value of this feat (factoring in chance of enemy being willing *and* able to identify your spells)? If so, we can go with +3. If +5 is somehow overpowered and +3 is somehow not worth it, sounds to me like +4 is the answer.

I'd also like to mention that [Magic Sense](https://www.kryxrpg.com/feats/magic-sense), another 2nd level feat, gives you advantage on identifying spells (equivalent to +5). Considering the fact that players need to identify enemy spells much more often than the opposite, that feat has higher value, which is why I thought adding the extra line about detect magic would bring my suggestion to par.
