### ISSUE TITLE
Rover (feat suggestion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#384]
> **Rover** (6th level, Survival)
> *Prerequisites: proficient in Athletics*
> Your walking speed increases by 5, and you gain a climbing speed and a swimming speed equal to your walking speed.

This is based on the 5e Ranger alternate class feature, Roving. It's available at level 1, but I thought it was a bit too strong, so I changed it into a 6th level feat that requires athletics. It also mirrors the [Gift of the Depths](https://www.kryxrpg.com/feats/gift-of-the-depths) feat, except instead of strong swimming powers, it's weak swimming and weak climbing and a bit of extra movement.

(Note that a character, by default, has a "climbing/swimming speed" of half their normal walking speed.)

**Comment by mlenser** [comment]
Climbing and Swimming speed should not be so freely granted. This would allow PCs to entirely avoid Athletics.

Gift of the Depths requires magic and is basically a permanent water breathing (self only though, else it would be higher).

**Comment by itamarcu** [comment]
What if instead it was a feat like Gift of the Depths but specialized for climbing?

6th level, gives you climbing speed, and gives you the ability to climb on difficult surfaces without using your hands (like spider climb, vampire, etc).

**Comment by mlenser** [comment]
> What if instead it was a feat like Gift of the Depths but specialized for climbing?

Based on what magic or physical feature?

> What if instead it was a feat like Gift of the Depths but specialized for climbing?

Huh, I made wording changes here to indicate that checks should always be made for climbing and swimming, not just difficult situations. But they seem to not be there. I'll make sure to bring them back.

> Um, it lets you cast water breathing on another creature.

I removed that, it should be there.

**Comment by itamarcu** [comment]
> Based on what magic or physical feature?

It could be many things - beasts frequently have claws that let them climb things or spider-like hairs that let them stick to surfaces, and there's a lot of media with ninjas that can climb anything and run up walls - but it could also be explicitly magical, with Telekinesis/Air (keeping you light enough to climb easily) or Gravity (letting you walk on walls - might want to wait until we decide on a gravity theme though). 

If you don't want to make a generic feat with no prerequisites, you could make several identical ones with different flavors. Air/Telekinesis/Gravity requiring spellcasting, Beast/Survival requiring claws or a climbing speed, and Shadow/Skirmish requiring proficiency in athletics.

Should I make a new github issue?
