### ISSUE TITLE
Replace the Reliable feature for Rogue

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#385]
The Rogue gets:
> **Elusive** (17th)
> You are so evasive that attackers rarely gain the upper hand against you. No attack roll has advantage against you while you aren’t incapacitated.

> **Reliable** (17th)
> You can turn failure into success in combat. If you miss with an attack roll, you can roll it again with advantage. Once you do so, you can’t use this feature again until you finish a short or long rest.

> **Stroke of Luck** (20th)
> You have an uncanny knack for succeeding when you need to. If your attack misses a target within range, you can turn the miss into a hit. Alternatively, if you fail an ability check, you can treat the d20 roll as a 20.
> Once you use this feature, you must finish a short or long rest before you can use it again.

The "Reliable" feature is way too similar to Stroke of Luck. The first one rerolls a miss and gets advantage, the second one turns a miss (or ability check) into a hit. The class shouldn't just gain the same ability again but slightly better.

(The origin seems to be the "Master Duelist" feature of the swashbuckler rogue, which functions the same way. I think it's badly designed :P)

I think Stroke of Luck is better to keep, because
- It's more elegant
- It's more useful outside combat
- It's literally doing what the flavor text for Reliable is doing
- Its name doesn't conflict with the "Reliable Talent" feature's name

So, I think Reliable should be changed to something more unique.

**Comment by DalenWBrauner** [comment]
There is a pretty big power difference between the two, though. You can still fail a 'Reliable' roll, whereas Stroke of Luck is both guaranteed and a crit. Plus they can both be used within a single short rest, so it's really more like Reliable gets a big upgrade at level 20.

While I'm cool with the Rogue having a more unique feature at 17 or 20, I think we need to see what that feature is, first.

**Comment by itamarcu** [comment]
Actually, Stroke of Luck is *not* a crit - for attack rolls it turns a miss into a hit, and for ability checks it turns a failure into a 20 which is just usually a success (not even always).

Also, funnily enough, Reliable can turn a miss into a hit with Advantage, which can trigger Sneak Attack, which means that, counterintuitively, in some situations it's better for you to miss than to hit.

**Comment by mlenser** [comment]
Until a better option is presented, Reliable is a good feature for the rogue. If you want it replaced, please suggest an alternative that you think fits better.

**Comment by mlenser** [comment]
Rogue 20th level feature is now Cunning Reflexes. Stroke of Luck has moved to 17th level, replacing Reliable.
