### ISSUE TITLE
Anchor links dont account for Navbar on mobile

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#387]
When redirected via an anchor link such as https://www.kryxrpg.com/rules/conditions#prone, it _does_ successfully redirect me to the Prone section, but the very top of it is cut off by the Navbar.

![Screenshot_2020-06-23-15-57-07~2](https://user-images.githubusercontent.com/3477032/85454056-858d1d00-b56a-11ea-8016-c3fc70548316.png)

Not a big issue, of course.
I'm using Google Chrome on an android phone.

**Comment by mlenser** [comment]
It's true on everything, desktop and mobile. Anchor links can't acocunt for a stuck header without doing special routing type links.

I don't plan to fix this soon.

**Comment by mlenser** [comment]
The header now hides when you scroll down and comes back if you scroll up
