### ISSUE TITLE
Psi-blades damage type

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#388]
At 5th Level > Your psi-blades count as psionic and magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.

Psi-blades already do force damage. This benefit has no actual effect besides confusing players!

**Comment by mlenser** [comment]
mlenser/kryx-rpg-issues/issues/388

**Comment by mlenser** [comment]
Soulknife Psychic Strikes feature which added confusing and pointless wording removed
