### ISSUE TITLE
Psychic Focus - damage boosts shouldn't apply to normal attacks

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#389]
Many of the Psychic Focus choices are like this:

> **Force**. You have resistance to force damage and you gain a +2 bonus to rolls for force damage.

This is cool and generally fine when the psionicist only uses spells, but it's problematic when the psionicist's main attack uses this type of damage. For example, the Soulknife psionicist uses daggers that deal force damage, so taking this psychic focus would make every single attack deal more damage, without restricting the soulknife's options, which is too strong.

Similarly, the Monk could take the Fire psychic focus along with the Fire (Monk) focus which turns the unarmed strikes damage into fire. Then, the monk makes 4-5 attacks, all attacks deal fire damage, and all of them get +2 to damage.

I suggest changing all of these psychic foci choices to:

> **Force**. You have resistance to force damage and your spells that deal force damage deal an extra 2 force damage.

**Comment by marcosPlayX** [comment]
This is also true for elemental weapon spells, if you freeze your weapon each attack deals 2 additional damage.

**Comment by Marcloure** [comment]
This is also true for elemental weapon spells, if you freeze your weapon each attack deals 2 additional damage.

**Comment by itamarcu** [comment]
Would this still be broken with [Magic Missiles](https://www.kryxrpg.com/spells/magic-missiles)?

> As an action, you create five glowing darts of magical force. Each dart hits a creature you can touch or see within 120 feet. A dart deals 1d4 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.

+2 damage to every missile is *a lot* of extra damage, and if you can put all of it on a single creature, it's even more broken.

This ability in general is something that improves AoE attacks much more than it improves single-target attacks, and I dislike that.

I suggest fixing this by changing it to one of the following:

> **Force**. You have resistance to force damage.

> **Force**. You have resistance to force damage, and whenever you roll for force damage on a spell, you can reroll a result of 1.

> **Force**. You have resistance to force damage and once a turn when your spell deals force damage to a creature you can deal an extra 3 damage to that creature.

> **Force**. You have resistance to force damage, and whenever you roll for force damage on a spell, you can deal 1 extra force damage to all of the spell's targets or 3 extra force damage to a single target.

**Comment by mlenser** [comment]
Psychic focus damage boosts only apply to spells and effects now

**Comment by mlenser** [comment]
On second thought, I don't think Psionicists should boost damage. That's more the Suffused's nikche.

**Comment by mlenser** [comment]
I think these are better options:

- You have resistance to acid damage and the first time on its turn that a creature touches you or hits you with a melee attack while within 5 feet of you, it takes acid damage equal to your proficiency bonus.
- You have resistance to necrotic damage and the first time on its turn that a creature touches you or hits you with a melee attack while within 5 feet of you, it takes necrotic damage equal to your proficiency bonus.
- You have resistance to fire damage and the first time on its turn that a creature touches you or hits you with a melee attack while within 5 feet of you, it takes fire damage equal to your proficiency bonus.
- You have resistance to force damage and the first time on its turn that a creature touches you or hits you with a melee attack while within 5 feet of you, it takes force damage equal to your proficiency bonus.

**Comment by itamarcu** [comment]
Yeah, this is definitely better.

Some issues:
- if the psionicist is grappling the enemy (as monks often do), this translates to an automatic damage per turn effect. Might be okay, but might be too strong.
- this still applies while incapacitated, which is neat but might not be intended.
- if the psionicist's allies touch the psionicist to cast a heal or buff (or drag the incapacitated psionicist someplace), the allies take damage. This is really cool but might be too detrimental. Maybe replace "creature" with "enemy"?

**Comment by mlenser** [comment]
Removing the damage. It didn't feel right either. Resistance is still a free 1 mana spell, basically.

**Comment by mlenser** [comment]
Psychic focus damage boosts removed
