### ISSUE TITLE
Toll the Dead is a bit too weak

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#390]
If you compare the [Death](https://www.kryxrpg.com/themes/death) cantrips, you can see that Toll the Dead is not great. Chill Touch prevents healing and hurts undead more, Life Syphon deals 1 less damage but heals you for half, and Reanimating Word has a chance to crit (though it requires a corpse).

Toll the Dead, though, deals 1d6+1 damage (equivalent to 1d8), and the +1 is *only* if the creature is injured, which isn't always the case (I'd estimate it's probably true only 90% of the time). The power balance sheet, too, shows this cantrip as slightly underpowered (and that sheet treats the +1 as always happening):

![image](https://user-images.githubusercontent.com/6516621/85503684-e3fdde00-b5f2-11ea-8df8-2c897b670414.png)

Therefore, I suggest changing it to deal 1d4+1d4 damage - i.e. 

> The target must succeed on a Will saving throw or take 1d4 necrotic damage. If the target is missing any of its hit points, it takes 1d4 extra damage.

and scale with +1d4 to both, of course.

This would make it a bit more elegant (no hard numbers, and symmetric), a bit more true to the flavor of being worse against full-health creatures, and a bit stronger (+0.5 damage):

![image](https://user-images.githubusercontent.com/6516621/85503867-579feb00-b5f3-11ea-82f2-b3e4c5174232.png)

Considering the fact that I think this needs to be multiplied by 0.95 on the sheet, to account for the restriction on usage, it ends up perfect.

**Comment by mlenser** [comment]
> I think this needs to be multiplied by 0.95 on the sheet,

We should almost always evaluate options at their full power level, not multiple by their chance to happen. Else you make edge cases that are super strong and then players only use those edge cases.

**Comment by mlenser** [comment]
Toll the Dead adjusted to be a more competitive option
