### ISSUE TITLE
Suggestions for a few new Survival abilities

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#391]
As part of #301, I'm suggesting a few abilities to help flesh out the Survival theme.

---

### Close Wounds
*1 mana spell*
As an action, you regain 3d6 hit points immediately and additional hit points equal to half the amount healed by this spell at the end of your next turn. If you are wounded, you reduce your wounded condition by 1.

Augment
You can increase the healing by 4d6 for each additional mana expended.

---

### Quickened Instincts
*1 mana spell*
(based on spells like [Thought Shield](https://www.kryxrpg.com/spells/thought-shield) and [Inspire](https://www.kryxrpg.com/spells/inspire))
As a reaction, which you take when you make a Reflex saving throw, you increase your reaction speed. Until the start of your next turn, including against the triggering saving throw, you have a +2 bonus to Reflex saving throws, and advantage on saving throws to avoid being grappled or restrained.

You can use this spell before or after making the saving throw, but before any effects of the saving throw are applied.

**Augment**
You can augment this spell with the following options, expending mana for each option.
- You can increase the bonus to Reflex saving throws by 2 for each additional mana expended.
- You can expend 1 additional mana to cast the spell as a reaction, which you take when you or one of your allies within 10 feet of you makes a Reflex saving throw. Until the start of your next turn, you and all allies within 10 feet of you have a +2 bonus to Reflex saving throws.

---

### Protection from the Elements
*2 mana spell, 4 hours/mana*
(based on [Protection from Fire](https://www.kryxrpg.com/spells/protection-from-fire) and similar spells.)
As an action, your body's skin toughens. For the duration, you gain the following benefits:
- You ignore the effects of extreme heat, extreme cold, high altitude, and heavy precipitation.
- You have advantage on saving throws against being poisoned, burning, slowed, blinded, or deafened, and against effects that would prevent you from using your reaction.

**Augment**
You can target one additional willing creature you can touch or see within 60 feet for each additional mana expended. The creatures must be within 30 feet of each other when you target them.

---

### Superb immune system
*6th level feat*
(similar to [Nature's Ward](https://www.kryxrpg.com/feats/natures-ward) )
After years of survival in the wilderness, your body has developed a natural immunity to toxins and illnesses. you are immune to poison damage, the poisoned condition, and disease.

---

### Tireless Perseverence
*8th level feat*
You can endure greater fatigue than others. When you have the exhausted condition, you only suffer the effects of lower levels of exhaustion, as if you had one less level. Finishing a long rest reduces your exhaustion level by 2, instead of 1.

---

[Commune with Nature](https://www.kryxrpg.com/spells/commune-with-nature) - I think this should be added to Survival, but perhaps it should be reworded or tweaked, and added as a similar spell. It would be more about using your knowledge and skills, studying the area around you, and less about just magically asking for the information.

**Comment by mlenser** [comment]
These suggestions point out to me that Survival is not a good theme.

- Close Wounds is a Life theme spell. Plants have some healing due to their thematics of plants being able to heal. Survival does not have those thematics beyond plants.
- Superb Immune System is Alteration
- Quickened Instincts is Time
- Protection from the elements' second bullet is too broad. I don't think it should exist, probably. Its first bullet is also too much. A race ignores one of those options and certain spells let you ignore one and gain resistance. Ignoring all of them is too much.
- Tireless Perserverence shouldn't exist. There shouldn't be ways to lessen exhaustion. Exhaustion is rare and it should matter when it comes up. At best this would just be a waste of a feat. At worst it would distrupt play and expectations.

**Comment by itamarcu** [comment]
My concept here was to make Survival focus on physical self buffs (barely granting benefits to others), focus on protective effects only, and focus on enduring natural elements/hazards/dangers. I don't think that's too broad - there's other themes that are much broader (like Alteration that's about shapeshifting/mutation but has healing, aura buffs, sustenance, skill empowerment...).

I'm alright with some of these spells being discarded or changed, but I still think many of them fit:

- Close Wounds - Feels to me more thematic than Regeneration is in the Alteration theme, but alright, I'll discard this.
- Superb immune system - Like I said, you can't just dump everything into Alteration. Developing natural immunity to toxins is something very common in media (and real life), and it's what survivors in nature do.
- Quickened Instincts - Yeah, that's fair. The goal was just a "mini danger sense".
- Protection from the Elements - Maybe this should tweaked to be your choice of the protection instead of all at once? Survival should allow you to traverse hazardous terrain with ease, so something like this should exist, and I tried to balance it for 2 mana so I added all the extra little benefits.
- Tireless Perseverance - Can you explain how it can disrupt play? Resisting Exhaustion fits perfectly into survival (lots of environmental hazards cause it). Greater Restoration can already instantly remove it for 9 mana, and there's plenty of other feats that help only in rare situations ([aging](https://www.kryxrpg.com/feats/gift-of-life), [speaking to plants](https://www.kryxrpg.com/feats/tongue-of-wild-spaces), [being mind-read](https://www.kryxrpg.com/feats/labyrinthine-mind), [subtle water control](https://www.kryxrpg.com/feats/water-guide)).

**Comment by mlenser** [comment]
The Protection theme used to be an all encompassing theme that covered many aspects of protection. That theme was purposefully changed as I believe a scope of that size is not a good design. A scope of that size actually limits the game.

Scopes should be narrow and an all-encompassing option like "I survive" which can be broadened to all kinds of concepts is really not a good fit.

Survival needs to be narrow or removed, which can be discussed as part of #301

**Comment by mlenser** [comment]
> you can't just dump everything into Alteration

Alteration is the immune system theme. That's where all the metabolic type spells go and this is very much in the same vein.

**Comment by mlenser** [comment]
#### Minor
- **Themes**
  - **Skirmish**
    - Quick Reaction added as a 1 stamina die maneuver [#391](https://github.com/mlenser/kryx-rpg-issues/issues/391)
  - **Time**
    - Quicken Reaction added as a 1 mana spell [#391](https://github.com/mlenser/kryx-rpg-issues/issues/391)

#### Patch
- **Themes**
  - **Plants**
    - Immunity to charm or frighten from fey removed from Nature’s Ward [#391](https://github.com/mlenser/kryx-rpg-issues/issues/391)

- Close Wounds belongs in the Life theme and is already covered there
- Protection from the Elements is covered by Metabolic Adaptation in the Alteration theme
- Superb Immune system is covered by Nature’s Ward in the plants theme
- Tireless Perseverence shouldn't exist.

**Comment by mlenser** [comment]
Please open one suggestion per issue in the future.
