### ISSUE TITLE
Inspire is better than Thought Shield

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#392]
[Inspire](https://www.kryxrpg.com/spells/inspire) is a reaction to you or another creature within 60 feet, gives +2 to all attack rolls or all saving throw rolls, and lasts until the start of your next turn.
[Thought Shield](https://www.kryxrpg.com/spells/thought-shield) is a reaction only for yourself, and gives +2 only on Will saving throws, and also lasts until the start of your next turn.

The only advantage Thought Shield has is that it has a very situational augment that lets you give the bonus to all creatures within a 10 foot radius for cheaper than Inspire would do so.

My suggestion is to improve Thought Shield by giving an extra advantage to saves against being charmed or frightened, and also let you target allies as a normal reaction. Alternatively you could make it damage the creature causing you to make a will save, or make it last for more than one turn.

Alternatively, nerf Inspire such that it only grants the bonus on a *single* attack/save, and not *all of them*. In that case, the [Inspire](https://www.kryxrpg.com/maneuvers/inspire) maneuver should probably be rebalanced to match.

**Comment by mlenser** [comment]
Inspire is only on other creatures. Thought Shield is only on you. They aren't really comparable options as Inspire can't be used on you.

**Comment by itamarcu** [comment]
You're right, my bad - Inspire is definitely weaker for the inability to cast it on yourself. It still seems stronger to me, but not in all situations, so maybe a change isn't as necessary.

**Comment by mlenser** [comment]
Overall, I think this difference makes them both good spells, but for different purposes.
