### ISSUE TITLE
Utility maneuvers

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#394]
Would this be a good template for utility maneuvers?

(updated)

> **Gymnastics**
> *1 stamina maneuver, skirmish+vanguard*
> As a reaction, which you take when you make an Acrobatics check, you have advantage on the check. Until the end of the turn, standing prone or maintaining your balance doesn't cost you extra movement, and if you fall any distance, your fall distance is reduced by 20 feet for the purposes of calculating fall damage.

> **Herculean Effort**
> *1 stamina maneuver, skirmish+vanguard*
> As a reaction, which you take when you make an Athletics check, you have advantage on the check. Until the end of the turn, climbing, swimming, and dragging creatures or objects does not cost you extra movement, and your jumping distance is doubled.

> **Tiptoe** or **Prowl**
> *1 stamina maneuver, deceit+shadow*
> As a reaction, which you take when you make a Stealth check, you have advantage on the check. You do not suffer disadvantage for moving more than half your speed during your turn.

Some more ideas (matching them to themes is a bit difficult, though)

> **Leap**
> *1 stamina maneuver, skirmish+air*
> As a bonus action, you can make a particularly long or high jump. Your jump distance is doubled, and you can add to it a number of feet equal to the result of the stamina die.
> *Enhance*
> You can spend additional stamina dice to increase the jump distance further.

> **Lift**
> *1 stamina maneuver, vanguard+earth*
> *1 minute/stamina*
> As an action, you put your entire strength into lifting an object. Roll the stamina die. Until the end of your next turn, your carrying capacity is calculated as if your Strength was increased by that amount. While pushing or dragging weight in excess of your carrying capacity, your speed is reduced to half your speed, instead of 5 feet.
> You can use your action on subsequent turns to maintain this effect, extending the duration until the end of your next turn.
> *Enhance*
> You can spend additional stamina dice to further increase your carrying capacity, adding their result to the roll.

> **Hurl**
> *1 stamina maneuver, marksmanship+beast*
> As a bonus action, you can throw an object you are holding or a creature you are grappling that is smaller than you. You can throw an object weighing up to 2.5 pounds a distance of 120 feet, an object weighing up to 5 pounds a distance of 60 feet, or an object weighing up to 10 pounds a distance of 30 feet.
> If you aim at a creature, make an attack roll against it. On a hit, you deal bludgeoning damage equal to the stamina die. If you throw a creature, treat it as an object with the same weight, and it takes half that much damage if it hits a solid object.
> *Enhance*
> You can spend additional stamina dice to deal additional damage and throw heavier objects. Each additional spent die doubles the maximum weight you can throw at each distance.

**Comment by mlenser** [comment]
> As a reaction, which you take when you make an Acrobatics check, you have advantage on the check. Your jump distance is doubled until the end of the turn.

Jump is part of athletics though, not Acrobatics. I think it's important to keep that super clear as some people like to mix those which makes Acrobatics more powerful than it should be. A jump could require dex in some circumstances, depending on your GM. But the rules expect mostly Strength.

**Comment by mlenser** [comment]
Please open an issue for each suggestion
