### ISSUE TITLE
Catapult should be balanced for higher chance of success

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#395]
[Catapult](https://www.kryxrpg.com/spells/catapult):

>  The object flies in a straight line up to 120 feet in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Reflex saving throw.

This implies that if there are multiple creatures in that line, each of them would need to make a reflex saving throw, and the catapult would hit the closest creature that failed it.

Because of that, this cantrip actually has a much higher chance of hitting - it isn't 55%, it's more like 90% (I estimate), because frequently you could find a 120 ft long line starting 60 ft from you that would include multiple enemies you'd like to hit. The chance of you hitting the *intended* target might not be higher, but the chance of hitting *any* target is.

For that reason, I think this spell's damage should be reduced to 1d6 or even 1d4.

**Comment by mlenser** [comment]
Catapult should be 60 range, not 120. RAW is 60.

A Line 60 has ~2 targets.
Chance to hit: 0.55+((1-0.55)*0.55) = 80%

It should be a 1d6.

**Comment by mlenser** [comment]
Catapult range changed from 120 to 60 (like RAW) and its damage changed to 1d6
