### ISSUE TITLE
Gymnastics

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#396]
(moved from #394)

> **Gymnastics (alternatively: Nimble Movement, Gracefulness)**
> *1 stamina maneuver, skirmish+vanguard*
> As a reaction, which you take when you make an Acrobatics check, you have advantage on the check. Until the end of the turn, standing prone or maintaining your balance doesn't cost you extra movement, and if you fall any distance, your fall distance is reduced by 20 feet for the purposes of calculating fall damage.

Concept - a generic maneuver for acrobatics check advantage, and a few minor acrobatics-themed benefits.

The one thing that bothers me with this design is that a character might want to use it for the extra benefits (e.g. just to stand prone), where an Acrobatics check might not be necessary. However, I don't want to make this a bonus action, because reactive acrobatics checks are very common and because it would be very odd to phrase it as giving you advantage to a check you don't need to make.

Also, would be nice if this could be enhanced to soften the fall further, but I can't really justify an enhancement just for one of the minor benefits.

Note: I know that Acrobatics has Soften Fall, but that requires a reaction and reduces fall by 1d20+prof+dex feet. My concept here was that a character would attempt an acrobatic maneuver with a risk of failure, which can frequently lead to falling (e.g. if you're balancing on a tightrope or jumping from something to grab onto something else). Since you can't use your reaction twice, I thought the player shouldn't need to choose between improving their chances and reducing the penalty, when it's so minor. In addition, this mirrors Enhance Ability, which (for 1 mana and concentration) grants advantage on every dexterity check plus the 20 feet fall softening, for 1 hour.

**Comment by mlenser** [comment]
Acrobatics is how a character is meant to prevent falling. I thought of making it a maneuver, but skills need their benefits as well.

Since it exists there, it shouldn't exist here.

**Comment by mlenser** [comment]
Also, standing from prone is part of the athlete fea which is Athletics, not Acrobatics.

**Comment by mlenser** [comment]
Balanced version:
> As a reaction, which you take when you make an Acrobatics check, you can add 2 to the result.
> _Enhance_
> You can increase the bonus by 2 for each additional stamina die expended

**Comment by mlenser** [comment]
Acrobatic Maneuver added as a 1 stamina die maneuver
