### ISSUE TITLE
Herculean Effort

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#397]
(moved from #394)

> **Herculean Effort**
> *1 stamina maneuver, vanguard*
> As a reaction, which you take when you make an Athletics check, you have advantage on the check. Until the end of the turn, climbing, swimming, and dragging creatures or objects does not cost you extra movement, and your jumping distance is doubled.

Like #396 - It's a bit weird that one can't get the extra benefits (e.g. dragging) without the trigger of the athletics check, but I couldn't think of a better way to phrase it, and I'd like this to remain a reaction (athletics checks outside your turn are common, e.g. when you're grappled).

**Comment by mlenser** [comment]
Acrobatics already has Soften Fall:
> If you are proficient with Acrobatics and you fall any distance, even as a result of a missed jump, you can use your reaction to attempt to reduce the impact. Make an Acrobatics check and reduce the distance fallen equal to the result. You still end up prone if you take damage from the fall.

**Comment by itamarcu** [comment]
> Acrobatics already has Soften Fall:

yes, but I think you meant to reply to #396!

**Comment by mlenser** [comment]
This doesn't make so much sense when we have Leap as a maneuver. Also, how can you make a Herculean Swim, Jump, or Climb? This seems more targeted toward grappling, overrunning, shoving, etc.

**Comment by itamarcu** [comment]
There should still be a maneuver for climbing/swimming, but alright, this can be narrowed down. It'll a bit verbose, but it has be if it's not a generic Athletics maneuver.

> As a reaction, which you take when you make an Athletics check to push, pull, grapple, shove, or overrun a creature, or to resist one of these, you add 2 to the result.
> *Enhance*
> You can increase the bonus by 2 for each additional stamina die expended.

**Comment by mlenser** [comment]
Athletic Maneuver covers this
