### ISSUE TITLE
Tiptoe

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#398]
(moved from #394)

> **Tiptoe** or **Prowl**
> *1 stamina maneuver, deceit+shadow*
> As a reaction, which you take when you make a Stealth check, you have advantage on the check. You do not suffer disadvantage for moving more than half your speed during your turn.

Note that this is meant for stealth outside combat - for stealth during combat, [Ambush](https://www.kryxrpg.com/maneuvers/ambush) is better, as it lets you sneak faster and deal more damage, but not sneak *better*.

**Comment by mlenser** [comment]
Balanced version:
> As a reaction, which you take when you make an Stealth check, you can add 2 to the result.
> _Enhance_
> You can increase the bonus by 2 for each additional stamina die expended

**Comment by itamarcu** [comment]
It's clean and seems pretty good, but - 
1. Why not add the extra benefit, allowing you to move your full speed for the turn?

and, this applies to multiple suggested maneuvers but let's keep the discussion here -

2. "add 2 to the result" - usually this is phrased "add 2 to your roll".
3. I think this should say "You can do so after you roll but before any effects of the roll occur." Players would rarely spend resources for such a small bonus before seeing their roll, especially outside combat. 

Also, compare this with the RAW maneuver "Ambush" - it lets you add a superiority die (d8 to d12) to a roll of Stealth or Initiative. The value of superiority dice is obviously not the same as stamina dice, but it's close, so if this only adds +2 to the roll I think it should add an additional benefit (ability to choose after the roll, or faster stealth, or some other thing).

**Comment by mlenser** [comment]
> Why not add the extra benefit, allowing you to move your full speed for the turn?

I try not to establish rules and then specifics to override them. Sometimes, but I think it should be rare.

> Also, compare this with the RAW maneuver "Ambush"

We have this discussion each time maneuvers come up. They are meant to be small effects that occur often. RAW Superiority Dice are on a completely different balance system. They are front loaded like crazy and have much less uses. Lets compare at 9th level:
- RAW has 5 superiority dice
- Warrior has 20 stamina dice

Completely different systems. Adding 4.5 to a roll 5 times per rest is very different than adding ~5 (advantage) or 4.5 (1d8) to a roll 20 times per rest.

**Comment by mlenser** [comment]
Sneak added as a 1 stamina die maneuver
