### ISSUE TITLE
Leap

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#399]
(moved from #394)

> **Leap**
> *1 stamina maneuver, skirmish+air*
> As a bonus action, you can make a particularly long or high jump. Your jump distance is doubled, and you can add to it a number of feet equal to the result of the stamina die.
> *Enhance*
> You can spend additional stamina dice to increase the jump distance further.

Note as a reminder - jump height is a quarter of the distance (in my opinion, a third would match 5e better, but is obviously more annoying to calculate), and a standing jump halves both distance and height.

In addition, in the Kryx RPG system, jump distance is a number of feet equal to your athletics check, so it's probably around 15 feet for a middle tier character, and 30 feet with a good roll at the final tier. There's plenty of effects that double jump distance, so adding stamina die to it should be fine if not underpowered.

The maximum height a character can jump with this maneuver (and no other jump buffs) at highest tier would be about 20 feet. In my opinion it's a bit low - there's plenty of characters in media who can jump ridiculous heights - but considering the fact that other feats or spells can increase it further, it's not that bad.

**Comment by mlenser** [comment]
Balanced version:
> As a reaction, which you take when you make an Athletics check to jump, you can add 2 to the result.
> _Enhance_
> You can increase the bonus by 2 for each additional stamina die expended

**Comment by itamarcu** [comment]
That's not balanced, it's pretty useless. The current rules let you jump a number of feet equal to your Athletics roll result. Jumping another 2 feet is never going to make the difference, and adding 10 feet for 5 stamina is a huge cost. It's already a very situational maneuver.

The Striding and Springing spell costs 1 mana to increase your speed by 10 and triple your jump, for an *hour*. For an average character, that's increasing your jump from 15 feet to 45 feet, and for high tier characters it'd be a 90 feet jump.

I think it's more than fair for a maneuver to double a single jump and add 1d8 feet.

**Comment by mlenser** [comment]
Skill maneuvers should cover the whole skill. Otherwise a character would have 4 maneuvers for Athletics. So we'll go with that.

Regarding Jumping: Those are the jumping rules. Striding and Springing is likely too powerful.

**Comment by mlenser** [comment]
- Athletic Maneuver added as a 1 stamina die maneuver
- Striding and Springing and Striding and Springing Potion now provide advantage on ability checks to jump

**Comment by Marcloure** [comment]
I like that Striding and Springing can increase your jump limit, not only make you jump easier. It's not like a character has to jump that much usually

**Comment by itamarcu** [comment]
There are so many abilities that double your jump, and I don't think anyone has ever complained that it's too much. I get it if tripling is too much of an effect, but only granting advantage or only adding 2 feet per stamina is really bad.

This is a fantasy world. Mages can fly, teleport, and phase through walls! Monks can catch arrows in mid-air and run up 50 ft walls! Why shouldn't martial characters be able to jump more than 30 feet forward?

**Comment by mlenser** [comment]
> I like that Striding and Springing can increase your jump limit, not only make you jump easier.

Giving you advantage on the check makes you jump further. :)

Striding and Spinging's main benefit is the speed benefit. Several feats and other options give a similar 10 feet.

**Comment by mlenser** [comment]
> There are so many abilities that double your jump

The only ones I know of:
- Jump in RAW (tripple)
- Step of the Wind (double)

**Comment by Marcloure** [comment]
> Giving you advantage on the check makes you jump further

Well, it doesn't allow you to jump from the ground to the roof of a house, your limit is kept the same.

**Comment by mlenser** [comment]
> Well, it doesn't allow you to jump from the ground to the roof of a house, your limit is kept the same.

Correct, but we play a game based on numbers and averages. For a Warrior with proficiency and +4 strength this changes the jump distance from ~15.5 feet to ~18.82 feet. A 3 foot difference.

**Comment by itamarcu** [comment]
Players who play martial characters at the peak of their strength don't want to be extraordinarily reliable - they want to be extraordinary. When a player's character has the power to sometimes leap over 15 foot chasms, the buff they want isn't to *always* leap over 15 foot chasms - it's to sometimes leap over *30 foot* chasms.

Reliability is nice to have as a player, and it's great in combat. But it's not as useful, flavorful, or fun as superhuman shows of strength. 

If jump distance absolutely must be limited by athletics - maybe the rules of jumping need to be changed? For example, a character's normal jumping distance might be 10 feet, and maybe making an athletics roll will double it on a result of 20, quadruple it on a result of 25, etc. This would still limit huge jumps to proficient and strong characters,

**Comment by Marcloure** [comment]
Just as a note, I'm talking about the Striding and Springing spell, not a maneuver that would allow that. I have mixed feelings about a maneuver that would allow jumping that high or far, but no opinion.

**Comment by mlenser** [comment]
@itamarcu the jump system matches what is achievable by olympic athletes. It is also what 3.5 and PF used, but that's just lucky. The Olympic record for long jump is 29 feet. If a character wants to jump far then expertise in Athletics and a high strength are crucial.

Examples:
- A level 1 Warrior with 4 strength and proficiency in Athletics will clear between 6 and 25 feet with 15.5 feet as an average, or ~19 feet as an average with advantage.
- A level 5 Warrior with 4 strength and expertise in Athletics will clear between 9 and 28 feet with 18.5 feet as an average, or ~22 feet as an average with advantage.
- A level 9 Warrior with 5 strength and expertise in Athletics will clear between 12 and 31 feet with 21.5 feet as an average, or ~25 feet as an average with advantage.

Those numbers seem totally fine to me.

**Comment by mlenser** [comment]
Note: RAW jumping distance is Strength score so ~16. Double that and you're at 32. For 5 Strength it's 20/40.

So double RAW is higher than what you can achieve at lower levels, that's for sure. But I believe the numbers used by my system are in a good place based on the above.
