### ISSUE TITLE
Lift

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#400]
(moved from #394)

> **Lift**
> *1 stamina maneuver, vanguard+earth*
> *1 minute/stamina*
> As an action, you put your entire strength into lifting an object. Roll the stamina die. Until the end of your next turn, your carrying capacity is calculated as if your Strength was increased by that amount. While pushing or dragging weight in excess of your carrying capacity, your speed is reduced to half your speed, instead of 5 feet.
> You can use your action on subsequent turns to maintain this effect, extending the duration until the end of your next turn.
> *Enhance*
> You can spend additional stamina dice to further increase your carrying capacity, adding their result to the roll.

For reference - normal carrying capacity is 150 + 30 x Strength, which for a strong character would be 300 lb. This maneuver adds 135 lb per stamina die (on average). With spells like Enlarge or Bull's Strength which double your carrying capacity (as a minor side-effect), this feels good to me.

**Comment by mlenser** [comment]
This seems far too niche to be picked or even used more than once a campaign.

**Comment by itamarcu** [comment]
If you think it's niche, it should be expanded or added onto another maneuver, such as #397. It's super flavorful for a character to have a burst of adrenaline and be able to lift an extremely heavy object (preventing a wall from crushing your party, holding a gate open for people to pass through, pulling a rope holding multiple people).

**Comment by mlenser** [comment]
Not sure what to do with this one. It should probably be skipped as its too niche.

**Comment by mlenser** [comment]
Lifting heaving things would be part of Athletics. The total capacity should not be changed except by magic like Bull's Strength (also called ant haul in older editions). That's part of Bestial Transformation.

**Comment by DalenWBrauner** [comment]
One common case of characters lifting objects is when characters lift _other creatures_, usually out of harm's way (e.g. they're paralyzed, unconscious, etc).

While currently, this maneuver is strictly about lifting objects you ordinarily wouldn't be able to carry, what about also improving a character's ability to carry things that are not in excess?

> The total capacity should not be changed except by magic

This I disagree with. When applied, human adrenaline allows for seemingly inhuman acts of strength.

**Comment by mlenser** [comment]
> When applied, human adrenaline allows for seemingly inhuman acts of strength.

Sure, up to your capacity.

**Comment by mlenser** [comment]
> what about also improving a character's ability to carry things that are not in excess?

How would a maneuver spell do so? As a GM I'd ask for Athletics to carry something heavy.
