### ISSUE TITLE
Hurl

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#401]
(moved from #394)

> **Hurl**
> *1 stamina maneuver, marksmanship+beast*
> As a bonus action, you can throw an object you are holding or a creature you are grappling that is smaller than you. You can throw an object weighing up to 2.5 pounds a distance of 120 feet, an object weighing up to 5 pounds a distance of 60 feet, an object weighing up to 10 pounds a distance of 30 feet, or an object weighing up to 20 pounds a distance of 15 feet.
> If you aim at a creature, make an attack roll against it. On a hit, you deal bludgeoning damage equal to the stamina die. If you throw a creature, treat it as an object with the same weight, and it takes half that much damage if it hits a solid object.
> The GM may rule that an object is particularly unwieldy and can only be thrown half the distance and with disadvantage on the attack roll.
> *Enhance*
> You can spend additional stamina dice to deal additional damage and throw heavier objects. Each additional spent die doubles the maximum weight you can throw at each distance.

The intention here is to allow martial characters to throw non-weapon objects effectively, primarily focusing on maximizing distance/weight. The damage calculation is included because it obviously makes sense to have it, but the intention of the maneuver is not to be used as a bonus action damaging attack. It could also combo with Alchemist concoctions (though I didn't try to balance for that).

I derived the weights and distances from a short check online - it seems like distance scales linearly against weight, roughly. You could increase the numbers a bit or make them nonlinear, particularly if you want creature-throwing to be more viable (currently you'd need to spend 4 dice to throw a goblin 30 feet away).

The damage to the thrown creature is halved because the creature has no save (and I don't think it should, as grappling it is a prerequisite and it needs to be smaller than you). Maybe a sentence could be added to prevent throwing creatures to the air for fall damage, if that's worrying anyone.

**Comment by mlenser** [comment]
This seems like a normal rule for throwing things like rocks, which is improvised weapons handled by a GM.

How can you throw a creature? The weights stop at 20 pounds. If you can throw a creature then it'd be incredibly OP as the creature will likely end up prone.

**Comment by itamarcu** [comment]
That's fair - maybe it should be a normal rule. I'd still like stamina dice to be able to improve it somehow, but maybe it would be part of another maneuver.

As for throwing creatures - I took it into account. Fling is a 2 stamina maneuver that can throw a medium creature 20 feet, make it prone, and deal 1d8 bludgeoning damage to it. This maneuver requires grappling, doesn't make the creature prone and is heavily limited by creature weight (you'd need 3-4 stamina to throw a small creature 15 feet). Even just requiring you to grapple the creature is a lot, because the grapple obviously stops when you throw the creature, so you have to spend an earlier attack to do that.

**Comment by mlenser** [comment]
Why do we need hurl when we have Fling and Throw?

**Comment by mlenser** [comment]
Fling and Throw already cover throwing a creature.
