### ISSUE TITLE
Gaseous Form, Watery Form, and augments condition immunities

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#402]
I think these spells should grant some elemental immunities like against grappled, poisoned, prone, and restrained

**Comment by mlenser** [comment]
Wind Walk should be an augment to Gaseous Form.

**Comment by mlenser** [comment]
I moved Wind Walk to an augment of Gaseous Form and Water Glide to an augment of Watery Form.

Neither Gaseous Form or Wind Walk give any kind of resistances that you mention by RAW. I'm not sure that they should get them here either.

**Comment by Marcloure** [comment]
> you assume a gaseous form for the duration, appearing as wisps of cloud

It's weird to be grappled, prone, or restrained in that form. The other immunities shouldn't be added really (poisoned, exhausted, etc). Petrified is questionable, but I can see cloud or water getting petrified.

**Comment by mlenser** [comment]
- Gaseous Form is now immune to many conditions
- Watery Form is now immune to many conditions
