### ISSUE TITLE
Rename Exhaustion to Exhausted

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#403]
https://www.kryxrpg.com/rules/conditions

![image](https://user-images.githubusercontent.com/6516621/85938813-21c37500-b919-11ea-947c-9e7f2e539c6d.png)

Exhaustion is the only condition that's named as a noun, instead of an adjective.

A character can be blinded, burning, charmed, confused, deafened, dying, and... exhaustion?

Since it's the only one of its kind, I think it would be perfect if it was renamed "Exhausted". Effects that specify "gain one level of exhaustion" could be changed to "become Exhausted 1".

Statements such as:
> It is resistant to cold, poison, and necrotic damage and immune to exhaustion, frightened, and the poisoned conditions.

Will become:
> It is resistant to cold, poison, and necrotic damage and immune to the exhausted, frightened, and poisoned conditions.

**Comment by mlenser** [comment]
I thought about this the other day as well. I agree,

**Comment by mlenser** [comment]
- Exhaustion renamed Exhausted to match the wording of other conditions
- Exhausted changed back to 6 levels and includes death
