### ISSUE TITLE
Inflict Wounds has no save listed

### ISSUE THREAD

**Issue by RobTheDM** [mlenser/kryx-rpg-issues#404]
> As an action, you lacerate the flesh of a creature that you can see within 60 feet. Make a ranged spell attack against the target.
> 
> On a hit, the target takes 5d8 necrotic damage, or half as much damage on a successful save.

It's either missing what kind of save it is, or needlessly calls for a save. Not sure which.

**Comment by Marcloure** [comment]
> Make a ranged spell attack against the target.

It's a spell attack, no save required.

**Comment by RobTheDM** [comment]
That's what threw me off, because it's a spell attack, but then says half damage on a save.

**Comment by mlenser** [comment]
The half damage on a save text is incorrect.

**Comment by Paulorpribeiro** [comment]
I know the issue is closed, but don't you guys think it's weird that this spell is an attack, if it's not a ray? Do you have to "aim" the negative energy at the target and they can "dodge" the energy or have it harmlessly whiff against heir armor? If that is not the case, I think it should be changed to a save

**Comment by itamarcu** [comment]
In 5e, Inflict Wounds was a melee spell attack, which made more sense.

For a ranged spell attack, I guess you can flavor it like Eldritch Blast - it's an ambiguous attack you make at someone and you can choose how it manifests. Maybe you're shooting a negative energy beam, maybe you're throwing bolts of pain, maybe you're conjuring a magical whip that strikes at the flesh of the enemy.

**Comment by mlenser** [comment]
It's flavored like https://harrypotter.fandom.com/wiki/Sectumsempra

> Sectumsempra is a curse invented by Professor Severus Snape that lacerates the target and causes severe haemorrhaging.

> Blood spurted from Malfoy's face and chest as though he had been slashed with an invisible sword.

**Comment by mlenser** [comment]
Note: It already has that flavor: `you lacerate the flesh of a creature`. So no need to add on any kind of other flavor.
