### ISSUE TITLE
Leveraging Strike

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#406]
> **Leveraging Strike** (or any other name)
> When you hit a Huge or smaller creature with a weapon attack using a heavy weapon, you can also push it up to 10 feet away from you.

This was a player of mine's suggestion. It is similar to thunderous strike, but since this is done with pure strength, it may be too much against a Huge creature. Also, we already have knockback and other maneuvers that push for this purpose.

**Comment by mlenser** [comment]
I think I should add a Reflex saving throw to both versions. Auto pushing is problematic, even at 10 feet.

**Comment by Marcloure** [comment]
Maybe once per turn instead of rolling a save for each attack as well?

**Comment by mlenser** [comment]
Thunderous Strike changed to occur once a turn and have a Reflex saving throw

**Comment by mlenser** [comment]
Forceful Strike added as a Vanguard feat
