### ISSUE TITLE
Clarify Psychic Focus

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#407]
> At 9th level you can focus on two psychic focuses at a time.

> Once you overload your psychic focus, you can’t gain your psychic focus again until you finish a short or long rest.

When you overload, do you end all focuses or only the one from the theme you overloaded? The text is not clear I think

**Comment by mlenser** [comment]
Psychic Focus clarifies that if you overload a focus, it ends them all. The psi limit is changed to a max of 4 psi.
