### ISSUE TITLE
Rename Minor Alteration

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#408]
I can't read this name without thinking it's a spell, it is too active for a feat. I suggest renaming it to something like "shifting physiology", "mutable form", or other more descriptive name.

**Comment by mlenser** [comment]
But it is active:
> When you finish a long rest, you may alter your body in a minor way.

It doesn't just happen.

**Comment by Marcloure** [comment]
Well, yes, but reading the name I go looking for a spell, not a feat. For instance, barkskinned, which allows you to cast a spell, so it's an active action, is descriptive.

**Comment by itamarcu** [comment]
I agree - there are Minor Illusion, Minor Spell Resistance, and Minor Telekinesis, which are all spells (and cantrips).

This feat could be changed into a cantrip, perhaps, but if not, a name change would be good. Shifting Physiology, Mutable Form, Lesser Shapeshifter, Surface-Level Mutations, Superficial Shapeshifting?

**Comment by mlenser** [comment]
Minor Alteration renamed Shifting Alterations
