### ISSUE TITLE
Subclass Feature Position is Inconsistent

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#410]
For some subclasses, the feature that grants you a related theme is closer to the top of the page, while for other subclasses it's placed lower down.

For example, the Psionicist's Order of Breeze has the "Air Theme" feature at the top:
![image](https://user-images.githubusercontent.com/3477032/86068515-8a0f7500-ba45-11ea-8409-3cd32303c7d9.png)

Whereas the Order of Flowing River does not:
![image](https://user-images.githubusercontent.com/3477032/86068526-9b588180-ba45-11ea-87e6-2d26552449d5.png)

And instead it appears at the end of the Level 1 class features:
![image](https://user-images.githubusercontent.com/3477032/86068558-aa3f3400-ba45-11ea-9b61-644457da10de.png)

**Comment by Marcloure** [comment]
It's alphabetically ordered

**Comment by DalenWBrauner** [comment]
Ah, I see! In that case, I humbly request that it not be.

It's really jarring to see it move from place to place on the page each time you click on one, especially if you're not sure what themes a given subclass is going to grant (i.e. where on the page it's going to be).

**Comment by mlenser** [comment]
Features need to be sorted in some manner.

I'd rather integrate into the power display section
![image](https://user-images.githubusercontent.com/235857/86085348-392c6a80-ba9f-11ea-8f59-44cb5e29384b.png)

**Comment by mlenser** [comment]
Subclass themes are now integrated into the feature which lists your initial archetype themes
