### ISSUE TITLE
Everything as skills

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#414]
- Weapons as skills: #411
- Armor as skills
- Saving throws as skills: #417 
- Spellcasting abilities as skills: #556

**Comment by ChefSasquatch** [comment]
What You could do to avoid the whole disadvantage on skills giving you disadvantage on attacking/casting is separate it out, have Magic Skills, Weapon Skills, General Skills, maybe even separate out Social Should and then whenever an effect gives you disadvantage it gives it to a specific subset of Skills

**Comment by mlenser** [comment]
Armor and saving thows can remain as they are as I'm not convinced that skills is the best fit.
