### ISSUE TITLE
Feedback on the forcefull strike feat

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#415]
I know it will make the feat less appealing to small characters, but a medium character forcing a Hill giant to take a step back with a blow is already fantastic enough.
Even if 10 ft is just a step for a giant, a halfling weights what 1% of the weight of the giant. It makes absolutely no sense that a small character can force a huge monster to move with a great club.

My suggestion is to restrict this to 2 size categories larger than the attacker.

**Comment by itamarcu** [comment]
While we're there, there are also two little typos in the spell description.

If fixed:

> Once on your turn when you hit a creature with a melee weapon that you wield in two hands, the creature must make a Reflex saving throw or be pushed up to 10 feet away from you. The creature must be two sizes larger than you or smaller.

(also, maybe it should specify "melee attack from a melee weapon...", so that a fighter can't throw a greatsword to push someone?)

(also, IMO, it could be limited to bludgeoning weapons)

**Comment by mlenser** [comment]
Shove requires the creature to be within one size of you.

**Comment by mlenser** [comment]
I think this feat should be removed. We have knockback for this purpose.

**Comment by mlenser** [comment]
- Forceful Strike removed as we have the Knockback maneuver
- Thunderbolt Strike renamed Thunderous Blast and reworked to only apply to concussion damage
