### ISSUE TITLE
Hold Creature should move from Force to Mind (and/or get changed to remain under Force)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#416]
https://www.kryxrpg.com/spells/hold-creature

This spell requires a Will saving throw and doesn't work on undead or constructs. It seems like it's about compelling the creature to freeze in place, or halting its nervous system, both of which would fit better in Mind.

There are many spells with this same template - if one should still remain in Force, I think it should be flavored around creating force-field bindings to hold the creature in place (also kinda similar to Telekinesis). In that case, it should probably be Reflex and lose the restriction on undead and constructs.

**Comment by mlenser** [comment]
Hold Creature moved from the Force theme to the Mind theme
