### ISSUE TITLE
Identifying items

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#418]
Arcana has:
> ***Identify a Magic Item***. If you are proficient with Arcana you can identify one magic item that is not a legendary item, sentient item, or artifact. Once you use this feature, you must finish a long rest before you can use it again.

There are similar features for other skills, such as Engineering and Psionics.

I understand that the purpose is to represent that the process of identification takes time. However, Once a day is not enough for many parties (especially if the loot is several common/uncommon items and not a single rare item). In addition, this doesn't specify the time needed, so it could be read as allowing you to instantly identify something you've just seen.

Since a mage can already cast Detect Magic as a ritual and spend 5 minutes identifying an item, I think it wouldn't be so bad if trying to do it without magic would simply take much longer - anywhere between 15 minutes and several hours. It could also have a DC, since common magic items are probably easier to identify than rare magic items, but that can be left to the GM.

My suggestion is:

> If you are proficient with Arcana you can identify one magic item that is not a legendary item, sentient item, or artifact. You need to spend an hour near the item, and the GM may require you to make an Arcana check if the item is particularly complex.

You could also add the paragraph from *Detect Magic*:

> You learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any. You learn whether any spells are affecting the item and what they are. If the item was created by a spell, you learn which spell created it.

**Comment by mlenser** [comment]
updated wording to identify magic items during a short or long rest
