### ISSUE TITLE
Antimagic Sphere permanency should be rephrased

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#419]
[Antimagic Sphere](https://www.kryxrpg.com/spells/antimagic-sphere):
> Until the spell ends, the sphere moves with you, centered on you.
> Casting this spell on the same spot every day for a year makes this effect permanent.

A permanent antimagic sphere that moves with you is pretty good :P

I suggest changing the second statement to:

> Casting this spell on the same spot every day for a year makes this effect permanent in that spot.

**Comment by mlenser** [comment]
fix antimagic sphere wording
