### ISSUE TITLE
Correct CR for Acid/Fire Elemental

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#420]
I was calculating the CR of the level 1 Fire/Acid Elemental and with their offense and defense, they were actually CR 4. To lower this for the Acid Elemental you can get rid of their immunities or the resistances. Resistances would make more sense thematically since acid shouldn't hurt a creature completely made of acid.

The same goes for the fire elemental but with the stacking, burn effects its a bit harder to calculate. I still think stacking burn is still cool, but for some of the elementals, I'd consider removing their resistances to bring them more in line for a 1 Mana Summon or summon of their level.

**Comment by itamarcu** [comment]
Are you talking about the *companion* elementals?

I think their resistances/immunities shouldn't be changed, because it's flavorful and consistent to give all elementals similar base stats. I would rather see the damage or HP or speed decreased.

**Comment by wherfz** [comment]
Yes I mean the companion elementals. In theory reducing their health to about half would also lower their CR properly.

**Comment by mlenser** [comment]
Can you show some calculations? All companions use a very similar system so elementals wouldn't be unique if they are too strong for challenge.

Though, tbh, challenge is a metric most useful for monsters, not companions

**Comment by wherfz** [comment]
Absolutely, when I'm off work I'll post them here.

**Comment by wherfz** [comment]
This is the calculations I used for the Acid Elemental. The fire elemental is a little harder to calculate directly because of the burning capability.

Acid Elemental 1 Resource
Using CR calculation on p. 273 of DMG
Calculate Defense Challenge Rating:
26 Hit Points
Creatures CR 1-4 have this value doubled for resistance as well as immunity.
26 * 2 = 52 (from resistances)
52 * 2 = 104 (from immunity)
Effectively the acid elemental has 104 HP.
This puts the acid elemental firmly at Defensive CR 3.
Calculate Offense Challenge Rating:
Each round, the acid elemental has various means of dealing damage.
8 damage from standard hit
8 damage from chemical burn on a hit target
8 damage from a creature striking the elemental in melee
8 damage from the elemental standing in a creature’s space
More damage can be potentially dealt with Spring Attack Maneuver (+4), but generally the per-round damage appears to be approximately 32 (8 * 4).
32 damage per round and +5 to hit places the elemental at Offense CR 4.
Final CR Calculation
Defense 3
Offense 4
Total CR is rounded up to 4.

**Comment by mlenser** [comment]
### Defensive challenge
HP is 26 which is 1/8 challenge. If we double HP for resistances we get 52, or 1/4 challenge. AC is 1 higher, so don't adjust down the table.

HP shouldn't be doubled for some edge case resistances like acid and poison.

Defensive challenge: 1/4.

### Offensive challenge
Damage is ~24 per turn which is challenge 3. Attack is +5, but within the limits so no adjustment

The damage when hitting it should not be assumed. There are tons of ways to avoid that.

## Final challenge
Average of 1/4 and 3 = Challenge 1.625. Round up to 2.

**Comment by mlenser** [comment]
Though, as I said, challenge really doesn't matter for companions. The challenge system is not very valuable when comparing them. It's only useful for monsters and determining some kind of difficulty.

Direct damage and health comparisons are better metrics.

**Comment by mlenser** [comment]
Closing this as the challenge is correct, though it's only calculated for the purpose of determing proficiency bonus. Otherwise its not valuable for companions.

**Comment by mlenser** [comment]
As discussed on discord:
- http://blogofholding.com/?p=7283
- http://blogofholding.com/?p=7338
