### ISSUE TITLE
Smash

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#421]
(Maneuver Suggestion. Update the labels on this github issue because I can't do that.)

> **Smash** (1 stamina, *Vanguard, Beast*)
> As a bonus action when you hit an object, structure, or creation of magical force with a weapon attack, you smash it to smithereens. Roll and add the stamina die to your attack, and you deal double the damage to the target.
> *Enhance*
> You can expend 2 additional stamina dice so that your attack can even shatter creations of magical force, such as the wall created by *wall of force*. You can destroy a 5-foot radius sphere of such a creation, instead of rolling for damage.

**Comment by mlenser** [comment]
Smash added as a 1 stamina maneuver

The magical force stuff doesn't need to/shouldn't be referenced as either its an object/surface and can be smashed, or it is immune to smashing via `immune to bludgeoning, necrotic, piercing, poison, and slashing damage` and this shouldn't override that.
