### ISSUE TITLE
Add burning immunity to some creatures

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#422]
A not exhaustive list of creatures I think should be immune to burning:
- Ghost
- Air elemental / elemental myrmidon
- Shadow
- Specter
- Water elemental / elemental myrmidon
- Wraith
- Sword Wraith
- Allip
- Vampiric Mist
- Will-o'-wisp
- creatures that are insubstantial overall. Even though they can take fire damage, I don't think they can catch on fire if they don't have substance

**Comment by mlenser** [comment]
Added burning immunity to all creatures with Incorporeal movement and water elementals

The following don't resist fire or have a reason to be immune as far as I can see:
- Air elemental
- Sword wraith
- Vampiric mist

**Comment by mlenser** [comment]
Creatures with Incorporeal Movement and Water Elementals are now immune to the Burning condition

though open to discussing if you think others have a reason to be immune

**Comment by Marcloure** [comment]
Just commenting on these:
- Air elemental: I think this can burn if we think of gas igniting? Fire is literally burning air, but air isn't usually inflammable 
- Sword wraith: they are like wraiths, but use a spectral sword. If we think them like Nazgul, Aragorn proved they can burn
- Vampiric mist: it's a mist, don't know how inflammable that is
