### ISSUE TITLE
Alchemist Blood Hunter "maneuvers only" option has two useless options

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#423]
https://www.kryxrpg.com/character/classes/alchemist
Blood Hunter has an option for maneuvers-only. However, this makes two of its abilities useless:

- Alchemical Inspiration
- Quick Alchemy

**Comment by mlenser** [comment]
I think Blood Hunter should be a Rogue. It could still choose full maneuvers, half half, or full alchemy. It would just lose all the really alchemist stuff.

I just tried it out locally and it works quite nicely, I think.

**Comment by mlenser** [comment]
Blood Hunter moved from the Alchemist to the Rogue

**Comment by itamarcu** [comment]
Small note - the starting equipment of the blood hunter should be changed to include:

- A formula book
- Alchemist’s supplies

**Comment by mlenser** [comment]
I don't have a way of differentiating starting equipment based on maneuver/alchemy choices. Though I guess there is no harm for the full maneuvers version to get them.

**Comment by Paulorpribeiro** [comment]
Also, the blood Hunter now has both sneak attack and fighting styles. Is this intended? Just for that reason alone I guess a full maneuver blood Hunter is straight up better than infiltrators rogue

**Comment by mlenser** [comment]
https://github.com/mlenser/kryx-rpg-issues/issues/426
