### ISSUE TITLE
Regeneration should override healing-from-dying tax

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#424]
Monsters like [Trolls](https://www.kryxrpg.com/monsters/troll) have this as their core defining feature - at the start of each turn, they regenerate 10 hit points.

In 5e, this made Trolls scary, because they keep hitting you every turn until you stop their regeneration and kill them.

In Kryx RPG, however, the Dying condition states that if you gain hit points you are still incapacitated until the end of your turn - for Trolls this means they will almost definitely stay neutralized until they're killed, which makes the trait weaker and less flavorfully impactful.

Other monsters are similar, and so is the Regeneration spell effect (from some augments).

I think the Dying condition should change as follows:
> - If the dying creature regains any hit points, it becomes wounded 1 and is no longer dying, but it is incapacitated (see the condition) until the end of its next turn. **A regenerating creature, such as a Troll, does not become wounded or incapacitated when it regains hit points.**

Alternatively, every single regeneration effect should have this statement added:
> - **If the creature becomes Dying, regaining hit points does not cause it to be wounded or incapacitated**.

**Comment by mlenser** [comment]
There are ~22 creatures with regeneration, so we need to fix it on them.

I don't think the same applies to regnerate as its not an ongoing effect like the other cases of regeneration. Troll oil, however, should also not be impacted by dying.

**Comment by mlenser** [comment]
Ah, several of them had restrictions on having at least 1 hit point. So the following get the wording:
- Dire Troll
- Frost Giant Everlasting One
- Juiblex
- Revenant
- Thorny
- Troll
- Vegepygmy Chief
- Vegepygmy
- Wood Woad

Example wording: `If the vegepygmy was dying, it does not become wounded or incapacitated as a result of regaining these hit points.`

_____

Troll Oil also fixed

**Comment by mlenser** [comment]
- Monsters with regneration are not wounded or incapacitated as a result of regaining the hit points
- Troll oil does not cause the creature to be wounded or incapacitated as a result of regaining the hit points

**Comment by itamarcu** [comment]
> as a result of regaining these hit points

Amusing loophole: this specifies that it only applies to hit points regained from the regeneration. This means that player can use their own healing spells on the monsters to incapacitate them.

**Comment by Marcloure** [comment]
> Troll oil does not cause the creature to be wounded or incapacitated as a result of regaining the hit points
Doesn't this basically makes the creature immortal?

**Comment by mlenser** [comment]
> Doesn't this basically makes the creature immortal?

"Immortal" in the same sense that a troll is immortal. You must apply the thing that stops the regeneration.

**Comment by Marcloure** [comment]
Well, that is broken. You use it on your fighter and it doesn't need to care about hp for the next 3 minutes

**Comment by mlenser** [comment]
@Marcloure please open a new issue for troll oil. I don't disagree, but it's a separate topic.

**Comment by mlenser** [comment]
> Amusing loophole: this specifies that it only applies to hit points regained from the regeneration. This means that player can use their own healing spells on the monsters to incapacitate them.

New wording:
> The troll regains 10 hit points at the start of its turn. **_While the troll is able to regenerate, it does not become wounded or incapacitated as a result of regaining hit points._** If the troll takes acid or fire damage, this trait doesn’t function at the start of the troll’s next turn.
