### ISSUE TITLE
Blood Hunter Fighting Styles

### ISSUE THREAD

**Issue by laserbison** [mlenser/kryx-rpg-issues#426]
With the addition of Blood Hunter to rogue, it becomes the only rogue subclass to get fighting styles, making an all-Manuever Blood Hunter better than Infiltrator.

**Comment by Marcloure** [comment]
Indeed, the Infiltrator doesn't have any feature that the others don't have too

**Comment by mlenser** [comment]
Comparing the 3 options:

## Infiltrator
- 12 skills
- Danger Sense
- Reliable Talent

## Spellthief
- 8 skills
- Steal Spell
- Magic Ambush

## Blood Hunter
- 8 skills
- Danger Sense
- Hunter (Advantage to know about creatures and track them)
- Fighting Styled

________________

4 skills is effectively 4 feats. Sure, they're for skills and not damage, but that leaves plenty of room to invest the feats for Infiltrator as they have skills covered like crazy.

I believe these options are different, but balanced.

**Comment by mlenser** [comment]
DPR difference is about 8% in the early tiers, scaling down to around 4% in the later tiers.
![image](https://user-images.githubusercontent.com/235857/86535665-32a85380-bee2-11ea-9604-f5c4470dd9be.png)

**Comment by laserbison** [comment]
This is on top of the blood hunter's better armor and weapons proficiencies, which are also effectively extra feats. I don't find that players tend to use feats for skills at all, where if there was an option to have 4 more skills or the equivalent of a magic weapon (+1 to attack, damage, and AC in duelist) for the one class that properly incentivizes one weapon fighting, I know what most people would choose. 

It seems counterintuitive to me that if you want to be an effective assassin sneak attacking fighter, your best option is to be a blood hunter but without access to concoctions. The same way that I wouldn't want an all spell ranger to be a better spellcaster than a druid

**Comment by mlenser** [comment]
> This is on top of the blood hunter's better armor and weapons proficiencies

Weapons is covered by that DPR difference. (~4-8% difference)

Armor: 
- Infiltrator will generally have 5 dex which is 17 AC
- Blood Hunter will either buy armor for 17 AC or invest in dex for it.

Different doesn't mean better.

> if you want to be an effective assassin sneak attacking fighter

They fill entirely **_different playstyles_** so this is really not the case. The Infiltrator and Blood Hunter only crossover in TWF fighting styles and those are rather different (light weapons vs one handed weapons).

The Infiltrator sneaks up and assassinates you
The Blood Hunter is much more of a brute type archetype, typically much more in your face. It could do the first option, but it wouldn't be as good as the infiltrator due to skills.

**Comment by laserbison** [comment]
I don't think that 4 skills on top of 8 is enough to make up that conceptual difference. A blood hunter with 8 skills and backgrounds can take pretty much every skill you'd need to be an effective assassin AND be better at it because doing more damage is better assassaning as well as being better in a fair fight.

I think infiltrator needs something more to support that playstyle, especially since reliable is about as effective as hunter in that regard.

**Comment by itamarcu** [comment]
also worth noting - Reliable Talent is a 9th level feature, while the Blood Hunter features are both 2nd level.

**Comment by mlenser** [comment]
## Level 2

### Damage
~1 DPR difference. For this level, very minimal
- Conclusion: **Blood Hunter**

### AC
- Infiltrator: 15
- Blood Hunter: 14-16 (15 or 16 if they have dex)
- Conclusion: **equivalent**, slight advantage for infiltrator as Blood Hunter likely doesn't want to invest too much into dex

### Skills
- Infiltrator: 12
- Blood Hunter: 8
- Conclusion: **Infiltrator**

______________________

Where is the problem?

4 skills are surely worth the DPR difference and the playstyles are completely different... This is one of the closer comparisons.

**Comment by mlenser** [comment]
>I think the Blood Hunter could lose the Danger Sense feature [...]. This would fit the flavor of "being in your face" instead of dodging.

Sure, I can see that. Then I'd need a 9th level feature to give to the Blood Hunter.

**Comment by mlenser** [comment]
Blood Hunter replaces Danger Sense with Brand of Castigation
