### ISSUE TITLE
Water Glide and Wind Walk should increase 2 targets by mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#427]
Otherwise with 5 mana you can't target a party of 4 people. It was like that before merging with Gaseous Form / Watery Form

**Comment by mlenser** [comment]
2 mana = you
5 mana = you + 3

That's a party of 4

**Comment by itamarcu** [comment]
Except it also costs an extra 1 mana to make it the travel form, instead of the slow form.

I think that additional mana on such noncombat utility spells should add more targets, especially for 2 mana utility spells. Im in favor of +2 or even +3 targets per mana.

**Comment by mlenser** [comment]
- Gaseous Form augments to two additional creatures per mana [#427](https://github.com/mlenser/kryx-rpg-issues/issues/427)
- Watery Form augments to two additional creatures per mana [#427](https://github.com/mlenser/kryx-rpg-issues/issues/427)
