### ISSUE TITLE
Companions feedback (with a comment about monsters)

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#428]
So, I have two feedback about companions and summons, they come from my druid players. It is related to maneuvers mostly:

- It is very discouraging to use it when you have to learn 3 to 5 new maneuvers to cast a spell or change shape, and also to track their stamina. It's already a lot to know your 20 or so spells, and now you need to learn a few more to cast a spell that will last for a few turns. Often times they will rather cast something more straight forward and that has clear result.
 • One of my players suggested to convert the one or two most important maneuvers to traits that you can read on the sheet, like modern adventures do with spells (they write the spell's description on the creature's actions). This could also allow non-maneuver traits, like awakened plant being able to entangle a creature.
 • Using standard monster usage (recharge or per rest) also makes it so much easier to decide what to do with your resources without requiring extra labor.
- Companions are kinda too similar and their attributes too flat. An awakened tree starts with 12 Dex and 12 AC, not very tree-like. This is a known issue form other posts, and I think companions can be more unique if they have more specialized traits or maneuvers (like the previous point).

Now, as my personal feedback, I agree. And while I do not play, I find it very hard to use your monsters (just like I find it hard to use RAW caster monsters). It is so much easier and quicker when we have few but important choices, and also more unique. I stopped filling all the spells/maneuvers for my monsters and only put the 3 most defining ones, and it feels much more diverse and specialized; now it isn't almost everything that has spring attack, and suddenly a bear is running after you with spring attack because it is a bear, and not a rat.

**Comment by mlenser** [comment]
> Often times they will rather cast something more straight forward and that has clear result.

**Comment by mlenser** [comment]
> Often times they will rather cast something more straight forward and that has clear result.

This is great. Summons have always slowed down the game and will always slow down the game. I generally prefer players not use them. But they are there for players that really want that playstyle and groups that enjoy it.

I don't believe there to be an alternative here that pleases everyone. If summons/monsters were super basic then there would be complaints on the other side.

______________

For your monster feedback, please open a new issue. They are different discussions.

**Comment by mlenser** [comment]
Actually, the monster feedback is already covered via https://github.com/mlenser/kryx-rpg-issues/issues/9 and https://github.com/mlenser/kryx-rpg-issues/issues/93.

**Comment by mlenser** [comment]
This issue is covered by several other issues already. Please use those issues to provide further feedback
- the monster feedback is already covered via #9 and #93
- companion feedback is covered by #313


Monster system is covered by #3 which would likely end up using a system similar to GiffyGlyph, but its a lot of work.
