### ISSUE TITLE
Invisibility as a 1 Mana spell

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#429]
I was looking at the Invisibility spell- with the 5 mana change shouldn't the duration be 1 hour without augmenting? It made more sense with the 10 mana system that Invisibility was 1 Mana but required an additional augment to bring it in line with Raw 5e. Now the augments seem especially expensive. I think the duration should naturally be 1 hour as is RAW.

Any other opinions on this?

**Comment by mlenser** [comment]
Invisibility is a powerful game altering spell. Its 1 mana usage should not be super strong.

There are a few spells like Invisibility that were 2 mana in RAW, but are too powerful for level 1. In this case its self-only and a limited duration.
