### ISSUE TITLE
Can you replace a spell for 2 cantrips?

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#43]
> When you gain a level in this class, you [...] can choose a spell you know and replace it with another spell from a theme you know, following the restrictions above.

Can you swap a spell for 2 cantrips and vice-versa? The text actually allows you to trade one cantrip for a higher mana spell, since a cantrip is still a spell.

**Comment by mlenser** [comment]
> choose ***a spell*** you know and replace it with ***another spell***

Both cases highlighted above are singular. Restrictions is not the same thing as options. It doesn't say "choose one of the following options above". It says trade a spell for a spell "following the restrictions" which is this part:

> The spell must cost equal to, or less than, your mana limit and you must know a number of spells from the spell’s theme equal to half the spell’s mana cost (rounded down).

Though currently the wording would allow for a cantrip to be converted to a spell, which isn't intended.

**Comment by mlenser** [comment]
this wording should be clarified now:

Divine Blessings
You gain two divine blessings as shown on the Divine Blessings column of the Priest table. A divine blessing grants one of the following options:

- Learn a new theme from your power source.
- Learn two cantrips of your choice from the themes you know.
- Learn a new spell from a theme you know. The spell must cost equal to, or less than, your mana limit and you must know a number of spells from the spell’s theme equal to half the spell’s mana cost (rounded down).

When you gain a level in this class, you gain two additional divine blessings and you can choose a cantrip you know and replace it with another cantrip from a theme you know or you can choose a spell that costs 1 or more mana and replace it with another spell that costs 1 or more mana from a theme you know, following the restrictions above.
