### ISSUE TITLE
Make unstable concoctions not stackable

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#431]
While one Alchemist alone can buff the whole party, I have found that it's much more powerful when a single creature is buffed with invisibility, flight, haste, regeneration, and more. This hyper-buffed creature can singlehandedly win an encounter, and I don't think that is very fun for the team or the game.

So, I propose that a creature can't be under two unstable concoctions' effects at the same time. Sure, multiple spellcasters can buff a single creature too, but that require concentration from multiple PCs. Also, an Alchemist's concoction can't be stopped by breaking concentration, and it can buff multiple creatures too.

**Comment by mlenser** [comment]
> a single creature is buffed with invisibility, flight, haste, regeneration

This would require 4 different themes and 4 different concoctions. To create and drink those would also take 4 rounds and at least 5 catalysts. That's a fairly large investment by the Alchemist.

Invisibility: Greater is meant to augment for 2 (so 3 catalysts total). The spell does, but I forgot the concoction. So if they're using greater invis that'd be 7 catalysts.

The rounds can happen outside of combat, but by the time they're "fully buffed", the duration of several of those is quite limited. So for this to work you'd have to stand in the room next to the room where you want to fight, make/drink the potions and then rush in before the duration runs out. Seems difficult.

Maybe there is something here, but I'd need to understand more where the problem is. Maybe you can articulate some examples?

> an Alchemist's concoction can't be stopped by breaking concentration

Rarely, if ever, do I experience concentration being targeted by monsters and broken. It would require quite intelligent monsters and a fair amount of coordination.

**Comment by Marcloure** [comment]
> To create and drink those would also take 4 rounds and at least 5 catalysts

This would be the same for spellcasters, but they can't do that. Also, just being able to mix two buffs is more than any caster can do.

A few powerful combos:

- Mellowroot with Invulnerability Potion
- Fire Oil and Envenomed Weapon in a single weapon
- Lightning in a Bottle with Levitation Potion

No caster alone can do that, and I believe for a good reason. The Alchemist has the benefit of being able to buff multiple targets, and I think that is enough.

> for this to work you'd have to stand in the room next to the room where you want to fight, make/drink the potions and then rush in before the duration runs out

2 or 3 minutes is enough so that you still have enough time to fight, it's like you will be only a fraction of the battle buffed.

> Rarely, if ever, do I experience concentration being targeted by monsters and broken.

Sure, that depends a bit on DM style. Most of my enemies target casters if they are able to and recognize spells, but indifferent of that, doesn't the spreadsheet consider that concentration spells last for 2 turns or so? Just being able to make a new effect without ending the previous one is a huge gain.

**Comment by itamarcu** [comment]
Another problem (that this suggested fix might not even fix) is [Giant Insects](https://www.kryxrpg.com/concoctions/giant-insect-liquid) - what's stopping you from creating an army of insects, one per 2 mana, and then fighting with all of them for a duration of 1 hour?

**Comment by mlenser** [comment]
> just being able to mix two buffs is more than any caster can do.

Being able to cast in combat using 1 action instead of multiple characters using actions is more than any alchemist can do.

> doesn't the spreadsheet consider that concentration spells last for 2 turns or so

No, the value of effects is reduced each round, but there is no assumption that a spells ends due to concentration in the duration. Concentration lowers the value by 10% though.

_________________

But this isn't a bad direction and the wording becomes much more thematic:

> Some concoctions are made with unstable mixtures. If a concoction is unstable, that fact appears on its entry. A creature can only have the effects of one unstable concoction at a time. If the creature consumes another unstable concoction before the effects of the existing unstable concoction expires, both effects end and the creature takes 1d6 damage for each catalyst used on both concoctions.

**Comment by mlenser** [comment]
> Another problem (that this suggested fix might not even fix) is Giant Insects

This doesn't solve that. Not sure how to solve that. Feel free to open a new issue.

**Comment by mlenser** [comment]
Unstable definition changed to prevent a creature from consuming multiple unstable concoctions

**Comment by itamarcu** [comment]
> both effects end and the creature takes 1d6 damage for each catalyst used on both concoctions.

this is a bit too punishing - I think a nicer way would be

> the previous effect ends and the creature takes 1d6 damage for each catalyst used on both concoctions.

**Comment by mlenser** [comment]
They're both unstable. If two unstable things mix, I don't expect one to stop working and one to continue working. I would expect both to stop working.

Besides, this shouldn't happen. It is a waste of resources anyways so this is really just flavor.

**Comment by itamarcu** [comment]
Concentration spells don't have this limitation, and even allow the caster to stop the effects at will. With this rule in place, a character who drinks a Danger Sense or Find The Path potion is taking a big risk and preventing itself from drinking more unstable concoctions in combat.

**Comment by DalenWBrauner** [comment]
Would it be trivial to have some method of "cleansing" your body of a concoction? I feel there are multiple reasons (besides just potion stacking) that you might want an otherwise beneficial effect to stop. Unless that's preferred as an intended drawback of the mechanic.

**Comment by DalenWBrauner** [comment]
(Obviously referring only to concoctions you willingly drank for their positive effects, not poisons and the like.)

**Comment by itamarcu** [comment]
I think this could be limited to "Effects of concoctions brewed by the same alchemist" and fix the poison problem! Perhaps even with an augment that lets it remove harmful foreign effects unless they're made with more catalysts (like how Dispel Magic works).

If such a Cleansing Potion existed, I think this solution to unstable concoctions would be perfect.

**Comment by Marcloure** [comment]
Also, the solution should limit to one effect on an object too, otherwise you can use Fire Oil and Envenomed Weapon on a weapon and virtually surpass your catalyst limit for this particular combo

**Comment by itamarcu** [comment]
> Fire Oil and Envenomed Weapon

but how else are you going to create the Flaming Raging Poisoning Sword of Doom?

**Comment by mlenser** [comment]
Unstable definition changed to prevent a creature from consuming multiple unstable concoctions or from applying multiple unstable concoctions to an object

Also, the ability to purge stomach contents added to end the effect of an unstable concoction

There are 4 unstable concoctions that last a long time:
- Danger Sense
- Giant Insect Liquid
- Past Impressions
- Web Vial

I've also added a note to Giant Insect Liquid that it ends if another one is used.
