### ISSUE TITLE
Cocoon shouldn't give a normal Reflex save to escape paralysis

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#432]
[Cocoon](https://www.kryxrpg.com/spells/cocoon) and [Cocoon Vial](https://www.kryxrpg.com/concoctions/cocoon-vial) both make a target paralyzed unless it succeeds on a Reflex save. That's fine.

However, the target can repeat the saving throw each turn, and that's problematic, because:

> **Paralyzed**
> The creature automatically fails Reflex saving throws.

I believe the spell should change to a Fortitude saving throw to fix this. Alternatively, have the first save Reflex and further saves Fortitude. Alternatively, make an exception for this spell, and say "this Reflex save is unaffected by the creature being paralyzed".

**Comment by DalenWBrauner** [comment]
It's not ideal, but another option is to make the creature "both Incapacitated and Restrained" instead of Paralyzed. This has the following effects:
- Disadvantage on Reflex rather than autofail
- Opponents dont autocrit if within 5ft
- Creature can speak

**Comment by mlenser** [comment]
Another example of how it should be Brawn/Coordination to break free. :(

**Comment by itamarcu** [comment]
In 5e, paralyzed creatures automatically failed Strength and Dexterity saving throws. In the current KryxRPG system, they fail Reflex saving throws, which are a combination of both.

How would it be in the skills-as-saves system? Because literally being paralyzed *should* make you automatically fail anything that requires movement of your body.

I think the problem here is with the spell itself - it doesn't really paralyze you, it just traps you in a cocoon of webs, so your muscles still work, albeit only for the purpose of pushing yourself out of the cocoon.

I think this spell has to have an exception to the rules written within it, or alternatively to make it restrained and incapacitated (I believe being restrained shouldn't affect your brawn/bruteness, so it will work well with skills as saves).

**Comment by mlenser** [comment]
Cocoon updated to use a Brawn or Coordination check to escape, like Chains of Light
