### ISSUE TITLE
Alchemists shouldn't be able to create more than one giant

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#433]
[Giant Insects](https://www.kryxrpg.com/concoctions/giant-insect-liquid) - what's stopping you from creating an army of insects, one per 2 mana, and then fighting with all of them for a duration of 1 hour?

This should pretty clearly be fixed - a level 5 chemist shouldn't be having 4 giant insects fighting together, and a level 20 one shouldn't have 15 of them. Even if that's really cool.

My suggested options to fix this:
* Reword "The insect is friendly to you and your companions, and it disappears when it drops to 0 hit points or when the concoction ends **or when you use the concoction again on another insect**." This isn't really explaining the flavor reason for the limitation, so it's bad.
* Add a statement: "The creature is hostile towards any other giant insects it can see, unless they were enlarged together with the same concoction." This basically explains the limit as "insects are territorial/aggressive and you can't have more than one".
* Add a statement: "As part of creating or applying this concoction, you rub a special oil on yourself that emits particular pheromones, suited for the specific creature you are trying to control. If you use this concoction again on another insect, you must replace the pheromones, and the first insect no longer obeys you."

**Comment by mlenser** [comment]
Added a note to Giant Insect Liquid to specify that it ends if another one is used.
