### ISSUE TITLE
Some leftover stamina conversion errors

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#434]
- Mutagen (Alchemist Mutant feature) lets you convert catalysts to twice as many stamina dice, and should be three times as many
- same with Wild Shape Potion (should act like Wild Shape, where 1 mana = 3 stamina)
- also Spirit Drain: should drain 3 stamina, not 2 stamina

**Comment by mlenser** [comment]
- **Classes**
  - **Alchemist**
    - Mutagen now produces the proper amount of stamina dice [#434](https://github.com/mlenser/kryx-rpg-issues/issues/434)
- **Themes**
  - **Beast**
    - Wild Shape Potion now produces the proper amount of stamina dice [#434](https://github.com/mlenser/kryx-rpg-issues/issues/434)
  - **Spirit**
    - Spirit Drain now drains the proper amount of stamina dice [#434](https://github.com/mlenser/kryx-rpg-issues/issues/434)
