### ISSUE TITLE
Remove "School of", "Circle of", "Order of" from subclass names in the scrollable tab selector

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#435]
I think most wizard subclasses (also known as arcane traditions, also known as schools) can be renamed to be shorter, without the "school of" part, and can even match the Archivist by being a "verber".

- Archivist will remain as it is
- School of Abjuration → Abjurer
- School of Divination can be removed, I believe, because it's identical to Archivist - but if not, rename it Diviner
- School of Enchantment → Enchanter
- School of Illusion → Illusionist
- School of Necromancy → Necromancer
- School of Teleportation and Time → Dunamancer

Could alternatively just name them as the school - Abjuration, Divination, Etc.

**Comment by itamarcu** [comment]
Actually, I think this change could be made for other classes too - Naturalist, for example, really shouldn't have "Circle of the Totem Warrior". Just "Totem Warrior" is enough. Similarly, the Psionicist's Orders don't need the "Order of..." part.

It's okay if the descriptions still use these names - e.g. "Psionicists of the Order of the Flowing River draw their power from the moon." - I'm just asking that the names in the selection don't contain the redundant prefix, so that more can be visible at once.

**Comment by mlenser** [comment]
> School of Divination can be removed, I believe, because it's identical to Archivist - but if not, rename it Diviner

The theme is the same, but the flavor is different. You can see this in several subclasses for other classes.

**Comment by mlenser** [comment]
- **Classes**
  - **Mage**
    - Mage subclasses renamed [#435](https://github.com/mlenser/kryx-rpg-issues/issues/435)
  - **Naturalist**
    - Naturalist subclasses renamed [#435](https://github.com/mlenser/kryx-rpg-issues/issues/435)
  - **Psionicist**
    - Psionicist subclasses renamed [#435](https://github.com/mlenser/kryx-rpg-issues/issues/435)
