### ISSUE TITLE
War Strike is barely useful

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#436]
>War Strike
> 5th Level class feature
> When you take the Attack action, you can forgo one weapon attack that uses your ability modifier to use a maneuver that has a use time of 1 action.

This would probably be really cool if it applied to maneuvers that cost a Bonus Action, but because it only applies to maneuvers which cost exactly an Action, it only applies to 6 maneuvers:

- [Aim](https://www.kryxrpg.com/maneuvers/aim), except Aim allows you to do this anyway
- [Nimble Defense](https://www.kryxrpg.com/maneuvers/nimble-defense), except you'll only use this once per combat
- [Precognition](https://www.kryxrpg.com/maneuvers/precognition), except you'll only use this once per combat
- [Charming Presence](https://www.kryxrpg.com/maneuvers/charming-presence)
- [Fearsome Beast](https://www.kryxrpg.com/maneuvers/fearsome-beast)
- [Pillar of Command](https://www.kryxrpg.com/maneuvers/pillar-of-command)

It'd be nice if this either also applied to Bonus Action maneuvers, or if it was just replaced with something more valuable.

**Comment by mlenser** [comment]
Maneuvers are already built to be used with attacks. War Strike is just there for the few maneuvers that use an action, that is its purpose. It isn't meant to allow multiple maneuvers per turn.
