### ISSUE TITLE
Phantasmal Killer & Fear

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#438]
In #354, we discovered that [Terrifying Visage](https://www.kryxrpg.com/spells/terrifying-visage) was unclear about what precisely the target was afraid of. Now looking at [Phantasmal Killer](https://www.kryxrpg.com/spells/phantasmal-killer), I'm discovering it has the same issue.

Now:
> As an action, you tap into the nightmares of a creature that you can touch or see within 120 feet and create an illusory manifestation of its deepest fears, visible only to that creature.

Possible fix:
> As an action, you tap into the nightmares of a creature that you can touch or see within 120 feet. Choose one space within 60 feet of the target to create an illusory manifestation of its deepest fears, visible only to that creature.

I'd also like to point out that these spells are almost completely identical; one is missing an augment, and even the flavor text is nearly the same. I have no opinion one way or the other, but I believe they could be merged into a single spell that exists in both themes.

**Comment by mlenser** [comment]
> I'd also like to point out that these spells are almost completely identical; one is missing an augment, and even the flavor text is nearly the same. I have no opinion one way or the other, but I believe they could be merged into a single spell that exists in both themes.

One uses illusions, the other doesn't. Therefore, different spells.

**Comment by mlenser** [comment]
Also, the wording wasn't changed for Phantasmal Killer as it doesn't need to be changed. See the RAW version: https://www.dndbeyond.com/spells/phantasmal-killer

It's not a stationary illusion in a space. See https://www.reddit.com/r/DMAcademy/comments/68c2xb/questions_about_phantasmal_killer_and_the/

**Comment by mlenser** [comment]
Actually, going to remove Phantasmal Killer and use Terrifying Visage.

**Comment by itamarcu** [comment]
Tiny suggestion - in Terrifying Visage:
> You can target one additional creature for each additional mana expended. The creatures must be within 30 feet of each other when you target them.

Change this to:
> ***Weird:*** You can target one additional creature for each additional mana expended. The creatures must be within 30 feet of each other when you target them.

if you want to keep the "Weird" spell somewhere (just like how it's done with other spells that were originally unique).

**Comment by mlenser** [comment]
- Phantasmal Killer removed in favor of Terrifying Visage
- Terrifying Visage wording updated to not create a manifestation, but to cause them. That should be more clear that it isn’t placed in a specific place

![image](https://user-images.githubusercontent.com/235857/86941341-1f94be00-c144-11ea-86d2-196be1c39a3f.png)

**Comment by itamarcu** [comment]
I still think it's not absolutely clear what *mechanically happens* here.

The Frightened condition says:
> A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.
> The creature can’t willingly move closer to the source of its fear.

The players or DM will read this, read the spell description, and then find themselves unable to say exactly what the "source of fear" is, much less how you can't get closer to it if it doesn't exist.

If the mechanical intention is that the creature is *constantly* suffering disadvantage and can't move *anywhere*, it isn't clear. If the creature is actually free to move, it isn't that clear either. If the position of the manifestations is subject to DM decision, I think it should be explicit.

**Comment by mlenser** [comment]
> I still think it's not absolutely clear what mechanically happens here.

The source of feat is pretty much never explicit. Most are worded like dragons: "Each creature of the dragon’s choice that is within 120 feet of the dragon and aware of it must succeed on a DC 19 Will saving throw or become frightened for 1 minute.". One can assume the monster is the source in these cases.

The creature is afraid of the visage and the visage isn't in a specific place. It is seen by the creature and moved with it. I'm not sure if that needs to be stated and how to state it if so.

**Comment by DalenWBrauner** [comment]
> Feel free to seach through some for guidance.

I've searched, and there isn't a consistent answer. Most of the discussions ([like this one](https://rpg.stackexchange.com/questions/74427/does-the-phantasmal-killer-spell-affect-creatures-immune-to-being-frightened)) are just concerned with poorly worded text about the saving throw. So we're back at square one.

> I'm not sure if that needs to be stated and how to state it if so.

The frightened condition requires a position of the source of your fear to be known by the DM in for them to run it. It cannot be ambiguous, or every DM will need to come up with their own ruling.

Either:
- Target doesn't know its fear's position, and is unaffected
- Target knows its fear's position, and cannot move closer to that position
- Target can actually see its fear, thereby seeing whatever point in space it appears to be in, and cannot move closer to that point in space. It also suffers penalties to its rolls for the duration.

>  It is seen by the creature and moves with it.

This is a good starting concept, but it is not explicit (and it needs to be). Is there a single phantasm, that has a position in space and follows the affected creature? Are there several, which appear wherever the DM would choose? Do they change from round to round, should the target have multiple fears? Does the caster have any say in the general direction the fear may be coming from at any given time? At the beginning of the casting of the spell?

Because the frightened condition requires a position by definition, either:
- the spell needs to give a ruling on the manifestation's position,
- the spell needs to say that the DM adjucates the manifestation's position (and whether or not the caster has any influence),
- or the spell inflicts the frightened condition without actually allowing the frightened condition to take effect. This case is bad for two reasons:
1. Players are given an explicit condition to go reference, only for it to be ambiguous whether the condition has any mechanical effect, and how to run it.
2. This sets a terrible precedent for how Fear effects could work in general.

I understand this is a problem in RAW, but that doesn't mean we shouldn't seek to fix it.

Alternatively, if you believe there should be legitimate instances where a creature is affected by the Frightened condition, but there is no "form" in space that it is currently afraid of (perhaps an effect that causes a creature to be afraid of the future, or some more abstract concept), then this is actually a problem with the Frightened condition, not the spell.

**Comment by mlenser** [comment]
> The frightened condition requires a position of the source of your fear to be known by the DM in for them to run it. It cannot be ambiguous, or every DM will need to come up with their own ruling.

The source is clear. The manifestations are the source of the fear. It says that right in the spell's description: `causing it to see manifestations of its deepest fears, visible only to that creature`.

> This is a good starting concept, but it is not explicit (and it needs to be).

You're viewing it as a physical thing with a space. It is not that. It is a manifestation that the creature sees.

______________

> that doesn't mean we shouldn't seek to fix it.

But your solution is to give the manifestation a space, which is it not intended to have. I agree that this is not 100% clear, but it shouldn't have a space.

**Comment by DalenWBrauner** [comment]
> But your solution is to give the manifestation a space, which is it not intended to have. I agree that this is not 100% clear, but it shouldn't have a space.

Interesting- sure! But this still has problems that need solving. If there is no space, then the mobility portion of the Frightened condition is ambiguous. How would you rule it? Is the creature's movement unrestricted, because the fear isn't in a "direction"? Or should the creature stay in place, because the creature sees this fear everywhere?

**Comment by itamarcu** [comment]
The current wording on the website is now:
> Choose one creature or object within 60 feet of the target, which the target regards as a manifestation of its deepest fears.

Assuming I'm not having caching errors, this is the original request - a physical position for the source of fear.

If we want to have the fear follow the creature, we can change this:

> On a failed save, the creature takes 6d6 psychic damage and is frightened until the start of its next turn. **If the source of its fear is no longer visible to it, a new creature or object within 60 feet  of it becomes the source of its fear.**

**Comment by mlenser** [comment]
> You're viewing it as a physical thing with a space. It is not that. It is a manifestation that the creature sees.

**Comment by Marcloure** [comment]
Well, then I think it's better to phrase it as "you have disadvantage on attack rolls and ability checks. A creature that can't be frightened is immune to this effect". The frightened condition does require a source location, otherwise it doesn't have any effect, or always have both effects (DM fiat).

**Comment by itamarcu** [comment]
That phrasing would work too, I guess.

I was trying to keep the normal usage of "Frightened", and just say that the source of fear is not truly a physical thing (because it keeps following you around and switching places), but it's still something with a direction to you that you can see (so DMs can still have a rule to follow and understandable events to narrate).

**Comment by mlenser** [comment]
> The frightened condition does require a source location, otherwise it doesn't have any effect

See https://www.dndbeyond.com/spells/phantasmal-killer. This spell is that spell. The designers haven't errata'd it, so obviously it works.

The manifestations cause the creature to be frightened. The creature is frightened by the manifestations.

**Comment by Marcloure** [comment]
Sure, then how would you rule this two situations:

- To where the target can't move? Can it move in any direction? Can it not move? Is it left for the DM decides?
- If the target hides inside a closet, does it still has disadvantage on ability checks and skill checks? If so, can the target move further into the closet or out of it, or it can't move?

I'm asking this because I really don't know how this spell is supposed to behave in any of these.

**Comment by itamarcu** [comment]
> The designers haven't errata'd it, so obviously it works.

I really don't think that's the bar we should set for "this is fine". This system, while based on and inspired by 5e, should strive to be better and to fix problems that were carried over. A lot of spells haven't been errata'd, particularly spells that players didn't complain about because they were underpowered and used less often.

Like Marcloure said - a lot of people online are confused by this ([more](https://www.reddit.com/r/DMAcademy/comments/cv9e22/does_the_frightened_condition_imposed_by_the/) [examples](https://forums.giantitp.com/showsinglepost.php?p=23653816&postcount=17)), particularly about the movement restriction. 

Maybe the solution could be "illusory manifestation of its deepest fears, visible only to that creature, in a direction of your choice".

**Comment by mlenser** [comment]
Better wording:
> On a failed save, the target sees the manifestations in a direction you choose and is frightened of them for the duration. At the start of each of its turns while frightened, the creature must make a Will saving throw.
