### ISSUE TITLE
Heavy Armor Master and Defensive Tactics feats should belong to Protection

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#439]
[Heavy Armor Master](https://www.kryxrpg.com/feats/heavy-armor-master)

[Defensive Tactics](https://www.kryxrpg.com/feats/defensive-tactics)

Currently these two belong to Vanguard.

The other armor feats ([Armored](https://www.kryxrpg.com/feats/armored), [Shielded](https://www.kryxrpg.com/feats/shielded)) are in Protection too, so this will be consistent.

**Comment by mlenser** [comment]
This exposes a weakness in the martial themes. This views them as:
- Skirmish: Offensive Dex
- Vanguard: Offensive Str
- Protection: Armor and blocking stuff

Those splits don't make me happy. By this logic then Twin Parry should also move to protection and we should probably move a lot more.

I'd rather find a better way to define martial themes.

**Comment by itamarcu** [comment]
I think Protection is more specifically:
- Armor (the equipment) and shields
- "Tanking"/"Taunting" (making enemies hit you instead of your allies)
- Keeping enemies close to you instead of your allies (sentinel, grapple)

Stuff like Twin Parry might add to your AC, but it's not the kind of ability that armored tank characters would use. Just like how Barkskin and Force Shield aren't in Protection.

I can see how Defensive Tactics might potentially fit Vanguard more than Protection - it heavily encourages enemies to hit creatures other than you, which is kind of against the common theme. It still combos very well with the Protection abilities, though.

The only ability currently in Protection that feels out of place is Disarm - it's only indirectly about protection, and I feel like it might better fit another theme (Earth?).

**Comment by mlenser** [comment]
Heavy Armor Master added to Guardian
