### ISSUE TITLE
Allow Beast maneuvers to work with natural weapons

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#44]
A lot of Beast maneuvers requires that you hit if an unarmed strike. By RAW, an attack with a natural weapon is not an unarmed strike.

Alternatively, you can just rule that attacks with natural weapons are unarmed strikes. That will cause some problems when a Monk, or character with the Brawler fighting style and the Pugilist feat turns into a creature.

**Comment by mlenser** [comment]
- Flesh Ripper, Fling, Rampage, Swipe, and Tear Tendon can be made with a natural weapon or unarmed strike
- Inject Venom maneuver can only be made with a natural weapon now
