### ISSUE TITLE
Trick Shot

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#442]
(based on [Tactile Shot from the Spheres of Power](http://spheresofpower.wikidot.com/sniper). neat website!)

#### 2 stamina, *marksman*
As an action, or in place of an attack when you take the Attack action, you make an unconventional ranged attack at an object, in an attempt to manipulate it with your projectile.
Choose an unattended object within your weapon's range, or a light object held or carried by a creature. If the creature is unwilling, you must make an attack roll against the creature's AC. Otherwise, make an attack roll against AC 10. The GM may choose to increase this number if the unattended object is particularly small.
On a hit, you can choose one of the following effects:
- **Detach**: You cause an object to drop off from where it's attached, such as by cutting a chandelier's rope or making a keyring on someone’s belt drop to the ground.
- **Disarm**: You attempt to knock a light object from a creature's grasp. The creature must make a Reflex saving throw. It automatically succeeds if it's holding the object with two hands or if the object is heavier than 1 lb. On a failed save, the creature drops the object in its space. If the saving throw fails by 5 or more, the object lands in a space 5 feet away instead.
- **Push**: You push an object. You can knock an unattended object up to 10 feet away, or apply force to a heavier object, such as by closing a door, pushing a lever, or pressing a button.
- **Light/Extinguish**: You can extinguish a tiny open flame, such as the flame on a torch. Alternatively, you light such an object, provided that you have the means to set your ammunition on fire.

**Comment by mlenser** [comment]
In general, offensive maneuvers shouldn't use actions. They are intended to use bonus action or characters would have to weigh the cost of an attack vs a maneuver and often low level maneuvers would be horrible in that comparison. See https://www.kryxrpg.com/maneuvers/rain-of-arrows for an example.

The ones that exist now are conditions besides Aim, which speaks to the idea that Aim shouldn't really exist.

Specific cases:
- Detach would just be a normal attack against the chandelier's rope. For shooting a keyring off someone I'd probably make it an attack with disadvantage.
- Disarm already exists as a maneuver that is a bonus action
- Push already exists as knockback or Brute Force
- Light/Extinguish should just be an attack against a flat DC. If the target is tiny, then increase the DC/provide disadvantage.

**Comment by itamarcu** [comment]
The issue here is that a trick shot *is* an attack by itself, it's not really something you can do in addition to making two normal attacks on your turn. Perhaps it can be phrased as "As a bonus action, when you make an attack against an object".

Spending one attack on something non-damaging already has a lot of precedence (grappling, shoving, casting spells, throwing concoctions). In a standard RPG game, a player would ask the GM "can I try and shoot that rope?" and the GM would rule it as one of the character's attacks.

If the question is about the value - I believe that this can definitely be valuable, and not only during combat. This maneuver is intended for creative players to have an actually useful tool for solving certain problems or thinking outside the box.

If the argument is that these should just be standard rules that apply to everyone - I kind of disagree. Yes, everyone can try it, but only a marksman who has practiced making such particular shots would be able to do it consistently and in combat. There's plenty of examples of characters in media who show off like this.

> Disarm

Disarm is limited to melee weapons. This specific version of Disarm is meant for ranged weapons, which is why I made it less effective (doesn't do damage, can only affect light objects). A ranged character needs to be able to do this thing.

> Detach, Push, Light/Extinguish

Yes, these could all be attempted by anyone. But a character who specialized in precisely hitting stationary objects should be able to do it better! This maneuver gives the character the option to do it, and gives the GM a useful baseline (for AC and for actions that can be done), so they don't have to make rulings on the fly.

**Comment by mlenser** [comment]
>  In a standard RPG game, a player would ask the GM "can I try and shoot that rope?" and the GM would rule it as one of the character's attacks.

Yes, and that is why it shouldn't be a maneuver.

Many are already covered and if they aren't covered those use cases can be added. But shooting a candle/chandelier is not a maneuver.

______

> Disarm is limited to melee weapons.

And purposefully so.

> A ranged character needs to be able to do this thing.

No they don't. Ranged has its own uniqueness.

____

> gives the GM a useful baseline (for AC and for actions that can be done), so they don't have to make rulings on the fly.

Add standard rules for hitting small things like such as hitting a a candle/chandelier if you'd like. The other 2 cases are covered and I would handle those 2 cases as an attack, potentially with disadvantage depending on the scenario.
