### ISSUE TITLE
Tough it Out

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#443]
#### 2 stamina, *vanguard, earth*
*1 minute/stamina die, concentration*
As a reaction, which you take when you become confused, exhausted, frightened, poisoned, slowed, or staggered, you push through the worst of it and rely on adrenaline to carry you through a moment longer. The negative effect does not apply to you, though it strains you to keep going like this; You must concentrate on this maneuver as if you were concentrating on a spell, and if you lose your concentration the negative effect immediately starts applying to you, as if it only took hold at that moment.

**Comment by mlenser** [comment]
Maneuvers are intended to never have concentration.

Also, 2 stam to automatically avoid a debilitating condition is far beyond what 2 stam should provide. It could potentially provide an additional save, but not a guarantee like this.

**Comment by itamarcu** [comment]
Maybe the concentration part can be tweaked, but the goal is "you can't avoid this condition, only delay it". It fits the thematics a warrior who shrugs off pain and pushes themselves through with the power of pure adrenaline, only to collapse a moment later. It's not intended to let you outright remove a debilitating condition, so it needs to be a delay effect, and not a saving throw bonus (plus, we already have those maneuvers).

Maybe instead of concentration and a long duration it could just delay the condition until the end of your next turn, at which it will be applied?

**Comment by mlenser** [comment]
> 2 stam to automatically avoid a debilitating condition is far beyond what 2 stam should provide

It would be a 4-5 stamina cost if it exists (which I'm not sure it should).

2 stamina is 0.66 mana. This is more powerful than 0.66 mana.

**Comment by itamarcu** [comment]
> This is more powerful than 0.66 mana.

I'll compare it to other Reaction powers:

[Wave Shield](https://www.kryxrpg.com/spells/wave-shield) is 1 mana ("3 stamina"), and for one round it gives you +2 AC, resistance to fire, advantage against burning.

[Winter's Bite](https://www.kryxrpg.com/spells/winters-bite) is 1 mana ("3 stamina"), deals 9 damage, slows 1 for a round, and causes disadvantage on one attack roll (both with a save).

[Fountain of Blood](https://www.kryxrpg.com/maneuvers/fountain-of-blood) is 1 stamina to frighten creatures in a sphere around you for one round (with a save).

[Guided Strike](https://www.kryxrpg.com/maneuvers/guided-strike) is 2 stamina to give an ally advantage on attack rolls for one round.

The ability I'm suggesting is less powerful than any of these. It's delaying a medium condition ("worth" 3-5 points in the spreadsheet) by 1 round, which should be just as powerful as granting yourself a medium buff for 1 round, or causing a medium debuff to an enemy (or more debuffs or more enemies, if it's behind a save).

Guided Strike gives such a buff to an ally, Fountain of Blood gives such a debuff to multiple enemies, Winter's Bite does much more than that (behind a save and for 1 mana), and Wave Shield gives you something similar to being Hasted 1 for a round (arguably).

Judging by these, the value of delaying one of these conditions for 1 round should be 2-3 stamina.

**Comment by mlenser** [comment]
> The ability I'm suggesting is less powerful than any of these

I believe it is significantly more powerful in the scnearios where it should be used.

I'm not sure how to handle these issues where feedback isn't taken into account.

> if it exists (which I'm not sure it should).

> automatically avoid a debilitating condition is far beyond what 2 stam should provide. It could potentially provide an additional save, but not a guarantee like this.

I don't believe this should exist based on the above.

**Comment by itamarcu** [comment]
> I'm not sure how to handle these issues where feedback isn't taken into account.

It feels like you are the one who isn't taking my actual arguments into account :/

You said you believe it's powerful (4-5) stamina, I replied with specific examples of similarly powerful abilities that cost 2-3 stamina. If you're arguing that it's stronger than it looks, please give me actual explanations backing this up. I'm trying to do the same.

The debilitating conditions are all roughly as bad as Poisoned, which gives disadvantage on your attack rolls. Guided Strike can give an ally advantage on attack rolls, which is equivalent in power, since they cancel each other. If you want to argue that buffing any ally within 60 feet is less powerful than buffing yourself situationally (when you're poisoned/frightened/etc), you can say that. Otherwise, this ability at 2 stamina is on par with the ones I've detailed above, and I'm fine with increasing it to 3 stamina if we want to play it extra safe.

I don't see how there is a scenario where this ability is significantly more powerful than it sould be - it's strictly limited by what it can do.

> if it exists (which I'm not sure it should).

Thematically, it should exist. Warriors can stave off pain and use adrenaline to keep fighting an extra few moments. It's so common that [it's a trope](https://tvtropes.org/pmwiki/pmwiki.php/Main/PostVictoryCollapse). Mechanically, it needs to be delaying your punishment, and not giving you a saving throw bonus/advantage.
