### ISSUE TITLE
Confusion Poison (& Confusion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#445]
[Confusion Poison](https://www.kryxrpg.com/spells/confusion-poison) should be reduced to 1 mana, and the duration removed from it. Looks like there's a data error there. It should be identical to [Confusion](https://www.kryxrpg.com/spells/confusion).

While bringing this up, I noticed that Confusion is particularly underpowered:

![image](https://user-images.githubusercontent.com/6516621/87206315-21ac7780-c312-11ea-8cd7-2c6a56d7fb84.png)

Compare it to [Avalanche](https://www.kryxrpg.com/spells/avalanche) - which does good damage, affects creatures in an area, and deals a more debilitating condition (according to the sheet, at least).

I think it can be buffed to have a 1 minute duration with concentration, or to deal psychic damage, or to have a 1 minute duration, or to give a situational disadvantage on the will save (e.g. disadvantage if the target has no creatures next to it).

**Comment by mlenser** [comment]
Confusion Poison aligned with confusion.
