### ISSUE TITLE
Add magic items

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#446]
https://old.reddit.com/r/dndnext/comments/hp8e75/here_are_a_bunch_of_more_flavorful_and_slightly/

**Comment by itamarcu** [comment]
More sources for magic item effects:

http://www.lordbyng.net/inspiration/tables.php

https://manysideddice.com/2015/03/10/a-table-of-contents-thats-better-than-nothing/

https://drive.google.com/file/d/1w9X0SOT0s2ezPjv_RrS9yDqPTeaR_Gqz/view

**Comment by mlenser** [comment]
Butterfly Knife and Drummer’s Retort added

There are hundreds of magic items out there. Please open a new issue for specific groups/cases that are worth adding.
