### ISSUE TITLE
Add some non-weapon-specific Fighting Styles

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#447]
As discussed on Discord - most martial builds only have 1 useful fighting style (based on their weapons of choice) plus the Defense style. ~~Since we want to encourage characters to invest a bit in INT (to learn more styles)~~ *(nevermind, fighting styles are no longer tied to that)*, I suggest that we add 2-3 new generic styles, that would be at least occasionally useful to many characters.

If you have any ideas, please suggest them in comments. My starting ideas:
- **Fleet-footed** - Your movement speed is increased by 5 feet.
- **Absorbing** - You have resistance to bludgeoning damage.
- **Pit-Fighting** - When attacking a creature grappled by you or grappling you, you gain a +2 bonus to attack rolls.
- **Hunting** - The first time on each of your turns that hit a creature with a weapon attack, that creature's speed is reduced by 5 feet.
- **Stout** - If you aren't incapacitated, you gain a +2 bonus to Fortitude saving throws.

Note - the Absorbing style could be made weaker by only applying the first time you take damage each turn. And others for the other physical damage types could be added. The flavor for Absorbing is that you learned to absorb punches by shifting your body with their momentum (what many people train to do), but mechanically, it's just a neat way to make damage types more distinct.

**Comment by mlenser** [comment]
Fighting styles are worth about 10% damage or less damage.

- 5 foot speed is always on, not only in combat. Therefore most every character would simply get +5 speed out of combat as a flat buff. So that's not an option.
- resistance to bludgeoning is worth way more than 10%. Not a fan of the flavor either. Shifting your body weight is part of AC (defense)
- pit fighting is really niche. Feels like brawler would be better. Maybe 1 handed weapon grappler is the niche? It's small.
- hunting seems too weak and too strong at the same time.
- stout: similar problems to the speed. Also, this is a fighting style, not a random fort buff.

**Comment by itamarcu** [comment]
- **Fleet-footed** - +5 ft out of combat to some martial characters in your party - how would that affect anything? no one counts speed out of combat and parties travel at the rate of the slowest member. To avoid this, though, could this perhaps be reworded as "Your movement speed is increased by 10 feet if you've spent mana or stamina since your previous turn"?
- **Stout** - that's just a simplified version of Protection, which currently exists and lets you add your shield's AC to your Reflex score. If a fighting style lets you increase Reflex I think it makes sense for it to allow increasing Fortitude or Will, too. Maybe it can be tied to armor requirement, and another benefit could be added, to mirror Protection?

Some more ideas...

- **Dirty Fighting** - When you make an attack with advantage against a creature, if you hit, you gain a +2 bonus to the damage roll.
- **Heavy Weapons** - When you make an attack with a heavy weapon against a creature using a shield, you gain a +2 bonus to attack rolls.
- **Light Weapons** - Being prone or restrained does not impose disadvantage on your attack rolls with light weapons.
- **Unarmored Defense** - While you are not wearing armor, you gain a +1 bonus to AC.
- **Safety** - Being behind cover grants you double the bonus to your AC and Reflex saving throws as usual.

**Comment by mlenser** [comment]
- **Fleet-footed**: You're giving a flat +5 speed to all martial characters who bother. That's not good.
- **Stout**: The flavor for shields is in the fighting style: `interposing your shield between yourself and the source of the effect`.

I believe the other options are not in line with the current fighting style methodology for being simple and effective most of the time. Many of these are niche. This isn't the direction that I'd like to go.

**Comment by Marcloure** [comment]
>  You're giving a flat +5 speed to all martial characters who bother. That's not good.

Can't that be said about Defense as well? It's a free +1 AC for anyone martial who wants it

**Comment by itamarcu** [comment]
I'd rather keep this issue open and have other people suggest more ideas for fighting styles. Unless you disagree with the premise - we *do* need to add more fighting styles, especially so when they've been limited to themes in the latest change.

**Comment by itamarcu** [comment]
> Can't that be said about Defense as well? It's a free +1 AC for anyone martial who wants it

Actually, it's only for people with armor. The Battlerager is unable to use it, which is why I suggested the Unarmored Defense fighting style.

Currently if you play a classic barbarian (unarmored and wielding a greataxe) you can *only* benefit from Great Weapon Fighting.

**Comment by mlenser** [comment]
> Can't that be said about Defense as well? It's a free +1 AC for anyone martial who wants it

Defense is pretty much only usable in combat, barring the odd trap.
A fighting style that gives movement speed without restrictions of being in combat of some kind just becomes a running style that gives all characters +5 speed whole out of combat. That's not good.

**Comment by mlenser** [comment]
Regarding keeping it open: I've stopped engaging in several GitHub issues as I don't feel feedback is considered. It just becomes a long discussion and the results don't heed the main issues pointed out. So it's easier to be clear that this isn't a direction that I think is a good design and move on.

**Comment by Paulorpribeiro** [comment]
I hate to try and ressurrect a closed issue, but, I do think we need more fighting styles, and among those suggested, unarmored defense is the only the sounds good to me. Like itamarcu said, battleragers can't use Defense fighting style, and a specific style for them "fixes" it. If +1AC to armored people is fair game, I can't see why +1 AC to unarmored people in a different theme would not be appropriate. 
I could also suggested some more styles, but I need to know if this is the desired direction, and if "simple and passive" is the framework we have to work with.

**Comment by mlenser** [comment]
Additional fighting styles aren't ***needed***, as long as the main ways of fighting are covered. If we've missed some then we can try to support those styles. Additional options _could_ be added if there are strong options.

Simple requirements for fighting styles:
- It should be passive (active is for maneuvers)
- It should be simple: THF is the most complex it can be. The other options are much simpler though, and that should be the aim
- It should have a value of ~10% more DPR
- It should be a fighting style, not a running around the countryside style or a "you can swim" style
- It should not overlap much with the current fighting styles
- It should be generally useful, not only usable in super niche scenarios like "when you have advantage", "when you grapple", or "when you are prone".

Could be some more, but that should cover the baseline.
