### ISSUE TITLE
Number of fighting styles

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#449]
I see the number of fighting styles is no longer influenced by intelligence. I quite liked this from the previous iteration, and i think it makes int meaningful to martials, and not completely a dump stat. Now at, say level 15, if you have 5 themes that have fighting styles, you get all 5, even if you dump Int.
I would suggest continue to cap the number of fighting styles available to your Int stat. This could be done by saying on the feature "you can choose a number of fighting styles equal to your intelligence (modifier). Each time you learn a new theme, if it has a fighting style av available, learn a fighting style from it if your total number of fighting styles would not be greater than your Intelligence (modifier)"

**Comment by Paulorpribeiro** [comment]
Edit: it's actually INT+1

**Comment by mlenser** [comment]
You can always only have 1 fighting style active. More fighting styles simply means a bit more versatility if you encounter a situation where your main one doesn't work as well.
- Defense: against difficult enemies that hit hard
- Archery/Throwing: across a crevice/against flying creatures
- Brawler: when you're without a weapon

I understand the desire to make Int more meaningful for classes that don't have much meaning in Int, but I believe it doesn't capture the thematics so well. Getting a theme means you spend time on training the things in that theme.
