### ISSUE TITLE
Lower overall damage of PCs

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#452]
We discussed on Discord about damage in this system being higher than RAW damage. That is not totally true, but:

> **Kryx**
> so when I decided to maintain values from RAW I picked polearm and GWM as TWF is trash by RAW
polearm is a bit weaker than GWM and we could adjust down a bit, but I wouldn't use RAW TWF as a baseline

> I suppose it's the Greatweapon Master feat that makes them equal then? Personally I don't like that too much, that feat pushes PCs' damage too high (I find that mosters' hp are balanced to a world without GWM and Sharpshooter)

> **Kryx**
> I was planning on moving most 4th level feats to 6th level which would lessen this problem at 4/5 and make the curve much smoother. I can do that first and then see where the numbers are

There is also the issue with single target burst spells and healing:

> I get the feeling that, maybe, single target damage is a bit too bursty. The value of being able to annihilate that priority enemy, like a greater demon or powerful caster, with a single action before they can do too much should be considered a bit higher. Like, 14d6 at 5th level is a lot for the price of a single action.

> A symptom of the current high values is that druid's Self Recovery heals them for 40 hp at 2 mana, but they have ~40 hp at 5th level, so it's a full heal. Even at 8th level, when they have ~60 hp, it's a big % healing

So damage would need to be downgraded overall, both DPR and peak damage from burst spells. The reduction would be around ~3 DPR to get the damage from RAW Greatweapon Master level to RAW Polearm Master level.

**Comment by mlenser** [comment]
Based on my calculations, comparing to options in RAW such as polearm, the numbers match:
![image](https://user-images.githubusercontent.com/235857/88793085-8e41c600-d19c-11ea-92bf-024adf37e0aa.png)
While there are some peaks and valleys, the numbers are overall the same.

Many options in RAW are quite garbage choices and in that sense, PC DPR is increased, but the top tier damage is the same.

I believe the numbers are currently where I would expect them to be. Also, there is limited options to nerf all martials without reducing maneuvers for example. We could buff monsters a bit if there is a problem, but that isn't the best option.

**Comment by mlenser** [comment]
Class and Archetype damage boosting features moved from 9th level to 13th level to better align with RAW
