### ISSUE TITLE
Bloodrage has no chosen theme

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#455]
Suffused - Bloodrage:

> You have resistance to bludgeoning, piercing, slashing, and the damage type associated with the chosen theme.

There isn't a "chosen theme" anymore, so this needs to be updated.

Maybe this could even be removed - the Suffused already gains resistance to a damage type fitting their origin.

**Comment by mlenser** [comment]
wording clean up by removing it
