### ISSUE TITLE
Health calculation is confusing

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#457]
According to the [class](https://www.kryxrpg.com/character/classes/suffused):

> Health: 1d6 (or 4) + your Constitution per suffused level

According to the [species](https://www.kryxrpg.com/character/species/orc):

> Health. Your health increases by 10.

From these two, the intuitive understanding is that the character would have 10 hit points plus (4 + CON) x Level.

However, the [How to make a character](https://www.kryxrpg.com/character/how-to) page mentions:

> You start with health from your species and an amount equal to the highest roll of your class die, as indicated in your class description

Which would imply that *actually* the hitpoints should be 10 + (6 + CON) + (4 + CON) x (Level - 1).

I think the first option makes more sense. It's a much simpler calculation, and it makes sense with how starting hit points are affected by your species.

Therefore, I suggest changing the last quote I mentioned, to simply be 

> You start with health from your species and an amount equal to a roll of your class die (or the average), as indicated in your class description

(note - In RAW 5e, this is not confusing, because it separates "Hit Points at 1st Level" and "Hit Points at Higher Levels" in the class description.)

**Comment by mlenser** [comment]
Wording cleaned up:

At 1st level, your character has 1 Health Die, and the die type is determined by your class. You start with health from your species and an amount based on your class die, as indicated in your class description. (You also add your Constitution, which you’ll determine in step 5.)
