### ISSUE TITLE
Metamagic - Twinned Spell - cost too high?

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#458]
In the [Metamagic](https://www.kryxrpg.com/feats/metamagic) feat, Twinned Spell allows you to cast a spell on two creatures at once. It requires spending metamagic/mana equal to that spell's cost, **plus 1**.

I think the "plus 1" should be removed.

Reasons:

- Reverberating Spell has a similar effect (but repeating a spell twice in the same area, instead of twice on two different creatures) and yet it doesn't add 1 to the cost
- RAW twinned spell doesn't add 1 to the cost
- Adding 1 to the cost might have been more fair in the 10 mana system, but now with mana being worth twice as much, it's a higher price to pay

Alternatively - you could make it "plus 1" only on Concentration spells (since those are the cases where Twinned lets you do something unique, and even more efficient).

**Comment by Marcloure** [comment]
Without the +1, twinned spell doesn't cost extra mana, so you are casting a spell twice in a turn for no extra mana cost. Example: casting inflict wounds on a turn and then inflict wounds on another turn would cost the same 2 mana of twinning inflict wounds. You are doubling your immediate damage for no extra cost, and that is too powerful for this feat, I believe.

Also, in RAW you can't convert from spell slot to sorcery points without paying extra, so you do lose slots if you want to use them to twin a spell.

**Comment by mlenser** [comment]
Twinned spell allows for significant burst in a turn. Reverberating spell is the same effect next turn, which is much less valuable.

As @Marcloure pointed out, +1 should stay.
