### ISSUE TITLE
Feral Growth

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#459]
I'm suggesting a utility cantrip to the Beast theme, because currently it only has a single cantrip and it's a combat one.

The purpose of this cantrip is to be a minor version of [Bestial Transformation](https://www.kryxrpg.com/spells/bestial-transformation) that gives you a weak boost for a single turn.

---

### Feral Growth (or another name)

As an action, you channel primal magic to briefly adapt a part of your body to a more feral form. 

Choose one of the following effects. It lasts until the end of your turn.

- You reinforce your calf muscles. You have advantage on Athletics checks to jump.
- You grow webbing between your fingers. You have advantage on Athletics checks to swim.
- Your fingers stiffen to support your weight. You have advantage on Athletics checks to climb, and Brawn checks to hang onto an object.
- You heighten your sense of smell or hearing. You do not suffer disadvantage on Perception checks for relying on sight in a lightly or heavily obscured area.
- You stiffen your muscles, doubling the weight you can drag, push, pull, or carry.

---

I made it require an action on purpose - most characters won't be able to Dash while using it, which makes it useful to help a character avoid a failed jump/climb but not to move quickly or cross a longer distance, along with being less useful in combat. It won't help you jump across a long pit, but it will prevent you from failing a jump across a short one. It also won't help your party.

If advantage is too strong, this could be replaced with something like increased climb/jump/swim speeds. I chose it because it's simple and prevents stacking multiple effects.

Note that many of these effects are things you can do much better with spells and maneuvers. For example - Sprint lets you adv-jump, dash, and ignore difficult terrain, as a bonus action. Bull’s Strength gives you advantage on all strength checks, along with doubled capacity, for an hour.

**Comment by mlenser** [comment]
Cantrips shouldn't negate skill checks, or in this case significantly lessen the need for proficiency in them. If magic does that, it must come at a cost. Same with higher speeds.
