### ISSUE TITLE
Chromatic Dragons' spells and maneuvers

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#46]
I'm moving my dragon spells and maneuvers to this new issue.

Black and Blue dragons can be found at issue #9.

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Green Dragon
Green dragons use cunning, trickery and illusions to hunt and play with their victims. They enjoy the fear they cause, stalking a prey for days before attacking. They also use the terrain and the nature to fight in their favor.

Green dragons rely in intimidation to make prisoners and gather information. They are devilish negotiators, ploying schemes and manipulating lesser creatures.

Overall, their **spell themes** are Fear, Plants, and Trickery. Their **martial themes** are Beast and Trickery. Green dragons have frightening spells earlier than other dragons.
### Wyrmling
#### Maneuvers (3 stamina, limit 1): 
- **1 stamina die:** ambush, inject venom

#### Spells (2 mana, limit 1): 
- **cantrips:** blind spot, minor illusion
- **1 mana:** fear, image

### Young
#### Maneuvers (11 stamina, limit 3):
- **1 stamina die:** ambush, inject venom, fearsome beast

#### Spells (6 mana, limit 3): 
- **cantrips:** blind spot, minor illusion
- **1 mana:** animate plants, fear, image, invisibility
- **2 mana:** bloodlust, false sensory input, phantasmal force, plant growth
- **3 mana:** dark delirium

### Adult
#### Maneuvers (17 stamina, limit 5):
- **1 stamina die:** ambush, inject venom, fearsome beast

#### Spells (9 mana, limit 5): 
- **cantrips:** blind spot, minor illusion
- **1 mana:** animate plants, fear, image, invisibility
- **2 mana:** bloodlust, false sensory input, frightful presence, phantasmal force, plant growth
- **3 mana:** dark delirium, incite panic, wall of thorns
- **4 mana:** geas, mirage

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** ambush, inject venom, fearsome beast

#### Spells (10 mana, limit 5): 
- **cantrips:** blind spot, minor illusion
- **1 mana:** animate plants, fear, image, invisibility
- **2 mana:** bloodlust, false sensory input, frightful presence, phantasmal force, plant growth
- **3 mana:** dark delirium, incite panic, wall of thorns
- **4 mana:** geas, mirage

**Comment by mlenser** [comment]
Moving the other posts here

**Comment by mlenser** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Black Dragon
Black dragons are cruel, sneaky, and sadistic, targeting the weakest enemy first and frightening the rest. They often play with their prey, letting them escape only to hunt them down again.

Black dragons live in foul water and acidic environments. They are often found in ruins, marches, and other blasted, dark places.

Overall, their **spell themes** are Acid, Fear, and Shadow. Their **martial theme** is Beast. As a rule of thumb, wyrmling and young dragons have only a few frightening powers when compared to adult or ancient dragons (when they gain Frightful Presence in RAW).
### Wyrmling
#### Maneuvers (3 stamina, limit 1): 
- **1 stamina die:** ambush, dive attack

#### Spells (2 mana, limit 1): 
- **cantrips:** gloom, hidden shadow
- **1 mana:** acidic spray, eruptive postule

### Young
#### Maneuvers (9 stamina, limit 3):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** tear tendon

#### Spells (5 mana, limit 3): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acidic spray, command, eruptive postule
- **2 mana:** acid fog, cloak of shadows, vitriolic sphere
- **3 mana:** corrosive bane

### Adult
#### Maneuvers (16 stamina, limit 4):
- **1 stamina die:** ambush, dive attack, fearsome beast, swipe
- **2 stamina dice:** tear tendon

#### Spells (8 mana, limit 4): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acidic spray, command, eruptive postule, fear
- **2 mana:** acid fog, cloak of shadows, frightful presence, vitriolic sphere
- **3 mana:** corrosive bane, incite panic

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** ambush, dive attack, fearsome beast, swipe
- **2 stamina dice:** tear tendon

#### Spells (10 mana, limit 5): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acidic spray, command, eruptive postule, fear
- **2 mana:** acid fog, cloak of shadows, frightful presence, vitriolic sphere
- **3 mana:** corrosive bane, incite panic

**Comment by mlenser** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Blue Dragon
Blue dragons are patient. They play it safe, harming its prey at a distance and only entering the fray when it has the advantage. They also hunt from moving under the sand. 

Blue dragons command minions and many monsters. The older ones have elemental servants.

Overall, their **spell themes** are Fear, Sand, Storm, and Trickery. Their **martial themes** are Beast and Trickery. As a rule of thumb, wyrmling and young dragons have only a few frightening powers when compared to adult or ancient dragons (when they gain Frightful Presence in RAW).
### Wyrmling
#### Maneuvers (4 stamina, limit 1): 
- **1 stamina die:** ambush, dive attack

#### Spells (2 mana, limit 1): 
- **cantrips:** blind spot, mold sand, shock
- **1 mana:** galvanize, wrath of the storm

### Young
#### Maneuvers (11 stamina, limit 3):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** blind

#### Spells (6 mana, limit 3): 
- **cantrips:** blind spot, frighten, mold sand, shock
- **1 mana:** invisibility, galvanize, locate water, sand cloud, wrath of the storm
- **2 mana:** blur, chain lightning, storm lord

### Adult
#### Maneuvers (18 stamina, limit 5):
- **1 stamina die:** ambush, dive attack, fearsome beast, swipe
- **2 stamina dice:** blind

#### Spells (9 mana, limit 5): 
- **cantrips:** blind spot, frighten, mold sand, shock
- **1 mana:** fear, invisibility, galvanize, locate water, sand cloud, wrath of the storm
- **2 mana:** blur, chain lightning, frightful presence, sand storm, storm lord

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** ambush, dive attack, fearsome beast, swipe
- **2 stamina dice:** blind

#### Spells (10 mana, limit 5): 
- **cantrips:** blind spot, frighten, mold sand, shock
- **1 mana:** fear, invisibility, galvanize, locate water, sand cloud, wrath of the storm
- **2 mana:** blur, chain lightning, frightful presence, sand storm, storm lord
- **3 mana:** incite panic

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Red Dragon
Red dragons are rage and pride incarnate. They are arrogant and destructive, never bowing before an enemy.

Red dragons use their sheer power and their immensely hot fire to slaughter foes and destroy kingdoms.

Overall, their **spell themes** are Fear and Fire. Their **martial theme** is Beast. As a rule of thumb, wyrmling and young dragons have only a few frightening powers when compared to adult or ancient dragons (when they gain Frightful Presence in RAW).
### Wyrmling
#### Maneuvers (5 stamina, limit 2): 
- **1 stamina die:** dive attack, rampage

#### Spells (3 mana, limit 2): 
- **cantrips:** cauterize wound, produce flame
- **1 mana:** fiery rebuke, immolation
- **2 mana:** fireball

### Young
#### Maneuvers (12 stamina, limit 6):
- **1 stamina die:** dive attack, fearsome beast, rampage, swipe

#### Spells (6 mana, limit 3): 
- **cantrips:** cauterize wound, produce flame
- **1 mana:** heat metal, fiery rebuke, immolation
- **2 mana:** fireball, incendiary cloud, molten upheaval
- **3 mana:** flame bane

### Adult
#### Maneuvers (19 stamina, limit 5):
- **1 stamina die:** dive attack, fearsome beast, grapple, rampage, swipe

#### Spells (10 mana, limit 5): 
- **cantrips:** cauterize wound, produce flame
- **1 mana:** heat metal, fear, fiery rebuke, immolation
- **2 mana:** fireball, frightful presence, incendiary cloud, molten upheaval
- **3 mana:** flame bane
- **5 mana:** phoenix spark

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** dive attack, fearsome beast, grapple, rampage, swipe

#### Spells (10 mana, limit 5): 
- **cantrips:** cauterize wound, produce flame
- **1 mana:** heat metal, fear, fiery rebuke, immolation
- **2 mana:** fireball, frightful presence, incendiary cloud, molten upheaval
- **3 mana:** flame bane
- **5 mana:** phoenix spark

**Comment by mlenser** [comment]
Dragons are indeed half casters and half martials. Though all I need is the list of maneuvers/spells. The resources and limits are automatically calculated so you can skip those.

**Comment by Marcloure** [comment]
Yeah, I'm posting my own comments and the limit so other people can more easily give their opinion.

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### White Dragon
White dragons are the most savage and brutal of all dragons. While not as intelligent, they are exceptional hunters and survivalists.

Overall, their **spell themes** are Fear and Ice. Their **martial themes** are Beast and Skirmish. As a rule of thumb, wyrmling and young dragons have only a few frightening powers when compared to adult or ancient dragons (when they gain Frightful Presence in RAW).

I thought about making white dragons have only maneuvers, since they are the most beastful of all true dragons. I decided not to, since they are still true dragons and not wyverns.
### Wyrmling
#### Maneuvers (3 stamina, limit 1): 
- **1 stamina die:** blood in the water, dive attack

#### Spells (2 mana, limit 1): 
- **cantrips:** frostbite, icicle
- **1 mana:** cold snap, winter's bite

### Young
#### Maneuvers (8 stamina, limit 2):
- **1 stamina die:** blood in the water, dive attack, fearsome beast
- **2 stamina dice:** slashing blades

#### Spells (4 mana, limit 2): 
- **cantrips:** cauterize wound, produce flame
- **1 mana:** cold snap, snow storm, winter's bite
- **2 mana:** cold fog, winter's grasp

### Adult
#### Maneuvers (15 stamina, limit 4):
- **1 stamina die:** blood in the water, dive attack, fearsome beast, grapple
- **2 stamina dice:** fling, slashing blades

#### Spells (8 mana, limit 4): 
- **cantrips:** cauterize wound, produce flame
- **1 mana:** cold snap, fear, winter's bite
- **2 mana:** cold fog, ice storm, frightful prescence, winter's grasp
- **3 mana:** frost bane

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** blood in the water, dive attack, fearsome beast, grapple
- **2 stamina dice:** fling, slashing blades

#### Spells (10 mana, limit 5): 
- **cantrips:** cauterize wound, produce flame
- **1 mana:** cold snap, fear, winter's bite
- **2 mana:** cold fog, ice storm, frightful prescence, winter's grasp
- **3 mana:** frost bane, incite panic

**Comment by Marcloure** [comment]
I'm not sure how to do this, but for the **Dracolich**, I believe it should be a templete where the dragon loses all its maneuvers and becomes a full caster, while also adding Death to its themes.

What do you think? Maybe it should still keep its maneuvers.

The same goes for **Shadow Dragons**. They probably add Shadow to their themes and gain some spells like five shadow strike, shadow form, and shadow walk.

**Comment by mlenser** [comment]
I'm curious what you think about the breath weapons. Acid Breath for example is the same as Acidic Spray, but Acidic Spray does less damage. We could remove the breath weapons.. hmm

**Comment by Marcloure** [comment]
I think breath weapons are good as a different thing. The reason why I think that is that they are more powerful (damage and AOE-wise) than spells. It's like they were full casters to use the breath weapon!

**Comment by mlenser** [comment]
Added Black dragons with some tweaks:

- https://marklenser.com/rpg/monsters/black-dragon-wyrmling
- https://marklenser.com/rpg/monsters/young-black-dragon
- https://marklenser.com/rpg/monsters/adult-black-dragon
- https://marklenser.com/rpg/monsters/ancient-black-dragon

Let me know what you think

**Comment by Marcloure** [comment]
I think dragons can fling with their bite (grab and throw) and tail, no?

**Comment by Marcloure** [comment]
Oh, also, I gave _Tear Tendon_ to Black Dragons because they like to play with their prey, letting them escape to hunt them down again. The idea was that the dragon would hurt the creature and watch it try to run while bleeding.

**Comment by mlenser** [comment]
> I think dragons can fling with their bite (grab and throw) and tail, no?

ya

> Also, I gave command to the Black Dragon, but forgot it to the others.

Could you add it? Will be easier as I go through.

______

> Oh, also, I gave Tear Tendon to Black Dragons because they like to play with their prey, letting them escape to hunt them down again. The idea was that the dragon would hurt the creature and watch it try to run while bleeding.

But then it should also have _Bleed_.

**Comment by Marcloure** [comment]
> Could you add it? Will be easier as I go through.

Done

> But then it should also have Bleed.

It could, but _bleed_ doesn't kill because the target got panicked and ran away. It's not as fun.

**Comment by mlenser** [comment]
## Wymlings

- "maneuvers": ["Ambush", "Dive Attack"],
- **Spells**: 1-3 cantrips, 3-4 spells

## Young

- "maneuvers": ["Ambush", "Dive Attack", "Swipe (Claw only)", "Fling"],
- **Spells**: Wymling Spells + Frighten, Command + more

## Adult

- "maneuvers": ["Ambush", "Dive Attack", "Fearsome Beast", "Swipe (Claw only)", "Fling", "Fountain of Blood"], +1 more if possible
- **Spells**: Young spells + more

## Ancient

- "maneuvers": ["Ambush", "Dive Attack", "Fearsome Beast", "Swipe (Claw only)", "Fling", "Fountain of Blood"], +1 more if possible
- **Spells**: Adult spells + more

**Comment by Marcloure** [comment]
I'm not sure if every dragon should have ambush. Although Red Dragons are proficient in Stealth, I don't think Red Dragons are the kind to ambush

**Comment by mlenser** [comment]
Indeed. I've pushed the Chromatic dragons now. Let me know what you think.

I changed the Green Dragon to Contamination more than other themes. But reading it now maybe I should also add Trickery of some kind, but that's a lot of spells.

**Comment by mlenser** [comment]
Added charm theme spells to green dragons as well.

**Comment by mlenser** [comment]
Added maneuvers and spells to chromatic drakes

**Comment by Marcloure** [comment]
I think that if I were to change something, would be just to remove _command_ from white dragons. They are very non social, even between dragons, and also not very clever. The are more hunters than tyrants.

**Comment by mlenser** [comment]
Anything else?

**Comment by Marcloure** [comment]
I think that is all.

**Comment by mlenser** [comment]
added some sand spells to blue dragons
