### ISSUE TITLE
Influence Animals

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#460]
Cantrip suggestion - intended to evoke the "relationship with animals" part of Beast. It's meant to be like a mix of Druidcraft and Charm, that works on small animals. It lets you shoo mosquitos, pet a cute cat, or frighten a donkey.

---

### Influence Animals ("Animal Whisper"? "Control Pests"?)

**Cantrip (beast theme)**
*Duration: 1 minute*

As an action, you attempt to affect the behavior of an animal. A beast of your choice within 30 feet, or a swarm of them, must make a Will saving throw. Creatures with CR of 1/4th or higher are unaffected.

On a failure, the creature is drawn towards you. It will attempt to approach you, if it appears to be a safe course of action. Alternatively, you can choose to drive the creature away, making yourself appear scary or disgusting to the creature.

On a success, the creature may become agitated, at the GM's discretion. An agitated creature may flee, hide, or attack.

**Comment by mlenser** [comment]
Animal Friendship converted from a 1 mana spell to a cantrip
