### ISSUE TITLE
Magus: Replace War Magic

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#461]
Add an option for many themes that give damage or damage+minor effect instead. Examples:
- 1d4 cold damage and slowed 1 (if not slowed already)
- 1d6 force damage

**Comment by itamarcu** [comment]
This would help speed up combat, for Magus players who used saving throw cantrips, which would be nice 👍 

However, I'd rather not have it be a simple "you add 1d6 fire damage when you hit a creature". Too many classes have the same ability with slight alterations, and I'd rather keep the Magus unique.

Casting a cantrip along with your attack allowed for this - it was flavorful and special, and I think it rewarded players for being creative with non-damaging effects (e.g. using Light to prevent an enemy from hiding, Gust to push an enemy away, Poison to poison).

**Comment by Paulorpribeiro** [comment]
I think we can keep current state if we address the issue that, imo, make the feature a little overpowered:

-It currently add 1d8 (produce flame for example) damage to the attack at early levels, which is a buffed up sneak attack every round with no caveat, or a free maneuver every round (for a minute, then you cast again) with no cost in stamina and only a bonus action every minute I stead of every turn;
-It has no concentration, so it stacks with other buffs;

These are the main things I think need some.kind of fixing, now my proposed solutions:

-Limit it to one attack per cast. It is a cantrip, can be cast infinitely, there is no need to have it last any amount of time. The cantrip that last either conjure a weapon or don't deal damage, and if they deal.damage, they end.
- Have a hard limit on it, like witchcraft or chamei divinity. I'd rather not go that route though.

**Comment by itamarcu** [comment]
We first need to agree on what the problems are, if any, before trying to fix them.

Currently, the DPR on a magus is **balanced** (as far as I can tell). So, @Paulorpribeiro - the Magus should be as strong as other classes, with this "always on" +1d4 damage buff.

Also, note that it's 1d4 and not 1d8, because the extra damage is halved for anything with an attack roll (and things with a saving throw work about half the time so it's balanced around this).

**Comment by mlenser** [comment]
@Paulorpribeiro when discussing balance, you should always refer to DPR. Discussing in real terms like 1d8 vs 1d6 misses the save, as @itamarcu mentioned. The DPR sheets are there for everyone to see.

Magus is actually on the lower end through the middle levels. It's definitely balanced as far as the math shows.

**Comment by Paulorpribeiro** [comment]
Well, I misread it. If it is supposed to compare to hex, divine strike and hunters mark, I guess it is alright. It just feels like "free enchant weapon" but I guess so is divine strike. Hope that's where we change when reducing the DPR of all classes.

**Comment by mlenser** [comment]
War Magic reworked a bit to weave spells in between attacks which allows for more targets and diversity for non-combat spells as well
