### ISSUE TITLE
Bend Luck should use 1d4 instead of half your stamina die

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#462]
[Bend Luck](https://www.kryxrpg.com/maneuvers/bend-luck) (the maneuver) is similar to [Bend Luck](https://www.kryxrpg.com/spells/bend-luck) (the spell), in that at its base form it adds 2.5 on average to a roll. However, the maneuver does this by adding 1d8 divided by 2 and rounded up, instead of just adding 1d4. (note - the spell has some other differences, such as being able to affect an ally or an enemy. I don't think there's a balance problem.)

This is problematic because there are enhancements that increase the "die" to 1d6, 1d8, or 1d10.

I suggest making the wording the same as the spell:

> Roll a d4 and apply the number rolled

**Comment by mlenser** [comment]
Bend Luck maneuver augments updated to reflect that it is a maneuver
