### ISSUE TITLE
Move "Create Thrall" augment from Enthrall to Charm Creature

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#463]
![](https://media.discordapp.net/attachments/736805578504011804/736864924760014968/unknown.png)

Other than using the word "thrall", the augment is unrelated to the Enthrall spell. Furthermore, the augment is incredibly strong, if it applies to all creatures you can see within 60 feet, and makes half of them your allies for 24 hours.

I suggest removing this augment from Create Thrall, and adding it to [Charm Creature](https://www.kryxrpg.com/spells/charm-creature), as a 1-mana augment. There could also be an augment to increase the duration to 24 hours for 1 mana.

This way, it would be...

- 1 mana to charm a creature for 1 hour
- 2 mana to thrall a creature for 1 hour
- 3 mana to thrall a creature for 24 hours, or to thrall two creatures for 1 hour

**Comment by mlenser** [comment]
Create Thrall split from Enthrall
