### ISSUE TITLE
Cantrips such as Guidance, Luck, etc. can be stacked for a huge ability check increase

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#465]
The following cantrips all add 1d4 to a creature's ability check: [Luck](https://www.kryxrpg.com/spells/luck), [Guidance](https://www.kryxrpg.com/spells/guidance), [Confidence](https://www.kryxrpg.com/spells/confidence), [Ancestral Blessing](https://www.kryxrpg.com/spells/ancestral-blessing), [Wild Guesses](https://www.kryxrpg.com/spells/wild-guesses).

If a party has all of these spells (on different characters, since it's concentration), they can stack them for +5d4 to a creature's ability check. Outside combat and group checks, this is like functionally giving +10 to all skill checks for all characters, and it's not great.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/88483661-95cd5900-cf69-11ea-96e9-b0f07043d219.png)
this rule would apply.

The effects have different names, but they have the same effect. RAI they are not meant to stack.

**Comment by mlenser** [comment]
wording cleaned up
![image](https://user-images.githubusercontent.com/235857/88483881-07f26d80-cf6b-11ea-89e9-c2d9ad5e243b.png)

**Comment by Marcloure** [comment]
If that is the intention, then we need to update that rule to say that spells that work in similar fashion don't stack. Currently, if two spells have different names, then they're different spells and they stack.

It would also apply in other instances where similar spells stack, like _blur_ with _concealing amorpha_, _battle leader_ with _crusader's mantle_, and more

**Comment by mlenser** [comment]
@Marcloure that'll be covered with the new wording.

**Comment by itamarcu** [comment]
That's a good change!

Perhaps the "Light Weapon Master" feat could be split up again, now that it can't be stacked? Just to have the more specific flavor in each theme.
