### ISSUE TITLE
Minor Spell Resistance could be improved a little bit

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#466]
[Minor Spell Resistance](https://www.kryxrpg.com/spells/minor-spell-resistance) gives +1d4 to saving throws against magic.

[Resistance](https://www.kryxrpg.com/spells/resistance) gives +1d4 to saving throws against anything.

To make them a bit more balanced against each other - and more unique - I suggest adding this to MSR (similar to Precognition):

> As an action, you touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice against magic. It can roll the die before or after making the saving throw. The spell then ends. **Alternatively, when the target is attacked with a spell, it can roll a d4 and add the number rolled to its Defense against that spell attack.**

**Comment by mlenser** [comment]
Some options are better than others due to their theme thematics. This is one of those cases.

Minor Spell Resistance shouldn't make you less vulnerable from getting hit by rocks flung via telekinesis.
