### ISSUE TITLE
Dervish Battle Dance should not work with ranged weapons

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#467]
I don't think it's thematic to have battle dancers who use bows. In all media I know, these kinds of characters are either completely reliant on martial arts (like monks) or reliant on weapons (usually light weapons but I guess it's not required).

Thrown weapons are okay, IMO -  I think a knife dancer makes sense, and that character would like to be able to throw their dagger at people.

So, I suggest changing the limitation of Battle Dance to:
> ...you gain the following benefits if you aren’t wearing plate armor or using a shield **or a ranged weapon**.

**Comment by mlenser** [comment]
It is purposeful that they can use melee or ranged weapons.
