### ISSUE TITLE
Blight vs. Horrid Wilting

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#47]
Both spells fulfill the same niche, and both are in the Plants theme. Horrid Wilting is 2 mana though.

**Comment by mlenser** [comment]
Blight is a single target while Horrid Wilting is an aoe.

Same as Scorching Ray vs Fireball.

**Comment by Marcloure** [comment]
Wow, that is correct. I have no idea how I let that pass.
