### ISSUE TITLE
Brawn/Acrobatics checks during conditions such as Restrained or Unconscious

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#470]
I'll start with the suggested solution (as this was partly discussed on Discord):
1. Change the Paralyzed, Petrified, Stunned, and Unconscious conditions as follows:
> - The creature automatically fails Reflex saving throws, **Strength checks, and Dexterity checks.**
2. Change the Restrained condition as follows:
> - The creature has disadvantage on Reflex saving throws, **Strength checks, and Dexterity checks, unless those are made to escape its restraints.**
3. Change the [Cocoon](https://www.kryxrpg.com/spells/cocoon) spell as follows:
> ... be ~~paralyzed~~ **restrained and blinded** for the duration.

---

This will fix the following problems:
- Dragging unconscious (or paralyzed, etc.) creatures should be easier, and it requires grappling them. Players/GMs probably already allowed uncontested grapple on these creatures.
- Cocoon is broken and doesn't allow normal escape ([this fix did not help](https://github.com/mlenser/kryx-rpg-issues/issues/432))
- A creature restrained in a net should be a bit easier to restrain with another net, or grapple (it's already easier with the grapple maneuver, but not the standard grapple attack).

While maintaining:
- A creature restrained in a net shouldn't have disadvantage on trying to escape the net
- An incapacitated creature shouldn't necessarily be easier to grapple; for example, Symbol of Pain just prevents a creature from acting, but not moving or instinctively trying to avoid being grabbed.

**Comment by mlenser** [comment]
The proposed option for Cocoon doesn't give this part of the Paralyzed condition:
> Any attack that hits the creature is a critical hit if the attacker is within 1.5 meters of the creature.

Attacking a cocooned creature should be a crit, I believe.

Fuse Flesh is very similar to Cocoon in flavor. I've changed it to break free like Cocoon does.

**Comment by DalenWBrauner** [comment]
I'm unsure how to thematically justify a guaranteed critical strike on a creature that is almost completely encased in a substance. Even if you think you know the location of your opponent's neck, the cocoon itself has Defense and HP stats because it isn't trivial to cut through.

**Comment by mlenser** [comment]
And on Fuse Flesh?

**Comment by itamarcu** [comment]
Well, another way to solve it is just to extend my suggestion to the other effects - have Paralysis cause you to auto-fail all Reflex saves except those that are made to escape it.

However, this really feels like a special case, so maybe a better solution is to write the exception into the Cocoon and Fuse Flesh spells? Have them say that they paralyze you, and at the end of your turn you make a Reflex save, and that reflex save is unaffected by your paralysis.

**Comment by DalenWBrauner** [comment]
Good point. For the case of Fuse Flesh, I think shem's solution is best. 

For cocoon, I think whether or not it should be easier to break someone out than it is to crit the trapped person, might just be up to how sturdy the material is. When I see "webbing", I think "okay, yeah, this could be thin and pliable enough to get some good attacks in without freeing the opponent". When I see "like a mummy" and the defense/HP stats, I think "maybe this is a sturdy material, as a weapon may fail to break or cut through it. It might resist a weaker fireball or hammer, so it would make sense the target would resist the same". It's not that defense/hp and paralysis _have_ to be mutually exclusive, I'm just unsure how durable the substance is supposed to be, judging from the spell text alone.

In any case, I think shem has a good direction for the originally-posted problems.

**Comment by DalenWBrauner** [comment]
Some cocoons in media become rather hard and have to "crack" open, some are little more than being encased in a thin gluey gum, and some are inbetween. That interpretation probably matters for determining the spell's effects.

**Comment by mlenser** [comment]
Paralyzed and Restrained conditions updated to specify that they impact Strength and Dexterity checks

**Comment by mlenser** [comment]
The goal of cocoon is to be a bestial equivalent to spells like Hold Creature. It is meant to be paralyzing.

**Comment by itamarcu** [comment]
So could it just use a Reflex save and explicitly say "this save is not affected by the paralyzed effect"? (not necessarily in these words, could even explain how it's because your body can still move inside the cocoon)
