### ISSUE TITLE
Patience defense s little too strong

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#471]
Let's compare the defensive benefit first

It allows you to take the dodge action as a bonus, which is huge. Disadvantage  to attacks against you equates to having +3 to +5 defense. Thats at least equivalent to a 3 stamina parry or nimble dodge. Another comparison I found is the shadow veil spell at 2 mana, which allows you to force a rerrol on attacks against you or an ally until the start of you next turn, very similar to disadvantage. Keep in mind that basic shadow veil (1 mana) allows you to force a rerrol to ONE attack.

The defensive part allows you to make an attack as a reaction if an enemy misses you. The caveat is this is an unarmed attack. Well, for monks, sacred fists and some other builds it is the same as Riposte, baked into the original maneuver.

My proposed change is the following:
Patient Defense (1 stamina)

"As a bonus action, you can enter a defensive stance. You can force the first creature you can see that hits you before the start of your next turn to rerrol the attack and use the worst result.

Enhance
If you expend 1 additional stamina dice and a creature misses you before the start of your next turn , you can use your reaction to make a meele attack against the creature. If the attack is made with a weapon wielded in one hand, add half the result of one of the stamina dice to the attack’s damage roll.

**Comment by Paulorpribeiro** [comment]
With this fix the defense part is roughly equivalent to the shadow veil spell, only afecting you and using a bonus action inatead of a reaction asd the riposte part is streamlined to all classes and made part of an augment, to.match the riposte maneuver (2 stamina)

The way it was, and even if you weren't a monk, the defensive part of the spell is already way better than other options, and for monks the patient defense maneuver was a better riposte at 1 stamina

**Comment by mlenser** [comment]
Patient Defense has to be used beforehand, while other options like Parry can be used as a reaction when you're just barely hit. Completely different use cases that are not comparable.

**Comment by Paulorpribeiro** [comment]
But do you agree it is too strong? Dodge as a bonus action is a lot superior than a measly +1 to defense, even of you can use the +1 defense as a reaction to being hit. 

With dodge (+3 to +5 to defense for most cases) you practically guarantee you won't be hit. You also get a riposte maneuver for free, even before you could afford to learn the riposte maneuver

**Comment by itamarcu** [comment]
With a preemptive Dodge, an enemy might just choose not to attack you. Yeah, it guarantees you won't be hit, but it might just shift the damage to one of your allies instead of canceling it (like a reaction maneuver will do).

As for "only good for monks", I suggest changing it as follows (helps encourage light weapon users, sword-and-dagger, and even flavor for monks who use weapons):

> ... you can use your reaction to make an unarmed strike against the creature **or to attack with a light weapon**.

As for being overpowered - I do think it's a bit too powerful at low levels, and if you're 1v1ing an enemy it's definitely more defensive than relying on a maneuver like Parry to keep you safe. It doesn't allow you to use the bonus action for damage, but the damage might still be added to the reaction attack, so it's not like you're losing much on DPR.

It's also worth noting that Dodge gives you advantage on reflex saves, in addition to the attack disadvantage for enemies.

I think this maneuver would be balanced as a 2 stamina maneuver.

**Comment by Paulorpribeiro** [comment]
My original propose was breaking the reaction attack part and make it into an augment, in order to keep the defensive part of the maneuver at 1 stamina. But I'm not against making it a 2 stamina and keep both things.

**Comment by mlenser** [comment]
Patient Defense changed to just be dodge without a reaction attack. A reaction attack exists on several other maneuvers

**Comment by mlenser** [comment]
> Although a 2 stamina maneuver that keeps both the defensive (dodge) and offensive (riposte) parts, is obviously better than riposte currently. The reaction attack part of this maneuver has to be weaker than riposte for all classes.

That wouldn't be the case as Patient Defense has to be used preemptively. That makes a huge difference.

But it doesn't matter now.

**Comment by Paulorpribeiro** [comment]
I like this change, the maneuver now is actually quite good for tanks, better than block blow. You boost your defense with your bonus action and keep your reaction if the enemy tries to get past you and go for the back line.

**Comment by mlenser** [comment]
Well, block blow is a reaction.
A bonus action is valuable when you know you'll be attacked while reactions are good when you're occasionally attacked or to add on top of of a normal maneuver.
