### ISSUE TITLE
GWF Dervish dpr gets too high

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#475]
My friend pointed out that the Dervish damage is considerably high with GWF after the 9th level. It has 45 DPR at 9th level, while other classes range from 36 to 41. This extra damage remains until the 20th level, reaching 10 DPR above some options then.

I believe the best way to solve this is to grant the Battle Dance's extra attack at 9th level only if you don't wield two-handed weapons. The spreadsheet doesn't count it, but I believe bow Dervish must be quite above the rest as well, so not allowing two-handed weapons would solve both.

Also, Battle Dance includes other bonuses that are not counted on the spreadsheet. The +2 to AC means you can have as much AC as with shield while wielding a greatweapon.

**Comment by mlenser** [comment]
That's simplifying the situation. Dervish is a bit high at some points, but is overall totally fine for Polearms:
![image](https://user-images.githubusercontent.com/235857/89198880-1d404b00-d5ae-11ea-9977-5772a07ee095.png)

**Comment by mlenser** [comment]
Also note: Berserker gets resistance to damage during the same period as Dervish gets +2 AC.

**Comment by mlenser** [comment]
Dervish Extra attack was mis-calculated. It multiplied the attack chance twice, so the damage is higher than expected.

I'll look at it overall.

**Comment by mlenser** [comment]
Warrior: Dervish changed back to not give an additional attack for two handed weapons

**Comment by Marcloure** [comment]
I'm still wondering how this can be balanced when compared to action surge. At 9th level, the two extra attacks from Battle Dance is similar to action surging every turn for 1 minute. But if the sheet says that it's balanced, I can only trust it.

**Comment by mlenser** [comment]
## 1st round with Action Surge
- 2 attacks
- Bonus action (maneuver)
- 2 attacks

## 1st round with Battle Dance
- 2 attacks
- 1 extra attack

Additional considerations:
- Battle Dance can only be used once betweens rests, or twice between rests at 9th level. Action Surge can be used up to 5 times (though not immediately in the next round).

**Comment by Marcloure** [comment]
## 1st round with Action Surge

- 2 attacks
- Bonus action (maneuver)
- 2 attacks

## 1st round with Battle Dance

- 2 attacks
- 1 extra attack

I suppose this is at 5th level, right? At 9th, Battle Dance is 2 attacks + 2 extra attacks, which is the same as action surge. You don't get to use a maneuver at the first round, but you are getting an attack-only action surge every round after that

**Comment by mlenser** [comment]
Warrior: Dervish removed as Battlemaster can cover the niche of an agile warrior
