### ISSUE TITLE
Stone Bones balance

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#476]
Stone Bones might be too strong. For 2 stamina as a reaction, it gives you resistance to three damage types for a round, along with +1 defense.

Compare that to Uncanny Dodge which replaces the +1 defense with halving a single attack's damage.

They aren't obvious to compare - Uncanny Dodge lets you avoid attacks that deal other damage types, too - but it still feels like Stone Bones is a bit too much.

**Comment by Paulorpribeiro** [comment]
If you take away the +1 to def, it's similar to the bladeward cantrip as a reaction.
A lkso, +1 to defense (that helps you avoid getting hit) and resistance to some damage types work against each other. If the +1 to defense helps you not get hit, you won't benefit from the augment, and if you do get hit, +1 to defense is useless.

**Comment by Marcloure** [comment]
> +1 to defense (that helps you avoid getting hit) and resistance to some damage types work against each other

As the maneuver lasts an entire round, you can block some attacks and reduce the damage from others, so it's not totally useless if you are target by more than 1 attack.

**Comment by Paulorpribeiro** [comment]
Well, for all attacks the dilema is the same, you either use one half of the maneuver or the other. You may use one half against one attack, and the other half against the other.
But that is besides the point imo, +1 to def AND resistant to damage don't pair well together in the same maneuver

**Comment by mlenser** [comment]
- **Earth**
  - Stone Bones changed to only half the damage against you
- **Skirmish**
  - Nimble Dodge renamed Uncanny Dodge and the augment to half the damage is removed
