### ISSUE TITLE
Wrath of Nature requires a saving throw after an attack

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#479]
https://www.kryxrpg.com/spells/wrath-of-nature

> ***Rocks***. As a bonus action on your turn, you can cause a loose rock in the sphere to launch at a creature you can see in the sphere. Make a ranged spell attack against the target.
> On a hit, the target takes 4d8 bludgeoning damage, and it must succeed on a Reflex saving throw or fall prone.

Very few effects require a saving throw after an attack roll - and these are effects that cause long-duration consequences (banish, contagion, etc). This effect is repetitive, and it's a bonus action, so it will slow down the game a bit.

I think the prone condition should be imposed if you hit with the attack, instead of being behind a saving throw. The damage could be reduced, to account for this.

**Comment by mlenser** [comment]
That's how it is by RAW. Saves after an attack exist in many places in the system. It isn't super common, but there isn't a goal to get rid of it.
