### ISSUE TITLE
Metallic Dragons' spells and maneuvers

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#48]
Continuing from #46, now for metallic dragons.

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Brass Dragon
Brass dragons are talkative. They like to talk even when their listener doesn't want to hear from them. 

Overall, their **spell themes** are Charm, Fear, and Mind. Their **martial theme** is Beast.
### Wyrmling
#### Maneuvers (1 stamina, limit 1): 
- **1 stamina die:** pounce, sprint (really unsure about this one, but brass dragons seem to be playful)

#### Spells (1 mana, limit 1): 
- **cantrips:** charm, lullaby
- **1 mana:** charming presence, sense minds

### Young
#### Maneuvers (8 stamina, limit 2):
- **1 stamina die:** fearsome beast, pounce, sprint (see wyrmling)
- **2 stamina dice:** fountain of blood

#### Spells (4 mana, limit 2): 
- **cantrips:** charm, frighten, lullaby
- **1 mana:** charming presence, command, friends, mind trap, sense minds, sleep
- **2 mana:** charm creature, enthrall, instinctive charm

### Adult
#### Maneuvers (15 stamina, limit 4):
- **1 stamina die:** fearsome beast, pounce, sprint (see wyrmling)
- **2 stamina dice:** fountain of blood

#### Spells (8 mana, limit 4): 
- **cantrips:** charm, frighten, lullaby
- **1 mana:** charming presence, command, fear, friends, mind trap, sense minds, sleep
- **2 mana:** charm creature, enthrall, frightful presence, instinctive charm
- **3 mana:** catnap, douse the flames of war, incite panic

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** fearsome beast, pounce, sprint (see wyrmling)
- **2 stamina dice:** fountain of blood

#### Spells (10 mana, limit 5): 
- **cantrips:** charm, frighten, lullaby
- **1 mana:** charming presence, command, fear, friends, mind trap, sense minds, sleep
- **2 mana:** charm creature, enthrall, frightful presence, instinctive charm
- **3 mana:** catnap, douse the flames of war, incite panic
- **5 mana:** glibness

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Bronze Dragon
Bronze dragons are creatures of the sea. They are apt swimmers and involved with the water and sea creatures. They also take part in warfare, often joining arms that fight against tyranny.

Overall, their **spell themes** are Beast, Fear, Water. Their **martial themes** are Beast and Vanguard.
### Wyrmling
#### Maneuvers (3 stamina, limit 1): 
- **1 stamina die:** dive attack, precision

#### Spells (2 mana, limit 1): 
- **cantrips:** shape water
- **1 mana:** animal friendship, beast bond, wave shield

### Young
#### Maneuvers (11 stamina, limit 3):
- **1 stamina die:** dive attack, fearsome beast, precision
- **2 stamina dice:** fling, fountain of blood

#### Spells (6 mana, limit 3): 
- **cantrips:** frighten, shape water
- **1 mana:** animal friendship, beast bond, command, create/destroy/purify water, fog cloud, locate animals, locate water, wave shield
- **2 mana:** tidal wave, water breathing

### Adult
#### Maneuvers (17 stamina, limit 5):
- **1 stamina die:** fearsome beast, hammering blow (Tail only), pounce, sprint (see wyrmling)
- **2 stamina dice:** fling, fountain of blood

#### Spells (9 mana, limit 5): 
- **cantrips:** frighten, shape water
- **1 mana:** animal friendship, beast bond, command, create/destroy/purify water, fear, fog cloud, locate animals, locate water, wave shield
- **2 mana:** call beast, frightful presence, tidal wave, water breathing
- **3 mana:** control water, incite panic
- **4 mana:** maelstrom

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** fearsome beast, hammering blow (Tail only), pounce, sprint (see wyrmling)
- **2 stamina dice:** fling, fountain of blood

#### Spells (10 mana, limit 5): 
- **cantrips:** frighten, shape water
- **1 mana:** animal friendship, beast bond, command, create/destroy/purify water, fear, fog cloud, locate animals, locate water, wave shield
- **2 mana:** call beast, frightful presence, tidal wave, water breathing
- **3 mana:** control water, incite panic
- **4 mana:** maelstrom

**Comment by Marcloure** [comment]
### Copper Dragon
Copper dragons are hosts and pranksters. They like trickery, jokes, riddles and music. They are probably the most playful of all dragons. 

Copper dragons are also very related to the earth. They crave earthen minerals and can shape the tunnels of their lairs, often making false walls, pits, and other trap-like features.

Overall, their **spell themes** are Earth and Fear. Their **martial themes** are Beast and Trickery.
### Wyrmling
#### Maneuvers (1 stamina, limit 1): 
- **1 stamina die:** ambush, dive attack, disorient

#### Spells (1 mana, limit 1): 
- **cantrips:** minor illusion, mold earth
- **1 mana:** avalanche, fissures

### Young
#### Maneuvers (7 stamina, limit 2):
- **1 stamina die:** dive attack, disorient, fearsome beast, swipe (Claw only)
- **2 stamina dice:** fling, fountain of blood, misdirection

#### Spells (4 mana, limit 2): 
- **cantrips:** frighten, minor illusion, mold earth
- **1 mana:** avalanche, command, fissures
- **2 mana:** bones of the earth, earth tremor, earthbind, move earth

### Adult
#### Maneuvers (16 stamina, limit 4):
- **1 stamina die:** dive attack, disorient, fearsome beast, swipe (Claw only)
- **2 stamina dice:** fling, fountain of blood, misdirection

#### Spells (8 mana, limit 4): 
- **cantrips:** frighten, minor illusion, mold earth
- **1 mana:** avalanche, command, fissures
- **2 mana:** bones of the earth, earth tremor, earthbind, frightful presence, move earth
- **3 mana:** incite panic, stone shape
- **4 mana:** transmute rock, wall of stone

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** dive attack, disorient, fearsome beast, swipe (Claw only)
- **2 stamina dice:** fling, fountain of blood, misdirection

#### Spells (10 mana, limit 5): 
- **cantrips:** frighten, minor illusion, mold earth
- **1 mana:** avalanche, command, fissures
- **2 mana:** bones of the earth, earth tremor, earthbind, frightful presence, move earth
- **3 mana:** incite panic, stone shape
- **4 mana:** transmute rock, wall of stone

**Comment by mlenser** [comment]
I think Brass should be based on Sand based on it being listed a lot on their description [PF](https://www.d20pfsrd.com/bestiary/monster-listings/dragons/dragon/metallic-brass/).

**Comment by Marcloure** [comment]
Brass dragons do have lair and legendary actions that involve sand. Adding (or substituting) Sand makes sense.

Also, I just noticed none of the metallic dragons have elemental bane. Well, they do fell less connected to their breath damage than chromatic dragons (most people know that blue dragons breathe lightning, red breathe fire, and black breathe acid, but fewer are those who know what a brass or copper dragon breathes).

**Comment by mlenser** [comment]
Replacing Fling with Knockback and moving Swipe and Knockback down to Wyrmlings

**Comment by mlenser** [comment]
Added Trip (Tail only) to Adult and Ancient

**Comment by Marcloure** [comment]
I feel like a wyrmling's arm is too short for AOE attacks, no?

**Comment by mlenser** [comment]
Really depends what a Wymling looks like. I found this image on D&D beyond:

![image](https://user-images.githubusercontent.com/235857/78471235-0f79d680-7730-11ea-94de-6d0a62cbb714.png)

If a Bear can swipe, so can a wymling

**Comment by Marcloure** [comment]
Ok, if a black bear can, so should a wyrmling.

**Comment by mlenser** [comment]
Added some shadow spells to black dragons

(I haven't pushed the most recent stuff, will do so soon)

**Comment by Marcloure** [comment]
### Gold Dragon
Gold dragons are wise and solitary. The book really doesn't say much more about them. 

Overall, their **spell themes** are Fate (they have a legendary action to glimpse into the future. Also, gold dragons are a symbol of luck and destiny in eastern cultures), Fear and Fire. Their **martial theme** is Beast.
### Wyrmling
#### Maneuvers (limit 1): 
- **1 stamina die:** dive attack, knockback (Claw only), swipe (Claw only)

#### Spells (limit 1): 
- **cantrips:** luck, control flames
- **1 mana:** burning hands, continual flame, precognition

### Young
#### Maneuvers (limit 3):
- **1 stamina die:** dive attack, fearsome beast, knockback (Claw only), swipe (Claw only)
- **2 stamina dice:** fountain of blood

#### Spells (limit 3): 
- **cantrips:** frighten, luck, control flames
- **1 mana:** burning hands, continual flame, foretell, precognition
- **2 mana:** bend luck, command, fear, fireball, remove curse, pyrotechnics 
- **3 mana:** flame bane

### Adult
#### Maneuvers (limit 4):
- **1 stamina die:** dive attack, fearsome beast, knockback (Claw only), swipe (Claw only)
- **2 stamina dice:** fountain of blood

#### Spells (limit 4): 
- **cantrips:** frighten, luck, control flames
- **1 mana:** burning hands, continual flame, foretell, precognition
- **2 mana:** bend luck, command, fear, fireball, frightful presence, remove curse, pyrotechnics 
- **3 mana:** flame bane, incite panic, wall of fire

### Ancient
#### Maneuvers (limit 5):
- **1 stamina die:** dive attack, fearsome beast, knockback (Claw only), swipe (Claw only)
- **2 stamina dice:** fountain of blood

#### Spells (limit 5): 
- **cantrips:** frighten, luck, control flames
- **1 mana:** burning hands, continual flame, foretell, precognition
- **2 mana:** bend luck, command, fear, fireball, frightful presence, remove curse, pyrotechnics 
- **3 mana:** flame bane, incite panic, wall of fire

**Comment by Marcloure** [comment]
### Silver Dragon
Silver dragons are the most social of all dragons. They are chivalrous and defenders of the weak.

Overall, their **spell themes** are Antimagic, Fear and Ice. Their **martial themes** are Beast and Protection.
### Wyrmling
#### Maneuvers (limit 1): 
- **1 stamina die:** covering strike, dive attack, knockback (Claw only), swipe (Claw only)

#### Spells (limit 1): 
- **cantrips:** frostbite, minor spell resistance
- **1 mana:** cold snap, cone of cold, deflect spell, detect magic, ice slick, purge

### Young
#### Maneuvers (limit 3):
- **1 stamina die:** covering strike, dive attack, fearsome beast, knockback (Claw only), swipe (Claw only), sacrifice
- **2 stamina dice:** fountain of blood

#### Spells (limit 3): 
- **cantrips:** frighten, frostbite, minor spell resistance
- **1 mana:** cold snap, command, cone of cold, deflect spell, detect magic, fear, ice slick, purge
- **2 mana:** cold fog, freezing sphere, counterspell, dispel magic, protection from cold
- **3 mana:** frost bane, private sanctum, wall of ice

### Adult
#### Maneuvers (limit 5):
- **1 stamina die:** covering strike, dive attack, fearsome beast, knockback (Claw only), swipe (Claw only), sacrifice
- **2 stamina dice:** fountain of blood
- **4 stamina dice:** disarm

#### Spells (limit 5): 
- **cantrips:** frighten, frostbite, minor spell resistance
- **1 mana:** cold snap, command, cone of cold, deflect spell, detect magic, fear, ice slick, purge
- **2 mana:** cold fog, freezing sphere, frightful presence, counterspell, dispel magic, protection from cold
- **3 mana:** frost bane, incite panic, private sanctum, wall of ice
- **4 mana:** catapsi

### Ancient
#### Maneuvers (limit 5):
- **1 stamina die:** dive attack, fearsome beast, knockback (Claw only), swipe (Claw only)
- **2 stamina dice:** fountain of blood

#### Spells (limit 5): 
- **cantrips:** frighten, frostbite, minor spell resistance
- **1 mana:** cold snap, command, cone of cold, deflect spell, detect magic, fear, ice slick, purge
- **2 mana:** cold fog, freezing sphere, frightful presence, counterspell, dispel magic, protection from cold
- **3 mana:** frost bane, incite panic, private sanctum, wall of ice
- **4 mana:** catapsi

**Comment by Marcloure** [comment]
That does it for metallic dragons. Maybe I should go back and add the breath element theme to Brass, Bronze, and Copper.

**Comment by mlenser** [comment]
I already did those. I should push soon

**Comment by mlenser** [comment]
Silver seems more like Air/Cold. I don't see any Antimagic in its theme

**Comment by Marcloure** [comment]
Yeah, I don't see much of it too. I put Antimagic there more as an extension of its defender characteristic.

About Air, yeah, I agree. Reading about its lair again: "Silver dragons dwell among the clouds, making their lairs on secluded cold mountain peaks." They have some weather related powers as well.

**Comment by mlenser** [comment]
Review

- All Dragons get access to some fear theme spells and generally use a core of beast maneuvers with 1 or 2 others

## Chromatic:
- ***Black.*** Acid and Shadow spells
- ***Blue.*** Sand and Storm spells with some minor illusion stuff from Trickery
- ***Green.*** Charm, Contamination (poison), and Plant spells
- ***Red.*** Fire spells
- ***White.*** Ice spells

## Metalic
- ***Brass.*** Fire and Sand spells with some minor sleep stuff from Charm
- ***Bronze.*** Water and Storm spells with some minor beast stuff to talk with animals
- ***Copper.*** Acid and Earth spells
- ***Gold.*** Fate and Divine spells with some minor sleep stuff from Charm
- ***Silver.*** Air and Ice spells

First review: I should add some more fire spells to Red and see if White has any other theme to put in (though Ice has a lot of spells <=3 mana).

**Comment by Marcloure** [comment]
I think you broke the dragon's page, it's not loading

**Comment by mlenser** [comment]
it's fixed now

**Comment by Marcloure** [comment]
Oh, so monsters can break the usual limit of half casters PCs? That is cool.

If all is done here, I think I'll do orcs and other humanoids next.

**Comment by mlenser** [comment]
> Oh, so monsters can break the usual limit of half casters PCs? That is cool.

What do you mean?

**Comment by Marcloure** [comment]
Half casters and martials have limit of 5 at 20th level. Ancient dragons can progress further to limit of 8 and I suppose up to 10 at CR 27.

**Comment by mlenser** [comment]
The limit is supposed to be as follows:
0: 1
1: 1
2: 1
3: 1
4: 1
5: 2
6: 2
7: 2
8: 2
9: 3
10: 3
11: 3
12: 3
13: 4
14: 4
15: 4
16: 4
17: 5
18: 5
19: 5
20: 5
21: 6
22: 6
23: 6
24: 6
25: 7
26: 7
27: 7
28: 7
29: 8
30: 8
31: 8
32: 8
33: 9
34: 9
35: 9
36: 9
37: 10
38: 10
39: 10
40: 10

**Comment by mlenser** [comment]
Ahhh, right. I see the issue. That is based on a "caster level" ("X is a 17th-level spellcaster" as written in RAW).

"caster level" is not the same thing as challenge. Currently, "caster level" is determined by multiplying challenge by 1.25 and rounding it.

**Comment by Marcloure** [comment]
Yeah, caster level is usually higher than CR, but I didn't know we could have a creature be more than a 20th level half-caster. I thought the limit was 20th level half-caster or 20th level full caster.
