### ISSUE TITLE
Change Antilife Shell from 10 foot radius to a sphere centered on you

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#480]
[Antilife Shell](https://www.kryxrpg.com/spells/antilife-shell) currently says:

> a shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you

I think it would be more consistent and slightly more versatile if it was instead:

> a shimmering barrier extends out from you in a sphere and moves with you, remaining centered on you

This would make it the same as Holy Circle, Cloak of Flies, Wild Magic Sphere, Catapsi, etc.

There would be no difference when cast at 2 mana (still radius of 10 feet); the only difference would be when casting it with more mana.

**Comment by mlenser** [comment]
Antilife Shell changed from a 10-foot radius to a sphere so it scales
