### ISSUE TITLE
+ defense spells and maneuvers are not as valuable with the near miss change.

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#481]
With the change that attacks that miss by 4 or less still deal half damage, the value of + defense spells and maneuvers changes.

The reaction spell (or maneuver) used to make a 15 damage hit into a 0 miss. Now it has a chance to change a 15 dmg hit into a 7.5 dmg and a chance to make a 7.5 dmg near miss into a 0 dmg miss.
I'm not sure if the damage reduction per mana (or stamina) is the same, or maybe just a little less, but the damage reduction per action is very different, I'd say half the value (you used to reduce 15 damage with a reaction, now you reduce 7.5). We should discuss how to address and adapt to this change.

**Comment by Marcloure** [comment]
Maybe we add "+2 AC and you don't take half damage from an attack that missed by 4 or less"?

**Comment by mlenser** [comment]
I don't think we should override the partial hit rules.

I need to evaluate the numbers.

**Comment by Paulorpribeiro** [comment]
I also agree we should evaluate the numbers first, but at some point player will want an option (spell, maneuver feature, class, magic item) to override the partial hits.

As for defense spells and maneuvers, I think giving an extra +1 to defense at base cosy an keeping the progression rate at +1 per stamina +2 per mana (and increase the maximum) is sufficient

**Comment by mlenser** [comment]
> at some point players will want an option (spell, maneuver feature, class, magic item) to override the partial hits.

I don't plan to offer it. I'm not a huge fan of "here is the standard rule and here is option X to override it". Some rules should be set.

**Comment by mlenser** [comment]
## Tier 1:

Goblin does ~5 damage
Parry, if used correctly, will reduce ~2.5 damage

## Tier 2:

Drider does ~12 damage
Parry, if used correctly, will reduce ~6 damage (from 12 to 6 or 6 to 0) with the potential for ~12 more damage, but a very low chance of that
Stone bones will reduce ~6 damage or ~3 damage

Tier 3 is pretty similar to tier 2

## Conclusion
- Parry should probably only block one attack
- Stone Bones is the same strength of a well-used parry. I wonder how to balance the chance for parry to not be used correctly.

**Comment by mlenser** [comment]
Maneuvers and spells updates. Spells grant +4 Def, scale once by 2. Maneuvers grant +2 Def, scale by 1 for each stamina die.
