### ISSUE TITLE
Eidolon health clarification in Fuse Form

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#483]
One of the dots from Fuse Form states:

> When you transform, you gain temporary health equal to the **companion** form’s Constitution multiplied by double the amount of resources used. When you divide, you return to the amount of health you had before you transformed and any remaining temporary health vanishes.

How does this line interact with "If your eidolon is reduced to 0 health while you are fused, you are immediately ejected"? Do you still track the eidolon health while you are fused with it?

**Comment by mlenser** [comment]
Fuse Form wording about health removed. Your Eidolon has health and you use that while fused
