### ISSUE TITLE
Align Ebb and Flow to use the same saving throw

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#484]
Currently, [Ebb and Flow](https://www.kryxrpg.com/spells/ebb-and-flow) (which is a very cool spell) uses a Reflex saving throw when doing high-damage-low-heal, and a Fortitude saving throw when doing low-damage-high-heal.

I suggest changing it to always use Fortitude.

**Reasons:**
- Drawing water or life force away from a creature feels like it should always be Fortitude
- Players won't need to remember that this spell uses two different saves
- This spell's versatility comes from the ability to heal and hurt at the same time, and to choose which one to focus on; adding saving throw versatility is not necessary
- It will slightly reduce the value of the Reflex option, and by doing that, make it a bit closer to the perfect numbers

**Comment by mlenser** [comment]
Ebb and Flow now uses Fortitude for the Ebb part of the spell
