### ISSUE TITLE
Spells that use several saving throws

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#485]
I noticed that a few spells use several saving throws. I made a list of small issues I found:

- Ebb and Flow - could both be Fortitude, I created #484 for more detail
- [Drown](https://www.kryxrpg.com/spells/drown) - the spell starts with Reflex and continues with Fortitude. In the [Power Balance Sheet](https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=1121938024), the spell says it starts with Fortitude. One of these sources should be changed to fit the other one.
- [Fate Link](https://www.kryxrpg.com/spells/fate-link) starts with Fortitude and continues with Will. I don't see why these are two different saves. Resisting being "fate-linked", however it happens, should be consistent.
- [Prismatic Vortex](https://www.kryxrpg.com/spells/prismatic-vortex), [Prismatic Spray](https://www.kryxrpg.com/spells/prismatic-spray) and [Prismatic Wall](https://www.kryxrpg.com/spells/prismatic-wall) use different saves for the Violet option - it's Will in the vortex and the wall, but it's Fortitude in the spray. I think all of them should be Will (which matches Wisdom, in 5e, for the two others).

**Comment by mlenser** [comment]
- Drown now uses Fortitude for the initial saving throw
- Fate Link now uses Will for both saving throws
- Prismatic Vortex and Prismatic Wall now use Fortitude for the Violet option as that option blinds. The wording about the creature being sent to another plane is removed.
