### ISSUE TITLE
Reincarnate Card is strangely long

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#486]
Although it looks fine on [its own page](https://www.kryxrpg.com/spells/reincarnate), on [the Spirit page](https://www.kryxrpg.com/themes/spirit), the card for the Reincarnate spell seems to extend a superfluous length:

![image](https://user-images.githubusercontent.com/3477032/89724658-021d7300-d9d4-11ea-86a5-1c929217958e.png)

I've tested this under various page widths, with different sizes in the gap as a result.

**Comment by mlenser** [comment]
adjust height calculation for long tables
