### ISSUE TITLE
Wild Surges - Polymorph

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#488]
in the [Wild Surges table](https://www.kryxrpg.com/themes/chaos) there are options that make you cast Polymorph on yourself or on a random creature. It should specify what they polymorph *into*, I think, like how in 5e it polymorphed you into a sheep.

Perhaps it can be "a random beast" or "a CR 0 beast chosen by the GM" or something. But it shouldn't be chosen by the player, IMO, since it's a low and unlucky roll.

Also, unrelated, but there's a small typo in that same page - "hhealth".

**Comment by mlenser** [comment]
Polymorph:

> The creature must make a Will saving throw or be **transformed into a harmless beast appropriate to the area** for the duration.
