### ISSUE TITLE
Totem Spirit: Tiger gives proficiency

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#489]
> **Tiger.** You gain proficiency in two skills from the following list: Acrobatics, Athletics, Stealth, and Wilderness. The cat spirit hones your survival instincts.

Should probably be capacity, other 2nd level feats give capacity.

**Comment by mlenser** [comment]
Totem Spirit feat cleaned up a bit to remove the condition that it only applied when you were not at full health, the tiger option updated to give capability with one skill, and the elk option updated to not apply to creatures other than you.
