### ISSUE TITLE
Precognition maneuver should cost more stamina

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#490]
Precognition gives +1d4 to attack, skills, saving throws, and defense at 2 mana for 2 minutes (no concentration).

At 2 mana, precision gives +2 to attack, parry gives +3 defense at 2 mana.

Precognition seems like a fairly better maneuver.

**Comment by itamarcu** [comment]
Note that Precognition costs an action (well, usually an attack) while Precision and Parry are reactions.

Instead of making it cost more stamina, other solutions are:

- Make it add +1 to these rolls, instead of +1d4
- Make it require your reaction to add 1d4

**Comment by mlenser** [comment]
As I wrote on a similar "option x is better than option y" thread: some themes provide more versatility. It should be the common case, but sometimes option x is slightly better than option y. Option y is still a good option, especially for someone who doesn't want to invest in option x.

In this case, precognition is an action and is +2.5. But 2.5 is really 1-4. It's not reliable so that is a difference that could be a downside.

**Comment by mlenser** [comment]
Since it is an action and the others are reactions, these aren't comparable options. Precognition cannot be based on this comparison. If Precognition is too strong for other reasons, we can reopen.

**Comment by Marcloure** [comment]
I do think it is slightly strong, it boosts a lot of stats (from attack to defense and saves) and can't be broken by concentration. Using an action maneuver after 5th level doesn't cost that much anyway, and with the amount of stamina you can basically use this at the start of every combat.

+1d4 to defense alone is comparable to shield of faith, but while shield of faith is a bonus action, it also required concentration and can be lost (and doesn't grant all the other bonuses)

**Comment by mlenser** [comment]
No maneuver has concentration. It is not relevant to the discussion of a maneuver's balance.

> Using an action maneuver after 5th level doesn't cost that much anyway,

Using an action is a large cost. Combat isn't expected to often or even ever allow for a prep round, so if you're providing that, then many options could appear too strong.

**Comment by Marcloure** [comment]
> No maneuver has concentration. Concentration is not relevant to the discussion of a maneuver's balance.

I'm not asking to add concentration to this maneuver, but considering concentration is important. If you have a spell and a maneuver with similar effects, but the spell requires concentration and the maneuver does not, then obviously the maneuver is considerably stronger.

> allow for a prep round

You don't need a prep round, but to forgo 1 attack (~13 damage if that attack would hit?) to gain +2.5 to all attack rolls, defense, saving throws, and skills until the end of the battle. It's hard to work the math of this maneuver, since most of its benefits are adds to defense and saving throws, but through comparison it seems to be on the stronger side.

I can't give you more arguments, you can close the issue if you don't think it has merit.

**Comment by mlenser** [comment]
> considering concentration is important

Maneuvers never have concentration so concentration is not relevant to the discussion of a maneuver's balance. There are many cases where a maneuver would have concentration if it were a spell. It's simply not relevant to maneuvers though.

Additionally, I believe the fear of losing concentration is vastly overestimated.

**Comment by mlenser** [comment]
> It's not about about the action though, it's just that this is a "buff all" maneuver that has a quite low cost.

The same is true for the spell version. Bless is even stronger as it buffs 3 characters.

> You don't need a prep round, but to forgo 1 attack

That's a big cost. You lose out on burst damage which could kill an enemy. Currently the system values damage in future rounds as half as valuable as the current round. Is Precognition a good buff? Yes. Is it so powerful that it should be used most combats? I don't think so. Not anymore than Bless.

**Comment by Marcloure** [comment]
It's not about losing concentration, more that concentration is a resource you have; you have to allocate it to a spell. If you are concentrating on a buff, then you aren't on a fog or on a target control spell. If you are concentrating on bless, for instance, then you can't use detect evil and good, or incendiary cloud.

**Comment by Marcloure** [comment]
> Bless is even stronger as it buffs 3 characters. Bane debuffs 3 characters. By that same logic, PCs should be using those spells each encounter as well.

I believe they aren't because bless requires concentration, so many times you have better options in that situation to concentrate on. If bless didn't required concentration, it would be really powerful.

**Comment by mlenser** [comment]
If Bless isn't worth concentration then the benefit it gives is not OP, even when applied to 3 characters. This benefit is a little better, but how is this benefit, when applied to 1 creature, OP? The martial can't really stack multiple buffs, and the few that it can would cost actions (turns).

**Comment by Marcloure** [comment]
> This benefit is a little better, but how is this benefit, when applied to 1 creature, OP

I believe it's better than using 2 stamina in other maneuvers. If I had only 2 stamina dice, I would rather use this than parry or precision (that is why I mentioned them) or many other maneuvers. If I had 1 mana, I can't say I would rather use bless than other 1 mana spells.

**Comment by mlenser** [comment]
Precognition maneuver removed as maneuvers only use bonus actions now.
