### ISSUE TITLE
Thoughness is worse than armor

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#491]
The Berserker's toughness gives Defense equal to 12 + Con. Also, the berserker can wear scale armor, which gives 17 Defense. That means thoughness has little use until the Berserker reaches 5 Con.

That may be intention, but I think it should be as good as wearing armor.

**Comment by mlenser** [comment]
Armor has downsides like cost, weight, and potentially disadvantage on stealth. It does have an upside of Soak on that last downside. 

This feature is about the same value as RAW, but without the dexterity investment cost.

I do not expect toughness to be as good as armor. It should be a level below, else there is no reason to wear armor.
Though I think it's a bit lower than that currently. It's 14 defense which isn't so great. Armor doesn't provide 17 until level 3-5, but toughness is ~2 below armor at pretty much every tier which isn't good.

**Comment by mlenser** [comment]
Thematically, I'm not liking toughness anymore. I don't see how it increases defense. Soak maybe, but rage already provided resistance.

I'm of the mindset that we should potentially remove this. An unarmored berserker shouldn't have defense as high as armor.

**Comment by itamarcu** [comment]
Unarmored berserkers are a staple of D&D and fantasy in general. It doesn't need to be equivalent to being armored, but it needs to be viable.

If it needs to be a bit more viable, it could add a small non-defense benefit - for example, +5 movement speed if you're unarmored.

**Comment by mlenser** [comment]
Because Conan? I think such logic should be rejected the same as discussions around Rangers and Drizzt.

If the goal is viability, then that's met. It's an option that works currently and is similar power to RAW. Berserkers care less about defense as they half incoming damage.

If it must exist, then it is fine as is.
