### ISSUE TITLE
Sneak Attack typo

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#493]
> or if the target is within 5 feet of an enemy isn’t incapacitated

Should be "of an enemy **that** isn’t incapacitated". Posting here instead of Discord since you are away.

**Comment by itamarcu** [comment]
Since this is brought up, I'd like to mention again that it's not obvious that "enemy" here refers to what is usually your ally.

We discussed this briefly in Discord - I think it should be:

> or if the target is within 5 feet of **another enemy of the target** that isn’t incapacitated and you don’t have disadvantage on the attack roll.

**Comment by mlenser** [comment]
It already was, I just only changed it for the Spellthief.

**Comment by mlenser** [comment]
Sneak Attack clarified for the Infiltrator like it was for the Spellthief
