### ISSUE TITLE
Move Nail Bomb to Creation

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#495]
Currently, it is in Fire

**Comment by mlenser** [comment]
Nail bomb doesn't seem to fit creation. Nail ***Bomb*** is still a bomb. It uses fire and metal to cause damage.

**Comment by Marcloure** [comment]
I don't think it fits fire. It has fire in it, but could very well be concussion + piercing. The important part of Nail Bomb is the nails, not the fire, so I do think it fits Creation better.

Also, fire already have Fire Bomb, which is pretty similar but with concussion instead of piercing (so most the time there isn't really a reason to pick one over the other).

**Comment by Marcloure** [comment]
Also, it's not because it's a bomb that it has to be in Fire. A Salt Bomb wouldn't be in Fire.

**Comment by mlenser** [comment]
Creation doesn't fit. Creation is the opposite of destruction.

I believe fire is the best fit. Fire, in this context, isn't just about fire damage. It is about the propellant used to launch the nails. That can't be anything other than fire (with gunpowder in modern terms, some alchemical liquid in concoction terms). Concussion is a damage type, not a way to propel nails.
