### ISSUE TITLE
Change Psychic Redoubt

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#497]
Psychic Redoubt is a boring feature that requires the player to register a few hp each time it casts a spell. Although it is not weak, it does fell weak.

I would suggest to change it to something similar to RAW Monk's Wholeness of Body (value to be determined):

> You gain the ability to heal yourself. As an action, you can regain hit points equal to three times your monk level. You must finish a long rest before you can use this feature again.

Its flavor and purpose is similar to Psychic Redoubt, but instead of being a thing that you gain when you cast spell, it's something you have to meditate to gain (maybe even change it to a 1 minute meditation).

**Comment by mlenser** [comment]
Psychic Redoubt serves a different purpose than wholeness of body. Psychic Redoubt provides some minor survivability, but that is driven by encouraging the psionicist to cast spells and use maneuvers in combat.

**Comment by Marcloure** [comment]
In #132 you said you had wishes to replace Psychic Redoubt with something more impactful. I think you said something about its power being hidden by dispersion and that it requires the Psionicist to actually take damage between spells to be useful, so it's not that great.

**Comment by mlenser** [comment]
#132:

> I don't think it fits the Psionicist flavor so well and would prefer another feature in its place.

I said it's flavor doesn't fit, not that it isn't impactful. It is effective, even more so for the martial that converts psi to stam.

It could be replaced though. Any ideas?

**Comment by Marcloure** [comment]
I think that some sort of meditation or mental excersice would be cool to enforce their power source a bit more. I don't know what kind of effect it would have though.

**Comment by mlenser** [comment]
> currently it's easy to look at the Psion's features and say it's a Sorcerer

I don't think that's the case. Psychic focus is quite mentally oriented and strength of mind is about mastery of self.

**Comment by DalenWBrauner** [comment]
I like the original idea of 1 minute spent in meditation, but I think Temp HP suits the class better than closing wounds. Perhaps you gain Temp HP that scales with your level when you long rest, and can then meditate once afterwards (per long rest) to gain it again?

Adding it per short rest is simpler to run, but I wanted to spur players to say "My character meditates" to help them feel a bit in-character.

Of course, instead of something combat-related, daily meditation could confer some other bonus.

**Comment by itamarcu** [comment]
After some thinking and discussion on Discord, here's my suggestion:

> 1st level feature (possibly 2nd, doesn't matter much)
> Your training allows you to use magic with the power of your mind, unaided by gestures or incantations. You can cast spells silently and without any motion, if they cost up to half your psi limit (rounded down).

(could be limited further by restricting it to spells from the psionic power source, but I think psioicists will already use these for the most part)

This gives Psionicists their common flavor of using spells without somatic/verbal components, and it also fits with how Monks fights without using weapons. It's useful both in and out of combat, and it's limited so it's not too powerful (especially not at low tiers).

The biggest problem with this is that we don't yet have rules for spell components. #186 was put on pause and we'd need to complete it for this to really make sense.

**Comment by DalenWBrauner** [comment]
> The biggest problem with this is that we don't yet have rules for spell components. #186 was put on pause and we'd need to complete it for this to really make sense.

100%. Until this game has explicit, codified rules for how sneaky a spellcaster can be, and when gestures or spoken words are needed, I don't think we should even consider going this route. Alluding to a rabbit hole is only going to pull us into it.

That said, I do like this suggestion, for whenever that happens.

**Comment by mlenser** [comment]
> Your training allows you to use magic with the power of your mind, unaided by gestures or incantations. You can cast spells silently and without any motion, if they cost up to half your psi limit (rounded down).

That's a given, not really a replacement feature.

> The biggest problem with this is that we don't yet have rules for spell components.

General rule: spells require hand movements and verbal sounds.

**Comment by mlenser** [comment]
Psychic Redoubt reworked to give temporary health when you finish a long rest or use your Second Wind feature
