### ISSUE TITLE
Astral Avoidance - Astral Refuge augment is too strong

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#499]
https://www.kryxrpg.com/spells/astral-avoidance

I believe the augment is too strong for 2 mana. It gives the player 2 extra actions (limited in usage), for the price of merely a reaction and 2 mana. Furthermore, it lets you briefly disappear from an area, which is incredibly useful for the purposes of avoiding damage.

in RAW, it's a 6th level feature that costs an action and returns you to the same place at the end of your turn - so functionally it just allowed casting two spells on yourself for 1 action.

I think it would be better to separate them into two augments. One augment to make you appear at the start of your next turn (similar to Blink), and one augment to let you take a single action that only affects yourself.

(It's also worth comparing the extra-actions part to Time Stop.)

**Comment by mlenser** [comment]
Astral Avoidance changed to work against damage in addition to an attack. The Astral Refuge augment now only gives 1 additional action

**Comment by mlenser** [comment]
Time Stop also cost 2 and it can be used for out of combat purposes as well. Astral Refuge now costs 2 mana and gives 1 action (same as time stop), but only really works in combat (unless you have an ally hit you). Seems fair there.

I'm not sure how the returning at the start of your next turn is worth an augment so I left it as is, but perhaps there is an argument for why it is too strong.
