### ISSUE TITLE
Companion to attack bonus

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#502]
On the spreadsheet, companions are balanced as an attack spell, but companions have +6 to attack at 3 mana, while an attack spell at 9th level would have around +8 to attack. I think companions' attack bonus could be increased, unless I'm not seeing something here.

![image](https://user-images.githubusercontent.com/29084710/90336106-f4f21c80-dfaf-11ea-84e1-ecd2f38b347b.png)

**Comment by mlenser** [comment]
The sheet assumes a standard attack bonus vs a standard defense. So if you're facing higher challenge monsters then they'll have more defense, but you also have more attack as you level.

The same is true for companions. The difference is that a summon does not scale to your mana limit (though a companion does). In that case, you should probably summon a stronger companion.

The feat is still giving you far more damage and tankiness than any other feat. I'm not concerned at all about +6 attack for the third tier.

**Comment by Marcloure** [comment]
The issue also relates to Wild Shape, since the tankiness doesn't count for that spell, but maybe that is another issue.

**Comment by mlenser** [comment]
Wild Shape gives a caster:
- Potentially higher Str/Dex for checks
- Save Throw prof that you likely don't have
- Temporary health
- Maneuvers
- 2-3 attacks that deal some decent damage
- Utility from swimming/flying/burrowing, etc
- Utility from looking like an animal

Additionally, I put it through some basic DPR and it's far above what martials offer:
![image](https://user-images.githubusercontent.com/235857/90337166-fd168000-dfe0-11ea-9182-70d8d6bb53d6.png)

https://docs.google.com/spreadsheets/d/1sGvcz9vbq9yk4kRBEY6ZYGWhGO6-t7CWudznQcWPk74/edit#gid=304134422
I just looked at the Gish options to evaluate this

If anything, Wild Shape is too strong.
