### ISSUE TITLE
Covering Strike vs. Shield Bash

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#504]
Both maneuvers are pretty similar and are in the same theme: they deal the stamina die of damage, half on save, and remove the target's reaction. Shield bash has the benefit of pushing the target 5 ft. and has a variety of enhancements. It does require a shield though.

Should something be done since both are in the same theme? Or is the fact that you can use Covering Strike without a shield enough to justify its existence?

**Comment by mlenser** [comment]
Covering Strike is used on many monsters that don't have a shield.

**Comment by itamarcu** [comment]
That sounds like Covering Strike is a bit of a trap option to players who don't notice that Shield Bash is strictly better if you have a shield.

I think Covering Strike should get a small benefit and more enhancements, too, to make them more balanced against each other.

I suggest adding the following:

> On a failed save, add the stamina die to the attack’s damage roll and the target can’t take reactions until the start of its next turn. **You have advantage on opportunity attacks against the target until the start of your next turn.**

> On a successful save the target takes half as much damage.

This would reinforce the flavor of covering your ally - the target is not only unable to opportunity-attack them, but is also threatened with additional damage if they chase after them.

**Comment by Paulorpribeiro** [comment]
The benefit of covering strike that you don't need a shield. You can have a two handed weapon (that usually deals more damage) dual wield or use the dueling style. Shield bash is indeed better if you have a shield, but it restricts your play style. Covering strike can be used by all styles

**Comment by mlenser** [comment]
Covering Strike is only meant to add a dsitrction. It isn't meant to add any kind of retribution or sticky mechanic like advantage on opportunity attacks would bring.

It is less useful than Shield Bash, but Shield Bash requires a shield and Covering Strike does not. I believe that is ok.
