### ISSUE TITLE
Blight should be moved from Shadow to Death

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#505]
https://www.kryxrpg.com/spells/blight

The Death theme fits it perfectly and the Shadow theme doesn't really fit.

Blood and Water could work too, but I think Death is the core theme it belongs to.

**Comment by itamarcu** [comment]
(also, compare https://www.kryxrpg.com/spells/horrid-wilting - basically the same effect with small differences)

**Comment by Marcloure** [comment]
Water has desiccate, which is equal to blight. Horrid wilting is the AoE version of the spell.

**Comment by mlenser** [comment]
mlenser/kryx-rpg-issues/issues/505
