### ISSUE TITLE
Increase range of Create/Destroy/Purify Water

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#506]
https://www.kryxrpg.com/spells/create-destroy-or-purify-water

This is pretty minor, as it's a utility spell, but - I would like it if this spell's range was increased from 30 feet to 120 feet.

The reason is that [Fog Cloud](https://www.kryxrpg.com/spells/fog-cloud) has a range of 120 feet, and I think it makes sense for one spell and its counter to have the same range.

This is already a very situational spell, so I don't think any harm can be done from increasing its range.

**Comment by mlenser** [comment]
By RAW it is 30 feet and I think 30 feet is the right distance for such a spell. Most spells are 60 feet. Blight is a similar spell, but draining moisture and that is 60 feet.
