### ISSUE TITLE
Create a feat that allows special Familiar options

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#507]
This feat would be used by Occultists, but it would be nice if the prerequisites were simply "able to cast Find Familiar" so that other characters could use it.

More familiar options that could be included are:

Imp, Quasit, Pseudodragon, Crawling Claw, Awakened Shrub, Cranium Rat, Mephits?, Pixie?

I think they should be CR 0 or 1/8, and Tiny. Creatures with spellcasting, small creatures, and creatures with CR 1/4 or 1/2 - those could potentially be added for flavor or with a specially mentioned additional price/pact/requirement.

**Comment by mlenser** [comment]
Crawling Clawa is already in Find Familiar. Cranium rat is challenge 0 so is allowed by default

**Comment by Paulorpribeiro** [comment]
I like that solution. But first we must agree on the issue.

Now that find familiar can't be used to summon "improved familiars", which we can define as typical familiars with CR 1/8 or higher, do we need an option to summon them?
I think the answer is YES.
The options:
Augment of the spell;
Feat;
Wichcraft option (this limits to Occultists only);

**Comment by mlenser** [comment]
Improved Familiar feat added to allow improved familiar forms
