### ISSUE TITLE
Inflict wounds does not match the expected effect

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#509]
Well, at least in my view of the spell, and according to the parallel with Harry potter's sectumsepra curse, the spell is supposed to make a slash on the targets flesh, and that slash bleeds profusely.
Currently , the spell only deals bleed damage. I suggest we include some initial damage as well, making it a mix between the Bleed spell and the original Inflic Wounds spell. It just fells kinda of odd to me that you slash the target (and if you use 3 or 4 mana, you literally slash your target in half!) and it just dies at the start of its turn, instead of dying on the spot, each half falling to each side.
It should be balanced again for damage in that case, but I think it is worth it so the spell better matches the effect it is modeling (sectumsepra curse).

**Comment by mlenser** [comment]
Inflict Wounds changed to cause initial damage and cause ongoing hemorrhaging
