### ISSUE TITLE
Take ideas from the latest UA articles

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#51]
https://dnd.wizards.com/articles/unearthed-arcana

**Comment by eunomicZenith** [comment]
My party has been getting quite a bit of mileage from spell tattoos, in 5e. It'd be lovely if those were ported over.

**Comment by Marcloure** [comment]
https://media.wizards.com/2020/dnd/downloads/UA2020_SubclassesRevisited_0512.pdf

This one has some interesting features. The Wizard feature to perform rituals in the standard time one per long rest seems like it could make into the game

**Comment by mlenser** [comment]
This issue is too broad. If there are specific things from UA that should be added, please open individual issues.
