### ISSUE TITLE
Psychic Reformation and cantrips

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#510]
> **Psychic Reformation**
> As you spend 10 minutes to cast this spell, a willing creature that you can touch or see within 30 feet can replace a spell they know with another spell from a theme they know.

Should you be able to swap cantrips with this spell? I'm wondering because when you learn the Divination theme you also gain a cantrip of it, then you can cast Psychic Reformation and swap that cantrip for a Light cantrip.

**Comment by Marcloure** [comment]
The same issue (_if_ this is an issue) also happens when you level up. You can technically swap the free cantrip you gain by learning a theme for a cantrip from another theme.

Not that this is broken somehow, but if the idea is that the character will have at least a cantrip from each theme they know, this goes against the goal.

**Comment by mlenser** [comment]
Psychic Reformation changed to allow concoctions, maneuvers, or spells and it specifies that a cantrip must be replaced with another cantrip.

**Comment by mlenser** [comment]
> The same issue (if this is an issue) also happens when you level up. You can technically swap the free cantrip you gain by learning a theme for a cantrip from another theme.

I think this is ok. Unintended and people probably shouldn't do it, but it won't break anything.

**Comment by mlenser** [comment]
Actually, I'm going to prevent that:
> You cannot replace a cantrip if you would then know zero cantrips from that theme and your choices must follow the restrictions above.
