### ISSUE TITLE
Updraft causes prone even on a successful save

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#513]
After 13th level, updraft causes the target to take 1d6 fall damage even on a successful save, which means it will end up prone either way. It's pretty powerful for a cantrip to guaranteedly prone a target.

Not sure how to solve this. Ideally, I think the target wouldn't be lifted on a successful save, but that would make this cantrip an exception.

**Comment by mlenser** [comment]
Updraft changed to not deal half damage on a save, otherwise it automatically causes a creature to fall prone. The height has been increased and I’ve added restrictions to the creature’s size.
