### ISSUE TITLE
Knowledge of the Ages is much better than Wandering Mind

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#514]
Compare these two 1-mana spells:

https://www.kryxrpg.com/spells/wandering-mind
- Mind theme
- spend 10 minutes
- gain proficiency in a mental skill

https://www.kryxrpg.com/spells/knowledge-of-the-ages
- Divination theme
- spend 1 action
- gain proficiency in any skill or in any language

I know Divination is supposed to be better at obtaining knowledge, but I don't think it should be *that much* better. It's incredibly versatile, right now.

I suggest the following change, to keep them thematic and make each unique and useful:

## Wandering Mind
- spend 1 minute to cast
- gain any skill, language, or tool proficiency that a creature you can touch or see within 30 feet of you is proficient in
- augment now allows you to reduce the casting time to 1 action (for +1 mana) or to 1 bonus action (for +2 mana).

This will change Wandering Mind from a nondescript "deep contemplation" to something more psychic-like: you temporarily borrow the skill of your ally, or if you're powerful enough, the skill of an enemy.

## Knowledge of the Ages
- spend 10 minutes to cast

Keeps it useful as it gives you proficiency with *whatever you need* for an hour. Its power is versatility. It's no longer instant knowledge (which feels ridiculous to me as a 1st level spell), but it's still very good.

**Comment by mlenser** [comment]
> gain any skill, language, or tool proficiency that a creature you can touch or see within 30 feet of you is proficient in

The spell is about self discovery like a Psion does. It meditates on the self. It should not be reliant on any other creatures.

**Comment by mlenser** [comment]
- **Divination**
    - Knowledge of the Ages changed to a 10 minute casting time [#514](https://github.com/mlenser/kryx-rpg-issues/issues/514)
  - **Mind**
    - Wandering Mind changed to learn a language or skill [#514](https://github.com/mlenser/kryx-rpg-issues/issues/514)
