### ISSUE TITLE
Webshooter vs Vine Lasher - minor differences

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#515]
https://www.kryxrpg.com/spells/webshooter
* **1 minute/mana**
* augment includes:
> Webs shoot out to a solid surface within 60 feet, or the falling creature, and lower you or the creature up to 120 feet from the point of attachment toward the ground.

https://www.kryxrpg.com/spells/vine-lasher
* **5 minutes/mana**
* augment includes:
> Vines lash out to a solid surface within 60 feet, or the falling creature, **and hold you or the creature,** and lower you or the creature up to 120 feet from the point of attachment toward the ground.

The two spells should be consistent with each other (I suggest 5 minutes/mana for both, and remove "and hold..." from Vine Lasher).

**Comment by mlenser** [comment]
Webshooter and Vine Lasher synced
