### ISSUE TITLE
Hideous Laughter is odd

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#517]
[Hideous Laughter](https://www.kryxrpg.com/spells/hideous-laughter) targets two creatures, but the description sometimes refers to "the target". Furthermore, the augment only adds 1 extra creature per mana, which is less efficient than the initial mana.

I'm not sure what the intention is for the spell (hard to judge its balance), but I think one of the two should happen:

- Change to target only one creature
- Clear up wording to description refer to multiple creatures, and make the augment add +2 or even +3 targets

**Comment by mlenser** [comment]
Hideous Laughter now correctly targets one creature and the wording has been cleaned up
