### ISSUE TITLE
Add additional unique effects to weapon enchantments

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#522]
### Goals:
- These effects shouldn't slow down the game (a save after every attack is bad)
- It's nice when elements show off their unique effects
- The damage should be the main thing; the additional effect is small or rare

### The basic template:
- weapon deals +1d4 when it hits (note: near misses don't count)
- damage type varies
- sometimes there's a minor ongoing effect (fire and radiant emit light, shadow reduces light)
- (usually) on a critical hit, the creature must make a saving throw. On a failure, an additional effect is added.

### Effects:
- [Booming Weapon](https://www.kryxrpg.com/spells/booming-weapon) - Fortitude save or deafened for a minute, with additional saving throws at the end of each turn
- [Flaming Weapon](https://www.kryxrpg.com/spells/flaming-weapon) & [Fire Oil](https://www.kryxrpg.com/concoctions/fire-oil) - Reflex save or burning 1
- [Shocking Weapon](https://www.kryxrpg.com/spells/shocking-weapon) & [Shocking Oil](https://www.kryxrpg.com/concoctions/shocking-oil) - Reflex save or cannot take reactions 
- [Umbral Weapon](https://www.kryxrpg.com/spells/umbral-weapon) - Will save or frightened of you until the start of your next turn
- [Corrosive Weapon](https://www.kryxrpg.com/spells/corrosive-weapon) & [Corrosive Oil](https://www.kryxrpg.com/concoctions/corrosive-oil) - Reflex save or take additional 2d4 acid damage at the end of its next turn (scales with augment. possibly use half weapon's damage instead?)
- [Freezing Weapon](https://www.kryxrpg.com/spells/freezing-weapon) & [Freezing Oil](https://www.kryxrpg.com/concoctions/freezing-oil) - Fortitude save or slowed 1 (maybe speed reduced to half or to 0, instead)
- [Daybreak Weapon](https://www.kryxrpg.com/spells/daybreak-weapon) - Fortitude save or blinded until start of your next turn. The additional damage to undead and oozes should be removed, IMO, because undead-heavy areas are common and then this is just twice as powerful every time. perhaps you can keep extra damage to them but on a crit.
- [Sharpness Oil](https://www.kryxrpg.com/concoctions/sharpness-oil) - on a critical hit, ignore soak and target has disadvantage on its next attack (possibly with fortitude save?)
- [Force Weapon](https://www.kryxrpg.com/spells/force-weapon) - on a critical hit, ignore soak and ignore resistance to force damage
- [Chaotic Weapon](https://www.kryxrpg.com/spells/chaotic-weapon) - on a critical hit, deal an additional 1d8 damage, and you can choose which damage type your attack deals? alternative: Will saving throw or creature is staggered (or...confused?)

**Comment by Paulorpribeiro** [comment]
I really like all of those, I just have some comments on the following:

Corrosive weapon/oil: it feels kinda of odd that you would do 2d4 acid on a crit (double the +1d4 of the spell) and again 2d4 on the next turn, is this balanced?

Daybreak weapon: how about the additional damage to oozes and undead apply if the targ e t has sunlight sensitivity?

Sharpness oil: disadvantage on the next attack doesn't really match with sharpness (at least in my opinion) hoe about increasing crit range? I know nits kinda of a taboo, but since the oil can't stack with other magic enhancements (even from magic weapons) I think it is allright.

On a side note, it is usual in media that an enchanted weapon strikes so hard that the target is knocked prone or pushed. Which enchant could have this? I was thinking maybe force?

Great work, looking forward to this addition

**Comment by itamarcu** [comment]
I tried to roughly balance the crit effects to make them all have a similar damage value - in my suggestions here it's about 3, but it could be changed to be whatever can allow all of these to be satisfying.

I haven't done too much math here so I hope @mlenser could go through it and fix the discrepencies.

Corrosive - 5 damage behind a save is about 3 damage, which is similar to other stuff (e.g. Burning 1 is 3.5 for some time, but behind a save and can be ended early; Blinded is "worth" 3, so I made it last for a turn; Deafened is "worth" very little, so it can last up to a minute).

Daybreak - I don't think sunlight sensitivity cares about radiant damage so I don't see the problem here.

Sharpness - I agree, disadv on an attack is not super thematic. Ignore Soak was to be half of it, so another half could be "The creature cannot regain hit points until the start of your next turn", going with the idea that the weapon is so sharp its wounds cannot be easily closed. Another idea: reduce speed of target by 10 (kinda like slashing hamstrings or making them bleed).

Prone/Pushed would be a great effect. I think push 15 behind a save, or simply prone behind a save - would be more or less okay. I suggest adding those to a new weapon enchantment, one that works for weapons that deal bludgeoning damage. Alternatively, you could add it to Booming Weapon, making it a Fortitude save with failure being deafened and pushed.

**Comment by mlenser** [comment]
I'd rather not have a lot of focus on crits. I think these spells work better without this complexity.

Booming Weapon deafness removed
