### ISSUE TITLE
Aid wording could be improved

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#524]
https://www.kryxrpg.com/spells/aid

> As an action, you bolster your allies with toughness and resolve. Choose two creatures within 30 feet. A creature’s maximum health and health increase by 8 for the duration.

Augments: 

> The target’s health increases by an additional 10 for each additional mana expended. If this spell is augmented to target additional creatures, the health is halved.

> You can target two additional creatures for each additional mana expended. The creatures must be within 30 feet of each other when you target them.

> You can expend 1 additional mana to cast the spell as a bonus action and the targets’ maximum health and health increase by 5 for the duration. Additional augments to the health increase the health by 7 for each additional mana expended, instead of the normal increase.

It's unclear how the first augment functions in combination with the second augment (is only the extra health is halved? if all health is halved, shouldn't it say so in the second augment?).

Furthermore, the augments only mention health increase, which makes it unclear if the maximum health can be increased further.

I think it would be clearer if the spell was like this:

---

> As an action, you bolster your allies with toughness and resolve. Choose two creatures within 30 feet. Each creature's health increases by 8 for the duration. Its maximum health increases by the same amount for the duration.

Augments: 

> The creatures' health increases by an additional 10 for each additional mana expended.

> You can target two additional creatures for each additional mana expended. The creatures must be within 30 feet of each other when you target them. Additional augments to the health increase it by 5 instead of 10.

> You can expend 1 additional mana to cast the spell as a bonus action and the creatures' health increases by 5 instead of 8. Additional augments to the health increase it by 7 instead of 10.

**Comment by mlenser** [comment]
Aid wording cleaned up

**Comment by Marcloure** [comment]
The augment confusing is also true for other spells. Death Clutch for instance says: 

> You can increase the damage by 4d6 for each additional mana or psi expended. If this spell is augmented to target additional creatures, this damage is halved.

It could very well be written "Augments to the damage increase the damage by 2d6 for each additional mana or psi expended, instead of the normal increase."
