### ISSUE TITLE
Ricochet damage is too high

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#525]
[Ricochet](https://www.kryxrpg.com/maneuvers/ricochet):
> As a bonus action when you hit a creature with a ranged weapon attack, your attack can ricochet toward another target, which must be within 15 feet of the first target. Add the stamina die to the second attack’s damage roll.

A ranged weapon is 1d4-1d8, plus 4, so adding another 1d8 damage and doing all of that as a 1-stamina bonus action maneuver doesn't make sense. You can compare it to [Snap Shot](https://www.kryxrpg.com/maneuvers/snap-shot), which is similar but less limited (no need to hit first, no need to make only ranged attacks, no range limit), and costs 2 stamina.

I believe it should be one of the following:

1. The second target takes damage equal to the stamina die (no attack roll, no weapon damage added)
2. Change the cost to 2 stamina (changing damage into "Add one of the stamina dice")
3. Change it to be like Avalanche Onslaught: the second attack deals 1d8+[Ability/2] damage or half on a miss.

All of these would be pretty balanced according to the spreadsheet.

**Comment by mlenser** [comment]
Ricochet now correctly does lesser damage to the secondary target
