### ISSUE TITLE
Change illusions to Perception instead of Will save

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#526]
I have three main reasons for this request:

1. When a player asks to investigate a wall and you ask for a Will saving throw, it's very, very suspicious. 
2. Saving throws are mostly reactive. When you are investigating something, it should be a skill check. It feels weird when someone asks to investigate something, and you ask for a Will saving throw instead of a check.
3. A perceptive eye should be able to catch clues that indicates that something is an illusion. Maybe make it explicit that it's a Perception check using Intelligence if that is preferable.

If this change happens, I think gnomes should then gain advantage on Will saving throws against magic and on ability checks to detect illusions.

**Comment by mlenser** [comment]
The math doesn't work for skills vs spell DCs.

Level 1 for example: Spell DC is 8 + prof + spellcasting ability: ~13. Saves are around 10.5+0-2+0-3. Skills are around 10.5+0-2+0-3. However, skills are almost always higher as the abilities behind them are almost always higher and the chance to have proficiency is much higher. This is especially true for perception.

This would largely amount to a mathematical nerf to illusion spells without further changes. #417 has the same problem and the DCs would need to change for that to work.

**Comment by itamarcu** [comment]
I agree that it needs to stay balanced, and I don't think a change is necessary.

However, I would just use passive investigation and active investigation, if it's not an offensive illusion spell. Investigation was created for this purpose, and Perception doesn't need yet another use case. In @DalenWBrauner's scenario it would be the same thing - player asks to investigate a wall, player rolls an investigation check, nothing is suspicious.

**Comment by Marcloure** [comment]
Maybe illusions could have higher DC (instead of your spellcasting DC, use 12 + bonuses), so they are naturally harder to perceive through, but I don't know if an exceptional formula is a good idea either.

I guess there isn't much to do here then.

**Comment by DalenWBrauner** [comment]
I would agree that #417 ought to take a form that solves the problem, and might even be _the_ way to solve it.

Outside of making a saving throw for them in secret, of course. (But there aren't good rules for that.)

**Comment by mlenser** [comment]
> Maybe illusions could have higher DC

All spell saves should be the same DC.

**Comment by Marcloure** [comment]
It would be your spellcasting DC, but rather an independent DC like counterspell DC. But I agree this isn't the best solution.

**Comment by mlenser** [comment]
Closing as this could happen in #417, but not on its own.

**Comment by mlenser** [comment]
Reopening now that expertise is gone.

**Comment by mlenser** [comment]
Illusion spells that could be examined now use Perception (Intelligence) instead of a Will saving throw. That is Disguise, Disguise Potion, Illusory Dragon, Image, Minor Illusion, Mirage, Phantasmal Force, Project Image.

**Comment by mlenser** [comment]
Reopening now that expertise is gone.

**Comment by mlenser** [comment]
Illusion spells that could be examined now use Perception (Intelligence) instead of a Will saving throw. That is Disguise, Disguise Potion, Illusory Dragon, Image, Minor Illusion, Mirage, Phantasmal Force, Project Image.

**Comment by Marcloure** [comment]
Should gnomes gain advantage on this check?

**Comment by mlenser** [comment]
Interacting with the illusion in RAW is also an ability check, which Gnomes do not have any benefits to in RAW:
![image](https://user-images.githubusercontent.com/235857/93001625-96797900-f530-11ea-9da7-2a0e0855a7a5.png)
