### ISSUE TITLE
Skull Lord's spellcaster level and mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#528]
> **_Spellcasting._** The skull lord is a 19th-level spellcaster. Its spellcasting ability is Charisma (spell save DC 18, +10 to hit with spell attacks). It has 14 mana, a mana limit of 3, 

Its mana limit and mana doesn't match its spellcaster level. It is not a gish, since it doesn't have stamina.

**Comment by mlenser** [comment]
It is a half caster like any of the PC classes that can be half caster while still only using spells. Stamina dice are not required to be a half caster.

Multiattack x3 is why it is a half caster.

**Comment by mlenser** [comment]
Paladin with all spells for example has t he same mana and mana limit at 19:
![image](https://user-images.githubusercontent.com/235857/91257826-22d32000-e76b-11ea-93f1-2ab4183843aa.png)

**Comment by Marcloure** [comment]
Ah, ok. It's a bit hard to understand that is what is happening looking at the sheet, but not that it matters in the end.

**Comment by mlenser** [comment]
Which part is hard to understand? I copied RAW's format for presenting the spellcasting text. Is there something that can be improved so it is easier to understand?

**Comment by Marcloure** [comment]
It's hard to understand whether the calculation is based on a full spellcaster or on a half spellcaster. RAW uses "it's a 10th-level paladin spellcaster", so you know it has the spell slots and slots level of a 10th level paladin.

I'm not sure how to improve this here, nor if it's really needed.
