### ISSUE TITLE
Slightly alter Psychic Disentanglement

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#529]
https://www.kryxrpg.com/character/classes/psionicist#psychic-disentanglement

This is pretty minor, since it's a 20th level feature, but still - the first half of this feature, just like the 5e Mystic's Psionic Body, feels bad to me. I love the flavor of surviving death through psionic disentanglement, but the fact that it's tied to an arbitrary dice roll (55% chance) makes this a bad feature that you cannot rely on.

I suggest changing it to be a guaranteed success (you always revive 1d3 days later).

If that's too good for some reason, you can limit it in other ways:
- Limit it to activate only if you die during your 1-minute transformation
- Add "you cannot use this feature again until a month has passed"

**Comment by mlenser** [comment]
I don't think providing 100% immortality, even as a capstone, is a great idea.

**Comment by itamarcu** [comment]
I want it to be more consistent, but it doesn't have to be full immortality. Another idea: keep it a d20 roll, but you need to roll above a 1 to remain alive, and this number increases by 1 every time you die.

So functionally you'll have a 95% chance of surviving, but it's reduced by 5% every time. Statistically, you are likely to die before your 6th attempt.

**Comment by mlenser** [comment]
Psychic Disentanglement split to Psychic Transcendence and Psychic Disentanglement. Psychic Disentanglement reworked a bit to appear as a ghost on the ethereal plane.
