### ISSUE TITLE
Miscellaneous humanoids' spells and maneuvers

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#53]
Continuing issue #9 for bandits, scouts, knights, champions, spies, and other generic humanoids.

**Comment by Marcloure** [comment]
### Archer
Remove Archer's Eye trait
**Themes:** Skirmish
#### Maneuvers (limit 2)
- **1 Stamina die:** distant shot, volley
- **2 Stamina dice:** rain of arrows

### Assassin
Remove Archer's Eye trait
**Themes:** Skirmish, Trickery
#### Maneuvers (limit 3)
- **1 Stamina die:** ambush, feint, gag, precision, step of the wind
- **2 Stamina dice:** blind, staggering strike

### Bandit
**Themes:** Trickery
#### Maneuvers (limit 1)
- **1 Stamina die:** cripple, gag

### Bandit Captain
**Themes:** Trickery, Vanguard (thought about Leadership instead, but RAW it has parry)
#### Maneuvers (limit 1)
- **1 Stamina die:** bloodletting, cripple, gag, grievous wound, parry

### Berserker
**Themes:** Vanguard
#### Maneuvers (limit 1)
- **1 Stamina die:** charge, glancing blow, whirlwind

### Champion
**Themes:** Vanguard
#### Maneuvers (limit 3)
- **1 Stamina die:** charge, lunge, parry, precision, sweeping strike
- **2 Stamina dice:** riposte

### Commoner
Nothing?

### Cultist
**Themes:** Trickery
#### Maneuvers (limit 1)
- **1 Stamina die:** disorient, grievous wound

### Cultist
**Themes:** Trickery
#### Maneuvers (limit 1)
- **1 Stamina die:** disorient, grievous wound

### Gladiator
**Themes:** Protection, Vanguard
#### Maneuvers (limit 2)
- **1 Stamina die:** avert blow, goading strike, shield bash, shield trip
- **2 Stamina dice:** brace, riposte

### Guard
**Themes:** Protection
#### Maneuvers (limit 1)
- **1 Stamina die:** avert blow, covering strike

### Knight
**Themes:** Leadership, Protection, Vanguard
#### Maneuvers (limit 2)
- **1 Stamina die:** lead the attack, parry, rally, sturdy stance
- **2 Stamina dice:** commander's strike, riposte

### Martial Artist Adept
The special effects from unarmed strike are of a much higher stamina limit, so removing it would nerf the creature.
**Themes:** Skirmish
#### Maneuvers (limit 2)
- **1 Stamina die:** nimble dodge, positioning strike, step of the wind
- **2 Stamina dice:** throw

### Master Thief
**Themes:** Skirmish, Trickery
#### Maneuvers (limit 2)
- **1 Stamina die:** ambush, disorient, fan of blades, feint, gag, nimble dodge, vault
- **2 Stamina dice:** slashing blades

### Noble
**Themes:** Leadership, Vanguard
#### Maneuvers (limit 1)
- **1 Stamina die:** coordinated movement, parry

### Scout
**Themes:** Skirmish, Trickery
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, distant shot, vault

### Spy
**Themes:** Trickery
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, distract, feint

### Swashbuckler
**Themes:** Skirmish
#### Maneuvers (limit 2)
- **1 Stamina die:** bait and switch, nimble dodge, positioning strike, vault
- **2 Stamina dice:** slashing blades

### Thug
**Themes:** Vanguard
#### Maneuvers (limit 1)
- **1 Stamina die:** bonecrush, knockback

### Tribal Warrior
**Themes:** Beast
#### Maneuvers (limit 1)
- **1 Stamina die:** pounce, sprint

### Veteran
**Themes:** Leadership, Vanguard
#### Maneuvers (limit 2)
- **1 Stamina die:** charge, incite, lead the attack, parry
- **2 Stamina dice:** riposte

### Warlord
**Themes:** Leadership (all maneuvers?)
#### Maneuvers (limit 4)
- **1 Stamina die:** coordinated movement, incite, inspire, lead the attack, rally, 
- **2 Stamina dice:** commander's strike, guided strike
- **3 Stamina dice:** battle leader, clarion call, pillar of command

**Comment by Marcloure** [comment]
That does it for all purely martial miscellaneous humanoids. Blackguard, war priest, and some other half-casters are missing.

**Comment by mlenser** [comment]
Can you include any maneuvers of higher costs than currently usable? There aren't too many maneuvers of higher costs, but I'd like to allow monsters to scale up/down a little. So if they scale up they should get the higher maneuvers.

**Comment by Marcloure** [comment]
I can do that, but probably only later today.

**Comment by mlenser** [comment]
> ## Archer
> - **1 Stamina die:** distant shot, volley
> - **2 Stamina dice:** rain of arrows

Archer should have a lot more imo:

"Distant Shot", "Distract", "Impale", "Precision", "Ricochet", "Vault", "Volley", "Rain of Arrows", "Entangling Shot"

**Comment by mlenser** [comment]
> ## Assassin
> - **1 Stamina die:** ambush, feint, gag, precision, step of the wind
> - **2 Stamina dice:** blind, staggering strike

Assassin should also have a lot more imo:

"Ambush", "Bloodletting Blade", "Cripple", "Disorient", "Distract", "Fan of Blades", "Feint", "Gag", "Grievous Wound", "Nimble Dodge", "Pierce Armor", "Positioning Strike", "Precision", "Blind", "Feigned Opening", "Misdirection", "Slashing Blades", "Slice Tendon"

**Comment by mlenser** [comment]
Added maneuvers to Aarakocra, Archer, Assassin, Bandit, Bandit Captain

**Comment by Marcloure** [comment]
About the ones that already have spells, such as the blackguard and warpriest, should I keep their selection or retheme them?

**Comment by mlenser** [comment]
I do a bit of both. Keep any spells you think match their flavor, but also pick a bunch of spells from themes in the new system that match their flavor. Drop any that don't.

**Comment by mlenser** [comment]
Added maneuvers to Berserker, Champion, Commoner, Cult Fanatic, Cultist, Gladiator, Guard, Knight, Martial Arts Adept, Master Thief, Noble, Scout, Spy, Swashbuckler, Thug, Tribal Warrior, Veteran, and Warlord
