### ISSUE TITLE
Catapsi and Holy Circle should do the same thing

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#530]
Currently [Catapsi](https://www.kryxrpg.com/spells/catapsi) is 1 minute/mana for a sphere, and [Holy Circle](https://www.kryxrpg.com/spells/holy-circle) is 5 minutes/mana for a double-sized sphere. Both spheres have the same mechanical effect.

Also, I'm not sure how Catapsi (a 3e spell that hinders psychic powers) transformed into this weak one-sided anti-magic field. Maybe it's better to rename this spell to something else, like... Repel Magic, or Aura of Arcane Aversion, or something else that's unrelated to psychic magic?

(same with Reddopsi)

**Comment by Marcloure** [comment]
Catapsi could be something like "when a creature tries to cast a spell in this area, it needs to make a Will saving throw or something". It's more akin to the original.

**Comment by itamarcu** [comment]
Yup, that would be like the original (though for all magic instead of only psychic). If we want it to be really true to the original, it could even be something that limits but not completely disables these abilities inside it - an effect could be something like "On a failed save, the creature's mana limit or psi limit is halved while inside the area, and it cannot cast any spell with a limited number of uses."

**Comment by itamarcu** [comment]
[Holy Circle](https://www.kryxrpg.com/spells/holy-circle) still has a small mistake:

> As an action, holy energy radiates from you, distorting and diffusing magical energy within a sphere centered on you. Until the spell ends, the **sphere that is twice as big as normal** moves with you. 

Should just be "sphere", there.

**Comment by mlenser** [comment]
- Catapsi removed in favor of Antimagic Sphere
- Antimagic Sphere causes creatures within the sphere to often fail casting spells as well

Holy Circle remains twice as big as normal.
