### ISSUE TITLE
Antimagic Sphere might be too strong?

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#531]
[Antimagic Sphere](https://www.kryxrpg.com/spells/antimagic-sphere) is basically the 5e Globe of Invulnerability spell (was 6th level). However, there is one important difference - the original spell is immobile.

The immobility was the biggest limiting factor of the original spell - it allowed a lot more counterplay against it. Finding cover, blocking the sphere with a fog cloud, using a non-magical area of effect, or just running away - these are no longer options that help against the Antimagic Sphere, since it can move with the caster (and it's bigger and it lasts longer).

On the other hand, the augment that lets you cast it as a stationary spell is not that great. This spell only stops magic from the outside in, so it's really not useful to cast it on an enemy, and only mildly useful when cast on a far-away ally (you'd always rather include yourself in the AoE too).

I really like the spell and all of its small additional details (casting it in the same place to make it permanent, upcasting it for a true antimagic field, etc); however, it feels too strong at its base form.

I suggest swapping the two; changing this spell to a normal sphere centered on a point within range (e.g. 60 feet), with an augment to make it follow you.

**Comment by DalenWBrauner** [comment]
The spell is normally 3 mana, and you achieve the Antimagic Field augment with another 2: a 5 Mana spell in total. That would mean it would not possible to cast Antimagic Field and also augment it to follow you, as that would cost 6 Mana.

I think I'm okay with that, given the immense power that comes with immunity to all spells at 5 Mana and below.

**Comment by itamarcu** [comment]
You're talking about spending 6 mana to cast the normal effect of the spell and having it follow you - this is what is currently possible, and feels extremely overpowered to me, because it's one-sided immunity to all enemy spells. I'm happy to remove it.

Antimagic Field is different, though, and I will be fine with having its augment also allow it to follow you ("for free").  AF stops *you* from casting spells, too, as all of its effects apply to everything within it (your magic items are useless just like the enemy's). I think it's fine to have blanket anti-magic like this.

**Comment by mlenser** [comment]
The spell has several negatives:
- It requires concentration
- It doesn't stop martial damage of any kind
- It only blocks spells of 3 or less mana (or more if you augment)

It's a nice spell, but I don't see how it is overpowered.

> the augment that lets you cast it as a stationary spell is not that great

You could cast it at a choke point without endagering yourself from melee monsters.

**Comment by itamarcu** [comment]
Spells should be balanced around being used effectively - this spell is meant to be used in combat against spellcasters, and I believe that it's in that scenario that it's too good (or at least too boring).

The original spell was immobile, smaller, and weaker (6th level that stopped 5th or lower). Even in mage vs mage combat, you had to sacrifice mobility and you could still be hit by equal power spells. 

With the new spell, it feels like you'd *always* want this spell when you're part of a party (who can protect you from melee attackers), or when you're flying (e.g on a pegasus). With the fact that it can block spells of *equal* cost, it means that you counter enemy spellcasters to an even fuller extent.

I would compare it to Counterspell and Dispel Magic (not directly of course); these two can counter a *single* spell, but their success is not guaranteed and you have to use your actions and reactions to do so. They are already considered very useful in "wizard battles". If by spending just 1 extra mana the wizard can neutralize 95% of the enemy's abilities (assuming they're the same level), this tactic would be used very often; but I'd rather keep having such battles full of colorful spells, instead of being a battle of antimagic.

**Comment by itamarcu** [comment]
I'm not absolutely certain this spell is overpowered, it's just a gut feeling - so for now, I'll close this issue.

**Comment by mlenser** [comment]
> (or at least too boring).

Sounds like you're a detrator of the School of Abjuration 😛 

> The School of Abjuration emphasizes magic that blocks, banishes, or protects. Detractors of this school say that its tradition is about denial, negation rather than positive assertion. You understand, however, that ending harmful effects, protecting the weak, and banishing evil influences is anything but a philosophical void. It is a proud and respected vocation.

__________

This is like a bit of a lesser version of Antimagic Field:
![image](https://user-images.githubusercontent.com/235857/91571207-954c2780-e946-11ea-929f-c1a565122af9.png)

3 mana is purposeful so gishes can use it at high level. I wouldn't want to decrease it from there. If it's too strong, we can consider it further.
One big difference between these spells is the duration. Though 3 minutes is long enough for a battle.

I need to see how this fits in with Catapsi.

____________________

> With the new spell, it feels like you'd always want this spell when you're part of a party (who can protect you from melee attackers)

Would a party who is going up against a Lich _always_ want this spell? They could be forced to group up and if the lich has minions or alchemy of some kind, it could be quite negative to group up to avoid magic. Plus it uses concentration. It could be quite effective, but I'm not sure it is too much.

**Comment by itamarcu** [comment]
I don't think there's any problem with Antimagic Field - that spell is a blanket removal of all magic, and it's pretty awesome because it's limiting the group's magic too. Antimagic is a great tool for the GM, as well!

My problem is with the basic spell, which was based on a different 5e spell, Globe of Invulnerability:

![image](https://user-images.githubusercontent.com/6516621/91594052-ede0ec00-e969-11ea-99db-d346af434859.png)

This spell gives you protection against magic without restricting your own magic. Similar to Catapsi, yeah, though this is a power-based spell filter and not a bonus to saving throws (I think the first is much more interesting).

I think both Antimagic Field and Globe of Invulnerability are cool spells, and I think it's fine to merge them together, but I didn't like the fact that the current version in this system granted mobility (unlike GoI). There's also a slightly bigger radius and stronger antimagic (it stops even same-level instead of only lower-level).

**Comment by mlenser** [comment]
> This spell gives you protection against magic without restricting your own magic.

And we found the difference in understanding. I pictured this stopping all spells inside the sphere as well, but that is not the case. I'll look to correct that.

**Comment by mlenser** [comment]
Antimagic Sphere causes creatures within the sphere to often fail casting spells as well
