### ISSUE TITLE
Catapult description

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#532]
The new [Catapult](https://www.kryxrpg.com/spells/catapult/) spell description is missing the actual... catapulting part. As written, you choose an object near you and make an abstract ranged attack at some target.

I suggest wording the spell like this:

> As an action, choose one object weighing 1 to 5 pounds within 60 feet that isn’t being worn or carried. The object flies in a straight line towards a creature or object within 60 feet of it. Make a ranged spell attack against the target.
> ...
> The object itself takes the same amount of damage.

**Comment by Marcloure** [comment]
The pass through to hit the next creature part was removed? That is a shame, it was what made this spell unique.

**Comment by itamarcu** [comment]
It was removed because of the change to make it a ranged spell attack - https://discordapp.com/channels/701706060440010753/701706060440010756/745230702710095933

I also agree that it was a cool mechanic, but I think we can add it again on a different (new) spell - just as a Reflex save for a spell that uses a magical projectile (one that armor shouldn't help against).

**Comment by mlenser** [comment]
Hitting something behind an initial target, if it exists as a rule, should apply to all attacks. If I fling a small rock it shouldn't hit creatures behind my target unless arrows do as well.

If we want to go that direction, that could be added, but it shouldn't be a one-off spell.

**Comment by itamarcu** [comment]
I think it makes sense as Reflex saves where you have to get away from the path of something, but it doesn't make sense for many ranged attacks (when they can be blocked).

I think the "move in a line until you hit a target" can be limited to just one spells (or more) when it's a projectile that moves slowly enough to dodge and is physical enough that it only hits a single creature but is also magical enough that a shield or armor will not really work against it.

For example, I can imagine an Earth spell that creates a giant boulder that rolls in a direction, or an Ice spell that shoots a slow-moving ball of magical frost that chills the first creature it touches.

**Comment by mlenser** [comment]
Projectiles are blocked by armor, which Reflex does not allow for. If I fling an arrow with this spell it shouldn't behave differently than if I shoot an arrow with a bow. They are the same.

**Comment by mlenser** [comment]
Catapult wording cleaned up
