### ISSUE TITLE
Ritual Caster feat should be reworded

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#533]
The [rules](https://www.kryxrpg.com/rules/concoctions-maneuvers-and-spells) say:
> To cast a spell as a ritual, a spellcaster must have a feature that grants the ability to do so

For example, the [Naturalist (Druid)](https://www.kryxrpg.com/character/classes/naturalist): 
> You can cast a spell from a theme you know as a ritual if that spell has the ritual tag.

The [Ritual Caster feat](https://www.kryxrpg.com/feats/ritual-caster) does something completely different, though:
> You have learned how to cast rituals. Rituals are spells which are written in a ritual book, which you must have in hand while casting one of them.
> When you choose this feat, you acquire a ritual book holding one spell from a theme you know with a mana cost of 1 and the ritual tag.
> (+ how to scribe new spells)

It needs to be changed. Currently it doesn't actually make you cast spells as rituals.

There are two options: either this feat grants a specific few spells that can be cast as rituals (and only as rituals!), or this feat grants the ability to cast any known spell as a ritual spell (like the class feature).

If it's the first option (like 5e), the first line should be:

> You have learned how to cast some rituals. While holding a ritual book, you can cast spells written inside it as rituals.

If it's the second option, it should be:

> You can cast spells as rituals if they have the ritual tag.

**Comment by mlenser** [comment]
I'm not understanding. The wording matches RAW.

![image](https://user-images.githubusercontent.com/235857/91567300-32a65c00-e945-11ea-9249-ae057743e42d.png)
The part in black changes the number of spells learned and removes the class part, but otherwise the wording matches RAW as far as I can see.

**Comment by mlenser** [comment]
> You have learned how to cast rituals spells that are written in a ritual book, which you must have in hand while casting one of them.

This clarifies it I believe.

**Comment by mlenser** [comment]
Ritual Caster wording clarified

**Comment by itamarcu** [comment]
The issue was that it lacked "as a ritual", sorry for not being clearer.
