### ISSUE TITLE
Comparing Fuse Form with Wild Shape (again)

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#535]
So, I decided to compare these two transformations again, since I think Fuse Form has some advantages. I'll assume both wants to turn into a resources 3 creature:

### Fuse Form
- Consumes 2 mana to Fuse Form as **bonus action**
- Keeps access to spells
- Requires a feat (Eidolon)
- It consumes 3 mana to maintain the Eidolon, but:
-- The Eidolon starts at full resources, so you are not losing mana, just giving your mana to the eidolon. When you fuse form, you kinda get this mana back
- You are stunned for a turn if your Eidolon dies (it has around 60 hp)
- You are limited to the form of your Eidolon

### Wild Shape
- 3 mana to turn into a beast as an **action** (requires a feat to use as a bonus action)
- Requires a feat to access spells
- You have access to 2-6 different forms

#### Considering all:
- Wild Shape requires 2 feats to allow everything that Fuse Form has for the price of 1 feat
- Wild Shape costs 3 mana to turn into a 3 resources companion, 4 mana for a 4 resources companion, so on.
- Fuse Form costs 2 mana to fuse into a 3 resources companion and keeps at 2 mana for a 4 or 5 resources companion. It has required the mana to maintain the eidolon, but this is a fake cost: the Eidolon gains the mana you have expended to maintain it.
- Fuse Form might stun you for a round.
- Wild Shape has more utility versatility, since you can turn into different forms
- You can Wild Shape without any of those feats, but then it's also worse than Fuse Form

Fuse Form has the benefit of becoming some much more powerful forms like elementals, but that is another issue (#313)

The conclusion is that Fuse Form is more powerful than Wild Shape. It requires 1 less feat, and costs a fix 2 mana to fuse into any companion.

**Comment by itamarcu** [comment]
Should also mention that Wild Form gives you ~4 shapes to choose from while Fuse Form is limited to a single one.

**Comment by Marcloure** [comment]
That is true, I'll add that in

**Comment by mlenser** [comment]
The comparison above really feels like it misses the mark. Spells, based on their flavor, are different. [Fuse Form](https://www.kryxrpg.com/spells/fuse-form) for example is different than [Warg](https://www.kryxrpg.com/spells/warg).

Some light comparison of the basic options:

## Fuse Form
- (+) Castable as a bonus action
- (-) Requires a feat
- (+) Does not require concentration
- (+) Your physical body is vulnerable while the spell is in effect
- (-) Can only be used on your companion

## Warg
- (+) Does not require a feat
- (-) Requires concentration
- (-) Your physical body is vulnerable while the spell is in effect
- (+) Can be used on any creature, but the creature must be there. You can summon a creature, you can have a companion, or it can be a wild creature

## Wild Shape
- (+) Does not require a feat
- (+) Does not require concentration
- (+) Your physical body is not vulnerable while the spell is in effect
- (+) Can be used to transform into any creature you know. All kinds of utility is given by this. You can fly, swim, burrow, blend in to the environment, etc.


**Some rants:**
- Wild Shape doesn't _require_ any feats. There are feats available to make it a bit nicer, but Wild Shape lasts an hour. You'll be fine not having a feat for a bonus action activation and a heal. You'll be fine without a feat to cast spells. If you want them, they're there, but they are by no means required.
- Beasts can't spells. This should not be a surprise to anyone. An Eidolon is a magical creature who is the embodiment of your patron who is the source of your spells. The Eidolon can therefore cast spells. This also shouldn't be a surprise.
- There are 10 pieces to this puzzle and you try to simplify the whole thing. This isn't solved by making these abilities the same. And it isn't solved by buffing Wild Shape which is what this and all the previous threads about Wild Shape are after.
- I expect these "wild shape isn't good enough" threads to continue endlessly. It doesn't even feel worth addressing as there is always something not good enough about it compared to one of 10 things to compare it to. Wild Shape is a great utility spell that allows a full caster to deal consistent martial damage, nearly to the level of a martial (especially so at later levels ). It provides good consitent damage. You or your player doesn't like it? Then don't use it or use RAW.

**Comment by Marcloure** [comment]
I'm not asking for a buff to Wild Shape, but actually a nerf to Fuse Form:
- make it cost 1 Mana per resource of the companion, so you can't use 2 Mana to Fuse into a 5 resources companion
- make it an action, as is wild shape. I don't see reason to make one an action and the other not when both spells last the same.

> Wild Shape doesn't require any feats

It doesn't, but I'm comparing both spells in equal footing, otherwise there is no comparison to be made. The fact that I'm pointing out is that wild shape costs more (both in terms of Mana and of feats) to be as good as Fuse Form

**Comment by mlenser** [comment]
> I'm not asking for a buff to Wild Shape, but actually a nerf to Fuse Form

Then I would point you to my last point:

> All these comparisons are silly as companion + full caster is better than a full caster fused into a companion.

**Comment by mlenser** [comment]
> The fact that I'm pointing out is that wild shape costs more (both in terms of Mana and of feats) to be as good as Fuse Form

You're really distorting the comparison. They are very different spells that have quite different requirements and server quite different purposes.

**Comment by mlenser** [comment]
Closing this issue due to the Wild Shape bias. Fuse Form is a different option that has its own requirements, pros, and cons. Fuse Form is not better than not taking the Fuse Form spell and just using your companion and spells (or your companion and wild shape).

**Comment by Marcloure** [comment]
A druid Wild Shaped into a wolf with the feat to cast spells is worse than a warlock fused into a wolf. That is my point, but if that seems balanced to you, then I don't think there is much more to discuss.

**Comment by mlenser** [comment]
A Full Caster using Wild Shape can get flying, burrowing, swimming, climbing, or several other utility options. A Fuse Formed Occultist can never get that utility with an Eidolon or Fused Form.

Different spells for different purposes with different pros/cons.

**Comment by Marcloure** [comment]
I must say there is something else that I did not consider: while Fuse Form at 3 mana gives you around 60 extra health, if you happen to lose this health you can't use your eidolon or the spell again until you complete the 8-hours long ritual. Wild Shape gives you 12~18 temporary health at 3 mana, but it lasts until you drop to 0, and you can recast it if you lose the form.

I still think this should be addressed though, otherwise it can give you 130 health for the cost of 2 mana:
> make it cost 1 Mana per resource of the companion, so you can't use 2 Mana to Fuse into a 5 resources companion

**Comment by mlenser** [comment]
> make it cost 1 Mana per resource of the companion, so you can't use 2 Mana to Fuse into a 5 resources companion

Absolutely not. That would make it a horrible choice. As I wrote above:

> All these comparisons are silly as companion + full caster is better than a full caster fused into a companion.

A character who could use Fused Form already has an eidolon. Jumping into their Eidolon is a loss of overall damage. It shouldn't cost more than a few mana.

**Comment by Marcloure** [comment]
But then you can pick the feat and use the Eidolon to gain 130 health at 17th level. That is more than worth the price of a feat and 2 mana

**Comment by mlenser** [comment]
Fuse Form can be an action though. The idea of casting a spell and then jumping in your eidolon to do more damage is a bit much. It's the same mechanically as if you didn't use Fuse Form, but the duration is for a quite a while so if you want to fuse, you can do it beforehand. This makes escaping with a sliver of health into your eidolon cost a bit more.

**Comment by mlenser** [comment]
> But then you can pick the feat and use the Eidolon to gain 130 health at 17th level.

They already have that! The eidolon already has all of that HP.

**Comment by Marcloure** [comment]
Sure, but two characters with 130 hp is not the same as one with 260 health. Even less so because your character is more important than the Eidolon
