### ISSUE TITLE
Call Steed is considerably better than Call Beast

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#536]
**Call Steed** with 2 mana allows you to summon a saber-toothed tiger permanently. The saber-toothed tiger makes one attack with +6 to hit, 12 average damage. It has 52 health.

**Call Beast** with 2 mana allows you to call a resources 2 saber-toothed tiger for _2 hours, concentration_. It has no stamina unless you expend more mana. A 2 mana companion makes 2 attacks with +4 to hit, 6 average damage each. It has 33 health.

Call Steed and Find Steed at 2 mana are both much more powerful than a 2 mana companion summoned through Call Beast. Not requiring concentration would be reason enough, but the steed also appears with full stamina, has more to-hit, and more hp. Although I used the saber-toothed tiger as an example, it is true for any creature called with Call or Find Steed.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/91593053-c553f480-e95f-11ea-9baf-354e36ac49df.png)
A camel costs 50 sp, a Mastiff 25 sp, a Pony 30 sp. Call Steed is providing you that creature at the cost of mana.

The augmented versions may be more powerful. I'd have to calcualte them.

Call Beast and Companion are balanced as far as I can detect:
![image](https://user-images.githubusercontent.com/235857/91593243-1a900600-e960-11ea-8705-33b4ffe3deb6.png)

**Comment by Marcloure** [comment]
My point is that you have no reason to use Call Beast at 2 mana when you can use Call Steed, which is objectively better. Of course, you can't cast Call Beast at 1 mana, so that is fine

**Comment by mlenser** [comment]
Call Beast lets you command the creatures, Call Steed doesn't.

**Comment by mlenser** [comment]
Call Steed reworked to be based on companions

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/91594694-9723e400-e962-11ea-9c19-c795cf72fd9d.png)

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/91594753-af93fe80-e962-11ea-870d-162fc70e7dd6.png)

**Comment by Marcloure** [comment]
It should have an exception to be called as a large creature, otherwise it's useless as a steed for medium creatures until very late.

Also, there is Find Steed, which uses creatures like pegasus and griffon.

**Comment by mlenser** [comment]
Call Steed sized appropriately for the caster

**Comment by mlenser** [comment]
Find Steed adjusted as well
