### ISSUE TITLE
Defense should not get significantly worse as you level

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#538]
Currently, the chance to be hit by an equivalent challenge threat becomes much easier as you level as Defense is relatively static after ~level 5. Currently, there is a loss of ~20-25%.

The same does not occur for your chance to hit an equivalent level threat so there isn't a magic item expectation.

I need to see if I can fix this without making lower level threats meaningless when PCs are at higher levels. My current idea is to use proficiency, which results in +1 defense around level 9 and 17. With partial hits I think the overall threat of lower challenge monsters will remain similar, but I can verify a bit more.

![image](https://user-images.githubusercontent.com/235857/91652767-8ffff180-ea9a-11ea-890a-22051774134d.png)

**Comment by mlenser** [comment]
Defense now includes half proficiency bonus so it scales into high levels. Mechanically, this is like adding 1 defense at 9th level and 17th level.

**Comment by itamarcu** [comment]
Have you considered adding the +1 bonus in a more seamless way, such as by adding better levels of armor (but expensive or with a stat/level requirement)?

Also, how does this apply to monks, sacred fists, and berserkers, who have unarmored defense? and how does this apply to mage armor and similar spells?

**Comment by mlenser** [comment]
If you want scaling in 5e there are generally two options:
- ability
- proficiency (capable, proficiency, expertise)

Proficiency is generally how stuff scales in 5e. This also meets what I expected back on https://github.com/mlenser/kryx-rpg-issues/issues/4

Monk and mage armor also use half prof
