### ISSUE TITLE
Limit Monk's Defense 

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#539]
Monks can have 20 Defense at 7th level while dealing high DPR. Their AC should be limited to 17 (not considering half prof. to AC), like it's for other damage dealers.

**Comment by itamarcu** [comment]
Currently, it's like this -

Berserker: (note: it allows adding a shield)

> your Defense equals 12 + your Constitution

Sacred Fist & Priest:

> your Defense equals 10 + your Dexterity + your Wisdom

Monk:

> your Defense equals 10 + your Dexterity + your Intelligence

---

I suggest:

> your Defense equals 8 + your proficiency bonus + your Dexterity/Intelligence/Wisdom

This mirrors stuff like Maneuver save DC (which is 8 + prof + STR/DEX), and makes the unarmored AC scale from ~13 at low level to ~19 at the highest.

**Comment by mlenser** [comment]
Did it as part of #538

**Comment by mlenser** [comment]
Acolyte is the same:
![image](https://user-images.githubusercontent.com/235857/91662014-08d56c80-eae0-11ea-9771-56428492c47b.png)

**Comment by mlenser** [comment]
I can change those to max 3 though. I think 18 is fine if they fully invest in those abilities

**Comment by Marcloure** [comment]
A caster monk certainly will, a full maneuvers may prefer Constitution.
