### ISSUE TITLE
Add Earth theme to martial maneuvers

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#54]
Consider removing the similar maneuvers from Vanguard. Maybe after making slashing versions of Whirlwind and Sweeping Strike for example.

Maybe Vanguard should be split?

**Comment by marcosPlayX** [comment]
I don't understand why add these maneuvers to Earth. I feel like they are huge stretches, just pick a maneuver, limit it to bludgeoning weapons, and call it an Earth maneuver. That feels incorrect.

If a character wants to make a warrior of the Earth, can't they just pick Earth and Vanguard?

**Comment by Marcloure** [comment]
Sorry, that was me commenting. I had forgotten to switch to my personal account

**Comment by mlenser** [comment]
> I don't understand why add these maneuvers to Earth

Monsters like earth elementals should be able to pick thematic maneuvers. Vanguard had some, but now that I've fleshed out the Earth theme there will be more options available to them - more thematic options.

I plan to expand some other themes if possible. Air and Shadow maybe.

Several maneuvers were already limited to a specific damage type, which makes thematic sense. I will try to differentiate a bludgeoning maneuver vs a slashing maneuver for example.

> If a character wants to make a warrior of the Earth, can't they just pick Earth and Vanguard?

A warrior could pick Earth and Vanguard, ya. I'm not sure I understand the question.

**Comment by Marcloure** [comment]
> A warrior could pick Earth and Vanguard, ya. I'm not sure I understand the question.

Couldn't an elemental do that as well? What I mean is, if a creature should have both Earth spells and maneuvers, then it should pick Vanguard and Earth, no?

> Several maneuvers were already limited to a specific damage type

Yeah, I agree with that. I just don't think that these maneuvers feel particularly Earth. Step of the Wind and Mind Over Body sure are maneuvers that fit their themes, but just because a maneuver requires a bludgeoning weapon I don't think that makes them Earth.

Sturdy Stance is a maneuver that fits the theme, but Glancing Blow, Hammer Spin, Rolling Boulder, they feel like stretches to me.

**Comment by mlenser** [comment]
> Couldn't an elemental do that as well? What I mean is, if a creature should have both Earth spells and maneuvers, then it should pick Vanguard and Earth, no?

Maneuvers/spells can be in multiple themes. Ambush, for example, can be in Beast, Shadow, and Trickery. A character should be able to get it from any of those themes. The same is true for these Earth maneuvers.

As I said I plan to add more to other themes and potentially split Vanguard. I need to look at it all though.

> Glancing Blow, Hammer Spin, Rolling Boulder, they feel like stretches to me.

Check out tome of battle from 3.5. Most of the Earth maneuvers and earth-like maneuvers from Vanguard have the idea originate there in the Stone Dragon section.

**Comment by mlenser** [comment]
Done
