### ISSUE TITLE
Acolyte - Minor Deification (20th level feature) - save increase

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#540]
https://www.kryxrpg.com/character/classes/acolyte

> You attain a fragment of godhood. You can understand any spoken language you hear and when you speak, any creature that knows at least one language and can hear you understands what you say.
> **Choose Fortitude, Reflex, or Will saving throws to become capable with, or proficient if you are already capable.**
> Additionally, you can reroll a saving throw that you fail. If you do so, you must use the new roll. You can use this feature a number of times equal to your Wisdom or Charisma (minimum of once), and you regain all expended uses of it when you finish a long rest.

The first line says you gain divine powers, that's cool. Speaking every language is sweet. The third line lets you reroll saving throws several times a day, which is not very epic but it's a bit like legendary resistance that some gods probably have, so I guess I see why. Side note - "Wisdom or Charisma" could just say your spellcasting ability.

I don't see the need for the second line. Slightly increasing one of your three saves is really not interesting or epic for your 20th level. Besides, why not just add it to the "Resilient" feature that gives you the same at 5th and 9th levels?

I'm in favor of simply removing the second line. If the feature needs to be stronger as a result, you can either increase the 3rd part (give more uses) or add some new ability.

**Comment by mlenser** [comment]
Save increase makes it so you have to use the reroll less often. Deities have higher saves so this immitates that. It is not part of the normal Resilient because it comes from deification.
