### ISSUE TITLE
Increase Divine Word banishment to 4 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#542]
> Regardless of its health, a celestial, an elemental, a fey, or a fiend that fails its save is forced back to its plane of origin (if it isn’t there already) and can’t return to your current plane for 24 hours by any means short of a wish spell.

I think this is a very powerful effect for a 3 mana spell, and it targets multiple creatures. It could be turned into a 4 mana augment of the spell.

The rest of the spell could be increased by 10 health for each stage. (60 health to deaf, 30 to kill). Hellfire deals ~31 damage at 3 mana at a distance, so I think instakilling at 30 health around you is fine, since it doesn't deal damage above that. It would also become a better tool against minions, since 40- health creatures would be stunned on a failed save (that includes most CR 2 or less creatures).

**Comment by Marcloure** [comment]
Oh, as comparison, Dispel Evil and Good is a 3 mana spell that allows you to banish an outsider if first you hit it with a melee spell attack, and then it fails a saving throw. Divine Word banishment is an amplified version of that, so maybe it should become an augment of Dispel Evil and Good?

**Comment by itamarcu** [comment]
Note: Divine Word is a bonus action 3 mana spell that can banish any number of creatures, if they fail the save.

It's even strong compared to [Banishment](https://www.kryxrpg.com/spells/banishment), a spell which was *built* for banishing things - and still requires targeting only 1-2 creatures (for 2-3 mana), requires a full action, and requires concentrating for a full minute to make the banishment permanent.

**Comment by itamarcu** [comment]
I'm in favor of putting the banishing part of Divine Word behind an augment of 5 mana, even.

I also think it would make more sense for the spell to have a Will save, not a Fortitude save, as it's Charisma in 5e and it's generally a Will save that protects creatures from being banished.

**Comment by mlenser** [comment]
- Deafened: Fortitude
- Blinded: Fortitude
- Stunned: Fortitude
- Killed: Fortitude
- Banished: Will. Perhaps banishment doesn't fit this spell at all.

**Comment by mlenser** [comment]
Dispel Evil and Good Dismissal now only requires a saving throw instead of an attack and a saving throw.

**Comment by mlenser** [comment]
Divine Word reworked as a spell in the format of Turn the Faithless
