### ISSUE TITLE
Resolve "resistance from X from nonmagical attacks"

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#543]
As @itamarcu has pointed out several times this is just a magic item check.

Maybe the nonmagical part should be removed? Or maybe we should add soak for these cases?

**Comment by itamarcu** [comment]
I'm in favor of using options like the following, whichever is the most flavorful (or fun), whenever it fits:

- Resistance to just one or two of the physical damage types. Example: skeletons, trees
- Resistance to damage unless it's from a silver weapon (replace silver with adamantine or cold iron or wood or whatever is flavorful)
- Resistance to damage from the first source of damage every turn, or every round
- Resistance to damage while below half health; or while above half health, that's also interesting
- Resistance to damage while this creature is in its home plane
- Immunity to partial hits (especially for elusive creatures)
- Resistance to damage from ranged weapons

Some of the above could be resistance to all damage instead of just physical damage, and some could even be immunities. It all depends on flavor and balance and the tactics we'd like to include in the game.

**Comment by mlenser** [comment]
> Resistance to just one or two of the physical damage types. Example: skeletons, trees
> Resistance to damage unless it's from a silver weapon (replace silver with adamantine or cold iron or wood or whatever is flavorful)

These I like.

> Resistance to damage from the first source of damage every turn, or every round
> Resistance to damage while below half health; or while above half health, that's also interesting
> Resistance to damage while this creature is in its home plane
> Resistance to damage from ranged weapons

hmm, not sure these are cases for these

> Immunity to partial hits (especially for elusive creatures)

Not likely to happen unless there is a super strong case for it.

**Comment by itamarcu** [comment]
Could you provide a list of monsters with resistance to nonmagical weapon damage? (assuming it's easy to search the data for it)

For spells, I found the following: 
- [Oak Body](https://www.kryxrpg.com/spells/oak-body) - nonmagical BPS
- [Shadow Form](https://www.kryxrpg.com/spells/shadow-form), [Spectral Form](https://www.kryxrpg.com/spells/spectral-form) and [Watery Form](https://www.kryxrpg.com/spells/watery-form) - nonmagical damage
- [Shadow Walk](https://www.kryxrpg.com/spells/shadow-walk) - nonmagical attacks (why only attacks..?)
- [Stoneskin](https://www.kryxrpg.com/spells/stoneskin) - description says "nonmagical BPS", augment says "BPS from weapons".
- [Prismatic Wall](https://www.kryxrpg.com/spells/prismatic-wall) - red and orange layers, for nonmagical and magical ranged attacks. This is actually a special case I'd be fine with keeping!

**Comment by mlenser** [comment]
It's a very long list:
![image](https://user-images.githubusercontent.com/235857/91665925-53afae00-eaf9-11ea-9b85-981c6846b7c3.png)
![image](https://user-images.githubusercontent.com/235857/91665928-5ca07f80-eaf9-11ea-8829-30b4378b1ba6.png)
![image](https://user-images.githubusercontent.com/235857/91665931-61653380-eaf9-11ea-8847-92fbbbc189df.png)
![image](https://user-images.githubusercontent.com/235857/91665934-675b1480-eaf9-11ea-98b7-af1b5c371fa8.png)
![image](https://user-images.githubusercontent.com/235857/91665935-6a560500-eaf9-11ea-8f61-a0b8cd29ba3d.png)

**Comment by itamarcu** [comment]
A lot of people have a lot of excuses for why certain monsters are resistant - there's many threads like [this](https://www.reddit.com/r/DnD/comments/e6ouf3/how_to_describe_a_resistance_to_nonmagical_damage/) or [this](https://www.enworld.org/threads/damage-types-are-lame.583770/).

I believe the best solution might be to go through the list one by one and make decisions.

**Air Elemental Myrmidon** - It's an air elemental. How should weapons hurt air elementals? I think it should be resistance to bludgeoning and slashing, and immunity to piercing. Arrows have a hard time going through winds, and piercing in general probably can't "push" or "cut off" the elemental air. Alternatively, I think "resistance to damage from ranged attacks" could work here.

**Alhoon** - It's a mind flayer lich. I think weapon damage should affect it normally.

**Alkilith** - oh boy. It's an ooze demon. In 5e it has resistance to nonmagical B/P/S. Okay, but maybe in older editions it was more specific, and we can use it, right? Well, according to the ["monstrous manual"](http://www.mojobob.com/roleplay/monstrousmanual/t/tanatalk.html), it's got, um.... resistance to slashing and bludgeoning, but can only be hit by +2 weapons or better. not to mention it has "magic resistance 40%", whatever that is. So, uhh.... I guess we can make it simply resistant to slashing and bludgeoning weapons.

**Allip** - insane suicidal ghost. I think ghosts can be special and we can just make them immune to nonmagical bludgeoning/piercing/slashing damage and resistant/immune to some physical elements (fire, lightning, acid, necrotic?).

**Amnizu** - gruesome noble life-draining devil. I think we can go with silver for devils and cold iron for demons, like 3.5, though maybe some are special...? well, either way, "resistance to nonsilvered weapons" seems good enough here.

**Androsphinx** - they're just sphinxes. 3.5e and Pathfinder both give no special resistances to sphinxes. Not sure why 5e did. I think it can just be removed.

**Annis Hag** - 3.5e and PF gave them small damage resistance that is ignored with bludgeoning. I think the annis hag should get either resistance to slashing and piercing or no B/P/S resistance at all.

**Arcanaloth** - it's a jackal-head fiend (not devil or demon, just a "neutral fiend") and I can only find sources that give it blanket damage resistance, so.... let's go with BPS resistance regardless of magicalness. Extra soak (~5) would also work.


... this is a lot of work and I'm only 4% of the way through. 😬

**Comment by mlenser** [comment]
4%? Try 1%. There are 788 monsters.

Ya.. lots of work.

**Comment by DalenWBrauner** [comment]
We're hoping to remove all cases of resistance to _any_ nonmagical damage, right? Not just cases of resistance to damage from nonmagical _weapons_? I feel like both are equally harmful.

If a creature has resistance to nonmagical bludgeoning damage, for instance, they would take reduced damage from falling. I've also heard weird debate over whether a creature should resist "ordinary" rocks falling on their head vs "magical" rocks falling on their head, e.g. [Upheaval](https://www.kryxrpg.com/spells/upheaval).

For these reasons, as well as the original cons, I don't care for distinguishing between "magic" and "nonmagic" damage at all.

---

Judging from the amount of work that would be required, the wide menagerie of monsters that have it, the even wider range of reasons why they would have it, and the lack of consensus for each... yeah, I say just give them Soak. It might seem lazy, but at least it's practical. (And frankly, I feel like 'resistance to nonmagical weaponry' isn't quite the paragon of effort and creativity either.) Plus, soak values can always be adjusted on a per-monster basis later.

**Comment by itamarcu** [comment]
I'm okay with Soak as a default but I think we can at least cover some broad strokes first, implement a good fix to the low-hanging fruit, where we can select a group of 10+ monsters and change them all together.
- Devils should have resistance to nonsilvered BPS
- Demons and Fey should have resistance to non-cold-iron BPS
- Golems and constructs should have resistance to non-adamantium BPS.
- Elementals should be similar regarding these damage types, we should figure out exactly how. For example, I think Earth elementals could be immune to P and S, and Water elementals could be immune to B, and Fire elementals could be resistant to BPS.
- Ghosts/specters should be similar, and I think they are the one case where magical weapons make sense (as most things go right through them). It should still be about magical weapons, though, and not magical rocks or knives or thorns. It could also be a new property of weapon we decide to add, such as "runic" or something.
- Bone creatures (like skeletons) could be resistant to PS, possible even vulnerable to B (like skeletons?)
- Undead like zombies and mummies... I think they could have no resistance, or they could just have more soak, except for special cases. 
- A bunch of extraplanar creatures can easily have "resistance to BPS while in its home plane"

**Comment by DalenWBrauner** [comment]
I like that approach, and each of those suggestions.

Nitpicking Ghosts/Spectres: These are generally capable of avoiding damage because they're partially ethereal, right? 

I generally like the concept that some "magical" attacks might be able to strike them effectively while nonmagical attacks can't, but also feel like it still shouldn't fall to just a "Do you have a magic weapon?" check. And if magic _can_ hit them... does it seem strange to anyone else that Upheaval or Burning Hands can be fully effective against something only partially on this plane? What about the fire from a _mundane_ torch? I just feel like we need a smarter criteria than "sufficiently magical".

**Comment by itamarcu** [comment]
Actually for ethereal creatures I was thinking of giving them something like
> Damage resistances - acid, concussion, fire, lightning; bludgeoning, piercing, and slashing from spells and nonmagical weapons
> Damage immunities - cold, necrotic, poison

This way, magical weapons are actually *more* effective than spells (barring psychic, radiant, and force; the "less physical" damage sources).

Another option is to do what other editions did and say "every time an incorporeal creature takes damage, there's a 50% chance it doesn't take that damage".

**Comment by Marcloure** [comment]
What happens to creatures that has immunity to b/p/s damage from nonmagical attacks (spirit troll, a few constructs)? I don't believe they can become immune to all b/p/s damage.

**Comment by itamarcu** [comment]
For the Spirit Troll, its flavor is that it's a combination of a ghost and a troll, both very resistant to things. The Spirit Troll has a regeneration trait that functions unless it is dealt psychic or force damage, and it has resistance/immunity to basically everything except psychic, force, poison, and necrotic. It's basically a monster renowned for being hard to kill.

I think it's flavorful enough to keep it as it is, remaining one of the rare monsters that can only be damaged with magic weapons and with specific spells. I think the treatment should be similar to what we do with ghosts.

> Damage resistances - acid, cold, concussion, fire, lightning
> Damage immunities - bludgeoning, piercing, and slashing from spells and nonmagical weapons

**Comment by itamarcu** [comment]
Similarly, I would suggest that the spell [Stoneskin](https://www.kryxrpg.com/spells/stoneskin) be changed to just grant resistance from B/P/S regardless of magicalness of the source (and remove the augment).  That is, unless there is some really good flavor reason for Stoneskin to be particularly vulnerable to magic weapons.

**Comment by itamarcu** [comment]
We've created [this online spreadsheet](https://docs.google.com/spreadsheets/d/10aJ0RlW94B2t9tHw6VO-2oqej_X4P8fwHc9nR2BcUsk/edit#gid=0) to list monsters with resistance to nonmagical weapon damage.

This isn't final yet, but the basic idea was to add some additional weapon materials/properties (Silver, **Cold Iron**, **Obsidian**, Adamantine, **Runic**, **Hallowed**, **Desecrated**) and to use some broad replacements depending on creature categories. See the other tabs in that document for explanations.

**Comment by mlenser** [comment]
- All demons are now resistant or immune to bludgeoning, piercing, and slashing from weapons that aren’t made of cold iron instead of nonmagical weapons. If it previously did not have any resistance the health dice have been slightly reduced [#543](https://github.com/mlenser/kryx-rpg-issues/issues/543)
- Marut, Sacred Statue, and Steel Predator damage resistances are now bypassed by adamantine. Scarecrow loses its damage resistance in favor of a bit more health and defense

**Comment by mlenser** [comment]
All fey are now resistant to bludgeoning, piercing, and slashing from weapons that aren’t made of cold iron instead of nonmagical weapons. If it previously did not have any resistance the health dice have been slightly reduced

**Comment by mlenser** [comment]
Not sure what to do with the rest

**Comment by mlenser** [comment]
Earth Elemental damage resistances are now bypassed by adamantine

**Comment by mlenser** [comment]
Ice Elemental damage resistances are now bypassed by adamantine

**Comment by mlenser** [comment]
All creatures have been updated based on the spreadsheet. See the latest changelog
