### ISSUE TITLE
Fatality Maneuver

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#545]
(Intended as part of #544)

> 

> **_Fatality_**
> ? Stamina
> _Death Theme_
> 
> As a reaction, which you take when you hit a creature with a melee attack and reduce it to 0 health, you can brutally obliterate a portion of its body. Choose a (nonvital?)* part of the creature's body (a limb, part of its torso, etc). As part of your attack or with a brief follow-up, you pulverize that portion into an unrecognizable pulp.
> This part of the creature's body can only be restored by means of a _resurrection_ spell cast with 5 mana or a _wish_ spell.
>
> Augment
> You can expend ?? additional stamina to target a creature's head or vital organs.*

I realize that if you always use this maneuver to target the head, then you're completely nullifying the revivify and lower-level resurrection spells on this creature. I thought it might be a good idea to limit that, so I split it into its own augment. That way you can still have the fun effect of just hampering revivify, rather than preventing it.

*Using that line of thinking, it might also make sense to prevent characters from targeting a creature's vital organs for the same reason.

 I'm not entirely sure how much this maneuver should cost. After all, you can theoretically accomplish this same task given just a short period of time. I think this maneuver is mostly useful just for flair, or for when you're trying to guarantee a murder on the quick.

**Comment by itamarcu** [comment]
- I think this could also be called "Brutalize"
- the 'part of the creature' should probably be restored with a Major Regeneration (3 mana heal). I don't think requiring 5 mana makes sense for something as simple as this; Revivify will already get the creature back without the limb, for the short term.
- This is the kind of maneuver that would be much more impactful for a monster/NPC to have than for a player, which makes it difficult to balance. I think something like 2-3 stamina makes sense.
- Perhaps it should also include an actual benefit, to give monsters a non-gamey reason to use it. For example, the maneuver could.... give you temporary hit points, frighten enemies nearby, sicken them, taunt them, maybe just instantly kill the creature you reduced to 0 hp?

**Comment by DalenWBrauner** [comment]
> This is the kind of maneuver that would be much more impactful for a monster/NPC to have than for a player

I don't think this is _quite_ right; there's just a bit of nuance here.

Let me first say that I shouldn't have used "reduce to 0 health", but instead used something like "killed a creature" or "dealt a fatal blow". If a player character is affected by this, it should only occur after their death is already decided.

Second: This effect is almost always more punishing when applied to a PC than when applied to an NPC, that much is true. _But_, this is can still have a permanent impact on NPCs as well; that's one less Big Bad that can be revived for a dramatic reveal later, or even one less Key Ally for the players to try to bring back. In other words, this maneuver has a relatively limited effect _unless_ revival is something readily accessible- then it's nothing to scoff at for either side.

I think this counters the "actual benefit" concern- it's a Just For Fun maneuver if revival isn't in play, and if it is, then it has a strong narrative consequence (but much stronger than less-than-a-minute's time of smashing can accomplish). It just has a niche.

> the 'part of the creature' should probably be restored with a Major Regeneration (3 mana heal)

100%- unless, of course, that part is a vital organ. You can't revivify a creature whose heart's been reduced to a fine mist. (Hence locking it behind the augment.)

> Brutalize

That would be the perfect name... if we didn't already have the evocative "Fatality" from the MK series 😛

**Comment by mlenser** [comment]
Gotta say.. while it was fun to watch you guys talk about this, I don't see the purpose. It is such a niche scenario where a PC really needs to mutilate a NPC or monster's body so they can be resurrected and if the need arrives they could do so out of combat. Without some meaning (like Blood in the Water has), this maneuver would be largely worthless.
