### ISSUE TITLE
Widen spell (metamagic suggestion)

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#547]
The suggestion is a metamagic that increases a spell's area by 1 step. Something like (wording is weird):

> **Widen Spell**
> When you cast a spell that has an area, you can expend 1 metamagic, mana, or psi to increase the spell's area as if you had cast the spell using 1 additional mana or psi. You can further increase the area for each additional metamagic expended.

I think the price is good as 1, since using this metamagic is worse than augmenting a spell with 1 mana, but it allows you to go beyond your normal area limit. The last sentence can be removed too, it is not needed.

**Comment by mlenser** [comment]
Metamagic has had the Widen Spell option added
