### ISSUE TITLE
Header sublines are cutting under the Languages table

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#548]
![image](https://user-images.githubusercontent.com/29084710/91683797-f719b680-eb2b-11ea-9fda-acb24d63f1e9.png)

**Comment by Marcloure** [comment]
White mode:

![image](https://user-images.githubusercontent.com/29084710/91683833-157fb200-eb2c-11ea-8032-76122561d5dd.png)

**Comment by mlenser** [comment]
Solved
