### ISSUE TITLE
Naturalist's Rebuke the Defilers

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#549]
With Turn the Faithless updated to use Divine Word, should something be done with the Naturalist's Primal Call Rebuke the Defilers? It's a considerably narrower feature, but I'm not sure something needs to change here.

**Comment by mlenser** [comment]
This feature is a bit different from Turn the Faithless/Divine word in flavor. It doesn't have the same blind/deaf/stunned idea.

Though it could be updated to not turn/banish. It should do something else.

**Comment by RodrigoZanon** [comment]
Instead Will, Reflex I think could be a good option.

Blind&Deafen -> Prone
Stun -> Restrained
Banish -> Paralized 
Turned  above the CR -> Slow

The flavor is, vines below the ground try to take those who commit some anathema. They try to wrap these creatures. For those creatures above the CR, this vines just try to gripe around its feet, slowing it down

**Comment by mlenser** [comment]
- Rebuke the Defilers added as a spell
- Rebuke the Defilers Primal call now uses the Rebuke the Defilers spell
