### ISSUE TITLE
Move Undeath to Occult Power Source

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#550]
Undeath relates to Necromancy, which I think is about as evocative of cultists and the occult as you can get.

As well, defying death is often portrayed as defying the natural cycle of life and death, which is not just an affront to "righteous" gods, but sometimes also an affront to the unholy beings that collect souls from the departed. I don't think these powers would often come from a Divine source.*

_*(Though now that I think about it, an "Undead God" sounds very cool.)_

**Comment by mlenser** [comment]
Occultists, Spellthiefs, Shadow Suffused, Spectral Suffused, and Vampiric Suffused (the classes and subclasses that have Occult as their power source) are not necromancers.
