### ISSUE TITLE
Minor benefits of armor spells

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#551]
There are a lot of "armor" spells that give Defense equal to 12 + half proficiency + dexterity.

I noticed that Mage Armor and Inertial Armor *also* give resistance to force, while the other armor spells (Gale Cloak, Frost Armor, Prescience...) do not. There's also Prescience that can only be applied to yourself, not to allies, making it less versatile.

I think we should make the other armors also give resistance to a damage type, or a similar minor boon.

- Mage Armor - resistance to force damage
- Inertial Armor - resistance to force damage; alternatively, concussion damage
- Frost Armor - resistance to cold damage
- Gale Cloak - "always have half cover against ranged attacks" or "advantage on saving throws against effects of gas"
- Prescience - bonus/advantage to initiative, or "can't be surprised"
- Blood Armor - resistance to necrotic damage
- Bone Armor - resistance to necrotic damage?
- Forge Armor - ??? - maybe advantage on saves against effects that restrain you?
- Rock Armor - advantage on saves against being pushed, pulled, or knocked prone
- Slick Skin - advantage on brawn/acrobatics checks to avoid being grappled (perhaps restrained?)

**Comment by Paulorpribeiro** [comment]
I like the idea. May I suggest that forge armor spell makes the armor a perfect fit and does not count it's weight toward encumbramce or something similar? The forge armor spell always looked to me as a spell that magically creates an armor perfect for the user

**Comment by mlenser** [comment]
Inertial Armor no longer resists force damage. 
I'll leave Mage Armor because Force is rare and it's a bit historic.

There are already spells to provide resistance like Protection from cold. We shouldn't mix these spells too much.
