### ISSUE TITLE
Remove Glancing Blow

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#552]
https://www.kryxrpg.com/maneuvers/glancing-blow

I just experienced a weird situation where the creature had already used its bonus action in the first attack, and the second attack was a near-miss. Using glancing blow on the second attack would deal more damage than if it had hit.

I think it should be removed since we already have near miss.

**Comment by mlenser** [comment]
Glancing Blow removed as we have partial hits
