### ISSUE TITLE
Levitate as deceit

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#557]
I think hover fits deceit much more than levitate.

**Comment by mlenser** [comment]
Hover is not the same. Hover does not let you float up behind stalagmites in the underdark.

Perhaps Levitate and Fly should be split.

**Comment by Paulorpribeiro** [comment]
Hover let's you move silently, which I think fits deceit very well. Floating around to hide in the ceiling or near stalagmites? Id say doesn't fit deceit as much

**Comment by Paulorpribeiro** [comment]
Perhaps they are proficient in other themes too. I've never heard elves were particularly proficient in the teleport theme, but they got far step

**Comment by mlenser** [comment]
Levitate removed from the Deceit theme
