### ISSUE TITLE
Master of Intrigue is a bit too good

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#559]
https://www.kryxrpg.com/feats/master-of-intrigue - 2nd level feat

- You learn one language of your choice
- You become capable with the Deception, Skulduggery, or Streetwise skill. If you are already capable, you become proficient. If you are already proficient, you gain expertise with it.
- You can unerringly mimic the speech patterns and accent of a creature that you hear speak for at least 1 minute, enabling you to pass yourself off as a native speaker of a particular land, provided that you know the language.

Compared to other feats, this provides too much value at level 2. I think we should remove either the first or the second bullet point. Also, Skulduggery can be removed, as it pertains only to dextrous criminal activities, not to social ones.

**Comment by mlenser** [comment]
Master of Intrigue changed to remove the mimicry

**Comment by itamarcu** [comment]
Wait, what? But... but mimicry was the one thing that made it unique. The only reason for its existence. 😕

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/92995848-53ef7680-f507-11ea-8f15-73c7c3313d48.png)

**Comment by itamarcu** [comment]
Impostor is a high-level ability to perfectly pretend to be a specific person, while Master of Intrigue was about passing yourself as a generic member of a culture.

I think it might be okay if that ability was mentioned as a Deception/Streetwise skill usage?

**Comment by mlenser** [comment]
Then that is already covered by Impersonate from Deception:
![image](https://user-images.githubusercontent.com/235857/92996260-95355580-f50a-11ea-863c-538764138d0b.png)

**Comment by itamarcu** [comment]
Small update: I found that the [Actor](https://www.kryxrpg.com/feats/actor) feat grants this ability too (perfectly mimicking a native speaker). I think it's perfect there, so no changes need to be made 🙂

**Comment by mlenser** [comment]
Exactly, I moved it there
