### ISSUE TITLE
More incentives for players to be capable

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#560]
Copying @itamarcu's comment from https://github.com/mlenser/kryx-rpg-issues/issues/558#issuecomment-691436395

> I think the best way to do that is to put a capability requirement on a lot more skill checks, tool/item uses, and perhaps feats.
>
> I suggest...
>
>**Skills**
>- Acrobatics - Grab Edge, Soften Fall, Tumble - should require capability (currently they require proficiency, other than tumble)
>- Alchemy, Engineering, Arcana, Occult, Psionics, Primal, Divinity - should require capability for all use cases. recalling knowledge, monster lore, identifying magic items, and identifying spells
>- Athletics - maybe put a lower limit on your jump distance if you're capable? +1-+3 feet of jump distance are quite insignificant.
>- Brawn - require capability to overrun, and *maybe* to shove/trip? or with disadvantage on shoving/tripping unless you're capable?
>- Deception - require for using a Disguise Kit
>- Medicine - require for most of the things mentioned there (instead of proficiency, for some)
>- Skulduggery - require for forging documents, arming/disabling traps, and opening locks
>- Streetwise - require for recalling knowledge (like the other knowledge skills), understanding unfamiliar slang, maybe to locate a fence and to track
>- Wilderness - require for a bunch of these
>
>**Gear**
>- Climber's Kit could require capability in Athletics
>- Battering Ram, and perhaps Sledgehammer and Crowbar, could require capability in Brawn to provide the advantage to the check.
>- Navigator's Tools - wilderness? acrobatics? unsure, because seafaring doesn't fully match a skill I can see
>
>**Feats**
>- Thematic Diversification and the Initiate skills already require proficiency in power source skills
>- several of the Deceit feats could require capability in Deception, Stealth, or Skulduggery
>- same with Divination and Insight/Perception/Investigation

**Comment by mlenser** [comment]
@itamarcu tagging you as I failed to do it properly on the first post.

I'm not sure about adding capability requirements to many skills. It then prevents characters from being able to attempt many checks at all. I think that's the opposite of what we want.

I think capability fits better when it is reserved for advanced usages like grabbing an edge or softening a fall.
Thoughts?

**Comment by mlenser** [comment]
So far:

- **Deceit**
  - Capability with Deception added as a requirement to the Infiltration Expertise and Impostor feats
- **Divination**
  - Archival Knowledge feat removed as the Breadth of Knowledge feat and the Call to Mind spell cover the niche in better ways
  - Capability with Insight added as a requirement to the Ear for Deceit and Eye for Detail and Extract Aspects feats

**Comment by itamarcu** [comment]
I agree, it should be for advanced usage, and generally for cases where you'd need training to know how to do something. Picking a lock, cleaning a wound, using disguise kit and navigator's tools - you don't need to be good at it, but you need a bit of training to do it correctly at all. I might have gone overboard trying to find something for every skill, but I do feel good about that direction.

A softer way of doing it would be saying that characters without capability make the check with disadvantage. I think it's fair to allow characters in emergency situations to *try* doing advanced things, like disarming a trap or trying to identify a magic shield.

I also didn't really try to give these requirements/benefits to the more common skills - Perception, Insight, Stealth, etc - because those are already used a lot by characters, and getting capability in them is already pretty good.

**Comment by mlenser** [comment]
> Skulduggery - require for forging documents, arming/disabling traps, and opening locks

Disabling a trap and opening a lock already have harsh failure conditions so I don't think a capability check is necessary.

______________

- Acrobatics: Tumble now requires capability [#560](https://github.com/mlenser/kryx-rpg-issues/issues/560)
- Alchemy: Craft now requires capability [#560](https://github.com/mlenser/kryx-rpg-issues/issues/560)
- Arcana: Disable magical trap now requires capability [#560](https://github.com/mlenser/kryx-rpg-issues/issues/560)
- Brawn: Overrun now requires capability [#560](https://github.com/mlenser/kryx-rpg-issues/issues/560)
- Deception: Impersonate now requires capability [#560](https://github.com/mlenser/kryx-rpg-issues/issues/560)
- Engineering: Craft and Repair now requires capability [#560](https://github.com/mlenser/kryx-rpg-issues/issues/560)
- Skulduggery: Create a forgery now requires capability [#560](https://github.com/mlenser/kryx-rpg-issues/issues/560)
