### ISSUE TITLE
Add maneuvers, spells and/or feats to help skulduggery

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#561]
With the removal of expertise, characters and particularly rogues need something to help with this option. There are multiple maneuvers and feats for Stealth, so I think some could be added for this.

**Comment by mlenser** [comment]
They don't need it, but it could be an option.

Please feel free to suggest options.

**Comment by itamarcu** [comment]
### Fast Hands (6th level feat) (similar to [Vanish](https://www.kryxrpg.com/feats/vanish))
*Prerequisites: Proficient with the Skulduggery skill*

Your fingers move with practiced ease, giving you the following benefits:
* You can use a bonus action to make a Dexterity (Skulduggery) check that would otherwise take an action.
* When making a Dexterity (Skulduggery) check for an action that takes a longer time, such as creating a forgery or securing a prisoner, you can do it in half the time.
* During combat, you can pilfer or plant an object even if the target is aware of your presence, but you have disadvantage on the Dexterity (Skulduggery) check. The target notices your attempt regardless of

(theme is probably Shadow/Deceit. potentially Skirmish...?)

**Comment by itamarcu** [comment]
### Deft Maneuver (near copy of [Agile Maneuver](https://www.kryxrpg.com/maneuvers/agile-maneuver), Sneak, etc)
As a reaction, which you take when you make a Skulduggery check, you can keep a keen eye and maintain a steady grip. You have a +2 bonus on the triggering Skulduggery ability check.

You can use this maneuver before or after the ability check is made, but before any effects of the check are applied.

**Enhance**
You can expend 1 additional stamina die to instead have advantage on the Skulduggery ability check.

**Comment by mlenser** [comment]
Deft Trickery added as a Deceit maneuver to improve Skulduggery

I don't think Deft Hands is really worth a feat. A bonus action to open a lock or pick a pocket is not very useful and I generally try to avoid options that override default rules. They exist, but it shouldn't be commonplace.

**Comment by mlenser** [comment]
Deft Trickery removed as skills can inherently be boosted now
