### ISSUE TITLE
Buff Color Spray

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#562]
Compared with Sunbeam, Color Spray is a pretty bad spell (it's actually a bad spell without the comparison too, but sunbeam is just a better version of it):

![image](https://user-images.githubusercontent.com/29084710/93092166-7d2e1500-f675-11ea-9533-05087f27c52a.png)
![image](https://user-images.githubusercontent.com/29084710/93092199-87e8aa00-f675-11ea-86af-ac7c06ce25ca.png)

There is one small difference though, which I think should be rectified: Sunbeam's blindness lasts until the end of the **creature's** next turn, while color spray's one lasts until the end of **your** next turn.

**Comment by itamarcu** [comment]
How about making Color Spray's blindness last for 1 minute, with a save at the end of every turn? Just eyeballing the screenshot and what I remember, I think it'll multiply the value by about 2.5, which will make it more balanced..?

Alternatively, you could make the spell appear in a cone twice as big as normal.

**Comment by mlenser** [comment]
1 minute would be too strong. Compare it to blindness/deafness.
Aoe blindness is strong.

**Comment by Marcloure** [comment]
I think increasing the area could give it a purpose, otherwise it can just be removed from Light

**Comment by mlenser** [comment]
Color Spray now staggers creatures as well
