### ISSUE TITLE
Sleeping Gas / Incapacitating Agent

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#564]
# Sleeping Gas // 2 mana spell

*concentration, 1 minute/mana or psi*

As an action, a faintly purple cloud of smoke appears in a sphere centered on a point you choose within 60 feet. The cloud spreads around corners and lightly obscures its area. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.

When the cloud appears, each creature in it must make a Fortitude saving throw. A creature must also make this saving throw when it enters the spell’s area for the first time on a turn or starts its turn there. A creature that does not breathe is unaffected.

On a failed save, the creature becomes slowed 1 for the duration. If the creature was already slowed by this spell, the slow level increases by 1. If it reaches slowed 3, the creature falls into a magical slumber, becoming unconscious for the duration.

A slowed creature can repeat the saving throw when it starts its turn outside the spell's area, ending the effect on itself on a success.

A sleeping creature wakes up if it takes damage or someone uses an action to shake or slap it awake. Additionally, a creature can repeat the saving throw each minute or if it hears an extraordinarily loud noise such as the *thunderwave* spell, waking up on a success.

**Augment**
You can augment this spell with the following options, expending mana or psi for each option.
* You can expend 1 additional mana or psi to make the cloud invisible. It does not obscure its area.
* You can expend 1 additional mana or psi to increase the duration to 1 hour/mana or psi.

# Incapacitating Agent // 2 mana concoction

...basically the same thing, but a concoction you throw somewhere, instead of a spell.

**Comment by itamarcu** [comment]
I went through multiple iterations in my head while working on this - I tried to keep it intuitive, balanced, and flavorful, and it's possible it ended up a bit underpowered. Here are some things that could change to rebalance it while keeping it thematic:
* Make the sphere twice as big as normal
* Detach cloud duration from sleep duration; making the creature stay asleep for the duration even if you lose your concentration. Maybe only in the 1 hour augment.
* Make the cloud move 10 feet away from you every round
* Instead of 1 slow per fail and sleep at 3, make 2 slow per fail and sleep at 4+
* Make the slow reduced by 1 each turn, instead of completely removed, when leaving the cloud
* Increase range to 120 feet

**Comment by Paulorpribeiro** [comment]
It makes more sense (to me at least) to apply the poisoned condition while the creature stays in the cloud. The slowed and asleep should require a succesfull save to shake off

**Comment by mlenser** [comment]
Added a simpler and more direct augment to Sleeping Potion

I'm not sure this should be a spell

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/93228915-5572a600-f776-11ea-8a55-14deef470c99.png)

**Comment by itamarcu** [comment]
The spell I described could be a concoction too, or even just a concoction. I do feel like there's flavor value in a sphere that remains in an area and *slowly* puts people to sleep. It's very different from a sleep potion (ingested by a person), and even different from some theoretical chloroform-on-a-handkerchief concoction (which would be cool too).

**Comment by mlenser** [comment]
One of Crawford rules is that features/spells/whatever should not overlap. If there is already a feature/spell/whatever then this should be different enough or combined in.

The only difference I see between the suggestion and the version I have above is onset period. I don't think both should exist.

**Comment by itamarcu** [comment]
Alright, so I guess we can close this and keep it simplified and as an augment.
