### ISSUE TITLE
Evaluate which ability psionic monsters should use

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#565]
The Psionicist is changed to Wisdom because their ability to channel psionic energy is based on `your connection to psychic energies and mastery of your own mind`. I believe that is different from psionic monsters. Though I need to evaluate it.

**Comment by Marcloure** [comment]
Githzerai are more about mastery of your own mind. I think most of the others are really about having a more powerful mind

**Comment by mlenser** [comment]
Githzerai are already Wisdom which is a nice foundation for the change.

**Comment by mlenser** [comment]
Githyanki and Duergar Despot spellcasting ability changed to Charisma
