### ISSUE TITLE
Clarify Kinetic Bulwark

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#566]
> **Kinetic Bulwark**
> As a bonus action, an invisible kinetic bulwark forms within a sphere twice as big as normal centered on you that moves with you.
> 
> When you use this feature or as a bonus action on a later turn, each creature within 15 feet of the bulwark must succeed on a Reflex saving throw or be pushed 15 feet away from it.

This spell is a bit confusing. It creates a bulwark that fills a sphere, but the second part affects creatures within 15 feet of it. Does that mean you can push creatures 15 feet outside the sphere? Isn't it better to make it push the creatures only within the area?

**Comment by mlenser** [comment]
Removed the ability to have the Bulwark explode outward
