### ISSUE TITLE
Update Psionics skill to allow multiple abilities

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#568]
Now with the Psionicist using Wisdom, the skill should be updated as well. It will cause some conflicts with Intelligence psionic monsters in the spellcasting with abilities system though.

**Comment by mlenser** [comment]
To your point the other day: some skills should not be tied to an ability. I believe that is the case here. Some monsters use Int, some use Wis, some use Cha.

We'll need a better way to handle that, but the "default" shouldn't change here.

**Comment by Marcloure** [comment]
I see. It can work similar to the Acolyte, which allows both Charisma and Wisdom for its spellcasting

**Comment by mlenser** [comment]
The Psionicist itself is connected to Wisdom. It is all about mastery of self.

But the skill is used by the class and monsters.

**Comment by mlenser** [comment]
Psionics changed to Wisdom
