### ISSUE TITLE
Blood spell suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#570]
One of my players found this homebrew spell and wanted to suggest a spell based on it ([source](https://www.reddit.com/r/UnearthedArcana/comments/fdfb6e/blood_storm_a_supportive_spell_for_necromancer/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)).

![image](https://user-images.githubusercontent.com/29084710/94034056-f1646900-fd97-11ea-8a1a-f1aef323fa77.png)

It's an AOE spell similar to Battle Leader / Daybreak Weapon, but instead of adding 1d4 to the damage of your allies, you make the affected enemies take an extra 1d4 damage. The flavor is that their blood doesn't coagulate well, so I think we can find a more suitable name for it than "Blood Storm".

**Comment by itamarcu** [comment]
I quite like the idea of a spell that makes people a bit more vulnerable to injuries - I think it fits the flavor and the mechanics quite well. However, I tihnk it doesn't make much sense that a rain of blood would cause these effects. Coagulation is not a process that takes mere seconds (as far as I know) and a rain of blood has much more pronounced effects, such as... well, drenching everyone in blood.

Maybe it can be reflavored as "Tides of Blood" and it creates an aura of increased blood flow, making all creatures in the aura take +1d4 damage whenever they take bludgeoning/piercing/slashing.

(perhaps even remove bludgeoning, as sometimes it doesn't draw blood)

**Comment by Marcloure** [comment]
I agree that blood rain is a bad flavor for this spell

**Comment by mlenser** [comment]
Hmm, not sure about this.
- I would expect a saving throw. See Bane and spells like Flame Bane
- The Ranger and the Hexblade have extra damage to a target as a class feature. Spells shouldn't encroach upon class features.

I think this can't exist due to the second bullet. If Ranger/Occultist had different features then this could be workable. I could see a Fate version too, "Sealed Fate".

**Comment by mlenser** [comment]
Blood Bane added as a 1 mana spell

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/94985100-d346f780-0553-11eb-9dba-ff2f4cd69a99.png)

**Comment by mlenser** [comment]
Going with a different version:
Blooddrinker added as a 1 mana spell to augment your weapon

![image](https://user-images.githubusercontent.com/235857/94986695-02179a80-0561-11eb-9006-ec26a948f270.png)

One target is not as valuable as a persistent option.
