### ISSUE TITLE
Monsters saves are wrong in spellcasting-skills

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#572]
Monsters in https://spellcasting-skills.kryxrpg.com/ are adding half their proficiency to their saving throws, even to non proficient saves. The Acolyte, for instance, has +2 Fort with only 1 Con, and +4 Will with +3 Wis and +1 Cha. The Planetar has +14 Fort with 7 Con and 5 Prof. bonus (it should have 12 Fort then).

**Comment by mlenser** [comment]
That is correct. Monsters, pretty much universally, got capability with saving throws.

I need to revist that whole branch. I've taken it offline for now.

**Comment by Marcloure** [comment]
> the Planetar has +14 Fort with 7 Con and 5 Prof. bonus (it should have 12 Fort then).

That is not correct still. 

Also, why should every monster be at least capable in every save? This removes a bit of their weaknesses and flattens their stats in a way I don't think makes the game better. I believe this is another discussion though, so I'll leave it at that

**Comment by mlenser** [comment]
> I need to revist that whole branch. I've taken it offline for now.
