### ISSUE TITLE
Minor comments regarding Genie Suffused features

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#574]
https://www.kryxrpg.com/character/classes/suffused

### Elemental Resistance (2nd)
> You have resistance to damage associated with your genie type

> **Dao** You have resistance to acid damage and against any abilities or spells that use earth or rocks to deal bludgeoning damage.
> **Djinni** You have resistance to concussion and lightning damage.
> **Efreeti** You have resistance to fire damage
> **Marid** You have resistance to acid, cold, fire, or lightning damage (your choice) and against any spells or abilities that use water to deal damage that don’t deal cold damage.

My suggestions:
- Add a period after each genie type. For example, "**Dao.** You have..."
- Change Efreeti/Marid to be more balanced against each other. Currently, Marid is strictly better, and even if it's supposed to be a flavor choice I feel like players who want to play Efreeti-based Suffused will be disappointed. Some ideas:
  - Resistance to radiant damage
  - Advantage on saving throws to end the Burning condition
  - Immune to the effects of extreme heat and dehydration
- Another solution (not necessarily instead of suggestion 2) would be to remove the option of fire resistance from the Marid. The [5e Marid](https://5e.tools/bestiary/marid-mm.html) doesn't have fire resistance/immunity, and I'm not sure why the [KryxRPG version](https://www.kryxrpg.com/monsters/marid) has it.

### Genie Mobility

- Again, should add a period after each genie type. For example, "**Dao.** You have..."
- Missing period at end of first sentence ("You gain the ability to move like your genie origin")
- Typo in: "The chosen creatures gain a the flying or swimming speed"
- The Dao genie has only fly 30 and burrow 30, making it unable to give its allies part of its power. This is kinda bad. I suggest changing it to allow the Dao to give 15 ft of burrow speed to all its allies (even 10 or 5 feet would be nice to have).
- "choose a number of creatures up to 3 + your spellcasting ability" - is pretty meaningless, because you'd almost definitely have +4 or +5 to your spellcasting ability, and the difference between 7 people and 8 people is really minor. I suggest just saying "choose up to 7 other creatures".
- Would be nice to add "and can hover", at least to the two fly-only genie subtypes. Genies are known for hovering, so grappling them (reducing speed to 0) shouldn't make them drop from the sky.

**Comment by mlenser** [comment]
> Change Efreeti/Marid to be more balanced against each other.

The balance difference is reallllly minor here. choice of 1 from 4 can be better applied to campaigns, but then you're also a Marid instead of an Efreeti.

> I'm not sure why the KryxRPG version has it.

A creature composed of water does no burn so well.



This issue is super minor and I don't see a good option here.

_________________

> The Dao genie has only fly 30 and burrow 30, making it unable to give its allies part of its power.

I'll fix this.

> choose a number of creatures up to 3 + your spellcasting ability

This wording is used in many places in Suffused. It comes from the UA document:
![image](https://user-images.githubusercontent.com/235857/95162100-21066e80-07a5-11eb-8165-110c60ce53ae.png)

> Would be nice to add "and can hover", at least to the two fly-only genie subtypes. Genies are known for hovering, so grappling them (reducing speed to 0) shouldn't make them drop from the sky.

They aren't known for hovering in 5e. None of them have hover.

**Comment by mlenser** [comment]
Genie Mobility now allows the Dao to share its burrow speed
