### ISSUE TITLE
Blood Hunter mobility feature

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#575]
https://www.kryxrpg.com/character/classes/rogue
> **Blooded Brand (2nd)**
> As a bonus action, you can brand a creature that you can touch or see within 120 feet with blood magic. For 8 hours, your speed increases by 5 feet while you are within 60 feet of the branded creature.
> Once you brand a creature, you can’t use blooded brand again until you finish a short or long rest unless the target drops to 0 health before this feature ends.

This feature is really weird now that it doesn't add damage.
- If you can brand any creature, and it just gives you a speed boost, you should always brand yourself or your ally.
- Functionally, this is just like giving you +5 ft to your speed, passively.
- Is it flavorful for the blood hunters to be faster than other rogues?
- Is it flavorful for blood hunters to be faster than almost everyone else (not only rogues), considering the fact that they can also use Cunning Action to dash?
- Do blood hunters even need this extra movement for anything? (Cunning Action already grants mobility)

I suggest completely removing this feature.

**Comment by mlenser** [comment]
Blood Hunter’s Blooded Brand feature removed. It was reworked a bit with the new Blood Hunter and Supernatural Sense features and no longer makes sense and is no longer needed
