### ISSUE TITLE
Text of Channel Divinity mismatch with table

### ISSUE THREAD

**Issue by sjlevin** [mlenser/kryx-rpg-issues#576]
The text of Channel Divinity says `You learn an additional effect at 4th, 7th, and 9th level. `, but the Level 4 row in the table does not include Channel Divinity.

**Comment by mlenser** [comment]
The table is counting the amount of times it can be used, bot the additional effects, hence the "2/rest" wording. It is for this wording of the feature:
> Beginning at 7th level, you can use your Channel Divinity twice between rests, and beginning at 17th level, you can use it three times between rests.
