### ISSUE TITLE
Planar Rift should belong to the Teleportation theme

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#577]
https://www.kryxrpg.com/spells/planar-rift

This spell creates two linked portals in space, without doing any inter-planar magic.  I think this fits Teleportation better, as Teleportation has spells such as [Gate](https://www.kryxrpg.com/spells/gate).  All the other planes spells do something with other planes, demiplanes, and such.

It's also possible to keep this spell in Planes (just having it belong to both themes);  a player could flavor the planar rift as momentarily going through a different plane (as is the [original flavor of Dimension Door in D&D](https://i.stack.imgur.com/HCVhv.jpg).

**Comment by mlenser** [comment]
Planar Rift renamed Rift and moved from the Planes theme to the Teleportation theme
