### ISSUE TITLE
Allow Boosting Perception checks (spending stamina to improve a roll) 

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#578]
Several [skills](https://www.kryxrpg.com/rules/skills) (acrobatics, athletics, brawn, skulduggery, stealth) allow spending stamina dice to gain a bonus/advantage on a skill check.

 I suggest also including Perception in this list.

My reasoning:
1. It's flavorful for warriors to pay extra attention to their surroundings. They are the most "physical" characters, and they interact only with the physical world, unlike casters who have to know and understand magic.
2. In popular media, perceptive characters and "eagle-eyed" characters tend to be archers (and sometimes ninjas or noncombat characters like detectives). However, none of the existing rules or mechanics encourage martial characters to do this, or allow them to be better than casters.
3. Casters can certainly improve their senses - there are many spells that give them magical senses of various sorts, that let them see things hidden both physically and magically. It would be good to allow martial characters to do the same.
4. It balances Stealth - if characters can spend resources to sneak better, other characters should be able to do the same in the other direction.
5. I don't think this will introduce any problems. Perception may be a common roll for all characters, but this feature would require spending resources to improve it, and it's limited by you being capable/proficient in the skill - so it won't be used too often. Plus, in my personal experience, failed perception rolls can sometimes awkwardly stop the game (when the GM expected a success from at least one player but everyone failed); this change will change an awkward failure into a small resource loss, which keeps the game rolling smoothly.

**Comment by mlenser** [comment]
Boosting a skill exists on Acrobatics (Dex), Athletics (Str), Brawn (Str), Skulduggery (Dex), and Stealth (Dex).

Perception doesn't fall into that category the same way a Wilderness or Arcana check doesn't. I don't see the flavor for how stamina can increase perception.

**Comment by itamarcu** [comment]
You're right.  I have several reasons why I think this should belong in the game, but we once again run into the problem of stamina being limited by its name :(

This idea (and lots of other concepts for maneuvers) feels perfect to me, for the game, when stamina is treated as "personal energy for nonmagical actions that require extra effort".  However, due to a number of reasons, stamina isn't that - while mana is definitely just a generic magic battery that can be used for almost anything.

I guess I'll close this ticket and keep being frustrated about it without having a good solution :/
