### ISSUE TITLE
Some minor suggestions to improve livelihoods (in Backgrounds)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#579]
I decided to look over the [backgrounds](https://www.kryxrpg.com/character/background) and try to make sure all skills are represented well.

Problems I noticed and suggested solutions:
- Alchemy and Engineering are never offered directly. I think Guild Artisan could fit them, and Sage too.
- Folk Hero offers any two skills from anywhere. Since you could already get this by making a custom livelihood (explicitly mentioned above), I think this could be narrowed down a little bit. Perhaps "One Strength or Dexterity skill, and one Wisdom, Intelligence, or Charisma skill"? Perhaps make one of them Athletics or Perception (common for standard folk heroes)?
- The following should be removed, as livelihoods no longer grant features:
- - > To customize a livelihood, you can replace one feature with any other one, choose any two skills to be capable with...If you can’t find a feature that matches your desired livelihood, work with your GM to create one.
- The following should be removed, since bonds and flaws and such are not tied to background anymore:
- - > Finally, choose two personality traits, one ideal, one bond, and one flaw.
- Hermit is limited to Divinity, Medicine, and Wilderness - but I think it could allow stuff like Psionics (for hermit monks), Primal (similar to wilderness but for natural magic), and Perception (for paying attention to everything around you).
- Acolyte should allow Occult instead of Divinity (either directly, or as a "variant: Cultist" below). It mentions occult groups in its own description.
- Urchin should allow Streetwise (obviously), Skulduggery (because you should be able to be a pickpocket without being a criminal), and Brawn (because thugs).

**Comment by mlenser** [comment]
> Folk Hero offers any two skills from anywhere. Since you could already get this by making a custom livelihood 

Folk Hero is really generic so I think it's best to keep it as is.

> The following should be removed, since bonds and flaws and such are not tied to background anymore:

Traits, Ideals, Bonds, and Flaws are still connected to livelihoods. I just haven't added them due to copyright concerns.

> Acolyte should allow Occult instead of Divinity

I've removed the occult wording for Acolyte. A cultist is something different.

> and Brawn (because thugs)

That's not an urchin :)

**Comment by mlenser** [comment]
Livelihoods cleaned up
