### ISSUE TITLE
Animal Companion and Homunculus for non-casters

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#581]
[Animal Companion](https://www.kryxrpg.com/feats/animal-companion) and [Homunculus](https://www.kryxrpg.com/feats/homunculus) (also [Eidolon](https://www.kryxrpg.com/feats/eidolon) but it's limited to Suffused) all have this line:

> Subtract an amount of mana or psi equal to your mana limit or psi limit each time you take a rest. Your companion is augmented to that amount of mana or psi. 

However, spellcasting is not a requirement for this feat, so it could be taken by a character with no mana/psi.

I want to be clear about one thing - **I don't want to limit these feats to spellcasters only**.

Having an animal companion is common in lots of stories and games, and I'm sure that many people want to play a rogue/warrior/etc who doesn't have any magic but still has an animal friend.

I suggest going one of two ways:
1. Make the characters spend stamina instead of mana (triple the amount probably)
2. Make it a weaker companion that doesn't cost mana but doesn't scale. A "0 resource" companion.  I think most players would be totally fine with having a small critter friend that doesn't participate in combat. To phrase it, I suggest something like "If you spend no mana or psi, it is a 1 resource companion that cannot use spells or maneuvers and cannot use spells or maneuvers".

**Comment by mlenser** [comment]
There is no thematic way to tie stamina to a companion. Alchemy could work via some kind of intoxication potion or something, but there isn't any thematic room for stamina.

**Comment by mlenser** [comment]
Homunculus feat now works with catalysts as a homunculus is surely something that an alchemist could make

**Comment by mlenser** [comment]
If there is a thematic basis for pure martial companions, please open a new issue. I don't currently see a thematic way that could occur though.

**Comment by itamarcu** [comment]
What about
> Make it a weaker companion that doesn't cost mana but doesn't scale. A "0 resource" companion.

> "If you spend no mana or psi, it is a 1 resource companion that cannot use spells or maneuvers"

?

A small critter friend that is useless in combat feels thematic to me, and I don't think there's currently another way to do it (other than the GM just saying you have a pet dog/ferret/lizard).

**Comment by Marcloure** [comment]
I believe anyone can domesticate a dog or rat, there is no need of the spell for it. The point of the spell is to provide a stronger companion

**Comment by itamarcu** [comment]
Yeah, and this 2nd level feat is specifically about a companion that comes back even if it dies.  Since there isn't much mechanical point to having a "0 resource" pet, maybe it's better to not offer it as an actual feat, and leave it to the players and GM.

**Comment by mlenser** [comment]
I'm not sure what a "0 resource" pet is. A creature similar to a familiar?

A dog or rat can be domesticated (likely via Wilderness), but it would have minimal impact on combat. It would defend itself, or could possibly be trained to "sick 'em", but then we're talking about actions to command it and it remains quite a weak creature.
