### ISSUE TITLE
Light Dash [spell suggestion]

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#582]
> **Light Dash** (I really wanted to name this Rainbow Dash)
> 
> As an action, you teleport yourself to an unoccupied space you can see within 120 feet as you streak as light. Each creature other than you in a line that originates from where you teleported from and ends on the space you teleport to must make a Fortitude saving throw. A creature takes 1d10 radiant damage on a failed save, or half as much damage on a successful one.
> 
> You can bring along objects as long as their weight doesn’t exceed what you can carry.
> 
> Augment
> You can increase the damage by 1d10 for each additional mana or psi expended.

The flavor is that you become light and moves at the speed of light towards the destination. I wasn't sure between damage in a line or blindness, but I think blindness would be too powerful.

**Comment by itamarcu** [comment]
This sounds very cool, but I think the teleportation range or damage should be reduced.  The amount of targets you'd hit in a 120 foot line, on average, is probably 2-5 - likely more than Thunder Step's 5 foot sphere (which I guess is the comparison).

I think blinding until the end of a creature's next turn might not be too powerful. Compare [Sunbeam](https://www.kryxrpg.com/spells/sunbeam) - it's 1 mana to shoot a cone/line, where a failed save is 7 damage + blind and a success is 3.5 damage.  Considering that, I think teleporting 30 or 60 feet and blinding those in the way (for 1 turn, behind a saving throw) would be balanced.

Also, it should specify the width - probably a 5-feet-wide line?

**Comment by Marcloure** [comment]
> This sounds very cool, but I think the teleportation range or damage should be reduced. 

I agree with that. I just copy-pasted from Thunder step and forgot to change the range.

> Also, it should specify the width - probably a 5-feet-wide line?

 Yeah, 5-feet-wide line is what it should be, I also forgot to add that.

**Comment by mlenser** [comment]
I think it should be movement, not teleportation. Flash for example runs really fast, but doesn't teleport (minus the time travel stuff, but that's a different theme profile).

It could allow movement through targets.

**Comment by mlenser** [comment]
Light Speed added to the Light theme as a utility that lets you move Dash and move through creatures, searing them with radiant damage as you move

![image](https://user-images.githubusercontent.com/235857/97104907-a485f200-16b7-11eb-83a0-2ae87cf1d407.png)
