### ISSUE TITLE
Teleport spell range is bad;  let's add an action-cost variant

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#584]
The [Teleport](https://www.kryxrpg.com/spells/teleport) spell is supposed to be the classic teleport option, in the teleportation theme.  However, because it is a bonus action spell, it is mechanically limited and so the distance is really short (30 feet), just like the old Misty Step spell.

For somebody who wants to teleport a longer distance, Teleport is a really bad spell.  Augmenting it with 1 mana increases the teleportation range by merely 60 feet.  The Dimension Door augment is +1 mana to remove the limitation of sight, but it doesn't increase the range in any way, so it's still merely 30 feet (unlike the 5e spell, which was an action, 500 feet, and could bring a friend, for the equivalent of 2.5 mana).

Compare [Thunder Step](https://www.kryxrpg.com/spells/thunder-step) - it's an action spell that lets you teleport 120 feet *and deal damage*.  Also makes noise and the damage isn't optional, which are small flavorful drawbacks.

I think the core issue here is that Teleport is balanced around being a bonus action spell, but often a player would want to go a long distance and wouldn't mind spending an action. As a spell belonging to the Teleportation theme, this should be the most efficient way, other than [Distant Teleport](https://www.kryxrpg.com/spells/distant-teleport) (which serves a very different purpose).

Also, not exactly relevant, but the "Teleporting Strike" augment (which lets you spend 1 mana to make a weapon attack before/after teleporting) doesn't make much sense on a Bonus Action spell, that already allows you to do that. In my opinion, this can just be removed, as gish classes can already attack before/after casting a spell.

My suggestion is that we make this into a "double"/"variant" spell, like [Heal and Healing Word](https://www.kryxrpg.com/spells/heal), where the top option is an action and the bottom option is a bonus action.

(names could be changed, of course, if anyone has a better idea.)

----

## Teleport
- Action, teleport 120 feet.
- **Dimension Door** - Increase range to 300 feet and remove sight requirement.
- **Joint Teleport** (unchanged) - Bring 2 allies with you.

## Quick Teleport
- Bonus action, teleport 30 feet. (unchanged)
- **Spatial Leap** - Increase range by 60 feet.
- **There and Back Again** (unchanged) - return at the end of your turn.
- **Continuous Teleport (2)** (unchanged) - change to duration spell, 1 minute.

**Comment by mlenser** [comment]
Teleport is now an action with a much longer distance and a refined Dimension Door augment. The bonus action teleport is now a variant that teleports for a much shorter distance.
