### ISSUE TITLE
Anchored Navigation needs a rework

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#585]
Currently, [Anchored Navigation](https://www.kryxrpg.com/spells/anchored-navigation) is very bad.

> As an action, you create an invisible, intangible teleportation anchor in a 5-foot cube you can see within 120 feet of you. For the duration, whenever you teleport, you can instead teleport to the anchor, even if you can’t see it, but it must be within range of the teleportation ability.

Reasons:
- The [Word of Recall](https://www.kryxrpg.com/spells/word-of-recall) spell (2 mana) is much better, as it lets you retreat no matter how far you are from the anchor, and has a built-in augment to bring extra creatures with you (which you will very likely want to do).
- Anchored Navigation doesn't disappear when you teleport to it, but this is a really minor benefit, that I can't imagine somebody really taking advantage of.
- By restricting your range from the anchor, the spell becomes almost useless.  Most limited-range teleportation effects are 15, 30, or 60 feet, and if you're planning to teleport to a spot within that short range the chance that you'd be unable to see your target but prepared enough to anchor it beforehand is extremely minor.  Particularly in combat, where using this as an action would feel bad.
- Longer-range teleportation spells, such as Distant Teleport and Teleportation Circle, are not helped by this anchor.

My suggestion, to make this spell fun and viable, is to make one or several of the following changes (depending on how you want the spell to end up used):
- Remove the range limitation (explicitly say that the anchor is always considered to be within teleportation range)
- Turn this into a cantrip, possibly with a limit on the ongoing anchors you can have
- Turn this to a bonus action spell
- Allow teleportation circle to teleport into this anchor as if it were a circle
- Allow you to teleport between anchors as an action (when you set up multiple anchors), up to a certain range
- Add some additional benefits to having the anchor, [much like the 3.5e psionic power](http://www.d20srd.org/srd/psionic/powers/anchoredNavigation.htm).  The benefits mentioned there are "you always know the way back to the anchor, and you can speak telepathically with a creature near it".

If I had to pick a specific option, I'd go with a bonus action cantrip that allows adding 1 mana to remove the range limitation and allow teleportation circle to use it.

**Comment by mlenser** [comment]
Why not just remove it since we have Word of Recall?

**Comment by itamarcu** [comment]
I'm okay with removing it.

My suggestions were options that would keep the spell but alter it to be something unique that isn't currently possible - e.g. make it a shorter range/duration version that can be used multiple times, or give you extra sensory info.

**Comment by mlenser** [comment]
> Remove the range limitation (explicitly say that the anchor is always considered to be within teleportation range)

This would basically be the same usage as Word of Recall so no need to double up

**Comment by mlenser** [comment]
Anchored Navigation removed as its niche is covered by Word of Recall
