### ISSUE TITLE
Lightning Lure should pull 10 feet, not 15

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#586]
Compare [Thorn Whip](https://www.kryxrpg.com/spells/thorn-whip) with [Lightning Lure](https://www.kryxrpg.com/spells/lightning-lure) - they're nearly identical, except Lightning Lure pulls 15 feet (or 4.5 meters) instead of 10 feet.

Other cantrips, that push, push 10 feet - e.g. [Hydraulic Push](https://www.kryxrpg.com/spells/hydraulic-push).

Looking at the balance sheet, pulling 10 feet instead of 15 will put it in line with the other cantrips, and more balanced at early levels.  It will be worse (and below par) at late tiers, but the other cantrips are the same, so it's not so bad.

**Comment by mlenser** [comment]
There are several cantrips that are in this similar area:
- Frostbite reduces speed by 10 feet
- Hydraulic Push pushes by 10 feet
- Lightning Lure pulls 15 feet
- Mold Earth  pushes by 10 feet
- Thorn Bola reduces speed by 10 feet
- Thorn Whip pulls 10 feet

The numbers look good:
![image](https://user-images.githubusercontent.com/235857/97087897-a86d3200-162d-11eb-9a89-61822de737ac.png)

Lightning Lure with 10 feet would be below the others:
![image](https://user-images.githubusercontent.com/235857/97087913-b9b63e80-162d-11eb-841e-22f0a251c5b4.png)
