### ISSUE TITLE
Entangling Shot - could be improved

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#587]
Currently, [Entangling Shot](https://www.kryxrpg.com/maneuvers/entangling-shot) costs 2 stamina to add 1d8 damage and halves the speed of an enemy, until that enemy makes a grapple-break action or cuts the rope.

Some problems:
- The rope is very easy to destroy - it has Defense 10 and Health 2, making it basically guaranteed that a creature would destroy it with a single attack, especially with half-miss dealing half damage.
- Several other maneuvers (e.g. [Cripple](https://www.kryxrpg.com/maneuvers/cripple)) do something very similar but feel cleaner: they cost less stamina and cause Slowed 1 (which is -10 to speed instead of halving; but also reduce AC and Reflex).  their duration - 1 minute or until target saves at end of turn - is arguably better, because the DC scales with your level and it's less of a guaranteed escape during the enemy's turn.  Furthermore, the enemy can escape the rope at the start of its turn to ignore the movement reduction, but cannot do the same when crippled/hamstrung/etc.
- The augment increases the damage, but doesn't actually make the entangling part any better or more durable.

I think that, thematically, a warrior with higher stamina should be able to use it to attack and accurately shoot a heavier and stronger rope (or bola or whatever).  Therefore, an Enhancement that improves the rope itself makes sense to me.

I suggest:
- Replace the rope defense and health (10 and 2) with a bigger static number, similar to the Coccoon spell (10 and 30), to encourage enemies to spend an action to escape the rope instead of just one attack.
- Add a 1 stamina enhancement that reduces the target's speed to zero, and a 2 stamina enhancement that restrains the target.

**Comment by mlenser** [comment]
> The rope is very easy to destroy - it has Defense 10 and Health 2, making it basically guaranteed that a creature would destroy it with a single attack, especially with half-miss dealing half damage.
> Furthermore, the enemy can escape the rope at the start of its turn to ignore the movement reduction, but cannot do the same when crippled/hamstrung/etc.

That costs an action or 1 attack. That's quite fair for both parties.

> their duration - 1 minute or until target saves at end of turn - is arguably better

Statistically, saving at the end of every turn is going to last 1.54 turns with Fortitude.

> because the DC scales with your level

The DC of Entangling Shot scales

> Replace the rope defense and health (10 and 2) with a bigger static number, similar to the Coccoon spell (10 and 30)

Coccoon is a spell, which is 3x as powerful as a maneuver. Though it likely has too much health - I'll drop it to 15. Bola is 5 Health - I'll follow that.


> a 2 stamina enhancement that restrains the target.

I don't see a rope restraining, thematically.

**Comment by mlenser** [comment]
Entangling Shot reworked to automatically apply on a hit and to reduce the creature’s speed to 0
