### ISSUE TITLE
Thri-Kreen extra arms should not allow certain things

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#589]
[Thri-Kreen](https://www.kryxrpg.com/character/species/thri-kreen):
> **Extra Arms**. You have four arms, which can carry items normally and allow you to interact with one extra object for free on your turn. If you make an attack with a two-handed or loading weapon, you cannot benefit from a shield until the start of your next turn.

This looks like it's intended to be a small feature, that's used more for flavor than for any big mechanical benefit.  For example, allowing a warrior to switch quickly between a two-handed weapon and sword-and-board (or a bow) is a neat benefit, and so is the ability to grapple without sacrificing some damage.

However, this allows you to benefit from a shield while dual-wielding, which is very strong (+2 AC).  It also allows using a shield during your turn before you attack (e.g. to avoid opportunity attacks).

Also, I think it allows you to hold a reach weapon while also holding a different set of weapons (e.g. a glaive and two shortswords).  While this is very cool, it might be too strong, as it functionally gives a dual-wielding character extra reach for opportunity attacks.

I think it should say that you cannot benefit from a shield if you make an off-hand attack.  Maybe even simplify it to:
> If you hold weapons with two hands or more, you cannot benefit from a shield until the start of your next turn.

**Comment by mlenser** [comment]
Thri-kreen extra arms simplified to not benefit from a shield if you are using two handed weapons or multiple weapons
