### ISSUE TITLE
Some monster Defense values don't include half proficiency

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#590]
I'm not 100% sure, but I believe that some monsters - that have no worn armor - use 10+Dex for their armor, instead of 9+Halfprof+Dex.

For example, look at [Hydroloth](https://www.kryxrpg.com/monsters/hydroloth) - it's CR 9, so its proficiency modifier should be +4, which means half prof is +2.  It has Dex +5, and no other armor, so its AC calculation should be 9 + 2 + 5 = 16, but the shown result is 15.

Similarly, [Illusionist](https://www.kryxrpg.com/monsters/illusionist), base [Necromancer](https://www.kryxrpg.com/monsters/necromancer), and probably several others.

Compare this to [Fire Giant](https://www.kryxrpg.com/monsters/fire-giant), which has Defense 19, which fits 17 (plate) + 2 (half prof).

**Comment by mlenser** [comment]
It's not quite a bug. Monsters are assumed to already have their pb in their defense. Increasing their armor would have made it harder for PCs to hit which would throw off the math.

Though looking at the math now, it does get easier to hit enemies as the levels progress so maybe this could be added.
![image](https://user-images.githubusercontent.com/235857/97079328-4394e600-15f3-11eb-800d-8402931a3b58.png)

**Comment by mlenser** [comment]
Ok, I did the math
![image](https://user-images.githubusercontent.com/235857/97100772-68db3000-1697-11eb-83a5-91c5190a9f1e.png)

So half prof gives us a bit better numbers - I'll make it so all monsters add half prof to their defense (only impacts monsters below challenge 1 and above challenge 9)

**Comment by mlenser** [comment]
Monster defense is now 9 + half proficiency bonus as elsewhere in the system. This is now the base defense formula for the whole system.
