### ISSUE TITLE
Companions with Pack Tactics attack bonus

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#591]
Companions with pack tactics currently have the same attack bonus than other companions. They used to have 1 fewer attack bonus, and that is how it's calculated on the spreadsheet.

Also, I think tanky companions (bear, boar, etc) could also have 1 fewer attack bonus for 1 additional Constitution. Currently, the blood hawk has 52 hp and 14 AC while the bear has 60 hp and 13 AC, so the bear isn't actually a more tank companion than the hawk.

**Comment by mlenser** [comment]
The Bear does have 1 Constitution more than the Blood Hawk. Companions overall need more differences, but it can't really be addressed at such a micro level. There needs to be a full structural analysis. If you want to do so, go for it!

**Comment by mlenser** [comment]
Companions with Pack Tactics now correctly reduce their main attack ability by 1

**Comment by Marcloure** [comment]
> There needs to be a full structural analysis. If you want to do so, go for it!

I do have the desire to do this. I feel like companions should be more role-focused (DPS, Moblity, tanky) instead of how flat they are right now. I'm not sure how to approach this though, so I haven't suggested anything.
