### ISSUE TITLE
Acolyte power source/themes should be more based on their deity

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#593]
# Problem:
The question I'm asking myself is "What themes are core to nearly every Acolyte?"

In practice I can find none other than Holy/Unholy.

- **Charm**: Only some deities would enchant the emotions and intentions of others. <25%
- **Courage**: Only some deities would encourage and strengthen those around them. <25%
- **Death**: Only some deities would cause murder, death, disease, or focus on the natural cycle of life. <25%
- **Fear**: Only some deities would elicit fear. <25%
- **Life**: Only some deities would be life givers. <25%
- **Light**: Only some deities would exude radiant light. <25%
- **Undeath**: Only some deities would bring creatures back from the dead. <25%

This is in stark contrast to other power sources:
- **Arcane**: every Mage could realistically study every theme there. There could be schools that teach general themes and some that focus
- **Occult**: those that are involved in the occult would feasibly use a vast majority of these options. Some differences character to character, but they all follow a similar vibe
- **Primal**: This is the most diverse power source with elements (Acid, Air, Earth, Fire, Ice, Sand, Storm, Water) and nature (Beast, Plants).
- **Psionic**: This is a well established group of themes that most people with psionic powers would be able to manifest

Divine is too big of a power source. Every deity, like every Suffused Origin, is unique. Every deity would offer a small subset of themes.

______________

# Solutions

One option: each deity gives Holy/Unholy + themes from the deity's portfolio (Knowledge, Life, Light for Apollo for example) + 1 theme of their choice from the Divine power source.

Still need to explore how to execute this well.

**Comment by mlenser** [comment]
Charm and Fear themes removed from the Divine power source as they would only be available to some deities.

**Comment by Marcloure** [comment]
I don't know, I feel like Fear can fit any deity. It also fits both celestials and fiends, and even good deities can be terrifying (think of Gandalf speaking to Bilbo)

**Comment by DalenWBrauner** [comment]
> I don't know, I feel like Fear can fit any deity. 
Dieties are nearly always awe-inspiring, but I'm not quite sure that's the same thing as terrifying. More importantly, while the dieties themselves may invoke awe, that doesn't necessarily mean that it's a fitting a power for them to pass on.

That being said, perhaps another approach to this problem would be to think about what powers an Acolyte would be able to access just from being linked to a diety at all, regardless of who. In that case, themes like Fear, Charm and Courage might make much more sense- they may not fit the style of every diety, but are fitting, thematic extensions of "being someone who can invoke the power of a god."

It becomes more of a question of "What kind of Acolyte are you?" and "_How_ do you serve your god?" And then whether or not your diety would approve of/allow your methods is up to them.

**Comment by Marcloure** [comment]
> More importantly, while the dieties themselves may invoke awe, that doesn't necessarily mean that it's a fitting a power for them to pass on.

I don't believe the Divine power source is only about what powers your deity passes on. Divine involves more than just the gods, it also relates to celestials, fiends, and undead. A Wizard or Suffused interested in Divinity may have little to do with the gods, but be interested in the power of other divine forces, and I do believe Fear is one of these forces.

The argument of "they would only be available to some deities" could be said about every theme in the Divine power source. Not every god cares about Light, Life, Holy, Unholy, or Undeath. These themes don't represent the power of the gods, but instead powers of Divine nature (light and light is of divine nature no matter which god you serve).

**Comment by mlenser** [comment]
> I don't know, I feel like Fear can fit any deity.

Taking a look at the Greek Deities:
![image](https://user-images.githubusercontent.com/235857/126075886-7ea7b0b2-99dd-4e27-b357-8fa423df6cee.png)

- Zues is Tempest. He himself can do frightful things, but his acolytes wouldn't be known to be frightening.
- Aphrodite is the goddess of love and beauty. Definitely not frightening.
- Apollo is the god of light, music, and beauty. Definitely not frightening.
- Ares is the god of war and strife. He himself can do frightful things, but his acolytes wouldn't be known to be frightening.
- Artemis is the goddess of hunting and childbirth. Definitely not frightening.
- Athena is the goddess of wisdom and civilization. Definitely not frightening.
- Demeter is the goddess of agriculture. Definitely not frightening.
- Dionysus is the god of mirth and wine. Definitely not frightening.
- Hades is the god of the underworld. Not frightening in the normal sense. More about life and death.

So none of those deities would commonly have the Fear theme in their portfolio for their Acolytes.

**Comment by mlenser** [comment]
> I don't believe the Divine power source is only about what powers your deity passes on.

That's exactly what this issue is about. Dionysus, the god of mirth and wine, should not offer the Fear theme to its Acolytes.

> Divine involves more than just the gods, it also relates to celestials, fiends, and undead.

None of which choose themes from the Divine power source. They choose specific themes like light, life, poison, fire, undeath, etc.

> A Wizard or Suffused interested in Divinity may have little to do with the gods, but be interested in the power of other divine forces, and I do believe Fear is one of these forces.

"Divine forces" is not a possible differentiator or else every theme should be available in the Divine power source.

> The argument of "they would only be available to some deities" could be said about every theme in the Divine power source.

Exactly what this issue is about. Read the original issue.

**Comment by Marcloure** [comment]
Speaking about Fear itself, the Divine power source is related to powers of immortals, to things much larger than mortal life. In every culture people learn to fear the gods and their divine wrath, and speaking of fantasy worlds, I believe even Aphrodite and Dionysus could put on an immortal visage that would scare humans and animals alike.

> Exactly what this issue is about. Read the original issue.

Sure, I understand the issue, but until it is solved in a better way, I don't think going against Fear is good. Based on what I said above (fear of beings much more potent than mere mortals), Fear is much more fitting than Undeath, Light, and Courage.

Also, consider that without Fear, the Divine power source is very thin. It's likely that a PC with Life, Light, and Holy won't take Death, Undeath, and Unholy, so the power source has only 4 themes for "bright" acolytes and 4 themes for "dark" acolytes.

**Comment by mlenser** [comment]
I gave an example of many Greek deities above. Fear is not fitting for the vast majority.

The same is true for Undeath, Light, and other themes, but those themes are not in other power sources so they will remain.

Fear won't be added back to the Divine Power source, barring whatever final solution I come up with.

**Comment by Marcloure** [comment]
If this power source represents the powers given by deities, and not the power related to immortal creatures, then it indeed makes no sense...

**Comment by mlenser** [comment]
I've explained it above a few times now, but I will try one last time. Please let it rest after that.

Acolytes get their power from their deity. Deities should give powers based on their portfolio, not a wide range of options that would be very against their portfolio. That's generally 3-5 themes total. That's the goal.

The Divine power source has no purpose other than:
- Acolytes
- Suffused

Acolytes shouldn't have access to all the themes. Suffused shouldn't either. Any creatures already have the themes appropriate for them.

The Divine power source shouldn't be a collection of themes, really. Or at least not a collection of themes like the other power sources that give access to each theme.

**Comment by DalenWBrauner** [comment]
> The Divine power source shouldn't be a collection of themes, really.

Then what reasoning do we have for it to still exist? If Holy/Unholy were to come with the Acolyte class, then what purpose would a Power Source serve? Other than "the work hasn't been done yet"- is there any reason Acolytes shouldn't have their themes come exclusively from their subclass?

**Comment by mlenser** [comment]
> Then what reasoning do we have for it to still exist?

This issue is open to solve that problem.

> Other than "the work hasn't been done yet"- is there any reason Acolytes shouldn't have their themes come exclusively from their subclass?

I need to have a clear understanding of how it should function. It affects the Acolyte and Suffused and possibly other power sources. How to handle it fully isn't clear.

**Comment by mlenser** [comment]
Acolyte subclasses are now based on their deity’s portfolio. Acolyte’s power source is a collection of themes determined by the deity.
