### ISSUE TITLE
Improve See Magical Invisibility

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#595]
I suggest that [See Magical Invisibility](https://www.kryxrpg.com/spells/see-magical-invisibility) be improved a bit (compare it to [Seeing](https://www.kryxrpg.com/spells/seeing)).

My suggestion is that one of the following is added (and maybe the spell should be renamed):
- You have advantage on saving throws against magical illusions you can see
- You automatically succeed on saving throws against magical illusions you can see
- You see a faint aura around any creature or object that bears magic, including invisible creatures or illusions.

Possibly through augments, or possibly by making *this* effect an augment of Detect Magic.

**Comment by mlenser** [comment]
Antimagic shouldn't anti-illusion. Seeing can see through issusions because it lets you see things as they are.

Savvy Skeptic should be removed and this shouldn't add more anti-illusion stuff.

**Comment by mlenser** [comment]
Some spells in some themes are better than other spells. Seeing is better than See Magical Invisibility. But See Magical Invisibility should not be the same as seeing as Antimagic is not the same theme as Divination.

If it can be made better then it should be made better, but it should not absorb the flavor that seeing has.

**Comment by mlenser** [comment]
See Magical Invisibility now allows the caster to attempt to end the invisibility
