### ISSUE TITLE
Specify if you keep or pick the Determined Human reroll

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#596]
> Determined. When you make an attack roll, an ability check, or a saving throw, you can reroll the roll, but before any effects of the roll are applied.
> Once you use this trait, you must finish a short or long rest before you can use it again.

The feature should say if you keep the new roll or if you can choose which one to keep.

**Comment by mlenser** [comment]
Reroll means use the new dice. The places that mention "you must use the new dice" are verbose and can be removed.

**Comment by mlenser** [comment]
Reroll wording cleaned up so using the new roll isn’t specified, but assumed
