### ISSUE TITLE
Destructive Wave persistent aura and prone condition

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#597]
The Destructive Wave's augment that turns the spell into a persistent aura is actually not as effective as it seems. The affected creature has to make the saving throw at the start of its turn, but then it can just get up again if it falls prone. Sure, it is still effective when the creature enters the area, but that is once per casting (unless you cheese the effect by walking back).

**Comment by mlenser** [comment]
Fancy that, I just removed Destructive Wave earlier today.

**Comment by Marcloure** [comment]
Hm, why was that?

**Comment by mlenser** [comment]
Destructive Wave removed as Corona of Light can cover the niche
Destructive Wave removed as Consumptive Field can cover the niche
