### ISSUE TITLE
Combine Deceiver and Blessing of the Deceiver

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#599]
[Blessing of the Deceiver](https://www.kryxrpg.com/spells/blessing-of-the-deceiver) costs an action and gives advantage on deception for a minute to an ally.

[Deceiver](https://www.kryxrpg.com/spells/deceiver) costs a reaction and gives advantage on a single deception check.

I think it would make sense for the two spells to be combined, very much like [Feather Fall](https://www.kryxrpg.com/spells/feather-fall) with the preemptive and reactive versions.

If we want to be consistent, we could even make similar changes with [Browbeat](https://www.kryxrpg.com/spells/browbeat) (coercion), [Judge](https://www.kryxrpg.com/spells/judge) (insight), and [Friends](https://www.kryxrpg.com/spells/friends) (persuasion).  I assume here the balance is similar for all skills, though I may be mistaken.

**Comment by mlenser** [comment]
Blessing of the Deceiver removed as Deceiver covers the niche
