### ISSUE TITLE
Quivering Palm says it's a spell

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#60]
> last for the duration, until you end them, or until you use this spell again.

Also, isn't this maneuver a bit weak? It adds your stamina die to the damage, but other maneuvers do that too while applying other effects.

**Comment by mlenser** [comment]
fixed the typo.

Regarding it being weak see the [Maneuvers spreadsheet](https://docs.google.com/spreadsheets/d/1_ig6KbPdhBrkIp3JqgHIRR8XbBTu-O1zNKuLJXgu378/edit#gid=278923347) where you'll see that Quiverring Palm's save is made with disadvantage which makes it worthwhile.
