### ISSUE TITLE
Martial Empowerment shouldn't be in Force

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#600]
https://www.kryxrpg.com/spells/martial-empowerment

**Comment by itamarcu** [comment]
Antimagic?

Or, if #594 results in Force being split into "forcefields/constructs" and "magic utility", this could belong to the 2nd one.

**Comment by mlenser** [comment]
Antimagic? Huh? This is 100% magic. I was thinkin Alteration or Mind (like mind over body).

**Comment by itamarcu** [comment]
Alteration and Mind make sense too, especially with Mind being psionic and close to the flavor of ki.

I mentioned Antimagic just because this spell takes away your magic, in a way :P

**Comment by DalenWBrauner** [comment]
I would say Alteration, but not Mind. Alteration falls under the Psion's power source, so they can still achieve it that way.

While I can see this spell befitting a Psionic Warrior, I don't see it befitting any other character or creature that takes the Mind theme.

**Comment by DalenWBrauner** [comment]
I could also see this being in the Beast theme (empowerment through body shifting), the Blood theme (using mana to power your body through your blood), or Courage (emboldening yourself to perform a heroic feat).

**Comment by mlenser** [comment]
> While I can see this spell befitting a Psionic Warrior

Psionicists don't need this spell as they have psi which can be freely converted.

**Comment by mlenser** [comment]
> Beast theme (empowerment through body shifting)

Wild Shape already does this

> Blood theme (using mana to power your body through your blood)

This is a bit of a stretch. Mana -> blood -> stamina. Seems like Blood would sacrifice health for stamina.

**Comment by mlenser** [comment]
Martial Empowerment renamed Invigorate and moved to the Alteration and Courage themes
