### ISSUE TITLE
Combine Dayvision Potion and Essence of Night

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#601]
https://www.kryxrpg.com/concoctions/dayvision-potion

https://www.kryxrpg.com/concoctions/essence-of-night

These two do the same thing, with different names and different themes.  I think they are similar enough to be combined to a single concoction.

Also, it's worth noting that [the Dayvision spell](https://www.kryxrpg.com/spells/dayvision) only belongs to Alteration, while the concoctions above belong to both Alteration and Shadow.  Why shouldn't Dayvision belong to Shadow too, then?

(I think all of these should also belong in Light, but I can see arguments against it too)

**Comment by mlenser** [comment]
Dayvision spell and Dayvision potion replace with Essence of Night

for both Alteration and Shadow
