### ISSUE TITLE
Add 'Extinguish Flames' to Quick Reference Sheet

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#603]
Yes, I know players that still use it :) 

> **Extinguish Flames.** You make a DC 10 Dexterity check to extinguish the flames on yourself or an ally (see Burning [condition](https://www.kryxrpg.com/rules/conditions)).

**Comment by mlenser** [comment]
Added extinguish flames to the Quick Reference
