### ISSUE TITLE
Bones of the Earth and cylinder sizes

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#604]
https://www.kryxrpg.com/spells/bones-of-the-earth

In 5e, this created 5 ft radius 30 ft high cylinders.  In KryxRPG, it's just "a cylinder", implying it's a 5xM ft radius 15xM ft high cylinder, where M is the amount of mana/psi spent.

It's cool that this spell can make taller and bigger earth pillars, but this causes some issues:

- Pillars can lift multiple creatures up, but the spell is balanced around each pillar lifting just one creature
- Pillars leave a 10 ft radius difficult terrain area around them when they break... but obviously wider pillars should create a bigger area.
- The size restriction of creatures under pillars doesn't actually depend on pillar size right now.
- The dexterity save to move 5 feet away doesn't make sense if a large pillar is created under a creature/

I suggest changing the spell so that it simply creates 5-ft-radius 30-ft-high pillars, with an augment to increase pillar height by 30 feet instead of adding more pillars.

I do think that creating wide earth pillars out of the ground is awesome (I did watch ATLA), so I think there can be room for another Earth spell added (possibly as a variant of this):  a spell that just makes one huge cylinder (twice the normal size), that  rises up from the ground and lifts everything on it, not instantly but over time (e.g. rising 30 feet every round).  That spell would be for utility and epic moments, not for damage.

**Comment by Marcloure** [comment]
>  a spell that just makes one huge cylinder (twice the normal size), that rises up from the ground and lifts everything on it

I agree that a separate "Rise Ground" spell could be quite cool.

**Comment by DalenWBrauner** [comment]
> the spell is balanced around each pillar lifting just one creature
Is it? I don't think there's anything in the spell that has any problem with lifting multiple creatures. As far as I can tell, all of the text of spell still works with three tiny things on one pillar.

I would agree with everything else, though; either we need to reword the spell to properly scale with pillar size, or we decide that the pillar size doesn't scale with mana (your augments give you additional pillars anyway).

**Comment by itamarcu** [comment]
> the spell is balanced around each pillar lifting just one creature

This sentence was just based on the spreadsheet. It didn't have the same area-based target multiplier that other spells have.

**Comment by mlenser** [comment]
>  implying it's a 5xM ft radius 15xM ft high cylinder,
> It's cool that this spell can make taller and bigger earth pillars

I don't understand the math or where you think these pillars are bigger. The pillars are normal cylinders. At 1 mana they are 4.5 meters tall, at 2 mana they are 9 meters tall, at 3 mana they are 13.5 meters tall, etc.

> Pillars can lift multiple creatures up, but the spell is balanced around each pillar lifting just one creature

Unlikely. The sheet in this case is a best estimate.

> Pillars leave a 10 ft radius

I'll refine the radius from the rubble: "which creates an area of difficult terrain that is twice as wide as its normal radius"

> The size restriction of creatures under pillars doesn't actually depend on pillar size right now.

I've removed this

> The dexterity save to move 5 feet away doesn't make sense if a large pillar is created under a creature

We use Reflex to avoid giant balls of fire. I think there is also a 5e spell that lets you avoid being in a dom of some kind.

**Comment by mlenser** [comment]
Bones of the Earth damage recalculated and it has been refined to remove the creature size limitations and to improve the rubble so that its size is based on the size of the cylinder
