### ISSUE TITLE
Make number of species-given spells consistent

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#605]
Currently species have features that gives them spells as follows (usually with a cantrip)

* [Deep Gnome (3)](https://www.kryxrpg.com/character/species/gnome) - Blindness/Deafness, Disguise, Blur (2 mana!)
* [Duergar (2)](https://www.kryxrpg.com/character/species/dwarf) - Enlarge/Reduce, Invisibility.  Also, no cantrip
* [Drow (3)](https://www.kryxrpg.com/character/species/elf) - Darkness, Faerie Fire, Levitate
* [High Elf (1)](https://www.kryxrpg.com/character/species/elf) - Any one spell from Arcane source
* [Genasi (2)](https://www.kryxrpg.com/character/species/genasi) - Any two spells from Air/Earth/Fire/Water
* [Githyanki (2)](https://www.kryxrpg.com/character/species/gith) - Striding and Springing, Teleport
* [Githzerai (3)](https://www.kryxrpg.com/character/species/gith) - Force Shield, Mind Over Body, Thought Shield
* [Firbolg (2)](https://www.kryxrpg.com/character/species/firbolg) - Disguise, Invisibility
* [Tiefling (2)](https://www.kryxrpg.com/character/species/tiefling) - Any two spells from a list of eight specific spells

I believe that these should be standardized to either:
1. All grant 2 spells
2. All grant 3 spells
3. All grant either 3 specific spells or 2 custom spells from lists (like Genasi and Tiefling), depending on species
4. All grant either 2 specific spells or 1 custom spells from lists (like High Elf), depending on species

I'd be in favor of any of these solutions.

If we go with solution 3, the changes I'd make are:
* Deep Gnome - replace Blur with False Sensory Input or Shadow Veil (1 mana spells)
* Duergar - add a cantrip: Ferrous Growth, and a spell: Sustenance
* High Elf - change to any two Arcane spells
* Githyanki - add Telekinetic Charge
* Firbolg - add Animal Messenger

If we go with 4 instead, and need to remove spells, I'd remove:
- Deep Gnome: Blur
- Drow: Levitate
- Githzerai: Mind Over Body (I don't see why they should both have the spell and have a feature that does the same)

**Comment by Paulorpribeiro** [comment]
I'd vote for 2 prechosen spells (like for golf is now) or one choice from a power source + a cantrip (like high elf is now). All 1 mana. 3 spells is far too much for a species to have for free. That's what half caster get at lvl 1

**Comment by mlenser** [comment]
Some spells are inherent to species and shouldn't be removed. Drow for example have had Dancing Lights, Darkness, Faerie Fire, and Levitate for multiple editions. Deep Gnomes have has Blindness, Blur, and Change Self (Disguise).

**Comment by itamarcu** [comment]
For Deep Gnomes, the fact that Blur is a 2-mana spell makes this a bit troublesome.  With the current rules, they learn the spell at 3rd level, even though no one else can get the spell before 5th level. Possibly solvable with #617 (Blur as 1 mana concentration).

One possible option would be to give each species a choice of 2 spells from a list of 3-4 options.  Could also extend this to cantrips. For example:
- Deep Gnomes - choose two from Blindness, Disguise, Blur.
- Duergar - choose two from Enlarge, Invisibility, *Sustenance* (maybe also give cantrip: Hammer?)
- Drow - choose two from Darkness, Faerie Fire, Levitate
- High Elf - Detect Magic and choose one 1-mana spell from the Arcane power source
- Genasi - choose two 1-mana spells from Air/Earth/Fire/Water (depending)
- Githyanki - choose two from Striding and Springing, Teleport, Telekinetic Charge
- Githzerai - choose two from Force Shield, Thought Shield, Mind Over Body
- Firbolg - choose two from Disguise, Invisibility, Animal Messenger (or Locate Animals or Speak With Animals)
- Tiefling - choose two from (same list) charm creature, darkness, disguise, immolation, fiery rebuke, poison burst, ray of enfeeblement, ray of sickness.

**Comment by mlenser** [comment]
Some species are more magical than others. Variance is ok here. I've categorized the differences and assigned points. See #618 as a followup.
