### ISSUE TITLE
10 vs 11 gallons, in Create/Destroy/Purify Water

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#606]
![](https://cdn.discordapp.com/attachments/701706060440010756/777876388119052359/unknown.png)
![](https://cdn.discordapp.com/attachments/701706060440010756/777876437574746132/unknown.png)

**Comment by mlenser** [comment]
Explanation: Conversions have some exceptions to ensure we get nicer numbers. The conversions can be done with a string or a regex. regex allows them to occur multiple times. I had it in my notes to make sure they were all regex, but forgot liquids. This is fixed now:

![image](https://user-images.githubusercontent.com/235857/99306247-37e4ba00-2855-11eb-9b6f-a8114e7cf8ed.png)
