### ISSUE TITLE
Change 3.25 feet to 3 feet

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#607]
There's a standard of "1 meter" that always gets converted to "3.25 feet", for example in [Floating Disk](https://www.kryxrpg.com/spells/floating-disk), and again in lots of spells that have to do with objects ([Call Object](https://www.kryxrpg.com/spells/call-object) for example).  I think it would be nicer if `1, 2, 3, 4, 5` meters were translated into `3, 6, 10, 12, 15` feet. (currently it's:  `3.25, 6.5, 10, 13, 16`)

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/99306818-fbfe2480-2855-11eb-9bdf-70e922ecde7e.png)

**Comment by itamarcu** [comment]
Uhhh, this might have not been a perfect fix.

![image](https://user-images.githubusercontent.com/6516621/99411446-46d27780-28fc-11eb-8c31-ae81ea034a3b.png)

It says 9 feet instead of 10 feet, almost everywhere.

**Comment by itamarcu** [comment]
(not sure if I should reopen this or open a new ticket, sorry)
