### ISSUE TITLE
Remove Sand Walk

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#608]
https://www.kryxrpg.com/spells/sand-walk

This spell is **very** niche.  The only thing it can do is protect a creature from quicksand.

Either we add more features to the spell (e.g. allow fast movement on dunes), or we remove the spell.

**Comment by mlenser** [comment]
Is it worthless? What if the campaign takes place on a planet like featured in Dune?

Sand can easily be considered difficult terrain and this spell nullifies that.

**Comment by itamarcu** [comment]
Sand can sometimes be considered difficult terrain, but there are many other things that can be too (high grass, mud, rocky terrain) and there aren't spells that act on these particular surfaces.  There's Water Walk, but that spell is useful because most worlds have a lot of water everywhere (oceans, rivers, swamps...) and it even extends to stuff like lava.

Even if the players are traveling a desert, this spell is not really good right now; it's 2 mana to make a single party member avoid difficult terrain (or the potential quicksand) for one hour.  If you want to cast this on your entire party, you must either spend a lot of mana or spend your time ritual-casting the spell again and again. Plus, there are other, more generic spells that help against difficult terrain (Freedom of Movement, Hover, Fly...) and if your ally is deep in quicksand you might not even be able to see them to cast the spell on them.

If the spell was changed to a more generic "move good in sandy areas" spell, I could see its merit.  For example, if it allowed you to slide fast on sand (60 feet of movement), or if it granted burrow speed.

**Comment by Marcloure** [comment]
I think the spell could be lowered to 1 mana. I like it that it is a ritual, so it doesn't actually cost 1 mana

**Comment by mlenser** [comment]
> most worlds have a lot of water everywhere (oceans, rivers, swamps...) and it even extends to stuff like lava.

If most worlds reflect the earth then they should also have lots of sand. 33% of earth is sand. There are also worlds that are 100% sand. For these normal words the spell seems like a good option.

**Comment by mlenser** [comment]
This spell avoid difficult terrain and can bypass encounters that are intended to be very debilitating so when it is useful it is super useful. Based on the second point I believe that part must remain at 2 mana.

**Comment by mlenser** [comment]
Sand Walk changed from 2 mana to 1 mana and now makes it so a creature is unhindered by difficult terrain caused by sand. It can be augmented to move across sandy surfaces as before.
