### ISSUE TITLE
Divine Emissary (Holy Find Familiar)

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#609]
I think there is flavor here. An Acolyte of Odin can have a crow familiar, the goddess of the sea can give a crab emissary to its followers, the god of hunt can send a hawk, Lolth a spider, so on.

**Comment by mlenser** [comment]
Can you please flesh out this idea? Not sure what you intend here.

**Comment by Marcloure** [comment]
My intent is to make a duplicate of Find Familiar into Holy, since I think many gods can send an animal to their followers as some sort of guide or emissary

**Comment by mlenser** [comment]
Please write up the text you'd expect as I'm unclear what you're after. Should I take find familiar and replace some parts? I can only guess your intent, so it'd be good if you could write it.

**Comment by Marcloure** [comment]
> **Divine Guide (or Divine Emissary)**
> _(ritual); M (charcoal, incense, and herbs worth 10 sp that must be consumed by fire, consumed)_
> As you spend 10 minutes to cast this spell, you summon a divine emissary from your god to assist you on your quest. The creature's form is one of the following that most fits the domains of your god: awakened shrub, bat, cat, crab, crawling claw, fish (quipper), flying snake, frog (toad), hawk, homunculus, lizard, octopus, owl, poisonous snake, rat, raven, sea horse, spider, weasel, or any Tiny or smaller beast of challenge rating 0.
> 
> [Copy and past Find Familiar rules here]

This is basically it.

**Comment by mlenser** [comment]
Divine Emissary added as a 1 mana spell that is similar to Find Familiar

**Comment by itamarcu** [comment]
I suggest also updating [Improved Familiar](https://www.kryxrpg.com/feats/improved-familiar) to allow for this - because it's definitely flavorful for some evil acolytes to have something like an imp.

**Comment by mlenser** [comment]
Improved Emissary added as a feat
