### ISSUE TITLE
Blackguard's spells and maneuvers

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#61]
## Blackguard
"Blackguards are paladins who broke their sacred oaths and now indulge their own dark ambitions. They consort with fiends and undead, and they reject all goodly things from their former lives."

**Themes:** Death, Deceit (martial only), Divine, Fear, Shadow (martial only)

### Maneuver:
**1 stamina die:** Bloodletting Blade, Feint, Grievous Wound, Stalking Shadow
**2 stamina dice:** Blind, Feigned Opening, Misdirection

### Spells:
**Cantrips:** Frighten, Life Siphon, Sacred Flame, Toll the Dead
**1 mana:** Absorb Spirit, Command, Fear, Divine Weapon, Inflict Wounds, Life Drain, Protection form Evil and Good
**2 mana:** Control Undead, Destructive Wave, Divine Steed, Fiendish Calling, Finger of Death, Terrifying Visage, Wall of Terror
**3 mana:** Antilife Shell, Hurl Through Hell

**Comment by Marcloure** [comment]
Should I do the War Priest as a half caster as well, or should it remain a full caster?

**Comment by mlenser** [comment]
I think we should split War Priest:

1. Avenger
2. Paladin
3. Priest

**Comment by mlenser** [comment]
_**Maneuvers.**_ The blackguard uses maneuvers (maneuver save DC 15). It has 10 stamina dice which are d8s, a dice limit of 3, regains its stamina dice when it finishes a short or long rest, and knows the following maneuvers:

1 stamina die: bloodletting blade (Scimitar only), cripple, disorient, distract, feint, grievous wound, slice through, whirling blade

2 stamina dice: blind, feigned opening, misdirection, staggering strike

_**Spellcasting.**_ The blackguard casts spells. Its spellcasting ability is Wisdom (spell save DC 13, +5 to hit with spell attacks). It has 5 mana, a mana limit of 3, regains its mana when it finishes a short or long rest, and knows the following spells:

Cantrips (at will): death blade, frighten, life siphon, sacred flame

1 mana: absorb spirit, bane/bless, command, divine shield, divine weapon, false life, fear, inflict wounds, life drain, path to the grave

2 mana: circle of death, control undead, destructive wave, divine steed, fiendish calling, finger of death, speak with dead, terrifying visage, wall of terror

3 mana: antilife shell, death ward, hurl through hell

**Comment by Marcloure** [comment]
Priest already exists at CR 2 (needs scaling). Blackguard is evil paladin. So, add an Avenger (maybe name the creature zealot)?

**Comment by mlenser** [comment]
> Blackguard is evil paladin.

We need a good Paladin.

> So, add an Avenger (maybe name the creature zealot)?

Avenger, imo. Zealot is already somewhat associated with Barbarian due to its subclass in RAW
