### ISSUE TITLE
Lower Ice Sculpture to 1 mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#610]
Ice Sculpture doesn't seem that useful as a 2 mana spell. The spell's area isn't that large to make bridges at 2 mana, so I think it could be lowered to 1 mana without a issue.

**Comment by mlenser** [comment]
This spell is very similar to Shadowy Creation and Fabricate. They likely need to stay at the same mana level.

**Comment by itamarcu** [comment]
it only takes 1 minute to cast (unlike Fabricate's 10), and if you have some water/ice/snow around you can make stuff bigger than Shadowy Creation enables, so I think it's actually good where it is.  For a bridge-building spell, I would just suggest creating a completely new spell, probably something with a lower duration and less flexibility.

**Comment by Marcloure** [comment]
You can make adamantine weapons with Shadowy Creation, or a long rope, gemstones, a shield, a resilient window, so on. Ice Sculpture is far more limited in this aspect: it can only make objects out of hard ice

**Comment by itamarcu** [comment]
Ice can still make some of these - weapons, shield, window - but you're right that it's less versatile.

I think it would make more sense to keep the 2 mana cost, but improve it in other ways (area, duration...) - so it's more similar to the other spells.

If the goal is to be able to be like Elsa, maybe the spell (or an augment) could be like Mold Earth, in the sense that it lets you create and reshape ice over a long duration, instead of just making one thing quickly.

Another way this spell could be improved would be if it let you instantly shatter the ice, as a free/bonus action.  This would allow for some cool traps, and fun RP situations!

**Comment by mlenser** [comment]
Please write up a version that could be "good enough" for 2 mana.

I've also added "Form Ice"

**Comment by itamarcu** [comment]
### Suggestion (changes are in bold/strikethrough):
*1 hour/mana*
As you spend 1 minute to cast this spell, you create and shape ice into the form of an object of your choosing within 30 feet for the duration. The object created must be no larger than a 5-foot cube or a 10-foot cube if you have a nearby volume of water, ice, or snow. The object melts after **10 minutes** in a hot environment, ~~melts after half the duration in a warm environment,~~ and melts after **24 hours** in a cold environment.

**As a bonus action on your turn you can make the object melt or explode into shards. If it explodes, each creature within a sphere centered on it must make a Reflex saving throw. On a failed save, the creature takes 3d10 piercing damage, or half as much damage on a successful save.**

**Augment:**
**- You can increase the size of the cube by 5 feet for each additional mana or psi, or 10 feet if you have nearby water, ice, or snow.  The damage from the shards increases by 2d10 for each additional mana or psi.**
**- You can expend 1 additional mana or psi to create up to 6 additional objects, as long as each can fit within a 5-foot cube.**

---

Now the environment matters more (melts after 10 minutes in a desert, but can last for an entire day in a snowy area), which should make it a bit more impactful.  Also, now you can use a bonus action to make a trap sculpture explode and damage everyone around it, or to melt a barricade you erected around something to protect it.  The augments to increase the area felt necessary, and the augment to create extra items is something that I feel like the spell needs anyways (e.g. to arm some villagers with ice spears) but would be extra useful with the ability to create several little "ice traps" in an area.

**Comment by DalenWBrauner** [comment]
I have a concern with the "6 additional" augment. Wouldn't that create 6 objects you could remote-detonate for 3d10 damage each? Even if they each take seperate bonus actions, that feels like a lot of value for 3 mana- especially considering that isn't this spell's primary purpose.

I don't mind the idea of adding offensive options, but these seem less like traps and more like objects you can toss at your foes and detonate in realtime. The version you suggested would make for some probably-too-great throwing knives.

**Comment by mlenser** [comment]
I think this spell and spells like Shadowy Creation are confused. It should be able to make a bridge over a gap or a small item.

**Comment by itamarcu** [comment]
I do think creating bridges/stairways/barriers would be quite often useful, but the problem is that Wall of Ice is a spell that can do exactly these things.  If this spell had the ability to create bridges and such, Wall of Ice would have less of a purpose, other than its damaging capability. 

Creating a bridge over a 5-foot or 10-foot gap is not really useful - it's small enough you could usually just jump across, or lay down a plank, or something.  For creating tiny items, Form Ice (previously Frozen Trinket) seems good enough.

I think the niche here should be creating medium-to-large items - box, statue, barricade, sled, weapons/shields (if it can do multiple small items), igloo, temporary cage/restraints, and so on.

**Comment by mlenser** [comment]
I think we need to start from scratch here (and for similar spells). We should have a cantrip that can create minor stuff and a spell that can create bigger stuff like ice or shadow bridges.

**Comment by itamarcu** [comment]
I don't think "shadow bridges" make sense.  Shadows aren't solid, and Shadowy Creation is pretty much an outlier - it's almost like a pure Creation spell that mentions "from the shadowfell".  I don't think Shadow should be able to do that, so I think that spell should move to Creation (or get removed).

With Ice Sculpture, though, I feel like it's already pretty good, and I'd prefer to only make minimal improvements to it - like some of the ones I suggested above.

Creating ice bridges with Wall of Ice is already possible, and I think this spell can't really fit the idea - this spell is about creating medium-large and somewhat complex objects, but walls are much bigger and much simpler.  If we want Ice to make long walls like Wall of Stone can do, maybe it can be a variant option in Wall of Ice, to make something longer and not damaging.

**Comment by mlenser** [comment]
> it's almost like a pure Creation spell that mentions "from the shadowfell". I don't think Shadow should be able to do that, so I think that spell should move to Creation (or get removed).

It's from RAW: https://www.dndbeyond.com/spells/creation

> Creating ice bridges with Wall of Ice is already possible.

Wall of ice must be made on a solid surface. It would not work to span two gaps.

> this spell is about creating medium-large and somewhat complex objects

This is why I said we shuld start from scratch. I think this spell is generally worthless. We should have a cantrip to create small stuff and a spell to create big stuff.

**Comment by mlenser** [comment]
Ice Sculpture removed as it is too much of a trap option. I don't have the motivation to tackle the revamp now, but if someone does please open a new issue with how we could structure it better. What I wrote above on https://github.com/mlenser/kryx-rpg-issues/issues/610#issuecomment-735434152 I think is a good starting point.

**Comment by DalenWBrauner** [comment]
For future reference, Kryx found a cool example:
![unknown-7](https://user-images.githubusercontent.com/3477032/103097850-a6483500-45d6-11eb-8cd8-17bd5067a41d.png)

Notable differences include:
* 1 Action cast time with 10 minutes duration (vs 1 minute for 1 hour)
* explicit hit points, AC and damage types
* explicit banning of machinery
* ice transparency, which probably didn't need to be stated?
* lacks bonus to casting adjacent to water/ice
