### ISSUE TITLE
Remove Hold Creature from Mind

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#611]
Mind has Hold Creature and Psychic Crush, but Psychic Crush is objectively better since it deals damage. Choosing Hold Creature is a trap option in this case

**Comment by Marcloure** [comment]
Also, Paralytic Poison and Bind Blood deal 5d6, while Psychic Crush deals 2d6. I suppose that is because they require a Fortitude save, instead of a Will save?

**Comment by itamarcu** [comment]
Related: #571

**Comment by Marcloure** [comment]
Kryx have said that:
> Hold Creature and Stasis are more neutral - they could be used to restrain someone without hurting them

While that is true, I still think that this is a very niche use. Most people will pick one and not even consider picking the other just because of this use. It would be bad if they picked Hold Creature without realizing there is a better version of it a few boxes below.

**Comment by mlenser** [comment]
Hold Creature removed as Psychic Crush and Stasis cover the niche
