### ISSUE TITLE
Hurl Boulder

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#613]
I was surprised to find that the Earth theme has no spell that allows throwing a big rock at someone.  The closest things are Catapult (telekinesis theme), Avalanche (which throws multiple rocks in a cone/line), and of course Mold Earth (which is a cantrip).

Here's my suggestion (balanced according to spreadsheet, roughly):

# Hurl Boulder (spell, 1 mana)
As an action, you pull earth and stone from the ground, forming a large rock and hurling it at a creature or object within 60 feet. The target must succeed on a Reflex saving throw.
On a failed save, the target takes 3d8 bludgeoning damage and is knocked prone.
On a successful save, the target takes half as much damage and isn't knocked prone.

#### Augment
* You can increase the damage by 4d8 for each additional mana or psi expended.
* **Big Boulder**. You can expend 1 additional mana or psi to increase the size of the rock, making it the size of a sphere. All creatures within the sphere must make the saving throw. The ground under the sphere becomes rubble, an area of difficult terrain that lasts until the rubble is cleared. Additional augments to this spell increase the damage by 1d8 bludgeoning damage.
* **Hard Rock**. You can expend 1 additional mana or psi to make the rock sturdy and hard. The rock remains where it lands, as a 5-foot-radius sphere with 5 Defense and 30 Health. The target is pushed 5 feet away from its center. When reduced to 0 health, the rock crumbles into rubble, an area of difficult terrain that lasts until the rubble is cleared.

**Comment by DalenWBrauner** [comment]
I like this spell a lot! I have a goofy question though, because of course I do.

If you pull all this rock from the earth, would there be any rock missing from the earth afterwards, or is conjuring it a bit of the magic (like with a lot of water spells)?

**Comment by Marcloure** [comment]
I like the spell a lot as well, but I prefer the name Hurl Boulder than Boulder Hurl.

**Comment by itamarcu** [comment]
@DalenWBrauner I thought about it too, and at first I tried to make it "60 foot range, or 120 foot range if you toss an existing boulder", and also considered "...pulling from the ground in a 5-foot cube next to you, which becoes difficult terrain".  But I decided these add a bit too much complexity to the spell that isn't really needed.

@Marcloure - good point, and I think I agree!  I'll rename it.

**Comment by mlenser** [comment]
Big Boulder is pretty much already covered by Erupting Earth plus the thematics of making a huge boulder that is as big as a sphere and throwing that is.. weird. I'm more concerned about the niche though which I think Erupting Earth covers fully.

**Comment by mlenser** [comment]
Hurl Boulder added as a 1 mana spell
