### ISSUE TITLE
Rename "-er" spells and maneuvers

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#614]
This is more of an opinion - I think these names are not good, because they go against the general pattern of spell/maneuver names: verb or descriptive noun.

The changes I'm asking for are:
* Blooddrinker → Blooddrinker Weapon / Blooddrinking Weapon / Bloody Weapon
* Deceiver → Deceive
* Flesh Ripper → Rip Flesh
* Spell Slayer → Spell Slay / Slay Spell / Spellsplinter / Counterstab / Suppress
* Tidal Breaker → Tidal Break / Breaking Wave
* Vine Lasher → Lashing Vines
* Webshooter → Webshoot / Spinneret / Silk-Spinning / Web-shooting

(I'm alright with keeping others, like Animal Messenger or Blessing of the Deceiver)

**Comment by mlenser** [comment]
- Blooddrinker renamed Blooddrinking Weapon
- Deceiver renamed Deceive
- Flesh Ripper renamed Tear Flesh
- Spell Slayer renamed Spellsplinter Weapon
- Tidal Breaker renamed Tidal Break
- Vine Lasher renamed Vine Lash

Webshooter will remain as you become a webshooter (based on spiderman)
![image](https://user-images.githubusercontent.com/235857/99577816-2a0d7100-29dc-11eb-84cd-481e277cc096.png)
