### ISSUE TITLE
Rampage reword

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#615]
https://www.kryxrpg.com/maneuvers/rampage

Currently Rampage is a 1 mana maneuver that states:
> As a bonus action, when you reduce a creature to 0 health with a melee attack, you can move up to half your speed and make an attack roll against a creature.

It's unclear what that last statement means - are you making an attack with the weapon you're holding, or making a special attack roll with some result, or something else?

The spreadsheet implies that this attack deals `1d8+4` damage.  In that case, I am guessing it is either doing your normal weapon damage, or doing stamina + maneuver ability damage.

I suggest changing it to either be like [Ricochet](https://www.kryxrpg.com/maneuvers/ricochet):
> ... make an attack roll against a creature.  On a hit, the creature takes damage equal to the stamina die + your maneuver ability, of the type associated with your weapon, but no additional effects from hitting apply. If you miss by 4 or less, the target takes half as much damage.

Or be like [Frenzy](https://www.kryxrpg.com/maneuvers/frenzy), costing 2 stamina:
> ... make a weapon attack against a creature.

(I think this would be better.  Rampage would be just like Frenzy, with an added ability to move, but restricted to after killing and not scaling the same way)

**Comment by mlenser** [comment]
It lost some wording during the partial hit change. Fixed now

**Comment by mlenser** [comment]
Rampage maneuver lost some wording when we switched to partial hits. It now deals damage based on stamina dice.
