### ISSUE TITLE
Dozens of power cards merge with each other when viewing 2 columns in "All..." page

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#616]
When viewing https://www.kryxrpg.com/themes/all-feats-concoctions-maneuvers-and-spells with a smaller window, that can only view 2 columns at once, and scrolling all the way down, this happens:

![image](https://user-images.githubusercontent.com/6516621/99870941-6bba3980-2bdf-11eb-8e46-93367d3dbeb1.png)

![image](https://user-images.githubusercontent.com/6516621/99870937-64932b80-2bdf-11eb-9388-4e009e873155.png)

This doesn't happen with 3 columns, or with 1 column, or in any other page that I've checked.

This is a minor bug so it's not critical to solve it.  I believe the solution is either to fix the CSS or to sacrifice three innocents of pure blood to the eldritch gods below.

**Comment by mlenser** [comment]
So I spent a fair bit of time on this. It only occurs on spells now. I'm not sure the exact cause, but it has something to do with the number of spells and that specific resolution. I can't fix it without turning off the columns.
So for now use mobile or desktop.

**Comment by itamarcu** [comment]
I think it actually became worse now - now in https://www.kryxrpg.com/spells I see the bug all the time, not only as a small window (2 columns) but also in a regular window (3 columns), and in all zoom levels and all browsers, so now there is no workaround and the page is unusable :/

Was there maybe a recent change that caused this somehow?

**Comment by mlenser** [comment]
I only see it on 2 columns, not 3.

These pages are only for reference. They are not how I want to present the data. So if they are problematic the next result is to remove them.

**Comment by mlenser** [comment]
Spells no longer adapt to the length of the spell to prevent this issue.
