### ISSUE TITLE
Mirror Image, Blur, Entropic Shield - suggested changes

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#617]
1. [Mirror Image](https://www.kryxrpg.com/spells/mirror-image)'s Illusory Self is not that good.  You spend 3 mana as a reaction to create a single illusion, that has only 50% of protecting you from the triggering attack, and costs your concentration.  I think this would be better if it **created two duplicates** or if it **created one duplicate with guaranteed protection and no concentration**.
2. [Entropic Shield](https://www.kryxrpg.com/spells/entropic-shield) requires concentration, while the other Blur-like spells ([Cloak of Shadows](https://www.kryxrpg.com/spells/cloak-of-shadows), [Concealing Amorpha](https://www.kryxrpg.com/spells/concealing-amorpha), [Blur](https://www.kryxrpg.com/spells/blur)) don't.  I think **concentration shold be removed from it**.
3. The duration of the Blur-like spells is all 5 minutes/mana, but reduced to 1 minute/mana when cast as a reaction.  The **duration of Mirror Image should be the same**, in my opinion, as it serves a very similar purpose (through different mechanics).
4. In Mirror Image, "You can use your action to dismiss the illusory duplicates." - I think this can be **reduced to a bonus action or even a free action**, as no one would have any reason to dismiss the duplicates during combat, so I see no problem with allowing them to do it faster.
5. Would it be possible to allow all of these spells at **1 mana but with concentration** (with 1 mana augment to remove concentration)?  This isn't very important, but it would give them a bit more versatility, and it would make it easier to give Blur to Deep Gnomes as a species spell.  I can't find them on the sheet (understandably), so I don't know how strong it would be to have this effect, but I guess it can be compared to [Force Bulwark](https://www.kryxrpg.com/spells/force-bulwark) which grants constant half cover and costs a bonus action.

**Comment by mlenser** [comment]
> In Mirror Image, "You can use your action to dismiss the illusory duplicates." - I think this can be reduced to a bonus action or even a free action, as no one would have any reason to dismiss the duplicates during combat, so I see no problem with allowing them to do it faster.

Many spells require an action to dismiss. Alter Self, Mage Armor, Barkskin, Find Steed, etc. These should be consistent. I'm not sure if we should change them all.

**Comment by mlenser** [comment]
> Mirror Image's Illusory Self is not that good. You spend 3 mana as a reaction to create a single illusion, that has only 50% of protecting you from the triggering attack, and costs your concentration. I think this would be better if it created two duplicates or if it created one duplicate with guaranteed protection and no concentration.

The power of reaction spells have changed. Now they add +6 defense at 2 mana so I think this reaction can be 2 mana and add all 3 illusions.

**Comment by mlenser** [comment]
- **Chaos**
    - Entropic Shield changed from 2 mana to 1 mana and its duration changed to 1 minute/mana [#617](https://github.com/mlenser/kryx-rpg-issues/issues/617)
  - **Creation**
    - Concealing Amorpha changed from 2 mana to 1 mana and its duration changed to 1 minute/mana [#617](https://github.com/mlenser/kryx-rpg-issues/issues/617)
  - **Deceit**
    - Blur changed from 2 mana to 1 mana and its duration changed to 1 minute/mana [#617](https://github.com/mlenser/kryx-rpg-issues/issues/617)
    - Mirror Image changed from 2 mana to 1 mana and its reaction augment changed to create the normal amount of illusions. [#617](https://github.com/mlenser/kryx-rpg-issues/issues/617)
  - **Shadow**
    - Cloak of Shadows duration changed from 2 mana to 1 mana and its changed to 1 minute/mana [#617](https://github.com/mlenser/kryx-rpg-issues/issues/617)
