### ISSUE TITLE
Nerve-rack - Madness reaction spell that staggers

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#619]
(it's a suggestion for a spell. not sure about the name)

---

## Nerve-rack / Nerve-racking Response / Unnerve
(1 mana, *madness*)
As a reaction, which you take when you are hit by an attack, you lash out, unsettling the attacker.

If the creature who damaged you is within 60 feet it must make a Will saving throw as its mind is perturbed.

On a failed save, it takes 1d10 psychic damage and it is staggered until the end of its next turn.

On a successful save, a creature takes half as much damage and isn’t staggered.

#### Augment
You can increase the damage by 2d10 for each additional mana or psi expended.

**Comment by mlenser** [comment]
- Agonizing Rebuke now does less damage and staggers the enemy
- Agonizing Rebuke added to the Madness theme
