### ISSUE TITLE
Winter's Grasp area

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#620]
[Winter's Grasp](https://www.kryxrpg.com/spells/winters-grasp)

- The spell's balance calculation in the sheet is wrong - it's not a standard sphere, it's a 30-ft-aura centered on self that can only hit creatures of your choice (this is much better than a sphere, except for the range)
- Would be nice if instead of a 30 ft aura its size scaled with the mana (currently there's no reason to augment it).  For example, it could be a sphere twice as big as normal (would reduce it to 20 feet at 2 mana; not sure if it's good or bad considering the existing balance issue).
- An alternative idea, instead of augmenting to increase the area, would be adding damage per turn to the restrained creatures, or slowing them, or making them something like petrified for the duration (i.e. encased in ice).

**Comment by mlenser** [comment]
Winter’s Grasp adjusted to all creatures and a much shorter distance
