### ISSUE TITLE
New augments to Ice Slick

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#621]
@itamarcu  and I hashed these out (mostly Shem):

> You can expend 1 additional mana or psi to increase the duration to 1 hour/mana or psi.

> You can expend 1 additional mana or psi to create a layer of dry ice that covers one or several objects within the sphere that aren't being worn or carried.  A creature other than you that touches an object covered in this ice takes 5d4 cold damage when it touches the object and takes this damage again at the end of each of its turns while touching the object.

These came about from brainstorming alternative ways of dealing damage with Ice Sculpture, and realizing they made more sense in a different spell.

**Comment by itamarcu** [comment]
The concept here is enabling Ice Slick to work as not only area denial but also item denial.  The ice mage can cast the spell on a doorknob, a chest, a disarmed enemy's weapon, a valuable object... and prevent anyone (or anyone but the user) from using it or picking it up, at least without consequences.

To be clear - this isn't supposed to be used for the purpose of dealing damage (e.g. by casting it on a net and then throwing the net on an enemy, or something like that).  The attempt is to be preventative and punitive, not aggressive.

**Comment by mlenser** [comment]
> You can expend 1 additional mana or psi to increase the duration to 1 hour/mana or psi.

The duration varies based on environment:

> The ice is an instantaneous effect, but persists as non-magical ice. Under temperate conditions, the ice lasts 1 minute. In tropical environments, it might last only half as long. In cold environments where ice and snow persist without melting, it could last indefinitely.

**Comment by mlenser** [comment]
Added an augment to Ice Slick to freeze objects and clarified its duration
