### ISSUE TITLE
Feet/meters bug in monster attack ranges

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#622]
For example, in https://www.kryxrpg.com/monsters/darkling-elder:
> ***Dagger***. Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 4.5/18 ft. Hit: 5 (1d4 + 3) piercing damage.

Problems:
- "reach 5 ft" should be "reach 1.5 m", when on the metric setting
- Range "4.5/18 ft" should be either "15/60 ft" or "4.5/18 m". currently it's bugged like this regardless of metric setting

**Comment by mlenser** [comment]
Fixed reaches and ranges for monsters, companions, and weapons
