### ISSUE TITLE
Lore skill for some Background Livelihoods

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#625]
Following the recent addition of the Lore skill:

- Entertainer should lose Performance (it's not a real skill anymore).  Instead, it can have Lore (at least one of Legends, Civilization, Art, Circus, etc.)
- Faction Agent could have Lore (at least one faction) instead of one of the existing options or as an alternative
- Guild Artisan - can have Lore (at least one profession or guild) added to the list
- Noble - can make it "Your choice of Coercion or Persuasion, and Lore (at least one of Civilization, Heraldry, Genealogy)"
- Hermit - could add Lore to the list 
- Monster Hunter - I think it can be better worded as "You are capable with Lore, choosing the Creature subcategory twice."
- Sage - should definitely add Lore to the list
- Sailor - can add to the list as a choice:  Lore (at least one Sailing)
- Soldier - can add to the list:  Lore (at least one Warfare)

**Comment by mlenser** [comment]
> I think it can be better worded as "You are capable with Lore, choosing the Creature subcategory twice."

It's an array of objects so for the sake of not reworking it I'll keep it the same.

**Comment by mlenser** [comment]
Added Lore to many livelihoods
