### ISSUE TITLE
Consider simplifying/improving rule for multiple concoctions, maneuvers, or spells on a turn

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#626]
Currently in <https://www.kryxrpg.com/rules/concoctions-maneuvers-and-spells> the rule is phrased like this:
> If you create a concoction, use a maneuver, or cast a spell that costs mana, the catalysts limit, dice limit, mana limit, or psi limit of any other concoction you create, maneuver you use, or spell you cast this turn is 2 lower than your normal limit. If 2 lower than your normal limit is 0 or less, then you cannot create another concoction, use another maneuver, or cast another spell unless that spell is a cantrip.

- This is very verbose.
- This has weird ordering: you can cast a 5-mana-spell and then a 3-mana-spell, but you can't cast a 1 mana spell and then a 4 mana spell.  That's unintuitive, as the order in which you expend resources shouldn't matter like that.
- It allows 3 mana + 1 mana, but not 2 mana + 2 mana, which wouldn't be unbalanced to allow.
- Casting a spell reduces your maneuver limit and so on - which hurts gishes a lot.  Their limits are already reduced to half the limits of pure spellcasters/martials, so I don't think there's need to also prevent them from using spell+maneuver in a single turn, from a balance perspective.  Thematically, using one spell and one maneuver during your turn feels flavorful.

I suggest changing it to:
> If you cast multiple spells in one turn, you cannot spend more mana in total than your mana limit or psi limit.
> The same rule applies to concoctions and maneuvers, preventing you from spending more catalysts than your catalyst limit or more stamina dice than your dice limit.

This will nerf high level (13+) casters - they can no longer spend 6+ mana in a single turn - but I think that's for the best, and if it's a big concern they could get special features/feats that slightly increases this limit.

More importantly, it will allow lower level casters to cast two 1-mana spells (action + bonus) instead of a single 2-mana spell, which is fitting for their power level and allows more versatility.  The same will happen with martial characters - a 5th level warrior could spend 1 stamina on Grievous Wound, kill the enemy, and then spend 1 stamina on Fountain of Blood.

**Comment by mlenser** [comment]
> I don't think there's need to also prevent them from using spell+maneuver in a single turn, from a balance perspective.

There is. Maneuvers and spells are both bursty. Allowing both would be far more than a martial could do or a spellcaster could do. Gishes shouldn't be be ultimate bursters.

**Comment by mlenser** [comment]
> - This has weird ordering
> - It allows 3 mana + 1 mana, but not 2 mana + 2 mana

These are worth solving though. Not sure how it can be worded, but "The same rule applies to concoctions and maneuvers" is not a good way to word it and it wouldn't capture the fact that the total amount used must be less than your limit.

Perhaps you have a better way to word it.

**Comment by itamarcu** [comment]
> Allowing both would be far more than a martial could do or a spellcaster could do.

True, I forgot that their stamina dice still go up to 5, so it'd enable a lot of burst (5 stamina + 3 mana).

This isn't exactly the same, but it's close, and pretty elegant:

> You cannot spend a combined amount of mana, psi, stamina, or catalysts in a single turn that is greater than your proficiency bonus.

At tier 5 it will allow using 5+1 mana, 3+3 stamina, or combinations of them - which is close to the current maximum (slightly less).  It will only be a bit strong at tier 1, as characters will be able to use two 1-resource spells/maneuvers in a single turn.

We could reduce it (and the elegance) by making it:

> You cannot spend a combined amount of mana, psi, stamina, or catalysts in a single turn that is greater than your proficiency bonus minus 1 (which is your level divided by four).

**Comment by mlenser** [comment]
You cannot spend a combined amount of catalysts, mana, psi, or stamina dice on your turn greater than your highest limit
