### ISSUE TITLE
Fire should be effective against Ice Elementals

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#627]
The elementals have a bit of a cycle:
- [Fire Elementals](https://www.kryxrpg.com/monsters/small-fire-elemental) have:
> ***Water Susceptibility***. For every 1.5 meters the elemental moves in water, or for every 4 liters of water splashed on it, it takes 1 cold damage.
- [Water Elementals](https://www.kryxrpg.com/monsters/small-water-elemental) have
> ***Freeze***. If the elemental takes cold damage, it partially freezes; its speed is reduced by 6 meters until the end of its next turn.

I think it's both fair and thematic for Ice Elementals to have:
> ***Thaw***. If the elemental takes fire damage, it becomes partially thawed; its speed is reduced by 6 meters until the end of its next turn.

(could make it take damage instead, or get a different condition, e.g. staggered, poisoned, slowed... whatever feels right)

It should be noted that the D&D 5e Ice Mephits (similar creature) had Vulnerability to Fire;  I think replacing vulnerability with an effect like this is better for the game.

**Comment by mlenser** [comment]
I made them vulnerable to fire damage as part of #543

> I think replacing vulnerability with an effect like this is better for the game.

I don't think slowing down really captures it though. Vulnerability feels right here as part of their body melts.

**Comment by itamarcu** [comment]
Alright.  And maybe they could be immune to the Burning condition?  Ice can definitely melt, but it can't burn.  It will still make Fire super effective overall, but a constant source of fire damage will be more effective than a few short hot bursts (which I think makes the most sense).

**Comment by mlenser** [comment]
We should probably identify more creatures that are immune to burning. Fire elementals, Water Elementals, Ice Elementals, Phoenix, etc. Maybe you could browse through and help?

Should also do the same for Staggered, but that can be done separately.

**Comment by mlenser** [comment]
Earth and Ice elementals are immune to the burning condition

**Comment by itamarcu** [comment]
Creatures that should also be immune to burning:
- Most elementals: obviously fire (e.g. Fire Snake) and water (e.g. Water Weird), but also other elementals that don't make sense to burn:  Earth, Ice, Sand, Lightning.  (Air and Acid could still be burnable)
- Most constructs - those that are made from metal, stone, clay, etc.  A full list:  Animated Armor, Bronze Scout, 
Clay Golem, Duodrone, Flying Sword, Hellfire Engine, Helmed Horror, Iron Cobra, Iron Golem, Marut, Mindcrystal, Monodrone, Retriever, Sacred Statue, Steel Predator, Stone Cursed, Stone Defender, Stone Golem

Should be vulnerable to fire and aren't already:
- Rug of Smothering

Also, perhaps the [Slick Skin](https://www.kryxrpg.com/spells/slick-skin) spell could grant advantage on saving throws against Burning, similar to how Wave Shield grants it and similar to how Mage Armor grants resistance to force damage.

**Comment by mlenser** [comment]
Regarding constructs: if they can take fire damage then they should be able to burn.

**Comment by mlenser** [comment]
All monsters that are immune to fire damage and immune to the burning condition.

**Comment by mlenser** [comment]
Rug of smothering is vulnerable to fire damage

**Comment by mlenser** [comment]
Slick Skin now gives the target advantage on saving throws against the burning condition
