### ISSUE TITLE
Blink's roll can be simplified a bit

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#628]
https://www.kryxrpg.com/spells/blink

Currently you roll a 1d20 or 2d10, and blink on a roll of 16+/14+, 11+/11+, or 6+/8+.

Functionally, it's just 25%, 50%, 75%.

Therefore, it can be simplified - roll a 1d4, and vanish if you roll 4.  with the augments you also vanish if you roll 3 or if you roll 2.

**Comment by mlenser** [comment]
Blink reworked to use a d4
