### ISSUE TITLE
A few small improvements to class feature page

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#629]
![image](https://user-images.githubusercontent.com/6516621/101323030-b0e19b00-3870-11eb-9340-ea4e435af646.png)

Examples taken from the [Magus](https://kryxrpg-2actions.gtsb.io/character/classes/mage) page.
1. Mentions of the specific class level can be removed - multiclassing is not allowed, so "gain a level" is clear enough.
2. The paragraph about replacing cantrips and spells is very long, so I think it should be in its own header, especially because the first sentence is the most important and the rest of the sentence draws attention away from it.
3. Not shown in the picture, but... shouldn't the Magus (and other half-half gishes) be able to replace **maneuvers** on level-ups, too?  it's probably intended but not written.

**Comment by mlenser** [comment]
removed class name from features that refer to level
