### ISSUE TITLE
Paladin and Avenger monsters

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#63]
##### _(Note: it's the good paladin. I didn't call it Paladin because, by the rules, paladins can be evil)_
_Medium humanoid (any race), any non-evil alignment_
**Armor Class:** 20 (plate, shield), **Hit Points:** 153 (18d8 + 72)
**Speed:** 30 ft.

**STR:** 18 (+4), **DEX:** 11 (+0), **CON:** 18 (+4), **INT:** 11 (+0), **WIS:** 14 (+2), **CHA:** 15 (+2)

**Saving Throws**
**Fortitude:** +4, **Reflex:** +2, **Will:** +5

**Skills**
**Athletics:** +7, **Persuasion:** +5, **Religion:** +4

**Senses:** passive Perception 12
**Languages:** any one language (usually Common)
**Challenge:** 8 (3,900 XP)

---

**Dashing Strike.** If the holy knight uses its action to Dash, it can use a bonus action to make one melee weapon attack or shove a creature.

**Aura of Protection**. The holy knight and each friendly creature within 30 feet of it who can see or hear it has advantage on saving throws. _(note: this is stronger than the PC's version, but numeric bonuses are not the norm, so I allowed the NPC to have a stronger but simpler aura)_

#### Maneuvers (limit 3; Courage, Protection):
**1 stamina die:** avert blow, covering strike, incite, inspire, rally, sacrifice, unwavering mark
**2 stamina dice:** commander's strike, disarm, vengeance
**3 stamina dice:** battle leader, clarion call

#### Spellcasting (limit 3; Holy, Life, Light):
**Cantrips:** guidance, radiance, resistance, spare the dying
**1 mana:** aid, bless, blinding light, daybreak weapon, daylight, detect evil and good, guiding bolt, heal, protection from evil and good, sacred shield, shield of faith
**2 mana:** absorb pain, beacon of hope, corona of light, destructive wave, find steed, guardian of faith, holy nimbus, remove curse, restoration, summon celestial
**3 mana:** aura of purity, death ward

---

#### Actions
**Multiattack.** The holy knight makes three weapon attacks.
**Longsword.** Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) slashing damage.
**Shortsword.** Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage.
**Shortbow.** Ranged Weapon Attack: +3 to hit, range 60/300 ft., one target. Hit: 3 (1d6) piercing damage.

**Comment by Marcloure** [comment]
## Avenger
_Medium humanoid (any race), any alignment_
**Armor Class:** 17 ( ), **Hit Points:** 117 (18d8 + 72)
**Speed:** 30 ft.

**STR:** 11 (+0), **DEX:** 18 (+4), **CON:** 14 (+2), **INT:** 14 (+2), **WIS:** 17 (+3), **CHA:** 11 (+0)

**Saving Throws**
**Fortitude:** +2, **Reflex:** +6, **Will:** +6

**Skills**
**Acrobatics:** +8, **Perception:** +7, **Religion:** +7, **Stealth:** +8

**Senses:** passive Perception 17
**Languages:** any one language (usually Common)
**Challenge:** 9 (5,000 XP)

---

**Dashing Strike.** If the avenger uses its action to Dash, it can use a bonus action to make one melee weapon attack or shove a creature.

**Vow of Enmity (1/short rest).** As a bonus action, the avenger can utter a vow of enmity against a creature it can see within 60 feet of it. For 8 hours the avenger gains advantage on attack rolls against the creature or until the creature drops to 0 hit points or falls unconscious.

While the vow lasts, the creature’s general direction and distance from the avenger is revealed if the creature is within 5 miles of it.

#### Maneuvers (limit 3; Shadow, Skirmish):
**1 stamina die:** ambush, bait and switch, distant shot, fan of blades, impaling shot, nimble, nimble dodge, positioning strike, precision, stalking shadow, step of the wind, vault
**2 stamina dice:** blind, entangling shot, slashing blades, slice tendon

#### Spellcasting (limit 3; Divination, Holy, Light):
**Cantrips:** cloud senses, guidance, radiance, sacred flame
**1 mana:** blinding light, daybreak weapon, daylight, detect evil and good, exhort truth, faerie fire, guiding bolt, judge, locate, protection from evil and good, radiant rebuke, sunbeam
**2 mana:** burst with light, chains of light, clairvoyance, comprehend languages, corona of light, darkvision, destructive wave, flame strike, holy nimbus, seeing, spiritual weapon, sunburst
**3 mana:** ghostly gaze, past impressions

---

#### Actions
**Multiattack.** The avenger makes three falchion or longbow attacks. If it has a scimitar drawn, it can also make a scimitar attack.
**falchion.** Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) slashing damage.
**scimitar.** Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage.
**longbow.** Ranged Weapon Attack: +8 to hit, range 60/300 ft., one target. Hit: 8 (1d8+4) piercing damage.

**Comment by mlenser** [comment]
Naming it Paladin as a Priest could also be any alignment, this is just a "typical" paladin, same as Avenger would be the typical version.
Giving it the Courage and Protection maneuver themes and Holy and Life spell themes. Light could fit, but that's a lot and not super typical for a paladin. More of a Priest thing I think.

**Comment by mlenser** [comment]
Avenger has the Skirmish and Shadow maneuver themes and Divination and Holy spell themes. Light could be fitting, but again I'd say isn't core to the Avenger.

**Comment by mlenser** [comment]
- Added spells to the Acolyte and Priest. Priest changed from challenge 2 to 8 and Acolyte changed from challenge 1/4 to 2. Convert added to take the place of the Acolyte.
- Added a Paladin to mirror Blackguard
- Added an Avenger
