### ISSUE TITLE
Maneuvers-only Ranger has features that assume it can cast spells

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#630]
I don't know how to fix it, but the [Ranger](https://www.kryxrpg.com/character/classes/naturalist) has no spellcasting or spell save DC, and yet these exist:

- > Some Primal Call effects require saving throws. When you use such an effect from this class, the DC equals your spell save DC.
- a bunch of things like "You can cast rebuke the defilers augmented to your mana limit without expending mana." 
- in Ancient Power, 3 of the 4 abilities you get require you to cast spells or have a spell save DC

**Comment by mlenser** [comment]
Acolyte, Minstel, and Naturalist has wording such as:
- If you do not have a spell save DC, the DC is 8 + your proficiency bonus + your Wisdom
- If you have mana, you can augment it further by expending mana.
