### ISSUE TITLE
Refine familiarity requirements

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#631]
- Familiarity should be the total amount of feats, concoctions, maneuvers, and spells a character has from a theme.
- The familiarity limits for maneuvers (on usage and enhancing) should include fighting styles
- ~~Cantrips getting better should be limited by familiarity~~
- ~~Feat choices should be limited by familiarity~~

**Comment by itamarcu** [comment]
> Feat choices should be limited by familiarity

Not sure about this... I agree on principle, but I don't know how we can implement this in an elegant way.

Also, some themes don't have enough feats/maneuvers right now, which might make the limit annoying.  For example, [Sand](https://www.kryxrpg.com/themes/sand) has cool feats - Grounded (6th) and Sand Burrow (14th) - but a character build of a "desert warrior" would probably be unable to get these (depending on rule implementation).  Of course, that's less of a reason to avoid this change, and more of a reason to add more content..!

**Comment by mlenser** [comment]
I believe you're right. The limit shouldn't apply to feats, but feats should add to "familiarity"

**Comment by itamarcu** [comment]
Possibly a bad idea, but... what if we introduce character tiers as an actual mechanic?  I think it will make wording smoother. Tiers are already mentioned in [How to Make a Character](https://www.kryxrpg.com/character/how-to), and yes, they explicitly say they have no rules associated with them, and yet... maybe they should?

---

# Tiers of Play
Your character's tier is a representation of your personal power, training, experience, and potential.  Your tier ranges between 1 (first tier) to 5 (fifth tier), as mentioned in *How to Make a Character*.

You cannot spend more catalysts, mana, psi, or stamina than your Tier during a single turn.

# Familiarity
Characters have a different levels of experience with different fields.  

Your character's Familiarity with a theme is the amount of your concoctions, maneuvers, spells (including cantrips), feats, and fighting styles that belong to the theme.  A Familiarity of 5 or more implies you are well-versed in that theme, and can use it to the fullest extent.

You cannot spend more catalysts, mana, psi, or stamina than your Familiarity with the theme the concoction, maneuver, or spell belongs to (if it belongs to multiple themes, you only need to be familiar with one of them).

Your cantrips become stronger at each tier, as mentioned in their description; however, a cantrip cannot grant you the benefit of a tier higher than your Familiarity with that cantrip's theme.

For example, Ariastus is an 18th level Mage (Magus) who specializes in Fire spells (Familiarity 7) and dabbles with Light and Shadow magic (Familiarity 2 for each). He can cast his *fireball* by spending 3 mana on the spell, and when he casts *produce flame* his attack deals 5d8 fire damage. However, he cannot augment his *darkness* spell to a cost greater than 2 mana, and when he casts *sunray* it will only deal 2d4 radiant damage to creatures around him.


---

Cantrips currently look like this:
> This spell’s damage increases by 1d6 when you reach 5th level (2d6), 9th level (3d6), 13th level (4d6), and 17th level (5d6).

And will change to:
> This spell’s damage increases by 1d6 when you reach the second tier (2d6), third tier (3d6), fourth tier (4d6), and fifth tier (5d6).

**Comment by Paulorpribeiro** [comment]
At this point, I think it may be better to just note your familiarity next to the themes you know on the character sheet, and modify it (If needed) at every level up.
You would have for example
Ariastus (wizard)
Known themes:
Fire 7
Light 2
Shadow 2

Its a little more work, but very streamlined and logic.

**Comment by mlenser** [comment]
- Classes must know a number of feats, concoctions, fighting styles, maneuvers, or spells to learn new concoctions, maneuvers, or spells now. This is easier than the previous requirement
- Augmenting or enhancing concoctions, maneuvers, or spells no longer requires any familiarity

This way still keeps some familiarity, but it only matters when learning new powers
