### ISSUE TITLE
Rework Knockout to be more thematic

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#632]
Currently, [Knockout](https://www.kryxrpg.com/maneuvers/knockout) is balanced, but it doesn't feel true to its name.

- It makes the victim incapacitated, instead of unconscious
- It deals extra damage to the victim

This basically prevents a creature from fighting back, and the damage helps you and your party finish it off earlier.

The flavor of knocking someone out is almost never like that; it's usually about one of these things:
1. quickly putting someone down before getting away; for example to dispatch a guard before that guard activates the alarm or shouts a warning
2. non-lethally ending a fight, with the intention of keeping the person alive;  usually the victim is tied up or restrained afterwards
3. temporarily disabling someone, to stop them from participating in combat, while other threats are handled

Note that none of these really involve dealing more damage to the target.  Though, frequently the knockout happens to creatures who are either low-threat (guards, goons...) or hurt (big boss after several rounds of combat).

So I suggest changing the maneuver to be like this (based on [Sleep](https://www.kryxrpg.com/spells/sleep)):

> As a bonus action when you hit a creature with a melee weapon attack that deals bludgeoning damage, you knock the target out. The target must make a Fortitude saving throw.  **If it is below half of its health maximum, it makes this saving throw with disadvantage.**
On a failed save, ~~add one stamina die to the attack’s damage roll and~~ the target is **unconscious** for the duration.
~~A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.~~
**This effect ends for a creature if it takes damage or someone uses an action to shake or slap it awake. Additionally, a creature can repeat the saving throw each minute or if it hears an extraordinarily loud noise such as the *thunderwave* spell, ending the effect on itself on a success.**
**Undead aren’t affected by this maneuver.**

small note - I added "if it's below 50% it has disadvantage on save" but this could just as well be "if it is above 50% it has advantage on the save".  This part and the stamina cost could be adjusted to keep this balanced.

**Comment by DalenWBrauner** [comment]
This sounds like a pretty different effect from the original, mechanically speaking. Maybe this should be its own maneuver (and we just rename this one), or this could be an augment of this one?

**Comment by itamarcu** [comment]
I don't really think there's a *need* for the original, to be fair.  There's already [Disorient](https://www.kryxrpg.com/maneuvers/disorient) which is nearly identical but at 1 stamina and with enhancements (1+1 stam for stagger, 1+3 stam for stun, 1+4 stam for paralyze).  If there's need for a maneuver that incapacitates, an extra enhancement can slot right in, for +2 stamina.  Duration could change for it or could be another enhancement.

But I do think there is a need for the maneuver I tried to design, because it's so common in stories for a dude to bonk a guard on the head and for the guard to drop down (without much physical damage being done).  The game already allows for "Knocking a Creature Out" instead of making a killing blow, but this maneuver allows a practiced expert to do it more easily with more versatility.

**Comment by mlenser** [comment]
This is a very different maneuver and the maneuver system has changed.

> it's so common in stories for a dude to bonk a guard on the head and for the guard to drop down

This is what Knockout does. It's not sleep, but what you propose is too strong I believe.

**Comment by itamarcu** [comment]
Please don't dismiss the idea and please read everything.

The maneuver system has changed, but that's irrelevant - the maneuver can still be like it is now, but without the extra damage and with the effect I mentioned.  It could even have the attack deal half or no damage.

The current Knockout maneuver simply doesn't fulfill its thematic purpose. An **incapacitated** creature is still aware of its surroundings, can still speak, is not prone, and will stop being incapacitated very quickly.

Knocking people **unconscious** is exactly what the maneuver should do.  It's a classic trope (["Tap on the Head"](https://tvtropes.org/pmwiki/pmwiki.php/Main/TapOnTheHead), ["Knockout Ambush"](https://tvtropes.org/pmwiki/pmwiki.php/Main/KnockoutAmbush)), and there's even other possible maneuvers that should reasonably exist and put people to sleep - like [Pressure Points](https://tvtropes.org/pmwiki/pmwiki.php/Main/PressurePoint) and [Choke Holds](https://tvtropes.org/pmwiki/pmwiki.php/Main/ChokeHolds).

Regarding actual balance - if it simply follows the standard sleep effect rules it can't be stronger than Sleep, which is already a low-resource spell that targets a weaker save and wouldn't have the advantage-if-above-half-health part.  If there's a risk of players using the maneuver to get an auto-crit next turn, the maneuver could just be adjusted to avoid that (e.g. by making the initial attack deal very little damage, or costing 3 instead of 2 stamina).

**Comment by mlenser** [comment]
It's a classic trope that is completely unrealistic. Choking someone out and they are then asleep for an extended period of time is not realistic. Knocking someone out is already covered in the rules: Reduce their hit points to 0 and choose to not kill them.

Choking someone out or one knock on the head and they're out for a while? Unrealistic.

**Comment by itamarcu** [comment]
> Unrealistic

If realism is the goal of the system, perhaps we should also remove spellcasting...

I think "thematics first" is a better principle than "realism first", and knocking someone out without almost killing them feels thematic to me ¯\\\_(ツ)\_/¯

Either way, if the target gets to save each minute, it probably won't be a very extended period of time.  I just think it should be enough to allow for the common usage:  preventing a guard from announcing your presence, kidnapping a victim, neutralizing an ally who acts against you, or buying yourself time to escape.

> Choking someone out

Actually, this is part of the existing rules, in a way - a creature that suffocates for a number of rounds and then fails its Constitution check will drop to 0 health and begin dying.  You'd have to stabilize the creature if you want it to surive afterwards, but at least it's already possible (with the GM having to decide what counts as suffocation/choking;  I think I'd probably require a player to grapple the enemy and spend each turn making a Brawl check to keep blocking airflow).

**Comment by mlenser** [comment]
> If realism is the goal of the system

Realism is part of the maneuver system. That was a community decision which I agree with.

No need to be sarcastic or combative..
