### ISSUE TITLE
Trace Teleport's DC could be increased

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#633]
https://kryxrpg-2actions.gtsb.io/spells/trace-teleport

> The DC equals 10 + the mana or psi expended.

This could be twice the effective mana, instead - and would be more consistent with Counterspell, Metafaculty, etc.

**Comment by mlenser** [comment]
Trace Teleport changed to use Arcana or Psionics check and the DC is increased
