### ISSUE TITLE
Locate spells - realignment and augment suggestions

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#634]
## Locate spells - realignment
- [Locate Animals](https://kryxrpg.com/spells/locate-animals) - 1 mana, ritual, 10 km range
- [Locate Plants](https://kryxrpg.com/spells/locate-plants) - 1 mana, ritual, 10 km range
- [Locate Water](https://kryxrpg.com/spells/locate-water) - 1 mana, ritual, 10 km range
- [Locate Gate](https://kryxrpg.com/spells/locate-gate) - **2 mana**, **not a ritual**, **2 km** range.  These should be changed to be like the others.  Also, the second paragraph about the limitations should be either removed from here or added to all the Locate spells.
- [Detect Portal](https://kryxrpg.com/spells/detect-portal) - 1 mana, **not a ritual**, **2 km** range.  Should be changed too, and spell should be renamed "Locate Portal".
- [Locate](https://kryxrpg.com/spells/locate) - 1 mana, ritual, 360 m range.  I think this spell is good the way it is, because it's a special case that has much more versatility.

## Locate spells - augments
I think these spells should allow augmenting them to increase the range.  It's not super powerful, as the range is already quite large, but it certain situations it'll help - and it definitely fits with the basic concept of more powerful spellcasters being able to achieve a greater effect of the same kind.
I think the augment should be exponential:  20 km for 2 mana, 50 km for 3 mana, 100 km for 4 mana, 200 km for 5 mana.
For non-metric (5 miles currently) it can be:  10 miles, 20 miles, 50 miles, 100 miles.

## Detect spells - augments?
Maybe similar augments could be added to spells like Detect Magic, Detect Poison, Detect Death, etc;  though these have much smaller ranges so the augments would be a different.

**Comment by mlenser** [comment]
- Nondetection blocks locate spells
- Locate Portal is now a ritual like other locate spells
- Locate Portal wording cleaned up to only specify that it is blocked by forbiddance as nondetection is covered in its spellcate Portal

Locate Portal is also unique - I think 2km range is best here.


> I think these spells should allow augmenting them to increase the range. It's not super powerful, as the range is already quite large, but it certain situations it'll help - and it definitely fits with the basic concept of more powerful spellcasters being able to achieve a greater effect of the same kind.

Not sure I'm in favor of this. The range is long by default. If we scale then the range should be significantly shortened. I'd rather keep it as is.
