### ISSUE TITLE
Item weights have non-metric amounts for metric units

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#636]
https://www.kryxrpg.com/equipment/weapons

I think all the weapons have mostly kept their numbers but changed their unit.  For example, in D&D 5e, Club = 2 lb and Dagger = 1 lb, but now in KryxRPG Club = 2 kg and Dagger = 1 kg.

These should all be fixed.  It's okay if the final numbers aren't all exactly the same as the originals (because we want round kg amounts too), but they should at least be within ~25% of the original weights.  For example, a Dart should be 0.1133 kg - so setting it to 0.1 kg or to ⅛ kg would both be fine.

**Comment by mlenser** [comment]
I didn't convert weapons weights from imperial to metric when I defaulted to metric. Will fix for weapons and check others like armor and alchemical creations.

**Comment by mlenser** [comment]
All weights have been adjusted so they are correct with metric and imperial units
