### ISSUE TITLE
Two near-identical Life feats

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#638]
There's a "Healer" feat and a "Doctor" feat, both identical except that the Healer feat has additional benefits for Healer's kits.

![unknown-5](https://user-images.githubusercontent.com/3477032/101979665-f31e2a00-3c2c-11eb-9b45-8cae96278e37.png)

I'd vote for keeping the Healer feat and tossing out the Doctor one. Could also rename Healer to something less generic, considering it's specifically about medical healing and not anything magical (unlike, say, the spell Heal).

**Comment by itamarcu** [comment]
Potential names:
- Healer
- Doctor
- Medic / Field Medic
- Surgeon / Field Surgeon
- First Aid Training
- Physician

**Comment by mlenser** [comment]
Healer feat renamed Chirurgeon
Doctor feat removed
