### ISSUE TITLE
Avalanche Onslaught augment power

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#64]
I think there is something wrong with the power balance of this maneuver.

The spreadsheet considers the augment die to be 1d4, is that correct?

I ask this  because I found "you continue until you miss" to be quite powerful. At my table, the Battlemaster player (with a +9 to hit) used this maneuver augmented to 3 stamina dice against a Veteran (17 AC). The player dealt 2d8 damage per hit, adding up to around 30 damage before missing, that as a bonus action expending 3 stamina dice, and against a creature with relatively high AC.

If the target was a lower AC monster (like a beast, caster, or zombie), the player could have killed it with one action+bonus, no matter how much HP it has. 

Maybe it was just luck, since I think a character has around 27% of chance to hit 3 attacks with 35% of chance to hit, but I think my concern is still valid. Against lower AC targets or if you gain at least an one-turn advantage (since you make all attacks on the same turn), you can destroy much of anything.

**Comment by mlenser** [comment]
It was 1d4 due to "You can increase the damage for every **other** additional stamina die expended"

**Comment by mlenser** [comment]
Avalanche Onslaught reworked to be 1 extra attack per die
