### ISSUE TITLE
Arc Lightning augment clarification

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#642]
> If you expend 2 or more mana, you can create one additional tendril and the damage for each tendril increases by 1d6 for each additional mana or psi expended.

First time I read it, I thought you gained (1 tendril and +1d6) * additional mana, not 1 tendril and (+1d6) * additional mana. I had to check the sheet to make sure that was not it.

The text can be clarified as such:

"If you expend 2 or more mana, you can create one additional tendril. Additionally, the damage for each tendril increases by 1d6 for each additional mana or psi expended."

**Comment by Marcloure** [comment]
So, the sheet has this observation on the spell's augment:
> 7d6 per mana:
> 1d6 = another tendril (6)
> 6d6 = 1d6 * 6 tendrils

But that is only true for the first augment. The next augment increases the spell's damage either by:
> 8d6 (then 9d6, 1d10, etc):
> 1d6 = another tendril (7)
> 7d6 = 1d6 * 7 tendrils

or by:
> 6d6 = 1d6 * 6 tendrils

**Comment by mlenser** [comment]
fixed wording

> You can increase the damage of each tendril by 1d6 for each additional mana or psi expended.
>
> If you expend 2 or more mana, you can create one additional tendril.

**Comment by Marcloure** [comment]
The spreadsheet still considers arc lightning grows 7d6 per level, when it's actually 6d6 past 2 mana (the 1d6 = another tendril (6) only happens once).

**Comment by mlenser** [comment]
Updated the sheet to be more accurate. It's still within the normal bounds.
![image](https://user-images.githubusercontent.com/235857/102042077-492bd280-3dd1-11eb-8422-a1c352d9aa64.png)

**Comment by mlenser** [comment]
Arc Lightning changed to add more tendrils of lightning
