### ISSUE TITLE
Restoration and Heal do the same thing

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#643]
https://www.kryxrpg.com/spells/restoration

https://www.kryxrpg.com/spells/heal (the Cure augment)

I think that Heal's "Cure" augment should be removed.

**Comment by DalenWBrauner** [comment]
I also think that the second paragraph of Heal's "Major Regeneration" augment should instead be an augment of Restoration. This paragraph:
> The target’s severed body members (fingers, legs, tails, and so on), if any, are restored after 2 minutes. If you have the severed part and hold it to the stump, the spell instantaneously causes the limb to knit to the stump.

Feels more in-line with Restoration's restorative effects, rather than straight healing, and would help differentiate the two spells.

**Comment by mlenser** [comment]
Heal's Cure does not remove Paralyzed and it has no way of removing the issues that Greater Restoration fixes.

**Comment by mlenser** [comment]
> I also think that the second paragraph of Heal's "Major Regeneration" augment should instead be an augment of Restoration. 

Restoration is not about healing wounds, that is what Heal is for.

**Comment by mlenser** [comment]
Heal’s Cure augment no longer removed the blinded or deafened conditions
