### ISSUE TITLE
Rift cantrip needing to be standardised 

### ISSUE THREAD

**Issue by DemiurgeJ** [mlenser/kryx-rpg-issues#644]
The second paragraph for the [Rift cantrip](https://www.kryxrpg.com/spells/rift) should be standardized due to having an Augment effect.

This is the paragraph as it currently is "_The rift is not stable enough for energy such as alchemical explosions or magic to pass through it, but you can expend 1 mana or psi when you cast this cantrip to stabilize the rift so energy can pass through it._"

I advise separating this by having "_The rift is not stable enough for energy such as alchemical explosions or magic to pass through it_" at the end of the spell description, then add the Augment tag for "_You can expend 1 mana or psi when you cast this cantrip to stabilize the rift so alchemical explosions and magic effects can pass through it_."

**Comment by itamarcu** [comment]
Another possibility:  make it an ability you unlock at a higher level (like how other cantrips scale).

**Comment by mlenser** [comment]
Rift Cantrip changed to get this effect at 9th level
