### ISSUE TITLE
Reincarnate generic species names

### ISSUE THREAD

**Issue by DemiurgeJ** [mlenser/kryx-rpg-issues#645]
The site uses the names Tabaxi and Triton on the species page but calls them "Catfolk" and "Gillmen" in the [Reincarnation](https://www.kryxrpg.com/spells/reincarnate) spell, which is a slight dissonance. I would advise settling on using the generic names or the specific names. I would lean towards the specific names.

**Comment by mlenser** [comment]
Reincarnate reallocated to the current species
![image](https://user-images.githubusercontent.com/235857/102024467-802ec380-3d92-11eb-9bb0-ecfc3e3a01c0.png)
