### ISSUE TITLE
Mighty Summoner feat references Magic b/p/s Resistance

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#646]
https://www.kryxrpg.com/feats/mighty-summoner

> The damage from its natural weapons is considered magical for the purpose of overcoming immunity and resistance to nonmagical attacks and damage.

This was useful when there was generic resistance to nonmagical b/p/s, but that no longer exists.

Should they simply deal more damage, or overcome Soak? Or perhaps you could choose to summon a creature whose natural weapons are considered to be made of Obsidian or something?

**Comment by DalenWBrauner** [comment]
Also, I'm pretty sure there are other "Summoner" feats, which might have the same issue.

**Comment by mlenser** [comment]
> This was useful when there was generic resistance to nonmagical b/p/s, but that no longer exists.

It still exists, just is more rare.
