### ISSUE TITLE
Rogue - Slippery Mind

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#647]
The [Rogue](https://kryxrpg.com/character/classes/rogue) gets Slippery Mind at 13th level:
> You have acquired greater mental strength. You gain proficiency in Will saving throws.

However, the Rogue already gets the standard saving throw improvement at levels 1, 5, and 9, which all allow the Rogue to gain Capable (or Proficient) in Will saving throws.  If a rogue does that, this feature will be wasted at 13th level.  This creates a weird incentive for all rogues to be bad at will saving throws for most of their career, for long-term efficiency.

This feature should be changed to prevent that.  Perhaps it could be advantage on Will saving throws, or the ability to automatically succeed or reroll one Will save every day.  It could also be replaced with something completely different.

**Comment by mlenser** [comment]
Slippery Mind changed to reroll Will saving throws
