### ISSUE TITLE
Rogue - Use Magic Device

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#648]
The [Rogue](https://www.kryxrpg.com/character/classes/rogue) gets Use Magic Device at 9th level:
> You have learned enough about the workings of magic that you can improvise the use of items even when they are not intended for you. You ignore all species, class, and level requirements on the use of magic items.

However, there are no species, class, or level requirements on any of the magic items mentioned in the [Magic Items](https://www.kryxrpg.com/equipment/magic-items).  Also, this is a feature that balances the system around the existence of magic items, which is not something we should do.

I suggest removing this feature and possibly adding something else instead if needed.

**Comment by mlenser** [comment]
The list of magic items is not all magic items ever. There are many that I chose not to include due to copyright concerns and items that GMs can make.

UMD comes from the Thief subclass in RAW. I think it is mostly a ribbon feature, but could be nice for rare cases.
