### ISSUE TITLE
Scaling suggestions for utility cantrips

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#649]
I have some scaling ideas for lots of cantrips, so I'll just write them all in here instead of creating dozens of tickets.  The exact levels of scaling aren't that important.  Currently cantrips scale every 4 levels (starting at 5), but soon they'll start scaling at 9th level due to the 2-action system.  My suggestions here assume scaling at 9th level, but it's flexible and doesn't really matter for combat.  As an example of an existing utility cantrip that scales:  the Message cantrip lets you send the message to all creatures within range, at 9th level.  Spare the Dying has even more stuff.

### Effects at higher levels that can be added:

- Animal Friendship - Duration is increased to 1 hour (from 1 minute).
- Bone Blade, Crimson Blade, Scythe, etc - Allow making an attack with the weapon as part of the same action.
- Dancing Lights - no longer requires concentration.
- Druidcraft:  the size of the harmless sensory effect increases (from 1.5 cube to bigger cube).
- Earthen Hide - maybe the Soak number could increase at higher levels?  (not sure)
- Hidden Pocket - you can have 2 objects hidden this way, or the object weight limit is increased, or you can summon it back without spending an action.  (also, it doesn't need to specify "or weapon" in its description, weapons are already objects)
- Illuminate - the radius increases (from 6m to 9m, 12m, 15m, etc?)
- Light Step - perhaps increase the movement speed further, or perhaps allow you to affect allies?
- Mending - change casting time from 1 minute to 2 actions or 1 action.
- Poison - allow you to cast the spell on food or drink, which will make any creature that ingests it within the next 5 minutes to make the save.
- Radiance - you may have the spell emit bright light at a radius around you that lasts until the start of your next turn.
- Sunray - similarly, can make the target creature shine with light for a round if it gets hit., or shine light around the area.
- Rift - The rift lasts until the start/end of your next turn (instead of current turn).  Alternatives:  allow spell effects without extra mana, or allow creating the rift as a reaction (without the attack).

**Comment by mlenser** [comment]
I did some of these as part of 2 actions

Some discussions points
- Animal Friendship is not Animal Companion. It is meant to be minor. I don't think 1 hour is a good choice
- Bone blade, etc: done
- Dancing lights is not meant to take the place of other options that are 1 mana spells. Concentration is the biggest limiting factor in that regard so it should stay
- Increasing the size of Druidcraft would only impact one option and that option increasign in size doesn't really make a difference
- Earthen Hide: Soak is almost always 1-3. Feats give +2 (max 3) and rare monsters have 4 or 5. This shouldn't be increased
- Hidden pocket; has higher level effects from 2 actions
- Illuminate: See Dancing Lights. This can't compete with 1 mana spells
- Light Step is gone
- Mending is meant to take a while Make whole is how it would be done quicker. This should not step on a 1 mana spell's toes
- Poisoning food is covered by the 1 mana spell Putrefy Food and Drink. This cantrip should not do the same thing
- Radiance already gets better?
- Sunray already gets better?
- Rift done as part of 2 mana

Closing this as I think most of these are done or won't do. Feel free to suggest any others in a new issue.
