### ISSUE TITLE
Proficiency Bonus rules can be shortened

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#650]
From the Rules page:
> Your proficiency bonus can’t be added to a single die roll or other number more than once. For example, if two different rules say you can add your proficiency bonus to a Will saving throw, you nevertheless add the bonus only once when you make the save.

> Occasionally, your proficiency bonus might be divided (halved, for example) before you apply it. If a circumstance suggests that your proficiency bonus applies more than once to the same roll, you still add it only once and divide it only once.

I'm pretty sure both of these rules are unnecessary because there's no way for a character to add the proficiency bonus again to stuff.

The only ways I know of to add your proficiency bonus to anything are:

- Death to Undeath adds +P damage to your attacks
- Sentinel at Death’s Door heals +P health
- Undead Thralls adds +P damage for your minion damage

and none of these seem like they can stack, or can add to an ability that already includes your proficiency modifier.

**Comment by mlenser** [comment]
These exist by RAW so must be there for a reason
