### ISSUE TITLE
Talisman of the Sphere should be removed

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#651]
> [Talisman of the Sphere](https://www.kryxrpg.com/equipment/magic-items)
*Arcane, legendary (requires attunement)*
When you make an Arcana check to control a *sphere of annihilation* while you are holding this talisman, you double your proficiency bonus on the check. In addition, when you start your turn with control over a *sphere of annihilation*, you can use an action to levitate it 3 meters plus a number of additional feet equal to 10 × your Intelligence.

This legendary item can control objects that don't exist, letting you double your proficiency bonus even though the rules don't even allow you to multiply it by x1.5 anymore, and allows you to move an object a combined metric-plus-imperial distance, which can even be negative.

I think we can say goodbye to this 😅

**Comment by mlenser** [comment]
Sphere of Annihiliation does exist

**Comment by mlenser** [comment]
Talisman of the Sphere now gives advantage instead of double proficiency bonus
