### ISSUE TITLE
Combine Locate Gate and Detect Portal

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#652]
See https://github.com/mlenser/kryx-rpg-issues/issues/634 for some details

**Comment by mlenser** [comment]
Locate Gate renamed Locate Portal
Detect Portal removed in favor of Locate Portal

**Comment by DalenWBrauner** [comment]
Is the new combined spell able to:
> detect the distance and direction to the closest planar portal within 1
mile of you.
Or is it just the teleportation spell renamed?

If not- is there some other magical means of detecting a planar portal?

**Comment by mlenser** [comment]
@DalenWBrauner check the site and see :)

**Comment by DalenWBrauner** [comment]
Nice, looks good! Didn't realize it was already live :)
