### ISSUE TITLE
Webpage Title for Fighting Styles say "Feat"

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#654]
e.g. the [Defense](https://www.kryxrpg.com/fighting-styles/defense) fighting style is called a "feat" on the title of the page.
![image](https://user-images.githubusercontent.com/3477032/102863730-fec5d980-4400-11eb-9900-54066ef6f477.png)

**Comment by mlenser** [comment]
fixed page title
