### ISSUE TITLE
Sync duplication between Dampen Spell and Deflect spell

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#655]
Deflect Spell already does what Dampen Spell do. I think it would be bad to make Deflect Spell only work against attack spells, so I would be in favor of removing Dampen Spell.

**Comment by mlenser** [comment]
They are based on different models. I need to check similar spells and make sure there isn't an imbalance here.

**Comment by mlenser** [comment]
Dampen Spell is the same model as:
- Ancestral Blessing
- Conviction
- Twist Fate
- WIld Guesses

These add +2.5 to attack rolls, ability checks, or saving throws. Dampen Spell adds +2.5 vs saving throws against magic. It should be allowed on allies like the others.

Deflect Spell is similar to Shield type spells (+4 to Defense), but also adds +4 to saving throws. The augments are the same too. +4 vs a saving throw is too much.

## Actions
- Dampen should be changed to be usable on you or another creature
- Dampen Spell should absorb Deflect Spell and allow dampening an attack spell (+4 defense) or a save spell (+2.5).
- Move augments from Deflect to Dampen.

**Comment by Marcloure** [comment]
I think both can be combined, but I prefer the name Deflect Spell either way

**Comment by mlenser** [comment]
Deflect doesn't make sense except vs attacks.

**Comment by itamarcu** [comment]
Personally, when I hear "Deflect Spell" my immediate thought is "turn the spell against its caster". I'm in favor of what you wrote above, but I'd be *really* in favor of making Deflect Spell something like an enhanced Counterspell, that throws the effect back at the caster (probably for 3 mana).

**Comment by DalenWBrauner** [comment]
I'm gonna toss a vote against what Shem said- when you deflect a sword coming at you, you're knocking it aside, not back against your enemy.

**Comment by mlenser** [comment]
Knocking it back would be "Reflect Spell" and could be an option that only works while wielding a shield and against spells that are attacks/have a beam. Totally different.

**Comment by mlenser** [comment]
- Dampen Spell reworked to work against attacks and saving throws against you or nearby creatures
- Deflect Spell removed as Dampen spell covers the niche

**Comment by mlenser** [comment]
FYI, updating the other defensive spells is on my TODO.
