### ISSUE TITLE
Transposition's augments could be rebalanced a bit

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#657]
https://www.kryxrpg.com/spells/transposition

The basic spell lets you switch the positions of two creatures within 120 feet, with the extra 30 foot distance limit for the two creatures.

The first augment lets you reduce the limit a bit (+30 feet).

The second augment (Reposition) lets you completely ignore the limit AND move them anywhere (plus add more creatures later).

I suggest:
- change (buff) first augment to completely remove the 30 feet requirement
- change (nerf) second augment so that it requires 2 actions instead of 1 action, OR so the creatures have to be within 60 feet of their original positions
- change " A creature can’t be teleported to a space harmful to it" to "**An unwilling** creature can’t be teleported to a space harmful to it".

**Comment by DalenWBrauner** [comment]
I like the 3rd and 2nd changes, but would aim towards keeping it a simple 1Action spell. I'd suggest:
* Adding the "unwilling" line
* Changing the Reposition augment to require the new destination for a creature to be within 30ft (notable nerf, but more inline with the spell's power)
* Allow the range-increase augment to apply to Reposition.
This lets the spell scale a bit more nicely with itself.

I'm not sure whether the range increase augment should be buffed, but it probably shouldn't be full-on Range Removal.

**Comment by Marcloure** [comment]
Reposition should be an augment of Relocate now, I guess, since it's just targeting additional creatures.

**Comment by mlenser** [comment]
Reposition removed from Transposition as the most likely desires are to move 1 creature (Relocate) or swap two creatures (Transposition).

First augment distance increased to 18 meters.

**Comment by Marcloure** [comment]
Now, I dislike that solution. I have seen a player use Reposition many times, and its goal really is to reposition the battle units (both allies and enemies). Transposition does that partially, but without an augment to target additional creatures, it's not the same by far

**Comment by mlenser** [comment]
> without an augment to target additional creatures

Perhaps suggest that instead next time instead of saying "I dislike that solution".

**Comment by mlenser** [comment]
Added an augment to Relocate to target additional creatures
