### ISSUE TITLE
Abscond

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#658]
I think it would be good to have a teleport reaction spell that moves you away, particularly when you find yourself in a bad position (and you can't afford to wait until your turn arrives).

Examples:
- a warrior pushed you through a window and you're about to fall off of your wizard tower
- you tripped the wrong tripwire, and now a giant guillotine axe blade is swinging towards your neck
- an eagle swooped in and yanked you off the ground, carrying you away
- someone is throwing a boulder/fireball/barbarian at you
- you're being charged by a centaur

Mechanically, I think it should be a very short distance and only in limited situations, with augments increasing the distance or allowing for more situations (cheap to teleport after being hit, expensive to teleport before being hit).

A character could already spend 1 mana and an action readying a Teleportation spell, in some of these cases, so I hope the mechanical effect I'm trying to create here is sensible and matches its cost.

So, my suggestion:

# Abscond (1)
#### *(teleportation)*
As a reaction, which you take when you are moved or knocked prone, you can teleport up to 15 feet to an unoccupied space that you can see.

### Augment
- You can teleport up to an additional 15 feet for each additional mana or psi expended.
- You can expend 1 additional mana or psi to cast this spell as a reaction when you take damage, when another creature comes within 5 feet of you, or when you become grappled or restrained.
- You can expend 2 additional mana or psi to cast this spell as a reaction when you are attacked or when you are forced to make a Reflex saving throw. An attack automatically misses you if you teleport away, and you automatically succeed on the save if teleporting away would put you out of danger (at the GM's discretion).

**Comment by mlenser** [comment]
Seems like we should modify this spell instead of adding a new one for similar purposes.
![image](https://user-images.githubusercontent.com/235857/103105929-6c584c80-4631-11eb-83da-fc22c10b1efa.png)

**Comment by itamarcu** [comment]
I considered that, and it's possible, but I think MOOTS is very specific in its thematics and mechanics, and not in a way that matches my suggestion.  MOOTS gives you a Defense bonus, which remains for a whole round, and lets you teleport back to a space you've been to in the nearby past (so maybe it should even be a Time spell).  It doesn't help in any of the other situations I mentioned, so I felt like it's best to create a new spell and leave this one as it is.

**Comment by mlenser** [comment]
Both spells are effectively "As a reaction, you teleport out of the way of a bad thing". That should be 1 spell.

**Comment by mlenser** [comment]
This needs the same treatment as Dampen Spell. #655

**Comment by Marcloure** [comment]
Also, Invisibility has a better augment than One Thousand Steps (but at 2 mana): 

> **_Misty Escape._** You can expend 1 additional mana or psi to cast the spell as a reaction, which you use when you are hit by an attack. Change the duration to instantaneous. You can turn invisible and teleport up to 60 feet to an unoccupied space you can see. You halve the attack’s damage against you. You remain invisible until the start of your next turn or until you attack or cast a spell.

Note that halving the damage is the same as turning a hit into near miss, which is what gaining AC usually does.

**Comment by mlenser** [comment]
Misty Escape is 2 mana while Memory of One Thousand Steps. Halving damage is available in other spells as 1 mana.

**Comment by itamarcu** [comment]
What do you think about the basic structure of the suggestion?  Do the power levels of each augmented cost make sense? Are there other possible triggers that aren't covered but make sense for a teleporter to use?

To summarize:

- 1 mana to teleport after being moved/prone

- 2 mana to teleport after taking damage
- 2 mana to teleport out of restraints/grapple after being restrained/grappled
- 2 mana to teleport when a creature approaches you

- 3 mana to teleport when attacked before being hit (auto miss)
- 3 mana to teleport when making a Reflex save before being hit (auto save)

**Comment by mlenser** [comment]
Some thoughts:
- Auto-miss is not something I plan to ever include. Similar spells add more defense. This should do the same.
- Teleporting out of grapple/restrained should be harder if anything, not easier. I don't think that should be included.
- Teleporting out of a Reflex save is largely covered by damage. If it's avoiding a spell entirely then I'm not sure it is a good idea.

**Comment by mlenser** [comment]
Abscond added as a 1 mana reaction

We can adjust small things here or there if needed.

**Comment by itamarcu** [comment]
The implemented version seems pretty good!  It doesn't allow everything but it allows for the most fitting situations, which seems good enough.

Posting the screenshot here for posterity:

![image](https://user-images.githubusercontent.com/6516621/103171308-f253dd80-4853-11eb-88bd-5fb5b90abc98.png)

Personally, I think the +1d4 to Defense for a round isn't really necessary here, but I'm fine with it added to the spell as a balancing part. I guess a player could flavor this as the character continuing to teleport small distances when being hit, or the enemies confused by the sudden teleportation and so making their attacks with less intensity.

**Comment by mlenser** [comment]
Ya, I considered making all of these cases against a singular attack, but that would make them not so great.

**Comment by mlenser** [comment]
Actually, this moves you away which should make it impossible to attack you again in many situations.

I'll change this case to only work for a single attack.
