### ISSUE TITLE
Divination volatile power suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#659]
**_Divination._** The next attack roll, ability check, or saving throw you make until the end of your next turn gains a d4 bonus to the number rolled.

It's based on Fate volatile power

**Comment by mlenser** [comment]
Divination doesn't have a spell like Twist Fate. Adjusting dice results doesn't seem to fit the theme.

**Comment by Marcloure** [comment]
Hm, that is true. Seeing the future isn't part of Divination

**Comment by mlenser** [comment]
Closing this as Fate is the theme for seeing the future.
