### ISSUE TITLE
Antimagic volatile power suggestions

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#660]
_**Antimagic.**_ You gain a +1 bonus to saving throws against magic and a +1 bonus to Defense against spell attacks until the start of your next turn for every 3 power expended.

_**Antimagic.**_ A creature that you can touch or see within 30 feet must make a Will saving throw or loses 1 mana (if any) for every 3 power expended.

I think a Antimagic volatile power would be specially cool, but these were the best I could think of.

**Comment by mlenser** [comment]
> Antimagic. A creature that you can touch or see within 30 feet must make a Will saving throw or loses 1 mana (if any) for every 3 power expended.

Removing mana should be the sole domain of spells.

**Comment by mlenser** [comment]
Added an Antimagic Volatile Power option
