### ISSUE TITLE
Adjust 2 actions Sword Wraith

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#661]
The sword wraith and sword wraith commander have this bonus action:

> **_Martial Fury._** As a bonus action, the sword wraith can make one weapon attack. If it does so, attack rolls against it have advantage until the start of its next turn.

That was simply lost in the 2 actions conversion. Now the sword wraith is a CR 3 creature that makes 1 attack for 1d8+4 damage, which is pretty weak.

---

Now I'm curious, what happened to other bonus actions creatures have? I suppose you converted them into actions?

**Comment by mlenser** [comment]
It was adjusted to this with 2 actions

![image](https://user-images.githubusercontent.com/235857/103154890-3a62f980-479b-11eb-916a-b168bac1e2b6.png)

**Comment by mlenser** [comment]
2d8 (9) is equivalent to the longsword damage so it's the same value overall.
