### ISSUE TITLE
Improve Shadow Jaunt

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#662]
Shadow Jaunt was a teleport spell similar to Quick Teleport / Misty Step (bonus action for 9m), but now there isn't bonus action anymore, and the spell remains as 9m. It probably should be made the same as teleport (action for 36m)

**Comment by mlenser** [comment]
Shadow Jaunt is now similar to teleport and it also allows an attack if you teleport a shorter distance
