### ISSUE TITLE
Reconsider the value of spells that require an action to break

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#664]
Spells like web, entanglement, the burn condition, etc. used to require the whole turn to attempt to break free. They now require a single action, which means monsters can still Dodge, Cast a Spell, or Disengage after attempting to break the effect. Some monsters have 3 or 4 actions, so these spells and effects are specially weaker against them.

This relates to #273 .

**Comment by mlenser** [comment]
This was already discussed on discord. See https://discord.com/channels/701706060440010753/701706060440010756/792137883062370334

**Comment by itamarcu** [comment]
> Some monsters have 3 or 4 actions, so these spells and effects are specially weaker against them.

This is an important point, and I don't know if the sheet is able to balance around that.  it means that a spell like Web is more effective against a high level player character (2 actions) than against a high-CR monster (3+ actions).

**Comment by mlenser** [comment]
The same is true for Staggered. It's not something to balance against.
