### ISSUE TITLE
Earthen Grasp - 2 issues

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#665]
[Earthen Grasp](https://www.kryxrpg.com/spells/earthen-grasp)

1. The damage should be 2d6, not 4d6, according to the spreadsheet
2. The phrasing "As an action on each of your turns thereafter, you can cause the hand to reach for a different creature or to move to a different unoccupied space within 30 feet. " implies you can't both move and attack at the same time.  This seems to remain from the 5e spell, but it's almost definitely not intended.  It makes the spell much weaker once an enemy has moved away.  Compare [Force Hand](https://www.kryxrpg.com/spells/force-hand) and [Flaming Sphere](https://www.kryxrpg.com/spells/flaming-sphere), which can move and attack.

**Comment by mlenser** [comment]
Earthen Grasp reworked to mirror Force Hand, Giant Crawling Claw, and Kinetic Grasp
