### ISSUE TITLE
Force Sword - better damage balance suggestion

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#666]
Force Sword currently deals 3d10 every turn and augments for +2d10.
![image](https://user-images.githubusercontent.com/6516621/103686848-158b3500-4f98-11eb-9b7d-87ba4fca1316.png)

I suggest changing it to a 6d4 base with +4d4 augment.
![image](https://user-images.githubusercontent.com/6516621/103686924-2d62b900-4f98-11eb-841d-04161d5fb898.png)

**Comment by mlenser** [comment]
I generally try to avoid large amounts of d4s
