### ISSUE TITLE
Entomb - requires an action to make a Reflex saving throw

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#667]
https://www.kryxrpg.com/spells/entomb

> An entombed creature can use an action to make a Reflex saving throw against your spell save DC.
> On a successful save, the effect ends and the target returns to the space it previously occupied, or the nearest unoccupied space.

This could probably be changed to an Acrobatics or Brawn check. It's almost unheard of to use an action to make a save.

**Comment by mlenser** [comment]
Entomb slightly reworked to repeat the saving throw at the end of each of its turns
