### ISSUE TITLE
Fuse Flesh requires the incapacitated creature to use an action to escape

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#668]
https://www.kryxrpg.com/spells/fuse-flesh

> A creature paralyzed by this spell can use an action to make an Acrobatics or Brawn check (its choice) against your spell save DC.

This spell is very special because it paralyzes a creature by creating a physical wrapping around its skin, one which is broken through through physical strength (or acrobatics, somehow).  However, by the rules, a paralyzed creature can't use an action.

I suggest one of:
- add "**This action can be taken despite the creature being paralyzed by this spell.**"
- change "The target retains the ability to breathe, eat, and excrete, **and can take actions that doesn't require it to move any part of its body**. "

Also, unrelated, but I think the following sentence should be removed:
> If the sudden transformation would prove fatal to the creature (such as fusing a flying target), the target has advantage on the save.

The other stun/restrain spells include no such thing, and I don't see why this particular spell should include it.

**Comment by mlenser** [comment]
Fuse Flesh reworked to repeat the saving throw at the end of each of its turns

**Comment by mlenser** [comment]
Stasis now has a note that the save is made with advantage if the result would be fatal

**Comment by itamarcu** [comment]
> Stasis now has a note that the save is made with advantage if the result would be fatal

But why?

There are a lot of effects that can cause a flying creature to drop.  Anything that causes a target to be grappled, restrained, stunned, paralyzed, petrified, or knocked prone - and we aren't adding this advantage thing to all of them.  I don't think we should, at all, because dropping from flight is intentionally something the flying creatures need to worry about, and there's even an extra rule that reduces the damage they would take.

> Flying creatures enjoy many benefits of mobility, but they must also deal with the danger of falling. If a flying creature is knocked prone, has its speed reduced to 0, or is otherwise deprived of the ability to move, the creature falls, unless it has the ability to hover or it is being held aloft by magic, such as by the levitate spell.

> Falling
> When a conscious flying creature falls, subtract the creature’s current flying speed from the distance it fell before calculating falling damage.

Furthermore, if you're able to stun a flying creature in a way that would make it drop 70+ feet (more than its flying speed), it usually means the creature falls out of range - e.g. down a cliff - making the stunned condition less valuable by itself.

**Comment by mlenser** [comment]
> But why?

Causing a falling creature to fall would cause massive damage. Adding that effect on to these already strong effects would make them very strong.

_______________

However as you have pointed out, hovering accounts for this. I assumed hovering didn't apply to stunned, restrained, etc, but it seems to.


> When a conscious flying creature falls, subtract the creature’s current flying speed from the distance it fell before calculating falling damage.

I wouldn't have expected this to apply if they are stunned.. They are still conscious, but this seems a bit silly..

**Comment by mlenser** [comment]
removed note about saving with advantage if it is fatal
