### ISSUE TITLE
Spells that cure disease and divine health acolyte feature. 

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#669]
A change was made to bump all spells that cure diseases to 3 mana, since getting rid of disease should not be that easy. I agree with that, and that was the motive given in the change log.

But acolytes can select the divine health feature that makes them immune to diseases from as early as 2nd level. I know immunity to diseases is not the same as cure them once you already got them, but maybe it is a little inconsistent that the acolyte can be immune to a disease that he will only be able to cure 10 levels ahead. 
Bonus: I don't see anything indicating that magic diseases are not included, so I assumed you are immune to them too?

Possible solution: maybe put a prereq. for this feature that you should have a mana limit of at least 2. That is not the 3 needed to cast "cure disease", but again, only you are immune and can't cure anyone else. At least it's a middle of the road. Alternatively, you can say that you are immune e to mundane diseases, and at 9th level you improve to being immune to all diseases.

**Comment by mlenser** [comment]
One character being immune to disease is very different from one character being able to cure the whole party/whole village. It also has implications on when village/city priests can cure their people.

Acolyte being immue at 2nd level is not an issue.

**Comment by mlenser** [comment]
Regarding magical diseases: I'm not finding any sources about them for 5e. I think it may be a 3.5 thing that doesn't exist in 5e.

**Comment by Paulorpribeiro** [comment]
I'm not 100% sure, but the many diseases that demons and devils cause is magical?

**Comment by itamarcu** [comment]
> but maybe it is a little inconsistent that the acolyte can be immune to a disease that he will only be able to cure 10 levels ahead.

It's probably much easier to prevent getting sick in the first place than it is to take the sickness out of someone.

Also, many diseases have repeated saving throws after being infected;  only high level priests will be able to completely cure the diseases, but low level priests could still use spells like Bless to increase someone's saving throw against the disease.

regarding magical diseases, there's a few mentions in [Resurrection](https://www.kryxrpg.com/spells/resurrection):
> It doesn’t, however, remove magical diseases, curses, and the like
