### ISSUE TITLE
Sugested maneuver - Aim (again)

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#670]
Aim got removed a few iterations ago if im not mistaken, but with the two action economy I think it will fit nicely. Here is the proposal

Aim -1 stamina (marksman)

As an action  you can choose a target you can see and lock your aim at it. Your next ranged attack roll against that target until the end of your next turn is made with advantage and if it hits, add the stamina die to the attack’s damage (add half if you miss by 4 or less).

Thoughts?

**Comment by Paulorpribeiro** [comment]
Ah, augment: You can increase the damage for each additional stamina die expended

**Comment by mlenser** [comment]
Aim added as a 1 stamina die maneuver

It's different than what you propose. See the discussion on Discord.
