### ISSUE TITLE
Ice Flows should give "ignore icy difficult terrain"

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#671]
**Ice Flows** feat creates difficult terrain on the squares you walk on, but this also affects you. The feat should grant you immunity to difficult terrain caused by icy surfaces. Not meant to be a buff, but just so you don't affect yourself. Also, it's thematic.

**Comment by mlenser** [comment]
Ice Flows changed so that you are unhindered by difficult terrain caused by ice
