### ISSUE TITLE
Martial initiate compare to arcane initiate

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#673]
i posted on discord a feddback from a friend who was that the martial initiate feat is comparatively worse than the arcane (or other power source) initiate feat.
Sumarizing, the martial feat gives you 3 stamina (considering 2 short rests a day) and a 1 stamina maneuver, while the arcane does the same thing, but since 1 mana = 3 stamina, you effectively get more resources with the same investment (feat).

I propose that the arcane (and other power sources) initiate feat gives you the spell, but only refreshes at a long rest, while the martial initiate remains refreshing on a short or long rest.

**Comment by mlenser** [comment]
Martial Initiate now allows the maneuver to be used three times

**Comment by Paulorpribeiro** [comment]
I think now it is too strong! A charactercthst takes the feat can effectively get an extra 9 stamina (only one maneuver option, but stil) on an adventure day! I think that is too strong for a feat, no?

**Comment by itamarcu** [comment]
Twice between short rests might be the happy medium, but maybe 3/rest is really the better one.  I think it'll depend on playtesting as much as it depends on balance sheet calculations.

**Comment by Paulorpribeiro** [comment]
3 times per rest makes.this fé a t insta pick for gishes. In fact it's better to go full spells as a gish (instead of say half-a d-half) and grab 9 equivalent stamina with a feat. Even a full stamina user can get a lot out of this

**Comment by mlenser** [comment]
I'll take a second look.

**Comment by mlenser** [comment]
Martial Initiate reverted back to once per short rest and the spell feats are changed to be once per long rest. 3 mana per day is too much for a feat to offer.
