### ISSUE TITLE
Site cache issue

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#674]
I'm reporting it here too before it gets forgotten:

> Just a note, whenever I go to your site, the changelog lists the last change on January 8th. I hit Ctrl + Shift + R, then it shows there are changes on the 17th. However, if I reopen the site again (or just refresh it), it goes back to only showing until January 8th

**Comment by mlenser** [comment]
Fixed. Hopefully it doesn't impact everyone. We'll see.
