### ISSUE TITLE
Knockout maneuver is too strong

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#676]
>  Add one stamina die to the attack’s damage (add half if you miss by 4 or less). The creature must succeed on a Fortitude saving throw or it is incapacitated for the duration.

Knockout cost 3 Stamina, but it's much better than Disorient at 2 Stamina, which staggers and deal only 1d8 at 2 Stamina. I believe knockout should be increased to 3 Stamina.

Better yet, make knockout a 3 Stamina augment of Disorient.

**Comment by itamarcu** [comment]
> make knockout a 3 Stamina augment of Disorient.

I agree, and it should be named "Incapacitate" (similar to Stagger and Stun).

Personally, I'm in favor of "Knockout" actually knocking someone out (= unconscious). But if that's not happening, merging it with Disorient makes sense.

**Comment by mlenser** [comment]
Disorient added to the Deceit theme with an augment to incapacitate the creature instead of preventing reactions. The Knockout maneuver has been removed.

A maneuver that knocks someone unconscious has been suggested and rejected on #632.

**Comment by Marcloure** [comment]
> **_Stagger._** You can expend 1 additional stamina die so the creature is staggered instead of not being able to take reactions.
> 
> **_Incapacitate._** You can expend 1 additional stamina die so the creature is incapacitated instead of not being able to take reactions.

Why are both of these 1 additional stamina? Incapacitate is considerably better than Stagger.

**Comment by mlenser** [comment]
Making changes late at night is why. Fixed now
![image](https://user-images.githubusercontent.com/235857/106703140-ee04a800-65e9-11eb-9746-dbe0b1b93f6d.png)

**Comment by itamarcu** [comment]
Have you considered turning "not being able to take reactions" into a condition, called Disoriented?

**Comment by Marcloure** [comment]
That seems redundant. Conditions exist mostly so you don't have to repeat a description or to reduce space, but saying "and it can't take reactions" or "and it is disoriented" takes basically the same effort.
