### ISSUE TITLE
Nerf Goliath's Stone Endurance

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#677]
At 13th level, this gives a Goliath around 11 Health 3 times per short rest, which sums up to an average of 99 Health on a long day. Even considering the extra 33 Health on a short rest is too much for a species feature, I believe.

I think just once per short rest is good in all levels, 10-17 Health is never less.

**Comment by itamarcu** [comment]
Some factors that make the feature weaker than it mathematically is (though perhaps it's still too strong):
- It requires your reaction, which is a resource.  Sometimes you'd have something better to do with your reaction, such as making an opportunity attack.
- When reducing damage to 0, there will usually be a bit of extra "wasted damage prevention" (e.g. when you take 7 damage and prevent 10 of it).
- A Goliath concentrating on a spell will often want to reduce the damage to 0, to avoid making a concentration check - which increases the chances of not getting the full effectiveness of the feature.

**Comment by mlenser** [comment]
Assuming all damage is prevented is too generous. Maybe something like 80% is fair.

Comparison at different levels using my standard assumption of 1.75 short rests per day:

## 1st level
- Goliath can mitigate **_up to_** 9.5 damage per short rest, or about 26 damage per day. Or about 21 if we take into account imperfect usage.

## 5th level
- Goliath can mitigate **_up to_** 19 damage per short rest, or about 52 damage per day. Or about 42 if we take into account imperfect usage.
- A 1 mana single target spell does ~15 damage per short rest or about 41 damage per day. Or about 33 if we take into account imperfect usage.
- A 1 mana aoe spell would do much more (Poison Burst on Tiefling for example)

## 5th level
- Goliath can mitigate **_up to_** 19 damage per short rest, or about 78 damage per day. Or about 63 if we take into account imperfect usage.
- A 2 mana single target spell does ~35 damage per short rest or about 96 damage per day. Or about 77 if we take into account imperfect usage.
- A 2 mana aoe spell would do much more (Poison Burst on Tiefling for example)

## Conclusion

Goliath's Stone’s Endurance seems in line with the power level of spell options and is considered at the same point level for balance. Everything seems ok to me.

**Comment by Marcloure** [comment]
I think you should consider Stone Endurance as a reaction healing spell to balance it properly. Negating 10 damage as a reaction is considerably better than dealing 10 damage as an action.

**Comment by mlenser** [comment]
Then it's balanced (assuming perfect usage):
![image](https://user-images.githubusercontent.com/235857/106703279-3d4ad880-65ea-11eb-9225-3676658909b5.png)

At later levels when Con goes up then it becomes stronger:
![image](https://user-images.githubusercontent.com/235857/106703334-58b5e380-65ea-11eb-9d68-1a42bf1a1d9f.png)

But both of these assume perfect usage, which wouldn't be the case.

Seems totally fine.

**Comment by Marcloure** [comment]
Sorry to answer to this quite late, but what that means is that Stone's Endurance is roughly as strong as a 1 mana spell, right? But then, being able to use it 3 times per _short_ rest isn't too much? Other species that gain spells or maneuver can use it once per short rest.

**Comment by itamarcu** [comment]
Goliath can do it once per short rest at 1st level, twice at 5th, and 3 times at 13th.

Species that have spells usually have 1 cantrip and 2 spells (I'm using this example because those two options have equal "Value" of 5 in the sheet), and your choice of one of the two spells can be cast once per long rest at 1st level, once per short rest at 5th, and is augmented to 2 mana at 13th.

I think these two seem roughly balanced.  Assuming SA is equivalent to a spell in its value, the Goliath do theoretically get x3 as many uses of the "spell", but:
- A cantrip and an extra choice of spell will provide a lot more versatility
- x3 between long rests will often be x2 or x1, depending on number of short rests, which slightly reduces the value
- imperfect usage of Stone's Endurance, as mentioned before, will slightly reduce the value

**Comment by Marcloure** [comment]
> x3 between long rests will often be x2 or x1, depending on number of short rests, which slightly reduces the value

It's x3 per short rest, not per long rest.

**Comment by itamarcu** [comment]
Yeah, but what I meant with that bullet point is that sometimes people take less than 2 short rests over a long day, which slightly reduces the x3-per-long-rest value multiplier for the purposes of evaluating this below 5th level.

Rephrasing - if you compare them at level 13, it's:
- Goliath gets these 15 value points (= 1 1-mana spell's worth), x3 per short rest, so **~45**.  minus potentially imperfect usage.
- Others get 35 value points (= 1 2-mana spells' worth), x1 per short rest, so **~35**.  plus the added versatility of an additional spell and an additional cantrip, and potentially the ability to use more mana on these spells.

**Comment by mlenser** [comment]
Goliath no longer gain the ability to use Stone’s Endurance twice between rests at 5th level. It is now delayed until 13th level. Instead, Grand Competitor can be used twice between rests at 5th level. Goliath’s also gain the Resilient trait which lets them endure a forced march, a lack of food or water, or a lack of sleep.

**Comment by mlenser** [comment]
Still a very good feature 
![image](https://user-images.githubusercontent.com/235857/109200465-f000f780-77a0-11eb-9814-eca4d48c7f2f.png)
