### ISSUE TITLE
Consider changing Metric to 1 meter = 5ft

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#679]
1 space/square = 1.5 meters is problematic and annoying to work with.

1 or 2 meter would be a better option for ease of use.

5 feet has always seemed too big to me and increasing it even more would be silly. Daggers don't have a range of 5ft - they have a range of arm length. Sword have arm length + weapon length. Both of which fit much better in 3ft/1 meter. 2 meters would be far too much for believable weapons imo

To that end I think we could try converting everything to 1 space/square = 1 meter and then adjusting certain distances to be shorter or in some cases leave them as they are.

**Comment by DalenWBrauner** [comment]
One of the more obvious problems with changing the standard "tile/space/square" size is that most battlemap art that exists is based around 5ft per square. Trying to work with battlemaps with incorrect grid sizes is definitely also annoying.

Another problem is that if we adjust only our metric measurements (e.g. using a ratio of 1 meter : 5ft) then obviously the discrepency becomes more noticable at larger distances.
(For reference, 1 meter = 3.28 feet.)

I'm not sure what a "best" solution might look like, but it's going to take a lot of thought; the problem definitely isn't exclusive to this system. I'm curious what other sort of 'homebrew' solutions people around the world have come up with.

**Comment by mlenser** [comment]
> One of the more obvious problems with changing the standard "tile/space/square" size is that most battlemap art that exists is based around 5ft per square. Trying to work with battlemaps with incorrect grid sizes is definitely also annoying.

As Marcloure wrote on discord: Maps are already too small. I would recommend that a standard 5ft square becomes 4 squares in most cases already. The only issue is some things might be a bit distorted, but I do this already even on the current 5ft = 1.5 meters.
Overall I don't think this an issue as squares can be expanded

> the discrepency becomes more noticable at larger distances.

Agreed, but I'm not sure these are actual concerns. I'll need to run some sample scenarios. I definitely don't expect it to behave how it currently does, but maybe it'll be fine as well.

> I'm curious what other sort of 'homebrew' solutions people around the world have come up with.
I've searched on this topic forever. The vast majority settle on 1.5 meters. I think 1.5 meters is tricky when we have options like Dwarves or Wood Elves who move one space more or less so inherently they get "weird" speeds. 1.5m will always cause that and if that's not what we want then we must choose something else which is 1m or 2m. Out of those I think 1m is superior.

**Comment by mlenser** [comment]
- RAW Longbow is 600 feet at long range = 120 spaces.
- RAW 30 feet of movement + dash is 60 feet = 12 spaces.
- 120/12 = 10
RAW it would take 10 turns to reach an archer

- Current longbow is 180 meters = 120 spaces
- Current 9 meters of movement + 2 dashes is 27 meters = 18 spaces
- 120/18 = 6.666
It would take 6.666 turns to reach an archer

_______________

If we use 1 meter = 1 space and keep the distance for longbow:

- Longbow is 180 meters = 180 spaces
- 180/18 = 10
It would take 10 turns to reach an archer

Seems it would be totally fine to switch directly, at least regarding long range options like the Longbow.

**Comment by Marcloure** [comment]
So spells that have range of 9 meters would still have 9 meters after changing spaces to 1 meter?

**Comment by mlenser** [comment]
I'm not sure. I haven't fully thought it through.

Similar comparison to above with 18 meters:

- 60 feet = 12 spaces.
- RAW 30 feet of movement + dash is 60 feet = 12 spaces.
- 6/12 = 1 turn to get within melee

RAW it would take 1 turn to reach the caster

- Current 18 meters = 12 spaces
- Current 9 meters of movement + 2 dashes is 27 meters = 18 spaces
- 12/18 = 0.666

It would take 0.666 turns to reach the caster

_______________

If we use 1 meter = 1 space:

- 18 meters = 18 spaces
- 18/18 = 1

It would take 1 turn to reach the caster

_________________

Seems like a decent option

**Comment by mlenser** [comment]
If we use 1m then movement should be 6m.

6 meters of movement + 2 dashes is 18 meters = 18 spaces.

The rest of the above would be the same.

**Comment by mlenser** [comment]
Along with this, I think we should adjust speeds to 5 meters/25 feet. Then we have nice increments:
- 25, 50, 100 feet instead of 30, 60, 120 feet
- 5, 10, 20 meters instead of 9, 18, 36 meters

**Comment by ChefSasquatch** [comment]
Why not just use spaces and leave it to the players to decide how big they are. Instead of saying a spell has 9 meters of range just say 6 spaces. I find it to be much more elegant and it's shap agnostic; didn't matter of it's a hex or a square, it's still just one space, no need for any complex math or conversions

**Comment by mlenser** [comment]
"Space" is not a term that works well for theatre of mind games. It is a concept designed for systems like 4e that pretty much must use a board. It also does not work well over long distances where then imperial and metric people have to multiple "space" by their unit.

It's a non-option imo.

**Comment by Kuro7369** [comment]
If you adjust the speed you'll then have to adjust spells/bow range or your previous calculations will be off

Taking 1m = 1 space with modified speed :

Longbow is 180 meters = 180 spaces
5 meters of movement + 2 dashes is 15 meters = 15 spaces (same results with feet)
180/15 = 12 turns to reach the archer instead of 10

**Comment by Marcloure** [comment]
I believe that consequence is intentional. Currently, creatures take less turns to reach ranged characters than in vanilla 5e, since here they can take 2 Dash actions. With this change reducing speed but keeping range, they would take the same amount of turns as in 5e.

**Comment by Kuro7369** [comment]
No, that would be the same as row with a 6m speed
6m or 30ft are both a 6 spaces speed

reducing speed (wether imperial or metric, wich is proposed with the nicer increments) while keeping ranges would augment the number of turns compared to RAW

**Comment by Kuro7369** [comment]
No, that would be the same as RAW with a 6m speed
6m or 30ft are both a 6 spaces speed

reducing speed (wether imperial or metric, wich is proposed with the nicer increments) while keeping ranges would augment the number of turns compared to RAW

**Comment by Paulorpribeiro** [comment]
I think the "number of turns of turns to reach the archer" should remain the same. But imo that's not the main issue. The biggest issue I think is that if we shrink one space to mean 1m (instead of 1.5) we will have to make bigger cre a tures take more space. It doesn't make sense that a giant or dragon that's supposed to be huge is suddenly 30% smaller. And if we think about 4x4 square creatures, they were 6x6 meters and will turn to 4x4 meters.

**Comment by Marcloure** [comment]
> No, that would be the same as RAW with a 6m speed
6m or 30ft are both a 6 spaces speed

You are not taking into account that creatures here can take more than 1 Dash action per turn. See Kryx explanation here: https://github.com/mlenser/kryx-rpg-issues/issues/679#issuecomment-786692554

**Comment by Kuro7369** [comment]
`You are not taking into account that creatures here can take more than 1 Dash action per turn`

`5 meters of movement + 2 dashes is 15 meters`

Did you read my message ? I gave the calculations, if you want do the calculations yourself and prove me wrong

**Comment by Marcloure** [comment]
> Longbow is 180 meters = 180 spaces

I don't think that would be the case if we change the speeds to 5/10/20/etc. meters. I believe the bow would have 150 meters of range in this case.

**Comment by Kuro7369** [comment]
Yup that's what I said in my first message 
> If you adjust the speed you'll then have to adjust spells/bow range or your previous calculations will be off
It wasn't the case with a 6m speed since it gave the same results as RAW, but with a 5m speed the bow should have a 150m/750ft range

**Comment by Paulorpribeiro** [comment]
5 meters/25 feet speed is very handy, and I would vote for it. Maybe adjust the ranges of ranged weapons (spells may be alright).

Slower races would be 4m/20 ft right? Is that too short? I think not, specially with double dash available

**Comment by mlenser** [comment]
> Slower species would be 4m/20 ft right?

PF2e does 25 ft as the standard. Dwarf are 20.

![image](https://user-images.githubusercontent.com/235857/110239322-9ccc3900-7f46-11eb-9934-b88760bc6f14.png)

________________

Overall there are a few goals with this issues:
- Make metric units easier to use (1 square = 1 meter)

- Continue using standard distances for everything

**Comment by mlenser** [comment]
> Slower species would be 4m/20 ft right?

PF2e does 25 ft as the standard. Dwarf are 20.

![image](https://user-images.githubusercontent.com/235857/110239322-9ccc3900-7f46-11eb-9934-b88760bc6f14.png)

________________

Overall there are a few goals with this issues:
- Make metric units easier to use (1 square = 1 meter)
- Likely adjust the standard range to 5 meters/25 feet so then we get nice increments like 5,10,20,40, and 25,50,100,200. Continue using standard distances for everything so if one thing adjusts, they likely all do.
- See if we can maintain some standard distance/turn. It won't be the same as RAW, but shouldn't be too far off.

**Comment by Kuro7369** [comment]
The problem here is not that we deviate from RAW, but the discrepancy between imperial and metric

Metric would give with base movement and 2 dashes 6m * 3 = 18m
180/18 = 10 turns to reach the archer

Imperial is 30ft * 3 = 90ft
600/90 = 6.667 turns to reach the archer

Reducing the space size from 1.5 to 1m stretches the range of attacks, suddenly jumping from 120 to 180 spaces for a longbow attack. You either need to reduce that distance, or augment the number of spaces a character can move

Imperial give 600/90 = 6.667 turns to reach the archer
you either need to have a range of 120m : 120/18 = 6.667 turns 
or augment the speed to 9m : 180/27 = 6.667 turns

**Comment by mlenser** [comment]
The main goal here is nice increments so we won't be using 18m or 120m or anything like that if this goes through.

I'm not greatly concerned about feet vs metric. If that's a major issue then I'd likely either adjust feet ranged or drop feet all together before I messed around with metric. Metric is the primary system.

**Comment by Kuro7369** [comment]
Well, I guess dropping feet would solve a lot of problems, you could adjust meters as you wish without being concerned by the consistancy

**Comment by ChefSasquatch** [comment]
I know myself, and likely many others, would much prefer to play with Imperial over Metric; would dropping a Square to 3 feet not solve the issue?

**Comment by mlenser** [comment]
5ft is definitely a sacred cow that I expect would also be a deal breaker for many groups. I don't think that should changes. 3ft might be a better fit, but then feet would have weird distances like 6 feet, 9 feet, 18 feet, etc. Not great.

I don't plan to remove feet. It was a hyperbolic statement meant to enforce that metric is the main system. Feet is a secondary system that is there, but the balance might not be as tight.

**Comment by ChefSasquatch** [comment]
I really don't feel that having even distances is that important to the average group; I get why in the case of Meters it's less desirable, given that it's an integer value and not a whole number, but 3 feet is fairly easy to do and in many ways, a more accurate representation of space (the average square being 5 feet on a side is a bit ridiculous)

**Comment by mlenser** [comment]
> the average square being 5 feet on a side is a bit ridiculous

Fully agreed. I think 3 feet would fit better as well. But I would never use it due to trading nice even increments based on 5 for increments based on 3.
Metric it's acceptable-ish because there haven't been better options.

Increments like 5, 10, 20, 40, 80/100 meters and 25, 50, 100, 200, 400/500 feet are very nice to work with. Increments not being nice is the whole complaint about the current metric system.

**Comment by Kuro7369** [comment]
That's why I think using better increments for the ranges would also be better. 150m/750ft would be better than 180m/600ft and it makes calculation a lot easier, it's a 10 turn reach for both (with 5m and 25ft speeds), same as RAW. It all feels nice and smooth.
I totally agree that trying to refine the increments is a great idea, but I do think that modifying certain values while keeping some others is a mistake

**Comment by mlenser** [comment]
> I do think that modifying certain values while keeping some others is a mistake

No one has ever said that will be the approach. You can clearly see above that all increments are in discussion. It wouldn't make sense to only change a few.

Either we stick strictly to doubling or go for some jumps. Either way, i don't expect 150 or 750 to be options.

Either 5, 10, 20, 40, 80, 160 or 5, 10, 25, 50, 100, 200.
That's 25, 50, 100, 200, 400 for the feet peeps. But here you see how optimizing for nice meters immediately will lead to either differences to feet or not nice increments for feet. That's why I'm making it clear that imperial is not the main system of measurement.

**Comment by mlenser** [comment]
Note: There are some parts of the system that are tied to distance. Soften fall, jump, etc would need to be reworked if we do this..

**Comment by mlenser** [comment]
I think we could possibly solve this issue for most tiers

**Metric:**
- 1.5 m base as normal.
- 7.5 m "standard" distance/speed (formerly 9 m)
- 15 m "medium" distance (formerly 18 m)
- 30 m "long" distance (formerly 36 m)
- 90 m crossbow/shortbow long range would stay the same
- 180 m heavy crossbow/longbow would stay the same

**Imperial:**
- 5 ft base as normal.
- 25 ft "standard" distance/speed (formerly 30 ft)
- 50 ft "medium" distance (formerly 60 ft)
- 100 ft "long" distance (formerly 120 ft)
- 300 ft crossbow/shortbow long range would stay the same
- 600 ft heavy crossbow/longbow would stay the same

**Comment by itamarcu** [comment]
This doesn't really solve the issue of using halves with metric at all, it just solves the newly brought up issue of distances being multiples of 30 instead of 25 feet.  Making everyone a little bit slower in combat (5 spaces/turn instead of 6 spaces/turn).

Why not go all the way and use 1 m = 5 feet, with standard distances of 1, 5, 10, 20, 50, 100 meters? (x5 for feet)

**Comment by mlenser** [comment]
> Why not go all the way and use 1 m = 5 feet, with standard distances of 1, 5, 10, 20, 50, 100 meters? (x5 for feet)

Main concern: people will google RAW values and they'd be different. Also what you suggest is more work.

Maybe you're right though..

**Comment by mlenser** [comment]
Proposal to mull over

**Metric:**
- 1 m base
- 5 m "standard" distance/speed (5 spaces, formerly 6 spaces. formerly 9 m)
- 10 m "medium" distance (10 spaces, formerly 12 spaces. formerly 18 m)
- 25 m "long" distance (25 spaces, formerly 24 spaces. formerly 36 m)
- 50 m ? is this needed?
- 100 m crossbow/shortbow long range (100 spaces, formerly 60 spaces. formerly 90 m)
- 200 m heavy crossbow/longbow would stay the same (200 spaces, formerly 120 spaces. formerly 180 m)

**Imperial:**
- 5 ft base as normal.
- 25 ft "standard" distance/speed (5 spaces, formerly 6 spaces. formerly 30 ft)
- 50 ft "medium" distance (10 spaces, formerly 12 spaces. formerly 60 ft)
- 100 ft "long" distance (20 spaces, formerly 24 spaces. formerly 120 ft)
- 150 ft ?
- 300 ft crossbow/shortbow long range would stay the same (60 spaces)
- 600 ft heavy crossbow/longbow would stay the same (120 spaces)

**Comment by mlenser** [comment]
Done
