### ISSUE TITLE
Convert 1/rest feats to maneuvers/spells

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#68]
Options like
- Temporal Acceleration
- Wholeness of Body
- Zealous Presence

should be converted to a maneuver or spell or removed if such an option already exists.

**Comment by Marcloure** [comment]
I think some of these feats worked well as stronger versions of a spell. For instance, Dispel Arcane was a 1/rest dispel magic that didn't require a check to dispel higher mana magic, so I think it was acceptable as a Feat

**Comment by Marcloure** [comment]
Also, some of them allowed non magical characters to have some magical powers. I think Form of the Beast is the great contender here, since it allows bestial warriors

**Comment by Marcloure** [comment]
Another issue is concentration, some of these Feats were concentration free versions of spells.

**Comment by mlenser** [comment]
> 1/rest dispel magic that didn't require a check to dispel

A 1/rest "end any spell on you" is a design to bypass the way the game handles ending magic. There is an established way to counter a spell (Counterspell) or end a spell (Dispel Magic). A feat could you advantage to those (which https://marklenser.com/rpg/themes/feats/improved-abjuration does) or some other option, but I don't think bypassing that defined system is good.

>  some of them allowed non magical characters to have some magical powers.

Non-magical characters should not have magical powers. Most such feats had the "The ability to cast at least one spell" prerequisite. Those that didn't, should've.

> I think Form of the Beast is the great contender here, since it allows bestial warriors

Faithful Summons (summoning a bunch of beasts to protect you when you fall to 0) is definitely a magical ability. It should be restricted to magic. A martial character who wants to have a beast can pick up a feat like Animal Companion which is not bound by magic. 

Form of the Beast was the **Natural Weapons** part of Bestial Transformation in a feat instead of a spell. But that transformation requires magic. Lycanthropy exists in the blood theme and is driven by a disease, not magic. That's why it's available to all.

> Another issue is concentration, some of these Feats were concentration free versions of spells.

Spells that require concentration should require concentration. Feats shouldn't be able to bypass that.

**Comment by Marcloure** [comment]
Ok, just so I'm not misunderstood, I'm not exactly defending that these feats don't be converted to spells. I'm just stating how Feats are different from spells so we can better judge if an effect could remain as a Feat.

> Animal Companion which is not bound by magic

I think you do need to be able to cast spells to pick the feat, since it only scales with mana. It actually requires the character to know the Call Beast spell.

**Comment by mlenser** [comment]
> I'm just stating how Feats are different from spells so we can better judge if an effect could remain as a Feat.

Feats, in general, should give permanent benefits. Some examples:

- Longer range concoctions
- Learn a concoction, maneuver or spell
- Proficiency in a skill
- More hit points
- More damage from attacks
- Permanent damage bonus to undead
- Regain hp if below half
- Cast a spell at will
- Reroll 1s on spell damage dice

Some of the options I converted to spells could live as a feat. For example Dark One's Own Luck could be a carbon copy of the new "Lucky" feat (I just pushed it). But in that case I think luck should live in fate, not Unholy.

Other cases could also have their own feat, but they should fit in the design space for a feat, not a spell/maneuver. If there is a gap that should be filled then lets explore if it should be filled and if so then how.


> I think you do need to be able to cast spells to pick the feat, since it only scales with mana. It actually requires the character to know the Call Beast spell.

You're right, my mistake. Mechanically, I'd let a character expend twice as much stamina dice as mana, but flavor-wise that makes no sense.
