### ISSUE TITLE
Acid should be able to dissolve through objects

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#681]
Currently the Acid theme has no way of destroying objects/structures.  I think this should be fixed, because it's pretty classic for acid to eat through materials, create holes, and dissolve objects or creatures.

- I think it could get a spell with a paragraph similar to that in Disintegrate and Ravage, which explicitly says it destroys/dissolves dead creatures and portions of objects.
- Corrosive Consumption should say "If a creature is killed by this spell, its flesh dissolves away, leaving a puddle of remains".
- Could add a spell which works just like the cool "Corrosive" feat but at higher speeds for a long duration - similar to Move Earth. Something like: 

> As two actions, choose a sphere of terrain twice as big as normal within 36 meters. The area fills with droplets of strong acid, which you can control to slowly eat through objects in the area.  You may choose to create holes in surfaces, create trenches, destroy nonmagical items, dissolve bodies, or carve a sculpture. It takes 1 minute to destroy organic material such as cloth, plants, or rope, 5 minutes to destroy wood, and 30 minutes to destroy metal.
Every 10 minutes you spend concentrating on the spell, you can choose a new area of terrain to affect.
Because the corrosion occurs slowly, creatures in the area can’t usually be trapped or injured by the acid.

**Comment by mlenser** [comment]
> Corrosive Consumption should say "If a creature is killed by this spell, its flesh dissolves away, leaving a puddle of remains"

This wording was removed form Immolation as if we use this logic then all acid/fire spells should have this wording, which I don't think is a good method. One or two should have it, not all.

> Could add a spell which works just like the cool "Corrosive" feat but at higher speeds for a long duration - similar to Move Earth. Something like:

Please open a new issue for each suggestion. I'll look at this later when I have time.

**Comment by mlenser** [comment]
Acid Fog now dissolves objects in the area
