### ISSUE TITLE
Ferocious Charger and Tiger Totem Aspect

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#685]
Ferocious Charger and Tiger Aspect of the Beast are two very similar feats, but the former is 14th level, and the later 6th level. There is also the 10 feet requirement difference.

Some notes: Tiger Aspect of the Beasts should specify its DC and maybe that it can only be triggered 1/turn, like Ferocious Charger currently is.

**Comment by mlenser** [comment]
Both of these should be removed - we have maneuvers for these purposes.

**Comment by Marcloure** [comment]
There are some feats that grant spells at-will. I don't think a few that allow you to use some maneuvers at will is that bad (the maneuver is still better, since it deals damage)

**Comment by mlenser** [comment]
- Ferocious Charger removed as we have many maneuvers like Charge, Pounce, Trampling Charge, etc to cover this niche
- Aspect of the Beast feat removed.
  - Bear’s soak benefit moved to a new Thick Hide feat
  - Eagle’s benefit already existed in the Slip feat which has been added to the Beast theme
  - Elk’s benefit already existed in the Stalker’s Prowess feat
  - Tiger’s benefit already exists in the Pounce maneuver
  - Wolf’s benefit already exists in the Lead the Attack maneuver which has been added to the Beast theme

**Comment by mlenser** [comment]
> use some maneuvers at will

Maneuvers are not intended to be used at will. There should always be a cost.

**Comment by Marcloure** [comment]
The maneuver gives a free Dash and deals damage, so it's not same-same, but it's fine.
