### ISSUE TITLE
Add maneuvers/spells to monstrosities

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#686]
https://github.com/mlenser/kryx-rpg-issues/issues/9

**Comment by itamarcu** [comment]
Here's what I got for the letters B—E: https://gist.github.com/itamarcu/8d6ff02d9b80f22c23c7dd481e658129

**Comment by mlenser** [comment]
Added maneuvers/spells to monstrosities: Banderhobb, Basilisk, Behir, Bulette, Carrion Crawler, Catoblepas, Cave Fisher, Centaur, Chimera, Chitine, Choldrith, Cockatrice, Darkmantle, Death Dog, Displacer Beast, Doppelganger, Drider, and Ettercap

**Comment by itamarcu** [comment]
Updated the above link with F—H (+Androsphinx).

**Comment by mlenser** [comment]
Added maneuvers/spells to monstrosities: Androsphinx, Female Steeder, Froghemoth, Giant Strider, Girallon, Gorgon, Gray Render, Grick, Grick Alpha, Griffon, Gynosphinx, Harpy, Hippogriff, Hook Horror, Hydra, and Male Steeder

**Comment by mlenser** [comment]
- **Creatures**
  - Maneuvers added to the Manticore, Peryton, Piercer, Purple Worm, Roc, and Roper. [#686](https://github.com/mlenser/kryx-rpg-issues/issues/686)
  - Spells added to the Medusa, Medusa Queen, Merrow, Mimic, Phase Spider, Remorhaz, and Young Remorhaz. [#686](https://github.com/mlenser/kryx-rpg-issues/issues/686)

**Comment by mlenser** [comment]
- **Creatures**
  - Maneuvers added to the Manticore, Peryton, Piercer, Purple Worm, Roc, Roper, and Rust Monster. [#686](https://github.com/mlenser/kryx-rpg-issues/issues/686)
  - Spells added to the Medusa, Medusa Queen, Merrow, Mimic, Phase Spider, Remorhaz, Shadow Mastiff, Shadow Mastiff Alpha, Spirit Naga, and Young Remorhaz. [#686](https://github.com/mlenser/kryx-rpg-issues/issues/686)

**Comment by mlenser** [comment]
- Maneuvers added to the Tarrasque, The Angry, The Hungry, The Lonely, The Lost, The Wretched, Tlincalli, Trapper, Umber Hulk, and Worg. [#686](https://github.com/mlenser/kryx-rpg-issues/issues/686)
  - Maneuvers and Spells added to the Winter Wolf. [#686](https://github.com/mlenser/kryx-rpg-issues/issues/686)

Only yuan-ti left

**Comment by mlenser** [comment]
Yuan-ti done.
