### ISSUE TITLE
Rename Halfling and Dragonborn

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#689]
## Halfling
Halfling is a pretty derogatory term by implying that the species is half the size of men. See threads about this:
- https://www.reddit.com/r/DnD/comments/a1slrj/reckon_halfling_is_a_slur_for_hobbits
- https://www.reddit.com/r/worldbuilding/comments/5kpp3m/very_random_thought_on_the_name_halfling

They are known as [Hin](https://forgottenrealms.fandom.com/wiki/Halfling) and I'll probably go with that option.

## Dragonborn
Similar to Catfolk→Tabaxi, Lizardfolk→Ssurran, and Merfolk→Triton, I think Dragonborn should have a proper name for their species

## Dwarf

I think dwarf is largely ok due to:

https://www.reddit.com/r/worldbuilding/comments/5kpp3m/very_random_thought_on_the_name_halfling/dbprmjj/
> "Dwarf" is different though, in that from the first the word has been used to mean a type of mythological creature. The association of the term with dwarfism may have come much later.
> 
> "Dwarf" comes from Old English "dweorg", which in turn comes from Proto-Germanic "dwerga". Some scholars associate the word etymologically with Sanskrit "dhváras" ("demon") and Lithuanian dvãsas ("spirit").

https://www.reddit.com/r/worldbuilding/comments/5kpp3m/very_random_thought_on_the_name_halfling/dbqwswl
> The difference is that Dwarves have their own language so "Dwarf" is a translation to what they're called by native speakers of the common speech. (Though Idk if it's an actual translation in meaning or just used to indicate the same thing, i.e., like how some first nations tribes called themselves the word for "people" but colonists interpreted it as the name for the tribe). They call themselves something like Khuzdul I forget. Halfling isn't a translation of Hobbit. It's a word other speakers of the same language chose for them which is thoughtless even if no one ever was offended by it.

Though I wouldn't be opposed to renaming them "Dweorg" or something different if others desire.

**Comment by Tyresias11** [comment]
> I'm ok with the politically correct renaming, but it kinda makes the system a little more unfriendly to new players and DMs. Halflings and Dragonborn are way more commonly known by the community.
> Just my 2 cents, no hate pls

There is like a 1000 maneuvers/spells/concoctions and hundreds of feats, but renaming two species to more appropriate names will confuse new players and dms and make it harder? Let's not be silly now. 

Also there is absolutely no rule or logic on why species should have the most generic names. We don't call elves "long eared magic person" or orcs "Green ferocious person". People ain't stupid and even if that was of any effort, then let people make the effort to remember the name of an entire species. Maybe it will teach people the importance of dismantling problematic, underlying patterns.

**Comment by Paulorpribeiro** [comment]
Stress on my last sentence, no hate pls.

But anyway, I don't mind. We can also change orc to orok.
If you're playing this game with grown-ups, a group of adventures seeing aaracokra for the first time will certainly call them "birdfolk". Maybe even after the first time if they are trying to be depreciation (which is understandable if they are antagonists). Anyway, since this is probably not going anywhere, I'm ok with the change. It's just a name that might get changed  according to the setting anyway

**Comment by mlenser** [comment]
Added other names that certain species might be called, many of which are rather derogatory. If you have any suggestions for more to add, please let me know.

**Comment by Paulorpribeiro** [comment]
I think that was a good idea.

I missed the derogatory terms dark elf for the drow and lizardfolk for the ssurran

**Comment by mlenser** [comment]
Added more to drow, dwarf, ssurran, svirfneblin
