### ISSUE TITLE
Dark Fire feat suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#694]
**Death, 2nd Level**
*You must be able to cast a spell that deals fire damage*
When you cast a spell that deals fire damage, you can change the fire damage dealt by the spell to necrotic damage.

---

I know changing a spell's damage type shouldn't be a thing, but I think necrotic fire is pretty awesome and also common in fantasy. However, I think it's important that this don't lead to Acidic Ice or Dark Lightning, just this one case seems reasonable. Also, Death Knights already throw necrotic fireballs.

**Comment by mlenser** [comment]
> I know changing a spell's damage type shouldn't be a thing

It should not be a thing.

![image](https://user-images.githubusercontent.com/235857/111068021-38b9ef80-84c7-11eb-944b-97acc51d603c.png)

Fire does not wither matter or the soul. It would not be thematic for fire to deal necrotic damage. "Evil fire" is still fire.

**Comment by itamarcu** [comment]
Holy fire that deals radiant damage is classic too.  But I think this kind of stuff should be kept to special magic items or special character mechanics discussed with the GM for your character, not as part of the system (as this shouldn't be a common thing at all).

**Comment by mlenser** [comment]
> Holy fire that deals radiant damage is classic too. 

I would say that is just fire, but coming from "the gods". Still fire~
