### ISSUE TITLE
Allow breaking Darkness

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#695]
Currently, the caster can't stop its own darkness. I think this should be allowed, otherwise the spell can last for hours when you just want a zone of darkness for a combat.

**Comment by mlenser** [comment]
How would you propose this be accomplished? The same argument could be used for tens to hundreds of spells.

Either:
- All spells can be ended at-will
- Only spells based on concentration can be ended at-will

I don't see a strong thematic argument for the first.

**Comment by Marcloure** [comment]
I don't think the first should be true, but I think it's a good exception for darkness, since it can follow you and last for hours. Casting darkness on your armor or weapon is very bad if you intent to walk in a town later that day.

**Comment by mlenser** [comment]
> since it can follow you and last for hours

If it's cast on an object then you can just drop the object. If it's cast on an area then you can move away. It's always possible to dispel it too.

> Casting darkness on your armor or weapon is very bad if you intent to walk in a town later that day.

Seems like a bad idea, ya. But the rules specify that only spells with concentration can be ended at-will. I don't see a reason to add this exception without it applying to all spells.

**Comment by mlenser** [comment]
Note that I see now: Fog Cloud has concentration. Darkness probably should as well. I'll reevaluate.

**Comment by mlenser** [comment]
- **Light**
  - Concentration added to Daylight [#695](https://github.com/mlenser/kryx-rpg-issues/issues/695)
- **Shadow**
  - Concentration added to Darkness [#695](https://github.com/mlenser/kryx-rpg-issues/issues/695)
