### ISSUE TITLE
Counterspell chance doesn't match the spreadsheet

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#697]
There is something wrong with the counterspell calculation on the spreadsheet. For instance, the DC to counterspell a 2 mana spell cast by a creature with +5 proficiency and +4 spellcasting ability is 21. The counterspell caster (with equal bonuses) would need to roll a 17 if they have a +4 to their spellcasting ability, which is not the 45% chance of success listed on the spreadsheet. 

If Counterspell added the caster's proficiency (totaling +9), the caster would need to roll a 12 on the die, which is the 45% chance of success. So, I think counterspell should add the caster's spellcasting ability _plus_ their proficiency? That is not what is on the site, so I'm not sure what is right.

**Comment by mlenser** [comment]
> For instance, the DC to counterspell a 2 mana spell cast by a creature with +5 proficiency and +4 spellcasting ability is 21

The spreadsheet assumes "standard progression". The calculations are based on an equivalent-ish challenge monster. If you fight a monster with a much higher proficiency (2 mana is 3 proficiency, so 5 is +2) and a higher spellcasting ability (generally 3-4 for this tier, so +1ish) then the DC will be harder and it'll be harder to counterspell that creature.

The spreadsheet shows examples of a "standard" caster who at 2 mana has a prof of 3 and a casting ability of 3-4. So we're at 8 + 4 (2*prof) + 3 + 3/4 = DC 18 or 19.

**Comment by Marcloure** [comment]
> The spreadsheet shows examples of a "standard" caster who at 2 mana has a prof of 3 and a casting ability of 3-4. So we're at 8 + 4 (2*prof) + 3 + 3/4 = DC 18 or 19.

Counterspell doesn't add the caster's proficiency, it says "make an ability check using your spellcasting ability".

**Comment by mlenser** [comment]
Reworked the DCs for Dispel Magic and the Counterspell augment of Dampen Spell and also made it a bit more likely to end the spell as the case that I calculate is the ideal case.

**Comment by Marcloure** [comment]
The talbe is still wrong :/ 
At 13th level, it considers the counterspell bonus at 4 mana as +12, but that should be +14 = 5[ability] + 5[prof] + 4 [2 augments].

Maybe the augment should be 1 additional bonus for each additional mana?
> You gain a bonus to your ability check equal to 2 for each additional mana or psi expended.

**Comment by mlenser** [comment]
The bonuses in intended to be 1, ya.
