### ISSUE TITLE
Alchemist's Quick Alchemy should apply to bombs

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#698]
> **Quick Alchemy**
> You can swiftly mix up and imbibe a concoction at a moment’s notice. You can drink a potion as part of the same action as creating it.

Should the Alchemist be able to throw concoctions with this as well? With some concoctions taking 2 actions, they can't create the bomb and throw it in the same turn as they can do with drinkables.

**Comment by itamarcu** [comment]
I suggest:
> You can swiftly mix up a concoction at a moment’s notice. As part of the action you take to create a concoction, you can drink, administer, throw, or otherwise use it.

**Comment by mlenser** [comment]
I actually think this should be removed now that we have two actions.

Concoctions inherently require a bit more forethought. It is not intended to create them on the fly as needed. That is one of the intended flavor differences from spells.

**Comment by Marcloure** [comment]
Then, maybe no concoction should require 2 actions to prepare? It's a bit hard to gauge how the action economy works for them

**Comment by mlenser** [comment]
Why? Two action concoctions thematically take a longer time to distill/mix. So you have to prepare them before you use them. Concoctions last 24 hours so this is a bit of a pseudo-prepared casting as that is how concoctions work thematically: they take some time to make.

**Comment by Marcloure** [comment]
Because I think requiring 3 actions along 2 turns is a bit too much, specially for offensive concoctions. Concoctions like Paralytic Gas, Flash Bomb, or Nail Bomb, you can't just foresee if they will be useful or not, but they are also a very bad to create and use mid combat. You have to either know that you will need a Purification Potion (very hard to foresee), or expend 3 actions to save someone, which will limit your next turn too.

It's very Vancian in the way that you need to take a risk about whether or not Web Vial will be useful.

Now, on the other hand, I just noticed that you can also throw two blasting bomb on the same turn, which may be a damage spike issue?

**Comment by mlenser** [comment]
> I think requiring 3 actions along 2 turns is a bit too much, specially for offensive concoctions

This is the worst-case scenario for when you are unprepared and haven't created the needed concoctions ahead of time.

If you create them ahead of time, then you can use concoctions that normally take two actions as an action. It's one of the tradeoffs of concoctions which is very thematic.

**Comment by mlenser** [comment]
> I just noticed that you can also throw two blasting bombs on the same turn, which may be a damage spike issue...

All the bombs are one action to throw. So if you have two actions you can throw two bombs - the same way that you could cast two spells.

Note: this lets you bypass some of the catalysts limits on a turn. Another of the tradeoffs.

**Comment by mlenser** [comment]
Quick Alchemy removed now that we have two actions as concoctions inherently require a bit more forethought. It is not intended to create them on the fly as needed. That is one of the intended flavor differences of concoctions from spells.
