### ISSUE TITLE
Website doesn't have rules for spell scrolls, only for concoctions

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#699]
https://www.kryxrpg.com/equipment/alchemical-creations

> You can craft and buy concoctions that are available on the Alchemy Power Source, paying the same price as scrolls:
75 sp for 1 catalyst
375 sp for 2 catalysts
1,500 sp for 3 catalysts
6,000 sp for 4 catalysts
25,000 sp for 5 catalysts

This implies that scrolls have the same price, but it's not mentioned anywhere else.  I think a similar table should exist under https://www.kryxrpg.com/equipment/magic-items for example.

The rules could also be expanded to allow for spell tattoos (there's a 5e UA for that), spell wands, and example prices to get magical services - paying a spellcaster to cast a spell for you in a city (such as Dispel Magic, Remove Curse, Ceremony, Detect Magic...).

**Comment by Marcloure** [comment]
> paying a spellcaster to cast a spell for you in a city (such as Dispel Magic, Remove Curse, Ceremony, Detect Magic...)

I was never much a fan of this, since it seems to imply that big cities have someone capable of casting these spells for the right price, or that a priest won't just heal you for free if you fall bleeding on their doorstep. I believe that the 5e lower-magic philosophy defends that there are only a _few_ capable casters, and that the DM will resolve their price for a spell in a case-by-case basis.

**Comment by itamarcu** [comment]
Sure, they can be guidelines, with explicit mention of being up to the GM to decide regarding availability and cost.

But in general - the rules establish guidelines for prices of spell scrolls and concoctions, not to mention some common magic items.  I think each campaign should have its own take on magical economy - but guideline charts like these are pretty important for GMs to come up with an approximate price on the spot.

Personally in most of my campaigns I would expect some churches to offer free healing services (with donations being welcome), some mages that can cast common detection and identification spells for about 20% of the cost of a scroll, and offer higher-power spells and concoctions (3+) only on a case-by-case basis.

**Comment by mlenser** [comment]
Spell scrolls added to the magical items section
