### ISSUE TITLE
Investiture of Waves is in Air

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#70]
Investiture of Waves and Investiture of Waves Potion is in Air, together with Investiture of Wind.

**Comment by mlenser** [comment]
Ya, I saw that. I actually need to remove all the Investiture spells - they combine too many spells into one.

**Comment by Marcloure** [comment]
I can agree with that. We already have elemental bane spells to surpass resistance/immunity, Storm Lord even gives flight. They can also increase weapon damage, which Elemental Weapon spells already do.
