### ISSUE TITLE
Stamina potions vs Mana potions - value seems unbalanced

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#700]
With stamina being valued as x2.5 or x3 of mana, I think [stamina potions](https://www.kryxrpg.com/equipment/alchemical-creations) should give more than they currently do.

Currently for the same price you'd get:
- 1.5 mana vs 2.5 stamina (1d2 vs 1d4)
- 2.5 mana vs 4.5 stamina (1d4 vs 1d8)
- 5 mana vs 9 stamina (2d4 vs 2d8)
etc.

I think it would be better if stamina potions scaled with:  1d6, 2d6, 3d6, 4d6.

**Comment by mlenser** [comment]
Stamina potions amount regained increased
