### ISSUE TITLE
Fire, Ice, etc. Adept feats should work with concoctions

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#701]
I understand why they currently don't, but I think it's reasonable that an incendiary Alchemist creates more reliable and hotter fires.

**Comment by Marcloure** [comment]
Full list is:

- Life Giver (Life)
- Acid Adept / Master (Acid)
- Fire Adept / Master (Fire)
- Ice Adept / Master (Ice)
- Poison Adept / Master (Poison)
- Storm Adept / Master (Storm)

**Comment by mlenser** [comment]
Not sure about this one.. Thematically it makes sense, but concoctions can be given to others. So if you're a fire master and you hand out fire bombs to your allies you could burst a creature quite quickly... 

Though I guess that's true whether you have these feats or not..

**Comment by mlenser** [comment]
Looks like I already did it for Poison Adept and Poison Master

**Comment by Marcloure** [comment]
https://www.kryxrpg.com/feats/life-giver

Life Giver wasn't updated. Not sure if intended.

**Comment by mlenser** [comment]
It was updated to 6th level like the others

**Comment by Marcloure** [comment]
No, I mean it doesn't work with concoctions

**Comment by mlenser** [comment]
Live Giver updated to work with concoctions
