### ISSUE TITLE
Acid Fog concoction

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#702]
Similar to Acid Fog spell, but a concoction instead.

**Comment by Marcloure** [comment]
Example text (damage may need adjusting, not sure if concoctions deal the same damage as spells):

_unstable, 5 min/catalyst_ | _2 catalysts_
As an action, you can create this bomb that contains caustic gas. As an action, a creature can throw this bomb at a point within 30 feet, where it explodes on impact. A green cloud spreads to fill a sphere centered on the impact point. The cloud spreads around corners and is heavily obscured. It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.

A creature that enters the concoction’s area for the first time on a turn or starts its turn there must make a Fortitude saving throw.

On a failed save, a creature takes 2d6 acid damage immediately and additional acid damage equal to half the amount of acid damage dealt at the end of its next turn.

On a successful save, a creature takes half the initial damage and no damage at the end of its next turn. Creatures are affected even if they hold their breath or don’t need to breathe.

The acid slowly eat through objects, creating holes in surfaces, destroying nonmagical items, or dissolving bodies. It takes 1 minute to dissolve nonmagical organic materials such as cloth, plants, or rope, 10 minutes to dissolve wood, and 30 minutes to dissolve bodies and metal.

**Augment**
You can augment this spell with the following options, expending catalysts for each option.
• You can increase the damage by 1d6 for each additional catalyst expended.
• You can expend 1 additional catalyst so duration changes to 1 hour/mana or psi.

**Comment by mlenser** [comment]
I should add similar ones for other themes - I need a bit of free time to tackle this.

**Comment by mlenser** [comment]
- **Acid**
  - Acid Fog Bomb added as a concoction [#702](https://github.com/mlenser/kryx-rpg-issues/issues/702)
- **Fire**
  - Incendiary Cloud Bomb added as a concoction [#702](https://github.com/mlenser/kryx-rpg-issues/issues/702)
- **Ice**
  - Cold Fog Bomb added as a concoction [#702](https://github.com/mlenser/kryx-rpg-issues/issues/702)
- **Plants**
  - Spike Bottle added as a concoction [#702](https://github.com/mlenser/kryx-rpg-issues/issues/702)
- **Poison**
  - Cloudkill Bomb added as a concoction [#702](https://github.com/mlenser/kryx-rpg-issues/issues/702)
- **Storm**
  - Rolling Thunder Bomb added as a concoction [#702](https://github.com/mlenser/kryx-rpg-issues/issues/702)

**Comment by Marcloure** [comment]
Rolling Thunder concocton has:
> It lasts for the duration or until a wind of moderate or greater speed (at least 10 miles per hour) disperses it.

The spell doesn't have it, and I don't think wind should clear this.

**Comment by mlenser** [comment]
Storm Cloud Bomb replaces Rolling Thunder Bomb
