### ISSUE TITLE
Update Giant Insect Liquid to use companions

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#703]
The concoction summons the monster insect, not their companion version like other similar effects.

**Comment by mlenser** [comment]
Can't do this until https://github.com/mlenser/kryx-rpg-issues/issues/86

And if I get monsters to scale their challenge then I might ditch companions (along with rebalancing a bunch of monsters to ensure they match their challenge).

**Comment by Marcloure** [comment]
I don't understand why #8 is so hard, but ok. The point about scaling monsters is fair, maybe there isn't much point in doing much work on Companions for now

**Comment by mlenser** [comment]
> I don't understand why #8 is so hard

Companions have their attack scale. Monsters like centipede break that attack damage scaling with a weak attack and high poison damage. So I'd have to calculate several more things which is not so straightforward.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/111796279-51137b00-88c8-11eb-8d58-e0781bdfb966.png)

Closing this as the current version is "balanced" enough.
