### ISSUE TITLE
Wolf Shifter refers to Pack Tactics maneuver

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#704]
The maneuver was removed long ago, but the Wolf Shifter still refers to it. Maybe it can have pounce instead.

**Comment by mlenser** [comment]
Thanks for pointing this out.

Though Wolves don't pounce though. I can just remove pack tactics.

**Comment by mlenser** [comment]
Removed Pack Tactics from the Wolf Shifter as it was removed long ago
