### ISSUE TITLE
Add Lore to all classes' skill list

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#706]
The skill is currently missing in every class (that I looked at).

Now, hadn't you removed classes' skill lists?

**Comment by mlenser** [comment]
Added Lore to the skill list of each class

**Comment by mlenser** [comment]
> Now, hadn't you removed classes' skill lists?

I remember discussing it, but I never pulled the trigger. I think between Species, Background options, and feats that the current system works pretty ok. If any class is missing a certain skill, let me know!
