### ISSUE TITLE
Slightly increase Companions resilience

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#707]
I think companions can be slightly tankier. 10 HP and 12 Defense maybe be ok at level 1, but that isn't much at 3rd level. That can also be said at 2 mana: 27 HP and 13 Defense can survive a turn at 5th level, but just a bit higher and it can die with a single attack from some enemies.

I think they could gain ~5 HP (or 1 Defense) per tier (so 15 HP at 1 mana, 37 HP at 2 mana, 67 HP at 3 mana, etc.)

**Comment by mlenser** [comment]
Companions have one additional health die

Not sure it's the best option to emulate all creature like this, but it'll be fine for now.
