### ISSUE TITLE
Create a feat for each language

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#708]
Create language feats similar to
- https://www.kryxrpg.com/feats/airy
- https://www.kryxrpg.com/feats/borealis
- https://www.kryxrpg.com/feats/celestial (could be more flavorful)
- https://www.kryxrpg.com/feats/coastal
- https://www.kryxrpg.com/feats/corrosive
- https://www.kryxrpg.com/feats/fiendish (could be more flavorful)
- https://www.kryxrpg.com/feats/fiery
- https://www.kryxrpg.com/feats/stone-speaker
- https://www.kryxrpg.com/feats/wind-speaker

**Comment by itamarcu** [comment]
#### Celestial (update)
> You can speak, read, and write Celestial and whenever you make a Charisma check when interacting with celestials, you have advantage.
> Additionally, as an action you can choose to make your eyes, hair, skin, or halo glow, shedding dim light in a 6-meter radius and dim light for an additional 6 meters.

#### Fiendish (update;  not sure if this is better or worse than the celestial idea)
> You can speak, read, and write Abyssal or Infernal and whenever you make a Charisma check when interacting with fiends, you have advantage.
> Additionally, you learn the Thaumaturgy cantrip, and can cast it only on yourself.

#### Wind Speaker - I think this should be changed to be identical to Airy (or merged).

**Comment by itamarcu** [comment]
For the Elven & Sylvan languages, maybe the wood elf mask of the wilds feature could be copied:

#### Wild Upbringing
> You can speak, read, and write Elven or Sylvan.
> Additionally, you can attempt to hide even when you are only lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena.

**Comment by mlenser** [comment]
> Wind Speaker - I think this should be changed to be identical to Airy (or merged).

Air and Storm should be different. I think the stones part is a typo so I'll remove that, but I think we should be able to come up with a benefit for Storm that is different from Airy.

**Comment by mlenser** [comment]
> Additionally, you can attempt to hide even when you are only lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena.

I would say this is a whole feat by itself.

**Comment by itamarcu** [comment]
For Wind Speaker - maybe rename to "Storm Speaker"?  Plus, idea:
> Additionally, when in stormy conditions such as strong winds or rain, you have advantage on saving throws against slipping or losing your concentration as a result of the weather.

Regarding the elf hiding feat - I think it's worth being half of a feat like that.  That mini-feature lets you hide when lightly obscured by natural terrain, but Goblins get the same thing *plus* when obscured only by a bigger creature (the Stealthy trait), and then there's an actual 2nd level feat in Shadow, [Skulker](https://www.kryxrpg.com/feats/skulker), which lets you hide when lightly obscured by *anything* along with an additional ability to not get noticed if you miss with an attack.

So, power-wise I think it's okay, and the question is if we can think of anything better that doesn't "infringe" upon the Elf species feature.  I was hopeful for this one because it's something someone who grew up with elves could reaosnably learn, but maybe it could be better and more unique.

**Comment by itamarcu** [comment]
Also - I think there should be a super generic feat that gives you a choice of any language plus any Lore, similar to [Master of Intrigue](https://www.kryxrpg.com/feats/master-of-intrigue).

#### Cultural Knowledge
> 2nd
You can speak, read, and write one language of your choice and you become capable, or proficient if you are already capable, with Lore (any subcategories of your choice).

(I tried limiting it to Lore about culture, relevant creature,s etc - but I think the majority of possible lore would fit anyways)

**Comment by mlenser** [comment]
- **Feats**
  - Cultural Knowledge added as a general feat   [#708](https://github.com/mlenser/kryx-rpg-issues/issues/708)
- **Themes**
  - **Storm**
    - Storm Speaker absorbs Storm Guide [#708](https://github.com/mlenser/kryx-rpg-issues/issues/708)

**Comment by mlenser** [comment]
Regarding Elves: The option you're talking about is only available for Wood Elves, not High Elves. I think we should venture down a different path.

**Comment by DalenWBrauner** [comment]
**Dwarven Speaker**
You have immersed yourself in a Dwarven culture. You can speak, read, and write Dwarven, and whenever you make an ability check related to stonework, you roll with advantage.

This might seem like it "infringes" on a core Dwarven trait, but it's such a minor flavor trait that I think could make sense as a _part_ of learning Dwarven. Their language would have developed and changed alongside the very caves some generations spend their whole lifetimes in, lending different stone features as easy reference for different phrases, slang and descriptors.

(Alternatively, Stonecutting could be altered to Proficiency in Lore about Stonework, rather than advantage on ability checks.)

**Comment by DalenWBrauner** [comment]
**Underdark Knowledge**
You have spent a considerable time learning about the lesser-known corners and cultures of the Underdark. You can speak, read and write in Undercommon, and you become capable, or proficient if you are already capable, with two Lore skills related to the Underdark (at your GM's discretion).

**Comment by itamarcu** [comment]
#### Hungry Jaws (a feat for all reptilian species, plus orcs and ogres who are sometimes cannibalistic depending on the setting, and I guess some lycanthropes/shifters could want it too even though they don't have a special language)
> You are a natural carnivore, with a large maw and sharp teeth or strong stomach. You can unhinge your jaw to easily devour your meals, and can even digest flesh and bone.  You can instantly swallow tiny objects and require a minute to consume organic corpses that are a size smaller than you.
> Additionally, you can speak, read, and write Draconic, Orcish, or Jotun.

**Comment by itamarcu** [comment]
#### Heart of the Dragon
> You can speak, read, and write Draconic.
> Additionally, you have advantage on saving throws against being frightened.

**Comment by Marcloure** [comment]
> Hungry Jaws (a feat for all reptilian species, plus orcs and ogres)
I don't think that is a language feat. I think it could be a Beast and Undeath (reflavored as Ghoulish Appetite) feat that also does something else (resistance to poison damage?)

**Comment by DalenWBrauner** [comment]
> #### Heart of the Dragon
So as not to confuse with the Kobold's slightly different trait of the same name, I propose renaming this something like **Draconic Resolve.**

**Comment by mlenser** [comment]
> **Dwarven Speaker**
> You have immersed yourself in a Dwarven culture. You can speak, read, and write Dwarven, and whenever you make an ability check related to stonework, you roll with advantage.

This would not be fitting if you live in a city and learn dwarves living there or if dwarves live in the wild (not underground). It feels like the wrong benefit

https://2e.aonprd.com/Feats.aspx?Traits=54 has some good ideas. https://2e.aonprd.com/Feats.aspx?ID=1 for example might be a good option. We could also provide the language and then a selection of several options including stonework or divinity or other options.

**Comment by mlenser** [comment]
> **Dwarven Speaker**
> You have immersed yourself in a Dwarven culture. You can speak, read, and write Dwarven, and whenever you make an ability check related to stonework, you roll with advantage.

This would not be fitting if you live in a city and learn dwarves living there or if dwarves live in the wild (not underground). It feels like the wrong benefit

https://2e.aonprd.com/Feats.aspx?Traits=54 has some good ideas. https://2e.aonprd.com/Feats.aspx?ID=1 for example might be a good option. We could also provide the language and then a selection of several options including stonework or divinity or other options.

_______________

> Underdark Knowledge
You have spent a considerable time learning about the lesser-known corners and cultures of the Underdark. You can speak, read and write in Undercommon, and you become capable, or proficient if you are already capable, with two Lore skills related to the Underdark (at your GM's discretion).

This feels like a generic option that is something like "You learn a language and two lore skills related to it"

_______________

> #### Heart of the Dragon
> > You can speak, read, and write Draconic.
> > Additionally, you have advantage on saving throws against being frightened.

A Mage who learns Draconic doesn't suddenly become less frightened by monsters. This seems unfitting.

**Comment by mlenser** [comment]
PF2e has some great sources to browse through for each species. The Dwarven feats for example have some good options to build from.

**Comment by Marcloure** [comment]
> A Mage who learns Draconic doesn't suddenly become less frightened by monsters. This seems unfitting.

This argument doesn't make much sense. Other language feats allow you to create fire from your touch, freeze water, emit light from your body, etc. Simply studying the language is not what these feats propose, I believe, but rather immersing yourself into those creatures and their behavior.

**Comment by mlenser** [comment]
> This argument doesn't make much sense. Other language feats allow you to create fire from your touch, freeze water, emit light from your body, etc.

As I wrote on discord the other day:

> The elemental feats are very different in that they are based on magic as those languages are based on an element. Draconic and other languages would not be structured the same.

Draconic is not a magical language. It doesn't give you magic powers or make you resistant to fear.

**Comment by Marcloure** [comment]
Being fearless is not that mystical considering that someone who picks this feat either studied dragons extensively, is pledged or devoulted to them, or lived with them.

Anyway, if you think it doesn't fit, that is settled.

**Comment by mlenser** [comment]
There are several issues with the idea:
- Learning Draconic does not make you a dragon
- Even if it did, dragons are not resistant to fear
- Ssurran know draconic and are not resistant to fear
- Vayemniri know draconic and are not resistant to fear

You could learn Draconic to blend in with Kobolds, Ssurran, and Vayemniri, to learn about dragons themselves, or to learn magical phrases. None of those things would make you resistant to fear besides possibly Kobolds.

**Comment by Marcloure** [comment]
We discussed how the only thing in common between all these creatures are their lizard physiognomy. Sseurran themselves only speak Draconic because, I believe, it's a language that they can speak without trouble, since they don't have any relation to dragons. Even between dragons themselves, their frightful aura is the only common thing they have.

I believe a better feature might exist, but this resistance to fear was the best we could come up with (the same way those scientists from Jurassic Park are much less scared of dinos, enough to touch them).

**Comment by mlenser** [comment]
> We discussed how the only thing in common between all these creatures are their lizard physiognomy.

I responded to your discussion with comments about how it wasn't a direction that I see working. That discussion went down a road that would be appropriate if there was the ability to mix species via feats.

Learning a language does not make you a member of a species or necessarily give you the traits of a species. In this case, the fear resistance isn't even a trait to get from the species. It does not seem like a good fit.

**Comment by Marcloure** [comment]
> Learning a language does not make you a member of a species or necessarily give you the traits of a species.

The advantage against fear didn't come from gaining a trait of dragons, but about being used or fascinated (instead of afraid) to these fearful creatures. Anyway, I guess that is decided.

We still need to find what is culturally common between dragons then.

**Comment by mlenser** [comment]
> We still need to find what is culturally common between dragons then.

We don't. There are a few options:
- A feat that gives Draconic and one of several options that could be fitting
- One feat each for Kobolds, Ssurran, and Vayemniri
- Don't add a feat. Cultural Knowledge can cover it.

**Comment by Marcloure** [comment]
What if this one feat was related to _dragons_ themselves, not just the language? Something like Dragon Disciple, which could give you a primal cantrip or something else? For people who just studied the language or are interested in Ssurrans, there could be another feat or the Cultural Knowledge one (since in their case is just study, not devotion)

**Comment by mlenser** [comment]
Languages are easier to lean from skills now. Feats are still nice if desired, but we have a general feat for these cases worst case.
