### ISSUE TITLE
Forge Armor and Bone Armor take longer to cast than others

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#710]
https://www.kryxrpg.com/spells/bone-armor
https://www.kryxrpg.com/spells/forge-armor

compare to:

https://www.kryxrpg.com/spells/mage-armor (and others)

the first two spells should take 1 action to cast.  I don't think there's a flavor reason for the armor being slower to conjure up, as Undeath can easily animate skeletons and such in a single turn with several other spells.

**Comment by Marcloure** [comment]
Also, forge armor:
![image](https://i.pinimg.com/originals/7a/14/76/7a14762dad5d106fa6d40b86a7750e5e.gif)
right?

Now for some nitpicking, it's funny that Forge Armor creates only light suits of armor.

**Comment by mlenser** [comment]
- **Creation**
  - Forge Armor is now created with an action  [#710](https://github.com/mlenser/kryx-rpg-issues/issues/710)
- **Undeath**
  - Bone Armor is now created with an action  [#710](https://github.com/mlenser/kryx-rpg-issues/issues/710)

**Comment by mlenser** [comment]
> Now for some nitpicking, it's funny that Forge Armor creates only light suits of armor.

You're creating an ad-hoc layer of armor from dirt, wood, plants, or metal. It is not a suit of dwarven forged metal that is better able to protect you. 😃
