### ISSUE TITLE
Hungry Jaws

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#711]
It's a feat for:
- reptiles, orcs, lycanthropes, ghouls, etc - lots of characters would love to have this as an explicit fluff feature, in addition to having actual jaws to bite with
- people who really like eating people
- adventurers who really really need the ability to clean their crime scenes

#### Hungry Jaws / Ghoulish Appetite (2nd, Beast, Undeath)
> You are a natural carnivore, with a large maw and sharp teeth or strong stomach. You can unhinge your jaw to easily devour your meals, and can even digest flesh and bone.  You can instantly swallow tiny objects and require a minute to consume organic corpses that are a size smaller than you.
> Additionally, you have resistance to poison damage and advantage on saving throws against poison.

**Comment by DalenWBrauner** [comment]
I like this feat, but I do not see why a feat about Eating would grant resistance against Poison Damage, which can come from non-ingested sources such as [Envenomed Oil](https://www.kryxrpg.com/concoctions/envenomed-oil) or [Stinking Cloud](https://www.kryxrpg.com/spells/stinking-cloud).

**Comment by itamarcu** [comment]
Yeah, though it's more of a general problem rooted in D&D - poison and venom are different things.

I think it's okay but I'd also be okay with replacing this with "advantage on saving throws against poison and disease".

**Comment by mlenser** [comment]
> reptiles, orcs, lycanthropes, ghouls

Kobolds, Orcs, Ssurran, and Vayemniri don't eat people like snakes.. Ghouls don't exist

> people who really like eating people

Nor do any other species..

_________________

This seems like an exclusive Yuan-ti or Ghoul option if either of those are ever made. Currently I see no thematic fit for this.

**Comment by mlenser** [comment]
Closing this until we have Yuan-ti or Ghoul species.
