### ISSUE TITLE
Githzerai Mind over Body feature

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#712]
When the spell [Mind over Body](https://www.kryxrpg.com/spells/mind-over-body) was rebalanced, the [Githzerai](https://www.kryxrpg.com/character/species/gith) feature with the same name & description was not. While the simplest solution would be to change it to allow you to cast Mind over Body... they actually already have a different feature that grants them exactly that.

As this particular feature seems intended as a counterpart to the Githyanki's **Decadent Mastery**, I think it should be replaced with a new feature that helps reinforce the different identify of the Githzerai.
There are plenty of 1 mana Mind spells that could fit this bill- Call to Mind, Mind Trap, Psychic Fortress, Haze Senses...

The alternative would be to leave this as a unique Githzerei feature, but I suspect that's not ideal.

**Comment by mlenser** [comment]
Mind Over Body as a Githzerai trait was left so they have their own unique feature.

> I think it should be replaced with a new feature that helps reinforce the different identify of the Githzerai.

Do you have a suggestion?

> There are plenty of 1 mana Mind spells that could fit this bill- Call to Mind, Mind Trap, Psychic Fortress, Haze Senses...

Githzerai already have spellcasting in Githzerai Psionics. They shouldn't get more spellcasting.

**Comment by mlenser** [comment]
Closing this until an alterantive is proposed.
