### ISSUE TITLE
2nd level "Skill feats"

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#713]
## There's a general pattern of:
- 2nd level feat
- no prerequisite, except a theme sometimes
- is not a prerequisite to other feats
- increases one skill (to capable or from capable to proficient)
- gives a secondary, minor perk

## Examples: 
- [Actor](https://www.kryxrpg.com/feats/actor), [Athlete](https://www.kryxrpg.com/feats/athlete), [Chirurgeon](https://www.kryxrpg.com/feats/chirurgeon), [Keen Mind](https://www.kryxrpg.com/feats/keen-mind)  - unique ability
- [Emissary of Peace](https://www.kryxrpg.com/feats/emissary-of-peace), [Survivalist](https://www.kryxrpg.com/feats/survivalist) - can apply half proficiency in more situations
- [Acolyte of Nature](https://www.kryxrpg.com/feats/acolyte-of-nature) - bonus cantrip
- [Knowledge Seeker](https://www.kryxrpg.com/feats/knowledge-seeker), [Cultural Knowledge](https://www.kryxrpg.com/feats/cultural-knowledge), [Master of Intrigue](https://www.kryxrpg.com/feats/master-of-intrigue) - bonus language

## Cases that should be fixed:
- [Beguiling Influence](https://www.kryxrpg.com/feats/beguiling-influence)
- [Steady Eye](https://www.kryxrpg.com/feats/steady-eye)
- ~~[Radiant Presence](https://www.kryxrpg.com/feats/radiant-presence)~~ Done
- [Tyrant](https://www.kryxrpg.com/feats/tyrant) - only increase one skill without any other benefit.
- ~~There's also [Competency](https://www.kryxrpg.com/feats/competency) but it's a general feat that works on any skill, so we have some agreement that it's okay if it's a bit weaker than the "specialized" feats.~~ Done

I think we should improve the ones I mentioned as "bad examples" here, to grant a secondary minor benefit.  For stronger skills (e.g. Perception) it's okay if the secondary minor benefit is usually irrelevant - what's more important is that the feat feels good enough to pick and satisfying compared to other options (and compared to gaining the same skill increase through normal leveling).

**Comment by Marcloure** [comment]
**Steady Eye** could give you something like "you can recognize details as small as 10 cm/5 inches across, such as faces or body marks, up to 1 mile away."

**Comment by itamarcu** [comment]
That's nice but I think it's too similar to the Eagle totem:  
> You gain the eyesight of an eagle. You can see up to 2 kilometers away with no difficulty, able to discern even fine details as though looking at something no more than 36 meters away from you. Additionally, dim light doesn’t impose disadvantage on your Perception checks.

But, some other ideas for it... (I'm basing these on PF2e feats such as https://2e.aonprd.com/Feats.aspx?ID=2154)
- If you spend at least 1 minute in a single spot looking into the distance, you have advantage on Perception checks to notice small details in the distance.
- You can quickly search a room, spending only a tenth of the time but suffering disadvantage on your Perception or Investigation check.
- You can take your time searching a room, spending ten times as much time and rolling with advantage on your Perception or Investigation check.

**Comment by itamarcu** [comment]
For **Beguiling Influence** (Charm - persuasion or deception), I think it can just be removed.  We already have Actor, Master of Intrigue, and Emissary of Peace.

Though, I do have an idea for a new one, based on [a PF2E feat](https://2e.aonprd.com/Feats.aspx?ID=2139):

#### Calming Presence (2nd, Courage)
> You become capable, or proficient if you are already capable, with the Persuasion skill.
> Additionally, as an action you can attempt to calm a frightened creature.  Make a persuasion skill check against DC 15.  On a success, the creature is no longer frightened or the fear effect is suppressed until the end of your next turn (at the GM's discretion).

**Comment by itamarcu** [comment]
For **Radiant Presence** (Holy - persuasion or coercion), I suggest:
- Additionally, you know the thaumaturgy cantrip.
- You have a knack for drawing attention to yourself.  You can attempt to Distract creatures using your Persuasion or Coercion skill, instead of your Deception skill.
- You have advantage on saving throws against being frightened.

**Comment by mlenser** [comment]
> For Beguiling Influence (Charm - persuasion or deception), I think it can just be removed. We already have Actor, Master of Intrigue, and Emissary of Peace.

This feat is meant to evoke the flavor of a beguiling fiend/fey, etc. I believe it can be improved.

**Comment by mlenser** [comment]
- **Courage**
  - Calming Presence added as a feat [#713](https://github.com/mlenser/kryx-rpg-issues/issues/713)
- **Holy**
  - Celestial now gives you the thaumaturgy cantrips instead of being able to glow with light [#713](https://github.com/mlenser/kryx-rpg-issues/issues/713)
  - Radiant Presence allows you to glow with light [#713](https://github.com/mlenser/kryx-rpg-issues/issues/713)

**Comment by mlenser** [comment]
Competency gives you capability with a Lore skill as well

**Comment by mlenser** [comment]
Beguiling Influence, Steady Eye, and Tyrant removed as we have enough Skilled features and Competency can cover the need for skills that don’t have unique feats.
