### ISSUE TITLE
Calm Emotions - can be lower mana

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#715]
[Calm Emotions](https://www.kryxrpg.com/spells/calm-emotions) is currently 2 mana to calm emotions for all creatures in a sphere (twice as big as normal).

I think it'd be better if it was a 1 mana spell that calmed the emotions of a single creature, with an augment to add +2 creatures per mana or to change it into a sphere instead of a single target.

**Comment by Marcloure** [comment]
>  an augment to add +2 creatures per mana or to change it into a sphere instead of a single target.

The second option would be better. Calm emotions should work for when you walk into a hostile tavern or witness a generalized fighting and calm everyone there down.

**Comment by mlenser** [comment]
https://www.dndbeyond.com/spells/calm-emotions is the original spell

**Comment by itamarcu** [comment]
Yes, the original spell is 2nd level and works on a group.

I'm saying that this system should change it to a single-target spell at 1 mana, with an augment to make it affect multiple people.

This would be the same direction that we took with spells like Relocate, Slow, Distant Teleport, Telepathic Bond.

**Comment by mlenser** [comment]
It feels like a spell that should affect an area. Stopping a barroom brawl or a marketplace argument are some examples. Single target doesn't seem to match how I envision it.

I'm not set on that direction though. Up for discussion~

**Comment by itamarcu** [comment]
One common scenario I'm imagining is in combat, when you want to remove the frightened or charmed condition on a single ally.  Charm and Courage spellcasters should be able to do this, to temporarily calm someone, even at 1 mana.

**Comment by mlenser** [comment]
Hmm, not sure I'm so fond of this idea. Restoration as a comparison is 2 mana and ends the blinded, deafened, paralyzed, or poisoned condition.

1 mana to supress charmed/frightened seems really strong in certain circumstances. It has some drawbacks like concentration and it doesn't end the condition, but it can be surpressed long enough..

I think a restoration clone at 2 mana, but for charmed/frightened would be more appropriate for your goals. Thoughts?

**Comment by itamarcu** [comment]
I think 1 mana to temporarily calm someone is perfectly balanced, though.  Every spell is really strong in certain circumstances, but in this case...
- Blinded and Paralyzed have [values](https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=2135347575) of 10 and 28, while Charmed and Frightened are 2.5 and 3.5.  Poisoned is 4 which isn't much, but I think there's lots of poisons that cause an additional effect that will be removed by this restoration - such as [Giant Spider](https://www.kryxrpg.com/monsters/giant-spider)'s venom.
- Concentration is a big cost
- Charmed and Frightened will usually not stop a creature from fighting, just make it a bit more difficult for it to fight the way it wants to.  Players who are charmed/frightened, in my experience, will usually either cast spells or use items that ignore those conditions (e.g. heal themselves).

**Comment by mlenser** [comment]
I'm not a fan of the spell in general. Automatically supressing conditions seems beyond what a 1 mana spell should do. Creatures that rely on frightened are nullified by the current Calm Emotions (if they are grouped).

I think 1 mana = reroll attempt, 2 mana = auto success like Restoration.

I'm happy for the same to be applied to Restoration. Deafened and Poisoned are surely weaker so bump blinded and paralyzed up to greater. Then 1 mana for reroll, 2 for auto end. 2 mana for reroll on greater, 3 mana for auto end.

**Comment by mlenser** [comment]
Calm Emotions no longer removed charmed or frightened.

We had a long discussion on discord that didn't lead to any clear path. If there is a need for some kind of spell in Charm that handles what we talked about, feel free to open a new issue with a clear direction.
