### ISSUE TITLE
d3 dice in maneuvers is an uncommon die

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#717]
Quite a few maneuvers (the ones that add a bonus to defence, attack, skills or saves after the roll) use the 1d3/2d3/3d3 progression

The d3 is very weird, usually a d6 divided by 2 round up or a d4, rerrol 4. Rolling 3 of these is unwieldy (imo). Also these don't use the standard (d8) stamina dice. 

I have 2 suggestions (I can go with either) to change that into more common dice:

1. Since we're not using the standard stamina dice anyway, why not change to 1d3/1d4+1/2d4+1. The probability distribution is pretty much the same and the dice are more standard.

2. Use half the stamina dice (round down as usual). 
1d8/2 is sightly better than 1d3, but not by much, small chance of a 4, greater chance of  a 1.
2d8/2 and 3d8/2 are better than 2d3 and 3d3 respectively. A lot more swingy results, but the bell curve and rounding of the dice make the values outside the intended range (2-6 for 2 stamina and 3-9 for 3 stamina) be quite rare.
This solution effectively "buffs" the average, but uses the stamina (d8) dice for all maneuvers.

What do you all think?

**Comment by mlenser** [comment]
d3 = d6: 1/2=1, 3/4=2, 5/6=3.

It's really simple I think.

**Comment by Paulorpribeiro** [comment]
It is simple, but since (stamina)/2 and 1d4+1 is simpler I think it is worth the discussion. I think most players are more comfortable rolling 1d4+1 than a 1d3.

Also, one of the first points of maneuvers was that they all use a d8 so that we could use a stack of dice to track stamina at the table.

**Comment by mlenser** [comment]
> why not change to 1d3/1d4+1/2d4+1

Some issues:
- If you don't like 1d3 then keeping it doesn't make sense
- Enhancement/augment dice are almost always the same as the base dice.
- 2d3 and 1d4+1 do not have the same math.
![image](https://user-images.githubusercontent.com/235857/111885168-5951e000-89c6-11eb-9330-769699623e11.png)
- 1d8/2 is the same "problem" as 1d3. You're still dividing.

All the above suggestions seem much worse to me.

________________

> one of the first points of maneuvers was that they all use a d8 so that we could use a stack of dice to track stamina at the table.

This is a fair point, but half of 1d8 has a weird distribution unless you round up
![image](https://user-images.githubusercontent.com/235857/111885233-d9784580-89c6-11eb-921f-25d6c4f8216e.png)

**Comment by Paulorpribeiro** [comment]
I still think 1d8/2 is better than 1d6/2 just because 1d8 is standard stamina die. But this is also a buff to the maneuver, and your word is last on the balance (you're better than me at balancing things)

Just one last thing, to roll 3d3 you need to:

Roll 1d6/2; repeat 3 times; sum the result. That's why I said it's a hassle.

Half of 3d6 is statistically worse, although easier to roll.

1d3 is fine, 2d3 and 3d3 is the ones I have issues with, because you need to divide and then sum.

My solutions may not be the best, but the problem is still there. Unless it's a problem just for me. People play online mostly nowadays, so perhaps even d5s and d11s could be acceptable

**Comment by mlenser** [comment]
Half of stamina die (1d8/2) could result in 0 so I think that option is off the table as you should always get some benefit of using this.
Rounding up makes it just as good as 1d4 at which point it is just as good as the spell.

Not seeing how either can work, unfortunately.

**Comment by Paulorpribeiro** [comment]
Maybe there is a 3rd solution, let's see of someone else jumps in

**Comment by itamarcu** [comment]
If you're playing digital dice, rolling 1d3 is super easy.

If you're playing with physical dice, you can roll 1d4 and just reroll 4s.  

For example when you need to roll 3d3, you could roll four d4s, get [1, 4, 3], then reroll the 4 to make it [1, 2, 3].

There are also physical d3s sold in some places :P

**Comment by mlenser** [comment]
I would prefer 1d6 over 1d4 reroll 4 as that would require rerolls whereas d6 wouldn't.
d6: 1/2=1, 3/4=2, 5/6=3

**Comment by mlenser** [comment]
Closing this as d3 works and there is no better suggestion.
