### ISSUE TITLE
Write multiple actions limitations on Combat page

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#718]
> You cannot repeat an action to avoid a negative consequence (such as escaping restraints) or to try to impose the same effect on a creature twice. For example you cannot use trip or vicious mockery against a creature if you already used it against the creature this turn.

This rule is written in classes' Extra Action feature, but I think it should also be written in as a general rule somewhere else, since monsters also can have multiple actions

**Comment by mlenser** [comment]
Moved the rule about multiple actions and not being able to impose the same effect to the Combat section.
