### ISSUE TITLE
Move Cloak of Flies to Pestilence 

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#72]
The theme also needs other options to sustain itself.

**Comment by mlenser** [comment]
> The theme also needs other options to sustains itself.

I'll add to it as we discover more that fit the theme. But I'd rather do a smaller theme than try to smoosh the theme into Poison or Death. It's important to do it this way as monsters can be connected to themes. Some monsters for example are connected to Poison, giving them all the Poison spells. I need to be able to provide them only Poison spells, not disease spells as well.
