### ISSUE TITLE
Merge Quick Reflexes into Uncanny Dodge

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#720]
Both are a dodge maneuver, one giving +1d3 to Reflex and the other to Defense. They could be merged with an 'or', like other similar maneuvers and spells are.

With that I mean Uncanny Dodge should gain the benefits of Quick Reflexes, and Quick Reflexes be removed from Skirmish. Quick Reflexes could still remain as is in time, but I don't know why someone would take time for this maneuver.

**Comment by mlenser** [comment]
Quick Reflexes merged into Uncanny Dodge
