### ISSUE TITLE
Infuser Suffused damage seems low

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#721]
Its main damaging ability, Infuse, deals 1d10 damage at 9th level once per turn. This seems low when compared to the Ranger's Weak Spot, which adds +1d6 per hit (so 2d6 or 3d6 at 9th level). We can argue that the Ranger may miss two attacks, dealing only 1d6, so that may be fine.

However, the Bloodrager itself gains 6 powers per turn at 9th level during the rage, so it can assuredly deal 2d6 to two targets per turn (and gains resistance to bps).

I think Infuse should be increased slightly either way, since it only procs once per turn.

**Comment by Marcloure** [comment]
Or rather, maybe it's the Bloodrager damage that is too high? A guaranteed 2d6 vs. two creatures at 9th level is much better than any other damaging feature.

**Comment by mlenser** [comment]
According to the spreadsheet they are quite close using GWF.

![image](https://user-images.githubusercontent.com/235857/111956755-6f0cf580-8aeb-11eb-8a68-4d90ef73fa32.png)

Seems ok at a glance.

Please let me know if you notice an issue with the sheet as that is what I use to balance them.

**Comment by Marcloure** [comment]
![image](https://user-images.githubusercontent.com/29084710/111959734-9e146e80-8acd-11eb-8d59-1953bd1696a5.png)

I'm not sure I'm understanding this correctly, but this 5.1 extra damage seems to be 3 damage from `Mana spell surge damage` times 0.86% of time raged. That is, this seems to consider that the bloodrage deals 1d6 damage per turn while raged, but that isn't true. The bloodrager gains its power limit on each turn, so 2d6 at 9th level.

Additionally, power surge deals 1d6 to two targets or 1d4 + light condition, so it should be valued slightly higher than 3 (maybe round it to 4 instead).

**Comment by Marcloure** [comment]
Wait, I lie. It does multiply 3 * 2. It doesn't even make sense to consider that 3 * 0.86 = 5.1, duh.

However, it still doesn't take into account that it targets two targets, and something still seems off. I'm not really sure how +1d10 with chance to miss once per turn can be equal to +2d6 to two targets with no chance to miss. I'll investigate further.

**Comment by mlenser** [comment]
> it still doesn't take into account that it targets two targets

Damage to a second target is not weighted as much as to the primary target. But I can check this later.


> if the damage is equal, isn't bloodrage automatically better, since it also grants move speed and resistance to BPS? Specially after 9th level, where 4 uses/day is similar to your 85% estimate usage of Infuse.

Resistances to damage is cancelled out by reckless attack. Without using it, the damage would be very low. And when using it, you're very likely to be hit.

Regarding speed: each class/archetype should have something that makes them unique. Bloodrager shouldn't remove the speed as many other cases have unique benefits. If infuser is lacking such an option, then please open another issue to address that.

**Comment by Marcloure** [comment]
> Resistances to damage is cancelled out by reckless attack

Bloodrager doesn't have Reckless though, their damage doesn't depend on that, so the resistance is totally a bonus.

> Bloodrager shouldn't remove the speed

No, I didn't mean to say that. What I meant is that even if the damage is equal for both archetypes, the Bloodrager still has other advantages the Infuser lacks.

**Comment by mlenser** [comment]
Right, bloodrager, not berserker. I'll check later.

> even if the damage is equal for both archetypes, the Bloodrager still has other advantages the Infuser lacks.

DPR is just a calculation of expected damage which I expect to be similar overall across class/archetype options. If other features are not equally worthwhile then please open a new issue identifying which options are subpart.

**Comment by mlenser** [comment]
- Power Surge now calculates damage to two targets (with the second target being half as valuable). Bloodrager’s Bloodrage now scales at 13th level instead of 5th and 13th level.
- Bloodrage now gives temporary health instead of resistance to bludgeoning, piercing, and slashing.
