### ISSUE TITLE
Add a new feature to Infuser Suffused

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#722]
The Infuser has two features that aren't shared with other Suffused: Infuse and Weapon Bond. **Infuse** is a mark that increases damage similar to Ranger's Weak Spot and Avenger's Vow, **Weapon Bond** is mostly a flavor feature that doesn't allow the Infuser to be disarmed. 

Compared to the Bloodrager (which has resistance to BPS and bonus speed while in rage), and with other gish classes, the Infuser lacks another useful feature (since Weapon Bond is mostly flavor-only)

**Comment by mlenser** [comment]
@Marcloure bloodrager no longer has resistance. Could you expand upon he comparison to other gishes? Infuser likely needs something, but I'm not sure how impactful it should be.

**Comment by Marcloure** [comment]
#### Infuser (d8)
- Infuse (extra damage)
- Weapon Bond (can't be disarmed)

#### Bloodrager (d10)
- Bloodrage (extra damage)
- Bloodrage (temporary hp)
- Bloodrage (extra movement)

#### Ranger (d8)
- Hunter's Mark (tracking, advantage on some skills)
- Weak Spot (extra damage)

#### Warden (d10)
- Nature's Wrath (use for **a)** temp hp, **b)** restrain target, or **c)** remove debility)
- Thorn Strike (tiny extra damage; 5th level)

#### Paladin (d10)
- Aura of Protection (+1 or +2 to saves for allies)
- Divine Smite (tiny extra damage)

#### Avenger (d8)
- Reveal the Forsworn (points toward a creature)
- Vow of Enmity (advantage on attacks; tiny extra damage at 5th level)
- Relentless Avenger (follow up on attack of opportunity; 5th level)

#### Spellthief (d8)
- Steal Spell (ignores a spell cast on you and steals it, if it is equal to or lower than your limit)

---

I think the Avenger seems a good target as a balance of cool features and powerful features, but some could gain a feature at 5th level. 

Some outliners seem to be the **Paladin** (could gain a small feature at 5th level), the **Spell Thief** (has only one and actually weakish feature, since it can only steal 1 mana spells until the 9th level), the **Infuser** (Weapon Bond is mostly flavorful), and maybe the **Ranger** (Hunter's Prey is more useful than Reveal the Forsworn, at least)

**Comment by Marcloure** [comment]
I made an update on the Paladin. I hadn't considered that it is the only gish that can use plate armor, giving it 1 additional Defense over the others, so maybe they are good too.

**Comment by mlenser** [comment]
> Well, what I said about the Paladin is not wrong, but is not correct either. The Monk, the Avenger, the Sacred Fist, and the Shifter can also get 18 Defense through their unarmored defense features.

They can only do so at 11th level. Paladin can do it ~5th. Huge difference.

**Comment by Marcloure** [comment]
I think a new improvement that allows for some small effects when Infuse is proced would be nice. Something like choose one of 
- push the target
- slow it
- teleport yourself 1 or 2 meters
- target makes concentration save with disadvantage
- etc.

Effects are just examples.

**Comment by mlenser** [comment]
Infuser and Hexblade both follow this pattern. Suffused and Occultist have a lot of core class features so there is slightly less in the archetype.
