### ISSUE TITLE
Suffused Volatile Power - Fate - needs to be reworked

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#723]
The Suffused's power surge:
> Whenever you expend stamina to use a maneuver, you gain 1 power per stamina die expended. Once on your turn when you cast a spell, use a maneuver, or as an action on a later turn, you can expend power to cause the magic within you to surge as it erupts out from you.

For the Fate theme:
> ***Fate***. You can expend 3 power when you make an attack roll, an ability check, or a saving throw to roll 1d4 and apply the number rolled as a bonus to the roll. You can do so after the roll but before any effects of the roll occur.

This doesn't make sense, being the only power surge that isn't an immediate act, but some sort of a reaction.

I suggest changing it as follows (see bold part):

> ***Fate***. You can expend 3 power **so that once before the end of your turn** when you make an attack roll, an ability check, or a saving throw **you can** roll 1d4 and apply the number rolled as a bonus to the roll. You can do so after the roll but before any effects of the roll occur.

**Comment by mlenser** [comment]
It's still a reaction.

Fate is essentially Twist Fate.
![image](https://user-images.githubusercontent.com/235857/112006525-160d8380-8b24-11eb-802d-8b9869ffc7f9.png)

It should either be removed or reference Twist Fate directly so one can't stack a reaction and this non-reaction.

**Comment by itamarcu** [comment]
My problem with it is that it doesn't follow the usual rules for power surges:

> Once on your turn when you cast a spell, use a maneuver, or as an action on a later turn, you can...

For example, improving your saving throw doesn't really make sense, unless you're fireballing yourself.

**Comment by mlenser** [comment]
I've removed it as an option.
