### ISSUE TITLE
Add more concoctions to Fate

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#724]
The concoction is a 4 catalyst concoction, but Fate has only 1 other, 1 catalyst concoction. Sure, you can pick a lot of feats to get that potion, but I think we should add more concoctions to Fate.

**Comment by Marcloure** [comment]
Remove Curse could be added as a Concoction, but we would still need a 1 catalyst concoction. Personally, I would be fine with removing concoctions from Fate; drinking a potion to see the future is... not unheard of, but I don't know how well that fits the Alchemist fantasy.

**Comment by mlenser** [comment]
Closing this issue as issues should be mostly straight forward. Nebulous issues like "add some options to X" don't have a straight forward path.

If there are clear tasks to add Fate concoctions, please open an issue for each.

**Comment by mlenser** [comment]
> Remove Curse could be added as a Concoction

This is not fitting as a concoction imo.

**Comment by Marcloure** [comment]
The issue is that there is currently no way to pick the Fate concoctions :/

**Comment by mlenser** [comment]
> The issue is that there is currently no way to pick the Fate concoctions :/

Yes there is, feats.

Feel free to suggest concoctions for Fate as their own issues.
