### ISSUE TITLE
Buff Pillar of Command

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#728]
The spell is a 2 mana spell that gives you and someone else an action. Considering that this is used mostly for attacking, the spell deals ~30 damage if both attacks hit. I think the spell could affect 3 targets at 2 mana instead.

**Comment by mlenser** [comment]
Commander’s Strike is in a good spot as it forces you to attack to give another character an attack.

Pillar of Command is not in a great spot. It effectively trades your two actions for 1 action for you and 1 action for an ally. Adding another ally makes it more of an AFK option to just buff up the main DPR character which I really want to avoid.

I think between Commander’s Strike and Clarion Call there isn't much room for Pillar of Command and it should probably be removed.

**Comment by itamarcu** [comment]
A possible solution: buffing it to affect 3-5 creatures but limiting the action to:

> On its turn, it can use an additional action on each of its turns. That action can only be used to make a Stealth check or to use the Dash, Disengage, or Use an Object action.

This would basically limit it to "tactical" actions - troop movements, getting behind cover, repositioning, reloading/switching weapons.  The kind of stuff that a *commander* would be responsible for, to turn a unit of combatants into a stronger force through battle strategy (not through "deal more damage").

**Comment by mlenser** [comment]
Pillar of Command reworked to 1 mana as it now provides utility actions to creatures.
