### ISSUE TITLE
Earthen Grasp should gain more Health per mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#729]
The spell has 10 Health and keeps at that at all mana levels, meaning you can lose a 3 or 4 mana spell to any AOE or single attack that hits (sometimes even half hits can destroy it). It should also have immunity to poison and psychic damage.

**Comment by mlenser** [comment]
Earthen Grasp, Force Hand, and Giant Crawling Claw no longer have health
