### ISSUE TITLE
Concoctions + Antimagic

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#73]
Concoctions cannot be counterspelled (Which is a huge boon, counterspell is amazing) however does an Antimagic Sphere or field block these effects? There doesn't seem to be any rules based on this and it's likely going to come up in our game soon. I would imagine their 'effects' can be dispelled but it's been mentioned that Alchemical Effects aren't necessarily 'magical'.

**Comment by mlenser** [comment]
I've purposefully avoided concoctions becoming "too magical." Concoctions, in flavor, are a mix of checmicals that produce an effect. It is intended that that mixture (concoction) is not magical by nature and therefore areas of Antimagic should have no effect.

That said I haven't thought it through for all concoctions. If you feel any are "too magical" let me know and maybe they shouldn't be concoctions.

**Comment by wherfz** [comment]
Interesting, well in RAW 5e I know you can dispel potions once consumed. Heroism, Oil of Etherealness, etc. can all be dispelled via dispel magic.  With how you've described concoctions these effects would remain until their natural duration ends?

**Comment by mlenser** [comment]
> in RAW 5e I know you can dispel potions once consumed. Heroism, Oil of Etherealness, etc. can all be dispelled via dispel magic

where can I see that ruling? Heroism, and especially Etherealness, are quite magical, but maybe there is a rule already?

**Comment by wherfz** [comment]
https://www.sageadvice.eu/2015/03/24/dispel-magic-potions/
This is what we found a long while ago for potions based on spells at least. I'm unsure if its actually listed anywhere for 5e but this is the closest direct answer I've found.

**Comment by mlenser** [comment]
**RAW Potions:**

- Oil of Etherealness specifically gives you the effect of a spell
- Heroism potion specifically gives you the effect of a spell
- Potion of Flying doesn't
- Potion of Climbing doesn't

______________

Looking through my Concoctions I'm going to stick with:

> Concoctions, in flavor, are a mix of checmicals that produce an effect. It is intended that that mixture (concoction) is not magical by nature and therefore areas of Antimagic should have no effect.

If there are any cases where that doesn't make sense, let me know and I can attempt to solve it.

**Comment by wherfz** [comment]
There are a few more:
- Potion of Mind Reading
- Potion of Invisibility
- Potion of Water Breathing
- Potion of Growth
- Potion of Animal Friendship
- Potion of Gaseous Form, Speed, and Clairvoyance also exist 
I think it's pretty important that these can be dispelled.

Thinking about it more, it may be problematic to have potions as strictly non-magical. They are essentially supernatural. I've always found the argument between magic vs supernatural (dragon breath) a bit odd when it's all, in essence, fantasy magic. From a balanced perspective having these separate effects would mean tracking their sources. If a character is stacking Heroism, Invisibility, and an Aiding potion its extra tedious to figure out which is actually lost due to Antimagic.

In addition, it's powerful that concoctions cannot be counter spelled- having them undispellable would also mean nothing could be done about a Foresight potion (for example) even in an antimagic zone. A spell that even cancels out some attunement items. 

I'm curious for your opinion on this, only recently in our games have we messed with stacking False Life along with other non-concentration spells. It's very fun, but dispel magic exists as a way to counteract this strategy. I like that concoctions are different but having them undispellable could be both tedious for players/DMs and could result in some unfair advantages for intelligent enemies/smart PCs.

**Comment by mlenser** [comment]
> They are essentially supernatural. I've always found the argument between magic vs supernatural (dragon breath) a bit odd when it's all, in essence, fantasy magic

These, and the dragon's breath are not supernatural. A dragon's breath is a chemical reaction, the same as an Ankheg's Acid spray is not magical, but could come from a gland in their body.

Concoctions follow the same logic. For example a Water Breathing Potion could be made from seaweed (Gilliweed in Harry Potter). It is not magical.

____________

> From a balanced perspective having these separate effects would mean tracking their sources [...] its extra tedious to figure out which is actually lost due to Antimagic.

I think it'd be very simple. "Is it a potion? Ok, not magical"

____________

> it's powerful that concoctions cannot be counter spelled- having them undispellable would also mean nothing could be done

Concoctions are so much more limited than spells. They have some perks as well (no concentration), but I would definitely not consider them ignoring magical dispels as OP by any measure - countering/dispelling magic is quite rare and concoctions are still a fair bit behind spells.

> Potion of Mind Reading, Potion of Animal Friendship, Potion of Gaseous Form

I purposefully don't have these in my system (nor Etherealness or Heroism) as they are too magical.

> Clairvoyance

This case is a bit different from the spell version as there is no sensor. It borders the edge and maybe goes too far over it.

____________

> nothing could be done about a Foresight potion

Foresight is a very high level catalyst. It's strong, but not OP by any means.

____________

> stacking False Life along with other non-concentration spells

14 tHP pre-buff is quite strong. Though it costs a fair number of resources at low levels.. I probably wouldn't be too worried, though maybe there is more to this story?

**Comment by mlenser** [comment]
Clairvoyance Potion will be removed when I release tomorrow.

**Comment by wherfz** [comment]
> You can't dispel magic every fight, or even more than 5% of fights without it being GM vs players. If there is a problem with things stacking then that should be fixed. It shouldn't require GMs to counter.

To clarify, in our game there can be a lot of player versus player. NPCs are created based on what players can get with plenty of creative exceptions to make it interesting. For players, antimagic very easy to get. Counterspell and dispel magic are just a feat away. Any level 3 full caster could receive it. Just going by the monster manual dispel magic and the strategies used are considerably rarer. We might just have to houserule things to play how we like to play! In the current campaign, setting magic is very common and well known- the higher CR individuals know how to strategize and thus know having an ally/minions with counterspell is very effective.

> Concoctions follow the same logic. For example a Water Breathing Potion could be made from seaweed (Gilliweed in Harry Potter). It is not magical.

I still find Gilliweed very magical/supernatural but it isn't the same as weaving a spell out in the air. I know Dungeons and Dragons has strict definitions of what is magical but these alchemical concoctions like gilliweed border on the fantastical. I like that they can be a little wild. I suppose it's just odd that antimagic doesn't work on some fantastical things as it does others.

**Comment by Marcloure** [comment]
I understand what you mean. I have always found strange that psionics couldn't be countered or dispelled in past editions, in my head they're still a kind of magic.

But then we also have invisible fungus, troll regeneration, and a nightwalker's aura of annihilation, all of which I don't think is magic at all. While I don't think you can make a potion for a nightwalker's heart, you can indeed from the fungus or the troll, or from some other weird root.

**Comment by mlenser** [comment]
## Concoctions are science, not magic

They are not supernatural or magical - they are chemical. They are only "magical" in the concept of anything that humans don't understand is magical. Guns, before they were understood, would be considered magical. But like the chemical reaction that occurs when a gun fires, a similar reaction would happen when a bottle of flammable fire ignites.
A gun wouldn't stop working in an antimagic field. Neither should other chemical reactions.


__________________________

> in our game there can be a lot of player versus player. NPCs are created based on what players can get with plenty of creative exceptions to make it interesting.

If you're talking about PvP then Alchemists are significantly behind a caster in so many regards. For example Concoctions are built to do AoE damage by default so their damage is less than a single target spell. I definitely would not try to make dispel magic apply here to balance this out.
