### ISSUE TITLE
Feral Senses and Echolocation

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#733]
The blindsight from Echolocation should fulfill the same utility Feral Senses does with additional range. From my understanding, Blindsight works like tremor sense, in a specific radius around the character. Thus, invisibility does not matter within a 30ft radius, nor does stealth. You cannot stealth with something directly looking at you. If you are in the radius of blindsight you are seen.

This issues goes into the specific uses of blindsight. Between tables/GMs and arguments online there isn't a solid answer for this:
[Sage Advice and Clarifications on Blindsight](https://www.reddit.com/r/AdventurersLeague/comments/cnbdn8/blindsight_faqs/)
There are a number of contradictions on how blindsight even works— so perhaps this is a moot point! 

I believe Echolocation should have a smaller blindsight range. 20ft (if we are running blindsight more powerfully, able to see invisibility notice anything inside)

 Otherwise, the feats are fine. Though I may start an issue on defining what Blindsight can/can't do.

**Comment by mlenser** [comment]
Hey Wherf, nice to see you around again.

Some clarifications: 

> nor does stealth

Stealth could hide you from Blindsight as Blindsight is based on sound so if Stealth causes you to make no sound, then blindsight wouldn't detect you.

> You cannot stealth with something directly looking at you. If you are in the radius of blindsight you are seen.

Technically Stealth says "You can’t hide from a creature that can **see** you clearly" so RAW it wouldn't apply. I would say RAI would be "You can’t hide from a creature that can see **or hear** you clearly".

________________

In general, Echolocation should be stronger than Feral Senses, but it requires specific requirements that only rare characters could meet so I think that's ok.

I think another issue to define what Blindsight is would be good.

**Comment by mlenser** [comment]
Closing this as #734 can cover this blindsight discussion. I think these two feats are ok based on above, but let me know if someone thinks otherwise.

**Comment by itamarcu** [comment]
Creatures shouldn't be able to hide from echolocation - even if you're standing completely still, echolocation will still tell the bat where you are (even if not your exact shape).

But I'd personally just say that not all Blindsights are the same, and it's up to the GM to decide sometimes.  There's heightened senses (Dragons), echolocation (bats), and magical I-know-everything-that-happens-in-this-radius (high level magic bullshit, maybe mimics/oozes use this, unsure about lore).  Sometimes you can hide by being quiet, sometimes you can hide by floating, sometimes you can hide by being out of the range.

**Comment by mlenser** [comment]
Echolocation is unique from blindsight. One can hide from blindsight. Hiding from echolocation is likely a lost cause unless you do the trick that bad guys do against daredevil: make loud noises so echolocation stops working.
