### ISSUE TITLE
Defining Blindsight

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#734]
Defined in 5e...

> Blindsight (monster ability) A creature with blindsight can perceive its surroundings without relying on sight, within a specific radius. Creatures without eyes, such as oozes, and creatures with echolocation or heightened senses, such as bats and true dragons, have this sense.
[Sage Advice on Blindsight](https://www.reddit.com/r/AdventurersLeague/comments/cnbdn8/blindsight_faqs/ )

Blindsight has the potential to be extremely powerful or outright ignorable based on the rules. Unfortunately the rules as written isn't very clear on what blindsight **is**. 

**Why does this matter**
1. Blindsight is a way to see without seeing directly. Thus, allowing certain creatures to notice others while they are stealthing around. Taking the rules in one respect: It should be nearly impossible to sneak around a dragon or a slime if you get within 30ft of the creature (or 60ft for older dragons). 
2. Creatures with blindsight, much like those with tremorsense, should be identified by the party ahead of time in order to counteract this special ability.
3. Taking the rules another way makes Blindsight nearly useless. It cannot see through cover, its soundbased so you just need to move quietly or use the 1 mana silence spell. Its essentially a weaker darkvision.
4. Many powerful creatures in DnD have blindsight. It is meant to be some sort of higher sense or sixth sense given that most creatures past CR 20 have this ability with some exceptions. 

**Things that Blindsight unarguably does**
1. Negates Illusionary spells like Blur and Mirror Image, where optical illusions provide disadvantage on attack rolls.
2. Counters Invisibility
3. Counters Fog Cloud, Darkness, etc.
4. (See the Reddit Link for a small list of debatable topics and things Blindsight does not appear to negate)

**Contradictions/Issues in Defining Blindsight**
1. Echolocation is a type of blindsight, but all blindsight does not appear to be echolocation.
2. Despite Blindsight being 'sound' based for some creatures, other creatures can still hide behind 'cover' with a stealth check (example in Sage Advise link). If it was sound based this doesn't make much sense unless the cover is soundproof.
3. Blindsight lets you notice creatures that are invisible or those in the cover of Magical Darkness, Ash, or Fog. For some reason, solid cover works, but gases, and liquids do not work,
4. Another quote states "You can't hide from a creature if you're in its blindsight radius, unless magic cloaks your presence entirely." The only example I can think of for magic cloaking presence entirely is planar magic such as hiding on the ethereal plane.

**Things I've Considered for my game:**
1. It is a high level ability. Many extremely high CR creatures have blindsight. Only rarely do low CR creatures have it. (Oozes can only see with blindsight)
2. In RAW 5e blindsight is unavailable to player characters. Rogues do get an almost equivalent ability called Blindsense.
3. In Pathfinder Blindsense and Blindsight are different things. Blindsense allows you to see anything in the radius. 
4. 'En' from Hunter x Hunter is similar to blindsight/sense. One of the few pieces of media that has this 'touchsense' visualized and [explained](https://hunterxhunter.fandom.com/wiki/Nen#En).

What is the best way to define blindsight? 
Can it see behind cover? Through walls? All illusions? How do we categorize it it from truesight and tremorsense?

**Comment by Marcloure** [comment]
Blindsight can be sound, yes, but also smell, thermal sense, or insect antenna which can sense air motion and other signals. Hiding from sound blindsight simply means you are not making a noise. From smell and temperature it's a bit more difficult to justify, but I guess you can mask it with the environment.

**Comment by mlenser** [comment]
> Its essentially a weaker darkvision.

Blindsight is much stronger than Darkvision. Darkvision gives disadvantage on Perception in darkness as it is dim light. Blindsight does not.

> Negates Illusionary spells like Blur and Mirror Image, where optical illusions provide disadvantage on attack rolls.

Stronger illusions create other senses like smell so I wouldn't say it negates all illusions, but some/most.

> Counters Invisibility, Fog Cloud, Darkness, etc.

These are based on vision, so yes Blindsight would not be affected by them

> Despite Blindsight being 'sound' based for some creatures, other creatures can still hide behind 'cover' with a stealth check (example in Sage Advise link). If it was sound based this doesn't make much sense unless the cover is soundproof.

Cover is not required as the stealth rules state "You can’t hide from a creature that can see you clearly" which has nothing to do with smell. Hiding from sound based blindsight is possible.

> Blindsight lets you notice creatures that are invisible or those in the cover of Magical Darkness, Ash, or Fog.

Invisible doesn't make you unnoticed (hidden). That requires Stealth. Stealth still works against Blindsight.

> For some reason, solid cover works, but gases, and liquids do not work

Not sure what this is refering to.

> Another quote states "You can't hide from a creature if you're in its blindsight radius, unless magic cloaks your presence entirely." The only example I can think of for magic cloaking presence entirely is planar magic such as hiding on the ethereal plane.

I don't see this text anywhere in my rules. Is it somewhere in the books?

_____________


From the questions raised here, blindsight seems pretty clear to me and many of the issues seem like rule misunderstandings.

**Comment by wherfz** [comment]
The issue on fog/gases is wrong! I misread something.

> I don't see this text anywhere in my rules. Is it somewhere in the books?
No, it was a clarification tweet from one of the creators of the rules. Found in the link I gave.

**Comment by mlenser** [comment]
Is there anything that needs to be clarified? I'm unsure what needs to be done here.

**Comment by mlenser** [comment]
Closing this issue as it feels clear to me. If there things that need to be clarified, please point them out specifically.
