### ISSUE TITLE
Naturalist: add an alternative to Feral Instinct

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#735]
Many themes wouldn't fit this feature (plants, elemental, spirit, etc). Either replace it or offer one of several features.

**Comment by mlenser** [comment]
Done

**Comment by Marcloure** [comment]
A late suggestion: an option that gives resistance to an elemental type could offer support to an Elementalist Druid (although there are feats for this as well).

**Comment by mlenser** [comment]
Feats and spells that absorb certain damage types cover that
