### ISSUE TITLE
Ferrous Growth should limit to 1 object at a time

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#738]
Similar to other spells, this spell shouldn't allow you to cast it a few times and make a whole thieves' kit or a set of items

**Comment by mlenser** [comment]
What other spells are limited so I can follow that pattern?

**Comment by Marcloure** [comment]
**Minor Illusion:** The illusion also ends if you dismiss it on your turn (no action required) or cast this spell again.

**Prestidigitation:** If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect on your turn (no action required).

**Shape Water / Mold Earth:** If you cast this spell multiple times, you can have no more than two of its non-instantaneous effects active at a time, and you can dismiss such an effect on your turn (no action required).

---

Just noticed Creation doesn't have a create trinket cantrip.

**Comment by mlenser** [comment]
Ferrous Growth limited to two objects.

**Comment by Marcloure** [comment]
Also, just a detail, can Ferrous Growth create tiny and intricate objects, like a pair of lock picks? The spell doesn't specify that it can't, but it only uses larger objects as examples.

**Comment by mlenser** [comment]
Up to the GM. I would say no.
