### ISSUE TITLE
Encumbrance calculations should depend on carrying capacity

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#742]
https://www.kryxrpg.com/rules/abilities

> If you carry weight in excess of 50 + your Strength × 10, you are slowed 1.

> If you carry weight in excess of 100 + your Strength × 20, up to your maximum carrying capacity, you are slowed 2 and you have disadvantage on ability checks and attack rolls that use Strength or Dexterity.

These should instead say something like:

> If you carry weight in excess of a third of your carrying capacity (usually 50 + your Strength × 10), you are slowed 1.
> If you carry weight in excess of two thirds of your carrying capacity (usually 100 + your Strength × 20), up to your maximum carrying capacity, you are slowed 2 and you have disadvantage on ability checks and attack rolls that use Strength or Dexterity.

This is because there are lots of things that affect your carrying capacity - your creature size, your species - and those should similarly increase the encumbrance thresholds.

**Comment by mlenser** [comment]
Please use metric when opening issues about things as that is what the data is stored in.

**Comment by mlenser** [comment]
Encumbrance is now one-third and two-thirds of your carrying capacity.
