### ISSUE TITLE
Unburden spell

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#745]
Similar to #743 - I want to add a spell that helps with carrying heavy stuff.  The first spell was something you put on items to make them lighter, and this suggestion is for something you put on a creature to make it carry more.

> **Unburden** (1 mana) (gravity, telekinesis)
> *3 hours/mana or psi*
> As an action, a creature you touch is surrounded with invisible force that helps it push, drag or lift objects for the duration.  Until the spell ends, the creature's carrying capacity is doubled.  

This could also potentially work as an Alteration, mechanically, though the flavor would change.  Force already has Force Disk so it doesn't need such a spell.

As a concoction, it could be "Potion of Heavy Lifting", or "...Unburdening", maybe a different theme.

**Comment by mlenser** [comment]
Bull's Strength (in bestial transformation) has 
> You have advantage on strength checks and your carrying capacity doubles.

so this is just a less versatile and less useful spell overall..

**Comment by itamarcu** [comment]
This spell's duration is longer than Bull's Strength (3 vs 1 hours, per mana) but additional benefits could be added, too, if this needs to be better.  My goal is to make it roughly as useful as Tenser's Disk (which is basically a free +500 lb).

Alternative or additional benefits:
- You can ignore the Heavy property of weapons
- You can ignore the speed reduction of armors you don't have the minimum Strength for
- You have advantage on Brawn checks
- You can double your distance with thrown weapons and objects
- triple instead of double
- carrying capacity is increased by 500 lb, instead of double

**Comment by mlenser** [comment]
I can't see how this is gravity spell as it is not applying to the object, but a person. Gravity doesn't make someone stronger unless they're in some kind of gravity field.
Telekinesis: same situation.

If anything this should be an alteration spell that makes someone stronger like bull's strength.

**Comment by mlenser** [comment]
Powerful Build spell and potion added to the Alteration theme.

> As an action, you body becomes more bulky and powerful. You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.
