### ISSUE TITLE
Give disease immunity to Druid's Timeless Body

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#746]
>Timeless Body
>The primal magic that you wield causes you to age more slowly. For every 10 years that pass, your body ages only 1 year.

The druid could become immune to diseases with this feature as well, to make it slightly more impactful.

**Comment by mlenser** [comment]
I went the other direction and removed it from the Psionicist's Timeless body. Characters shouldn't be so easily immune to diseases.
