### ISSUE TITLE
Guardian has a spell but isn't in a power source

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#747]
Guardian theme has a single spell, but the theme isn't in any power source. I think the spell could be moved to life.

**Comment by itamarcu** [comment]
for context - the spell is [Dampen Pain](https://www.kryxrpg.com/spells/dampen-pain).  Personally, I think it could also fit in the Death theme, since that theme is doing a lot with harm, wounds, and pain.  e.g. [Share Pain](https://www.kryxrpg.com/spells/share-pain) is there.

**Comment by mlenser** [comment]
Dampen Pain moved to Death, Life, and Undeath. It now only works on you so it has had the amount increased slightly. It has an augment to use on another creature.
