### ISSUE TITLE
Carry capacity and warhorses

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#748]
A warhorse has 4 Str, which gives it an unencumbered carry capacity of ~85 Kg.

**Math:**
70 + 4*15 = 130 base carrying capacity
130 * 2 = 260 Large carrying capacity
a third of 260 is ~85

The issue is: this means a warhorse can barely carry a naked strong male human (~80-90 Kg) without being slowed 1, which surely isn't right. Either warhorses (and horses, and possibly many other creatures) should have considerable more Strength, or some rules need to be tweaked.

**Comment by mlenser** [comment]
By RAW 16*5 = 80 lb (36 kg). Double that for large and you're at 160 lb (72 kg). So my system provides more than RAW.

I assume WotC would say "these rules are for player characters". I agree and don't think this is worth addressing.

**Comment by mlenser** [comment]
RAW carrying capacity:
![image](https://user-images.githubusercontent.com/235857/113486357-8caa6980-94b2-11eb-950a-50502f6528bb.png)

Following the carrying capacity = 3x encumbrance we end up with 540/3 = 180 lb = 81 kg.

So similar to my system.

**Comment by mlenser** [comment]
Several threads on the topic:
- https://www.reddit.com/r/dndnext/comments/3g3t0l/a_question_about_encumbrance/
- https://www.reddit.com/r/DMAcademy/comments/bnjcsr/5e_mounts_and_variant_emcumberance_question/

I agree with one statement in the second one: "Based on my googling, I'd say more than 100kg would slow down a horse somewhat. DnD horses have a pretty high move speed. Dropping 10ft off for carrying 200kg isn't going to be the end of the world, either."
