### ISSUE TITLE
Isnt poisoned and diseased the exact same condition?

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#751]
At least in their description under rules they have the exact same text

A poisoned/diseased creature has disadvantage on attack rolls and ability checks.

**Comment by itamarcu** [comment]
From discord:
> Several reasons:
> - being poisoned is not the same, thematically, as being diseased
> - creatures can have immunity to one, but not the other
> - poisons sometimes have additional effects. Diseases always do.

Still, I think maybe it could look as less of a "bug" if the Conditions rule page had "Poisoned / Diseased" before the rules text.

![image](https://user-images.githubusercontent.com/6516621/113551213-f2a30800-95fc-11eb-98de-b19f3cb2185e.png)

**Comment by Paulorpribeiro** [comment]
I see. Haven't had time to follow the discord lately. But I think conditions need to be  mechanically different to avoid overlap. If you double a condition because a creature that is immune should get that "adverse effect" from another source, the list will just bloat. We will be creating a frightened condition for "half turned" undead and maybe we stumble upon a way to restrain a swarm, and create another condition to that too.
The drive for creating new conditions (imo) should be new mechanics that  need to be translated into rules, not repeating them with different names. No disrespect for the decision to include diseased as a copy of poison delivered differently

**Comment by mlenser** [comment]
Diseased and poisons are different. They are not the same thing.

**Comment by mlenser** [comment]
Added some words to differentiate them a bit a bit ago:
![image](https://user-images.githubusercontent.com/235857/113570640-0e1a0d00-9615-11eb-99b0-cd8ff6ecb78d.png)
![image](https://user-images.githubusercontent.com/235857/113570645-12462a80-9615-11eb-86c7-3d632b514af4.png)
