### ISSUE TITLE
Wall of Sand and Wall of Water - small suggestions for improvements

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#752]
I think [Wall of Water](https://www.kryxrpg.com/spells/wall-of-water) and [Wall of Sand](https://www.kryxrpg.com/spells/wall-of-sand) should be made a bit more consistent

- Wall of Sand is "move at half speed" while Wall of Water is "difficult terrain";  I think both should be difficult terrain, but maybe the other way around is preferable for some reason
- Wall of Water - "any ranged weapon attack that enters the wall’s space has disadvantage on the attack roll" - I think this should be all ranged attacks.  Catapult, Mold Earth, Snowball, Acid Arrow - all of those should be slowed down by the water being in the way.
- Would be nice if Wall of Sand had an augment to make it denser, so people could walk on it (i.e. making a sand dune ramp);  to either fully prevent movement through it or make it something like a 4:1 ratio.  It would still keep it half as long as wall of stone, so that theme's "Specialty" won't be threatened.

**Comment by mlenser** [comment]
Walls updated to have consistent wording. Those that limit movement (Sand, Thorns, Water) have consistent wording structure that says the movement costs more.

## Moving through

 I went with this for Wall of Sand and Wall of Thorns:
 > A creature must spend 4.5 meters of movement for every 1.5 meters it moves through the wall.

and this for Wall of Water:
> A creature must spend 3 meters of movement for every 1.5 meters it moves through the wall.

This is similar to Wall of Sand's RAW wording.

## Attacks

I made it any attack as suggested

## Augment

Not sure about thickening a wall of sand. Generally there isn't much a fantasy of that as sand falls apart with little pressure. If you feel like there is something here, please formalize the wording as a new issue with some examples in some fantasy context so I can understand better.
