### ISSUE TITLE
Re-add "Trinket" cantrip to Creation theme

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#753]
This used to be an existing cantrip, so the wording could be copied from there.

[Form Ice](https://www.kryxrpg.com/spells/form-ice)'s 4th bullet point can do a partial version of this already.  This cantrip should be better than that, because it's the Creation theme and because it can't be used for other purposes.  Another reference to be potentially used is the 5e conjuration wizard ability.

**Comment by mlenser** [comment]
Please suggest a full wodring if "This cantrip should be better than that"

**Comment by itamarcu** [comment]
@mlenser Could you show the original Trinket wording?  (I assume you have it in the git repository)

**Comment by itamarcu** [comment]
from Form Ice:
> You can create an item by freezing water or forming snow or ice. The item created cannot exceed half a cubic meter in volume. It melts after 5 minutes or if it is exposed to extreme heat or a flame. Objects created in this manner may be used as tools, but they are too fragile to be extensively used. They are also too fragile to be used as weapons except for arrows, bolts, bullets, and darts (casting this spell will create up to three of such at once).

from Prestidigitation:
> You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn.

from 5e's Minor Conjuration:
> you can use your action to conjure up an inanimate object in your hand or on the ground in an unoccupied space that you can see within 10 feet of you. This object can be no larger than 3 feet on a side and weigh no more than 10 pounds, and its form must be that of a nonmagical object that you have seen. The object is visibly magical, radiating dim light out to 5 feet.
> The object disappears after 1 hour, when you use this feature again, if it takes any damage, or if it deals any damage.

**Comment by mlenser** [comment]
> This used to be an existing cantrip

Note: This can't be true since no one noticed its disappearance to Ice Trinket in June 2020 and from Ice Trinket to Form Ice in November 2020.

**Comment by mlenser** [comment]
Looking at the spell, I don't see the point of it. You create a super small tiny object. For what? Seems like a waste of a cantrip for 99.9% of people.

**Comment by Marcloure** [comment]
Being a waste doesn't make it useless. It's like saying Druidcraft is a waste of a cantrip. A lot of characters have enough damage cantrips to want more of those, and they often go for "fun or roleplay-y" cantrips. Maybe they want to be able to perform small party tricks, or to be able to create the spoon they'll use to eat.

Many times when I play a wizard in 5e, I grab prestidigitation solely to keep myself clean or to flavor my food just right. Small, useless things that are cool to have when you are already covered on the damage side.

**Comment by mlenser** [comment]
Druidcraft and Prestidigitation have all kinds of options, similar to Thaumaturgy. They can be used commonly.

Trinket on the other hand cannot really be used commonly.

> Also, it's not like Mending is that much more useful than creating small objects is.

Mending would be used very often if you're on board a ship, or drive a wagon, or all kinds of other scenarios. Not all the time by everyone, but often by some people.

**Comment by mlenser** [comment]
Closing this as I removed Trinket for precisely this reason: It is not something that is useful.

If someone wants to expand upon it and make it as useful as Druidcraft, Form Ice, Prestidigitation, and Thaumaturgy then please do so.
The old wording isn't sufficient for a cantrip.
