### ISSUE TITLE
Add initiative rules for creatures joining in the middle of a fight

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#754]
In https://www.kryxrpg.com/rules/combat I think a rule should be added about creatures that join in the middle of combat and roll initiative for themselves.  Generally, effects like the [Kobold Inventor](https://www.kryxrpg.com/monsters/kobold-inventor)'s Basket of Centipedes, or any spell that creates a [Companion](https://www.kryxrpg.com/character/companion), say:
> ... emerges from the basket and rolls initiative
> ... it rolls its own initiative and acts on its own turn.

My suggestion for a rule:

> If a creature joins the combat during another creature's turn and its initiative roll is higher than the initiative roll of the current creature's turn, it acts immediately after the current creature's turn, and maintains that position in the initiative order.

Explanation:
- If the new creature just rolls and uses its result, it might roll higher than the current creature's turn and thus basically lose its turn for the current round.  For example, in a fight where ten creatures roll 1.....10 and on creature 5's turn it summons an Air Elemental companion, that companion could roll a 4 to act right after its summoner, or it could roll a 6 and act only much later, in the next round.  This can create a wrong incentive, to summon lower-dexterity companions or to reduce their initiative roll with special abilities.
- If the new creature always goes after its summoner, it's fine but it removes the diversity of initiative (and nerfs companion dexterity a little bit)
- If the new creature goes immediately after the summoner in this round but then uses the real roll on the next round, it can potentially lead to that creature taking 2 turns before its enemies take even one turn.

**Comment by mlenser** [comment]
Added a clarification to initiative for when a creature joins combat while it is in progress.
