### ISSUE TITLE
Gravity Defying feat mentions "cosmos" instead of "gravity" in prerequisites

### ISSUE THREAD

**Issue by sjlevin** [mlenser/kryx-rpg-issues#756]
**Describe the bug**
The Gravity Defying feat has a prerequisite that mentions "cosmos" instead of "gravity". Cosmos is no longer a theme.

**Link**
https://www.kryxrpg.com/feats/gravity-defying

**Comment by mlenser** [comment]
Thanks for the issue!

This will be fixed soon. I'm having issues with my build provider right now, but when that is resolved this will go out.
