### ISSUE TITLE
Mage's Spell Mastery is boring and underpowered

### ISSUE THREAD

**Issue by sjlevin** [mlenser/kryx-rpg-issues#757]
**Is your feature request related to a problem? Please describe.**
The Mage's level 17 ability Spell Mastery is boring and underpowered. It essentially grants a bonus 6 mana per short or long rest, but only for specific unaugmented abilities.

Compare this to the Psionicist's Psychic Transcendence that refreshes 10 psi over 1 minute plus a bunch of other features for that 1 minute. It can also be refreshed every short or long rest.

Suffused has something similar with Metamorphosis where they regain up to 13-15 mana (depending on how much is already spent) once per long rest while also gaining additional features for an hour.

Since characters can only benefit from two short rests before taking a long rest, this comes out to (per long rest):
Mage: 12 mana (limited functionality)
Psionicist: 20 psi plus 2 minutes awesome
Suffused: 13-15 mana plus 1 hour awesome

**Describe the solution you'd like**
I am a big fan of the D&D 5E Wizard's Spell Mastery feature where it makes two unaugmented spells essentially become cantrips. I would recommend something similar here by removing the mention of requiring short or long rests.

**Describe alternatives you've considered**
Choose one spell that cost 1 mana and one spell that costs up to 2 mana. You an cast each of them at their lowest mana cost without expending mana. By spending 8 hours in study, you can exchange one or all of the spells you choose for different spells of the same mana costs.

**Comment by mlenser** [comment]
Ah, I missed this wording when I combined Spell Mastery and Signature Spells: `When you do so, you can’t do so again until you finish a short or long rest.`

I'll check this over.

Making a 1 mana spell a cantrip could be problematic though as 1 mana spells produce ~15 "damage value" while a cantrip at that level is ~9. Brief math says this is ~20% more DPR than all other casters and more than martials..

**Comment by sjlevin** [comment]
I don't really see a big problem with essentially making a super cantrip. The Mage gets two super cantrips while Psionicist and Suffused get more mana/psi which can be used to cast more big spells.

**Comment by mlenser** [comment]
Ignoring the potential math problem for a second: using RAW sounds like the opposite solution that this issue was raised for. A "super cantrip" that you can spam after you run out of mana sounds like the definition of boring. Studying spells could also easily lean into metamagic and the ability to alter your spells which seems much more interesting and fulfilling to play.

**Comment by sjlevin** [comment]
I was more imagining a Mage who has a favorite spell (ex: Telekinesis). After using it so much for a whole adventure, the Mage has gained mastery over it and can cast its base version as much as they like.

I personally feel that choosing a spell that does damage as a Mastery spell is a waste of potential, but I understand that you need to balance for people who feel differently.

**Comment by mlenser** [comment]
I've given mage a bit more identity.

Arcane Inspiration can now be used twice per rest at 13th level.

And added this feature which I think the mastery can build off of. I'll think through some options.
![image](https://user-images.githubusercontent.com/235857/114265766-f49d0a80-99f2-11eb-8b0c-aa9a5b6d185d.png)

**Comment by mlenser** [comment]
My thoughts:

At 17th level a mage picks two spells, one 1 mana and one 2 mana. It then assigns a metamagic option and a greater metamagic between them. The spells are then unique like we see with other spells in 5e like "ARCANIST's magic spell".

The main concern is that it makes 2 spells "better than others" which could limit options like the RAW Eldritch Blast does.

**Comment by sjlevin** [comment]
The Psionicist, Acolyte, Naturalist, and Suffused all have a Level 17 feature where they become awesome for a short time. Why not do something similar for Mage? It would be especially thematic if it granted features from the Antimagic theme like [Reddopsi](https://www.kryxrpg.com/spells/reddopsi).

For example:
*Flavor test*. For 1 minute:
* Regain 1 mana at the start of your turn.
* Gain effects of [Reddopsi](https://www.kryxrpg.com/spells/reddopsi)
* Gain effects of [Detect Magic](https://www.kryxrpg.com/spells/detect-magic)
* Gain effects of [Mage Armor](https://www.kryxrpg.com/spells/mage-armor)

**Comment by mlenser** [comment]
> The Psionicist, Acolyte, Naturalist, and Suffused all have a Level 17 feature where they become awesome for a short time. Why not do something similar for Mage?

Because not all 17th level features should be the same. Also many of those are very thematic. A Mage doesn't have a thematic option like that at face value. Their emphasis is all about mastering spells, which a 17th level feature like these would not add on to.

> For example:
> Flavor text. For 1 minute:
> 
> Regain 1 mana at the start of your turn.
> Gain effects of Reddopsi
> Gain effects of Detect Magic
> Gain effects of Mage Armor

You want me to create one of these for each theme?

Some issues with the current suggestion:
- Mage Armor isn't antimagic based. There are several other options that would fit other themes than mage armor (Mirror Image, Barkskin, Cloak of Shadows, etc)
- The 1 mana at the start of the turn is just a copy of the Psionicist. The psionicist is able to get that because it is their thematic to fully master themselves so they become a psi battery for a short period. Mage does not have that flavor, at all.
- The spells are just a bit of extra mana limited to specific spells. Not super thematic.

_____________

Mages master spells. You can see several names spells in the PHB like Tasha's Hideous Laughter, Tenser's Floating Disk, Melf's Acid Arrow, Nystul's Magic Aura, etc. The suggestion above is meant to accomplish that flavor a bit by giving signature spells - as the feature is called in RAW.

**Comment by itamarcu** [comment]
> At 17th level a mage picks two spells, one 1 mana and one 2 mana. It then assigns a metamagic option and a greater metamagic between them. The spells are then unique like we see with other spells in 5e like "ARCANIST's magic spell".

I like this idea a lot.  I imagine it'd basically be "Whenever you cast the selected spell, it is enhanced with the selected metamagic".  And still, with the ability to change the signature spell over a long rest or a week or a level-up, just in case players change their mind.

> The main concern is that it makes 2 spells "better than others" which could limit options like the RAW Eldritch Blast does.

I think at 17th level this is not a problem.  Mages have a ton of options under their belt, and they already can add metamagic to any spell.  Making their two already-favorite spells slightly better is not gonna change anyone's playstyle by that point.

I think it's perfect for the flavor of having a signature spell, like you said - being known for your homing catapults or your persistent shield buff.  Alternatively, by level 17 an archmage could create a real custom spell, but this system probably isn't ready for that :P

**Comment by mlenser** [comment]
> Alternatively, by level 17 an archmage could create a real custom spell, but this system probably isn't ready for that :P

Ya, that was another thought, but I don't think it's a very good standard option. Some GMs could do it, most probably not.

**Comment by Marcloure** [comment]
Any new, balanced spell would be suggested as standard spell, so that wouldn't work xD

**Comment by mlenser** [comment]
Signature Spells is now the new 17th level mage feature.
