### ISSUE TITLE
Allow copying spells of unknown themes into spellbook

### ISSUE THREAD

**Issue by sjlevin** [mlenser/kryx-rpg-issues#758]
**Is your feature request related to a problem? Please describe.**
The Mage's level 2 ability Arcane Inspiration currently relies upon the character's spellbook to contain more spells than the Mage knows. This requires the GM to create opportunities for the Mage to find written spells to be copied. Since the Mage can currently only copy spells of themes they know into their spellbook, that means that this feature becomes incredibly reliant on the GM providing enemy mages or libraries that relate to the player's chosen themes.

Imagine a player Mage who has used their Arcane Study to get a bunch of Primal themes. Where would they ever find spells for an Air spell? It's not like Naturalists regularly write spellbooks. It essentially requires finding the spellbook of another Mage who also was interested in Air spells. This requires rather a lot of GM fiat.

**Describe the solution you'd like**
Allow copying spells from any theme into spellbooks. This means that the player Mage can safely copy any interesting spells they find into their spellbook. They can use Arcane Inspiration to cast spells of themes they don't know. As the Mage gathers more spells from a single theme, they might choose to use their Arcane Study to learn that theme and be able to learn the spells from their spellbook.

**Describe alternatives you've considered**
Remove the phrase `if it is from a theme you know` from the `Copying a Spell into the Book` section about the spellbook.

**Comment by sjlevin** [comment]
An alternative for Arcane Inspiration would be to cast any spell (no matter whether it is in your spellbook) from any theme you know (which would essentially be like a minor Wish), but that would likely be too powerful for a 2nd level ability.

**Comment by mlenser** [comment]
Mages are not intended to be able to cast all spells from all themes. Mages, like all other classes, must choose themes and spells.
Arcane Secrets lets a Mage cherry pick a few spells without needing to know the theme and Arcane Study lets mages learn themes outside their power source.

All Mages have these features so inherently all Mages will know several themes outside of the Arcane power source which means there would definitely be spellbooks available.

The Mage will not have unlimited themes or spells, that does not fit with the design of the system or class.

**Comment by sjlevin** [comment]
This still requires a lot of custom work from the GM to make sure the world contains spellbooks containing spells from the appropriate themes. This either requires the GM to provide libraries containing spellbooks or NPC mages that specialize in the same themes as the player.

Imagine a campaign where the party is trying to stop a plot by non-humanoid NPCs (ex: demons) where enemy Mages are rare or nonexistent. The Mage is the only class that has features that rely upon the GM to be aware of their capabilities and specifically place items in the world for them to find. It makes loot party-dependent. If this restriction on only copying spells of known themes into spellbooks is lifted, it makes life significantly easier on the GM when worldbuilding.

In my experience as a GM, it is incredibly frustrating to provide spellbooks as loot to Wizards. The spellbooks need to contain spells that the NPC and the player Wizard actually would use. If the enemy wouldn't use it, it breaks immersion. If the player wouldn't use it, it is essentially trash. At least in D&D, the Wizard can copy any spell from an existing spellbook into their own spellbook because spellbooks can only contain Wizard-legal spells. The only thing the Wizard is incapable of copying is a spell scroll of a non-Wizard spell.

Mages are scholars of magic. Even if they find a spell for a theme they do not already know, the Mage would likely still be excited to study it. This rule essentially implies that Mages are only interested in magic that they have already begun to research. I honestly think this rule is against the philosophy of the Mage.

Imagine a Mage finds a spell from an unknown theme from a non-Arcane power source (ex: Fog Cloud). Is there really much imbalance enabling the Mage to cast a single spell in their spellbook from an unknown theme once per short rest? The mage still needs to find the spell and pay for the materials to copy it into their spellbook, so the GM can essentially control access to the maximum flexibility of Arcane Inspiration. I don't see the problem here.

**Comment by mlenser** [comment]
Some design clarifications:
- The Mage is not the 5e Wizard, purposefully. The 5e Wizard is insanely overpowered. In RAW, the Wizard can prepare almost double the spells of many other classes (barring Cleric and Druid I believe, it's been a while). According to D&D beyond the Wizard has 338 spells on its list while the Warlock has 129 and the Sorcerer has 197. The Mage is not the 5e Wizard, purposefully and it will never be.
- The Mage doesn't need many spells added to their spellbook to be effective. 1/level or 1/every other level wouldn't be bad target.
- If you prefer that Mages never learn from another spellbook you could implement Arcane Research or a similar system. See https://github.com/mlenser/kryx-rpg-issues/issues/50. However, doubling up on that plus learning from a spellbook would be too much.
___________

To addess your specific comments:

> This still requires a lot of custom work from the GM to make sure the world contains spellbooks containing spells from the appropriate themes. This either requires the GM to provide libraries containing spellbooks or NPC mages that specialize in the same themes as the player.

All spellbooks require work from the GM, whether that's in RAW or in my system. You can see many threads about spellbook contents on D&D forums. The way themes are chosen here does not significantly complicate things as all mages can choose themes outside of the Arcane power source. if we look at the "classic" wizard options in the PHB, several would be outside of Arcane. In Arcane: Abjuration, Conjuration, Transmutation. Outside Arcane: Divination, Evocation, Illusion, Necromancy.

> where enemy Mages are rare or nonexistent.

If enemy mages are rare or nonexistant then a RAW Wizard will also not be able to add spells from other spellbooks to their spellbook. This is not unique to my system. If such a scenario exists, then you should make scrolls available to your Mage or use Arcane Research or some other method to acquire a few spells (again, about 1/level or 1/every other level).

> In my experience as a GM, it is incredibly frustrating to provide spellbooks as loot to Wizards.

Then don't. Allow them to buy a few scrolls or to research.

> Mages are scholars of magic. Even if they find a spell for a theme they do not already know, the Mage would likely still be excited to study it.

See Arcane Study and Arcane Research. Both features cover what you're describing here.

>  Is there really much imbalance enabling the Mage to cast a single spell in their spellbook from an unknown theme once per short rest?

Yes, the Mage is not the 5e Wizard. Allowing them to store a ton of spells in their spellbook and then cherry pick from them as needed is not balanced.

**Comment by sjlevin** [comment]
Thank you for the detailed response. You make good points.

> Allowing them to store a ton of spells in their spellbook and then cherry pick from them as needed is not balanced.

Can you please explain how the [Psychic Reformation spell](https://www.kryxrpg.com/spells/psychic-reformation) does not enable any character (learned via the [Magical Secrets](https://www.kryxrpg.com/feats/magical-secrets) feat where the Divination theme can be accessed via the [Thematic Diversification](https://www.kryxrpg.com/feats/thematic-diversification) feat if necessary) to be able to cherry pick any spell from any theme they know? For example, a character with Psychic Reformation who knows the Force theme could spend 10 minutes to learn the Knock/Lock spell as necessary and then replace it again later.

I personally think that the Psychic Reformation spell (and the Magical Secrets and Thematic Diversification feats) are awesome additions, but I think they might go against your design philosophy here of preventing characters from being magical swiss army knives.

**Comment by Marcloure** [comment]
Psychic Reformation has a high cost at least. If you want to cast knock/lock or other similar spell using psychic reformation, you would be expending 3 mana for it, and then another 2 mana to swap to another spell.

**Comment by mlenser** [comment]
Arcane Inspiration lets you cast a spell when you need it. You can cast a spell as a reaction, action, two actions, etc. This can be used to store all kinds of utility options like Knock/Lock that you'll rarely use in your spellbook and use all your known spells on spells that you use more commonly. It's a taste of a "swiss army knife caster" while still limiting it to just the themes you know and the spells you've been able to acquire.

Psychic Reformation costs 2 mana (resources you can't spend elsewhere), 10 minutes (so you can't do it right as needed, you have to prepare it for coming challenges or wait a while if you come across a challenge), and is also limited to themes you know. The use case here is that the resource cost is quite high and the duration to use it makes it so it can overcome some challenges.

Quite different cases with significantly different power.

**Comment by mlenser** [comment]
Added a note about the availability of spells:
![image](https://user-images.githubusercontent.com/235857/114265190-c1a54780-99ef-11eb-88dc-2f210d9ac04e.png)

**Comment by Marcloure** [comment]
You may want to add that note to the Alchemist as well.

**Comment by Paulorpribeiro** [comment]
Average of one spell per level (other than the one you learn via discoveries) is a good ballpark. I once thought about upgrading arcane secrets to allow the mage to learn a spell from any theme AND adding a spell from any theme to your spell book. Also, upgrading arcane study to learn a theme outside your source AND adding a spell from that theme to your spellbook. That may address the issues of not enough spells in the spell book unless DM puts a scroll or magic shop in front of you.
Now that I think of it, to make use of those 2 "upgrades" to wizard features, you'd have to allow arcane inspiration to let the wizard learn any spell in his spellbook, regardless if you know the theme.

My two cents

PS: a mage studying a strange primal spell is him using arcane study when he level up, or getting the feat  to learn the theme

**Comment by itamarcu** [comment]
Arcane Inspiration is a very strong core feature - the "swiss army knife" available at a moment's notice out of a library limited only by your wealth is super useful.

I would argue that the existence of Arcane Inspiration is why you shouldn't allow mages to easily learn spells from any theme.  The combination of a huge library and the ability to instantly draw from that library is too much, and makes it much harder for GMs to plan good challenges.

However, if your mage player really wants that ability, I think it would be more or less fair if they lost their Arcane Inspiration as a price for gaining the ability to learn spells from anywhere they want.  This would give them a lot more versatility in what they know, but keep them from being able to draw on any one of those spells in a pinch, forcing them to plan ahead and keeping the game interesting.

**Comment by mlenser** [comment]
> I once thought about upgrading arcane secrets to allow the mage to learn a spell from any theme AND adding a spell from any theme to your spell book. Also, upgrading arcane study to learn a theme outside your source AND adding a spell from that theme to your spellbook. That may address the issues of not enough spells in the spell book unless DM puts a scroll or magic shop in front of you.

That could be an alternative if spells aren't made available through other methods, ya.

_____________

> However, if your mage player really wants that ability, I think it would be more or less fair if they lost their Arcane Inspiration as a price for gaining the ability to learn spells from anywhere they want. This would give them a lot more versatility in what they know, but keep them from being able to draw on any one of those spells in a pinch, forcing them to plan ahead and keeping the game interesting.

This would be a fairly balanced option, but I personally wouldn't use it. It limits the value of a spellbook to just changing things later and opens up far too much ability to cherry pick "the best" spells.
