### ISSUE TITLE
Add descriptions to the orc

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#759]
Add description to the Orc specie. They currently only have a 2 lines paragraph of description.

The description can't be ported from VGtM for the most part, since orcs are inherently "evil" there, but there may be a section or two we can use from there.

**Comment by mlenser** [comment]
Most species need descriptions. If you've written out a description of a species feel free to open an issue. Otherwise we don't need an issue for each case.

Orc can likely look at Exandria for some flavor that isn't "Orcs are bad savage people"
