### ISSUE TITLE
Allow Elemental Bane spells to bypass immunity

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#76]
My suggestion is to add an augment to the Elemental Bane spells that removes the target's immunity to damage.

Personally, I'm not sure about this one. I'm making the suggesting and leaving the decision to you. The problem is that if immunity can be removed with a single spell (although a concentration one), it may feel... unworthy?

**Comment by mlenser** [comment]
Apparently there is only one way to overcome immunity: level 18 Pyromancer. https://rpg.stackexchange.com/questions/103123/is-there-a-way-to-bypass-resistance-immunity-to-fire-damage

I think these spells could be augmented to 9 mana to get that.
