### ISSUE TITLE
Address Schism

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#761]
**Describe the bug**
Schism is worded the same way before 2 actions was implemented which leads to some issues. See the discussion https://discord.com/channels/701706060440010753/736805578504011804/830260677129142282

Schism is meant to give advantage on Will saving throws and additional spell(s). 1 extra 1 mana spell a turn is very useful, I think 2 might be problematic. I'll have to examine what the best option is.

**Comment by sjlevin** [comment]
I am curious how Schism works with feats that grant at will spells like Misty Visions. I personally love having Misty Visions and Illusory Reality to be able to essentially conjure real physical objects (like walls). Can the schism mind use these feats too?
> You can cast image at will, without expending mana.

> You have learned the secret of weaving shadow magic into your illusions to give them a semi-reality. When you expend mana or psi to cast a spell that creates an illusion, you can choose one inanimate, nonmagical object that is part of the illusion and make that object real. You can do this on your turn as an action while the spell is ongoing. The object remains real for 1 minute. For example, you can create an illusion of a bridge over a chasm and then make it real long enough for your allies to cross.
The object can’t deal damage or otherwise directly harm anyone.

**Comment by sjlevin** [comment]
I assumed Schism was just a less powerful version of [Fission](https://www.kryxrpg.com/spells/fission). Was that not the goal?

**Comment by itamarcu** [comment]
Schism is also cool with how it lets you "multithread" - think about two things at the same time.  Those are mostly RP benefits, though, even you're trying to solve a riddle while swordfighting or have a conversation while casting a ritual spell.

I think it might be better if Schism specifically had *one* action that it could use to cast any (one-action) spell, with the 1 mana limit.  then, an augment to 5 mana could increase it to allow casting 2-action / 2-mana spells.  5 mana is a huge cost and it seems epic enough.

It could also specify that the new mind cannot concentrate.  Or alternatively, that it can concentrate but whenever you take damage you make both a save for the mind's spell and a save for your own Schism spell.

**Comment by mlenser** [comment]
Schism simplified to give advantage on Will saving throws and to give a mental action which can be used for spellcasting low mana spells.
