### ISSUE TITLE
Add augment to Symbol of Death/Pain

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#762]
Symbol of Death deals 10d10 at 3 mana, but it has no augment. It could have one, maybe.

**Comment by mlenser** [comment]
I would say it shouldn't. A bigger trap can be insta-kill. I think 10d10 as a cap is fine for a trap spell.

**Comment by Marcloure** [comment]
A trap that deals 50-60 damage is not enough to insta-kill any 5th level or above character. Any  3 mana single target spell deals more damage than that, and we are talking about 4 and 5 mana Glyphs, so at even higher mana.

**Comment by itamarcu** [comment]
Why does Symbol of Death/Pain even exist, when Glyph of Warding can do practically the same thing with much more versatility for 20% of the price and with an augment for the basic damage?

I don't think the 10 minute duration is really that important for trap-makers, and if it is, then Glyph of Warding could be used with a spell like Cloudkill to achieve the same purpose.
