### ISSUE TITLE
Mummy Suffused requires another 1st level feature

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#763]
Other origins gain a language or skill capacity, plus a minor feature. The Mummy gains only the minor feature (Undying), so it should also gain capacity in Divinity (or something else).

**Comment by Marcloure** [comment]
If capacity with Divinity doesn't fit, maybe Death’s Gift could move to 1st level and they gain some curse at 2nd level. Mummies are famous for curses, but the Suffesed doesn't have any

**Comment by mlenser** [comment]
Death’s Gift, like all other resistances, belongs at 2nd level.
