### ISSUE TITLE
Phosphorescent Bomb

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#765]
This concoction would be similar to Faerie Fire spell:

> As an action, you create this luminous bomb. As an action, a creature can throw this bomb at a point within 5 meters, where it explodes on impact. Each creature and object in a sphere twice as big as normal is outlined in blue, green, or violet light (your choice). An unwilling creature must make a Reflex saving throw to avoid the effect. For the duration, objects and affected creatures shed dim light in a 2-meter radius.
> Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can’t benefit from being invisible.

I'm suggesting this because **a)** seems to make sense, and **b)** light could gain some more concoctions, since light is an important and fantastical product of chimestry.

**Comment by mlenser** [comment]
Phosphorus Bomb added to the Light theme.

**Comment by Marcloure** [comment]
I think this concoction should be against Reflex save, not Fortitude save. Unlike the spell, which causes the light to glow from your skin, the concoction covers you with a luminous substance, so you can dodge/scratch it off.

**Comment by mlenser** [comment]
Changed it to Reflex to align with other bombs
