### ISSUE TITLE
Alchemical Silver Oil suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#766]
#### Alchemical Silver Oil
2 catalyst | Creation

_unstable, 5 minutes/catalyst_

As an action, you can create this silvery, metallic oil. As an action, a creature can coat one weapon with the oil to make it silvered for the duration, potentially bypassing some monster's resistance to damage.
Alternatively, you can touch a quiver containing arrows or bolts, granting the ammunition pulled from it the same effect. The oil’s effect ends on a piece of ammunition when it hits or misses.

---

The idea here is pretty simple: you coat your weapon with this temporary silver to bypass resistances. I put it at 2 catalysts because it can be more impactful than the other oils when it is needed, but it doesn't increase the damage dealt to other creatures you may encounter there.

Finally, it can be named just **Silver Oil** as well.

**Comment by mlenser** [comment]
Silver Oil concoction and Silvered Weapon spell added to the Alteration theme.

**Comment by Marcloure** [comment]
Aren't spells that change objects in Creation? Looking at Alteration, most if not all are biological changes. Also, I think Alteration will be pretty big and generic if we include both objects and biological spells.

**Comment by mlenser** [comment]
> Aren't spells that change objects in Creation?

Nope. "Alteration magic mutates and shapes matter, both alive and inanimate." vs "Creation is the art of making new objects, whether from the materials of the world or out of thin air."

Alteration is for changing things. Creation is for creating. That's how it has been. See sharpness oil for example.

**Comment by itamarcu** [comment]
It's getting off-topic, but I kind of agree with Marcloure - the majority of Alteration spells/concoctions/feats are about changing living bodies, particularly your own body.  Creation is more limited like you say, but it also has Grease and Slipperiness Oil, which seem to me just like this Silver Oil (just coating a weapon with a layer of silver;  not changing the metal to become silver).

Either way, I think it's more reasonable to imagine spellcasters who specialize in biological alteration+creation and spellcasters who specialize in inanimate alteration+creation than ones who specialize in strict transformation of all things and ones who specialize only in creating things out of nothing (which is often indistinguishable from using Planes and Teleportation magic to summon things).

**Comment by mlenser** [comment]
> "Alteration magic mutates and shapes matter, both alive and inanimate." vs "Creation is the art of making new objects, whether from the materials of the world or out of thin air."

**Comment by Marcloure** [comment]
About the silver oil specifically, so on topic, I thought of it as a literal coat of silver that is applied on the weapon, not a change in the material:

> A creature can coat one weapon with the oil to make it silvered

**Comment by mlenser** [comment]
It's only silvered for the duration.

**Comment by mlenser** [comment]
It transforms the material.

**Comment by mlenser** [comment]
> Silver. Some monsters that have immunity or resistance to attacks are susceptible to silver weapons, so cautious adventurers invest extra coin to plate their weapons with silver.

Silver is plating. This is just adding a plating.

This issue is locked. Please let it be.
