### ISSUE TITLE
Tracking Dust suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#767]
#### Tracking Dust

1 catalyst | Divination

As an action, you create a pounce of this thin, white chalk. A creature can spend 1 minute to spread the chalk over a sphere, covering the ground and objects in the area. The dust reveals marks and tracks left behind, granting advantage on any skill checks to investigate the covered area or track creatures that past in the area in the previous 24 hours.

---

This could be just a generic Alchemical Creation, instead of a proper concoction, if you prefer.

**Comment by mlenser** [comment]
I think this is better as an alchemical creation as you say. It's basically flower/chalk that you spread over a smaller area (one space). So to cover a larger area would take multiple turns.

**Comment by mlenser** [comment]
Hmmm, I think on second thought that flour shouldn't work against magical invisibility.

https://www.reddit.com/r/dndnext/comments/5w0xn8/does_throwing_flour_at_an_invisible_creature

Similarly, I don't think concoctions could break it either as anything you attach to them becomes invisible.

**Comment by Marcloure** [comment]
Hm, I just noticed this wasn't added as a Alchemical Creations. The idea isn't to use it on invisible creatures, but to make tracks and secret doors more apparent, so I don't understand why your comment invalidated the issue.

**Comment by mlenser** [comment]
Making tracks more apparent = use regular flour.

If a secret door is impacted by powder then flour would again work. If it's magic then alchemy is not applicable.
