### ISSUE TITLE
Predator Scent suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#768]
#### Predator Scent

1 catalyst | Beast

_unstable, 1 hour/catalyst_

As an action, you create a vial containing the scent of a predatory animal. As an action, a creature can cover itself with this scent. Any beast who targets the covered creature with an attack or a harmful effect must first make a Will saving throw.

On a failed save, the beast must choose a new target or lose the attack or effect. This concoction doesn’t protect the covered creature from area effects, such as the slash of a swipe _[link to swipe maneuver]_.

If the covered creature makes an attack, casts a spell that affects a beast, or deals damage to a beast, any other beast aware of this act automatically succeeds on the saving throw against this concoction for the remaining duration.

Additionally, creatures have advantage on skill checks to track you by scent.

--- 

It's sanctuary, but against beasts. It has a much longer duration because of this. The last effect is just for flavor, it can be removed.

**Comment by Marcloure** [comment]
Alternatively, it could be a more generic version that works against every creature. It would probably be in Fear then.

**Comment by mlenser** [comment]
Hmmm, I don't think the flavor of this really works. Predatory scents keep prey away. They could possibly deter (or attract) other predators, but it wouldn't make them unable to attack unless they pass a Will saving throw.
I don't think it'd work as a concoction in general. It sounds very magical.

**Comment by Marcloure** [comment]
I thought of it more like a strong scent that smells like a predator for every beast. It could just be a noxious scent that repugnantes everyone instead, but that would be in Fear, and the only concoction in that theme (and another theme for Alchemy)

**Comment by mlenser** [comment]
So a skunk smell?

Hmm, still don't see a Will save or can't attack. Maybe a Fortitude or disadvantage at best.. but even then..

**Comment by Marcloure** [comment]
Yeah, something like that. I think Will should be the save against a skunk's smell, since as far as I know, they are not poisonous or aggressive like a teargas. The bad smell just disincentives you to pursue it.

**Comment by mlenser** [comment]
Skunk is definitely fortitude. See https://www.d20pfsrd.com/bestiary/monster-listings/animals/skunk/ for example.

So what you suggesting now is a concoction to cover yourself in such an awful smell that people have to make a Fortitude saving throw or have disavantage on attacks against you?
A bit like Mirror Image.

**Comment by Marcloure** [comment]
Yeah, something like that.

**Comment by DalenWBrauner** [comment]
If an Alchemist knows enough about certain creatures, I think they should be able to concoct a scent that repels just them. There are lots of examples of animals of being driven away (or toward) very specific scents.

That being said, I think this flavor matches the Fear mechanic better than Sanctuary. It's not that the creature doesn't want to take a swipe, it's that the creature doesn't want to be anywhere near you- it would be difficult for them to move closer, rather than to make (say,) a ranged attack.

**Comment by mlenser** [comment]
Skunk Odor added as a concoction to the Poison theme.
