### ISSUE TITLE
Resonance Oil suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#769]
#### Resonance Oil

1 catalyst | Storm

_unstable, 3 hours/catalyst_

As an action, you create this perfectly transparent oil. As an action, a creature can spread this oil on an object made of metal, causing it to resonate even to the quietest sounds. The oil only takes effect after the start of the creature's next turn. After this time, whenever a Tiny or larger creature touches the object or enters an area within a sphere twice as big as normal centered on the object, the object emits a continuous wobbling sound for 10 seconds that is heard up to 100 meters away. The sound is loud enough to awake sleeping creatures.

A creature can try to avoid causing the resonance by making a Stealth check to move silently or a Skulduggery check to touch the object gently. The DC for these checks equals your concoction save DC. On a success, the creature can move through the area or touch the object without triggering the effect until the start of its next turn.

---

This one is kind of Alarm, but has some fundamental differences. I made it much louder than alarm though, since it can't be set to be mentally heard. Not sure if it is very useful though, since it can't be cast as ritual as well.

Also, I made it avoidable for some reason. Alarm isn't though, so this can be unavoidable too, maybe.

**Comment by Marcloure** [comment]
If #770 is done, it should be done here too.

**Comment by mlenser** [comment]
This seems like a device that an artificer (#1) would create, not something that alchemy can achieve.
