### ISSUE TITLE
Add augment to Fabricate to allow for larger objects

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#771]
Currently, Fabricate allows only for medium objects at 2 mana, but I believe it should be able to create longer ladders and bridges, or bigger doors with more mana.

**Comment by mlenser** [comment]
I need to rework the wording here to work more like walls.

**Comment by mlenser** [comment]
@Marcloure feel free to suggest how this should be worded. I agree with your goal, but don't necessarily want to build the wording myself. If you reword the spell I'll do my best to update it.

Feel free to reopen if you suggest wording.

**Comment by Marcloure** [comment]
Base spell text is:

> You can fabricate a Large or smaller object (contained within a sphere), given a sufficient quantity of raw material. If you are working with metal, stone, or another mineral substance, however, the fabricated object can be no larger than Medium (contained within a single 1-meter cube)

For the augment:

> **Augment**
> You can augment this spell with the following options, expending mana or psi for each option.
> - You can expend 1 additional mana or psi to fabricate a Huge or smaller object. If you are working with metal, stone, or another mineral substance, you can fabricate a Large or smaller object.
> - You can expend 2 additional mana or psi to fabricate a Gargantuan or smaller object. If you are working with metal, stone, or another mineral substance, you can fabricate a Huge or smaller object.
> - You can expend 3 additional mana or psi to fabricate a Gargantuan or smaller object of any substance.

There is a lot of repetition there, so maybe something can be simplified.

**Comment by itamarcu** [comment]
> You can expend up to 3 additional mana or psi to increase the maximum size to the next size category.  For example, if you expend 2 additional mana, you can fabricate a Gargantuan wooden bridge or a Huge stone statue.

**Comment by mlenser** [comment]
Hmm, this doesn't quite cover the need as walls do. Wall description:

> A wall extends from its point of origin in a straight path up to its length and covers an area defined by its width and height. Every 1 meter of a wall is a panel.

Wall of Stone has some good wording too:

> You can use this spell to bridge a chasm or create a ramp. If you create a span greater than 4 meters in length, you must halve the size of each panel to create supports. You can crudely shape the wall to create crenellations, battlements, and so on.

**Comment by mlenser** [comment]
Closing unless someone else does the work here.

**Comment by Marcloure** [comment]
I don't understand what is required then; what is wrong with what I suggested above?

**Comment by mlenser** [comment]
See the comment above

https://github.com/mlenser/kryx-rpg-issues/issues/771#issuecomment-858798474

**Comment by Marcloure** [comment]
I saw the comment, but I don't understand what isn't covered. The original spell has "(contained within a single 1-meter cube)", we just need to increase the size of this area too, no?

**Comment by mlenser** [comment]
The comment above shows how walls are worded. The wording you suggested does not even come close to the options provided by the wall wording.

**Comment by mlenser** [comment]
Fabricate can now create a wall and be augmented for larger objects.

**Comment by mlenser** [comment]
Thanks!

> You can surround someone without a save, for instance, but the spell has 10 minutes of casting time, so that should be fine.

A creature might not be aware of what you're casting so it's good to have, imo.
