### ISSUE TITLE
Duplicate Object suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#772]
#### Duplicate Object

1 mana | Creation

_(ritual)_; M (an amount of the same material worth the cost of the original object, consumed)

As you spend 1 minute to cast this spell, you create an exact replica of a small object you possess that weighs no more than 1 kilogram, such as a key. The object performs identically to the original in all mundane ways and is not recognizable as a fake, even by magic. A copy of a magic item is nonmagical.

---

I don't have much to say about this. It's a spell that allows you to create copy of keys, symbols, written text, the looks of an artifact, and other objects. It's also a ritual, so it's part of my quest to add more rituals.

**Comment by itamarcu** [comment]
I really like this!

I think it might potentially be too strong at 1 mana, and would suggest having the object slowly deteriorate and revert to the raw material after an hour (with 1 mana augment to make it permanent).  As a 1 mana spell, **especially** a ritual, it would be too easy for the world to be full of "copier mages" who run wild with making duplicates of everything worth crafting/selling.  Copying books is a job big enough that people were paid for it in medieval times, for example.

**Comment by Marcloure** [comment]
I took this from 4thed, and there is has a duration depending on your Arcana check result to cast the ritual:

21-30 | 1 hour
31-40 | 1 day
41 or higher | 1 week

I made it permanent here, but I think you are right. It should be temporary at lower mana.

**Comment by DalenWBrauner** [comment]
It's also going to need language for only copying "simple" or "mundane" objects. No duplicating Sending Stones, wands, spell scrolls, or elaborate machines. Unsure about alchemical creations, because you DO still have to pay the cost...

**Comment by Marcloure** [comment]
It states "a copy of a magic item is nonmagical." So you can copy the appearance of a magic item, but not its magic. About elaborate machinery... I'm not against it, but I understand why copying a clockwork my be too much.

**Comment by DalenWBrauner** [comment]
Oh, I somehow misread that last sentence- that's totally cool then.

I was only thinking about "complex" devices because I know I've seen that wording in a few places and assumed there was some wisdom in keeping it. But the spell only works on smaller objects anyhow, so it may not be needed.

**Comment by mlenser** [comment]
Replicate Object added to the Forge theme.

**Comment by mlenser** [comment]
Replicate Object adjusted so it does not consume materials until the Indefinite version. The normal versions have a clear mark to ensure money and other things aren't duplicated.
