### ISSUE TITLE
Split Alteration and retheme Creation

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#773]
**Is your feature request related to a problem? Please describe.**
Currently, Alteration includes both changes to inorganic and organic materials, which creates a fairly large theme, both thematically and by number of spells/features. This also creates weird interaction where a dwarf cleric of Moradin gains access to Polymorph, and an anatomist Mage gains access to Silver Weapon.

Alterations spells and features are already mostly of organic nature, so this change would solidify this trend, making the theme more focused.

**Describe the solution you'd like**
The solution would be to remove the spells that affect solely objects and move them into Creation (and rename/reflavor Creation to also include changes, not only creation).

The list to be moved from Alteration to [new] Creation consists of:
- Enlarge/Reduce potion and spell when applied to objects (a version that affects only creatures and their equipment would remain)
- Sharpness Oil, Sharpen Weapon
- Silver Oil, Silvered Weapon

**Additional Suggestions**
As both Alteration and Creation would have a slight shift in their themes, a new name could be suitable. Particularly, I'm fine with their current names, since Creation does refer to objects (i.e.: created things, as opposed to born), but here are some suggestions anyway:

Instead of the Creation theme:
- Construct theme
- Object theme
- Inanimate theme (giving movement to inanimate things would fit)
- Fabrication theme

For the Alteration theme:
- Anatomy theme (as opposed to the Mind theme)
- Organism theme
- Morphism theme

**Comment by Marcloure** [comment]
Another personal thinking: making this change is more important than finding the most suitable name possible. The English language isn't made to have a single word for every concept.

**Comment by mlenser** [comment]
Names are very important. None of the current proposals would fit either the (new) Creation or Alteration.

Naming would have to be fixed before I attempt to align things to the new names and concepts.

**Comment by mlenser** [comment]
- Alteration theme renamed Mutation. [#773](https://github.com/mlenser/kryx-rpg-issues/issues/773)
- Creation theme renamed Forge. [#773](https://github.com/mlenser/kryx-rpg-issues/issues/773)
- Enlarge/Reduce split to Enlarge/Reduce (Mutation) and Enlarge/Reduce Object (Forge). Additionally, the Mutation version only affects yourself with an augment to affect another creature. [#773](https://github.com/mlenser/kryx-rpg-issues/issues/773)
- Sharpened Weapon, Sharpness Oil, Silver Oil, and Silvered Weapon moved from the Mutation theme to the Forge theme. [#773](https://github.com/mlenser/kryx-rpg-issues/issues/773)
- Concealing Amorpha moved from the Forge theme to the Mutation theme. [#773](https://github.com/mlenser/kryx-rpg-issues/issues/773)
- Mutation theme removed from Arcane, but added to Occult.

**Comment by sjlevin** [comment]
This change should have been marked as a Major change in the changelog. Major changes include "majorly reworking an archetype, class, species, or theme". Since the Alteration/Mutation theme was removed from Arcane, any existing Arcane-based character that relied on knowing that theme is broken.

**Comment by mlenser** [comment]
A major change is an incompatible change. This change isn't incompatible. The thematics that existed in the Alteration theme are still there - mostly in the Metabolism theme.

I'll redefine my versioning a bit to be more up to date with how I treat it.

**Comment by sjlevin** [comment]
I agree that the Metabolism contains most of what Alteration used to maintain, but the incompatible change was removing Alteation/Metabolism from the Arcane power source. If I am playing a campaign with a Mage character who knew the Alteration theme, I suddenly no longer have access to that theme unless my GM grandfathers me in to the Metabolism theme. Anything that requires a GM to allow a special rule should probably be considered an incompatible change, don't you think?

**Comment by mlenser** [comment]
> Anything that requires a GM to allow a special rule should probably be considered an incompatible change, don't you think?

I see what you're saying, but if I use that definition then I'll produce major changes nearly every week as minor things will inherently be "incompatible".

Major changes are just that - major. Stuff that is entirely incompatible with D&D 5e or previous versions of my system.

Other changes depend on GMs grandfathering or asking you to adjust. I don't see another way to do it without weekly major changes which hides the real incompatible major changes.

**Comment by sjlevin** [comment]
Are you opposed to providing a method of viewing the rules at a specific version so players can make characters at a specific version snapshot?

**Comment by mlenser** [comment]
Yes. I have no plans to provide older versions beyond temporary solutions like I have done in the past. Multiple versions will lead to difficulty for me to maintain the system and more importantly fragmentation.

If there are issues with a change then they should be discussed - either on Github or Discord. It is a living system that can and should adjust.
