### ISSUE TITLE
Add new features to the Spellthief

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#774]
From the list in #722 :
> the Spellthief has only one and actually weakish feature, since it can only steal 1 mana spells until the 9th level.

They need another two features to be competitive, since their current single feature scales very badly.

**Comment by Paulorpribeiro** [comment]
I always thought that "stealing spells" is quite a narrow archetype. This should be the "rogue gish" and while spellstealing is a nice option, I think I shouldn't be mandatory for the rogue gish. Perhaps a feature with the design similar to say primal call, where you have some options and choose 2 or 3.

**Comment by mlenser** [comment]
> This should be the "rogue gish" and while spellstealing is a nice option, I think I shouldn't be mandatory for the rogue gish

The rogue gish is based upon stealing spells - that's where they get their magic from. Without that there is no Rogue gish.

**Comment by Marcloure** [comment]
I too think the flavor is good. Stealing spells is very cool, and I think it is expected that a rogue character would use the tools of their enemies against themselves.

**Comment by mlenser** [comment]
Infiltrator and Spellthief are balanced against eachother.

## Both
- Lots of skills
- Cheap Shot
- Cunning Action
- Lots of later level features that other gishes don't have.

## Infiltrator
- more skills
- Possibility to have a bit of alchemy
- Danger Sense
- Reliable Talent

## Spellthief
- Possibility to have a bit or lots of spells
- Steal Spell
- Magical Ambush

So in essense we're trading more skills (and possibly some alchemy) vs spells. That's a fair trade as far as I'm concerned.

So there is no issue with the Rogue archetypes that I can see. Each archetype stacks up against another. If the Rogue is missing earlier level features (possible), then that'd be a different issue. Though they get a lot of later features so either we'd have to move some earlier or remvoe some and add earlier features if that is the case.

**Comment by Marcloure** [comment]
The issue is that Steal Spell is, frankly, a bad feature. Reasons:

- It is limited to stealing 1 mana spells until the 9th level. Good at the start, but after ~6th level, you are not as often targeted by 1 mana spells anymore. At 9th level the feature becomes acceptable again, but only by a few levels until it falls off again.
- Ok, stealing the spell is a minor effect, stopping it is the strong part. But then, it is a 1/short rest counterspell that you have for free. Correction, a counterspell that requires you to be targeted by the spell, and that depends on the target's Will (which will likely be high as they are a caster)

Considering both of these reasons, Steal Spell is both a situational feature while still being weak when it's useful (stopping a 1 mana spell at 6th+ level doesn't impact _that_ much). As this is the core feature of the Spellthief, I think it should at least feel either more present or more impactful.

**Comment by mlenser** [comment]
Steal Spell exists in RAW as Arcane Trickster's Spell Thief feature:
![image](https://user-images.githubusercontent.com/235857/114858328-9e143f80-9de9-11eb-99eb-dce78c629df2.png)

This version is available at 2nd level instead of 17th. Other than that it is largely the same.

According to guide (in order of google popularity):
- https://rpgbot.net/dnd5/characters/classes/rogue/subclasses.html the feature is a fantastic option.
- https://arcaneeye.com/class-guides/arcane-trickster-5e-guide the feature is a good option

**Comment by Marcloure** [comment]
Well, fireball is still cast at 17th level in RAW, but I can't believe that feature is strong even in RAW, which has some good 3rd level spells to steal. Once per long rest even? That is... fairly not very useful.

Also, I just noticed you negate the effect only on yourself, not on everyone else. It's not even comparable to a 1/short rest counterspell :/

**Comment by mlenser** [comment]
> I can't believe that feature is strong even in RAW

The top rogue guides disagree with you. Feel free to find discussions that talk about this feature, or open a discussion on it if you can't find any.

The Spellthief Rogue has great DPR, spells, a good amount of skills, good armor and weapon options, good utility in cunning action. I don't see what it is missing even if this feature was a bit weaker (which doesn't seem to be the case, but feel free to find other community opinions).

**Comment by Marcloure** [comment]
I'm not talking just about power, but about fantasy as well. The Spellthief has a limited amount of opportunities to use their unique feature, and even when they can use it, it isn't that impactful. They could gain some bonus to break concentration, dispel magic, or something else to reinforce their theme a bit. I don't think it needs to be powerful, just more than this single feature.

**Comment by mlenser** [comment]
Seems this will just go on and on, so locking it. Feel free to follow up as directed above.
