### ISSUE TITLE
AoE augment sizes seem wrong with both metric and imperial distances

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#775]
The table (at the bottom of each theme page) looks like this now:
![image](https://user-images.githubusercontent.com/6516621/114943002-085ecb80-9e4e-11eb-98be-1665ded28588.png)

This doesn't seem right.
- Cones:  3, 5, 9, 10, 15 - I would expect it to be 3, 6, 9, 12, 15
- Cylinder heights, line lengths, wall lengths - same problems as with cones
- Wall heights:  2, 4, 5, 8, 10 - I would expect it to be 2, 4, 6, 8, 10

(The numbers above are in meters.  in Imperial, they're all just the same multiplied by 5, as feet)

**Comment by mlenser** [comment]
fixed
