### ISSUE TITLE
Earthen Grasp's Interposing Hand should require acrobatics

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#777]
Earthen Grasp's, Force Hand's, and Giant Crawling Claw's **Interposing** version requires a Reflex save to pass through the hand's space, but it probably should be an Acrobatics check.

**Comment by mlenser** [comment]
Earthen Grasp, Force Hand, and Giant Crawling Claw now require Acrobatics or Brawn to bypass the interposing version.
