### ISSUE TITLE
Objects and piercing and slashing damage

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#778]
Object are immune to poison and psychic damage. Most should probably be resistant to piercing and slashing damage? We can apply this individually as well.

Some cases to look at: Wall of Stone, Wall of Thorns (different than stone), Sacred Statue, etc.

Additionally, should these apply to magical damage (spells)? Currently most cases like Stoneskin only apply to attacks (weapons or monsters).

**Comment by itamarcu** [comment]
I think it should be on a case-by-case basis.  Stone should be resistant to piercing and slashing, but Thorns should be resistant to bludgeoning.  Soft objects like ropes and plants, generally, should be resistant to bludgeoning (or vulnerable to piercing and slashing).

**Comment by DalenWBrauner** [comment]
I don't believe most Wooden objects would be resistant to any of these
things (though still immune to Psychic & Poison).

I agree with Shem- perhaps just a blurb containing some direction for DMs
on how to rule for objects and resistances?

**Comment by Marcloure** [comment]
> blurb containing some direction for DMs
on how to rule for objects and resistances?

The DMG already has a rule for this, but only for mundane objects, not spells:

> Objects are immune to poison and psychic damage. You might decide that some Damage Types are more effective against a particular object or substance than others. For example, bludgeoning damage works well for smashing things but not for cutting through rope or leather. Paper or cloth objects might be vulnerable to fire and lightning damage. A pick can chip away stone but can’t effectively cut down a tree. As always, use your best judgment.

**Comment by mlenser** [comment]
This is much less clear on creatures. Currently there are quite a few who are resistant to just attacks. Not sure how to handle those.

Pick also makes the stone cases weird. No way to write that well...

**Comment by mlenser** [comment]
Too complex to consider a general solution. If someone wants to find all the cases that should be adjusted and suggest how to handle them then I'd be happy to implement.
