### ISSUE TITLE
Add maneuvers/spells to Humanoid (goblinoid)

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#78]
Part of #9 .

**Comment by Marcloure** [comment]
## Bugbear
Remove Surprise Attack since we have Ambush?
**Themes:** Shadow, Vanguard
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, cripple, glancing blow, lunge, trip

## Bugbear Chief
Remove Surprise Attack since we have Ambush?
**Themes:** Shadow, Vanguard
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, cripple, glancing blow, lunge, spring attack, trip

## Goblin
Update Nimble Escape
**Themes:** Deceit, Shadow, Skirmish
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, bait and switch, distract, nimble, vault

## Goblin Boss
Update Nimble Escape
**Themes:** Deceit, Shadow, Skirmish
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, bait and switch, distract, feigned opening, nimble, nimble dodge, vault

## Hobgoblin
**Themes:** Vanguard
#### Maneuvers (limit 1)
- **1 Stamina die:** glancing blow, parry, precision, slice through, spring attack, trip

## Hobgoblin Captain
**Themes:** Courage, Vanguard
#### Maneuvers (limit 1)
- **1 Stamina die:** coordinated movement, glancing blow, incite, lead the attack, parry, precision, slice through, spring attack, trip

## Hobgoblin Devastator
**Themes:** Fire, Force, Storm (it has mostly damage spells by RAW)
#### Spells (limit 4)
- **Cantrips:** blade ward, force beam, produce flame, shock
- **1 Mana:** ash fall, force spear, heat metal, lightning bolt, scorching ray, thunderwave
- **2 Mana:** call lightning, fireball, force hail, homing motes, incendiary cloud, levitate, shatter
- **3 Mana:** storm sphere, wall of fire
- **4 Mana:** invulnerability 

## Hobgoblin Iron Shadow
Remove Shadow Jaunt
**Themes:** Deceit, Shadow, Skirmish
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, feint, quivering palm, patient defense, stalking shadow, step of the wind
#### Spells (limit 1)
- **Cantrips:** blind spot, control shadow, hidden shadow, minor illusion
- **1 Mana:** disguise, illusory script (to write espionage info), image, shadow jaunt

## Hobgoblin Warlord
**Themes:** Courage, Vanguard
#### Maneuvers (limit 2)
- **1 Stamina die:** coordinated movement, glancing blow, incite, lead the attack, parry, precision, slice through, spring attack, trip
- **2 Stamina dice:** commander's strike, guided strike, riposte, staggering strike

## Nilbog
_Note: Nilbogs are spirits that posses goblins. They keep the goblin's maneuvers and gain their innate spells already converted._
Update Nimble Escape
**Themes:** Deceit, Shadow, Skirmish
#### Maneuvers (limit 1)
- **1 Stamina die:** ambush, bait and switch, distract, nimble, vault

**Comment by mlenser** [comment]
> Remove Surprise Attack since we have Ambush?

I'd say it should remain, just like an Assassin has Sneak Attack.

**Comment by mlenser** [comment]
Bugbear is the same concept as the Thug, imo.

**Comment by mlenser** [comment]
> Update Nimble Escape

What do you mean? It's like Cunning Action

**Comment by mlenser** [comment]
> feigned opening

This costs 2 stamina dice

**Comment by Marcloure** [comment]
> Bugbear is the same concept as the Thug, imo.

Bugbears are known to be boogie creatures. They also have long arms (Volo's playable bugbear has increased reach for OA). Other than that, they are pretty similar to thugs, yea

> What do you mean? It's like Cunning Action

It takes a bonus action where Cunning Action takes no action

> This costs 2 stamina dice

My mistake

**Comment by mlenser** [comment]
Did the following on Bugbear:

 "Ambush",
        "Debilitating Crush",
        "Disorient",
        "Glancing Blow",
        "Hamstring",
        "Knockback",
        "Lunge",
        "Spring Attack"

> It takes a bonus action where Cunning Action takes no action

So should this take no action as well?

**Comment by mlenser** [comment]
I've had the Hobgoblin Devastator focus on Acid/Fire as those were the two most common themes in its existing spells and match its flavor of direct results

**Comment by mlenser** [comment]
Added maneuvers and spells to some goblinoids: Bugbear, Bugbear Chief, Goblin, Goblin Boss, Hobgoblin, Hobgoblin Captain, Hobgoblin Devastator, Hobgoblin Iron Shadow, Hobgoblin Warlord, Nilbog
