### ISSUE TITLE
Fleshwarp

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#782]
Add a spell or multiple spells to warp creatures like the [Sibriex](https://www.kryxrpg.com/monsters/sibriex) does or create extra limbs or other effects.

Some ideas:
- ~~One of the target’s legs grows longer than the other, reducing its walking speed by 2 meters.~~
- ~~A pair of wings, either feathered or leathery, sprout from the target’s back, granting it a flying speed of 5 meters.~~
- ~~The target’s ears tear free from its head and scurry away; the target is deafened.~~
- ~~The target’s skin becomes scabby, granting it a +1 bonus to Defense but reducing its Charisma by 2 (to a minimum of 1).~~
- ~~The target’s arms and legs switch places, preventing the target from moving unless it crawls.~~
- ~~The target’s arms become tentacles with fingers on the ends, increasing its reach by 1 meter.~~
- ~~The target’s legs grow incredibly long and springy, increasing its walking speed by 2 meters.~~
- ~~The target’s eyes turn black, and it gains darkvision out to a range of 20 meters.~~
- ~~The target swells, tripling its weight.~~
- ~~The target becomes thin and skeletal, halving its weight.~~
- ~~The target’s head doubles in size.~~
- The target’s ears become wings, giving it a flying speed of 1 meter.
- The target’s body becomes unusually brittle, causing the target to have vulnerability to bludgeoning, piercing, and slashing damage.
- ~~The target grows another head, causing it to have advantage on saving throws against being charmed, frightened, or stunned.~~

**Comment by DalenWBrauner** [comment]
Some ideas for Fleshwarp based on what's live:
(I can open separate issues for any that have further debate)

- Homunculus [spell](https://www.kryxrpg.com/spells/create-homunculus) / [feat](https://www.kryxrpg.com/feats/homunculus)
- Tweak [Amorphous Form](https://www.kryxrpg.com/spells/amorphous-form) to be more flesh-like. Could possibly decrease the reiststances gained to just bludgeoning, in exchange for being able to use your free "use an object" action, as your fleshblob form might be able to briefly form hands or the like.
- The old Eyestalks feat, or something similar (forget where it exists now, if anywhere)
- [Eruptive Pustule](https://www.kryxrpg.com/spells/eruptive-pustule) (might be a bit too acidic, though.)

Extra Arms feat (2nd Level): (stolen from Thri-Kreen)
> You have four arms, which can carry items normally and allow you to interact with one extra object for free on your turn. If you wield a weapon with two hands or wield two weapons, you cannot benefit from a shield until the start of your next turn.

Could alternatively be a 1min Cantrip (too weak to be a spell + "at will" feat).

**Comment by mlenser** [comment]
- Homunculus isn't related to fleshwarping? It's made with blood.
- Amorphous Form is more like an ooze thing. I think it's close enough for a bloby form
- Eyestalks is for a beholder though the Minor Mutation cantrip has "Your eyes push out of your head at the end of stalks."
- Extra arms: added to Minor Mutation

There are definitely more fleshwarp ideas to add. Let's close this issue though and add any fleshed out ideas to new issues.

**Comment by itamarcu** [comment]
> fleshed out ideas

nice.
