### ISSUE TITLE
Divine Word area should scale with mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#784]
Divine Word affects each creature of your choice within 5 meters of you. That is much larger than the Fear spell at low mana, which affects a normal cone, but shorter at higher mana (although Divine Word is still a sphere, and you can pick allies out of it).

**Comment by mlenser** [comment]
Divine Word and Rebuke the Defilers are unique spells that only impact creatures of much lower challenge.

**Comment by mlenser** [comment]
Other spells don't increase their range. It's only AoEs that change size.

**Comment by Marcloure** [comment]
> Divine Word and Rebuke the Defilers are unique spells that only impact creatures of much lower challenge.

That is untrue, it scares creatures of any CR, so in that aspect, it's a better fear spell than Fear itself is.

**Comment by Marcloure** [comment]
So, I just noticed that Fear allows the frightened creature to at least use reactions, while Divine Word doesn't allow that. The turned effect is a much larger and more effective Fear spell, and that doesn't affect allies.

**Comment by mlenser** [comment]
I'll take a second look.

**Comment by Marcloure** [comment]
I think constructs should be immune to this spell. As animated objects, I don't think they should be affected by this divine utterance.

**Comment by mlenser** [comment]
That is a different issue.

If you open another issue please address: Why would constructs be immune to the holy word of a deity?

**Comment by mlenser** [comment]
Divine Word reworked to only turn creatures of a lower challenge.
