### ISSUE TITLE
Remove Cocoon's health

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#788]
Cocoon does the same as entagle, except it can't deal damage, and it has health. Two issues with this:

- You can't upcast Cocoon to deal damage in the same action you cast the spell, while with Entangle you can. So, you can upcast Entangle to gain more from the action you used to cast it. This is a minor issue, since thematics come into place.
- As Cocoon has health, you can't use blast an AOE spell on a cocooned creature without freeing it, and it's much easier to free it than against entangle.

The first issue, again, is minor, not much to do about it, I guess. 

The second one, I don't understand why Cocoon has health when the other similar spells don't. If you can't cut the vines, why can you do it against the webbing?

Also applies to cocoon vial (concoction).

**Comment by mlenser** [comment]
The cocoon has health because it does everywhere else. Giant Spider for example:
![image](https://user-images.githubusercontent.com/235857/115970893-c1f02780-a545-11eb-96dd-e33aa5bceb75.png)

Cocoon is utility while Ensnare is utility + a little damage. Different thematics.
