### ISSUE TITLE
Elf's Fey Ancenstry should grant immunity to all sleep effects

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#789]
I know it's intentional in 5e, but a Brass Dragon's Sleep Breath can knock an elf asleep, as do sleep gas concoctions. Shouldn't they be immune to these effects as well? Why just magical sleep?

**Comment by mlenser** [comment]
Fey aren't immune to falling asleep - they are just immune to magical sleep.

https://rpg.stackexchange.com/questions/128989/fey-ancestry-says-magic-cant-put-you-to-sleep-and-brass-dragon-has-the-abilit

**Comment by Marcloure** [comment]
Yeah, I know it's intended like that, I'm just questioning if that should be the case. I suppose you think so, so that is resolved.

**Comment by mlenser** [comment]
Since at least 3.5 it's been tied to magical sleep. I'm fine sticking to that.
