### ISSUE TITLE
Immovable Object should specify noncarried objects

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#790]
Immovable Object can be used on carried objects like armor or belts. It should state that the object isn't being worn or carried.

**Comment by mlenser** [comment]
wording cleaned up

**Comment by itamarcu** [comment]
I think it should be "not worn or carried by an unwilling creature", or "by a creature other than you".  (I can't see the new wording yet, so ignore my comment if it's already like this)

**Comment by mlenser** [comment]
I've chosen the same wording as all similar places: "that isn’t being worn or carried by another creature"

None of them (darkness, daylight, animate objects, catapult), allow usage on a willing creature.
