### ISSUE TITLE
Re-add Grapnel to Forge

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#792]
Grapnel was a spell similar to Vine Lash and Webshooter, which created a grapnel that could be attached to objects. It was removed from Creation long ago for some reason I don't understand (see below), but I think it should be there.

The justification was:

> Grapnel removed as it is more of an item than fitting for a theme that creates an item. The creation theme could create a similar item, but the way the spell is worded now (how it is powered by your spellcasting ability) is more fitting for the other themes that it was duplicated to (Plants and Beast)

I don't understand what is the issue with this? Creating a temporary item seems reasonable as a spell in Forge. Maybe that meant that there should be an item which is a grapnel, and a spell that allows the caster to create any item? 

About "how it is powered by your spellcasting ability", I think your spellcasting can create better and more efficient items, tigher ties and stronger hooks, so that shouldn't be an issue.

**Comment by mlenser** [comment]
I believe there should be a clear dilineation between spells and tech equipment (for when I can finally build the Artificer/Engineer #1). The Grapnel I believe is really tech equipment, not a spell. See https://www.d20pfsrd.com/equipment/weapons/technological-weapons/#TOC-Autograpnel

Forge is really about the magic side of creating/modifying objects. I don't believe it should make tech equipment which can then be used. That is the role of the Artificer/Engineer.
