### ISSUE TITLE
Witch's Alchemy Ability only applies to Concoctions

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#793]
The Witch has this cool feature where she uses Wisdom for her Alchemy Checks, instead of Int. Except that's the _intent_ of the feature, not how it's written. The feature is described in this paragraph here (emphasis added):

> Alchemy Ability
> Wisdom is your alchemical ability **for your concoctions** since you learn your concoctions through ancient traditions and following the old ways. You use your Wisdom whenever **a concoction** refers to your alchemical ability. The Alchemy skill describes how to create a concoction.

The problem here is that, as written, you only use Wisdom in place of Int **for concoctions**. This means all of the other uses of the skill still require Witches to use Intelligence.

I know from Discord discussions that this isn't the intent, so we just need to fix the wording! Here's my first, rough attempt:

> Alchemical Ability
> Wisdom is your alchemical ability, since you learn your alchemy through ancient traditions and following the old ways. You use your Wisdom when using the Alchemy skill, including whenever a concoction refers to your alchemical ability. The Alchemy skill describes how to create a concoction.

The discord discussion then segwayed into whether certain skills should even have defaults, but that's a mostly seperate concern.

**Comment by mlenser** [comment]
I think this solved it, does it?

![image](https://user-images.githubusercontent.com/235857/116589192-ae193c80-a91c-11eb-9949-c9761885b17e.png)

**Comment by DalenWBrauner** [comment]
Hrmm... almost.
The disconnect is that Concoctions are functionally separate from other alchemical work and creations. Even that sidebar still kinda implies that Occultists can use Wisdom for concoctions, but it's not 100% clear whether they can for the other uses of the Alchemy skill, like Recall Knowledge.

Another concern with the sidebar approach is that it wouldn't stop the original paragraph from being unclear. I think a sidebar can absolutely help, but players should be able to understand that they can use Wisdom for all Alchemy checks _just_ from the Alchemy Ability section alone.

**Comment by mlenser** [comment]
Alchemical ability is just for concoctions. The same as Spellcasting ability is just for spells.

Acolyte for example:
> If you choose Wisdom the power of your spells comes from your devotion to your deity. If you choose Charisma the power of your spells derives from the strength of your convictions.

They can still use Charisma for Divinity, but "Spellcasting ability" and "Alchemical ability" are keywords used by concoctions/spells.

**Comment by DalenWBrauner** [comment]
Sure, I have no problem with keeping the Alchemical Ability section focused on Concoctions.

But we do still need the following to be clarified somewhere on the Witch's class page:

> The Witch uses Wisdom for _all_ of Alchemy.

Should it be in its own, or some other section, if not the Alchemical Ability section?

**Comment by mlenser** [comment]
@DalenWBrauner this feels clear enough to me.
![image](https://user-images.githubusercontent.com/235857/119259787-36af9380-bbd0-11eb-8146-ed5a219fc229.png)

The whole skill changes ability based on how you learn your concoctions.
