### ISSUE TITLE
Consider Weapons and magic skills using ability checks

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#796]
If your body is so poisoned that you can't stealth or shove effectively, why wouldn't it impact your attacks and spellcasting?

I'd need to filter through all things that impact ability checks and rebalance.

**Comment by itamarcu** [comment]
>  impact your attacks and spellcasting

To be clear:  the Poisoned condition currently gives disadvantage on attack rolls and ability checks.  This means that it does affect weapon attacks and spell attacks, though it doesn't affect maneuver DCs or spell DCs.

Anyways, as a pretty basic change (not necessarily the right solution), you could change Poisoned to also be:

> While poisoned, your maneuver DC and spell DC are reduced by 4.

or:

> While poisoned, creatures have advantage on saving throws against your spells and maneuvers.

Some things to consider, however:

- If both the attack has disadvantage and the maneuver is easier to save against, the condition might be extra debilitating to martials.
- Some maneuvers and spells are still unaffected - those that buff yourself/allies, have only utility, summon companions, have no attack/save, etc.
- Thematically, it's a bit odd for some spells to be unaffected.  You could say that Slow requires penetrating magical defenses, but Haste doesn't.  Lightning Bolt and Cone of Cold require some aiming on the mage's part, but Silence and Mirror Image don't?

**Comment by mlenser** [comment]
> the Poisoned condition currently gives disadvantage on attack rolls

Ya, that was a bad example. A better exmaple if Exhausted 1 vs 3.

And as you say, spell DCs are currently not impacted by these things at all, but probably should be.
I agree that attacks and manuever DC shouldn't double up on the pain.

It's a bit tricky to solve, but not too bad I think. I'll have to think through the ramifications though.

**Comment by Marcloure** [comment]
There is also concoctions' DC, which is a bit wacky since I guess you define the DC the moment you craft the concoction, not when it is thrown

**Comment by mlenser** [comment]
Aptitude Bonus moved us 1 step closer to this reality.

**Comment by mlenser** [comment]
I solved this as part of `30.0.0`. Spell DCs are not impacted as they are 2 off in the math and I'm not sure they should use ability checks at all as they would then be impacted by advantage which isn't too challenging to get. My loose feeling is that'd be a negative if they were impacted by advantage.
