### ISSUE TITLE
Imbue spell metamagic option should not be a major metamagic

### ISSUE THREAD

**Issue by Paulorpribeiro** [mlenser/kryx-rpg-issues#797]
**Describe the solution you'd like**
I think imbue spell should be a regular metamagic option, not a major metamagic option.

Comparing the options internally, major metamagics improve the damage (empower), number of targets (twin, reverberation, widen), make the spell harder to resist (highten) and improve action economy (quicken).

Imbue spell, on the other hand just improves the range of the spell if you hit with a ranged weapon (unless I'm missing something). It is much more similar in power with the regular metamagic options IMO.

Just for completion, regular metamagic options improve range (distant), duration (extend), accuracy (seeking) and saves allies from aoe spells (sculpt). 

All major metamagic options increase the damage of the spell in some way, with the exception of imbue spell, while regular metamagic improve the spell in other ways.

For those reasons I think imbue spell should be put under regular metamagic.

If I missed something please let me know. If I Imbue spell, apart from the mechanical benefit of increasing the range, is very flavourful for gishes and arcane archers, who need to select 2 feats to get its benefits.

**Comment by Marcloure** [comment]
I think the intention is that you gain an extra action to make an additional attack with the imbued weapon, but the text isn't clear on that.

**Comment by Paulorpribeiro** [comment]
If that is the case, I agree it being in the major metamagic. Although one attack is a lot less powerful than an additional 1 mana spell (comparing to quicken).

Also, in this case, I would advocate for a "lesser" imbue spell option in regular metamagic that doesn't include the additional attack just for flavour reasons

**Comment by mlenser** [comment]
Imbue Spell is a very strong option that "breaks" the action economy.

With Imbue a creature can take two actions and one (or two) of those actions can be to cast a spell and make a weapon attack. Effectively 3 actions for the price of 2.

This is a huge increase in burst potential that is not available in other ways. It is definitely a major option.

Without the attack there is no reason for Imbue to exist. A character can already make one attack and cast a spell.

**Comment by Paulorpribeiro** [comment]
Good, agreed

**Comment by Paulorpribeiro** [comment]
You can close the issue, nevermind that me and Marcloure both think the text isn't superclear on the extra attack, it's all good

**Comment by mlenser** [comment]
It is closed. I also cleaned the text slightly.
