### ISSUE TITLE
Merge Restoration and Antiplague concocitons

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#798]
Why is Antiplague a different concoction from the Restoration Potion? The Restoration spell can remove diseases with Greater Restoration, but the concoction version requires another pick to deal with this one niche thing (not like diseases are a common problem)

**Comment by mlenser** [comment]
Antiplague is advantage on disease and augments to remove the disease. Greater Restoration is 3 mana and only removes. So it's the same cost as an augmented Restoration spell.

Restoration potion differs from the spell in this regard. http://2e.aonprd.com/Equipment.aspx?ID=81 is the basis for the idea of antiplague.

If anything, Restoration is probably too versatile. Diseases and possibly other options should not be available in restoration.

**Comment by mlenser** [comment]
- Neutralize Poison added as a spell to the Life, Plants, and Poison themes.
- Remove Disease added as a spell to the Life theme.
- Protection from Poison Potion added to the Life theme and the ability to remove a poison is now at 2 catalysts.
- Restoration no longer interacts with poisons or diseases as we have Neutralize Poison, Protection from Poison Potion, Remove Disease, and Antiplague.
