### ISSUE TITLE
Merge Shadow Walk into Shadow Form

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#799]
Shadow Form is similar to Gaseous Form/Aqueous Form, and Shadow Walk is similar to the augmented version of those spells, so I think this merge should happen.

At least, Shadow Walk should be at 3 mana, as is the Wind Walk and Water Glide augments.

**Comment by mlenser** [comment]
Shadow Walk changed to an augment of Shadow Form.
