### ISSUE TITLE
Remove "you have trained to use martial weapons" from classes

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#800]
This information is completely useless, since there isn't any definition, requirement, or reference to being "trained" to use weapons. Full casters state that you can't become proficient with weapons, and that should be enough.

**Comment by mlenser** [comment]
It's used for 
![image](https://user-images.githubusercontent.com/235857/119193539-0eb21a00-ba82-11eb-987c-0f1df755f6d5.png)

**Comment by Marcloure** [comment]
Hmm, that rule is kinda hidden there. Shouldn't it be in the weapon skill section instead?

**Comment by mlenser** [comment]
The weapons section is where all the rules for weapons are. Simple/Martial, weapon groups, etc.

It would be a lot of duplication to put it in both places. The weapons skill is meant to be streamlined and the weapons page should be the main reference.
