### ISSUE TITLE
Update how language features work

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#801]
With the introduction of the Linguistics skill, dozens of features and spells that grant languages or state something like "you can speak, read, and write Aquan" needs to be updated.

The Suffused has a lot of these features, and many feats also grant languages in that way. The Knowledge of Ages spell has: "you learn a language or gain proficiency in a skill for the duration", which is redundant?

**Comment by mlenser** [comment]
Linguistics is a way to progressively learn languages. If you know them outright from some species or other method then I'm not sure specifying Linguistics is the right way to go.

It's maybe nice to have them consistent, but then it's a bit less direct..

**Comment by mlenser** [comment]
References to languages now refer to the Linguistics skill.

**Comment by mlenser** [comment]
You were right - consistency is more important.
