### ISSUE TITLE
Reduce Foresight duration to 1h/mana or psi

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#804]
There are a few reasons for my thinking:

- Foresight is a 9th level spell in 5e. While it may not be worth that slot, even if it was a 7th or 8th level spell, you can't cast another spell of those levels until the 20th level. So it's either Foresight or any other high level spell.
- The greatest contender to Foresight is **Greater Invisibility**. While Greater Inv. makes you untargetable, so it's arguably stronger, it only lasts for a bit more than a fight (4 min). Foresight lasts for the whole day (12h).
- Reducing it to 4 hours makes it last for a whole scene still, be it a dungeon crawl, a long social dispute, an infiltration, whatever it is, so it still competes well with Greater Invisibility.
- Lasting 12 hours means that you can cast Foresight right before bed and still get 4 hours of it on the next day. While this may occur as a problem for other spells too, it is most problematic with generic buffs like this one.

The Foresight Potion should be adjusted as well.

**Comment by mlenser** [comment]
Foresight also does not require concentration in RAW. In RAW it is considered one of the weaker higher level spells. I haven't formed an opinion yet, just responding to the concentration part.

**Comment by Marcloure** [comment]
I don't think it should be concentration, since concentration defeats the point of a long-lasting buff. I was just pointing out another difference in favor of Foresight.

**Comment by mlenser** [comment]
Foresight and Foresight Potion changed to 1 hour/mana, psi, or catalyst.
