### ISSUE TITLE
Battle Leader should end if you fall unconscious

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#805]
Currently, the maneuver lasts even if you fall unconscious, but I think it should not. Alternativelly, it could require concentration ("concentration like a spell"), but then it would be the only maneuver with concentration.

Also, it should require that the affected creature can see or hear the user.

**Comment by mlenser** [comment]
This would apply to all maneuvers. All the maneuvers that have a duration and aren't weapon based:

- Battle Leader
- Covering Strike
- Fearsome Beast
- Untouchable
- Unwavering Mark

**Comment by mlenser** [comment]
Battle Leader requires the creature to see or hear you.

**Comment by mlenser** [comment]
Battle Leader, Fearsome Beast, and Untouchable now end if you are incapacitated.
