### ISSUE TITLE
1.5x proficiency increases creatures spellcasting

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#806]
The Priest, for instance, applies 1.5x their proficiency bonus to Divinity, but that would result in an increase of their spellcasting DC by 1. There are probably other creatures that have 1.5x their proficiency in spellcasting skills.

I think expertise should just be removed from creatures as well, maybe with some few exceptions like a dragon's perception.

**Comment by mlenser** [comment]
Currently, creature's spellcasting is not based on their skills so this is not a current problem. Though I should update it so the spellcasting is based on skills.

**Comment by mlenser** [comment]
All creatures with spellcasting now have that spellcasting associated with a skill and have proficiency in that skill.

**Comment by mlenser** [comment]
Creatures no longer have any expertise in skills. Any existing expertise is now proficiency.
