### ISSUE TITLE
Precognition duplicates Fortune's Favor

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#808]
https://www.kryxrpg.com/spells/precognition
https://www.kryxrpg.com/spells/fortunes-favor

Precognition does the same as Fortune's Favor, except it can't target allies. It should just be removed.

EDIT: I lie, Precognition also increases Defense, but I think this shouldn't be the case. It makes it a generic spell, and smaller version of Foresight.

**Comment by mlenser** [comment]
Fortune's Favor is a mirror of Bless, but for the Fate theme. It applies to two creatures.

Precognition is a self-only, so it is weaker, but it also allows you to boost your Defense. It is meant to mimic the PF psionic power https://www.d20pfsrd.com/alternative-rule-systems/psionics-unleashed/psionic-powers/p/precognition. I don't think we should remove it.
