### ISSUE TITLE
Cantrip Scaling for Non-Players

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#81]
While working on a character with a Dragon Eidelon, I noticed that some of the Dragons have damaging cantrips. As companions, these dragons don't have "levels", so it's not clear whether their cantrips should scale, or how. I would imagine it either relates to the amount of resources poured in, or to the player's level. I have less of an idea how this would scale for a monster in general.

**Comment by mlenser** [comment]
Now I finally have the answer to why monsters had the spellcasting level listed.

I'll add it to all monsters with cantrips.

**Comment by mlenser** [comment]
Monsters now show their caster level
