### ISSUE TITLE
Wind Walk and similar augments should scale better for more people

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#810]
Aqueous Form, Corrosive Form, Gaseous Form, and Wind Walk Potion - all have an option to cast something like Wind Walk, where for 3 mana you become a flying/swimming thingie with a speed of 100m for 1 hour/mana.  They also have an augment to add +2 creatures per mana, the same augment that the base spells (e.g. Gaseous Form) offers.

I think the augmented forms of these fast-mobility spells should give you +4 creatures per mana instead of +2 per mana.  This way, a standard party could wind-walk with 4 mana.

Compare this to 5e where Wind Walk is a 6th level spell, lasts for 8 hours, and allows up to 11 creatures.

Also consider that Distant Teleport and Plane Shift allow moving a party of 5 characters for 4 mana (and much faster, though Wind Walk does have its benefits sometimes).

**Comment by mlenser** [comment]
I'm not so sure about this as I purposefully changed these spells to be less impactful so they take a lot of investment to apply to the whole party. Though [PF2e's Wind Walk](https://2e.aonprd.com/Spells.aspx?ID=376) allows for the whole party to move.

I'd need to align spells like Distant Teleport, Plane Shift, Wind Walk, etc to a standard of how many creatures it should affect.

@itamarcu can you help identify any other spells that affect a whole party in this way?

**Comment by itamarcu** [comment]
I think it should be:
- balanced against other spells of the same cost (e.g. if DT and PS grant the best long-distance travel for 5 people, at 4 mana, WW should allow a similar power level)
- an instant skip from "one person" to "all party", if it's a spell that you'd almost never want to cast on only half the party.
- easier to add more people to utility spells than to combat spells
- Tier 4 seems correct for the power level of group teleportation.  Tier 1 has swimming/climbing and steeds, Tier 2 has stuff like word of recall and dimension door and flight, Tier 3 has distant teleport and wind walk.  each tier allows a new form of movement for yourself and allows expanding the previous tier's movement to your whole party.

Aquatic Adaptation (1) - change +1 to +2 in the augment, and even consider +4. 

Feather Fall (1) - basic spell is "up to four willing creatures", with augment for +5.  I think the basic spell should be "up to five" to make it less awkward, as the normal party size is 5 people.  It's fine to keep the reaction version as it is.

Invisibility - Shared Invisibility (1+1) - I think additional augments should add +4 creatures per mana instead of +1.  this would mean you spend 3 mana to get a group-wide stealth "bonus" for 1 minute, but you'd have to spend 4 mana to make it a longer duration (1 hour).  this is all still worse than 5e RAW, which allows entire party for 1 hour with a 5th level slot.

Phantom Steed (1) - change the 1 mana augment from creating +1 steed to creating +2 steeds.  also, maybe make it a ritual, like 5e.

Levitate (1) - change +1 to +2 in the willing targets augment (keep it +1 for unwilling targets).  Levitating a full party up/down a cliff or a tall building seems fair for 3 mana.

Natural Weapons (1) - change the augment to simply be +4 willing creatures per additional mana.  gaining natural weapons is not a real buff spell.

Striding and Springing, Climbing Claws, Wall Bind, Sand Walk (1) - change +1 to +2 in the augment.

Water Walk (2) - change +1 to +4 in augment.  (5e allows all party with 3rd level spell, so it's still weaker)

Air Bubble (2) - change +1 to +4 in the augment.  (5e allows Water Breathing for all party with 3rd level spell, so it's still weaker)

Amorphous Form, Gaseous Form, Aqueous Form, etc (2) - change +1 to +2 in the augment.

Darkvision, Essence of Night (2) - change +1 to +4 in the augment.  granting Darkvision to your whole party isn't that strong in my opinion, but if you think it is, a +2 augment is still more than fair.

Telepathic Bond (2) - change +1 to +4 in the augment.  (5e is 5th level for 8 creatures so still stronger).

Warped Wings (2) and all similar spells that give flight - maybe change +1 to +2 in the augment?  (5e Fly is 3rd level with +1 creature per slot, which maps to +2 per mana.  it might make it more powerful in combat, though, and I don't know if flight is undervalued in 5e)

Wild Shape (2) - change +1 to +2 in the augment.  (It's balanced against Polymorph because the augment only allows willing targets, and at 4/5 mana this would be equivalent to 5e's Animal Shapes)

Temporal Progression (2) - maybe change +1 to +2.  using it on your entire party should be possible and 4 mana seems fair for that.

Etherealness (3) - change +1 to +4.  changing the entire party into ethereal ghosts for 4 mana, when it's only 5 minutes and dismissed for everyone at once when it's done, seems fine.  spells like Word of Recall already allow a better escape plan, and if you're using it to get past obstacles you could often already do it with Dimension Door and Clairvoyance.



Examples of spells that don't need changing:  Distant Teleport (3 with +4 augment), Plane Shift (3 with +4), Teleportation Circle (3, allows entire party, but limited), Astral Projection (3 with +4).

**Comment by mlenser** [comment]
Wild Shape is different from the other spells. It is 2 mana to use on yourself and 3 mana + concentration to use on someone else. It could possibly add one additional creature at 4 and 5 mana, but that's still a lot...

**Comment by mlenser** [comment]
Overall, I think some of the choice listed above are too ambitious. 5e is not the baseline that I'm trying to match. I think the 5e version of Telepathic Bond for example is too strong. 1 creature at 2 mana, 3 at 3 mana, 5 at 4 mana, and 7 at 5 mana seems good to me.

**Comment by mlenser** [comment]
Another balance point: Affecting so many creatures makes spells significantly stronger than concoctions. Concoctions cannot be augmented to target multiple creatures so options like Aquatic Adaptation become much better as spells than concoctions.

**Comment by mlenser** [comment]
- Astral Projection, Distant Teleport, Plane Shift, and Word of Recall now augment to transport five additional creatures. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)
- Etherealness now augments to target five additional creatures. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)
- Temporal Progression now augments to target two additional creatures. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)
- Feather Fall now affects up to five creatures. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)

**Comment by Marcloure** [comment]
> Affecting so many creatures makes spells significantly stronger than concoctions

On the other hand, concoctions don't require concentration, so some spells weight in favor of concoctions

**Comment by mlenser** [comment]
> On the other hand, concoctions don't require concentration, so sometimes the weight is in favor of concoctions

I'm all for there being some uniqueness, but that has to be balanced.

Current balance:
- Wind Walk potion is 3 catalysts, no concentration
- Wind Walk spell is 3 mana, no concentration. Augmentes for +2 people.

I think this current balance is good. The concoction is unique in that the action economy can be split and other minor differences. However, if Wind Walk spell augments for +4 people then the balance is problematic.

As I wrote above: 5e isn't my target. I think many of these spells are very powerful and with the ability to affect so many creatures become overpowering which makes spellcasting overpowering martials and alchemists.

**Comment by itamarcu** [comment]
> Concoctions cannot be augmented to target multiple creatures

This is a separate problem - I think it'd be fine to give them similar augments, but if you don't want catalysts to do that I suggest creating a feat/feature that allows making batches of identical concoctions, brewing and using them all together.  Regardless, I think this is a limitation imposed on concoctions that shouldn't matter to spells.

> Overall, I think some of the choice listed above are too ambitious

I'd like it if you gave a more specific reason not to make those changes, because I thought all of them through and I think some spells would be much less useful without them.

Some extra thoughts:
- Invisibility - there are a lot of situations where you want to turn the entire party invisible.  The "Dust of Disappearance" concoction already allows you to do that for 2 mana, so I think it's fair for the spell to allow a similar effect for 2-3 mana.
- Air bubble, Water Walk - if you need to fight underwater, run across a lake, escape a sinking ship, etc, you really don't want to spend 2 mana per character, but it's useless to only cast it on half of your party (because the rest will drown).  There's no maneuver for "hold your breath for an hour" or "jump to the other side of the lake", so your party has to rely on you.
- Climbing Claws, Wall Bind - these are

**Comment by Marcloure** [comment]
I understand what you mean, but these travel spells lose a lot of potency if they can't bring the whole party (unless you have multiple casters). You would have to split the part every time you want to benefit from this augment

**Comment by mlenser** [comment]
> I think it'd be fine to give them similar augments

I understand your position. You want these options to be more powerful. I'd like you to consider what I'm saying though. If these become more powerful then spellcasters become more dominant in parties. You could try to make the alchemist also become more powerful, but the martial will fall further behind. That's not desirable.

_______________________

> You would have to split the part every time you want to benefit from this augment

Distant Teleport has all kinds of bad situations that can occur. Plane Shift only works toward other planes. Astral Projection can be problematic if tyour tether is cut. These spells have quite difficult restrictions and can only impact the party at 4 mana. That's a huge cost.

Wind Walk doesn't have these negatives. It takes time, but is very safe. It is also quite different thematically. Thematically teleport-like spells are quite different to "you transform multiple creatures". Teleport happens in an instant. Transforming multiple creatures is changing their whole physiology. It should be harder.

**Comment by mlenser** [comment]
- Wind Walk Potion removed as it is really too magical in that it transforms you to a cloud. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)
- Invisibility’s Shared Invisibility augment now targets two additional creatures or objects for each additional mana or psi expended. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)
- Phantom Steed augment now creates two additional steeds. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)
- Sand Walking Potion added to the Sand theme.
- Amorphous Form, Aqueous Form, Corrosive Form, Gaseous Form, and Shadow Form aligned on augmenting for two additional creatures. Shadow Walk, Wind Walk, and Water Glide changed to augment for five additional creatures. [#810](https://github.com/mlenser/kryx-rpg-issues/issues/810)

__________


Other comments below:

- Aquatic Adaptation. I'm not willing to make the spell stronger than the potion. If there is some thematic way to make the concoction able to target multiple creatures (like Dust of Disappearance) then I'd be willing to bump it to 2 additional creatures per mana or psi.
- Phantom Steed as a ritual. I believe ther ability to create mounts which provide combat utility and travel utility should cost resources.
- Levitate. See Aquatic Adaptation. Though this would be problematic with Fly.
- Natural Weapons. See Aquatic Adaptation.
- Striding and Springing, Climbing Claws, Sand Walk. See Aquatic Adaptation.
- Water Walk. The spell is already better in that it can augment for 3 mana = 2 creatures and it is a ritual. The concoction is 2 catalysts = 1 creature and it is not a ritual.
- Air Bubble. You're suggesting making casters be able to fully bypass challenges with just a few mana. That doesn't lead to a balanced game. It leads to a game where casters are expected to solve all the problems. That's not a healthy game. Casters should be able to solve some problems, but they shouldn't be able to do so with trivial investments. Air bubble can affect the whole party if cast multiple times. I believe it is healthy for the party to sink most of the mana into trivializing a major problem like breathing in environments where they normally couldn't.
- Darkvision, Essence of Night. These cannot be stronger than the concoctions. Cast it multiple times.
- Telepathic Bond. This lets you bypass many social issues. It also slows down games in that parties can now small talk a ton. 1 + 2 seems fair to me.
- Warped Wings. Flight is strong. It already augments efficiently. I don't see a need to make this stronger by making it usable on a larger group for less mana than currently.
- Wild Shape. Manipulating the form of a creature is difficult. I don't see a need for a party to all be able to turn into bears for less resources than currently. It can already be cast multiple times if really needed.

**Comment by mlenser** [comment]
Closing this as there have been no further suggestions for any of the items not done on the list above.
