### ISSUE TITLE
Rapid Aging (Time Ravage augment) should age more

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#811]
Currently, Rapid Aging ages the target a number of years equal to half the base damage (3d12). That avarages to 10 years. I think it should be the full damage, so an avarage of 20 years.

**Comment by Marcloure** [comment]
Another option is to make it a 4 mana augment, instead of 5 mana augment.

**Comment by mlenser** [comment]
Why should it age more? 10 years is a significant amount of time in a human lifespan.

**Comment by Marcloure** [comment]
It doesn't feel 5 mana enough. Aging someone from 20 to 30 years, or from 30 to 40, or from 50 to 60, while it's definitively a lot of years lost, doesn't seem like it would cause a big impact on the development of story.

**Comment by mlenser** [comment]
If such a spell is cast multiple times it would.

I don't think aging should be easy, especially since it is non-reversible without wish or other capabilities.

**Comment by Marcloure** [comment]
It's a 5 mana spell, you can't cast it multiple times in a row. I was thinking that you can't have an old person come to you and say they were robbed of their youth (unless the DM use a custom effect, of course). Like, either they were young adult and are middle adult now, or they were old and just kept being old.

**Comment by mlenser** [comment]
> It's a 5 mana spell, you can't cast it multiple times in a row.

Yes you can:

- 1 character casts it over multiple days.
- A party stacks up multiple casters with it and instantly kills the human boss by all casting it.


> I was thinking that you can't have an old person come to you and say they were robbed of their youth

Sure you can: that person just had this spell cast on them multiple times or there is some other magical effect that is not this spell.

Closing this as I don't think aging should be super accessible.

**Comment by Marcloure** [comment]
> A party stacks up multiple casters with it and instantly kills the human boss by all casting it.

If killing is the goal, it's easier to just pick the damaging option. But I disgress, it's set then.
