### ISSUE TITLE
Merge Quicken Reaction into Memory of One Thousand Steps

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#812]
Both are Time spells that add 1d4 to either Reflex or Defense. I think both spells can be merged together. Also, returning to a previous point seems to make sense against Reflex save effects.

**Comment by mlenser** [comment]
It is meant to be limited like Thought Shield is limited to Will saving throws... hmm

**Comment by mlenser** [comment]
Quicken Reaction merged into Memory of One Thousand Steps.

**Comment by Marcloure** [comment]
> It is meant to be limited like Thought Shield is limited to Will saving throws... hmm

There are other spells that can apply 1d4 to attacks, Defense, skill checks, etc. Twist Fate, for instance, can affect every kind of roll from any creature (including enemies).
