### ISSUE TITLE
Control Shadow's grapple is too strong for a cantrip

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#814]
The Shadow Anchor option deals damage and grapples the target. This is much better then, say, Frostbite, which reduces the target's speed by 2 m. Grappling is specially good against flying creatures, since it makes them crash.

To remain thematic and unique, I think it should make the target unable to move more than 5 meters away from its shadow.

**Comment by itamarcu** [comment]
This is a bit ambiguous but you could say that the spell cannot be used to harm a flying creature, because it's not touching its own shadow.  That would be a neat limitation that also serves as a "balance patch".

**Comment by mlenser** [comment]
Control Shadow damage when grappling recalculated so its damage is much less.

**Comment by mlenser** [comment]
I recalcualted it. It now deals 1d3 damage instead of 1d8, which is much less than Frostbite.

Grapple can be escaped from or teleported out of, but it's still a heavy cost.

> Grappling is specially good against flying creatures, since it makes them crash.

The cantrip anchros a creature to terrain. Flying creatures aren't near terrain to be anchored to.

**Comment by mlenser** [comment]
I'll take a second look at this. Perhaps it should be a 1 mana spell like Ensnare.

**Comment by mlenser** [comment]
Shadow Anchor split from Control Shadow as its own 1 mana spells that is somewhat similar to ensnare, but has its own unique identity that has some slight synergy with Control Shadow.
