### ISSUE TITLE
Increase Bindings/Cocoon health per mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#815]
I think the Health / Defense of these spells should increase per mana, otherwise it's pretty easy to destroy them with an action after a certain level.

I was actually going to suggest to remove it, but I figured I already did on #788.

**Comment by mlenser** [comment]
Bindings, Cocoon, Ice Spear, Stalagmite, and a few other spells have has their objects defense and health increase when more mana is spent.
