### ISSUE TITLE
Clarify Tear Flesh enhancement

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#816]
https://www.kryxrpg.com/maneuvers/tear-flesh

Tear Flesh is a maneuver that deals an initial damage and then damage over time. It's enhancement should be clear whether the increase is only to the initial damage or to both damages (like Quivering Palm does).

**Comment by mlenser** [comment]
Bloodletting Blade and Tear Flesh now both specify:

> You can increase both damages for each additional stamina die expended.
