### ISSUE TITLE
Divine Word shouldn't affect constructs

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#817]
I posted this comment on #784 , and you asked me to open a new issue. You also asked:
> Why would constructs be immune to the holy word of a deity?

If a golem is walking to attack a creature, and the creature shouts with the voice of Thor thundering the skies, I can't imagine the construct being any affected by this. Mortals, planar creatures and undead would flee or be destroyed by the divine power, but the same way you can't use Divine Word against a door, you shouldn't be able to use it against a flying sword or a robot. I don't think a golem would stop in awe and recognize the grandeur of a god were they to face one.

**Comment by mlenser** [comment]
It affects constructs in 3.5 as far as I can see.

https://www.d20pfsrd.com/magic/all-spells/h/holy-word/

**Comment by Marcloure** [comment]
Yeah, ok. It's still weird that it does to me, but that is fine.
