### ISSUE TITLE
Thri-Kreen is not considering 6 m. of speed on the species' spreadsheet

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#818]
https://docs.google.com/spreadsheets/d/1LMmA8rGcXLxNz_EnH3SrD5R70UaQaYupdve5nmKtBcY/edit#gid=872807765&range=B251

The Thri-Kreen doesn't add the 3 points from having 6m. of speed like the Tabaxi right above does it.

**Comment by mlenser** [comment]
fixed
