### ISSUE TITLE
Juggernaut Warforged is missing their proficiency on unarmed strikes

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#819]
Warforged Juggernaut:

> ***Iron Fists.*** When you hit with an unarmed strike, you can deal 1d4 + your Strength bludgeoning damage, instead of the normal damage for an unarmed strike.

Other species (Centaur, in this case):

> ***Hooves.*** Your hooves are natural weapons, which you can use to make unarmed strikes that you are proficient with. 

---

Also, how does this guaranteed proficiency interacts with full casters? I suppose the specie is the exception in this case?

**Comment by mlenser** [comment]
> how does this guaranteed proficiency interacts with full casters

Hmm?

**Comment by mlenser** [comment]
Warforged Juggernauts are now proficient with their unarmed strikes.

**Comment by Marcloure** [comment]
> how does this guaranteed proficiency interacts with full casters

Full casters state that "you are unable to become proficient with a Weapons group", but the species's natural weapon say that you are proficient with those attacks. Which one is prevalent?

I suppose you are proficient with your unarmed attack but not with the Brawling Group?

**Comment by mlenser** [comment]
> Full casters state that "you are unable to become proficient with a Weapons group", but the species's natural weapon say that you are proficient with those attacks. Which one is prevalent?

Warforged are not becoming proficient with a weapons group. They are proficient with unarmed strikes (which isn't a weapons group).
