### ISSUE TITLE
Punch in Bunches + TWF

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#820]
One of my players figured you can play with two weapons and Punches in Bunches at the same time, allowing up to 5 attacks per turn:

Action 1: unarmed strike + punches in bunches + brawling fighting style (using kicks)

Action 2: weapon attack + off-hand weapon attack

I didn't do the math, but I believe the ability modifier being applied 4 times (since off-hand weapon won't apply the modifier) more than compensates for the lower damage of unarmed strikes. Maybe it doesn't though, so that would just be an interesting build.

**Comment by mlenser** [comment]
You shouldn't allow this, it's an oversight.

**Comment by itamarcu** [comment]
As an ugly/inelegant fix, you could add an extra sentence:

> **Punches in Bunches**
> Once on your turn when you use an action to make a weapon attack with an unarmed strike, natural weapon, or monk weapon, you can make one additional unarmed strike.
> You cannot use two-weapon fighting on the same turn that you make this additional attack.

**Comment by mlenser** [comment]
Brawling, Primal Aggression, and Punches in Bunches restricted to not be used with TWF. Primal Aggression and Punches in Bunches restricted to not be used together. Punches in Bunches can be used with TWF if you are a monk.
