### ISSUE TITLE
Move Freedom of Movement's immunity to paralyzation to augment

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#821]
Paralyzing effects were moved from 2 to 3 mana a while ago, but FoM is still at 2 mana. It's a concentration-free 2 mana spell that gives you immunity to many 3 mana spell and other effects.

**Comment by mlenser** [comment]
Aqueous Form and a few other 2 mana spells prevent being paralyzed as well. Preventing is quite different than solving the problem after it occurs as it requires investment before the problem happens which could be wasted.

I believe this is fine.
