### ISSUE TITLE
Reduce the Bone Devil Polearm's CR

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#823]
https://www.kryxrpg.com/creatures/bone-devil-polearm

The standard Bone Devil is CR 9. I don't think the increase in damage alone is enough to make this version 3 CR higher. The MM doesn't say anything about increasing the CR.

EDIT: actually, it isn't even more damage. Polearm attack is 1/turn, while claws are 2/turn.

**Comment by mlenser** [comment]
Bone Devil Polearm challenge changed to 10. It does more damage than the standard Bone Devil and its estimated challenge is 10.5 so this feels like the right power level for it.

**Comment by itamarcu** [comment]
> EDIT: actually, it isn't even more damage. Polearm attack is 1/turn, while claws are 2/turn.

Just FYI - the normal bone devil's damage is 8+8+30 (claw+claw+sting), while the polearm version deals 8+17+30 (claw+polearm+sting).  it's 46 vs 55 damage, so it's definitely more damage.

By the way, apparently the original BDP can attack twice with the polearm, so its damage is 64 - which probably justified CR 11 or 12.

**Comment by mlenser** [comment]
The original is one attack with the polearm, which I replicate
![image](https://user-images.githubusercontent.com/235857/120771237-4c518100-c51f-11eb-8af3-69f133c3dbeb.png)
