### ISSUE TITLE
Oni should have cantrips

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#824]
They have spells but no cantrips. They should have one from each of Air, Charm, and Ice. I'd suggest Frostbite, Empathy, and Gust

**Comment by mlenser** [comment]
That is how the Oni is by RAW
![image](https://user-images.githubusercontent.com/235857/120901284-2a98ec80-c63a-11eb-91df-c443b8eb6ffe.png)

Not all creatures have extensive spellcasting (cantrips). The Oni is mainly a martial character with a few spells here and there.
