### ISSUE TITLE
Specify what happens if you interact with another creature while in Temporal Bubble

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#826]
https://www.kryxrpg.com/spells/temporal-bubble

This spell doesn't mention what happens if you target of affect another creature while in the bubble.

**Comment by mlenser** [comment]
Time passes 24x as fast for the caster. So they can move much faster and do all kinds of things. It's pretty straight forward as I see it, but perhaps something is missing?

**Comment by Marcloure** [comment]
Does that mean they can take 24 turns for every turn everyone else takes? Can they attack enemies while under the effect of this spell? If yes, this is probably an inta-win spell in any battle.

**Comment by mlenser** [comment]
> If yes, this is probably an inta-win spell in any battle.

From the spell: 

> As you spend 10 minutes to cast this spell... The tear has a radius of 5 meters. If you leave that area or another creature enters that area the tear immediately ends.

Seems covered.
