### ISSUE TITLE
Update High Mana Spells on the rules page

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#827]
https://www.kryxrpg.com/rules/concoctions-maneuvers-and-spells

This page has a rule for using 5 mana spells or catalysts:

> **Concoction created using 5 catalysts**
> Concoctions created using 5 catalysts are particularly taxing to create. Once you create a concoction using 5 catalysts, you can’t create another concoction using 5 catalysts until you finish a long rest.

It should be updated to include 4 mana spells and catalysts as well. 

Also, you mentioned how you think this rule shouldn't affect creatures with higher limit, so I think that should be mentioned too.

**Comment by mlenser** [comment]
Removed it from this page so it only appears for classes
