### ISSUE TITLE
Some Mage clarifications required

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#829]
There are some interactions that I would like to confirm whether or not they are intended to work as they are written. First of all, it all depends from the fact that a character can know any theme, but can only know spells from their power source.

So, let's suppose a Mage who has the Light theme but can't cast spells from it.

The **Spellbook** feature states that:
> if you can decipher the unique system of notation used by the mage who wrote it, it is from a theme you know, it costs equal to (or less than) your mana limit, and if you can spare the mana, time, and costs to practice it and copy it.

So, this Mage is able to copy any Light spell they may find onto their spellbook.

**Arcane Adaptation** says that:
>  you can choose a number of spells you know up to half your proficiency bonus (rounded down) and replace each of them with another spell in your spellbook from a theme you know

So this Mage can swap any spell they know for Light spells (since they know the Light theme and have its spells in the spellbook)

**Arcane Inspiration** says that:
> you can cast a spell in your spellbook as if you know it

So they can cast any Light spell that is in their spellbook using this feature, since the Spellbook feature allows them to copy spells from any theme they know

--- 

The way it currently is, the Mage can know a bunch of themes outside their power source and use its spells with Arcane Adaptation and Arcane Inspiration. I believe this is not intended.

A simple solution for this is to require that a spell must be from the Mage's power source to be written onto the spellbook.

**Comment by mlenser** [comment]
> So, let's suppose a Mage who has the Light theme but can't cast spells from it.

Huh? If a character learns a theme, they are able to cast spells from it. It doesn't matter if the theme is from a subclass, feat, or Arcane Study for the mage. Arcane Study explicitly has wording to handle this: "That theme is considered to be from the Arcane power source."

**Comment by Marcloure** [comment]
> If a character learns a theme, they are able to cast spells from it

This is not true. A Druid can learn the Antimagic theme to pick feats from it, but they can't cast spells from that theme (since they can only cast spells from their power source).

I am not considering a Mage who learned Light through Arcane Study or Thematic Diversification, but a Mage who picked Light as a theme upon leveling up.

**Comment by mlenser** [comment]
So your scenario is a Mage who didn't use a subclass, Arcane Study, or Thematic Diversification to learn a theme, but used normal Arcane Discoveries and then the weird work around above? Sure, I can check and patch any hole, but it is minor edge case and clearly an abuse of the rules.

**Comment by Marcloure** [comment]
Yes, that is the situation. It's clear it's not intended, but it should be addressed nonetheless.

**Comment by mlenser** [comment]
This was already covered by item 2 in spellbook:

> Reproducing the basic form of the spell and practicing the spell until you are able to fully manifest the magic within.

However that isn't 100% explicit.

This is now covered by spellbook requiring the spell to be:

> it is from a theme you know in your power source
