### ISSUE TITLE
Spell Suggestion: Undo

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#830]
A flavorful utility spell for the Time theme, affecting objects.

Possible names:  Undo, Rewind, Revert, Regress, Undo Process.

---

# Undo (1)
As an action, you rewind time around a Small nonmagical object or parts of an object that you can touch or see within 5 meters and isn't worn or carried by another creature.  The object returns to the position and state it had just prior to your previous turn.  For example, pieces of a broken vase may be pulled together to make it whole again, a spilled drink may return into a bottle, and a hunting trap may reset itself.  You cannot cast this spell if any part of the object is out of your range or if it is prevented from returning to its previous location.

*Augment*
You can augment this spell with the following options, expending mana or psi for each option.
* You can expend 1 additional mana or psi to affect any number of small objects within 5 meters.
* You can expend 1 additional mana or psi to affect a Medium or smaller nonmagical object, or a portion of a larger object that is no larger than 2 meters across, such as a hole made through a wall.
* You can expend 1 additional mana or psi to revert the object by one minute instead of six seconds.

**Comment by mlenser** [comment]
Why not combine this with Undo Harm and make a more generic version that impacts creatures and objects? There is no reason to have one spell for creatures and one for objects as far as I can see.

**Comment by itamarcu** [comment]
Yeah, that can work too - I just preferred to keep them as separate spells for a few reasons:
- Both of these spells are pretty long so a combined version would be very long.  
- This suggestion is almost only useful out of combat, for utility, while rewinding creatures would be majorly useful during combat.
- Undo Harm is healing a set amount of health, and has augments that refer to the health (and to regeneration).  If this spell was "generalized" to work on creatures, I would expect it to simply undo all damage the creature took in the past round, which will be much stronger sometimes.  I'm in favor of it, but I'm not sure you are.
- Temporal Regression is actually a similar spell, but only affects either yourself or everyone within 200m.  It would likely be merged as well.
- I did consider suggesting another spell, which merely rewinds location but not state - i.e. it would move both creatures and objects back where they were a few seconds ago, but won't fix or heal them.  However, I think it makes more sense to rewind both at once.  And if you do that, then affecting creatures is stronger and even harder to balance against a utility spell (especially if the creatures have spent or regained resources like mana, health, potions, scrolls...).

I also considered suggesting this spell as a cantrip, which works similar to Mending or Prestidigitation but only as a reaction to items breaking/spilling/moving.  A cantrip like that should definitely not work on creatures, though, because it would be too useful.

Eventually and ideally, a Time Wizard / Chronomancer / Revision Mage should have a lot of versatility and should be able to do all of these things.  But I'd rather err towards making a dozen different spells with points of similarity than err towards having dense combined spells that don't fully satisfy everyone due to balance and complexity concerns.

**Comment by mlenser** [comment]
If a character can rewind time for a creature there is no thematic reason for them to be unable to rewind time for an object. If they are two separate spells then that requires learning two spells, which is not good.

> If this spell was "generalized" to work on creatures, I would expect it to simply undo all damage the creature took in the past round, which will be much stronger sometimes. I'm in favor of it, but I'm not sure you are.

Temporal Regression already covers that.

__________

As is, I won't add an object specific "rewind time" spell. It should be merged with Temporal Regression or Undo Harm or some other version should be created. Feel free to reopen if any of those pathways are taken.

**Comment by mlenser** [comment]
Temporal Regression can now affect objects.

Though it'd only be worthwhile on really important objects as the cost is high.

**Comment by itamarcu** [comment]
@mlenser That's exactly the problem I wanted to avoid by making it a different spell....  spending 3 mana to revert both yourself and one object is really not worthwhile, and there should be an easier way of doing that.

So how about changing the base spell to allow this?

- Basic spell is 1 mana (and 1 action) to regress a single object.
- augment for +1 mana to affect yourself or another creature.  this augment mentions that mana, stamina, and features do not change.  targeting an unwilling creature requires a saving throw.  (if you want you can make this version cost 2 actions, just like Power Word Heal is an augment that requires two actions)
- augment for +1 mana to add another target to the spell
- augment for +2 mana to change if from 1 turn (6 seconds) to 1 minute
- augment for +4 mana to change it to all creatures and objects within 200m.

This way it's still a single spell (single thing to learn), but rewinding time for an object is easier than doing it for a living creature - which is consistent with other spells (e.g. Telekinesis) and general balance.

**Comment by mlenser** [comment]
Some issues:

- Affecting yourself should _always_ be easier than affecting another creature or object.
- You've presumed that an object being restored isn't major. It could be campaign defining. I don't see a way to avoid that on low mana, so we have to assume the high value.

Going back in time is super nebulous. We can't assume relatively minor value. What if the king's crown is destroyed for example? Or some kind of Horcrux type thing? That's campaign defining.

**Comment by itamarcu** [comment]
Yup, that's why I added "nonmagical" (and a size limit) in the original suggestion.  There's almost never an important nonmagical object, and when there is, returning it 6 seconds back in time is very situational.  It's more likely that you'd want to Disintegrate it, steal it with Telekinesis, or fix it with Mending.

> Affecting yourself should always be easier than affecting another creature or object.

Yeah, I noticed that many spells are designed like this, so I'd like to stay consistent.  You could make it a 1 mana augment to target yourself and 2 mana augment to target another creature.

But also, I think there can be some valid reasons to not have the base spell affect only yourself:
- Usually the guideline you mention only applies to "buff" spells, that give you/others a strictly positive effect (such as Invisibility, Sanctuary, Hover).  The Temporal Regression spell can be either helpful or hurtful, depending on how you use it.
- There are exceptions to the rule, where it makes sense for targeting to be equally easy for everything (e.g. Vine Lash, Banishment, Dispel Magic...), or targeting only creatures but not necessarily yourself (Heal, Aid, Haste/Slow, Disguise, Feather Fall...) and there exist some spells where affecting creatures is harder than affecting objects or even impossible (Locate, Telekinesis, Immovable Object, Instant Summons).
- Thematically, rewinding a creature back in time can be considered harder than rewinding an object, because creatures have souls and magic and a constantly changing body, while objects are simple and usually static.

**Comment by mlenser** [comment]
Neither nonmagical nor a size limit solve the problem. A campaign defining item doesn't have to be magical or large.

The power of what you're suggesting varies between super minor to super impactful. There is no way to limit it without GM discretion.

**Comment by itamarcu** [comment]
If there's a campaign defining item that is nonmagical and small and not worn/carried and is within your range... why would this spell be the one that makes a huge impact on the game?

Disintegrate (or any acid/fire), Banishment, Hidden Pocket, Telekinesis, Animate Objects, Locate, Immovable Object, Image, Magic Aura, Instant Summons, Mending, Make Whole, Fabricate.  There are tons of spell that can be super impactful in that case.

I think there are enough limits on the object being targeted that this spell is in line with all other utility spells that affect items.  In particular, I think "not worn or carried" is a big one - most important objects I can think of will be held or carried, when they aren't lock and key.

**Comment by mlenser** [comment]
> Disintegrate (or any acid/fire), Banishment, Hidden Pocket, Telekinesis, Animate Objects, Locate, Immovable Object, Image, Magic Aura, Instant Summons, Mending, Make Whole, Fabricate. There are tons of spell that can be super impactful in that case.

- Disintegrate should be changed to target objects that are not being worn or carried, otherwise you could disintegrate weapons and armor of enemies
- Banishment is temporary
- Hidden Pocket can be recovered
- Telekinesis is just thievery which can be resisted and overcome


Undo prevents a scenario from occurring. Let's say a BBEG destroys some magical ankh, PCs could just undo that indefinantely. It puts too much control in the PC's pocket for 1 mana. Temporal Regression can cover this, at a higher mana cost.

**Comment by DalenWBrauner** [comment]
> PCs can just undo that indefinately.
What if the spell had:
> Once this spell has been cast on an object, that object cannot be targeted by this spell again for 10 minutes.
Would that resolve the concern?

While the spell can certainly have some impact, it does have a lot of limitations:
* You cannot cast this spell if any part of the object is out of your range (e.g. someone kicked a piece far away, or is simply covering it with their foot)
* If it is prevented from returning to its previous location (e.g. someone picked up a piece, which wouldn't even require an action)
* Has to be a small object
* Cannot be worn or carried

Anyone can break an item and then, if still in range, use their free item interaction to prevent it from being reassembled. So a DM has plenty of options to mitigate it, even without the 10-minute spam restriction.

**Comment by mlenser** [comment]
> Would that resolve the concern?

As above, affecting yourself should be easier than affecting another creature or object. Temporal Regression already covers this. We shouldn't have multiple spells for the same thing.

**Comment by mlenser** [comment]
Note: make whole from the Forge theme can reconstruct objects. So between a simple option like that and turning back time for a creature/object, this niche is covered as far as I can see.
