### ISSUE TITLE
Aiding Potion heals more than Healing Potion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#833]
Aiding Potion increases max and current Health by 15 (+20 per augment). Healing Potion heals for 3d8 (13.5 + 18). For the first time at least, Aiding Potion is a stronger heal.

**Comment by mlenser** [comment]
Aiding Potion should be updated to the same values as the spell. 9+10.

**Comment by mlenser** [comment]
Aid health changed to 7 and Aiding Potion health changed to 11 and augments for 15.
