### ISSUE TITLE
Clarify Illuminate spell

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#834]
https://www.kryxrpg.com/spells/illuminate

It's unclear to me what this spell does. It says "you can increase the amount of light emitted from objects", so you can't cast it on a dark room to light it up? Maybe you can increase the light emmited from non-luminous objects from nothing to dim light? If you can, what is the light radius of these objects?

Also, if you cast it on a torch, does it emmit 8 meters of bright light and no dim light? How does that work?

**Comment by mlenser** [comment]
The rules for Vision and Light are in the Adventuring section. https://www.kryxrpg.com/rules/adventuring.

Illuminate itself also specifies how it works:

> You can increase the light level by one step (no light to dim light, or dim light to bright light).

______________

All your questions should be answered by that except the bolded part below:

> Maybe you can increase the light emmited from non-luminous objects from nothing to dim light? **If you can, what is the light radius of these objects?**

Which I can come back and clarify.

**Comment by mlenser** [comment]
Illuminate slightly reworked to illuminate an area.

**Comment by itamarcu** [comment]
Maybe [Gloom](https://www.kryxrpg.com/spells/gloom) should also get "light emitted from objects in..." replaced with "light emitted in..."

**Comment by mlenser** [comment]
Gloom slightly reworked to deluminate an area.
