### ISSUE TITLE
Improve Vampiric Suffused origin's descriptions

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#835]
> **Bloodline**
> The vampiric gift runs through your bloodline.
> 
> **Patron**
> You are bound to a pureblood vampire lord of great power. Vampires seek thralls to act in their stead. You have earned the chance to drink its blood, becoming a pureblood yourself. You are now in service to a champion of night, blood, and undeath. What did it cost you to receive such a gift?
> 
> **Event**
> You have ingested the blood of a willing and living Pureblood. This is considered a great gift and is rarely given.

The description for event and bloodline are kinda bland, specially considering that power gained from another vampire ("you have ingested the blood of a willing and living Pureblood") is the Patron origin, not Event. This same description is indeed used in the patron origin.

I suggest:

#### Bloodline
The vampiric gift runs through your bloodline. Maybe you decend from a vampire lord or your lineage is tainted by some blood curse.

#### Event
You experienced some bloody tragedy that changed you. Whether you are the sole survivor from a village raided by vampires or on you were spilled the blood of a saint, this event both gifted and cursed you.

---

This "on you were spilled the blood of a saint" part references the myth that the first vampire descends from a Roman soldier who stabbed Jesus with a spear and Jesus' blood spilled on his mouth. I think this comes from Vampire the Masquerade?

**Comment by mlenser** [comment]
> you have ingested the blood of a willing and living Pureblood

A vampire giving you their blood does not make them your patron.


> You experienced some bloody tragedy that changed you. Whether you are the sole survivor from a village raided by vampires or on you were spilled the blood of a saint, this event both gifted and cursed you.

You don't turn into a vampire like this. You turn into a vampire by being born one or being turned. The suggestions here do neither.

**Comment by mlenser** [comment]
Vampire Bloodline description updated.

**Comment by Marcloure** [comment]
> A vampire giving you their blood does not make them your patron.

How not? Isn't your patron an entity that granted you powers? This seems like the vampire is giving you power.

> You don't turn into a vampire like this

The Vampiric Suffused isn't a vampire, they're a normal person with vampiric powers, but without being a proper vampire. They somehow gained some vampiric powers without being transformed, so this does make sense to me.

**Comment by itamarcu** [comment]
I thnk it's more correct to say that a vampire suffused is *not necessarily* a vampire.  They can be a full vampire, a half vampire, someone who made a deal to gain a vampire's powers, someone who got a blood transfusion from a vampire, someone who was bitten by a radioactive bat, or any other origin that makes sense.  If the player decides to also take the vampiric feats then that makes their character a "full" vampire, but a player could also choose a different character idea.

**Comment by mlenser** [comment]
> How not? Isn't your patron an entity that grants you powers? This seems like the vampire is giving you power.

A patron is a special kind of relationship. Drinking a vampire's blood does not make it your patron. It could, but doesn't have to. See the description of a patron:

> If you have a patron, spend some time thinking about your patron and the obligations that your pact imposes upon you. What kind of relationship do you have with your patron? Is it friendly, antagonistic, uneasy, or romantic? How important does your patron consider you to be? What part do you play in your patron’s plans? Do you know other servants of your patron? How does your patron communicate with you? Your familiar might occasionally speak with your patron’s voice. Some suffused find messages from their patrons etched on trees, mingled among tea leaves, or adrift in the clouds-messages that only the suffused can see. Other suffused converse with their patrons in dreams or waking visions, or deal only with intermediaries.

**Comment by mlenser** [comment]
> I thnk it's more correct to say that a vampire suffused is *not necessarily* a vampire. 

Suffused take the traits of their origin and eventually become powerful enough to transform into their origin.

For this case, the Suffused is definitely becoming a vampire. It doesn't just have some powers that vampires have.

> They can be a full vampire, a half vampire, someone who made a deal to gain a vampire's powers, someone who got a blood transfusion from a vampire, someone who was bitten by a radioactive bat, or any other origin that makes sense

See above. It's not just some bat powers. This origin is specifically about vampires.

**Comment by Marcloure** [comment]
> See the description of a patron

I don't understand, "you drank the blood of a vampire" seems to fit perfectly with that description. You need to think who's the vampire, what is your relationship with them, etc. Maybe if it was written in a way that the vampire itself doesn't matter, it would be better:

#### Event
You were baptized in a pool of vampire's blood, drank the blood of a vampire as part of a ritual or cult, or were for some reason cursed by the Dark Powers.

(I mentined the Darks Powers just as a nod to Strahd, you can remove it if you think it's out of place)

**Comment by mlenser** [comment]
Being baptized in a pool of blood doesn't turn you into a vampire. Moden mythical versions require some kind of bloodline, curse (more where it originated than new vampires), or being turned by an existing vampire.

I don't know what Dark Powers are, so will leave them out.
