### ISSUE TITLE
Remove "the GM rolls in secret" from commune

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#836]
https://www.kryxrpg.com/spells/commune

> If you cast the spell two or more times before finishing your next long rest, there is a cumulative 25% chance for each casting after the first that you get no answer. The GM makes this roll in secret.

Well, if the caster receives no answer, the result of this roll is obvious. There is no reason for the GM to keep secrecy about it.

**Comment by DalenWBrauner** [comment]
I'd like to propose an alternative: clear up the wording so that, instead of receiving no response from their diety, they do not receive a useful answer. That way the secret roll still does matter, *and* you get an important opportunity for roleplay.

Right now, I believe the text could be interpreted either way.

**Comment by mlenser** [comment]
That is how the wording appears in RAW 5e.
![image](https://user-images.githubusercontent.com/235857/121222192-9bccdf80-c886-11eb-80cc-a036066c500d.png)

Maybe there is a thread discussing this somewhere?

**Comment by Marcloure** [comment]
I found this thread:

https://rpg.stackexchange.com/questions/131578/what-will-be-the-difference-if-communes-secret-roll-is-not-rolled-secretly

The top answer suggests that it can be because the GM may decide to not give you an answer for some other reason, and you'll have no way to know if you rolled bad or something happened to your deity. That would be a bit weird though, since the roll only happens after the 1st attempt, so something would have to happen between your previous and current casting of the day.

**Comment by mlenser** [comment]
> However, depending upon your story, the deities themselves may be subject to things that might impair their ability to respond or they might opt to not respond to a diviner that has displeased them. Both of these potential story elements are within the realm of the DM to determine if they're even applicable, but if so, the roll should be made secretly.

This is a good argument. It should stay, imo.
