### ISSUE TITLE
Merge illuminate into light

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#837]
Both spells have the same flavor, with the only difference that one targets an area and the other objects. Merging both would simply make Light able to target a point in space too:

> As an action, you, an object you can touch or see within 5 meters that is no larger than 2 meters in any dimension**, a point in space within 5 meters** sheds bright light in a 1-meter radius and dim light for an additional 1 meter for the duration.

Added text in **bold**.

**Comment by itamarcu** [comment]
Counter-suggestion:  change Illuminate to be more useful:
> As an action, you can increase the amount of light emitted in a ~~1~~ **5**-meter radius within ~~5~~ **10** meters. You can increase the light level by one step (no light to dim light, or dim light to bright light).
> ...
> A creature within ~~1 meter of~~ the illuminated area must make a Fortitude saving throw.

The duration could also be changed into an hour (like Light's).  This spell is stationary so the time duration doesn't really matter at all - if you're staying in one place for an hour you can probably afford to recast the spell each time, so, might as well just avoid having players say it.

And Gloom would be updated similarly of course, reducing light in a 5m sphere.


Anyways, this way you'd have 3 light cantrips with different use cases:
- Light gives you a mobile light, concentration-free for one hour (similar to a torch), and makes it a small dot of bright light.  in combat, you're limited to a 5m distance, and out of combat you have to light and throw things (slightly costly and slow).
- Illuminate gives you a large area of increased lighting - dark to dim to bright.  its area is the biggest, but it's also static and doesn't have the bright area. the range is 10m.
- Dancing Lights gives you four points of dim light, at the farthest range (20m).  they can't create more than dim light, but they're very useful for scouting ahead in a dark cave, and also allow you to send distant signals in the night.

**Comment by mlenser** [comment]
A 5 meter sphere is far too big. That's larger than a 1 mana daylight/darkness.

**Comment by itamarcu** [comment]
Then, excuse my veering off-topic, but why not increase Daylight's range?  It's 2m radius bright and additional 2m dim (multiplied by mana cost).  A *lot* smaller than the 5e spell which was 12 square radius bright and additional 12 dim, and isn't even concentration.

**Comment by mlenser** [comment]
As I wrote in the other thread:

> 5e is not the baseline that I'm trying to match. I think the 5e version of Telepathic Bond for example is too strong.

This case is the same. A 60-foot-radius sphere of light is insanely huge.

As I've written several times: Casters being able to fully bypass challenges makes parties unbalanced and presents significant problems from a system design point of view. Casters should be able to solve challenges, but not able to fully bypass them with minimal resource expenditure. 5e is way off point here with many of their spells - in both directions. Some are far too strong and some are far too weak.

Genesys, the thematic agnostic version of SWRPG, says this about magic:
![image](https://user-images.githubusercontent.com/235857/121307020-cf981b80-c8ff-11eb-9aa0-078b15d84710.png)

As I wrote the last few times I've shared this image: I agree with their viewpoint. It'll never be to that level, but also no where near the level of casters being able to fully bypass challenges with minimal resource expenditure.

This is the system's goal. Please be mindful of it.

**Comment by mlenser** [comment]
- Dancing Lights no longer requires concentration, its radius is now a bit less than half that of a torch, and additional lights are created at higher level.
- Illuminate removed as Dancing Lights covers its niche.

**Comment by mlenser** [comment]
Dancing Lights reworked so it no longer requires concentration, its radius is now a bit less than half that of a torch, it now creates three lights instead of four, it can cause damage and make creatures vulnerable, and additional lights are created at higher level.
