### ISSUE TITLE
Disrupt (maneuver suggestion)

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#839]
Due to how concentration works, spellcasters are currently the best "counter" to spellcasters.  In addition to counterspell, antimagic shell, etc, they simply tend to have very high damage ("nova") spells - for example, [Blight](https://www.kryxrpg.com/spells/blight) at 2 mana deals 45.5 damage on average, which means a concentration save DC of 22, pretty difficult to pass.  At 3 mana and 2 actions, [Hurl Through Hell](https://www.kryxrpg.com/spells/hurl-through-hell) will deal 71.5 damage, guaranteed to end concentration on any reasonable creature.  Or, a caster can cast [Stasis](https://www.kryxrpg.com/spells/stasis) to simply stun an enemy that fails a Will saving throw, which automatically removes concentration (in addition to a strong debuff).

The best that a martial can do right now is spend 3 stamina to enhance [Disorient](https://www.kryxrpg.com/maneuvers/disorient) into "Incapacitate", though even then it only ends concentration on an enemy that both gets hit and fails Fortitude (the most common save), making it a smaller chance.

Additionally, there's the [Mage Slayer](https://www.kryxrpg.com/feats/mage-slayer) feat that gives disadvantage on the concentration saves, but even with disadvantage it's not too difficult to beat DC 10, particularly for higher Challenge monsters (a C 12 Archmage has +8 on the save, failing only on a natural 1).  And it would be DC 10 unless the martial deals more than 20 damage with an attack (unlikely).

So, this is my suggested solution:

---

# Disrupt (1 stamina, antimagic)
As an action, you can make a weapon attack in an attempt to disrupt a creature's concentration on a spell. If you hit the creature and force it to make a Will save to maintain concentration on a spell, the DC of that save is increased by your stamina die.  If you miss by 4 or less, add half the stamina die to the DC.

*Enhance*
You can increase the DC for each additional stamina die expended.

---

- I made it 1 stamina to make the wording simpler, but it could also be 2 stamina if you think tier 1 shouldn't have this.
- The expected DC at be 14.5 for 1 stamina, 19 for 2 stamina, 23.5 for 3 stamina, and probably a guaranteed concentration end for 4+ stamina (though at that point monsters have legendary resistances so it isn't really guaranteed).  This would match the effectiveness of spells at that tier - of course, you'd be spending stamina instead of mana, but you'd also be doing much less damage as the stamina isn't added to the attack's damage.
- By increasing the DC, it would usually increase it from 10, as half damage is often below that (at low-mid tiers).  This means the maneuver is equally useful for all weapons.  When you're high enough level to deal 21+ damage with your weapons, you're probably also able to add 4+ stamina dice and virtually guarantee the effect if you successfully hit.

Alternative names:  Interrupt, Brain-break, Discombobulate, Bonk

**Comment by mlenser** [comment]
I expect we're going to end up at the same end point we did on https://github.com/mlenser/kryx-rpg-issues/issues/353#issuecomment-650528758

But I'll check this later.

**Comment by itamarcu** [comment]
My goal was mainly to fix the problem at tiers 3+, where the party's spellcasters can deal 50+ damage (conc DC 25+) while the enemy spellcasters sometimes have +9 or more to their will save, meaning they always pass DC 10 (nullifying Mage Slayer).

This basic problem is a result of the basic concentration rule, with DC being half the burst damage or 10, whichever's higher.

**Comment by Marcloure** [comment]
An issue here compared to 5e is that here every caster has a high concentration save. In 5e, only the Sorcerer has proficiency in Constitution saves, and you can't increase your Con and your main stat at the same time. As we use Will for Concentration saves (which I agree with), casters naturally increase their concentration save together with their main stat.

**Comment by mlenser** [comment]
Better math:

## 1st tier
DC 11 per attack
Caster has ~+3 to Will (proficiency + average of top 2 mental abilities)

`output 2d10+3 >= 11` = ~21% chance to end concentration
multiple attacks: `1 - (0.79) ^ 2`

## 1st tier
- Single attack: ~21% chance to end concentration
- Two attacks (Monk <3, TWF, brawler, or maneuver usage): ~37.5% chance to end concentration
- Three attacks (Monk >3, or TWF/brawler+maneuver): ~50% chance to end concentration
- Four attacks (Monk >3+maneuver):  ~61% chance to end concentration

## 2nd tier
DC 11 per attack
Caster has ~+5 to Will (proficiency + average of top 2 mental abilities)

`output 2d10+5 >= 11` = ~10% chance to end concentration

- Two attacks: ~19% chance to end concentration
- Three attacks:  ~27% chance to end concentration
- Four attacks:  ~34% chance to end concentration
- Five attacks:  ~41% chance to end concentration

### Mage Slayer
`output [lowest 2 of 3d10]+5 >= 11` = ~23.3% chance to end concentration

- Two attacks: ~41% chance to end concentration
- Three attacks:  ~55% chance to end concentration
- Four attacks:  ~65.5% chance to end concentration
- Five attacks:  ~73.5% chance to end concentration

## 3rd tier

### Mage Slayer
DC 11 per attack
Caster has ~+7 to Will (proficiency + average of top 2 mental abilities)

`output [lowest 2 of 3d10]+7 >= 11` = ~7.9% chance to end concentration

- Two attacks: ~15% chance to end concentration
- Three attacks:  ~22% chance to end concentration
- Four attacks:  ~28% chance to end concentration
- Five attacks:  ~34% chance to end concentration

_____________

That should get us a better picture of the math.

**Comment by Marcloure** [comment]
> DC 11 per attack

This doesn't consider the attacker is using maneuvers then, right?

**Comment by mlenser** [comment]
## 5th tier

### Mage Slayer
Caster has ~+10 to Will (proficiency + average of top 2 mental abilities)

Let's assume the target is a Mage who has 20 Defense from mage armor. A martial character would have ~+11 to hit, so around ~72% chance to hit.

Ranger with TWF makes 3 attacks. 4.5[w]+5[stat]+7[weak spot] = 16.5 base

This ranger can choose to use:
- 3 stamina on each attack to disorient. The mage likely doesn't have high fortitude 0.72x0.65 = ~46% chance for each hit to end concentration. `1 - (0.54) ^ 3` = ~84% chance to end concentration if all 3 attacks use 3 stamina to disrupt. If all 3 of those fail, the mage still has to make concentration saves for each which would average at DC 11 (auto success), but would peak at 8+5+12+8 = 33 = DC 16. Basically between DC 11 and 16, with ~25% of attacks being in the higher range.
- 5 stamina on any other manuever. We're then looking at 16.5+22.5 = 39 average, so DC ~19.5 (20) which has ~62% chance to end concentration if it hits. The damage can peak much much higher, causing a much higher DC.

__________

Martials are expected to use stamina quite freely as they have quite a lot. Based on the above, I expect tier 3-5 to be totally fine.

_____________

Disrupt (using 1 stamina) tier 2 attacks would cause the chance to lose concentration when hit to go from ~23.3% to ~62.2%.

Based on the above options and this extremely lopsided outcome, this is idea is totally beyond expected levels.
