### ISSUE TITLE
Blood Bond augment saving throw

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#840]
[Blood Bond](https://www.kryxrpg.com/spells/blood-bond) has:
> As two actions, you connect your life to that of a willing creature within 10 meters. While the target is within 10 meters of you, you have resistance to all damage. Also, each time you take damage, it takes the same amount of damage.
> ...
> Each time the target takes damage, it makes a new Fortitude saving throw against the spell. If the saving throw succeeds, the spell ends.

I think this would be better as:

> Each time the target takes damage **through this connection**, it makes a new Fortitude saving throw against the spell. If the saving throw succeeds, the spell ends.

Otherwise, the victim can get plenty of extra saving throws, before you even make use of the spell, simply by being in combat.

**Comment by mlenser** [comment]
Blood Bond and Share Pain augments only allow a new saving throw if the target takes damage from the spell.
