### ISSUE TITLE
Minor water/ice utility cantrip improvements

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#844]
[Form Ice](https://www.kryxrpg.com/spells/form-ice) - it should have an option to freeze water/liquids in a 1 meter cube.  Currently it can make items out of frozen ice/water, but nothing states it can actually freeze a block, e.g. to make an ice bridge across a shallow pool.

[Shape Water](https://www.kryxrpg.com/spells/shape-water) *can* freeze water, so I think the same paragraph could just be added to Form Ice as an option.

Additionally, it would be nice if Shape Water allowed characters not only to freeze water but also to defrost it, i.e. to melt ice back into water.  In AtlA, for example, there's plenty of examples where Katara turns ice back into water, but currently none of the ice or water cantrips are able to do this.

**Comment by mlenser** [comment]
- Shape Water can no longer freeze water. [#844](https://github.com/mlenser/kryx-rpg-issues/issues/844)
- Form Ice can freeze water and melt ice and snow. [#844](https://github.com/mlenser/kryx-rpg-issues/issues/844)
