### ISSUE TITLE
Split Hamstring augment

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#846]
https://www.kryxrpg.com/maneuvers/hamstring

> You can increase the damage for each additional stamina die expended and the slowed level by 1 for every two additional stamina die expended.

It could have an option to increase the damage and another to increase the slow, instead of increase both every 2 Stamina

**Comment by mlenser** [comment]
They are meant to be tied together. The damage increases for every dice while the effect increases every other.
