### ISSUE TITLE
Problems in accessing Dragon, Elemental and Blink Dog Companion forms

### ISSUE THREAD

**Issue by PerfectGameReference** [mlenser/kryx-rpg-issues#847]
Everytime I try to acces the Companion forms of those three types the page just turns white and nothing loads

Link:
https://www.kryxrpg.com/character/companion

1. Go to https://www.kryxrpg.com/character/companion
2. Click on any option of the Dragon, Elemental or Fey Dog companion form
2. See error

**Comment by mlenser** [comment]
Thanks for the issue!

It should be fixed in a few minutes
