### ISSUE TITLE
Several spells affect ability checks too broadly

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#851]
Glibness, Ossified, Cloak of Flies - should apply only to social charisma checks

Reliable Talent - maybe should only apply to certain skills?  I don't think spellcasting is really a talent, it seems like this is intended more for physical and roguish skills

Call to Mind - should be limited to cases when you're making checks about knowledge

Fortunes of Fate - High Priestess - affects all wisdom ability checks, should be changed maybe somehow

There are possibly other examples of things that affect mental ability checks in species, classes, concoctions, or gear.

**Comment by mlenser** [comment]
- **Classes**
  - Reliable talent cannot be used on magic skills. [#851](https://github.com/mlenser/kryx-rpg-issues/issues/851)
- **Themes**
  - Cloak of Flies, Contagion, Glibness, Ossified, and Skunk Odor now only apply to social skills. [#851](https://github.com/mlenser/kryx-rpg-issues/issues/851)
  - Bestial Transformation and Enlarge/Reduce adjusted to impact skills directly. [#851](https://github.com/mlenser/kryx-rpg-issues/issues/851)
  - Call to Mind adjusted to be usable on specific usages of skills. [#851](https://github.com/mlenser/kryx-rpg-issues/issues/851)
  - Oak Body adjusted to use Brawn directly. [#851](https://github.com/mlenser/kryx-rpg-issues/issues/851)

Opened https://github.com/mlenser/kryx-rpg-issues/issues/853 and https://github.com/mlenser/kryx-rpg-issues/issues/854 to handle two additional cases.
