### ISSUE TITLE
Low spellcasting ability should be more detrimental

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#852]
There is a problem that one of my previous goals of limiting spellcasting ability can enable keeping it quite low at very little cost. Keeping it low is and should be an option, but there should always be a cost.
Some options that could be used (likely together):

- mana used on a spell is limited by your spellcasting ability and 2+ mana requires proficiency in the skill. Same for alchemy.
- add spellcasting ability to lots of spells. Same for alchemy.
- add spellcasting ability elsewhere like mana or spells known

It shouldn't be debilitating to have a low spellcasting ability, but it should make you less effective.

**Comment by itamarcu** [comment]
> add spellcasting ability to lots of spells. Same for alchemy.

This is the only one I don't like.  I liked the magic missiles change from 3x(1d4+1) to 5x(1d4), and I liked the Cure Wounds / Heal change from 1d8+ability to 3d8.  I think the fact that weapon attacks add ability while spells don't add them is a neat mechanical distinction that is worthwhile to keep.  I think the purity of damage only through dice is elegant.  It also keeps scaling perfect:  a spell with 2 mana will literally be twice as effective, because you roll twice as many dice.  And thematically, it's easy to say that spell strength only depends on the mana spent on the spell while your spellcasting ability affects how easy it is for you to control and direct the spell - aiming it at enemies, making it harder to resist, making it harder to break (if someone counterspells/dispels it).

The other changes make sense, though.  In particular, adding spellcasting ability to the number of spells known - maybe this can outright replace "Starting Spells".

**Comment by mlenser** [comment]
> And thematically, it's easy to say that spell strength only depends on the mana spent on the spell while your spellcasting ability affects how easy it is for you to control and direct the spell - aiming it at enemies, making it harder to resist, making it harder to break (if someone counterspells/dispels it).

Chance to hit is only one aspect of the "strength" of the spell and is more about accuracy. Damage/healing is the true "strength" of the spell.
Chance to hit also has no impact on spells that heal or shield, which I would say is problematic.

**Comment by mlenser** [comment]
- **Rules**
  - **Concoctions, maneuvers, and spells**
    - A character cannot expend 2 or more catalysts on a concoction unless they are proficient with the alchemy skill. A character also cannot expend more catalysts than their alchemy ability. [#852](https://github.com/mlenser/kryx-rpg-issues/issues/852)
    - A character cannot expend 2 or more stamina dice on a maneuver unless they are proficient with the weapon they use to execute it. A character also cannot expend more stamina dice than their Strength (or Dexterity if their weapon has the finesse property). [#852](https://github.com/mlenser/kryx-rpg-issues/issues/852)
    - A character cannot expend 2 or more mana or psi on a spell unless they are proficient with the spellcasting skill associated with that spell’s power source. A character also cannot expend more mana than their spellcasting ability. [#852](https://github.com/mlenser/kryx-rpg-issues/issues/852)

**Comment by mlenser** [comment]
One of the benefits of adding the spellcasting ability/alchemical ability to a concoction or spell is that the minimum and maximum possible damage/healing/other effect is more bounded. That's good for the player and also good for the system.

Heal, if changed to use spellcasting ability, would heal for 2d8+spellcasting (+3d8 each tier) which:
- At 3rd level is 5–19 instead of 3–24. Augmented to 2 mana at 5th level is 8–43 instead of 6–48.
- At 7th level is 6–20 instead of 3–24. Augmented to 2 mana is 9–44 instead of 6–48.
- At 11th level is 7–21 instead of 3–24. Augmented to 2 mana is 10–45 instead of 6–48.

It's more impactful at 1 mana, but still a nice little boost so spells are less likely to completely suck (all 1s).

**Comment by mlenser** [comment]
> adding spellcasting ability to the number of spells known - maybe this can outright replace "Starting Spells".

This wouldn't work with the current values or with classes that have alchemy/spellcasting, alchemy/maneuvers, or maneuvers/spellcasting. Currently:

- alchemy/spellcasting start with 2 spells and 2 concoctions
- alchemy/maneuvers start with 2 concoctions and 2 maneuvers
- maneuvers/spells start with 2 spells and 2 maneuvers
- alchemy start with 3 concoctions
- maneuvers start with 3 maneuvers
- spellcasting starts with 3 spells

**Comment by itamarcu** [comment]
> A character cannot expend 2 or more mana...

I think nicer wording would be "A character cannot expend more than 1 mana...." for these.

Also, it looks like currently these rules are written right at the start of the resource section, which looks a little bit confusing.  I think it should be moved further down, as a new paragraph under the "Mana limit" (etc) section, because these rules are less important than the basic limit rules and aren't necessary for new players to learn immediately.

**Comment by itamarcu** [comment]
Re: adding ability modifier to spells - I don't think I can convince you, but I'll list a few more reasons not to do it:

**Spell value (not counting chance to hit) now depends on the user's modifier and level, not just mana.**  This means that casting 1-mana spells multiple times will either be more or less efficient than casting a single high-mana spell.  

For example, on 9th level, Heal with 3×1 mana is 3*(2d8+3) = 36, vs once at 3 mana for 8d8+3 = 39.  But at level 17, the comparison becomes 42 vs 41.  Players who care about optimizing healing outside combat will now have to do the math to figure out which way is more efficient, while currently they can safely say it's always 3d8 per mana.

**Adds design constraints**.  If all damage/health spells were required to use spellcasting modifier, spell design would be more difficult.  For example, spells like Magic Missiles or Arc Lightning will need to be redesigned in a way that still lets you split their damage around.

**Doesn't solve the problem for most spells**.  A huge number of spells just don't include numbers that would make sense to alter based on spellcasting ability.  Floating Disk, Force Shield, Mage Armor, Protection from Fire, Rain, Silence, Detect Magic, Flaming Weapon..... and so on.  I think the costs involved with this change (including time and effort to go through all spells and all exceptions) aren't worth it if the main goal isn't achieved.  And I think that the new restrictions you added, along the existing rules, are enough reasons for people to avoid having low spellcasting.  Except for:

**People who want a low spellcasting ability will not really be affected.**  If I'm playing a martial/gish with a low spellcasting ability I'll simply choose spells that don't scale with it (like all the spells I mentioned above), or I might just not care about the added scaling (e.g. the difference between healing 10 Health and healing 12 Health is minor for me, so I'd still rather put the ASI in something else).


Regarding values being more bounded - yes, that's a nice minor benefit, but I think it only applies to a small number of spells, and I don't think it'll apply to the spells that matter.  The difference between healing 5 hp and healing 7 hp is pretty small, when both are unlikely.  People are more frustrated by rolling low on spells like Twist Fate, or with d20 rolls in general (2d10 helps with this).

On the other hand - this could really help with **cantrips**, which are all around 1d4 to 1d10 damage, so they very often roll negligible damage to enemies.  Those are spells that could really benefit from bounded results.

**Comment by Marcloure** [comment]
I agree with itamarcu here. Adding spellcasting ability to heals and damage won't impact spells like blur, darkness, walls, teleport, etc. Having a lower spellcasting ability already causes a lower DC, so damage spells are automatically balanced (with exception of Force spells).

**Comment by mlenser** [comment]
Spellcasting will be added to Heal, Force spells, and other spells that dont have an attack or save at minimum.

**Comment by mlenser** [comment]
> I don't think I can convince you

You haven't proposed a solution to the problem.

If you have a solution, feel free to suggest it.

**Comment by mlenser** [comment]
Currently, my plan is to add spellcasting ability to Heal, Force spells, and other spells that dont have an attack or save at minimum.

Maybe there is another way to solve the problem, though I think it's quite a good solution.

**Comment by mlenser** [comment]
> This means that casting 1-mana spells multiple times will either be more or less efficient than casting a single high-mana spell.

No, it doesn't. Spellcasting ability will range from 2-5, averaging ~3.5. It's equivalent to ~1d6. It won't have any impact on scaling beyond making 1 mana spells ever so slighlty above the damage value at higher tiers (but so would 2 and 3 mana spells).

At 7th level the main ability is 4. Two 1 mana spells = 2x (2d8+4) = 26. One 2 mana spell is 5d8+4 = 26.5.

> If all damage/health spells were required to use spellcasting modifier
> Doesn't solve the problem for most spells.

It's not all or nothing. It can be added to as many places as possible and others can be left as is.

> People who want a low spellcasting ability will not really be affected. If I'm playing a martial/gish with a low spellcasting ability I'll simply choose spells that don't scale with it

Sure, and that's ok. But having a low spellcasting then still has a cost of only choosing utility spells that don't have any numeric values, basically.

> Regarding values being more bounded - yes, that's a nice minor benefit, but I think it only applies to a small number of spells

It would apply to all spells that add spellcasting ability.

> On the other hand - this could really help with cantrips

It likely would not apply to cantrips as those are generally using ~1d4-1d10 and spellcasting ability itself is worth ~1d6.

**Comment by mlenser** [comment]
Force Hail, Force Spear, Force Sword, Glyph of Warding, Homing Motes, and Magic Missiles adjusted to use spellcasting ability.

I'll wait for any feedback before expanding to the heals.

**Comment by mlenser** [comment]
- All heal, shield, and temporary health spells now add your spellcasting ability. [#852](https://github.com/mlenser/kryx-rpg-issues/issues/852)
- All heal concoctions now add your alchemical ability. [#852](https://github.com/mlenser/kryx-rpg-issues/issues/852)

**Comment by Paulorpribeiro** [comment]
There are some other spells (gale strike, rising phoenix, telekinetic charge, maybe others) that deal damage without a spell attack or save, but instead on a successfull attack with your weapon. They are very good damage spells for low spellcasting-stat gishes as well. Maybe they could have one of their die changed to spellcasting ability too?

**Comment by mlenser** [comment]
- Acolyte Paladin’s Smite the Faithless now includes your spellcasting ability.
- Dimensional Strike, Gale Strike, Path to the Grave, Rising Phoenix, Seeking Strike, Shadow Jaunt, Telekinetic Charge, Teleport, and Toppling Punch now include your spellcasting ability.

**Comment by mlenser** [comment]
I think the changes are sufficient. Now pretty much all numeric-based spells (other than shield-style) do one of the following:

- An attack roll (based on spellcasting)
- A saving throw (based on spellcasting)
- Spellcasting ability added to the effect

If I've missed any other categories, please let me know.
