### ISSUE TITLE
Increase Hypoxia Bomb cost

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#859]
https://www.kryxrpg.com/concoctions/hypoxia-bomb

Hypoxia Bomb makes the target unable to speak, which means they become incapable of casting many spells. I believe its cost should be increased, specially considering that it's an AOE, unlike #857 and #858

**Comment by mlenser** [comment]
Hypoxia, Hypoxia Bomb, and Steal Breath adjusted to the new strength of silenced.
