### ISSUE TITLE
Command is far too strong for 1 mana

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#860]
It's 1 mana and 1 action to effectively prevent a whole turn if they fail a Will saving throw. That's the same value as incapacitated, but also has other effects like prone.

**Comment by mlenser** [comment]
https://2e.aonprd.com/Spells.aspx?ID=45 is a good reference.

> Command
> 2 actions
> Range 30 feet; Targets 1 creature
> Saving Throw Will; Duration until the end of the target's next turn
> You shout a command that's hard to ignore. You can command the target to approach you, run away (as if it had the fleeing condition), release what it's holding, drop prone, or stand in place. It can't Delay or take any reactions until it has obeyed your command. The effects depend on the target's Will save.
> 
> Success The creature is unaffected.
> Failure For the first action on its next turn, the creature must use a single action to do as you command.
> Critical Failure The target must use all its actions on its next turn to obey your command.

**Comment by Marcloure** [comment]
I don't know how likely "failure" and "critical failure" happen in PF2, but expending a single action of the creature seems ok for a single action of yours. Depending on the circunstances, that means the target has to expend 1 action running away and another coming back, but it can also take another action instead (like a ranged attack or a spring attack maneuver).

**Comment by mlenser** [comment]
> expending a single action of the creature seems ok

It's your two actions for their one action.

**Comment by mlenser** [comment]
- Command removed from the Charm theme.
- Command reworked to have some effects happen immediately and some happen on the creature’s turn. [#860](https://github.com/mlenser/kryx-rpg-issues/issues/860)
