### ISSUE TITLE
Add Mercy to Life

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#862]
https://www.kryxrpg.com/spells/mercy

The cantrip is only in Deceit currently, but I think it fits Life as an analgesic cantrip.

**Comment by mlenser** [comment]
It's an illusion.

**Comment by mlenser** [comment]
Illusions belong only in the Deceit theme.

If you want to make a variant that lives in the Life theme, one could be added. Not sure how it'd be flavored.

**Comment by Marcloure** [comment]
Something like:

> As an action, you provide succor to an ailing creature you can touch, relieving its suffering for the duration.
> 
> The creature must make a Fortitude (Will?) saving throw. On a failure, it no longer feels any physical pain or discomfort.

It's an anesthetic and soothing effect, so I feel like this fits Life.

**Comment by mlenser** [comment]
anesthetic would be poison.

**Comment by Marcloure** [comment]
I mean a magical anesthetic, not a quimical/biological one

**Comment by mlenser** [comment]
Anesthetics as we humans know them come from plants or animals.

This needs proper flavor. If you want a Life version then please create one with full flavor.

**Comment by Marcloure** [comment]
What about:

> ### Soothe
> _5 minutes_
> 
> As an action, you relieve the suffering of an willing creature you can touch, soothing its pain for the duration. The creature no longer feels any physical pain or discomfort.

As it is not an illusion, it can't be perceived as false, but you also can't soothe someone unwillingly.

**Comment by mlenser** [comment]
Soothe added to the Life theme.
