### ISSUE TITLE
Sword Burst should deal slashing/piercing damage instead of force damage

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#865]
[Sword Burst](https://www.kryxrpg.com/spells/sword-burst) - it creates swords and it's in the Forge domain, where Cloud of Daggers and Blade Barrier deal piercing and slashing.  This spell should do the same, instead of being Force.

**Comment by mlenser** [comment]
Sword Burst deals piercing or slashing damage instead of force damage.
