### ISSUE TITLE
Some Spell Strike suggestions

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#866]
For spells similar to https://discord.com/channels/701706060440010753/709048873351381042/857285681960452097:

#### Forge - Long Blade
> As an action, you momentarily enlarge and sharpen your weapon as you make a weapon attack. Your weapon's reach or range is doubled for this attack. On a hit, add 2d8 + your spellcasting ability to the attack’s damage roll.

#### Deceit - Triplicate Attack
> As an action, you can make a weapon attack with advantage as you shape two illusory duplicates of yourself that attack simultaneously from different directions. On a hit, add 2d6 + your spellcasting ability to the attack’s damage roll.

(reskin of Dimensional Strike)

#### Earth - Ground Launch 
> As an action, a short pillar rises from the ground and propels you away, moving you up to 5 meters in any direction. If you land next to a creature, you can make a melee weapon attack against it. On a hit, add 2d8 + your spellcasting ability bludgeoning damage to the attack’s damage roll. 

(Augments could allow launching yourself further distances)

#### Time - Rapid Rush
> As an action, you accelerate your body, moving faster than the eye can track. You can move up to 20 meters without provoking opportunity attacks. During your movement, you can make a melee weapon attack against a creature. On a hit, add 1d4 + your spellcasting ability to the attack’s damage roll.

(this is similar to Teleport, but worse because you're still limited by obstacles, pits, and the floor.  to compensate, you can move 
more when you attack, though I reduced the damage)

**Comment by mlenser** [comment]
There doesn't need to be one for each theme, but:

Acid: Corrosive Strike for acid and acid next round
Air: Zephyr Strike :white_check_mark: 
Antimagic: ?
Beast: would be cool to have some kind of primal savagery attack along with normal attacks
Blood: Blooddrinking strike: damage and heal
Chaos: ?
Charm: Compelled Duel :white_check_mark: 
Courage: Can make a spell version of Commander's strike

**Comment by DalenWBrauner** [comment]
Random Ideas:

**Chaos - Wild Strike**
> Attack an enemy, dealing a random damage type with such an unpredictable force that you're propelled 10ft in a random direction (and possibly in the air, to avoid crashing into the target)

**Poison -** Wasn't there once an "inject venom" maneuver? I think a similar flavor could work here. Perhaps this venom slows or the like.

**Ice - Frost Ramp** e.g. similar to Shem's suggestion for Earth, or **Chilling Blow** for a simple, substantial-slow-applying attack.

**Sand - Streaming Strike**
> Sand courses out from your feet, propelling you forward for additional movement and allowing you to ignore difficult terrain. Adds additional damage, either of the same type as the weapon through momentum or slashing from the tearing of sand.

**Gravity - Weighted Strike** to simply increase the heft of the blow, or something that allows you to leap high into the air and come down to crash upon an opponent.

**Spirit - Ancestral Assault**
> Spirits guide your body to a target, allowing you to ignore difficult terrain and impose disadvantage on opportunity attacks until the end of your turn. Your strike, too, is guided by their hands, dealing extra damage of the same type.

**Fate - Guided Gait**
> Fate or fortune guide you to your target... [same as Ancestral Assault]

I like something based on Hydrualic Push for **Water**, though it could also easily have a reflavored Rise of the Pheonix, Wild Strike or Streaming Strike.
