### ISSUE TITLE
Some Power Sources link to their skill

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#867]
Each theme's page has a list of power sources it belongs to, but only some of those power sources link to their related skill. See the [Charm theme](https://www.kryxrpg.com/themes/charm) for an easy example.

Skimming through the themes, it appears that:
* Arcane does not
* Divine does not
* Occult does
* Primal does
* Psionic does not

I wish you a trillion blessings, oh debugger of regex.

**Comment by mlenser** [comment]
It is because the skill is named the same or not

- Arcane = Arcana
- Divine = Divinity
- Occult ===
- Primal ===
- Psionic = Psionics

**Comment by mlenser** [comment]
will be fixed on next build
