### ISSUE TITLE
Wall of Terror needs an effect duration

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#868]
https://www.kryxrpg.com/spells/wall-of-terror

> On a failed save, a creature can’t overcome its terror and can’t move through the wall.

It can't move through the wall on this turn or until the spell end?

**Comment by mlenser** [comment]
Wall of Terror prevents moving through for the duration.

**Comment by Marcloure** [comment]
There is another thing. The spell should mention that the save is against fear and that creatures immune to being frightened is immune to the spell.

**Comment by mlenser** [comment]
Will be fixed on next push
