### ISSUE TITLE
Review all burning effects

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#869]
A save happens automatically at the end of the turn to reduce the burning level. Update the sheet and adjust values.

**Comment by Marcloure** [comment]
I know the values hadn't been adjusted yet, but it's always good to compare **fireball** with **vitrolic sphere**. Current Fireball deals 5d6 + burning 2, so it takes 3 turns to deal around the same damage vitrolic sphere deals over 2 turns, if the burning is only reduced once (5d6+3d6 vs. 4d8+2d8).

**Comment by mlenser** [comment]
See the refreshed burning condition. It's not just once.

Also see the spreadsheet for fireball's value.

**Comment by Marcloure** [comment]
I know it's not just once. Fireball deals 5d6 + burning 2. It takes 2 of the target's turns to deal 7d6, that is, if the target pass on one Fort save and fails the second. If the creature pass on both saves, it deals only 6d6.

Vitriolic Sphere deals 4d8+2d8, so it deals the same amount of damage in less turns.

Also, consider that burning isn't applied in a successful save against the spell, so the spell's damage is quite low on a successful save.

I think burning is valued too high on your spreadsheet, if what I said isn't somehow wrong.

**Comment by mlenser** [comment]
> the spell's damage is quite low on a successful save.

According to the sheet fireball's damage is nearly 10% above the guideline at 2 mana.

As I wrote above, I need to re-evaluate burning. However Vitriolic Sphere's secondary damage is not full value - the spreadsheet covers that as well.

**Comment by Marcloure** [comment]
Hm, ok I considered it would fail first and succeed later, it could deal 7d6 on the first turn if the creature fails then. That is fair. However, I still think that 0 burning on a successful save kinds drops the spell's damage by a considerable amount, when compared to other soe spells, no?

**Comment by mlenser** [comment]
> I still think that 0 burning on a successful save kinds drops the spell's damage by a considerable amount, when compared to other soe spells, no?

Not according to the sheet, no. This is all calculated. In this case the initial damage or secondary damage is increased to compensate.

**Comment by mlenser** [comment]
Sanity check:

Fireball does 6d6 and burns for 2, or half damage on a successful save:
`0.576*21 + 0.424*10.5 + 0.576*burning 2` = ~`16.5 damage + 0.576*7`= ~`16.5 damage and ~4 damage next turn`

Horrid Wilting does 4d12, or half damage on a successful save:
`0.52*26 + 0.48*13` = `~19.8 damage`.

Tradeoff is `3.3` less damage this turn for ~4 damage at the end of their turn and possibly more damage on later turns or action usages to end the burning if it accumulates with other burning.

Seems correct.

**Comment by mlenser** [comment]
Bleeding and Burning completely recalculated on the sheet which results in all concoctions, maneuvers, and spells that use those conditions to be recalculated.
