### ISSUE TITLE
Consider creating a Mage archetype that studies alchemy

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#871]
Based on the discussion on Discord, maybe there is a space for a Mage that studies both magic and alchemy. Even in D&D itself it is usual that wizards learn how to brew potions and often studies science too. Sure, there aren't Alchemists in core D&D, but I think there is a place of a class that does a bit of both here.

As a trade-off to use concoctions, this Mage would likely lose its Arcane Inovation (metamagic) feature and maybe Arcane Secrets (spells from any power source).

**Comment by mlenser** [comment]
> As a trade-off to use concoctions, this Mage would likely lose its Arcane Inovation (metamagic) feature and maybe Arcane Secrets (spells from any power source).

There doesn't need to be a tradeoff. Otherwise you're saying that the spells occultist is a subpar choice which should be fixed.

By choosing to be half alchemy half spells, a character is giving up a lot of power for some versatility. That tradeoff is fair in and of itself.

**Comment by Marcloure** [comment]
> There doesn't need to be a tradeoff. Otherwise you're saying that the spells occultist is a subpar choice which should be fixed.
> 
> By choosing to be half alchemy half spells, a character is giving up a lot of power for some versatility. That tradeoff is fair in and of itself.

I don't believe that is true. Alchemy has some very strong features, but what is of interest for the discussion: it doesn't require concentration and it doesn't have a power source. Alchemy also has some weaknesses, but what is interesting to us is that it is more limited in the variety of effects (better than maneuvers, worse than spells).

With access to both concoctions and spells, a character can:
- use alchemy to create potions that usually require concentration, instead of using the spell (any weapon oil, Danger Sense Potion, Invisibility Potion, etc.)
- use a concentration spell on top of an unstable concotion
- use spells to teleport, create walls, and do a lot of things that alchemy can't do
- since all alchemy is under a single power source, you gain access to effects that would be outside your reach if you were spell-only. To list a few: healing, invisibility, divination, metabolism, or beast concoctions, etc.
- if you are facing an enemy with Magic Resistance or inside an antimagic field, alchemy can back you up still

> character is giving up a lot of power for some versatility
A character isn't giving up powe: it doesn't have a slower progression, fewer resources, or anything like that. Maybe it can't use as many spells in a row, but it can save some mana by creating concotions instead. Regarding resources and damage, I believe it is a neutral trade-off.

**Comment by mlenser** [comment]
Please move your post to a new discussion about alchemy combined with spells. Alchemy combined with spells already exists in the Occultist (Witch) without any tradeoffs so by your logic the pure spells Witch is a bad choice and should be addressed. (Which I don't agree with, but it's a different topic than this topic).

**Comment by mlenser** [comment]
Regarding a Mage being able to study alchemy: I need a thematic basis to understand how that should work. Cases of characters in fantasy that study spells and alchemy and how those two combine. That then helps inform me for how I should structure the class.

The only two that I know of are Harry Potter and the Witcher.

**Comment by mlenser** [comment]
This needs more info so it can be worked on. Feel free to reopen when it is provided.

**Comment by Marcloure** [comment]
It's indeed a bit hard to find other references that aren't from D&D itself. Magic the Gathering has a bunch of alchemical and technological mages, but I guess that is more of a magical inventor.
