### ISSUE TITLE
Having access to concoctions, maneuvers, and spells may be more powerful than only having access to one type

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#872]
Quoting from Marcloure's post in #871 - 

Alchemy has some very strong features, but what is of interest for the discussion: it doesn't require concentration and it doesn't have a power source. Alchemy also has some weaknesses, but what is interesting to us is that it is more limited in the variety of effects (better than maneuvers, worse than spells).

With access to both concoctions and spells, a character can:

- use alchemy to create potions that usually require concentration, instead of using the spell (any weapon oil, Danger Sense Potion, Invisibility Potion, etc.)
- use a concentration spell on top of an unstable concotion
- use spells to teleport, create walls, and do a lot of things that alchemy can't do
- since all alchemy is under a single power source, you gain access to effects that would be outside your reach if you were spell-only. To list a few: healing, invisibility, divination, metabolism, or beast concoctions, etc.
- if you are facing an enemy with Magic Resistance or inside an antimagic field, alchemy can back you up still
character is giving up a lot of power for some versatility

A character isn't giving up power: it doesn't have a slower progression, fewer resources, or anything like that. Maybe it can't use as many spells in a row, but it can save some mana by creating concotions instead. Regarding resources and damage, I believe it is a neutral trade-off.

**Comment by itamarcu** [comment]
I think a lot of that is true.  We can list a lot of benefits from having 50% concoctions and 50% mana, but the drawbacks are minor:  you will sometimes be slower if you're trying to buff people during combat (during rare situations when you want to create and then give concoctions), and you'd have split resources you won't be able to use a huge amount of mana in a single fight (which seems to me like a situation you'd usually have time to prep concoctions for, anyways).

**Comment by mlenser** [comment]
This should be viewed holistically. Concoctions, maneuvers, and spells all bring different things to the table. If combining them is powerful then that needs to be addressed at all levels, not just spells and concoctions, but also spells and maneuvers.

I can write up a complete comparison of each later.

But either way, features will not be lost to "compensate" for more powerful combinations. It would just be less resources.

**Comment by itamarcu** [comment]
I don't think maneuvers are relevant here because they come with actual big drawbacks:
- mana limit increases more slowly (1---2---3 instead of 1-2-3-4-5)
- character has to invest in more ability scores
- Existing gish characters have less known spells/maneuvers/themes (they get +1 per level, while full casters get +2 per level)

**Comment by mlenser** [comment]
Maneuvers are relevant. They have advantages and disadvantages just like concoctions and spells. Being able to mix and match spells which are more powerful, but used less often with maneuvers which are less powerful, but are used very often could be more powerful than either.
That's the whole argument as I understand it: combining these options can be more powerful than the sum of their parts. If that's the case, then it applies to all 3 and options like maneuvers/spells should have a drawback compared to just maneuvers or just spells.

**Comment by Marcloure** [comment]
Think maneuvers+spells are a lot less of a problem than concotions+spells. The reason is that concoctions can do what spells do, but almost no maneuver does what spells do. So, when you lose spells to gain concoctions, you lose less than when trading spells for maneuvers. Does that make sense?

**Comment by mlenser** [comment]
Maneuvers are just as problematic. Parry for example can be used to add 2 Defense whereas spells can be used to add 2.5 Defense. Maneuvers can be used 3x as much as spells.

If we're going down this road, then we're making a proper journey. Only looking at one aspect fails to view this issue from a holistic perspective.

Currently, half/half characters get the number of resources rounded up. So at 20:
- 45 stamina
- 15 mana
- 23 stamina and 8 mana (equivalent to 24 stamina for a total of ~47 stamina equivalent)

So first step would be to not round up like that, but not have 0 at the lower tiers. Perhaps mixed resources should end up with ~41 at level 20 (~91% of pure resources).

**Comment by Marcloure** [comment]
> Parry for example can be used to add 2 Defense whereas spells can be used to add 2.5 Defense.

Just a note, parry is against 1 attack, shield spells protect against every attack until your next turn. I get your point though.

**Comment by mlenser** [comment]
- **Classes**
  - When regaining catalysts, stamina dice, mana, and psi on a short rest characters no longer round up, but instead use the standard round down rules. [#872](https://github.com/mlenser/kryx-rpg-issues/issues/872)
- **Creatures**
  - When regaining catalysts, stamina dice, mana, and psi on a short rest creatures no longer round up, but instead use the standard round down rules. [#872](https://github.com/mlenser/kryx-rpg-issues/issues/872)

**Comment by mlenser** [comment]
- **Classes**
  - Characters with stamina dice receive a bit less now. This aligns with half casters which I think fell out of alignment after I adjusted the strength of spells that cost 2 mana or more. [#872](https://github.com/mlenser/kryx-rpg-issues/issues/872)
- **Creatures**
  - Creatures with stamina dice receive a bit less now. This aligns with half casters which I think fell out of alignment after I adjusted the strength of spells that cost 2 mana or more. [#872](https://github.com/mlenser/kryx-rpg-issues/issues/872)

Based on the math on the [Mana calculation sheet](https://docs.google.com/spreadsheets/d/1VVduALSLGnbAlxJaFncqAxVMM_jun3eXhZeLScGOSvc/edit#gid=386534955):
![image](https://user-images.githubusercontent.com/235857/125835454-bad38ea1-9f68-46c4-bf9c-783fc2e35500.png)


Martials do ~10% more damage than a half caster does which is good as half casters have more versatility.
Half-half characters do ~2% more damage than a half caster and ~8% less damage than a martial. This seems good.

**Comment by mlenser** [comment]
@itamarcu I solved one of the core math issues that I had in relation to this issue.

Looking back at the original issue, however, it does not address what you may think may be an issue. My view is that there are tradeoffs when you choose half stamina, half mana vs mana or stamina or when you choose half concoctions half spells vs spells.
If you think there is still an issue we can continue looking at the overall picture.

**Comment by itamarcu** [comment]
> When regaining catalysts, stamina dice, mana, and psi on a short rest creatures no longer round up, but instead use the standard round down rules. 

Maybe add "(minimum 1)" to this?  Nearly all creatures have 2+ mana/stamina, but the half-and-half gishes only have 1 mana on levels 1-3 and 1 stamina on level 1.  This means that in very low-level parties some players will be fine with short rests while others will require long rests to regain their primary resources.  I know this is an edge case, but I think it'll hurt gameplay for 1st to 3rd level players.

**Comment by mlenser** [comment]
It is intended that there is no minimum. So half/half would not regain mana on a short rest. They would still regain stamina dice, however.
Adding a minimum would make half/half significantly stronger than a half caster or a martial at those levels.

**Comment by mlenser** [comment]
Reopening this as I reverted the change due to the ratio being off.

**Comment by mlenser** [comment]
Changed the ratio to 1:2.
![image](https://user-images.githubusercontent.com/235857/125977469-f3302d80-9d55-4640-9b07-8649447dcaa4.png)
