### ISSUE TITLE
Dimensional Anchor

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#873]
A spell that prevents teleportation and planar travel, just like in 3.5e and [PF2e](https://2e.aonprd.com/Spells.aspx?ID=70).

# Dimensional Anchor
## 2 mana, Planes+Antimagic
*1 minute/mana or psi*
As two actions, you attempt to interfere with the ability to teleport and travel between dimensions of a creature you can touch or see within 20 meters. The creature is dimensionally anchored for the duration, and is hindered whenever it attempts to teleport, move through a portal, or move to a different plane.
Whenever the creature makes such an attempt, it makes a Will saving throw. On a success, the attempt succeeds and the spell ends.  On a failure, nothing happens, as the creature is prevented from teleporting.
### Augment
- You can expend 1 additional mana or psi to target an additional creature within range.
- You can expend 1 additional mana or psi to increase the duration to 1 hour/mana or psi.

potential balance changes if needed:
- could make it 1 mana and 1 action if it's too weak
- could make it deal damage on each teleportation attempt if it's too weak
- could add concentration if it's too strong
- could make the spell stay even after a successful teleportation - would make it slightly more useful against something like a boss that teleports every turn in combat.

**Comment by DalenWBrauner** [comment]
Hrmm... I remember a past campaign where someone effectively accomplished this by casting Bound Proximity on a rival teleporter. (Not that that would work across planes.)

Yeah, imo it's a niche enough spell that if it worked as-written, I think it would make sense as a 1 Mana spell, but then again.. Avert Teleport is 2 Mana. This spell seems a lot like a non-reaction version of that spell.

Also, I think it could have an augment to have it affect an additional target.

**Comment by mlenser** [comment]
I've considered this spell before. This is a very niche spell which is already covered by Avert Teleport. Avert Teleport accomplishes the same goals of stopping a creature from teleporting, but in a way that would be used much more often.
