### ISSUE TITLE
Add Avert Teleport to Antimagic

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#874]
**Is your feature request related to a problem? Please describe.**
Nope- it just seems flavorful that an antimagic caster would be able to halt teleporters in their tracks.

**Describe the solution you'd like**
Add [Avert Teleport](https://www.kryxrpg.com/spells/avert-teleport/) to the Antimagic theme. It could stay in Teleportation as well, if that made sense.

**Comment by mlenser** [comment]
I believe this is stretching the Antimagic theme to be what the Abjuration school is by RAW.

If we follow this same logic then I should add Protection from Acid/Fire/Poison/etc, but limited to damage from magic. I then should also add ways to stop being slowed by magic. I should then add ways to protect your mind from magic.

I don't think this is a good direction.

**Comment by DalenWBrauner** [comment]
Ah, good point!
