### ISSUE TITLE
Magic Missiles adding 5 ability goes off the charts

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#875]
Similar to other no miss spells, Magic Missiles scales with the caster's spellcasting ability. The sheet considers the caster has 3.5 of said ability, and that is fine for other spells, but, since that ability is multiplied by the number of missiles, the spell deals way too much damage if you actually have a 5 in the ability instead.

It deals 1.5 more damage per missile, or 3 more damage per mana. Considering the spell can't miss, I believe that is equivalent of ~5 extra damage per mana. At 3 mana, that is close to a save spell dealing 15 more damage. I think that is way too much, so Magic missile shouldn't add the ability for each missile, but I'm unsure how to fix this.

**Comment by mlenser** [comment]
All spells adjust above/below the guidelines based on spellcasting ability.

Dampen Pain goes from
![image](https://user-images.githubusercontent.com/235857/123583981-dfa96980-d7e0-11eb-864d-579d0c210ba1.png)
to
![image](https://user-images.githubusercontent.com/235857/123583825-90633900-d7e0-11eb-9558-dd2f14664d30.png)

Magic missiles goes from
![image](https://user-images.githubusercontent.com/235857/123583959-d4563e00-d7e0-11eb-857e-957ba928db7d.png)
to
![image](https://user-images.githubusercontent.com/235857/123583862-a1ac4580-d7e0-11eb-9b56-2fd846466dde.png)

This is the nature of adding spellcasting ability.

**Comment by Marcloure** [comment]
I know, but other spells gain a constant ~3 if you max your spellcasting ability. As you can see on your table, Magic Missiles explodes way beyond that

**Comment by mlenser** [comment]
"Explodes" is a bit dramatic as other spells can also go beyond the guidelines like this.

But I see the issue. I'm just not sure it is solvable or how to solve it.

One idea: "one missile deals 1d6+ spellcasting ability damage and the other deals 1d6". Kinda messy.

**Comment by Marcloure** [comment]
I'm not sure what is the best way to solve this too. Maybe you shouldn't be able to target more than half your missiles on a single creature? Don't know how much that would bring the DPR down

**Comment by mlenser** [comment]
That wouldn't solve anything - the spellcasting ability is added to each missile still.

Plus I don't think we should limit Magic Missiles to not work against 1 creature.

**Comment by Marcloure** [comment]
So, maybe you create a number of missiles equal to your spellcasting ability, +X missiles per augment?

**Comment by mlenser** [comment]
That would be very unbalanced.

2d6:
![image](https://user-images.githubusercontent.com/235857/123586918-bfc87480-d7e5-11eb-9243-0e10d76a83ec.png)

3.5d6:
![image](https://user-images.githubusercontent.com/235857/123586894-b6d7a300-d7e5-11eb-86e0-d3ccb73b0e8c.png)

5d6:
![image](https://user-images.githubusercontent.com/235857/123586935-c820af80-d7e5-11eb-8267-dfdddff11ee1.png)

**Comment by mlenser** [comment]
Magic Missiles adjusted to evenly divide a pool of damage.
