### ISSUE TITLE
1d20 vs 2d10 settings bug in some pages

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#877]
https://www.kryxrpg.com/rules/combat, https://www.kryxrpg.com/rules/skills, https://www.kryxrpg.com/rules/conditions
Seems like 2d10 is always written instead of 1d20, regardless of 2d10 setting. The other numbers (e.g. crit ranges) still respect the setting.

https://www.kryxrpg.com/rules/conditions
The Dying condition table shows the 2d10 table regardless of setting.

https://www.kryxrpg.com/rules/skills, https://www.kryxrpg.com/rules/conditions, https://www.kryxrpg.com/rules/quick-reference, and probably other places:
The dynamic links for skills (e.g. [Arcana](https://www.kryxrpg.com/rules/skills#arcana)), conditions, saving throws, etc are only active when 2d10 mode is on.

**Comment by mlenser** [comment]
This should be fixed.
