### ISSUE TITLE
Improve Naturalist's Land Stride text

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#878]
The text for the Naturalist's Land Stride contains non-intuitive math, and I believe its example is actually wrong on some parts. "Costs three-fourths extra movement" is so confusing that I'm not even sure whether the example is wrong or not.

I suggest to change it to something like (important change bolded):

> Your walking speed increases by 1 meter. Additionally, **nonmagical difficult terrain costs you 1 additional meter for every 2 meters you travel**, instead of the normal amount. For example, moving 1 meter costs 1 meter, moving 2 meters costs 3 meters, moving 3 meters costs 4 meters of movement, moving 4 meters costs 6 meters of movement, moving 5 meters costs 7 meters of movement, and moving 6 meters costs 9 meters of movement.

This text basically means you need to divide by two and add the result (rounded down as usual) to the distance.

**Comment by itamarcu** [comment]
I think the 3/4th math is too complicated.  The system should limit itself to multiplication and division by 2 and to flat increases/reductions, as much as possible.

I suggest one of...
1. You can ignore up to 2 meters of nonmagical difficult terrain every turn, treating it as normal terrain instead.
2. Once per turn while moving you can spend 1 additional meter of movement to ignore nonmagical difficult terrain until the end of that turn.
3. As a reaction when moving through nonmagical difficult terrain you can ignore it until the start of your next turn, treating it as normal terrain instead.

**Comment by mlenser** [comment]
> I suggest one of.

This feature is not meant to be an active ability you use. It is meant to be passive. It must also apply to normal distances and travel pace.

**Comment by mlenser** [comment]
>  Additionally, nonmagical difficult terrain costs you 1 additional meter for every 2 meters you travel, instead of the normal amount.

I find this more confusing.

I've cleaned up the wording a bit:
![image](https://user-images.githubusercontent.com/235857/124394616-7c4b9a00-dd00-11eb-9d68-586039b5f58e.png)

**Comment by Marcloure** [comment]
Why 1 meter of distance costs 2 meters of movement? Your speed drops to 0.75, so you need 1.5 meters of movement to travel 1 meter, rounded down to 1 meter, no?

Also, this is still hard to calculate on the fly. If a creature wants to move 10 meters on difficult terrain, how much speed does it need? 15? 12? 13?

**Comment by mlenser** [comment]
> Why 1 meter of distance costs 2 meters of movement? Your speed drops to 0.75, so you need 1.5 meters of movement to travel 1 meter, rounded down to 1 meter, no?

Moving 1 meter would cost 1.5 meters. Spaces are counted in full amounts, so it would take 2 meters to move.

The same is true for standing up. Standing up requires half your speed. In RAW a Dwarf's 25 feet speed is 12.5 half. So they'd have 12.5 left which is effectively 10.

> If a creature wants to move 10 meters on difficult terrain, how much speed does it need? 15? 12? 13?

It should be super simple. Difficult terrain = double while this is 1.5x. So 10 would be 15 instead of 20.

**Comment by Marcloure** [comment]
> Moving 1 meter would cost 1.5 meters

Then 6 meters should cost 9 meters, not 8 meters as written in the example. On the other hand, moving having 8 meters of speed at 3/4 penalty means you move 6 meters (8 * 3/4 = 6 meters). That is why the writing isn't clear.

> Difficult terrain = double while this is 1.5x.

Sure, but "you move at three-fourths speed" isn't straight forward about that math, as shown above. Either "you expend 1.5 times the distance instead of double the distance" or "1 extra meter for every 2 meters" is much clearer imo.

**Comment by Marcloure** [comment]
Just to complement, you said:

> So 10 would be 15 instead of 20.

However, 15 * 3/4 is 11.25, so a character with 15 speed moving through difficult terrain would move 11 meters. A character with 13 speed moving through difficult terrain would move 9 meters (13 * 3/4). Math isn't straight forward the way it is presented.

**Comment by mlenser** [comment]
> "1 extra meter for every 2 meters" is much clearer imo.

That's not very clear though. It treats 1 meter as normal movement so players could just move 1 meter, then 1 meter, then 1 meter, etc.

Effectively it's what I wrote: "Moving 1 meter costs 2 meters, moving 2 meters costs 3 meters"

> I never calculated it like that. The rule says you take half your speed to stand up, and half of 25 ft. is 12.5 ft.. I always rounded the cost to 10 ft., not the remaining speed.

That is incorrect. A RAW dwarf doesn't use 10 feet to stand up and then have 15 remaining. They use 12.5 to stand up and have 12.5 left over, of which 2.5 is not useful so they have 10 left.

_______________

> Sure, but "you move at three-fourths speed" isn't straight forward about that math

The travel pace example should be quite clear. I'll look at the short movement again tomorrow.

**Comment by itamarcu** [comment]
I don't think travel pace even matters that much.  This ability doesn't help your allies (so it's not useful for the entire party), and even when it helps it takes 75% as long as normal which probably won't change the story.

**Comment by Marcloure** [comment]
Natural Explorer covers the Travel speed part:
> Your group moves at three-fourths speed instead of half speed through nonmagical difficult terrain.

**Comment by mlenser** [comment]
> I don't think travel pace even matters that much. This ability doesn't help your allies (so it's not useful for the entire party), and even when it helps it takes 75% as long as normal which probably won't change the story.

This is dismissive of travel pace in general and shows a narrow view of the game imo. Crossing a desert in less time matters. Crossing a dense forest in less time matters.
It only applies to you, but that's true for all travel pace issues. If the party wants to stay together then the character that can move the fastest can act as a scout that constantly goes out and reports back to the slower moving group.

This really misses the bigger picture of the game.

**Comment by mlenser** [comment]
Looking at some normal cases:

## 5 meters of distance
- No Difficult terrain: 5 meters
- Land's Stride: 3.75 meters (3)
- Difficult terrain: 2.5 meters (2)

## 10 meters of distance (dash)
- No Difficult terrain: 10 meters
- Land's Stride: 7.5 meters (7)
- Difficult terrain: 5 meters

## 15 meters of distance (dash + dash)
- No Difficult terrain: 15 meters
- Land's Stride: 11.25 meters (11)
- Difficult terrain: 7.5 meters (7)

## 20 meters of distance (?)
- No Difficult terrain: 20 meters
- Land's Stride: 15 meters
- Difficult terrain: 10 meters

It's quite straight forward.

__________________

> If a creature wants to move 10 meters on difficult terrain, how much speed does it need?

It needs to spend 14 meters of movement. 0.75*14 meters = 10.5 meters. I would've expected 15 as that's halfway between 10 and 20, but it isn't exact for reasons my brain can't fully comprehend right now.

**Comment by Marcloure** [comment]
Issue is that you usually have the distance and then want to find out how much speed you need to travel it. Doing 6*3/4 isn't hard, but figuring out what number 6 is three-fourths of requires some thinking. Also this calculation can happen multiple times on a turn: a Naturalist that wants to walk 4 meters of difficult terrain, then 2 meters of normal terrain, and another 5 meters of difficult terrain has to make multiple non-intuitive calculations to figure out the required speed for the movement.

**Comment by Marcloure** [comment]
An alternative solution could be to change the feature to something like: the first meters you walk through difficult terrain on a turn is considered normal terrain. This distance is equal to half your speed.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/124506829-c26e2f80-ddcc-11eb-9fe2-a1c592e91305.png)

**Comment by mlenser** [comment]
As I said above, this should work out to half way between normal and difficult terrain, but doesn't for some reason. If someone knows why, let's fix it. Otherwise it's good enough for me.

**Comment by itamarcu** [comment]
small notes:
- should be "move **at** three-fourths speed instead of **at** half speed"
- it doesn't add up to halfway between normal and difficult because the formula is `x costs CEIL(x*1.333) instead of (x*2)`.  This is because 1 / 3/4 = 4/3 = 1.3333.  If you want it to be exactly between them (up to rounding), make it "you move at two-thirds speed instead of half speed".  This would change the numbers from 2,3,4,6,7,8,10,11,12,14 to 2,3,5,6,8,9,11,12,14,15.

**Comment by mlenser** [comment]
A janky way you can work "backwards": multiple the target distance by 1.33333333333333 and round up.

It doesn't make me super happy, but 🤷

**Comment by mlenser** [comment]
> it doesn't add up to halfway between normal and difficult because the formula is `x costs CEIL(x*1.333) instead of (x*2)`.  This is because 1 / 3/4 = 4/3 = 1.3333.  If you want it to be exactly between them (up to rounding), make it "you move at two-thirds speed instead of half speed".  This would change the numbers from 2,3,4,6,7,8,10,11,12,14 to 2,3,5,6,8,9,11,12,14,15.

But that doesn't work for travel pace. 2/3 of 100 would be 66.66666666, not 75. These two behaving differently boggles my mind a bit........

**Comment by Marcloure** [comment]
> 2/3 of 100 would be 66.66666666, not 75

If you travel 100 miles per hour:
- normal terrain takes 1 hour
- difficult terrain takes 2 hours (100/2 = 50 per hour)
- Land Strider difficult terrain takes 1.5 hours (100 * 2/3 = 66.6 per hour, 100/66.6 = 1.5 hours)

2/3 is indeed the correct multiplier for half way between normal terrain and difficult terrain.

**Comment by mlenser** [comment]
> If you travel 100 units per hour and wants to travel 100 units:
> 
> * normal terrain takes 1 hour
> * difficult terrain takes 2 hours (100/2 = 50 per hour)
> * Natural Explorer difficult terrain takes 1.5 hours (100 * 2/3 = 66.6 per hour, 100/66.6 = 1.5 hours)
> 
> 2/3 is indeed the correct multiplier for half way between normal terrain and difficult terrain.

But this doesn't work when keeping the time (per minute, per hour, etc) consistent, like the table presents:
![image](https://user-images.githubusercontent.com/235857/124517044-47644380-dde3-11eb-8c0a-2e609b4abbea.png)

So with that table 100 meters would become 66, which is not halfway between 50 and 100.

**Comment by itamarcu** [comment]
That table uses very rounded numbers and doesn't make sense.  The distances per minute are 3x, 2x, 1x, while the distances per hour are 3x, 2x, 2.3333x.  To fix it the Slow Distance per hour should be 3 km and the Slow Distance per day should be 25.

**Comment by itamarcu** [comment]
Unless you use round numbers like half and double speed, you can't have both round numbers for the distance/speed and round numbers for the time.  If your speed is 75% it will take you 1.33 minutes to travel 100 meters.  If your speed is 66% it will take you 1 minute to travel 66 meters.

**Comment by Marcloure** [comment]
I believe using two-thirds is indeed better than 3/4. It's easier to calculate (distance * 1.5 rounded up) and it's more correct as the mid-way between normal terrain and difficult terrain, both for normal movement and travel movement.

**Comment by mlenser** [comment]
> That table uses very rounded numbers and doesn't make sense.

The table is what GMs should use to base longer distance travel upon. If they're wrong, then it should be updated. Ignoring it is not valuable feedback for this discussion.

Taking that 100 meters and using the Naturalist's difficult terrain modifier would be 66. That's not correct. It doesn't matter if the numbers are round or not. 66 is not halfway between 50 and 100.
