### ISSUE TITLE
Chronostasis / Time Freeze / Suspend

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#879]
This is a suggestion for a Time spell that freezes creatures and objects in time, for an extended duration.  Note that this is different from Stasis - it's a longer term utility spell.  It's more like Petrifying something.

---

# Chronostasis / Time Freeze / Suspend
#### 1 minute, concentration
As two actions, you halt the passage of time for a Medium or smaller object or a creature that you can touch or see within 10 meters.  

An unwilling creature must make a Fortitude saving throw. On a failed save, its body starts to decelerate as it is slowed 2, and it must make another Fortitude saving throw at the end of its next turn or become suspended in time.  On a successful save, the spell ends for the creature.

A creature or object that is suspended in time is unaffected by the world around it, becoming immune to all damage and to any magical effects that are not already affecting it. Its shape cannot change, though it can still be moved around or carried. A creature ceases aging, is unaware of its surroundings, and does not experience the passage of time.  

If you concentrate on the spell for the entire duration, it lasts for 24 hours. Any effect that removes the petrified condition also ends the spell.

If you cast this spell on the same creature or object every day for a year, it lasts until dispelled.

---

Some design notes:
- I intended it to be used mainly out of combat, so I simplified the combat application against creatures to just be two Fort saves, instead of 3+ saves with increasing and decreasing levels of slow (which is how e.g. Flesh To Stone does it).  I wouldn't care about adding more saves.  Either way, I don't think this is so effective in combat, because Fortitude saves are the easiest and a suspended creature can't be harmed (unlike a petrified/stunned creature).  Additionally, when used against players, it's less permanent and less dangerous than petrification, which should make it more fun at the hands of an enemy.
- It's usable on objects, so you can cast it on a corpse to keep it fresh (like Gentle Repose), or cast it on a chest to temporarily "lock" it, or cast it on a sentimental sword to keep it from rusting.
- I chose to give it a base "combat" version with concentration, a duration of 24 hours once concentration is done (= out of combat), and an infinite duration if cast every day for a year.  Alternatively, the extended duration could be an augment or even the base version of the spell.
- Uncertain about the name because all three options seem good to me.

**Comment by mlenser** [comment]
This is essentially 2 saves or out of the combat.

I purposefully removed or changed spells that remove creatures from combat as much as possible. I don't want to add anymore. This is super effective in combat. Adding more saves makes it less oppressive, but Stasis is already freezing someone in time, but with a save every turn.

**Comment by itamarcu** [comment]
I'm also fine with:
- Changing the saves to be just like Contagion/Petrify, with each fail increasing slow by 1 and each success decreasing by 1
- Changing it to a save every turn, and holding if you've managed to concentrate throughout the duration
- Removing the ability to affect an unwilling/conscious creature

The goal here is mainly non-offensive utility. I think this is a very thematic spell and the Time theme literally mentions "freeze creatures in time" and "completely stop time".

Adding to Stasis wouldn't be easy because that base spell lasts for a single round, no concentration, and only stuns a creature.  To add the effect I want (of suspending something in time) e.g. as an augment, you'd need to add about four paragraphs of text, and it won't make sense to combine with the other augments.

**Comment by mlenser** [comment]
Stasis is the spell that freezes people on time. This spell does the same thing, but "out of combat" (which this isn't).

One of the core tenets of this system is that spells should cover their niche and similar spells should be merged in or added as augments. This suggestion goes against that tenet as stasis already covers this niche.

> Adding to Stasis wouldn't be easy because that base spell lasts for a single round, no concentration, and only stuns a creature. To add the effect I want (of suspending something in time) e.g. as an augment, you'd need to add about four paragraphs of text, and it won't make sense to combine with the other augments.

Stasis augments to last multiple rounds and use concentration. It also has a save every round. It does everything that this spell should, but doesn't (no save every round is a deal breaker).

**Comment by mlenser** [comment]
It may be that you want a feign death type spell, but that would be completely different than the suggestion above.

**Comment by itamarcu** [comment]
I want a utility spell that freezes things in time.  Halts the progress of time for them.  Stops processes from continuing.  

Stasis is a combat spell that only applies combat conditions to a creature, without actually stopping anything's time.  The only thing it shares with my suggestion is the general flavor/aesthetic of using time magic.

If it's important for you that a single spell will do this instead of two spells, then please help me come up with a way to alter the Stasis spell or add an augment.  It feels like you're shutting down the idea without even considering its major utility purpose, just because of the combat applications or the superficial similarity to Stasis.

If we go with an augment to Stasis - it could look like this:
> - You can expend 1 additional mana or psi and target a creature or object to fully suspend it in time. A creature or object that is suspended in time is unaffected by the world around it, becoming immune to all damage and to any magical effects that are not already affecting it. Its shape cannot change, though it can still be moved around or carried. A creature ceases aging, is unaware of its surroundings, and does not experience the passage of time.
> The spell's duration becomes concentration, 24 hours, and a creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. Any effect that removes the petrified condition also ends the spell.
> If you expend 2 additional mana or psi, the spell lasts until dispelled.

**Comment by Marcloure** [comment]
If the goal is a spell that freezes time for a creature permanently, I believe it would be more similar to other 5 mana imprisonment spells than to Stasis.

**Comment by mlenser** [comment]
> Stasis is a combat spell that only applies combat conditions to a creature, without actually stopping anything's time.

What are "combat conditions"?????? Slowed 2 is a normal condition which you use.. This makes no sense,

Slowing time would not stop damage. So hopefully that's not the requirement for "stopping time".

> If the goal is a spell that freezes time for a creature permanently, I believe it would be more similar to other 5 mana imprisonment spells than to Stasis.

Agreed. If we're going with permanent then it should be a 5 mana spell similar to slumbering imprisonment.

**Comment by itamarcu** [comment]
("combat conditions" as in mechanics that are not useful for utility outside combat)

Regarding permanent version - I agree.  My first version had it permanent when cast over and over for a year, and my latest suggestion (a Stasis augment) had it become permanent when you spend 2 additional mana, i.e. when you spend 5 mana in total.  Though I didn't want to add all the stuff about a passphrase or the wish spell, as it was long enough already.

But I don't think it should start at 5 mana, because stopping time for an object/creature can be quite useful even if it only lasts for a short duration.  You can keep a flower fresh, keep a snowman from melting, freeze dying people until you have a cure/revival, mislead someone into thinking it's a different time of the day/week, prevent a bomb from exploding until the area is cleared out, and so on.

> Slowing time would not stop damage. So hopefully that's not the requirement for "stopping time".

I think it's "fair" for some time stop effects to prevent the victim from being harmed, as it leads to more interesting problem solving.  It also mirrors [Time Stop](https://www.kryxrpg.com/spells/time-stop).  Though I can also imagine having the spell end when the victim is harmed (takes damage or fails a save?), similar to Sleep.

**Comment by mlenser** [comment]
Frozen in Time added to the Time theme as a spell similar to Imprisonment.
