### ISSUE TITLE
Questions about Fuse Form

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#880]
The way this spell works is rather confusing and could be clarified on some regards. Some questions about it:

1. The first paragraph says that you can drop unconscious independently of your eidolon. The first bullet point states that your statistics are replaced by that of your eidolon. How is it possible to take damage separately from your eidolon then?
2. When you take damage while fused, is it you or the eidolon who takes the damage? Or is the Health shared?
3. I suppose your eidolon is removed from the initiative and loses their actions?
4. If your Eidolon can cast spells, why would you not always use this spell (when you don't want to talk)? At 4 mana limit, you expend 4 mana to create your Eidolon, and 2 mana to Fuse Form. However, you gain back 3 mana from your Eidolon, so the total cost is 3 mana to gain a list of resistances, improved attacks, movement, etc. Maybe you should need another feat to cast spells like with Wild Shape (which already doesn't grant the resistances many forms have and doesn't give you a second Health pool)?
5. Speaking of second Health pool, I also noticed you can fight until you get close to death, Fuse Form, and gain 90+ Health from your Eidolon. Shouldn't you instead gain temporary health like with Wild Shape? Doing this would mitigate the 4th point.

**Comment by Marcloure** [comment]
Just to be clear, I'm ok with Fuse Form allowing spells. The 4th point is just a complement to the 5th. What I meant to say is that this spell would be better worded if it worked like Wild Shape, removing your Eidolon but allowed you to cast spells.

**Comment by mlenser** [comment]
> The first paragraph says that you can drop unconscious independently of your eidolon. The first bullet point states that your statistics are replaced by that of your eidolon. How is it possible to take damage separately from your eidolon then?

The intention is that you merge into your eidolon. But ongoing effects like bleed or random heart attacks could still kill you. I need to fix that part so that you retain your hit points.

> When you take damage while fused, is it you or the eidolon who takes the damage? Or is the Health shared?

Eidolon.

> I suppose your eidolon is removed from the initiative and loses their actions?

Nope, you become the eidolon essentially so you are removed from initiative.

> If your Eidolon can cast spells, why would you not always use this spell

By using this spell you're removing action economy. Two creatures become one so you're losing 2 actions essentially.

> Maybe you should need another feat to cast spells like with Wild Shape?

You're already giving up action economy for limited benefit so there should be no additional cost.

> Speaking of second Health pool, I also noticed you can fight until you get close to death, Fuse Form, and gain 90+ Health from your Eidolon. Shouldn't you instead gain temporary health like with Wild Shape? Doing this would mitigate the 4th point.

Hmm? Your eidolon doesn't regain health when you fuse. Your eidolon and you both have a set amount of health. When you fuse, you essentially hide your health but there is no gain of health.

**Comment by Marcloure** [comment]
> Your eidolon doesn't regain health when you fuse. Your eidolon and you both have a set amount of health. When you fuse, you essentially hide your health but there is no gain of health.

A 4 mana Eidolon has 90+ Health. You can enter combat, take some damage, and let's say you have 10 health now. You cast Fuse Form and now you have the 90 Health your Eidolon had, and can continue using your powers. That is way I think it should work more like Wild Shape: give you temp Health instead of the creatures Health.

**Comment by mlenser** [comment]
Your eidolon has 90 health, you have X health. By merging into your eidolon you don't magically gain more health.

It shouldn't work like Wild Shape. It's totally different.

**Comment by mlenser** [comment]
FYI: I'm likely going to replace Fuse Form with a cleaned up Fusion. I'll have to think it through a bit more.

**Comment by mlenser** [comment]
Fuse Form removed in favor of the cleaned up Fusion.
