### ISSUE TITLE
Ensure Ice theme has a persistent damage spell

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#881]
Perhaps Freeze can be augmented or there can be another way to deal persistent damage in the Ice theme.

**Comment by FoxenSocks** [comment]
Given how some persistent damage works on effects now (burning, bleeding), would it be worthwhile to introduce a similar effect for ice?  Something like frostbitten or chilled, perhaps?  Or would this be too complicated on top of Freeze's stun capability?

**Comment by Marcloure** [comment]
I don't think cold kills as fast as fire or bleeding. Cold takes minutes, fire takes seconds.

**Comment by FoxenSocks** [comment]
Depends on the cold.  There are some medical techniques that work by freezing off areas or growth targeted for removal.  It goes pretty fast–matter of seconds.  Besides, this is ice, and not just cold.  If all of the water in your cells suddenly freezes, causes them to expand, burst, and shred, you're gonna have a bad time.

**Comment by mlenser** [comment]
There are many cases of persistent damage without conditions.
![image](https://user-images.githubusercontent.com/235857/127439737-2dabe5f2-8524-46f5-8fb8-cee6ab004d63.png)

I don't think Ice needs a condition.

**Comment by mlenser** [comment]
Frostburn added to the Ice theme.
