### ISSUE TITLE
Witchcrafter's Ritualist should limit to spells that don't heal

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#882]
The Witchcrafter's Ritualist says:

> At 17th level, you unlock ancient secrets and techniques to master rituals. Any spell you know that has a casting time of an action or longer and costs 2 or less mana becomes a ritual spell for you. When you cast a spell as a ritual that is not normally a ritual, it requires additional consumed material components worth 10 sp for each mana of the spell.

This shouldn't allow using healing spells as rituals, similar to how Ritual Preparation (a Witchcraft) works:

> **Ritual Preparation**
> As an action, choose a spell you know that does not restore health. You can cast the chosen spell as a ritual until you finish a short or long rest.

**Comment by mlenser** [comment]
Is this necessary? This effect allows unlimited out of combat healing, but has some costs

## 1 mana
- 5 minutes + 1 action
- ~13-14 health
- 10 sp

## 2 mana
- 5 minutes + 1 action
- 26-27 health
- 20 sp

So you can heal ~27 health every 5 minutes for 20 sp. Seems pretty limited.

**Comment by itamarcu** [comment]
To be fair, this is 17th level.  I think it's alright to allow unlimited slow healing out of combat at that level.

**Comment by Marcloure** [comment]
It may be fine, it's just that I believe free healing is usually never safe to have. The Warrior had its regeneration replaced by temporary health, por instance. It may be fine in this case, though, since it would indeed require quite some time to heal multiple characters.

**Comment by mlenser** [comment]
It's time and money. I'm not opposed to restricting healing, but I also find it kind of thematic for a witch to heal someone over time by spending time and money.

**Comment by Marcloure** [comment]
It's not a lot of money though, 20 sp shouldn't be a lot at that point. Well, you can buy potions for 75sp, so maybe that is fine.

**Comment by mlenser** [comment]
Witchcrafter cannot restore health with a ritual from the Ritualist feature.
