### ISSUE TITLE
Ritual Preparation (a Witchcraft) should be limited to 3 or less mana

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#883]
> Ritual Preparation
> As an action, choose a spell you know that does not restore health. You can cast the chosen spell as a ritual until you finish a short or long rest.

There are a few reason for why I think this shouldn't allow 4 mana or 5 mana spells:

1. This would allow you to cast Imprisonment, Blizzard, Foresight, etc. without counting against the limit per rest (since I suppose rituals don't count, as they don't spend mana/slots).
2. Even if they do count against the limit, the other witchcrafts, channel divinity, etc. allow you to cast a 1 mana spell, so they give you a 1 mana discount. Casting a 4 or 5 mana spell as ritual gives you too much extra mana

I think 3 mana is a good limit. The other options allow you to cast an unknown spells at 1 mana discount, while this one would require you to know the spell, cast it for 5 minutes, can't be augmented, but allows up to a 3 mana spell.

**Comment by mlenser** [comment]
Witchcrafter Ritual Preparation limited to spells that cost 3 or less mana.
