### ISSUE TITLE
Adjust mana–stamina conversion ratio

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#885]
The Monk and the Soulknife can exchange 1 psi for 3 stamina, but with the latest change to the Stamina pool, this ratio gives them more Stamina than pure martials have. The current ratio is ~1:2.4, so I am not sure how to write this in a manageable way.

The [invigorate](https://www.kryxrpg.com/spells/invigorate) spell has the same conversion with a tax at the first mana.

**Comment by itamarcu** [comment]
You could do:
> You can expend 1 psi to gain 2 stamina, or you can expend 2 psi to gain 5 stamina.

This gives the players a ratio of 1 to 2.5 which is nearly identical.

**Comment by mlenser** [comment]
This ratio needs to be 1:3 for the sake of the psionicist. I'll likely need to revert the change and re-check my math.

**Comment by mlenser** [comment]
Reverted the ratio to be 1:3
