### ISSUE TITLE
NPC orcs should state how much bonus damage Blood Fury gives

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#886]
https://www.kryxrpg.com/creatures/orc

Blood Fury says "it can add its proficiency bonus to the damage". That should state the exact value added to the damage, instead of "its proficiency bonus".

**Comment by mlenser** [comment]
Its proficiency bonus is available if you hover over the challenge.

**Comment by mlenser** [comment]
Duplicate #867

**Comment by mlenser** [comment]
#888

**Comment by mlenser** [comment]
wrong issue

**Comment by mlenser** [comment]
Orcs now show their proficiency bonus in their Blood Fury trait.
