### ISSUE TITLE
Capitalize all conditions to avoid incorrect linking

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#888]
Avoid cases like 
![image](https://user-images.githubusercontent.com/235857/125982570-67789ea0-988e-4009-baf8-96f16d0df35e.png)

**Comment by mlenser** [comment]
I'd really rather not do this. I was able to avoid the issue in this scenario so I'm closing this, but I may need to do it eventually.

**Comment by Marcloure** [comment]
I prefer it as normal text too, not as a game mechanic term that is capitilized just to seem important.
