### ISSUE TITLE
2d10 damage is being converted to 1d20 by the setting

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#889]
For instance, the [ogre battering ram](https://www.kryxrpg.com/creatures/ogre-battering-ram) uses a 2d10 weapon, and that is being converted to d20 if you use the d20 setting.

Not a huge deal, since the avarage is pretty close, but rolling a d20 weapon is funny XD

**Comment by mlenser** [comment]
This will be fixed on the next build for all cases.
