### ISSUE TITLE
Remove or nerf Psychic Redoubt from the Psionicist

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#891]
A short discussion was had on Discord about it:

https://discord.com/channels/701706060440010753/709048873351381042/865675107548659742

In short:
- The Psionicist chassis already has a variety of useful features (extra capacity on save, adaptable benefit from psychic focus, overload, maneuvers), while other classes like the Naturalist, the Alchemist, and the Acolyte have mostly focused / situational benefits (natural explorer, minor alchemy, aura of courage, divine sense, etc.).
- The Druid, the Chemist, and the Cleric have shields, armor, and armor of faith in their favor when compared with the Psion. Of course, this comparion isn't valid if we look at the ranger vs. the soulknife, for instance.
- The Monk and the Soulknife don't really need extra health. The Soulknife has d10 hit die and its parry option, and the monk has a lot of movement, deflect missile, and unarmored defense.
- The amount of health given by this feature is rather high. Even when not considering the second wind recharge, it is a 20–50% Health increase (higher the level, lower the percentage).

**Comment by mlenser** [comment]
[Psychic Redoubt](https://www.kryxrpg.com/character/classes/psionicist#psychic-redoubt) is a feature that isn't super thematic for a Psionicist. It is also very strong. Over an adventuring that that'd be used 2.75 times.
- At level 3: 2.75 × (5.5+3) = ~23 health
- At level 5: 2.75 × (5.5+5) = ~29 health
- At level 9: 2.75 × (5.5+9) = ~40 health
- At level 13: 2.75 × (5.5+13) = ~51 health
- At level 17: 2.75 × (5.5+17) = ~62 health


 It originates from the Mystic UA:
![image](https://user-images.githubusercontent.com/235857/126048193-58f3e4c6-81ee-47ec-b656-135460df1847.png)

But perhaps it should be removed?

**Comment by mlenser** [comment]
Psychic Redoubt removed from the Psionicist.
