### ISSUE TITLE
Sense Minds is too powerful

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#893]
https://www.kryxrpg.com/spells/sense-minds

The spell lasts for 1 hour/mana, concentration free, and detects every mind within its area (which means you can always detect hiding creatures).

Compare it [Detect Evil and Good](https://www.kryxrpg.com/spells/detect-evil-and-good), which lasts for 5 min/mana, requires concentration, an action to detect, and has limited scope in what it can detect.

**Comment by mlenser** [comment]
Detect Evil and Good does not require an action to detect. It's an action to start the effect, same as Sense Minds.

**Comment by mlenser** [comment]
- Sense Minds Feat reworked to cast the spell at will.
  - Sense Minds duration reduced and it now requires concentration.
