### ISSUE TITLE
Fleshy Maws is missing its concentration

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#894]
https://www.kryxrpg.com/spells/fleshy-maws

The spell has concentration on the spreadsheet, but it is missing it on the site.

**Comment by mlenser** [comment]
Hmmm, not sure if it should have concentration. Inflict Wounds and Immolation don't, but they are unique. I'll need to check this over.

**Comment by mlenser** [comment]
It should have concentration. Inflict Wounds and Immolation don't because they are conditions that can be ended in much easier ways. Other continuous effects that require a save each round have concentration.

**Comment by mlenser** [comment]
Fleshy Maws simplified as the mechanics were overly complex. It is similar to other ongoing damage effects like Corrosive Consumption.
