### ISSUE TITLE
Allow Large creatures in the Tiny Hut

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#895]
Tiny Hut states that:

> Nine creatures of Medium size or smaller can fit inside the dome with you. The spell fails if its area includes a larger creature or more than nine creatures. 

However, that is based on the 5e text, where no Large PC exists. Here, we have the centaur as Large species, so I believe we should allow Large creatures (but they should take 4 spaces).

Same with Walking Hut and Shelter.

**Comment by mlenser** [comment]
Shelter, Tiny Hut, and Walking Hut now all allow Large creatures.
