### ISSUE TITLE
Natural armor is wrong in d20 setting

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#896]
d20: 
> When you aren’t wearing armor, your Defense equals 10 + half your proficiency bonus + your Dexterity (max 4). 

2d10:
> When you aren’t wearing armor, your Defense equals 13 + half your proficiency bonus + your Dexterity (max 4).

I believe d20 should be 12 + bonuses?

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/126058777-8725e274-a457-4754-8ae1-0321c78a3450.png)
fixed on next release
