### ISSUE TITLE
Align Webshooter to be more consistent with Grapple rules

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#899]
I'm not sure if one of the rules for [Webshooter](https://www.kryxrpg.com/spells/webshooter) is well-aligned with how the rest of the system handles escaping from grapples. 

Webshooter:
> If you pull yourself towards a surface while being grappled, any creature that is grappling you must succeed on a Reflex saving throw or be forced to release the grapple. 
> On a successful save, the creature can prevent you from moving. 

This seemed a little inconsistent with how I remembered grapple/restrain checks usually working, so I went to double-check the rules for escaping a grapple. That's when I realized it's not a contested check like I remembered, but a Brawn/Acrobatics check vs Passive Brawn.

I'm not sure that lends itself to an easy solution, but I still think the grappler making a Reflex save to keep the person locked in place doesn't quite seem right. Brawn seems to be _the_ skill to keep a target grappled. Perhaps instead the grappler makes a Brawn check? Or something of the Caster's compares against the grappler's passive Brawn?

As a bonus, there may be an opportunity here to add a rule for the grappler to maintain their grip on the target and instead be pulled with them. (I don't want to put out any suggestions for us to grow attached to until we've worked out the rest of it, however.)

**Additional context**
Discovered while scouring for ongoing effects that induce Reflex Saves.

**Comment by mlenser** [comment]
I wonder if the "Grapple" wording is the main issue here. Because Webshooter can be used to shoot a web at a creature which pulls them toward you. Effectively, the web is temporarily grappling the creature. Reflex is ok in that scenario (and others like Thorn Whip) as there is dodging involved with the (temporary) grappling.

I'm not sure what is best here so I'll let it sit for a bit..

**Comment by itamarcu** [comment]
I think it would make sense as...
- if you're grappled by a creature, the creature makes a Brawn check against your spell save DC.  On a success, the creature can choose to prevent you from moving or to be pulled along with you. On a failure by 4 or less, the creature can choose to be pulled along with you or to let go.  A creature cannot be pulled along with you if it is larger than you.

**Comment by mlenser** [comment]
Thanks!

**Comment by mlenser** [comment]
Vine Lash and Webshooter pulling yourself to a surface while being grappled changed to a Brawn check.
