### ISSUE TITLE
Add maneuvers/spells to creatures

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#9]
## Done

- ~Aberration (39)~
- ~Beast (118)~
- ~Celestial (8)~
- ~Construct (31)~
- ~Dragon (56)~
- ~Elemental (58)~
- ~Fiend (87)~
- ~Fey (21)~
- ~Giant (27)~
- ~Humanoid (152)~
- ~Monstrosity (84)~
- ~Ooze (10)~
- ~Plant (19)~
- ~Undead (48)~

**Comment by mlenser** [comment]
I would love some help on this project in this area if anyone would be willing to contribute. There are hundreds more monsters to do.

@Marcloure @wherfz @DalenWBrauner @Lamorak11

**Comment by Marcloure** [comment]
Hey, yes, I can help with that. I have been doing it for a while for my table actually.

I have a question though, how should CR or monster damage change with maneuvers? In my experience, while maneuvers do make monsters stronger, most kinda need a buff.

Also, some monsters just shouldn't have maneuvers I think, like most oozes or a gibbering mouther.

**Comment by mlenser** [comment]
> some monsters just shouldn't have maneuvers I think, like most oozes or a gibbering mouther.

My goal is for every monster to have maneuvers or spells. Not all maneuvers have to be offensive. For example several beasts have Sprint or Ambush (which is half combat, half not).

It worked for Beasts so far and other monsters that I've tried.

For Oozes I'd probably add ambush (as they like to drop on creatures) and maybe one or two more. For Gibbering Mouther I'd read it's monster description and from that information try to determine what type of creature it is and add maneuvers accordingly.

> how should CR or monster damage change with maneuvers? In my experience, while maneuvers do make monsters stronger, most kinda need a buff.

In general I don't think maneuvers/spells should impact challenge. For beasts many of them had built in effects removed in favor of maneuvers. For example the Dire Wolf had it's built in Trip on every hit (after Reflex) replaced with 2 stamina dice. So now it can trip only twice at the same DC.

For other monsters, like elementals, they surely have more options now. But lets take a look at https://marklenser.com/rpg/monsters/large-air-elemental. If we compare it to RAW:

- It lost Whirlwind (which it could use in half of its turns
- It gained 6 stamina dice and 3 mana

Overall the new version is more powerful, but the loss is not insubstantial. I would say it's ok as is.

So overall I think challenge is unaffected by manuevers/spells. It's just a more dynamic way to play. If we had to adjust challenge then every monster would have to be more difficult which I don't think is good.

_______________

My plan was to go monster type by monster type. Some smaller types that could be easy to tackle:
- Celestial (8)
- Construct (31)
- Fey (21)
- Giant (27)
- Ooze (10)
- Plants (19)

I try to list all maneuvers/spells that a creature would logically have based on its flavor, even maneuvers/spells above its current challenge (as my goal is to allow monster challenges to be adjusted which would then allow them to access higher level maneuvers/spells). I already filter out maneuvers/spells beyond their current capabilities so having that extra information would be helpful.

**Comment by mlenser** [comment]
Maneuvers and Spells added to oozes

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Black Dragon
Black dragons are cruel, sneaky, and sadistic, targeting the weakest enemy first and frightening the rest. They often play with their prey, letting them escape only to hunt them down again.

Black dragons live in foul water and acidic environments. They are often found in ruins, marches, and other blasted, dark places.

Overall, their **spell themes** are Acid, Fear, and Shadow. Their **martial theme** is Beast. As a rule of thumb, wyrmling and young dragons have only a few frightening powers when compared to adult or ancient dragons (when they gain Frightful Presence in RAW).
### Wyrmling
#### Maneuvers (3 stamina, limit 1): 
- **1 stamina die:** ambush, dive attack

#### Spells (2 mana, limit 1): 
- **cantrips:** gloom, hidden shadow
- **1 mana:** acid arrow, eruptive postule

### Young
#### Maneuvers (9 stamina, limit 3):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** tear tendon

#### Spells (5 mana, limit 3): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acid arrow, command, eruptive postule
- **2 mana:** acid fog, cloak of shadows, vitriolic sphere
- **3 mana:** corrosive bane

### Adult
#### Maneuvers (16 stamina, limit 4):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** tear tendon

#### Spells (8 mana, limit 4): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acid arrow, command, eruptive postule, fear
- **2 mana:** acid fog, cloak of shadows, frightful presence, vitriolic sphere
- **3 mana:** corrosive bane, incite panic

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** tear tendon

#### Spells (10 mana, limit 5): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acid arrow, command, eruptive postule, fear
- **2 mana:** acid fog, cloak of shadows, frightful presence, vitriolic sphere
- **3 mana:** corrosive bane, incite panic

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Blue Dragon
Blue dragons are patient. They play it safe, harming its prey at a distance and only entering the fray when it has the advantage. They also hunt from moving under the sand. 

Blue dragons command minions and many monsters. The older ones have elemental servants.

Overall, their **spell themes** are Fear, Sand, Storm, Trickery. Their **martial themes** are Beast and Trickery. As a rule of thumb, wyrmling and young dragons have only a few frightening powers when compared to adult or ancient dragons (when they gain Frightful Presence in RAW).
### Wyrmling
#### Maneuvers (3 stamina, limit 1): 
- **1 stamina die:** ambush, dive attack

#### Spells (2 mana, limit 1): 
- **cantrips:** blind spot, mold sand, shock
- **1 mana:** galvanize, wrath of the storm

### Young
#### Maneuvers (9 stamina, limit 3):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** blind

#### Spells (5 mana, limit 3): 
- **cantrips:** blind spot, frighten, mold sand, shock
- **1 mana:** invisibility, galvanize, locate water, sand cloud, wrath of the storm
- **2 mana:** blur, chain lightning, storm lord

### Adult
#### Maneuvers (16 stamina, limit 4):
- **1 stamina die:** ambush, dive attack, fearsome beast, swipe
- **2 stamina dice:** blind

#### Spells (8 mana, limit 4): 
- **cantrips:** blind spot, frighten, mold sand, shock
- **1 mana:** fear, invisibility, galvanize, locate water, sand cloud, wrath of the storm
- **2 mana:** blur, chain lightning, frightful presence, sand storm, storm lord

### Adult
#### Maneuvers (16 stamina, limit 4):
- **1 stamina die:** ambush, dive attack, fearsome beast, swipe
- **2 stamina dice:** blind

#### Spells (8 mana, limit 4): 
- **cantrips:** blind spot, frighten, mold sand, shock
- **1 mana:** fear, invisibility, galvanize, locate water, sand cloud, wrath of the storm
- **2 mana:** blur, chain lightning, frightful presence, sand storm, storm lord
- **3 mana:** incite panic

**Comment by Marcloure** [comment]
I think I should move this to a new issue...

**Comment by Marcloure** [comment]
## Dragons
I made dragons half-casters half-martials, though spellcasting dragons are a variant in 5e. I'll break it into different comments, one for each type.
### Black Dragon
Black dragons are cruel, sneaky, and sadistic, targeting the weakest enemy first and frightening the rest. They often play with their prey, letting them escape only to hunt them down again.

Black dragons live in foul water and acidic environments. They are often found in ruins, marches, and other blasted, dark places.

Overall, their **spell themes** are Acid, Fear, and Shadow. Their **martial theme** is Beast. As a rule of thumb, wyrmling and young dragons have only a few frightening powers when compared to adult or ancient dragons (when they gain Frightful Presence in RAW).
### Wyrmling
#### Maneuvers (3 stamina, limit 1): 
- **1 stamina die:** ambush, dive attack

#### Spells (2 mana, limit 1): 
- **cantrips:** gloom, hidden shadow
- **1 mana:** acidic spray, eruptive postule

### Young
#### Maneuvers (9 stamina, limit 3):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** tear tendon

#### Spells (5 mana, limit 3): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acidic spray, command, eruptive postule
- **2 mana:** acid fog, cloak of shadows, vitriolic sphere
- **3 mana:** corrosive bane

### Adult
#### Maneuvers (16 stamina, limit 4):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** tear tendon

#### Spells (8 mana, limit 4): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acidic spray, command, eruptive postule, fear
- **2 mana:** acid fog, cloak of shadows, frightful presence, vitriolic sphere
- **3 mana:** corrosive bane, incite panic

### Ancient
#### Maneuvers (20 stamina, limit 5):
- **1 stamina die:** ambush, dive attack, fearsome beast
- **2 stamina dice:** tear tendon

#### Spells (10 mana, limit 5): 
- **cantrips:** gloom, hidden shadow, frighten
- **1 mana:** acidic spray, command, eruptive postule, fear
- **2 mana:** acid fog, cloak of shadows, frightful presence, vitriolic sphere
- **3 mana:** corrosive bane, incite panic

**Comment by mlenser** [comment]
Dragons done via #46 and #48

**Comment by mlenser** [comment]
Celestials done

**Comment by Marcloure** [comment]
About the number of spells, do you think its fine this number that Celestials have? I mean, when I look at the Deva's or other Angels's statblock, there are some many spells that it's hard even to read.

**Comment by mlenser** [comment]
Angels (Deva, Planetar, Solar) are the epitome of the divine, life, and light themes. They are basically what those themes are based upon. That's why angels have so many spells. Looking through them again I find it hard to find many that don't fit. There are a few maybe.

Are there any that you think don't fit an angel?

**Comment by marcosPlayX** [comment]
I wouldn't say the problem is fitting. I personally don't like even the 22 or so spells RAW monsters have, so I like even less having 40 spells. Maybe it's just me though, I like simplicity when playing monsters, considering that we have to handle maneuvers and spells for every monster.

**Comment by mlenser** [comment]
Some monsters will have very few maneuvers. Beasts for example, generally have 1-3 maneuvers. Higher challenge beasts or special cases where it makes sense the beast might have more. In many cases built in attack effects have been taken out.

Some monsters will have a few maneuvers. Humanoids for example, generally have around 5 maneuvers with higher challenge humanoids having more.

Quite rarely a monster will have a lot of maneuvers.

Spells I haven't worked out the difference between RAW yet. Largely just choosing options that are thematic.
But you don't need to use every spell/maneuver. Spells especially can be niche and won't always be applicable. For the Angels, maybe it's an angel of vengeance and it largely doesn't use healing spells for example.

**Comment by Marcloure** [comment]
Just so you know, I am still doing this. It's just that I'm busy with work these past few days

**Comment by mlenser** [comment]
Aberrations are done

**Comment by mlenser** [comment]
Plants are done

**Comment by DalenWBrauner** [comment]
Oh crap, I somehow only just saw this! Count me in- I should be able to start contributing over the course of the next week, I think.

**Comment by mlenser** [comment]
Giants are done

**Comment by mlenser** [comment]
I've started associating manuevers to weapons and then monsters get the maneuvers from their weapons + more.

To make some sense of my data structure here is an exmaple of the Oni:
```
"powers": {
  "resourceTier": "half",
  "maneuvers": {
    "maneuvers": [
      "Ambush",
      "Cripple",
      "Spring Attack",
      "Stalking Shadow",
      "Slice Tendon"
    ],
    "groups": ["Glaive"],
    "themes": ["Deceit"]
  },
  "spellcasting": {
    "ability": "Charisma",
    "spells": [
      "Darkness (at will)",
      "Invisibility (at will)",
      "Cone of Cold",
      "Gaseous Form",
      "Charm Creature",
      "Sleep"
    ]
  }
},
```

Glaive, for example, has
```
"maneuvers": [
  "Glancing Blow",
  "Hamstring",
  "Lunge",
  "Slice Through",
  "Whirling Blade",
  "Staggering Strike"
]
```

I may show the maneuvers on the weapons page if it helps people with suggestions.

**Comment by mlenser** [comment]
Constructs done

**Comment by mlenser** [comment]
Fey done

**Comment by mlenser** [comment]
Undead done

**Comment by mlenser** [comment]
Monstrosities done

**Comment by mlenser** [comment]
All done!
