### ISSUE TITLE
Improve Shadowslip

### ISSUE THREAD

**Issue by wherfz** [mlenser/kryx-rpg-issues#90]
Despite being a 10th level feat, Shadowslip is very similar to the Shroud spell. It does not require concentration nor have duration but it does have the limitation of the creature being in dim light/darkness.  What does everyone think of Shadowslip being a bonus action to activate? 

Shadowslip
10th
Prerequisites: The ability to cast at least one spell
You have learned to become one with the shadows. When you are in an area of dim light or darkness, you can use your action to become invisible. You remain invisible until you make an attack, cast a spell, or are in an area of bright light

Shroud
6th
Prerequisites: You know the invisibility spell
You can cast invisibility at will, without expending mana.

**Comment by mlenser** [comment]
They're in different themes. Shadowslip is in the Shadow theme while Shroud is in the Deceit theme (where Invisibility lives). Shroud is a better feat.

That said I can reduce Shadowslip to level 6.
