### ISSUE TITLE
Formula Copying for Witch and Bloodhunter

### ISSUE THREAD

**Issue by FoxenSocks** [mlenser/kryx-rpg-issues#900]
Guidelines for learning concoctions are missing from the witch's grimoire and the bloodhunter's formula book.  I think they were lost in the recent grimoire/spell book/formula book update.  Please add them back when it's convenient.  ^-^

https://www.kryxrpg.com/character/classes/witchcrafter
https://www.kryxrpg.com/character/classes/rogue

**Comment by Marcloure** [comment]
There was a long, long discussion about it on Discord, if you are interested in reading it: https://discord.com/channels/701706060440010753/708327512169775145/869698544234278953

**Comment by FoxenSocks** [comment]
Since they use wisdom for casting as well, how then could they replicate rituals?
I think also that one of the key features of concocting that distinguishes it from casting _is_ the consistency.  Therefore, copying formulas (not inventing them, but copying them) should be the same across all alchemical classes.

**Comment by mlenser** [comment]
- **Classes**
  - The Blood Hunter learns alchemy similar to how a witchcrafter does so its alchemical ability is changed to Wisdom and it uses concoction recipes.

### Patch
- **Classes**
  - Witchcrafter Grimoire now correctly allows you to add concoctions to it.
