### ISSUE TITLE
Calm Emotions Concoction Equivalent (Soothing Mist?)

### ISSUE THREAD

**Issue by FoxenSocks** [mlenser/kryx-rpg-issues#901]
I think concoction options are still a bit limited, so I'd like to see more concoctions added.  Thus, I had an idea for a concoction.

Given how many concoctions directly correspond to spells, I think a concoction based on the spell Calm Emotions would work.  Calm emotions is from the Charm theme, which already has a few concoctions, so it likely wouldn't be too out of the way for many concoction crafting characters.  It would resemble many of the sort of mildly sedative mists/smokes we see in a lot of media–ones that make everyone calm down and take it easy, without putting them to sleep, like the flowers in that one episode of Star Trek (This Side of Paradise).  

Additional thought:
As the spell is a two mana AoE spell, I thought that to capitalize a bit on the difference between spells and concoctions, the two catalyst, spell equivalent, AoE version could be an augment (one additional catalyst on top of the base one catalyst) of a one catalyst base version of the concoction which would only work on a single target – a literal chill pill, if you will.

The spell is here:
https://www.kryxrpg.com/spells/calm-emotions

**Comment by mlenser** [comment]
It can't be made as an augment to a 1 catalyst concoction, else it is 1 action while the spell is 2 actions.

**Comment by mlenser** [comment]
hmmm, I'm not sure Calm Emotions is the right spell to be made into a concoction. It's effect is very magical. "you can make it indifferent about creatures of your choice that it is hostile toward" is something the caster has control over.

**Comment by Marcloure** [comment]
A drug/tea that makes a creature completely apathetic isn't a far stretch. It should affect every creature though, not "creatures of your choice"

**Comment by mlenser** [comment]
> A drug/tea that makes a creature completely apathetic isn't a far stretch. It should affect every creature though, not "creatures of your choice"

I agree, but Calm Emotion's wording is very spell specific. If someone wants to try to reword it in a way that can work for a Concoction I think it could work well.

**Comment by itamarcu** [comment]
>  If a creature fails its saving throw, it becomes mellow and relaxed, indifferent to all creatures it is hostile towards. This indifference ends if the target is attacked or harmed by a spell or if it witnesses any of its friends being harmed. When the effect ends, the creature becomes hostile again, unless the GM rules otherwise.

**Comment by FoxenSocks** [comment]
> It can't be made as an augment to a 1 catalyst concoction, else it is 1 action while the spell is 2 actions.

Ah, that makes sense.  Base two catalyst then.


> > A drug/tea that makes a creature completely apathetic isn't a far stretch. It should affect every creature though, not "creatures of your choice"
> 
> I agree, but Calm Emotion's wording is very spell specific. If someone wants to try to reword it in a way that can work for a Concoction I think it could work well.

Perhaps...
**Soothing Mist** (2 catalysts)
_1 minute/catalyst_
As two actions, As two actions, you can create this bomb. As an action, a creature can throw this bomb at a point within 5 meters, where it explodes on impact, releasing a fine, mildly reflective magenta mist.  Each creature in a sphere twice as big as normal centered on the point of impact must make a Will saving throw; a creature can choose to fail this saving throw if it wishes. If a creature fails its saving throw, it becomes indifferent toward any and all creatures that it is hostile toward. This indifference ends if the target is attacked or harmed by a spell or if it witnesses any of its friends being harmed. When the effect ends, the creature becomes hostile again, unless the GM rules otherwise.

(no longer concentration, but you have far less control over the impact, and could catch party members by accident)

**Comment by mlenser** [comment]
Pacifying Gas added to the Charm theme.

**Comment by mlenser** [comment]
> Aside: can concoction making classes augment concoctions to change the mode of AoE between Cone and Sphere? Both are reasonable modes of spread for fluid substances.)

A cone isn't a reasonable outcome from a glass vial breaking. That'll go in all directions.

**Comment by Marcloure** [comment]
There is a feat for that: https://www.kryxrpg.com/feats/directional-bomb

**Comment by FoxenSocks** [comment]
> > Aside: can concoction making classes augment concoctions to change the mode of AoE between Cone and Sphere? Both are reasonable modes of spread for fluid substances.)
> 
> A cone isn't a reasonable outcome from a glass vial breaking. That'll go in all directions.

I thought more like making a spray bottle rather than a bomb, but that's a different discussion.  And Marcloure pointed out the feat. :)
