### ISSUE TITLE
You can't revert from Gaseous Form if you have only 1 action

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#903]
https://www.kryxrpg.com/spells/gaseous-form

>Until the spell ends, as two actions, you can revert to cloud form.

If you target this spell on a lower level character, or on a NPC that has only 1 action, they can't revert by themselves. Maybe reverting should require 1 action and you become incapacitated until the end of your current turn.

Same for Aqueous Form.

**Comment by mlenser** [comment]
Reverting to normal form is 1 action, just like dash. The quoted text allows you to turn back into cloud form for 2 actions.
