### ISSUE TITLE
Incite Panic should state what the creatures are afraid of

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#908]
https://www.kryxrpg.com/spells/incite-panic

Incite Panic should state by what the targets are frightened, otherwise the frightened condition has no effect on them.

**Comment by mlenser** [comment]
Good question.. Maybe it should be the center of the sphere? Or not frightened and just confused?

Original from UA Mystic:
![image](https://user-images.githubusercontent.com/235857/127778807-40e01e61-c628-4627-a541-a0f02a09de67.png)

**Comment by Marcloure** [comment]
I think it would be interesting if they run from the center of the sphere. Since the targets can't cross the area, the confusion would create a random dispersion effect.

**Comment by mlenser** [comment]
Incite Panic frightened of the area in the center of the sphere.
