### ISSUE TITLE
Wall Health is wrong

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#909]
https://www.kryxrpg.com/spells/wall-of-flesh
20 Health per centimeter

https://www.kryxrpg.com/spells/wall-of-ice
15 Health per centimeter

Walls have 30 centimeters of thickness per mana, which would give these walls 600 Health per mana and 450 Health per mana, respectively.

**Comment by mlenser** [comment]
RAW wall of stone:
> 5th level
> 6 inches thick
> Each panel has AC 15 and 30 Hit Points per inch of thickness.

So ~180 health per panel


My wall of stone:
> 2 mana
> 60 centimeters inches thick
> Each panel has 15 Defense, 3 Soak, and 20 Health per centimeter of thickness.

So ~24 inches thick (2 feet) and ~1200 health per panel

______________


Ya, the thickness and health per thickness should be decreased across the board. I'll fix.

**Comment by mlenser** [comment]
Walls are now 1 meter thick and have 1, 1.5, or 2 Health per centimeter of thickness. So we're looking at 100, 150, or 200 health per panel.
