### ISSUE TITLE
Consider adding the freedom theme

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#911]
https://www.d20pfsrd.com/classes/core-classes/cleric/domains/paizo-domains/liberation-domain

![image](https://user-images.githubusercontent.com/235857/127780282-88244931-d819-4054-8807-e8d8ef59d9dd.png)

**Comment by itamarcu** [comment]
I think "freedom"/"liberation" theme doesn't make sense unless "offense" or "mobility" or "buffs" are themes.  It seems very mechanical to me, instead of flavorful.  I think many of these spells fit Antimagic and Holy/Life, and I can't imagine a mage that specializes in "freedom spells".  Maybe Abjuration is flavorful for some worlds with magical schools, but it would include a lot of spells that are already covered.

**Comment by Marcloure** [comment]
On the other hand, I can totaly see a monk or rogue that focuses on never being stopped or pinned down.

**Comment by Marcloure** [comment]
> On the other hand, I can totaly see a monk or rogue that focuses on never being stopped or pinned down.

Actually, wouldn't hit and run be just skirmish?

**Comment by DalenWBrauner** [comment]
While I love some of the concepts here, I'm also not convinced they would avoid overlap with existing themes.
* "Liberation magic" is cool, but removing curses and debuffs from magical sources feels an awful lot like antimagic.
* "Movement magic" is cool, but I'm not sure how to differentiate it between either Telekinesis (allowing other things to move) or Metabolism (altering your own ability to move)

But I also think Marcloure is on a good track- this seems like it would make for a great subclass, to borrow from existing themes and combine parts of them into a new concept.

**Comment by mlenser** [comment]
> I think "freedom"/"liberation" theme doesn't make sense unless "offense" or "mobility" or "buffs" are themes.

Mobility is a theme, but just for maneuvers. Skirmish.

> Actually, wouldn't hit and run be just skirmish?

Exactly.

____________

https://github.com/mlenser/kryx-rpg-issues/issues/156 talks about these generic maneuver themes and this thread points out what can be problematic about Skirmish as a theme.

**Comment by mlenser** [comment]
Not going to add a freedom theme.
