### ISSUE TITLE
Are there any unarmed strike details missing?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#912]
I noticed on the Combat page, under [Making an Attack -> Melee Attacks](https://www.kryxrpg.com/rules/combat/#melee-attacks), the last paragraph says:

> Instead of using a weapon to make a melee weapon attack, you can use an unarmed strike: a punch, kick, head-butt, or similar forceful blow. See [Weapons](https://www.kryxrpg.com/equipment/weapons) for details.

**Describe the bug**
Upon going to the linked Weapons page, (the equipment page, not the Weapons skill,) there isn't actually any section or written detail on unarmed strikes. The only relevent information is a single entry in the Weapons table. This entry is very useful, but the quoted wording above leads me to question:

Was there supposed to be more information here? Or were the "details" intended to just refer to the line in the table?

If there aren't any missing details, I'd pedantically suggest tweaking the final sentence to something like:
> See [Weapons](https://www.kryxrpg.com/equipment/weapons) for the properties of an unarmed strike.

**Comment by mlenser** [comment]
Wording updated to
> See Weapons to see how much damage an unarmed strike does.
