### ISSUE TITLE
Add "special" to Unarmed Strikes on the Weapons table

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#913]
**Describe the solution you'd like**
Unarmed Strikes function differently than most [Weapons](https://www.kryxrpg.com/equipment/weapons), and have unusual rules regarding their use. Should we give them the "special" property, and write a section to better explain their use?

For instance, it could explain that they do not count as "weapon attacks", are not subject to spells such as Flaming Weapon, and that Unarmed Strikes cannot be made with Natural Weapons. (Or _correct_ versions of those statements, if I got any of those wrong.)

**Is your feature request related to a problem? Please describe.**
We've had some discussion in the past (and present) with how precisely Unarmed Strikes interact with other parts of the system. It think it would make sense to have any final rulings codified in text here.

**Describe alternatives you've considered**
We _do_ already have a sentence on Unarmed Strikes on the Combat page, but it links directly to this Weapons page. I think writing something on the Weapons page would be easier to reference- it is something of a "weapon alternative", after all. Plus, it's already (helpfully) in the Weapons table.

**Additional context**
I wanted this to be separate from #912 for two reasons. 1: That issue is to ask if there used to be more information that may have gone _missing._ 2: This issue is likely to prompt more discussion.

**Comment by Marcloure** [comment]
> it could explain that they do not count as "weapon attacks"

So, unarmed strikes _are_ weapon attacks, but are not weapons. If you are making an attack, any attack, it's either a spell attack or a weapon attack. A weapon attack can be made a) with a weapon, b) with a natural weapon, c) with no weapon (unarmed).

**Comment by mlenser** [comment]
> it could explain that they do not count as "weapon attacks"

They do count as weapon attacks.

> So, just to clarify this, unarmed strikes are weapon attacks, but are not weapons. If you are making an attack, any attack, it's either a spell attack or a weapon attack. A weapon attack can be made a) with a weapon, b) with a natural weapon, or c) with no weapon (unarmed).

Correct, though I think all PC cases of "natural weapon" are unarmed. The details that an unarmed strike can be used to make a melee attack are already covered in the combat section via

> Instead of using a weapon to make a melee weapon attack, you can use an **unarmed strike**
________________

> are not subject to spells such as Flaming Weapon

Flaming weapon says "a weapon you touch". An unarmed strike is not a weapon, but can be used to make a melee weapon attack.

______________

> Unarmed Strikes cannot be made with Natural Weapons

Hmm? I don't understand this.

> Yes, the attack is both with a natural weapon and unarmed at the same time...

There are no rules around "natural weapons" other than some maneuvers.

**Comment by mlenser** [comment]
Natural weapons wording has been removed from a few cases such as Sacred Fist, Monk, Natural Weapons, Natural Weapons Potion, Punches in Bunches, Brawling fighting style. Natural weapons wording still exists on feats like Infectious Fury and maneuvers like swipe as those are only meant to be made with natural weapons (such as the ones that a Mutant or Shifter archetype or an Aarakocra or Vayemniri species use). All the places where the wording changed should still function the same as before as PCs make natural weapon attacks via unarmed strikes.

Let me know if this didn't clarify things.
