### ISSUE TITLE
Inflict Wounds damage is wrong

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#914]
https://www.kryxrpg.com/spells/immolation

Immolation deals 4d6 + burning 3, but the spreadsheet seems to indicate it should do 3d6 + burning 3.

Also, https://www.kryxrpg.com/spells/inflict-wounds deals 3d6 + bleeding 3 (untyped damage though),

**Comment by mlenser** [comment]
Immolation is correct, Inflict wounds is not. Both should be 4d6 + 3 burning/bleeding
![image](https://user-images.githubusercontent.com/235857/128602757-aed1e40e-eae3-41d6-8293-fa2efb60a358.png)

**Comment by mlenser** [comment]
Inflict Wounds damage fixed to 4d6.
