### ISSUE TITLE
Flesh Whip should deal slashing damage

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#915]
https://www.kryxrpg.com/spells/flesh-whip

The spell turns your arm into a whip, so I think it should deal either slashing or bludgeoning damage, not piercing damage (unless your arm becomes a harpoon?)

**Comment by mlenser** [comment]
Thorn Whip is also a whip, but it deals piercing (due to the thorns).

This is a copy/paste error from Thorn Whip.

**Comment by mlenser** [comment]
Flesh Whip damage changed to slashing.
