### ISSUE TITLE
Make learning themes more costly

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#916]
I'd like to make themes more costly. Two advancements would be quite ok. I've been thinking of offering slightly more advancements so this could help that transition where some levels will award 2 advancements instead of 1 for martials/half casters so there is no sense of loss by waiting 2 levels to get a theme.

**Comment by Marcloure** [comment]
As for full casters, I think they have enough advancements. They will have around 20-30 spells after the 10th level, and that can be a lot for players to consider in a situation.

**Comment by mlenser** [comment]
- Learning a theme now costs two character advancements. [#916](https://github.com/mlenser/kryx-rpg-issues/issues/916)
  - Archetypes with half progression now have 5 character advancements over 20 levels. [#916](https://github.com/mlenser/kryx-rpg-issues/issues/916)
