### ISSUE TITLE
Monks cannot use longbows as monk weapons

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#917]
This isn't necessarily a bug, but I believe it is unintentional and should be rethought.

Basic monks, in both KryxRPG and RAW 5e, cannot use longbows as monk weapons - because monk weapons are restricted to a small subset of the weapons:
> quarterstaffs, light weapons, and any simple weapons that don’t have the two-handed or heavy property

Both KryxRPG and 5e have ways to turn other weapons into monk weapons, however.  In KryxRPG it's through the [Weapon Master](https://www.kryxrpg.com/feats/weapon-master) feat:
> If you are a Monk, weapons in these groups are considered monk weapons for you if they lack the heavy and special properties.

and in 5e the Kensei monk (which specializes in certain weapons) gets a similar paragraph, with a special exception for the longbow:
>  Each of these weapons can be any simple or martial weapon that lacks the heavy and special properties. **The longbow is also a valid choice.**

In KryxRPG, the sentence about the longbow has been removed.

I haven't played with longbow monk characters myself, but from browsing online it looks like there are many 5e players who built Kensei longbow users, so there might be some demand for it.

**Comment by mlenser** [comment]
I don't think it was unintentional, but I'm not sure why I made the decision to have monks use shortbow.

https://github.com/mlenser/kryx-rpg-issues/issues/303 is what caused the change.. hmm

**Comment by mlenser** [comment]
RAW: Shortbows and Longbows are not monk weapons. See https://rpg.stackexchange.com/questions/67091/can-monks-use-shortbows#:~:text=The%20shortbow%20is%20a%20simple,is%20not%20a%20monk%20weapon. Kensei Monk does allow shortbow and longbow to be a monk weapon.

My system: Shortbows and Longbows are not monk weapons. Neither can become a monk weapon.

Viewpoint as I see it now: I see monks as a short range class. They have tons of options to throw darts, daggers, sais, shurikens, etc. They also have some magical options to shoot magic stuff. I don't see the shortbow or longbow as being overly thematic for a monk. The shortbow can still be used, just not combined with unarmed strikes. I think combining unarmed strikes with bows isn't so thematic anyways.

**Comment by itamarcu** [comment]
Yeah, that seems valid.  Shortbow/Longbow have a much longer range than other ranged options like shuriken or slings, and if you're using them then you almost definitely won't have an enemy to hit with an unarmed strike anyways.

**Comment by mlenser** [comment]
Closing this since bows and unarmed strikes is a weird thematic combination.
