### ISSUE TITLE
Deceit Volitile Power should break when you force a save

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#919]
> **Deceit.** You become invisible for a number of turns equal to the power expended divided by 3. The invisibility lasts until the end of that turn or until you attack or cast a spell.

The invisibility should break if you use an action to force a save with enervation, earthen grasp, or other repeatable spells.

**Comment by mlenser** [comment]
How is this different from [Invisibility](https://www.kryxrpg.com/spells/invisibility) which states:

> The spell ends if you attack, throw a concoction, use a maneuver, or cast a spell.

None of the above would be covered by normal invisibility either.

**Comment by itamarcu** [comment]
We could add a rule someplace that says that using an action to control a spell counts as casting a spell for the purpose of triggers.  This would also allow Spellsplinter, Dampen Spell, and Steal Spell to work on these repeatable things, which seems reasonable to me.

**Comment by Marcloure** [comment]
> None of the above would be covered by normal invisibility either.

Well, it's strange and very powerful that you can cast Earthen Grasp or Evervation and remain the next few turns invisible while attacking with these spells. The invisbility spell requires concentration, so it's less of an issue, since repeatable spells are also concentration.

**Comment by mlenser** [comment]
> This would also allow Spellsplinter, Dampen Spell, and Steal Spell to work on these repeatable things, which seems reasonable to me.

Spellsplinter shouldn't work on using a spell after the fact. It's not casting a spell. Same with the others. They're only usable on the initial casting.

**Comment by mlenser** [comment]
Suffused Volatile Power Deceit invisibility now requires concentration.
