### ISSUE TITLE
Cauterize Wound Confusing

### ISSUE THREAD

**Issue by cyanomys** [mlenser/kryx-rpg-issues#92]
In American vernacular, cauterizing a wound is considered a _good_ thing that prevents someone from bleeding out, so my players keep getting confused because it's actually an *offensive* (not healing) cantrip.  

Here are some less confusing names that get sort of the same thing across:
- Sear Wounds
- Blistering Wounds
- Cauterizing Canker

**Comment by mlenser** [comment]
> Cauterization is a medical practice or technique of burning a part of a body to remove or close off a part of it. It destroys some tissue in an attempt to mitigate bleeding and damage, remove an undesired growth, or minimize other potential medical harm, such as infections when antibiotics are unavailable.

Cauterizing prevents infection and bleeding, but it definitely damages an area. In game terms that damage is preventing healing for a turn. Without the work cauterize this cantrip has no flavor to continue to exist.

**Comment by mlenser** [comment]
Cauterize Wound changed to stop bleeding and stabilize

**Comment by cyanomys** [comment]
Awesome!
