### ISSUE TITLE
Rename Demons and Devils to their real names

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#921]
So Kyton instead of Chain Devil for example.

**Comment by itamarcu** [comment]
Maybe have both in the name?  e.g. "Kyton (Chain Devil)"

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/128864976-4c547358-9bca-448b-a771-fe576e0751b7.png)

However it won't appear in the URL or the Creatures page. Seems ok.

**Comment by mlenser** [comment]
Renamed devils to their actual name.
