### ISSUE TITLE
Calculate traits as part of challenge

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#924]
as part of #898 I'll need take traits into consideration. The DMG has the following adjustments:
![image](https://user-images.githubusercontent.com/235857/129376908-e4563ccf-3270-4392-aac7-9b45edf9f9f9.png)
![image](https://user-images.githubusercontent.com/235857/129376940-0a7092b5-35dc-429e-851b-e874e5a4ff52.png)

I'm doing all of those now, but I will need to search through all traits that have come out since the DMG to account for them.

**Comment by mlenser** [comment]
Many traits now have an impact on the estimated challenge of creatures.

I ignored Frightful Presence and Web as I think they should be handled differently.

**Comment by mlenser** [comment]
All creature traits are now stored in one central location which makes it much easier for to value them. There were some minor adjustments made to traits that were thematically similar, but mechanically slightly different for a few creatures. Many more traits also impact their challenge now.

**Comment by mlenser** [comment]
All traits are now evaluated to impact a creature’s challenge estimate.

**Comment by itamarcu** [comment]
> All creature traits are now stored in one central location

Could you link to it? (here and/or in the website)

**Comment by mlenser** [comment]
> > All creature traits are now stored in one central location
> 
> Could you link to it? (here and/or in the website)

They're in data files.

**Comment by itamarcu** [comment]
Ah, alright, I thought they'd be in a spreadsheet like the species traits (would help some homebrewers).
