### ISSUE TITLE
Magic Resistance (feat) shouldn't give resistance to spell damage

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#927]
https://www.kryxrpg.com/feats/spell-resistance

Magic Resistance is already a powerful enough feat by giving you advantage on all saving throws against spells and other magical effects, so I'm not sure why it also gives resistance to spell damage. I mean, it is one of the best feats for post 14th level play —even if you don't take it at the 14th level, you will likely want it later. 

Also, since it gives you resistance to all spell damage, it also reduces the value of other damage resistance feats, which I think isn't desirable.

**Comment by itamarcu** [comment]
I agree - I think it would be better as two feats.  Could also add "spell attacks have disadvantage against you".

Other antimagic feat options could be that you are resistant in other ways, for example by halving the duration of all spells that affect you, or giving you advantage on spell saving throws beyond the first one for each spell (symbolizing a sort of immune system against spells), or forcing casters to make ability checks if they try to target/include you in a spell effect.

**Comment by mlenser** [comment]
Without evaluating the feat's power yet:

> it is one of the best feats for post 14th level play

There are only 28 feats at level 14+, most of which are wings and other forms of movement. It being "the best" among those isn't too hard to do.

More high level feats would provide more diverse options. Please do suggest them!

**Comment by mlenser** [comment]
> Other antimagic feat options could be that you are resistant in other ways, for example by halving the duration of all spells that affect you, or giving you advantage on spell saving throws beyond the first one for each spell (symbolizing a sort of immune system against spells), or forcing casters to make ability checks if they try to target/include you in a spell effect.

Please open suggestions!

**Comment by Marcloure** [comment]
> More high level feats would provide more diverse options.

It's not just about diversity, I understand that there aren't that many options. However, even if this wasn't a feat but a singular benefit, the damage resistance is an unasked boost to a very powerful bonus. The doubled benefit against damaging spells takes all of them out of concern for that character.

Also, no other spell resistance in the game also grants this ramage resistance, so I don't know why this one does.

**Comment by Marcloure** [comment]
Well, that subclass isn't something anyone can have, and this existing in 5e doesn't mean it's good. Also, characters have much less proficiency on saves in 5e.

 I just don't see the need for the damage reduction. Advantage on saves against every spell seems powerful enough to me.

**Comment by mlenser** [comment]
That said: I agree that it should be split

  - Magic Resistance feat added to the Antimagic theme which takes the first benefit of the Spell Resistance feat which is the same as the Magic Resistance trait that creatures have. [#927](https://github.com/mlenser/kryx-rpg-issues/issues/927)
  - Spell Resistance feat reworked to only include the resistance to damage from spells and moved to 18th level. [#927](https://github.com/mlenser/kryx-rpg-issues/issues/927)

**Comment by mlenser** [comment]
- Magic Immune Response added to the Antimagic theme. [#927](https://github.com/mlenser/kryx-rpg-issues/issues/927)

**Comment by itamarcu** [comment]
Magic Immune Response:
> If you fail a saving throw against a spell or other magical effect, your body develops resistances to that spell, learning how to fend it off. You have advantage on any subsequent saving throws against the spell or magical effect.

With its phrasing it seems to imply to me that if you fail one saving throw against e.g. Sleep you have advantage against each future creature that casts Sleep on you.  This would mean you can get vaccinated against spells, which is not intended (not that I'm against magical vaccines :P).  The phrase "subsequent saving throws" may be intended to mean only that specific "instance" of the spell/effect (not sure how to phrase that), and not future times someone casts the spell on you, but it feels ambiguous to me.

I suggest one of:
- Add "until it ends" (i.e. the resistance is gone once the spell or magical effect ends)
- Add clarifying text in parentheses: "..or magical effect (this does not apply if the spell is cast again)"
- Add a time limit, such as 1 hour.

**Comment by mlenser** [comment]
Magic Immune Response reworked to only apply to the next saving throw.

**Comment by itamarcu** [comment]
Oh, that's actually perfect, since if you fail the 2nd saving throw it will just keep triggering.  Slight weirdness with Contagion but that spell was always super weird and it still somewhat works for it.

**Comment by mlenser** [comment]
Ya, this way has more uses:
- Ongoing saves: save has advantage until you succeed
- Spell spammed against you: You have advantage on the 2nd instance if you failed the first.

Quite nice. Not too overpowered either.
