### ISSUE TITLE
Upate Death Clutch to match Psychic Crush and Memento Mori

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#928]
https://www.kryxrpg.com/spells/death-clutch

Death Clutch should be updated to match other similar spells: 2 mana, stun for 1 round with augment for concentration, 4d6 per additional mana, etc. 

https://www.kryxrpg.com/spells/memento-mori
https://www.kryxrpg.com/spells/psychic-crush

**Comment by mlenser** [comment]
Death Clutch is a different type of spell
![image](https://user-images.githubusercontent.com/235857/129526434-1e2a2104-e36b-4cec-9d6b-d86fb8bd1c48.png)

When compared directly it looks ok.
![image](https://user-images.githubusercontent.com/235857/129526645-7b512f0c-4a11-4388-824d-6f5ad1b4185e.png)
