### ISSUE TITLE
Fuse Flesh should last for 1 round

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#929]
https://www.kryxrpg.com/spells/fuse-flesh

The spell paralyzes the target for 1 min/concentration at 3 mana. Other paralyzing spells such as Death Clutch and Memento Mori paralyze the target for only 1 round at 3 mana.

**Comment by Marcloure** [comment]
I mean, sure, Death Clutch and Memento Mori deal 1d6 damage, but I don't think 3.5 damage covers the longer duration of paralyzed.

**Comment by mlenser** [comment]
- Psychic Crush and Memento Mori now require 2 mana to augment the spell to be persistent. [#929](https://github.com/mlenser/kryx-rpg-issues/issues/929)
  - Stasis now requires 2 mana to augment the spell to be persistent. [#929](https://github.com/mlenser/kryx-rpg-issues/issues/929)
  - Fuse Flesh mana cost reduced, but it only lasts until the end of the creature’s turn. It has augments to target multiple creatures and become persistent. [#929](https://github.com/mlenser/kryx-rpg-issues/issues/929)

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/130355849-05ee187a-6648-42b0-8d9a-9c9977acbff4.png)

**Comment by Marcloure** [comment]
Is it the save difference (Will vs. Fort) that makes Fuse Flesh paralizing at 2 mana balanced with Stasis stunning at 2 mana? I mean, paralyzation is considerably stronger, I didn't know Fortitude saves have such a higher success rate.

**Comment by Marcloure** [comment]
Also, [Archon's Trumpet](https://www.kryxrpg.com/spells/archons-trumpet) augment maybe have to be adjusted then.

**Comment by itamarcu** [comment]
@mlenser minor note - Stasis's range is 10m and not 20m, so either the spreadsheet is wrong or the website is wrong.

**Comment by mlenser** [comment]
> Is it the save difference (Will vs. Fort) that makes Fuse Flesh paralizing at 2 mana balanced with Stasis stunning at 2 mana? I mean, paralyzation is considerably stronger... if that is it, then I really wasn't expecting Fortitude saves have such a higher success rate.

Fort and Will are different, especially when used each round.
## Fort:
![image](https://user-images.githubusercontent.com/235857/130428469-3c5b4422-54df-44f7-867e-dc5a98404cb7.png)

## Will:
![image](https://user-images.githubusercontent.com/235857/130428487-cd70039b-3ace-492b-b7e6-b5b03d45193e.png)
