### ISSUE TITLE
Show maneuvers/spells on a monster's view

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#93]
I'm not sure how hard it is to do this, but I think using specially the monsters's page would be much easier if we could read a spell's description by hovering the mouse over the spell. Something similar to how your Shaped Sheet works.

It would be a great advantage to be able to quickly check if a spell requires concentration or what it does without leaving the page. Sometimes I need to open 10 tabs to pick a spell from a single monsters, and that is not very practical.

**Comment by mlenser** [comment]
> Sometimes I need to open 10 tabs to pick a spell from a single monsters, and that is not very practical.

Agreed. This will lessen with system mastery, but maneuvers/spells should be viewable from the monster page as well.

**Comment by mlenser** [comment]
Some options:
- List all maneuvers/spells that a monster has below its statblock.
- Some kind of hover (must work on mobile) / popover (how would it work on mobile as a click opens the link)

**Comment by Marcloure** [comment]
I check how 5etools display spells' popover on mobile, and it doesn't. The only way I can think to do this is: you open the popover on a click, and go to the page if you click on the spell name again.

**Comment by mlenser** [comment]
D&D beyond doesn't either.

> The only way I can think to do this is: you open the popover on a click, and go to the page if you click on the spell name again.

Ya, that's the only option I ser

**Comment by mlenser** [comment]
Done
