### ISSUE TITLE
Enlarge/Reduce augment shouldn't auto affect unwilling creatures

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#931]
https://www.kryxrpg.com/spells/enlarge-reduce

Enlarge/Reduce spell augment:

> You can expend 1 additional mana so a creature you touch grows larger or smaller instead. You can target one additional creature for each additional mana expended.

Should either only affect willing creatures or require a save from unwilling creatures.

**Comment by mlenser** [comment]
Enlarge/Reduce has a saving throw for unwilling creatures.
