### ISSUE TITLE
Duergar Warlord hammer is lacking psychic damage

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#934]
https://www.kryxrpg.com/creatures/duergar-warlord

On your site:
> Psychic-Attuned Hammer. Hit: 8 (1d8 + 4) bludgeoning damage

RAW:
> Psychic-Attuned Hammer. Hit: 9 (1d10 + 4) bludgeoning damage plus 5 (1d10) psychic damage

It's fine if the hammer doesn't deal psychic damage, but then it should just be a normal hammer attack, not a psychic-attuned hammer attack.

**Comment by mlenser** [comment]
Added missing damage
