### ISSUE TITLE
Spirit Guardians should maybe be twice a sphere

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#936]
I was looking at the Power Balance table, and it seems that if we change the area of Spirit Guardians to be twice as big as normal, the damage much closely follows the expected value. Now, I think PBSphereBig hits allies as well, so I may be wrong on that.

Also, Holy Circle has a similar purpose but against spells, and it does affect a radius twice as big. Maybe it's this spell that is too big? I mean, giving everyone within 4 meters of you spell resistance seems quite a powerful effect.

**Comment by mlenser** [comment]
Spirit Guardians does slightly more damage.
