### ISSUE TITLE
Duergar Screamer image should be the Duergar Hammerer

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#938]
https://www.kryxrpg.com/creatures/duergar-screamer

Both the screamer and the hammerer are duergar trapped within machines, however the duergar screamer is stripped of its beard:
> Duergar accused of spreading gossip or plotting against their superiors are trapped within one of these devices, their beards shorn and their ongoing agony channeled into psionic energy that powers the screamer.

Also, the Duergar Hammerer has a claw and a hammer attack, while the Screamer has only a drill attack. 

Since the image cleary has a claw and a hammer, and the duergar is bearded, that is a duergar hammerer.

**Comment by mlenser** [comment]
fixed the image
