### ISSUE TITLE
Warden of the World feat suggestion

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#939]
https://www.kryxrpg.com/feats/purity-of-spirit

I suggest a copy of Purity of Spirit for Planes, but using [Planar Protection](https://www.kryxrpg.com/spells/planar-protection) instead. 

I believe you can name it better than the pretentious name I gave.

**Comment by itamarcu** [comment]
"Planar Protector" would be straightforward too.

**Comment by mlenser** [comment]
Planar Protector added to the Planes theme.
