### ISSUE TITLE
Site doesn't work on iPhone 12

### ISSUE THREAD

**Issue by blindhamsterman** [mlenser/kryx-rpg-issues#940]
The site renders correctly, but the top bar doesn't allow for scrolling through options and the dropdowns and hamburger menu do not work at all.

**Comment by mlenser** [comment]
The issue is not the navigation. It looks like there is a breaking javascript error which causes everything that uses javascript to not work.

It's hard to debug, but I'll spend a bit of time.

**Comment by mlenser** [comment]
Solved it
