### ISSUE TITLE
Adamantine should be explicitly immune to being corroded or broken

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#942]
Adamantine weapons mention: 

> Metal weapons can be made with adamantine, one of the hardest substances in existence. Such weapons are unusually effective when used to break objects and are immune to most effects that would cause it to corrode or break. If you score a critical hit against a creature with an adamantine weapon, you can break a nonmagical shield the creature is wielding or armor it is wearing. A broken shield or armor provides 2 less Defense. An adamantine weapon weighs 50% more than normal.

Armor:

> Metal armor can be made with adamantine, one of the hardest substances in existence. While you’re wearing it, the armor has Soak 1 or its Soak value increases by 1 and any critical hit against you becomes a normal hit. A suit of adamantine armor weighs 50% more than normal.

I think three changes should be made:
1. Adamantine armor should say it's immune to being corroded or broken.  This is specifically important for fighting oozes and rust monsters (who shouldn't corrode adamantine), and for the off-chance that an adamantine weapon critically hits an adamantine armor/shield (shouldn't break it).
2. "immune to most effects that would cause it to corrode or break" seems a bit unclear to me.  I would rather have it say that is immune to *all* effects that would cause it to corrode or break, with the only exceptions being spells that explicitly say so.  Alternatively, it could say "immune to most effects.... such as rust monsters or the acid rain spell."
3. Minor, but - a broken armor providing 2 less defense would be odd if the armor's defense is 11 or less.  maybe this should change?  or maybe reuse the Corroded condition, potentially under a new name?

**Comment by mlenser** [comment]
> Adamantine armor should say it's immune to being corroded or broken.

This doesn't seem to be supported by the mechanics of how these things work: https://rpg.stackexchange.com/questions/156412/do-things-made-of-adamantine-rust

> Such weapons [...] are immune to most effects that would cause it to corrode or break

Hmm, not sure where I took this from. It should probably be removed. I'll check.

**Comment by mlenser** [comment]
Adamantine weapon material cleaned up to not provide any resistance to corrosion and it now weakens armor and shield by 1.
