### ISSUE TITLE
Banishment - incapacitated

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#944]
Why does Banishment make the target incapacitated while it's there?

I think it would be neater if the creature just had to spend its turns in the empty demiplane until it returns to where it came from.  This would make it more like Wall of Force's sphere option (the old Otiluke's Resilient Sphere), making it a "time out" button of sorts, which can also be useful on allies to protect them or give them time to heal or gain buffs or lose debuffs.
The incapacitation only makes sense for a spell like Time Hop where no time passes for the creature, unless the demiplane is some sort of a magical prison.

Though, maybe this makes banishment weaker and then it'd need to be buffed, and I don't know if that's easy to do.

**Comment by mlenser** [comment]
![image](https://user-images.githubusercontent.com/235857/130359998-c6f1d9d1-3037-44f6-b4a2-8ae62bfd921b.png)

**Comment by Marcloure** [comment]
I think allowing you to cast healing spells, drink potions, and take a second wind while banished would be quite a buff. Well, it also allows enemies to do that, but enemies don't always have buffs or healing spells.

Now, there is Time Stop, which does give you extra turns at 3+ mana, but it can't be used to banish enemies or paralyzed alies.

**Comment by itamarcu** [comment]
My point is that *thematically* it doesn't make enough sense for Banishment to make the target incapacitated if it's simply sent to a harmless demiplane.

Allowing the banished target to take actions would be a bit of a nerf as the caster, but also a buff since you can cast it on allies or yourself (extra versatility may be worth it).  It already includes the built-in buff of being able to permanently banish outsiders, unlike Time Hop, so maybe it's okay?

**Comment by mlenser** [comment]
Banishment changed so the creature isn’t incapacitated while it is banished.
