### ISSUE TITLE
Warped Wings feat should require a mean to gain the wings

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#945]
Add:
> Prerequisites: You must have a magical or physical mean of gaining these wings. Speak to your GM.

To https://www.kryxrpg.com/feats/warped-wings

You can't be a normal warrior or ranger and decide to grow wings on your back on a certain day.

**Comment by mlenser** [comment]
Warped Wings now requires a magical or physical means of gaining the feat.
