### ISSUE TITLE
Hag Coven DC should be based on Wisdom or Charisma

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#946]
Hag Coven:
> For casting these spells, each hag is a 12th-level spellcaster that uses Intelligence as her spellcasting ability. The spell save Difficulty is 13 + the hag’s Intelligence, and the spell attack bonus is 5 + the hag’s Intelligence.

I'm not sure why the Coven uses intelligence as their shared spellcasting ability when the hags themselves use Charisma. Maybe they should use Wisdom or Charisma instead?

**Comment by mlenser** [comment]
![Screenshot_20210822-215238](https://user-images.githubusercontent.com/235857/130368247-33e60171-eeed-4385-9307-b039488e3aaa.png)

**Comment by Marcloure** [comment]
Yes, I know that is how it is in RAW, I'm proposing it to be changed

**Comment by mlenser** [comment]
It's easier for me to understand if you phrase it like: "RAW hags use intelligence for their coven spells, but that doesn't seem to make sense".

I'm sure there is some logic for why it was Intelligence in RAW, but Wisdom makes more sense with the Witchcrafter.

**Comment by mlenser** [comment]
Hags’ spellcasting ability changed to Wisdom as they are similar to the Witchcrafter and their coven ability also changed to Wisdom.
