### ISSUE TITLE
Annis Hag attacks are missing their reach

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#947]
https://www.kryxrpg.com/creatures/annis-hag

Her attacks don't mention their reach, which is 1 meter for all of them per RAW. 

Also, Crushing Hug is missing a period before "If the hag uses the grapple maneuver".

**Comment by mlenser** [comment]
The normal reach of 1 meter is not listed on any creature. Reach is only listed if it is higher than normal. So same as the weapons.

I've fixed the formatting.
