### ISSUE TITLE
Immolation should specify "non flammable" liquid

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#95]
(see https://marklenser.com/rpg/themes/spells/immolation)

Because pouring gasoline on a burning man is not a good way to douse the flames :)

Alternatively, it could be described as a generic "dousing the flames" option, and list some suggestions - pouring water, pouring sand, using ice magic to chill yourself, using air magic to suck the oxygen away from the flames...

**Comment by mlenser** [comment]
> Alternatively, it could be described as a generic "dousing the flames" option, and list some suggestions - pouring water, pouring sand, using ice magic to chill yourself, using air magic to suck the oxygen away from the flames...

This sounds good, could you write up some sample text that I can use? I expect to use it a lot as part of #94.

**Comment by itamarcu** [comment]
Original:

> An ignited creature can use its action to make a Reflex saving throw against your spell save DC. Additionally, a creature that can touch the ignited creature can use its action to make a Medicine check against your spell save DC. On a success, the flames are put out and the effect ends.

> If at least 3.75 liters of liquid is poured over the creature the ongoing damage is reduced to 0 for the round. If at least 7.5 liters of liquid are poured over the creature the fire is extinguished.

(or 1 gallon vs 2 gallons, in non-metric :P)

I suggest changing it to:

> An ignited creature can use its action to make a Reflex saving throw against your spell save DC. Additionally, a creature that can touch the ignited creature can use its action to make a Medicine check against your spell save DC. On a success, the flames are put out and the effect ends.

> There may be other ways to extinguish the flames (under GM discretion) - pouring water over the creature, using sand, freezing its exterior, or removing nearby oxygen.

alternatively...

> There may be other ways to extinguish the flames (under GM discretion), such as with the spells Water Jet, Sandblast, Frostbite, or Hypoxia.

**Comment by marcosPlayX** [comment]
I think your first suggestion is good enough. If we really want to make explicit that spells can work for this purpose, we can state "or by using a spell that creates such effects".

**Comment by Marcloure** [comment]
I think your first suggestion is good enough. If we really want to make explicit that spells can work for this purpose, we can state "or by using a spell that creates such effects".

(Reposting as my personal account)

**Comment by mlenser** [comment]
The flames are also extinguishable if the creature is smothered in a blanket or covered in a substance such as sand or water (~2 gallons), at the GM’s discretion.

**Comment by mlenser** [comment]
The flames are also extinguishable if oxygen is removed from the surrounding area, if the creature is smothered in a blanket or if the creature covered in a substance such as sand or water (~2 gallons), at the GM’s discretion.
