### ISSUE TITLE
Terrifying Visage is requiring 2 saves for the first tick

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#951]
https://www.kryxrpg.com/spells/terrifying-visage

When you cast the spell, the creature makes a Will save. On the start of each of its turns, it makes another save. It should only make the save at the start of each of its turns. It's how the spreadsheet values the spell as well.

**Comment by mlenser** [comment]
Terrifying Visage reworded to not require two saving throws.
