### ISSUE TITLE
Write guidelines for creating custom monsters

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#956]
I think we could have a page or note somewhere about how to customize or make new creatures using this system's rules. I'm asking for this specially because I'm not sure how many save proficiencies and soak (given their armor) a creature of a certain Challenge should have.

**Comment by mlenser** [comment]
Closing in favor of #958.

For saving throws: think in terms of each "bonus" being capable or two bonuses being proficient. Each creature should have 2 "bonuses", gaining 1 more at 5, 13, 17, and 25 (fully proficient in all 3)

For soak: it's either based on the armor they wear or their natural armor.
Armor: For plate add 1 to the Soak at challenge 6 and 10. For scale add 1 to the Soak at challenge 8 and 12. For chain add 1 to the Soak at challenge 10 and 14. "Add 1" means 0+1=1 or 1+1=2.
Natural armor: divide the natural armor bonus by 3 and round to the nearest full number.
