### ISSUE TITLE
Stealth behind full cover should grant greater bonus

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#957]
Currently, half cover grants +2 to Stealth, 3/4 cover grants +4 to Stealth, but full cover grants no bonus.

Maybe it should be +2 behind 3/4 cover and +4 behind full cover, since you can't hide behind half cover anyway?

**Comment by mlenser** [comment]
The benefit granted by cover should be the same as Defense and Reflex.

**Comment by mlenser** [comment]
I've adjusted half cover and three-quarters cover to only provide Stealth bonus "to avoid being seen". Total cover already amkes it so you can't be seen.

**Comment by mlenser** [comment]
Half cover and three-quarters cover only provide Stealth bonus “to avoid being seen”. Total cover already makes it so you can’t be seen.
