### ISSUE TITLE
Variant durations (e.g. 1 minute/mana) should be clarified

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#96]
(e.g. https://marklenser.com/rpg/themes/spells/immolation)

A lot of abilities have their duration as 10 minute/mana, 1 hour/mana, etc.

The Powers rules (https://marklenser.com/rpg/themes/powers) should clarify what this means.

It is unclear if this implies you can augment the spell to specifically increase its duration, or if this implies that augmenting a spell for any reason (e.g. to deal more damage or change its area of effect) also increases its duration.

**Comment by mlenser** [comment]
> augmenting a spell for any reason (e.g. to deal more damage or change its area of effect) also increases its duration.

This is the correct interpretation. I'll clarify.

**Comment by mlenser** [comment]
If a concoction, maneuver, or spell specifies that its duration lasts an amount per resource used (1 minute/mana for example), the duration is automatically increased the amount listed based on the amount of resources (catalysts, mana, psi, stamina dice) used.
