### ISSUE TITLE
Increase Illusory Dragon damage

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#960]
https://www.kryxrpg.com/spells/illusory-dragon

So, one of my players noticed that this spell is a bit short on damage with its 4 mana augment. At 2 mana it already causes fear, so you are augmenting the spell to gain 3d6 repeatable damage, which doesn't sound worth your 4 mana spell. So I went and checked on the speadsheet, and indeed its damage value is 10 fewer than expected.

If we increase the damage to 4d6 at 4 mana, the augment turns green, but when augmented to 5 mana it goes a bit above some spells (although still below others). We could either leave the 5 mana spell dealing a bit more damage as other spells do, or just remove the damage augment, which puts the 5 mana augment at a perfect spot as well.

**Comment by mlenser** [comment]
> its damage value is 10 fewer than expected.

It's 6.8 fewer than expected, or about 88% of expected. Most cones are below expectation at 4 mana due to cones not scaling linearly due to the range changing at 3 and 5 mana.

**Comment by Marcloure** [comment]
The spell only deals damage at 4 mana, so I think it should be balanced to be good at that level. Alternatively, the damage augment could be decreased to 3 mana.

**Comment by mlenser** [comment]
The dragon doesn't do damage until 4 mana as illusions causing real impact is thematically a high mana effect.

**Comment by mlenser** [comment]
Illusory Dragon augment damage increased.
