### ISSUE TITLE
Black Tentacles seems weak compared to Web

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#962]
https://www.kryxrpg.com/spells/web

https://www.kryxrpg.com/spells/black-tentacles

Web restrains in a sphere double the area at 2 mana. Black Tentacles restrains in a normal sphere but deals 1d6 (2d6 if already restrained) at 3 mana. I think Web is much better than Black Tentacles.

**Comment by mlenser** [comment]
Web needs anchor points or it collapses upon it self.

Black Tentacles is meant to lock down a small area and whack the people in it. Web is meant to lock down a large area, but with limited parameters requiring anchor points.

Seems fair.

**Comment by Marcloure** [comment]
I think it would be fair if both were 2 mana, so you have a choice between damage or area. Now, I don't think the extra 1 mana and reduced radius is worth 1d6/2d6 damage per round.

**Comment by mlenser** [comment]
Persistent damage spells are quite valuable. If you look at all of them, they all do relatively lower damage.

It seems that you are valuing persistent damage less than the sheet does.

**Comment by mlenser** [comment]
The spells are quite similar to RAW where Web is 2nd level and and Black Tentacles is 4th level.

https://www.dndbeyond.com/spells/web
https://www.dndbeyond.com/spells/black-tentacles

**Comment by Marcloure** [comment]
> It seems that you are valuing persistent damage less than the sheet does.

Yeah, when the persistent damage is in a fixed area, I think I do. Black Tentacles for instance, if half the targets succeed on the initial save, and then half of the ones that fail succeed on escaping, and most of them leave the area, the damage is hardly the main benefit of this spell. Even the ones who remain inside will need another round to take 3d6 damage.

> The spells are quite similar to RAW where Web is 2nd level and and Black Tentacles is 4th level.

Maybe web should be a normal sized area then? Currently I think having a very large difficult terrain area is much better than this one that causes a bit of damage in a smaller area.

**Comment by mlenser** [comment]
- Avascular Mass and Web can now be broken by a nearby creature as other spells of this type can be. [#962](https://github.com/mlenser/kryx-rpg-issues/issues/962)
  - Web is now a normal sphere instead of being twice as big as normal as it matches Avascular Mass and is more in line with other spells. [#962](https://github.com/mlenser/kryx-rpg-issues/issues/962)
