### ISSUE TITLE
Issue with granting disadvantage after seeing the roll

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#963]
I found an issue with the updated spells and effects that allow you to grant dis/advantage to a roll after you see the result. See:

- If a creature rolled a 6 and a 8 on 2d10, and you grant it disadvantage, it will roll another d10 and use the two smallest values. So far, so good. 
- However, if the creature has advantage before the roll, it will roll three dice, let's suppose a 2, 7, 10. Advantage would make that a 17. Then someone casts Twist Fate, removing the advantage. That roll will now be 9 (assuming canceling advantage would make the creature pick its first 2 dice)
- Same situation as above, but the creature rolled 7, 10, and 2. Canceling the advantage would bring no benefit, since removing the last die, a 2, doesn't do anything.

Issue is, since the caster sees the roll, they will know exactly how much change removing the advantage will bring. Same is true with adding advantage to cancel disadvantage. Everyone will know which die will be used after the disadvantage is canceled.

More examples that happened in play (using d20, but the results are the same):

Since you use the spell after you see the roll, you know that canceling advantage here is useless:
![image](https://user-images.githubusercontent.com/29084710/132995570-b17f278b-c9c7-4744-8e79-3b243bde3d78.png)

And that canceling advantage here would be very effective:
![image](https://user-images.githubusercontent.com/29084710/132995621-83143089-e3e1-4b8b-9afe-4690b68f8118.png)

**Comment by mlenser** [comment]
The dice removed should likely be random.

**Comment by Marcloure** [comment]
Random is still a bit wacky, since you still know the value of the second die. So, either you know canceling advantage won't have an impact if both die pass, or you have 50% chance of succeeding and 50% of failing on 1d20 (not sure the percentage on 2d10, but the exact value isn't the point). Against a standard roll, you have no way to judge your chances of success based on the second die, since you'll only see it later.

**Comment by mlenser** [comment]
I have added the following wording to each case:
> If the roll already has advantage or disadvantage, you cannot apply another instance of advantage or disadvantage and you must use this before the roll to cancel out any advantage or disadvantage.

**Comment by mlenser** [comment]
Maneuvers, Spells, and Verses that can give a roll advantage or disadvantage as a reaction has been adjusted to specify when they can be used.
