### ISSUE TITLE
Uncanny Luck is worse than Lucky

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#964]
> https://www.kryxrpg.com/feats/uncanny-luck

First, the description is a bit obfuscating about what this feat really does. See, it says the GM rolls 2 dice in secret and you can use the highest of them on any one roll you make. In effect, this is the same to say "you gain advantage on a roll", since you don't know beforehand what is the value of that die.

Thing is, [Lucky](https://www.kryxrpg.com/feats/lucky) does exactly that but better, since it's twice per long rest.

**Comment by mlenser** [comment]
Uncanny Luck is a less powerful lucky. It is playing the odds that one of the rolls is high.

Lucky or Uncanny Luck should be modified so it has purpose, but it is quite a thematic feat.

**Comment by mlenser** [comment]
Uncanny Luck can now be selected multiple time to gain additional rolls to choose from. and it can now be used after the roll.

**Comment by mlenser** [comment]
Uncanny Luck is different from Lucky in that Lucky can be used to replace 1 die. Uncanny Luck can be used to replace both dice. So if you roll two low dice then Uncanny Luck would be the better option (most likely).
