### ISSUE TITLE
The Hexblade archetype's power source for Witchcrafter seems to be bugged on the kryx webpage.

### ISSUE THREAD

**Issue by Calibanana** [mlenser/kryx-rpg-issues#966]
On the kryx webpage for the Witchcrafter, the Hexblade archetype's information seems to currently be bugged. It does not display a power source, and instead says, 'You can learn spells from themes you know in the null power source.' This seems like it is incorrect.

The link can be found here: https://www.kryxrpg.com/character/classes/witchcrafter

Follow these steps to reproduce this:
1. Go to https://www.kryxrpg.com/character/classes/witchcrafter
2. Click on Hexblade
3. Scroll down to 'The Old Ways,' and look at 'Power Source'
4. See that the first sentence says 'You can learn spells from themes you know in the null power source.'

I believe this is simply a matter of an HTML error, and should be easily fixable.

**Comment by mlenser** [comment]
Thanks for pointing out the issue with such a detailed report!

This issue will be fixed in a few minutes when the site deploys.
