### ISSUE TITLE
Fluid Flootwork should be a 2nd level feat, and updated

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#968]
https://www.kryxrpg.com/feats/fluid-footwork

First, the conversion rates on this feat are wrong. It should use the same text from the Naturalist's Land's Stride.

Second, the feat is rather situational, specially considering that the same theme it is in has another feat that grants +2 meters of speed. A character with 7 meters of speed walking though difficult terrain walks the same as a character with 5 meters of speed walking at 3/4ths the speed. Also, +2 meters to speed is always on.

Fluid Footwork is only a better option if you have 7 meters of base speed, but even then it gives you only 1 additional meter on difficult terrain for 2 fewer meters on much more common normal terrain. Well, this if the difficult terrain is more than 5 meters long. 

For this reason, I believe this feat should just be a 2nd level feat.

**Comment by mlenser** [comment]
It can be the same benefit as Land’s Stride: +1 meter speed and three-fourths speed instead of half speed

**Comment by mlenser** [comment]
- **Classes**
  - **Naturalist**
    - Natural Explorer feature now allows you to move three-fourths speed instead of half speed through nonmagical difficult terrain. It is removed from Land’s Stride which still increases your speed and is moved to 3rd level to match the Warrior’s Fast Movement feature. [#968](https://github.com/mlenser/kryx-rpg-issues/issues/968)
- **Themes**
  - Fluid Footwork changed to 2nd level. [#968](https://github.com/mlenser/kryx-rpg-issues/issues/968)
