### ISSUE TITLE
Consistent pronouns for player characters

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#97]
It's a remnant from the existing 5e rules, that every time a player or a player's character is mentioned, the rules use "he or she", "his or her", "him or her". While reading through the Kryx RPG rules I noticed that many of the new rules written use singular "they", instead (a decision I agree with). However, sometimes it's still "he or she", and sometimes it's even "it", a pronoun usually reserved to non-player creatures.

For example, the following quote from https://marklenser.com/rpg/themes/powers is all over the place:

> Before a character can cast a spell, **he or she** must have extensive training with the spell and have it firmly fixed in mind. The number of spells a character can have fixed in mind at any given time depends on the character’s level. Each class details how many spells a character can learn. Whenever a character learns a new spell, the spell must be from a theme **they** already know.

> Whenever a character gains a level, **it** can choose one of the spells it knows and replace it with another spell from a theme it knows.

For consistency's sake, we should go through all of these pronouns and choose a single standard. I vote for singular they, but "he or she" would at least be consistent with the usual rules.

Also, note that this should have no effect on sentences that refer to a specific example of a character (e.g. "Spark, a 3rd-level Alchemist").

**Comment by mlenser** [comment]
I agree. `they` is the best option I believe.

`it` cases will be super hard to find...
