### ISSUE TITLE
Harpies shouldn't affect other harpies with their song

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#971]
https://www.kryxrpg.com/creatures/harpy

Harpies' Luring Song affect humanoids and giants, but since harpies became humanoids now, they affect other harpies too.

Maybe harpies should actually be fey? They do have many unseelie fairy qualities: they lure creatures with song to feed off them, they often ally themselves with hags and participate in occult rituals, many fantasy worlds have fables and myths that portrait harpies with a certain mystery, like mariner's fairy stories.

**Comment by mlenser** [comment]
Harpies are correct as humanoids. If you need another example of it, PF2e does it that way: <https://2e.aonprd.com/Monsters.aspx?ID=258>

**Comment by mlenser** [comment]
Harpies song fixed
