### ISSUE TITLE
Change saving throws to only deal half if the save fails by 4 or less?

### ISSUE THREAD

**Issue by mlenser** [mlenser/kryx-rpg-issues#972]

**Comment by Marcloure** [comment]
I am not sure this is a perfectly good idea. First, it's nice to have some differentiation between saving throws and attacks if they are to be different. Second, this would mainly increase the damage of spells and breath weapons on a hit, which I think are sufficiently high currently.

**Comment by mlenser** [comment]
> Second, this would mainly increase the damage of spells and breath weapons on a hit, which I think are sufficiently high currently.

It would be accompanied by an increase in the difficulty to account for this.

**Comment by mlenser** [comment]
The degrees of success system is sufficient for this. https://github.com/mlenser/kryx-rpg-issues/issues/961
