### ISSUE TITLE
Using skills for initiative weights against NPCs

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#974]
As PCs are proficient in a greater variety of skills than NPCs, using skills for initiative ends up granting the PCs a large proficiency bonus over NPCs. For instance, very few NPCs are proficient in Nimbleness or Athletics, while most PCs can be proficient in at least one of the two. At my table for instance, many combat situations end up with the players rolling for initiative with +10 from Nimbleness or Stealth while NPCs roll with +0 to +5 from Nimbleness.

**Comment by mlenser** [comment]
> At my table for instance, many combat situations end up with the players rolling for initiative with +10

This is only possible with PCs at 17th level or higher as they would need 5 aptitude bonus and 5 in the relevant ability.

___________________

NPCs on average generally have fairly high Brawn, mediocre Nimbleness, fairly high Perception, and Stealth would be high in cases where they use them.

In most cases NPCs will not be using Nimbleness, but in those cases they'd be slower to react as expected.

____________

Otherwise, this will be handled via #918

**Comment by Marcloure** [comment]
> This is only possible with PCs at 17th level or higher as they would need 5 aptitude bonus and 5 in the relevant ability.

Yes, sorry, we are still using 2–6 pb range, since we only apply some some updates when we level up.

---

> NPCs on average generally have fairly high Brawn, mediocre Nimbleness, fairly high Perception

I believe Brawn is harder for NPCs to use as initiative, since they are usually the ones being invaded. I suppose my main issue is mostly with Nimbleness, which few creatures are proficient with but is still the most used skill to determine initiative. If I understood the rules correctly, even in a situation where a player is rolling Stealth and another is rolling Nimbleness, most of the time the NPCs will be rolling Nimbleness since its a matter of acting faster, not about noticing the ones hiding.

**Comment by mlenser** [comment]
> I suppose my main issue is mostly with Nimbleness, [...] it is still the most used skill to determine initiative. 

It should not be. The examples provided should provide enough common cases that Nimbleness should be only be used sometimes.

Even then though, Dex was RAW so the only difference here is proficiency. If creatures are not nimble, then they should be slower.

> If I understood the rules correctly, even in a situation where a player is rolling Stealth and another is rolling Nimbleness, most of the time the NPCs will be rolling Nimbleness since its a matter of acting faster, not about noticing the ones hiding.

If the player is rolling Stealth then Perception would be the right choice for someone to notice them.

**Comment by Marcloure** [comment]
> the player is rolling Stealth then Perception would be the right choice for someone to notice them.

But what if some players are using Nimbleness or Athletics and others are using Stealth? I suppose a NPC would use Nimbleness for initiative, since perceiving the stealthy character first wouldn't help against the ones that running straight at them, no?

**Comment by mlenser** [comment]
> But what if some players are using Nimbleness or Athletics and others are using Stealth? I suppose a NPC would use Nimbleness for initiative, since perceiving the stealthy character first wouldn't help against the ones that running straight at them, no?

Can you describe the full scenario?

This scenario sounds similar?
![image](https://user-images.githubusercontent.com/235857/134780306-9c71586b-5efc-412f-9bea-65b5c75587cf.png)

For a character to be using stealth they need to have some cover or avoid being seen so if such a creature is high on the initiative, they'd have to use up movement to get through a door for example.

**Comment by Marcloure** [comment]
> This scenario sounds similar?

Yes, it's quite similar to that scenario. And as we can see in the example, the initiators choose their best skills to start the combat, while the defenders use the ones that make most sense against those skills. In many cases, "reacting faster" (Nimbleness) is the most fitting defensive option (in that example's case I would allow the hobgoblins to use Perception as initiative to notice the approaching threat). Although it makes sense for the initiators to have a better chance of getting the initiative, the difference can be very large.

**Comment by mlenser** [comment]
> In many cases, "reacting faster" (Nimbleness) is the most fitting defensive option

As I wrote above, this should not be the case. Nimbleness should essentially only be used when all parties are aware of eachother and aware of the upcoming battle. That isn't a common scenario. Stealth vs Perception should be far more common. Other cases like Deception vs Insight could be common in cities.

> Although it makes sense for the initiators to have a better chance of getting the initiative, the difference can be very large.

There is no surprise round. Using a skill with which you are proficient makes you more likely to go first if the other creatures aren't proficient in their side of things. That is to be expected.

**Comment by mlenser** [comment]
> in that example's case I would allow the hobgoblins to use Perception as initiative to notice the approaching threat

I have updated the example:
![image](https://user-images.githubusercontent.com/235857/134798561-22eaf186-e28a-442b-99e0-5990012a2ca9.png)

The scenario determines which skill to use. It should never be a choice after the events have already started. The choice is in how to initiate the combat which then determines which skill to use.

**Comment by mlenser** [comment]
Conclusion: It is intended that creatures who initiate combat have the option of initiating combat using their most advantageous skills. There is no surprise round so this covers that one side is more ready than the other and is 100% intended.

I assume the way in which you play is somehow heavily weighting initiative to use Nimbleness when it should be a rare event. Feel free to raise some scenarios to discuss so we can understand what is happening. Maybe there is something to adjust.

**Comment by Marcloure** [comment]
> There is no surprise round 

I did not notice surprise was removed. That being the case, I agree it's fine that the initiators can have choose their favored method of approach.
