### ISSUE TITLE
Skill checks can be quite unfair

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#975]
I will take Brawn as an example because it's the most unfair skill for this case.

> **_Grappple._** [...make] a Brawn check opposed by the target’s passive Brawn or passive Nimbleness.

This means that a character with +7 or +8 in Brawn can almost auto succeed on grappling a character with +0 or +1 in Brawn or Nimbleness. If you have advantage because of Rage or a spell such as enlarge, it's pretty much impossible to not get grappled.

Also, if you are grappled by a creature with +7 or +8 Brawn and you are trying to escape with a +3 bonus, your chances are quite slim as well, and can be literally impossible to succeed if the opposing creature has advantage.

My main concern is auto succeeding, but I think the chances could also be a bit tighter by making opposed checks. Some comparisons:

**Grappling (+7 to grapple vs. +3 to escape):**
https://anydice.com/program/247b3

**Escaping (+7 to grapple vs. +3 to escape):**
https://anydice.com/program/247b4

**Comment by mlenser** [comment]
Some notes:
- Grapple is only against creatures up to 1 size larger. I've just adjusted it to be in the larger creature's favor.
- Grapple is against the target's passive Brawn _or_ Nimbleness. Most (~80%) creatures should have one or the other. 
- Being proficient and using your highest ability vs a creature who isn't proficient and isn't using their highest ability will likely result in success. This is purposeful and is also true in RAW.
- The system is meant for one side to roll and the other side to be a static number, purposefully. There were some blogs that I referenced a while back for why this is the case. We could allow for all sides to roll as an option, but the default option is currently this.

**Comment by mlenser** [comment]
Conclusion: This is how it works in RAW and how it is intended to work. Some skills should be added to some creatures (#918) though.

**Comment by Marcloure** [comment]
> Being proficient and using your highest ability vs a creature who isn't proficient and isn't using their highest ability will likely result in success.

Sure, that obivously makes sense, but I don't think it should be an auto-success. For instance, a Behir grappling or tripping a character with +3 Dex is an auto-success for the Behir (+9 Brawn, and the target has -3 passive Nimbleness, so 2d10+9 vs. Difficulty 11). The same character trying to escape the Behir has 10% chance of success, so it's hardly worth using an action to escape this situation.  Trying to escape using roll vs. roll increases the chance to 17.6%, which isn't great still, but it's 1 in 6 chances. It gets even worse when you get to creatures with +13 Brawn, when it's literally impossible to escape with just a +3 or +4.

It kinda makes it almost obligatory for characters to have either Nimbleness or Brawn, since otherwise they can be grappled by a dragon or tripped by a giant and have abusolutely no answer to that.

**Comment by mlenser** [comment]
> Sure, that obivously makes sense, but I don't think it should be an auto-success.

Nothing is an auto-success in this system or in RAW 5e. However, there are plenty of cases where Brawn or even attacking have very high chances of succeeding in both. Zombies, for example, are super easy to hit. Most lower challenge NPCs are super easy to grapple/shove/whatever.

RAW at level 1 a Fighter can have 1d20 + prof (2) + ability (3) = 1d20 + 5 vs 1d20 which is a 73.75% chance (https://anydice.com/program/247e9). A raging barbarian can have advantage which is a 87.31% chance (https://anydice.com/program/247ea).

> For instance, a Behir grappling or tripping a character with +3 Dex is an auto-success for the Behir (+9 Brawn, and the target has -3 passive Nimbleness, so 2d10+9 vs. Difficulty 11). 

The target doesn't have -3 passive Nimbleness. Them trying to escape is 2d10 + 3 >= 20 which is a 10% chance (https://anydice.com/program/247eb), ya. If RAW monsters actually had skills then the Behir would have +10 Brawn which would be a 22.75% chance of escape (https://anydice.com/program/247ec) with the main difference coming from 1d20 vs 2d10.
With 2d10, creatures who should succeed do so more often. That's a feature, not a bug.

> It kinda makes it almost obligatory for characters to have either Nimbleness or Brawn, since otherwise they can be grappled by a dragon or tripped by a giant and have abusolutely no answer to that.

Creatures and characters should have brawn or nimbleness, ya. But it really isn't "necessary" by any means. Grapple is just speed 0. Creatures can still attack, cast spells, teleport out, use maneuvers, etc.

**Comment by Marcloure** [comment]
> Nothing is an auto-success in this system or in RAW 5e.

Well, of course there is auto-success. A creature with +13 to Brawn grappling or tripping another with +4 to Nimbleness is an auto-success (2d10+13 vs. Difficulty 15, _if_ same sized).

> The target doesn't have -3 passive Nimbleness

Why not? The Behir is Huge and PCs are Larger or smaller, so they do have disadvantage on their passive skill (so -3) to resist being grappled.

> Grapple is just speed 0.

That is true for garpple, but Brawn can also be used to trip, which can be devastating. You can also prone+grapple, which is basically a restraint the target can never escape if the Difficulty is high enough.

> the same as RAW if monsters actually had the skills that they should have

RAW uses opposed check, so even if you have a +0 and are facing a creature with +15 to grapple, you still have some chance of not being grappled or of escaping.

Now, if that is intended, then I guess there isn't much to be done. I particularly prefer to use opposed checks so that auto-successes and auto-fails can never ever occur.

**Comment by mlenser** [comment]
> Why not? The Behir is Huge and PCs are Larger or smaller, so they do have disadvantage on their passive skill (so -3) to resist being grappled.

-3 only applies to Brawn, not Nimbleness.

> That is true for garpple, but Brawn can also be used to trip, which can be devastating. You can also prone+grapple, which is basically a restraint the target can never escape if the Difficulty is high enough.

Trip can be effective, but the creature could trip just as well in RAW. And if you find cases like Behir where it can't then I believe those are mostly oversights where 5e monsters largely don't have any skills. If they did, the issue you describe would be there as well.

Grapple + prone would take two actions, of which the creature is doing nothing else. Effective in large groups, but requires lots of coordination and your team not helping. Totally fine.

> RAW uses opposed check, so even if you have a +0 and are facing a creature with +15 to grapple, you still have some chance of not being grappled or of escaping.

Opposed checks have very little impact on the result. If by "some chance" you mean the 5% crit, then sure. That's "auto fail" still.

Regarding opposed checks:

> The system is meant for one side to roll and the other side to be a static number, purposefully. There were some blogs that I referenced a while back for why this is the case. We could allow for all sides to roll as an option, but the default option is currently this.

> I particularly prefer to use opposed checks so that auto-successes and auto-fails can never occur (unless it's like, -5 against +15).

5% is effectively auto fail. You roll an extra roll and complicate things with ties for almost no benefit.
Now, if the whole system was rolling all sides then this would make sense, but the standard stream-lined system shouldn't have both sides roll.
