### ISSUE TITLE
Area damage maneuvers are missing critical failures and success

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#976]
https://www.kryxrpg.com/maneuvers/slice-through

Maneuvers like Slice Through and Hammer Spin should deal double damage on a critical failure on the saving throw, and no damage on a critical success.

**Comment by mlenser** [comment]
Chain Sweep, Fling, Hammer Spin, Hammer Through, Slice Through, Swipe, Throw, and Whirling Blade all are updated to use degrees of success.
