### ISSUE TITLE
Temporal Regression should have a heal limit

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#979]
https://www.kryxrpg.com/spells/temporal-regression

Issue is, since you regain all life lost snice your previous turn, the spell effectiveness grows naturally as you level up without requiring more mana. When you get it at 5th level, you are taking 20–25 damage per turn, but when you reach higher levels, you are taking 60+ damage per turn. 

Picture this: a high level caster casts immolation with 4 mana on a target. It takes some 65 damage and is burning 12. The target uses temporal regression with 2 mana and completely reverts both the initial damage and the burning condition. 

Another example: at 5th level, a gladiator has a DPR of 22. A pit fiend has a DPR of 122. Both are equally canceled by a 2 mana temporal regression. It's extremelly powerful that you can take 122 damage and revert all of it (and any condition that may come with it) with just 2 mana.

**My suggestion** is to put a cap of 20 health regained per mana, so up to 40 health regained at 2 mana, 60 at 3 mana, 80 at 4 mana, and maybe uncapped at 5 mana.

**Comment by mlenser** [comment]
> When you get it at 5th level, you are taking 20–25 damage per turn, but when you reach higher levels, you are taking 60+ damage per turn.

This makes several assumptions in the monsters you're facing and that you'd be targeted by them all. As a percentage of your total health things stay fairly similar. As a pure number count, you're likely taking more damage at higher tiers.

This spell isn't meant to provide pure numbers. It is meant to open ended to prevent broken bones, falling, significant damage, etc.


> Picture this: a high level caster casts immolation with 4 mana on a target. It takes some 65 damage and is burning 12. The target uses temporal regression with 2 mana and completely reverts both the initial damage and the burning condition.

Yup, it's a very strong spell. I'm not sure if it can be scaled to all tiers. Maybe it should be 3 mana?

**Comment by Marcloure** [comment]
> Maybe it should be 3 mana?

I think 3 is nice, since then to cast on someone else it would be a 4 mana spell, and you can't do that multiple times. Currently, if your ally didn't straight up die, you can just cast this spell and revert all damage and conditions again and again, which is much better than any healing.

**Comment by mlenser** [comment]
Temporal Regression augment changed to only target another creature, not yourself and it. It also has another augment to regress two creatures or objects.

**Comment by mlenser** [comment]
Temporal Regression limited to heal a specific maximum amount of health.
