### ISSUE TITLE
"gold" should be replaced with "silver"

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#98]
in https://marklenser.com/rpg/equipment, "Starting Equipment":

> When you create your character, you receive equipment based on a combination of your class and background. Alternatively, you can start with a number of gold pieces based on your class and spend them on items from the lists in this section. See the Starting Wealth by Class table to determine how much gold you have to spend.

Also, a few spells require material components with value in gp (e.g. Astral Projection, Augury, Consult the Spirits), which should probably be corrected. (I ctrl+F'd for "gp")

**Comment by mlenser** [comment]
You found the 3 spells that I missed :P
