### ISSUE TITLE
mutant disciplines give themes that the mutant already has

### ISSUE THREAD

**Issue by UnlcukyHub** [mlenser/kryx-rpg-issues#987]
on the mutants disciplines section both 'fleshwarper' and 'enhancer' give things the mutant already has, i would reccomend either letting them to take a theme or their choice, theme replace, or a thing that says "you get two free something or other from metabolism/fleshwarp"

**Comment by Marcloure** [comment]
That is just how the class/archetype are structured, it happens in a lot of classes. In these cases, you just don't pick the theme your archetype already grants.

**Comment by mlenser** [comment]
Fixed a bug that showed a theme on the initial themes and the subclass themes if that theme was the only possible choice for the subclass.
