### ISSUE TITLE
Update to the Animal Companion feat regarding resources, limits, and control.

### ISSUE THREAD

**Issue by Calibanana** [mlenser/kryx-rpg-issues#988]
Updating how the Animal Companion feat calculates the maximum level of the companion, what resources are able to be used, and possibly adjusting the wording about how companions are commanded.

### Resources used
First as discussed in Discord, it seems the animal companion feat is currently lacking some potentially helpful resources. Notably while the feat only requires you be capable with Wilderness to obtain the feat, there is no requirement that you also have mana to take the feat. The feat however requires mana, meaning it can currently be taken by anyone capable with Wilderness regardless of any spellcasting abilities. It may be a good idea to instead update this feat to allow the use of Psi or Stamina to pay for the cost, but at a 2:1 ratio compared to mana.

### Variations between full and half casters
Second, at the moment this feat heavily favors pure spellcasters due to the companion being augmented up to your mana limit. The result is that a 14th-level Naturalist Druid is able to have a CR 7 Large Companion with 100+ health and a +6 to hit, while a 14th-level Naturalist Ranger is only able to have a CR 3 Small Companion with about 40 health and a +3 to hit. It may be a good idea to instead change this limit to be equal to your aptitude bonus, that way all characters capable of summoning a companion can benefit equally from the companion.

### Controlling the companion
Finally the paragraph talking about controlling your companion ends with the sentence "Once given an order, the creature continues to follow it until its task is complete." This wording implies that you can give a general command to your companion, such as attack all enemies, and they will continue to do so without you needing to use your action on subsequent turns to keep it going. It was mentioned that this was how the feat was originally intended to function, so it may not need to be changed. If this is no longer the case and the character does have to issue a command each turn, the feat's wording will need to be updated to reflect that a companion cannot continue to follow a task.

Similar wording to above exists in both the Homunculus and Eidolon feats, which may also need to be updated should the Animal Companion feat be updated.

**Comment by mlenser** [comment]
- **Feats**
  - Animal Companion, Eidolon, and Homunculus updated so the cost to revive the creature is 10 sp for each mana limit. [#988](https://github.com/mlenser/kryx-rpg-issues/issues/988)
  - Animal Companion updated so it requires mana or psi. [#988](https://github.com/mlenser/kryx-rpg-issues/issues/988)
  - Animal Companion, Eidolon, and Homunculus updated so maximum catalysts, mana, or psi is equal to your Aptitude Bonus. [#988](https://github.com/mlenser/kryx-rpg-issues/issues/988)


I've split the controlling to [Consider removing the action cost to maintain spells and companions](https://github.com/mlenser/kryx-rpg-issues/issues/993) and Ranger with no mana to [Consider allowing animal companion without mana](https://github.com/mlenser/kryx-rpg-issues/issues/992)
