### ISSUE TITLE
Wild Magic Sphere centered on point should not move with you

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#99]
Just a minor fix for this - https://marklenser.com/rpg/themes/spells/wild-magic-sphere

> As an action, an invisible sphere of wild magic surrounds you. Until the spell ends, the sphere moves with you, centered on you.
> You can expend 1 additional mana to cast the spell centered on a point within 120 feet.

The second statement should probably also include something like: "It remains there for the duration, instead of moving with you."

**Comment by mlenser** [comment]
Conversion starts to round to the nearest whole number after 10 and to the nearest 5 after 20... booo

**Comment by itamarcu** [comment]
I think you commented on the wrong ticket, and meant to comment on this one: https://github.com/mlenser/kryx-rpg-issues/issues/100

:P
