### ISSUE TITLE
It's unclear what being capable in armor means

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#991]
The [Armored](https://www.kryxrpg.com/feats/armored) feat and the Armored trait on every martial class states that the character becomes proficient with armor instead of capable at the 5th level. It isn't clear what being capable with armor means however, since armor already only adds half aptitude bonus, and they have a minimum of 1 aptitude bonus added to it.

Maybe it means that you don't add the aptitude bonus to your Defense until the 5th level? Isn't that the same of just removing the minimum aptitude bonus to Defense?

**Comment by mlenser** [comment]
- **Classes**
  - Armor is never proficient.
- **Equipment**
  - **Armor**
    - Armor only adds half your Aptitude Bonus if you are capable.
- **Feats**
  - Armored: Armor is never proficient.
