### ISSUE TITLE
Metamagic link does not show the metamagic options.

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#995]
In the list of general feats, Metamagic shows the list of options available but in links pointing to metamagic from anywhere else, those options are not visible.

[metamagic](https://www.kryxrpg.com/character/feats/metamagic
)

**Comment by mlenser** [comment]
Thanks for the report! It's fixed now.

**Comment by Daniel-Soham** [comment]
No problem, thanks for fixing it!
