### ISSUE TITLE
It pronoun used instead of them under martial weapons 

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#997]
**Describe the bug**
Under the martial weapons section of the weapons page:
A character might be self-taught or it might have had a commander, elder, or master teach **it** how to effectively wield martial weapons.

It should be replaced with them as per the grammar in the rest of the page.

**Link**
https://www.kryxrpg.com/equipment/weapons

**Comment by mlenser** [comment]
Fixed in a few places

**Comment by Daniel-Soham** [comment]
Great, keep up the good work!
