### ISSUE TITLE
Misplaced text under shocked condition 

### ISSUE THREAD

**Issue by Daniel-Soham** [mlenser/kryx-rpg-issues#999]
**Describe the bug**
Under the shocked condition is the following text. It looks like it got pasted from hasted.

¹ replaces all previous speed increases.

**Link**
https://www.kryxrpg.com/rules/conditions#shocked

**Comment by mlenser** [comment]
Ah, shocked was a condition I was thinking of adding, but didn't. It was in my local files which went live as I changed the way I release code a bit ago. I'll remove the shocked condition.
